### PR TITLE
Start process of better client-side file locations

### PR DESCRIPTION
**Pull request by robertdown**
Also remove treeview1.3 as it is unused

### CODE REVIEW

**Comment by robertdown** [comment]
My IDE is set to trim whitespace on end of lines. Should I try to go back and undo that?

**Comment by Wakie87** [comment]
Shouldn't matter too much, specially if we start following PSR-1 and PSR-2. It would get done eventually.

**Comment by robertdown** [comment]
We just don't like mixing whitespace trims with actual code changes. I agree, white space will go away... I look forward to watching this happen

**Comment by sunsetsystems** [comment]
What is the reasoning behind choosing directory names "public" and "assets"?

**Comment by Wakie87** [comment]
@sunsetsystems  When we introduce composer and autoloading (Which is all part of modernizing the app) Anything outside of /public/ i.e: all your business code will be secure from direct URL access. All your publicly available asset files should be here, CSS, JS, Images.

As for assets, we can change this later if needed.

**Comment by bradymiller** [comment]
Hi,

The path really doesn't matter that much, since it will be always easy to change it via Robert's 2 changes to .bowerrc and interface/globals . This is because we will force using of $GLOBALS['assets_static_relative'] whenever use an asset in the codebase. So, we shouldn't be stressing too much over the best path.

Did a lot of work with bower over the last week. See the forum here regarding that:
https://sourceforge.net/p/openemr/discussion/202506/thread/d4ec2b8b/

Going to bring in the work describes there that we need to incorporate the version of the package into the path and have added 2 additional assets which Rod brought in a recent commit.

I'll then integrate Robert's changes into that.

-brady

**Comment by bradymiller** [comment]
I just brought this into the codebase(note the commits brought in prior to that to support multiple versions of packages).

**Comment by sunsetsystems** [comment]
@Wakie87 Thanks. Does that mean we're also looking to use a router script to protect the PHP files from direct URL access?

**Comment by robertdown** [comment]
That should be implemented at the server level

Get Outlook for iOS<https://aka.ms/o0ukef>




On Thu, Jul 7, 2016 at 3:19 AM -0400, "Rod Roark" <notifications@github.com<mailto:notifications@github.com>> wrote:


@Wakie87<https://github.com/Wakie87> Thanks. Does that mean we're also looking to use a router script to protect the PHP files from direct URL access?

-

**Pull request closed without merging**
