### PR TITLE
Some menu and menu role work

### PR DESCRIPTION
**Pull request by bradymiller**
Work to leverage current menu code and make it more generic to allow support for different menus (such as the patient menu work by @eyalvo-matrix ).

### CODE REVIEW

**Comment by bradymiller** [comment]
btw, the next goal on this menu system (ie. not for this PR, but for the future) is the following:
1. Graphical editor -  https://github.com/openemr/openemr/issues/1551
2. Store in database (in json format) rather than files. This will allow snapshots, history, and crazy functionalities :)

If any developers would be interested in working on this, just let me know, and I'd be glad to provide guidance.

**Comment by bradymiller** [comment]
@eyalvo-matrix ,
This is testing well and plan to bring this in after some more extensive testing. This will be a launching board to begin to develop better menu editing etc, so will bring this into the soon to be released OpenEMR 5.0.1 (then will be much easier to include improvements in 5.0.1 patches down the road).
-brady

**Comment by bradymiller** [comment]
woohoo, this is testing well and good to go. gonna bring it in.

**Comment by matrix-amiel** [comment]
@bradymiller  Amazing!! 
Note that after this change, the complex system of the hooks is unnecessary and we can add hooks with full flexibility and comfortably. 
Great work for OpenEMR developers.

**Pull request merged**
