### PR TITLE
Updated ACL help file, minor styling changes

### PR DESCRIPTION
**Pull request by zbig01**
Made minor styling changes to help files, added some css
classes to flat stylesheets
Updated ACL help file
Moved New Encounter Form and help file from previous PR to this commit

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @zbig01 ,

There seems to be lots of other unrelated code changes here (such as interface/forms/newpatient/common.php and interface/forms/newpatient/common_help.php)?

-brady

**Comment by bradymiller** [comment]
doh,
Disregard my above post @zbig01 .
I just noted that you meant to do did this in your comment. If possible, it is much better to not combine projects like this. For example, the acl stuff is basically a slam dunk to get into the codebase, but the encounter stuff has lots of issues (has reverted lots or previous code changes). So, in this case, the encounter stuff will really slow things down. Is there a way to separate out the acl stuff?
thanks,
-brady

**Comment by zbig01** [comment]
Done. Could you update the css and the other help files. Thanks

**Comment by bradymiller** [comment]
Regarding updating the css and other help files, I am assuming you mean the other code changes on this PR (or is there something else? )

**Comment by bradymiller** [comment]
btw, after I get clarification on my question above, then this is coming into the codebase :)
(I'll revert it to default light style with a proceeding commit)

**Comment by zbig01** [comment]
I added a couple of classes to the flat css stylesheets. I also added class oe-help-redirect to 
class="pull-right " in the heading , helps with the styling. 

The other style was if you decided to make an up for grabs demo. Pl revert to light before commit. 

Though it would  be nice to have an alternate official demo with a flat style :))

**Comment by bradymiller** [comment]
Just brought into codebase. Thanks for the improvements!
I think I can set one of the development demos (since we have at least 5 or 6 of them :) ) to use another style. The demo farm can run mysql for demo data so I think I can do this; just give me the mysql statement to change to the style you wish.

**Comment by zbig01** [comment]
style_sienna.css

**Pull request merged**
