### PR TITLE
Removed existing headers

### LINKED ISSUE #3092: Eye exam creates problem for other innocent forms
### Describe the bug
All functionalities on encounter summary page will stop working if you add an eye exam form.

Most probably the dialog.js is being included twice in the same page. 
I did a little debug and `interface/forms/eye_mag/report.php:255` `SetupHeader()` is responsible of the behaviour.

### To Reproduce
1. Add a eye exam report on patient encounter

Screenshot from 2020-03-06 21-21-30

### Client configuration

- Browser: Linux
- Operating system: Chrome

tag: `Good first issue`

### PR DESCRIPTION
**Pull request by yashrajbothra**
Signed-off-by: Yash Bothra <yashrajbothra786@gmail.com>

Fixes #3092

### CODE REVIEW

**Comment by sjpadgett** [comment]
Are you sure jquery is in scope? If so will bring in as i'm updating my dev env for testing and some new stuff:)
Thanks for quick fix...

**Comment by yashrajbothra** [comment]
> Are you sure jquery is in scope? If so will bring in as i'm updating my dev env for testing and some new stuff:)
> Thanks for quick fix...

Yes , its in scope by re-adding it resets jquery.esign which is giving .esign error

**Comment by im-Amitto** [comment]
@yashrajbothra A job well done!

**Comment by sjpadgett** [comment]
Second that! Thanks.

**Pull request merged**
