### PR TITLE
Interface Forms SQL

### PR DESCRIPTION
**Pull request by danehrlich1**
beginning of SQL Injection changes to `/interface/forms`.

Will comment again when done fully.

below by bradymiller:
Up for grabs demo for this PR here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Beta_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by danehrlich1** [comment]
Final file left: `interfaces/forms/vitals/C_FormVitals.class `

How do you fix a query like this:
```
        $dbconn = $GLOBALS['adodb']['db'];
        //Combined query for retrieval of vital information which is not deleted
        $sql = "SELECT fv.*, fe.date AS encdate " .
        "FROM form_vitals AS fv, forms AS f, form_encounter AS fe WHERE " .
        "fv.id != $form_id and fv.pid = " . $GLOBALS['pid'] . " AND " .
        "f.formdir = 'vitals' AND f.deleted = 0 AND f.form_id = fv.id AND " .
        "fe.pid = f.pid AND fe.encounter = f.encounter " .
        "ORDER BY encdate DESC, fv.date DESC";
        $result = $dbconn->Execute($sql);
```

**Comment by bradymiller** [comment]
hi @danehrlich1 ,
I'd rec using sqlStatement instead on the query (and delete the $dbconn line):
```
        //Combined query for retrieval of vital information which is not deleted
        $sql = "SELECT fv.*, fe.date AS encdate " .
        "FROM form_vitals AS fv, forms AS f, form_encounter AS fe WHERE " .
        "fv.id != ? and fv.pid = ? AND " .
        "f.formdir = 'vitals' AND f.deleted = 0 AND f.form_id = fv.id AND " .
        "fe.pid = f.pid AND fe.encounter = f.encounter " .
        "ORDER BY encdate DESC, fv.date DESC";
        $sql_results = sqlStatement($sql, array($form_id, $GLOBALS['pid']));
```
And then change line 72 to:
```
while ($result = sqlFetchArray($sql_results)) {
```
And remove line 91 ($result->MoveNext();)

**Comment by danehrlich1** [comment]
@bradymiller Wow this is embarrassing but why did I close this pull request / branch?

I think I was trying to clean up the branches in the repo.

Did I merge this somewhere else into a "mega pull request"? Why did I do this?

**Comment by danehrlich1** [comment]
@bradymiller Can you reopen this pull request and merge either with Master branch or with `sql-changes-3rd-go-round-de` branch?

This has all the changes I did for `interfaces/forms`, so it's a lot of work. 

Thanks so much and sorry I accidentally closed this at one time.

**Comment by danehrlich1** [comment]
@bradymiller can you please reopen? Might need to fix a couple things but want to get this going. Thanks!

**Comment by bradymiller** [comment]
it's weird, it won't let me re-open. but the code is there now, so can review it soon.

**Comment by bradymiller** [comment]
rebased this into 1 commit on top of most recent codebase in the following PR:
https://github.com/openemr/openemr/pull/2193

**Pull request closed without merging**
