### PR TITLE
tobacco or any given case fixed for input check

### LINKED ISSUE #2996: No check on start and last date input in case of tobacco
### Describe the bug

No check on start and last date input in case of tobacco

Screenshot from 2020-02-26 08-56-02

### To Reproduce
Visit patient info page 

### Expected behavior
Input should be checked before being used in SQL query

### Client configuration

- Browser: Chrome Version 80.0.3987.106 (Official Build) (64-bit)
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by im-Amitto**
Fixes #2996

#### Short description of what this resolves:
It corrects the check behavior for special cases.

#### Changes proposed in this pull request:
Move any needed where clauses in a variable which are being joined with the SQL statement.

### CODE REVIEW

**Comment by bradymiller** [comment]
Hi @im-Amitto , During testing, getting following error at Patient Summary Screen->History 

image

**Comment by im-Amitto** [comment]
@bradymiller  fixed :)

**Comment by im-Amitto** [comment]
rebased :)

**Comment by bradymiller** [comment]
hi @im-Amitto , Looks good and testing well. Bringing into codebase (and will go in next 5.0.2 patch). Thanks for these critical MySQL 8 fixes! -brady

**Pull request merged**
