### PR TITLE
remove 2010AB REF segment for 5010

### PR DESCRIPTION
**Pull request by stephenwaite**
another billing fix, jeez, i'm sorry...

### CODE REVIEW

**Comment by stephenwaite** [comment]
because it's not in the spec

**Comment by bradymiller** [comment]
@stephenwaite ,
Just let us know when you think it's ready to get into the codebase.
thanks, -brady

**Comment by stephenwaite** [comment]
ok, it's good to go, going to think about adding a pay-to address checkbox on the facility setup screen that will read from the addr book or that screen to get around this funny condition
https://github.com/openemr/openemr/blob/master/library/gen_x12_837.inc.php#L238

**Comment by bradymiller** [comment]
hi @stephenwaite , Great, will bring this into codebase. Thanks for the improvement! -brady

**Pull request merged**
