### PR TITLE
Some layout-related bug fixes.

### PR DESCRIPTION
**Pull request by sunsetsystems**
Added translation of layout subtitles.
Added checking for duplicate field IDs when editing a layout.
Fixes for radio button field types.

### CODE REVIEW

**Comment by sjpadgett** [comment]
How do you feel about users ability to change field id's for our core lbf's? Some must be hard coded in validations or lookup but is a consistent issue especially with new users that have not learned for hard experience...

**Comment by sunsetsystems** [comment]
Hi Jerry, it seems right to make a hard-coded array of field IDs that must not change, since references to them are hard-coded as well. Then the layout editor could check that and disallow changing them.

**Comment by sjpadgett** [comment]
I get that but, it has been difficult to track down the hard coded ids floating around. I think it is safe to not allow any of our core default forms field id's to be modified by simply disabling them. However, there is still a concern for those hard coded id's if the field has been selected as 'Unused' in LBF. Maybe you know.
All I know there are several combinations for users editing on the core forms that presents in several way. Namely two come to mind: 1. Allows a new patient entry up to save were it fails(I get this one), 2. completely locks the search/add popup iframe(could not get to the bottom of with user).
I think simply not allowing the core form field id's to ever be changed will maybe solve many of the woo's. I just see no reason user should be allowed to change. Label should be okay. Maybe you have a reason.

**Comment by sunsetsystems** [comment]
Well with core forms like demographics you want to allow new fields to be added, and then changed or removed. In my experience that is very common.

**Comment by sjpadgett** [comment]
Yep, I don't have a problem with that at all and defeats a main purpose of LBF anyway. Go ahead and finish what you're doing and i'll throw up a PR how I think it should work(disables in editor) and you can check it out for me.

**Comment by sunsetsystems** [comment]
Cool, thanks!

**Comment by bradymiller** [comment]
code looks good to me :)

**Comment by sjpadgett** [comment]
@sunsetsystems Can't wait to see new features so i'll wait to do changes to field id's 'till you are finished. Thanks.

**Pull request merged**
