### PR TITLE
My first module. Need assistance with framing module basics

### PR DESCRIPTION
**Pull request by juggernautsei**
Fixes #
This is in support of the discussion about how to create a module. The hopes are to create a skeleton that can be used for future developers.
#### Short description of what this resolves:
The hopes are to solve the lack of a pattern to follow. To get off and running quickly, there needs to be a barebones pattern to follow. 

#### Changes proposed in this pull request:

- Work out a barebones skeleton for the modules system
- Make this skeleton available for other future developers to use. 
-

### CODE REVIEW

**Comment by sjpadgett** [comment]
Rec if looking to do CC then check out my existing gateway. I dev so adding dif gateways would make payments throughout openemr consistent and reusable ie src/Billing/PaymentGateway.php act similar to an interface class you can extend or include.
Paytrace has a OmniPay plugin https://github.com/iddqdidkfa/omnipay-paytrace you can just add to composer.
This should make it seamless for ya.

Also note that i've integrated the gateway already in Front Payments for Authorize and Stripe as well as portal using portal/lib/paylib.php. For a module you could just add an event dispatcher to the make payment button. If you decide to do that, i'll convert the other payment options to use same dispatcher but, not needed and you can still add.

For your module you will need to bootstrap src/Core/ModulesApplication.php it most likely. 
Anyway, just saying:)

**Comment by sjpadgett** [comment]
I say we shoot Travis!!!!

**Comment by juggernautsei** [comment]
> I say we shoot Travis!!!!

I agree about Travis... however, it keeps us on the same page for coding standards. 

Thanks for the Omni pay code, I will look it over, The point was not paytrace. I just chose that because I have some stuff with them that I want to do that is not like what is in the code base but I will submit that once I get the module skeleton working. 

So, would you mind focusing on the module skeleton? What am I missing to get the menu code to work properly? @sjpadgett

**Comment by sjpadgett** [comment]
@juggernautsei You need to have a txt file info.txt in module root. interface/modules/custom_modules/module-name/info.txt
Populate with Example Module Framework v1.0.0 for example.

**Comment by juggernautsei** [comment]
@sjpadgett 
https://github.com/juggernautsei/openemr/tree/How_to_build_a_module/interface/modules/custom_modules/paytrace-gateway-module/info.txt

The infomation in the text file shows in the Module manager.
image

I remember talking with @adunsulag several times about this but still can't get it to implement. 
paytrace_add_menu_item(MenuEvent $event). This function should edit the menu on the fly. I still can't figure out what activates it.

**Comment by adunsulag** [comment]
@juggernautsei It's fired in [MainMenuRole](https://github.com/openemr/openemr/blob/master/src/Menu/MainMenuRole.php)

You can see all the places MainMenuRole is called [here](https://github.com/openemr/openemr/search?q=repo%3Aopenemr%2Fopenemr+MainMenuRole&unscoped_q=repo%3Aopenemr%2Fopenemr+MainMenuRole)

**Comment by juggernautsei** [comment]
Embarrassing. I misspelled bootstrap. So, in the skeleton, there has to be the file named openemr.bootstrap.php. I finally thought to look in the error log. 
This file is what sets the menu parameter for the module. It works and I can set as many as needed.
@adunsulag  Thanks for your patience and you too @sjpadgett

**Comment by juggernautsei** [comment]
@adunsulag here is my next hurdle. I want to set more than one menu location. How can I set multi menu locations that are not children of the module? Meaning I want to set a menu item in fees, and another in Patient/Client. How can I do that?

**Comment by zerai** [comment]
Hi @juggernautsei ,
if you want make the module installable by composer, you should add 
```yaml
"openemr/oe-module-installer-plugin": "^0.1",
```
in require section of composer.

**Comment by sjpadgett** [comment]
@juggernautsei 
Note that adding a table.sql to root will do any database actions on install.
https://github.com/openemr/oe-module-faxsms/blob/8031412849b3ba22d28c12c06989e7921ca00b64/table.sql#L10
Also, https://github.com/openemr/oe-module-faxsms/blob/8031412849b3ba22d28c12c06989e7921ca00b64/moduleConfig.php#L12
is handy if you have a setup script to expose in the zend module manager
image

Finally worth noting is ability to unregister module. This is handy for reinstall or just clean up
image

**Comment by juggernautsei** [comment]
@zerai 
I can't use this in the composer file?

        "require": {
             "openemr/paytrace-gateway-plugin": "^0.1.0",

**Comment by juggernautsei** [comment]
@sjpadgett thanks for the tips. The next thing is can I run my own entities and repositories?

image

**Comment by sjpadgett** [comment]
> The next thing is can I run my own entities and repositories?

Should. Just carry on as if your code is sitting in oemr dir tree. You may have to fixup your class loader for your includes.


> That setup feature has to be coming in 5.0.3. Doesn't work in 5.0.2(2)

Hmm, thought I brought that back along with unregister. Guess not but, as one vet(even if Navy!) to another and if Brady isn't too far along on Patch 3 maybe it is doable.


> ```yaml
> "openemr/oe-module-installer-plugin": "^0.1",
> ```

Is the generic installer to install all modules.

**Comment by zerai** [comment]
> @zerai
> I can't use this in the composer file?
> 
> ```
>     "require": {
>          "openemr/paytrace-gateway-plugin": "^0.1.0",
> ```

yes, you should use above code in composer.json file of openemr,

but composer.json file of your module should contains
```yaml
"openemr/oe-module-installer-plugin": "^0.1",
```
see @sjpadgett code [here](https://github.com/openemr/oe-module-faxsms/blob/ab000dd03ded7db28219c3a40def9330c20d19ff/composer.json#L21)

**Comment by juggernautsei** [comment]
What I am learning right now is that I am in a catch because the PSR4 auto load does not recognize my paths and I can't manually add them so,now what? My thinking is to create a repository where I can call and install what I have via composer then I should be able to work on it. Is this correct @zerai

**Comment by zerai** [comment]
Your autoload configuration look good, but the namespace in class AppDispatch.php  is wrong.
it's declared

```php
namespace OpenEMR\Modules\Paytrace\Controllers;
```

but should be 
```php
namespace OpenEMR\Modules\PaytraceGateway\Controllers;
```

becasue this is your declaration in composer.json
```yaml
 "autoload": {
        "psr-4": {"OpenEMR\\Modules\\PaytraceGateway\\Controllers\\": "controllers/"}
    },
```
[here](https://github.com/zerai/oe-module-demo-farm-add-ons) another module example.

**Comment by juggernautsei** [comment]
@sjpadgett - I sailed the final voyage of the USS America CV-66. We brought her back in and put her to rest. That is my footnote in history.
 However, this error message has me stumped. I have checked the PSR entry that @zerai pointed out and I still get the same error over and over. 
      [19-May-2020 19:08:16 America/New_York] PHP Fatal error:  Uncaught Error: Class 'OpenEMR\Modules\PaytraceGateway\Controllers\IndexController' not found in C:\oerm_dev\www\dev\eastccm\interface\modules\custom_modules\paytrace-gateway\cardUI.php:14
      Stack trace:
#0 {main}
  thrown in C:\oerm_dev\www\dev\eastccm\interface\modules\custom_modules\paytrace-gateway\cardUI.php on line 14

**Comment by sjpadgett** [comment]
@juggernautsei We all did our little part but, did it matter? I suppose we'll never know. At least we showed up:) Thank you for your service.


> ```yaml
> "autoload": {
>         "psr-4": {"OpenEMR\\Modules\\PaytraceGateway\\Controllers\\": "controllers/"}
>     },
> ```

I think you'll need to change your class paths to goto your module directory. Otherwise will search the OpenEMR namespace where the path doesn't exist.

**Comment by juggernautsei** [comment]
Thank you for your service also. The few the proud. I know the wrong slogan. Oh yeah, Army strong.
I am lost at sea with the comment about the autoloader.
See the image below. I thought I was following the blueprint walking in the footprints of the giants that have gone before me. @sjpadgett 
image
You should recognize the code on the right. It is similar to the code on the left. The only difference that I can find between the two is the one on the right has been installed via composer. So, now I am off on the path to figure out has to create a repo, upload what I have, and install it via composer to see if that solves my problem.

**Comment by juggernautsei** [comment]
This was not meant for the codebase. It is just an open lesson for me.

**Pull request closed without merging**
