### PR TITLE
add new style global for add edit events

### PR DESCRIPTION
**Pull request by eyalvo-matrix**
This branch is intended to add a new Global for the add edit event window size 

It intended to solve the following problem : 
1. The add edit event window size is hard coded in multiple file
2. In some styles the calendar of the "until date" is cut off making it hard to pick a date

Thanks 
Eyal

### CODE REVIEW

**Comment by eyalvo-matrix** [comment]
Not sure why there is a conflict here or how to resolve it

**Comment by bradymiller** [comment]
I think @sjpadgett uses auto sizing with these modals now(this was just recently added to the codebase). @sjpadgett, just confirming that my above statement is true?

**Comment by sjpadgett** [comment]
The point of doing the responsive dialog with resize and drag was for these types of sizing issues. This form (add/edit) should be restyled to be responsive instead of fixed size which I am in process of doing, much like i've done the prescriptions. I will do a PR for this and a new pop out viewer for documents in next couple days. Here is a shot of those. https://community.open-emr.org/t/full-screen-view-for-documents/9351

**Comment by eyalvo-matrix** [comment]
Please notice that because of the  date picker  in this screen css responsive screen
 will not be enough and the screen need to be larger or javascript must resize it. 
Q : @bradymiller will this future change will fit with the old none frame style?

**Comment by sjpadgett** [comment]
Why are you asking Brady? I'm doing the development.  By responsive, the form should size to the dialog size. So if dialog size changes, the form will as well. In the frame ui the dialog for appointments are windows which can resize therefore, if appointment forms are responsive then they will size to the window.
Using fixed sizes in UI leads to trouble when using OpenEMR on portable devices like tablets which is why the push toward bootstrap and zigbe's work. As I've advertised for past week on the forums, I have been developing replacement dialogs for both frames and tab UI and fixing forms as I implement.
If these forms are going to be touched then they should be made to come into line with the UI updates.

**Comment by sjpadgett** [comment]
@bradymiller  I'm not seeing this issue with my latest dialog so this may not be needed. I will post latest tomorrow sometime.

**Comment by bradymiller** [comment]
hi @eyalvo-matrix ,
Just checking if we can drop this PR now since this has been addressed by @sjpadgett 's super amazing popup/modal asset.
-brady

**Comment by eyalvo-matrix** [comment]
sure why not 
To another matter  @bradymiller and @sjpadgett the latest pull request is full of bugs 
2 critical bugs that i found so far are 
1. double press on create patient causes duplicate patient 
image

2. trying to add a patient in the therapy group causes 
image

this is for the non frame version of openemr

**Comment by sjpadgett** [comment]
@eyalvo-matrix The dialog error is because jquery-ui is not loaded however, dialog should load it if not there. Console log will show if getting loaded or not. Dup patients is mystery for now as dialog should have nothing to do with. When you say full of errors, can you be more specific? Try to remember that your module is an add on and a mystery to some of us.

**Comment by sjpadgett** [comment]
@eyalvo-matrix Can you go ahead and open an issue for these and we can straighten them out there. No worries we will get resolved. Okay

**Comment by sjpadgett** [comment]
@bradymiller Looks like i've missed some fancybox dialogs in demographics! Kinda strange how they get called in some cases but, I will need to go through and cleanup the dual classes and also redo the amendments framed dialog while I'm here. Also prob will be best to go ahead and full out covert demographic to bootstrap i.e add the dependency. As it stands now, dlgopen will add any dependency it needs to run i.e if bootstrap.css or js is missing I will dynamically add then when dialog is closed, dependency is removed from calling scope.  So, where is best place to track this adventure so other can report issues or lend a hand in ridding the fancybox? I'm starting to feel a little lonely in this endeavor. :)

**Comment by bradymiller** [comment]
@sjpadgett ,
I'm all for fancybox carnage, so count me in. Rec making a new Issue with title of 'Bye bye fancybox' or whatever catchy name you prefer. And let me know where I can help. The only other high priority thing I am working on is porting the mysql ssl stuff to 5.0.0 over the next couple days.
-brady

**Comment by eyalvo-matrix** [comment]
During the coming week I will check and report on the bugs that are not related to our adds on :) 
I opened a new issue for the groups in order to hot fix it with the solution @bradymiller suggested 
 that dlgopen will add any dependency it needs to run

**Comment by eyalvo-matrix** [comment]
I will also try to track why the demographic is duplicating a user when double clicking on add a user probably stop propagation need to be some where there

**Comment by eyalvo-matrix** [comment]
@sjpadgett @bradymiller  note that the latest JS changes 
is not backup compatible to IE11 and older versions of firefox  
for exammple the usage of isinteger function

**Comment by sjpadgett** [comment]
Have to remember the fancy box replace is on going so would not test to closely until I commit new PR for the further removal from demographics later today. I've turn on your module and will test as I go, best I can. Not sure how far back we need to be backwards compatible for browser support.

**Comment by eyalvo-matrix** [comment]
@sjpadgett about the specific bug I entered a straight forward fix at 
https://github.com/openemr/openemr/pull/1288

**Comment by sjpadgett** [comment]
Yep sir, just brought in. I'm going to get the Admins to recommend how far back in browser support we wish to honor and I will keep a closer eye on backwards compatibility. Call me out on it though, if you catch me.

**Comment by eyalvo-matrix** [comment]
Will do thanks

**Comment by bradymiller** [comment]
hi @eyalvo-matrix ,
Looks like this PR is no longer pertinent(since issues have been addressed by @sjpadgett's work). Can I close this PR?
-brady

**Comment by eyalvo-matrix** [comment]
sure

**Pull request closed without merging**
