### PR TITLE
bug fix #7558

### LINKED ISSUE #7558: Prior Authorizations Report Error. #7461
### Describe the bug

fail to find vendor.php
reported in issue #7461 

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by juggernautsei**
Fixes #7558

### CODE REVIEW

**Review by adunsulag — APPROVED** [review]

**Comment by adunsulag** [comment]
Bringing this in as all checks pass.

**Comment by bradymiller** [comment]
Hi, just checking if this was supposed to come into codebase instead of getting closed.

**Comment by juggernautsei** [comment]
I was under the assumption that it has already been brought into the codebase. Please reopen and bring it into the codebase.

**Comment by adunsulag** [comment]
@juggernautsei sorry about that. Thought I merged it, not closed it.  Great catch @bradymiller!

**Pull request merged**
