### PR TITLE
Remove dynarch calendar libraries

### PR DESCRIPTION
**Pull request by bradymiller**
Was hoping to get some feedback on this.

If we remove these libraries (no longer used in main codebase), this will likely break custom code and forms that uses the prior calendar picker.

Options are:
1. Remove it now
2. Remove it in the future (and give developers/users time to adjust code; ie. deprecate it)

thoughts?

### CODE REVIEW

**Comment by sunsetsystems** [comment]
I'd say the question is how to warn of deprecation. Perhaps modify the old library to pop up an alert that also gives instructions for removing the alert. That way a developer that ports their code in can't miss it, and won't be too inconvenienced at the time.

**Comment by bradymiller** [comment]
I'd hate to unleash a bunch of popups/alerts on the end users.

Another option would be to remove them and provide documentation with both options:
1. How to add the libraries back (very simple; basically add back the 5 files to the library directory)
2. How to migrate code to new datepicker (range from simple to complicated depending on the script)

-brady

**Comment by sunsetsystems** [comment]
That works too, but either way if someone upgrades without testing their custom code then users will be surprised. :)

**Comment by mdsupport** [comment]
May be move the files to `vendor/legacy/dynarch`, including the documentation about how it was used and datepicker replacement.  Then completely drop the files with next major release (e.g. 6).

**Comment by bradymiller** [comment]
@mdsupport ,
Sounds like a good plan. Will plan to do this (except will use contrib/legacy/dynarch instead since humans can't touch the vendor dir (only composer has permission :) ).
-brady

**Comment by bradymiller** [comment]
Now that we are on a new release cycle (5.0.2), am going to remove these libraries. This will give users likely at least 6 months before next release to adapt (or they can simply copy these back into their instance if need them when we release 5.0.2 in the distant future).

**Pull request merged**
