### PR TITLE
Sherwin's erx updated (temporary PR)

### PR DESCRIPTION
**Pull request by bradymiller**
This is a temporary PR for Sherwin (making sure it passes travis ci).

### CODE REVIEW

**Comment by bradymiller** [comment]
Hi @juggernautsei ,
Here is a temporary PR. Lets have you basically mirror this PR (then I can collaborate with you to help get this into the codebase asap). To mirror this PR, do the following:
``````
git remote add bradymiller https://github.com/bradymiller/openemr.git
git fetch bradymiller
git checkout bradymiller/new_erx_6
git checkout -b new_erx_6
git push origin new_erx_6
``````
Now go to github and make a PR from your new shiny new_erx_6 branch.
(then I'll close this PR)

**Comment by juggernautsei** [comment]
I have just forked this branch.

**Comment by bradymiller** [comment]
From your new branch, create another PR (then can confirm it looks ok and we can then use your PR to collaborate on; I'll then close my PR).

**Comment by juggernautsei** [comment]
Ok, this is done. Thanks!

**Comment by bradymiller** [comment]
new PR looks good:
https://github.com/openemr/openemr/pull/1017

**Pull request closed without merging**
