### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by stephenwaite**
@kchapple discovered through helping client

### CODE REVIEW

**Comment by stephenwaite** [comment]
testing well

**Comment by kchapple** [comment]
Thanks @stephenwaite @bradymiller I had this fix on my to-do list. I know it's easier for you because you have write privileges to this repository, but as you now code attribution is very important to vendors in an open source project, so in the future please ask, or provide accurate attribution to the author using --author flag in git. 
`git commit --author="Ken Chapple <ken.chapple@gmail.com>" -m "Description of commit"`

**Comment by stephenwaite** [comment]
hi Ken, sure, actually fixed it first when I sent you the php fatal error
will bring into 5.0.2 patch as well

**Comment by kchapple** [comment]
Thanks!

**Comment by stephenwaite** [comment]
https://www.open-emr.org/wiki/index.php/Ongoing_5.0.2_Patch_Trail
thanks for the git tip as always, just like that old  youtube video, with 2,325 views ! :stadium:

**Comment by bradymiller** [comment]
hi @stephenwaite and @kchapple , I can change attribution on this commit if needed (I simply do a revert of commit followed by a recommit; I've occasionally have had to do this when I accidentally bring in PRs in my name in the past). Just let me know if wish, and I'll do it. -brady

**Comment by stephenwaite** [comment]
that'd be great, thanks @bradymiller

**Comment by bradymiller** [comment]
hi @stephenwaite and @kchapple ,
done :)
https://github.com/openemr/openemr/commit/0720c4fd1bcd3fdfe2ba93a92cc3f59cf2970f5f

**Pull request merged**
