### PR TITLE
fix sql query for new.php misc bill options

### PR DESCRIPTION
**Pull request by stephenwaite**
fix reported for bug reported on forum https://community.open-emr.org/t/misc-billing-options-bug-warning-data-loss-potential/10031?u=stephenwaite and is testing well

### CODE REVIEW

**Comment by sjpadgett** [comment]
This troubles me a little and I can't put my finger on why! Maybe because, for me, the existing mbo form check is written backwards. Should query the forms table for an existing mbo form on current encounter and retrieve the mbo id from there if indeed form exists. After all the forms table is master here and holds all the info about form status. Just don't see the need for a join. Also using empty() for conditional on int values is not ideal, strict equality is more appropriate. Lastly, I have misgivings about relying on table setting correct default for a column such as deleted=0 ie for sure if is deleted we can count on deleted being true. Hope i'm not coming off as nit picky :) I know you are just modding existing but maybe another look at original can't hurt.

**Comment by stephenwaite** [comment]
thanks @sjpadgett i'm open to all ideas and a rewrite since you know best

**Comment by sjpadgett** [comment]
@stephenwaite Seems to have fixed the problem so if you want just leave as is and i'll bring in.

**Comment by stephenwaite** [comment]
sure, then we can work on somethin mo better down the road

**Comment by sjpadgett** [comment]
Okay thanks

**Pull request merged**
