### PR TITLE
some fixes

### PR DESCRIPTION
**Pull request by bradymiller**
Under radar fixes

Still testing

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller 
Don't ask me why mysqldump/perl commands insists quotes when used just for table dumps. Otherwise if there are some sql commands without table dumps the mysqldump doesn't require.

at L-413
`
`if ($tables) {
            if (IS_WINDOWS) {
                $cmd .= escapeshellcmd('"' . $mysql_dump_cmd . '"') . " -u " . escapeshellarg($sqlconf["login"]) .
                    " -p" . escapeshellarg($sqlconf["pass"]) .
                    " -h " . escapeshellarg($sqlconf["host"]) .
                    " --port=".escapeshellarg($sqlconf["port"]) .
                    " --opt --quote-names $mysql_ssl " .
                    escapeshellarg($sqlconf["dbase"]) . " $tables";
            } else {
                $cmd .= escapeshellcmd($mysql_dump_cmd) . " -u " . escapeshellarg($sqlconf["login"]) .
                    " -p" . escapeshellarg($sqlconf["pass"]) .
                    " -h " . escapeshellarg($sqlconf["host"]) .
                    " --port=".escapeshellarg($sqlconf["port"]) .
                    " --opt --quote-names $mysql_ssl " .
                    escapeshellarg($sqlconf["dbase"]) . " $tables";
                }
            if (IS_WINDOWS) {
              # The Perl script differs in windows also.
                $cmd .= " | " . escapeshellcmd('"' . $perl . '"') . " -pe \"s/ DEFAULT CHARSET=utf8//i; s/ collate[ =][^ ;,]*//i;\"" .
                " >> " . escapeshellarg($EXPORT_FILE) . " & ";
            } else {
                $cmd .= " | " . escapeshellcmd($perl) . " -pe 's/ DEFAULT CHARSET=utf8//i; s/ collate[ =][^ ;,]*//i;'" .
                " > " . escapeshellarg($EXPORT_FILE) . ";";
            }
        }`
`

**Comment by sjpadgett** [comment]
Do you want me to follow up this merge with fix or can you just add the changes in this PR?

**Comment by bradymiller** [comment]
hi @sjpadgett , thanks for the fix. I'll bring it into this PR (then just 1 commit to take over to rel-502).

**Comment by bradymiller** [comment]
plan to bring this into codebase (both master and rel-502) tomorrow

**Pull request merged**
