### PR TITLE
Updated gui for user facility settings

### PR DESCRIPTION
**Pull request by bradymiller**

### CODE REVIEW

**Comment by bradymiller** [comment]
@sjpadgett ,
Updated the user facility settings gui and popup for bootstrap and removal of fancybox. Testing well in frames and tabs. This uses the underlying layouts engine, so plan to do some more testing. Let me know if you see any flaws in how I converted from fancybox to the new jerryModal :)

**Comment by sjpadgett** [comment]
@bradymiller Looks good to me. I'm still somewhat bothered that FF will allow a target to a frame name but other browsers not. I did find out that if you dynamically create the target frame from targeting script, then it works. Oh well. What, 13 more to go:)

**Comment by bradymiller** [comment]
Testing well and going to bring into codebase.
Just 13 left!

**Comment by bradymiller** [comment]
@sjpadgett ,
btw, the next script I am attacking is edit_globals.php

**Comment by bradymiller** [comment]
https://github.com/openemr/openemr/issues/1317

**Pull request merged**
