### PR TITLE
correcting PR 2522

### PR DESCRIPTION
**Pull request by stephenwaite**
#2522 was a fail, this is promising pending travis

### CODE REVIEW

**Comment by stephenwaite** [comment]
just a few to hand edit :)

**Comment by bradymiller** [comment]
hi @stephenwaite , Looked through and looks great. Sorry you have to suffer through those and edits again (we should issue penalties for placing comments before else's :) ), but at least time it will get into the codebase and you can then try to stop having nightmares about comments before else's :)

**Comment by stephenwaite** [comment]
i've been diagnosed with sleep elsenea, favorite comment so far is 
`// This is probably very not ok...`

**Comment by bradymiller** [comment]
hi @stephenwaite , Looks great! Going to bring this into codebase now. You deserve a vacation (unpaid of course :) ). -brady

**Comment by stephenwaite** [comment]
[:)](https://duckduckgo.com/?q=no+rest+for+the+wicked&t=canonical&atb=v174-2_i&ia=videos&iax=videos&iai=rBmMzabdEKQ)

**Pull request merged**
