### PR TITLE
This is to be able to jump into a patients chart from the messages

### PR DESCRIPTION
**Pull request by juggernautsei**
Fixes #
Nothing
#### Short description of what this resolves:
Being able to jump from messages into the chart.

#### Changes proposed in this pull request:
Jump into chart

### CODE REVIEW

**Comment by juggernautsei** [comment]
Bump? hmmmm

**Comment by juggernautsei** [comment]
Bump again!

**Comment by bradymiller** [comment]
@juggernautsei , Is this opening the patient summary screen in the proper tab? And is it updated the top panel with correct patient (including removing any current patient)?

**Comment by juggernautsei** [comment]
Good questions and I will have to review this again now because it has been so long I don't know the answers to the questions. The original premise has been lost to time. I will rebase and revisit.

**Comment by juggernautsei** [comment]
Closing this pull request. Opened a new one. 
https://github.com/openemr/openemr/pull/4769/commits/ade58f23a33029f577c1768ab9ec5ace547e698b

**Pull request closed without merging**
