### PR TITLE
Fixed Errors in database.sql file

### PR DESCRIPTION
**Pull request by aaricpittman**
- Fixed handful of comments that were missing a space.
- Escaped single quote in Jehovah's Witnesses.
- Removed inserts into openemr_postcalendar_events as failed due to no longer matching table schema.

May also want to consider removing the session insert on line 4868.

### CODE REVIEW

**Comment by bradymiller** [comment]
Looks nice and straightforward. Will do a quick test and get this into the codebase over next couple days.

**Comment by bradymiller** [comment]
Not even sure what the session insert is for. Would be nice to have the install script actually show sql errors to prevent these things from getting into the codebase.

**Comment by bradymiller** [comment]
In fact, on a grep of "openemr_session_info", I can find no place that this is used.

**Comment by bradymiller** [comment]
Actually,  "openemr_session_info" is getting populated somewhere in the codebase since an entry gets added whenever login it appears.

**Comment by aaricpittman** [comment]
You can do either \' or ''. But as I understand it '' is the SQL standard way of escaping a single quote.

The openemr_session_info table stuff is part of the authentication mechanism. It's a little hard to find because the way it's written it doesn't refer to it as "openemr_session_info". They break it up into two parts "openemr_" and "session_info". It's used in:

- interface/main/calendar/config.php
- interface/main/calendar/includes/pnUser.php

That insert looks like a carry over from when someone did sql dump and still had session data in that table.

**Comment by bradymiller** [comment]
Hi Aaric,

I pushed your code into the codebase. Thanks for the contribution!

I made two minor changes:
1. Used \ instead of '' to escaped, since we are using \ in other places (and seem confusion if also have queuries like " WHERE patient='' ")
2. I removed the session row insert

-brady

**Pull request closed without merging**
