### PR TITLE
Exclude database views from #IfTextNullFixNeeded directive in sql patches

### PR DESCRIPTION
**Pull request by mdsupport**
1. Mysql treats database views as VIEW type of tables. OpenEMR IfTextNullFixNeeded directive in sql_upgrade_fx.php script tries to 'upgrade' the text columns in the views resulting in fatal error.  This revised sql statement limits field selection of #IfTextNullFixNeeded directive to database tables.

2.  Display report results as css specified alternating colored rows using nth-child() selector in style_light.  Also allows report_results class directly for tables.  Current css requires a table within another span/div tag.

### CODE REVIEW

**Comment by bradymiller** [comment]
Looks like there is lots of goodness on this PR:
1. TEXT upgrade sql fix for views
2. Style fix (what does this fix?)
3. json marked readability improvement and addition of the fax/scan(if possible, need to get the $GLOBALS['enable_hylafax'] || $GLOBALS['enable_scanner'] in there)

**Comment by bradymiller** [comment]
I note you explained 2 above, so will remove question regarding it in above post.

**Comment by bradymiller** [comment]
For number 2, can you point to a report where this fix is used(just so I understand it better).

**Comment by bradymiller** [comment]
Regarding 3, I think we are in luck since the algorithm will treat 2 globals checks as an OR and not an AND:
https://github.com/openemr/openemr/blob/master/interface/main/tabs/menu/menu_updates.php#L138-L154

**Comment by mdsupport** [comment]
Regarding the css update - effect can be seen in Report > Patient > List.  

Many old reports have report_results as a class and results in a table.  None of existing tables would have report_results but this change will now permit that as well.  No two sane people would agree on choice of colors but nth-child dramatically reduces html transmission from server.

Min Browser restrictions : IE 9, FF 3.5, Chrome 4, Safari 3.2, Opera 9.6.

**Comment by bradymiller** [comment]
They all look good and I brought them all in. I followed them with a commit to set the proper global checks for the fax/scan menu item(also plan to do more extensive testing on the mysql upgrade code). Thank you for these contributions!
-brady

**Pull request closed without merging**
