### PR TITLE
Integrating the "Flow Board" form to Bootstrap 4

### PR DESCRIPTION
**Pull request by nkyriakoulis**
Fixes #

#### Short description of what this resolves:
As seen below, not all form elements were styled in BS4 and for the 3rd column (datepicker) a table element was used:
image

Also, at some screen size, the form alignment would break:
image

With this commit, the whole form is integrated to BS4, maintaining the styling and responsive behaviour of the existing form:
image

While the form won't break at any screensize
image

#### Changes proposed in this pull request:

-Integrating form to BS4, removing some inline styling and unnecessary or obsolete classes
-Replacing the "table" structure of the third column with BS4
-Fixing the responsive behaviour of the form
-Providing cohesion for all form elements

### CODE REVIEW

**Comment by tywrenn** [comment]
Holy crap you actually did it 😂😂😂 The code was a mess in that

**Comment by sjpadgett** [comment]
> Holy crap

umm what language! :)

**Comment by nkyriakoulis** [comment]
> Holy crap you actually did it 😂😂😂 The code was a mess in that

Yeah it took some time, but I guess it was a good practice for the GSOC Project of "Modernizing styling and user Interface", which I'm applying for  😀 . Hope to contribute more!!!

**Comment by bradymiller** [comment]
hi @nkyriakoulis , Code looks good and testing well, so bringing this into codebase. Thanks for the improvements! -brady

**Pull request merged**
