### PR TITLE
Rel 501 user admin fix

### PR DESCRIPTION
**Pull request by growlingflea**
User admin menu only allowed default facility to be billing facility.  This fix populates the drop-down with service facilities, not billing facilities.

### CODE REVIEW

**Comment by adunsulag** [comment]
@growlingflea Were you wanting to merge this into the 501 branch or into the master branch?  It looks like you are trying to merge in 127 commits into master when you were wanting to merge this into the 5.0.1 branch.

**Comment by growlingflea** [comment]
The 501 please.

**Comment by growlingflea** [comment]
Checking in on the status of this.

**Comment by sjpadgett** [comment]
It may be better to decide if we want this as default behavior in 502 then port back to 501. 
I think this to be a matter of convenience where the provider will/can be in many service locations and one or two billing locations thus, changing their billing location in an encounter will be required far fewer times.
However, my opinion is that all facility locations should be the pull down and let user decide. Barring this idea, I vote service location be default in both versions of openemr. Maybe @stephenwaite has an opinion.

**Pull request closed without merging**
