### PR TITLE
Mostly PHP8 that can be picked to v6

### PR DESCRIPTION
**Pull request by sjpadgett**
- edit_list string to int

Fixes #

### CODE REVIEW

**Comment by bradymiller** [comment]
signal-2020-11-19-220815

**Comment by sjpadgett** [comment]
Fixed reminders and background services to trigger 10 seconds apart.
I firmly believe they can cause contention via globals.

app now working well enough I can get back to ONC.:) Will leave PR open for a bit watching for more PHP8 errors.

**Comment by stephenwaite** [comment]
checked back on demo site and all the tabs turned to `Unknown`

**Comment by sjpadgett** [comment]
Is the session still good i.e. can you navigate?

**Comment by stephenwaite** [comment]
no, when opening to view frame source it shows `Site id missing...`

**Comment by sjpadgett** [comment]
Okay, I'm going to go ahead and bring this in as I believe services is the issue. Will cherry pick then we can test tomorrow after demos reset or @bradymiller is able to reset before then. I'll also test tonight local.

Thanks for the test Stephen. Very helpful.

**Comment by sjpadgett** [comment]
not going to edit that last commit message as it is wrong so will note the allow enter in the globals search box in merge comment and hope it gets remembered. That had been driving me crazy for awhile.

**Pull request merged**
