### PR TITLE
Brought in new Color charts from WHO and CDC

### PR DESCRIPTION
**Pull request by growlingflea**
Brought in growth charts for patients affected with Down Syndrome, datasets not available so dr input is needed for percentile data
Brought in datasets from WHO that use dailt increments for percentile data for patients up to 5 years old
Replaced outdated tables with css grid for displaying vitals reports
Fixed 'ageInDays' function from returning negative values
Displays percentiles for weight, height, BMI, and head circumference from WHO dataset for patients up to 5 years old, displays CDC data for patients between
2 years and 20 years old.

brought in sql tables needed for percentile data

Fixes #

### CODE REVIEW

**Comment by growlingflea** [comment]
This brings in significant improvements to the vitals reporting.  The percentiles are much more accurate for children up to 5 years old.  With the CDC only incrementing every 6 months, percentiles are pretty far off for infants.  I hope this is a good contribution.

**Comment by growlingflea** [comment]
This had a missing table in the sql file.  Fixed now

**Comment by growlingflea** [comment]
I re-exported the sql file that has all the expanded growth chart data.  There should be no more SQL errors.

**Comment by growlingflea** [comment]
@stephenwaite We initially had some issues when someone installed the branch on their local machine due to missing tables.  I've updated the file to include an sql file with all necessary tables, so everything seems to be working correctly.  Is it possible that the SQL checks were failing because of the missing tables??

**Comment by stephenwaite** [comment]
hi @growlingflea , are you asking about the automated testing here? If so, most likely not.

**Pull request closed without merging**
