### PR TITLE
Change HFCA 1500 claims diagnosis code print length from 6 to 8 for I…

### PR DESCRIPTION
**Pull request by sjpadgett**
…CD10 codes

### CODE REVIEW

**Comment by sjpadgett** [comment]
Important for anyone using HFCA 1500 paper claim and ICD10 codes.

**Comment by bradymiller** [comment]
Hi,
Just checking if there was a reason why you closed the item? Do you want this reviewed to get into the official codebase?
-brady

**Comment by sjpadgett** [comment]
Nope did not realize was closed and I have no idea how I managed to close it. Had trouble with my windows git client but submitted from bash. Sorry!

**Comment by sjpadgett** [comment]
So let me know if prob...

**Comment by bradymiller** [comment]
Looks good. Will this change also be compatible with ICD9 codes?

**Comment by sjpadgett** [comment]
Yes, I've tested with both and researched the max length of icd10's being 7 characters max so 7+1decimal point=8.

**Comment by openemr** [comment]
Just committed this to the codebase. Thanks for the contribution!
-brady

**Comment by sjpadgett** [comment]
Brady, I wanted to commit an updated Snellen form but don't know how you may want it. The form is modified from mi-squared snellen by adding peripheral vision and vision questions. Should it be renamed and submitted as new form or as patched existing form?

**Comment by bradymiller** [comment]
Depends how significant the changes are. If it would break the prior form or make prior forms look odd for the current users, then would create it as a new form.

**Comment by bradymiller** [comment]
If you have additional questions, then would recommend it as a new form.

**Comment by sjpadgett** [comment]
Yes of course, new it is. Thanks

**Pull request closed without merging**
