### PR TITLE
fix to ICD10 codes in post payments

### PR DESCRIPTION
**Pull request by stephenwaite**
change ICD9 to ICD10 thanks to community forum tip

### CODE REVIEW

**Comment by bradymiller** [comment]
This is a good quick fix for the user on the forum. Is this basically supposed to be skipping diagnostic codes? If so, then the official fix will be a bit more involved (if so, I'll point to a good example of how to do this).

**Comment by stephenwaite** [comment]
yes, thanks Brady

**Comment by bradymiller** [comment]
Hi @stephenwaite ,
Quick background: When we went to support ICD10, took a strategy that allowed use of any diagnostic code set (not just ICD10), which is set in Administration->Lists->Code Types with the Diagnosis toggle. This then provides more flexibility on code set/type use (for example, if another country used snomed dx codes).

However, the 2 queries you found obviously got missed in this project.

Will basically join in the code_types sql table (where ct_key in code_types is equal to the code_type value already used in the query) on the query and include when the code_types.ct_diag is equal to 0(this will essentiall then ignore all entries with diagnostic codes).

Here's an example query that uses this strategy in the codebase:
https://github.com/openemr/openemr/blob/6169cf60c016d510104a54e76550953f9cb73dc7/interface/patient_file/report/custom_report.php#L767-L775

-brady

**Comment by stephenwaite** [comment]
thanks @bradymiller , i redid the commit

**Comment by bradymiller** [comment]
@stephenwaite ,
Code looks good. Just let me know that it tested well for you and then I'll bring it into the codebase.
-brady

**Comment by stephenwaite** [comment]
hi @bradymiller , it tested fine, thank you.  Are there any coding standards i should be concerned about @robertdown with the mysql syntax (like the backticks i mistakenly left in) or the single quoted variables, or event the indent?  not sure how php-fig handles the mysql queries...

thought that i made it more readable esp. on github.com where it's a nuisance when the code goes off screen

**Comment by bradymiller** [comment]
Hi @stephenwaite ,

The php-fig doesn't really cover this type of thing, but what you did is much more readable. Thanks for the fix! Will bring this into the codebase and also into the next 5.0.0 patch.

backticks are nice since they avoid conflicts if it happens to be a mysql keyword or reserved word:
https://dev.mysql.com/doc/refman/5.7/en/keywords.html
(and you never know what they will add in the future, so for new mysql queries I usually always use backtick and in this case would recommend replacing it on date since your never know when that may become a reserved word)

-brady

**Comment by bradymiller** [comment]
just realized date is in fact a reserved keyword. I'll add the backtick to that now on a subsequent commit.

**Comment by stephenwaite** [comment]
Nice, thank you

**Pull request merged**
