### PR TITLE
Class reorganization

### PR DESCRIPTION
**Pull request by bradymiller**
Issue discussed on this forum post:
https://community.open-emr.org/t/composer-updating-auto-loader/10615/10

### CODE REVIEW

**Comment by adunsulag** [comment]
We won't pull this into 5.0.2 right?  Or do you think it will be part of that?

**Comment by bradymiller** [comment]
So far testing really well (gotta do more code analysis/testing to ensure not missing any paths). Ideally would get this in for 5.0.2 or else patches will be really tough (if master had reorg code and 5.0.2 didn't, then would make it much more difficult to patch code over from master to 5.0.2 for patches).

**Comment by bradymiller** [comment]
(this is assuming that this reorg is helpful)

**Comment by adunsulag** [comment]
@bradymiller Your right patches will be difficult if people are modifying the code which I wasn't thinking about that.  The reorg is very helpful as people can start adding additional classes and they are just auto-loaded.  Makes it better for Matrix and others to minimize composer.json conflicts.

**Comment by bradymiller** [comment]
Testing well and bringing this in. Another step towards modern code :)
And giving a shout out to @Wakie87 for starting all this composer stuff!

**Pull request merged**
