### PR TITLE
new codes

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #
https://x12.org/codes/remittance-advice-remark-codes

### CODE REVIEW

**Comment by stephenwaite** [comment]
someday will work on consolidating duplicate classes here and edihistory...

**Comment by sjpadgett** [comment]
> someday will work on consolidating duplicate classes here and edihistory.

Should I put an alert event in my calendar?:)

**Comment by bradymiller** [comment]
thanks @stephenwaite . i just brought this over to rel-600 also for next patch.

**Comment by stephenwaite** [comment]
cool @bradymiller , i wasn't deeming these worthy of any special attention but appreciate it for sure and will do for now on, sharpen my git blade :)

**Pull request merged**
