### PR TITLE
Remove html2pdf and convert to use TCPDF/FPDI

### PR DESCRIPTION
**Pull request by Wakie87**
So after lots of testing, this was the best result. Removing HTML2PDF as it was only being called in 2 places and replace it with the already built in TCPDF/FPDI. 

This also keeps all the RTL/LTR.

### CODE REVIEW

**Comment by bradymiller** [comment]
This will require a lot of testing.
I'll do some testing on the custom report feature. I am a bit skeptical that it will manage html to pdf conversion as well as html2pdf, but I will keep an open mind until I do some testing on it :)

**Comment by Wakie87** [comment]
Things that need testing:

**Reports** 
Custom Report -> save as PDF
- including 1/2/3 pdfs
- including images with different filetypes (png, jpg, gif)
- Mix 1 pdf/2 images, 2 pdf/1 image, 1 pdf/3 images etc....

**Orders** - Untested
Single Order Results -> Save as PDF

**Popups** (Someone who is using the avery labels to print will need to test this. I just made sure that I replicated the previous output.
Address Label
Chart Label
Barcode Label

**Comment by bradymiller** [comment]
Also in Custom Report, need to test:
All the patient forms.

**Comment by bradymiller** [comment]
Have following error when use an image (both a jpg and png show the error):
TCPDF ERROR: [Image] Unable to get the size of the image: /openemr/sites/default/documents/1/google_afp_294.jpg

**Comment by bradymiller** [comment]
Have following error with the speech dictation form(note when the error happens it seems to send the output to html until the error happened):
(2016-08-23)
Dictation: sfsdf
TCPDF ERROR: Some data has already been output to browser, can't send PDF file

**Comment by bradymiller** [comment]
Actually, the only form that does not throw above error is the following form:
Review of Systems Checks

**Comment by mdsupport** [comment]
Suggest serious look at using css more effectively with bootstrap.  It is bit more front loaded effort but long term flexibility is just liberating.

**Comment by robertdown** [comment]
Closing this since outdated PR

**Pull request closed without merging**
