### PR TITLE
Misspelled words

### PR DESCRIPTION
**Pull request by scaramuzzini**
Fixes #
No ticket

#### Short description of what this resolves:
Misspelled words

#### Changes proposed in this pull request:
Misspelled words

### CODE REVIEW

**Review by ash1kn1zar — APPROVED** [review]

**Comment by robertdown** [comment]
Hello @ash1kn1zar - we kindly ask that Code Reviews only be completed by our maintainers and authorized members.

**Comment by robertdown** [comment]
Thanks, @scaramuzzini for the contribution!

**Comment by ash1kn1zar** [comment]
> Hello @ash1kn1zar - we kindly ask that Code Reviews only be completed by our maintainers and authorized member

@robertdown .  I understand that, thanks.  Shall refrain from reviews and try to make other other value additions.

**Comment by robertdown** [comment]
> > Hello @ash1kn1zar - we kindly ask that Code Reviews only be completed by our maintainers and authorized member
> 
> @robertdown . I understand that, thanks. Shall refrain from reviews and try to make other other value additions.

If you are looking to join our community, you can checkout our [community forum](https://community.open-emr.org). Perhaps look for an easy issue to work on and submit a PR.

We are always looking for new contributors. Thanks!

**Pull request merged**
