### PR TITLE
fixes #3456 : Hovering property

### LINKED ISSUE #3456: Suggestion : Dropdown item should open while hovering
### Describe the bug
In the `View past encounter` button the drop-down item should pop up while hovering over the button for better UI experience.

### To Reproduce
Screenshot (156)

### Expected behavior

No overlap of items

### Client configuration

- Browser: Chrome
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by adad20**
Fixes #3456 

#### Short description of what this resolves:

ezgif-7-e25e9c0183c5

### CODE REVIEW

**Comment by sjpadgett** [comment]
I personally don't mind styles in scripts but, we don't want @tywrenn yelling at us!:)

**Comment by adad20** [comment]
@sjpadgett Yeah thats why I am seraching for the file 😅

**Comment by sjpadgett** [comment]
lol yep! It's such a beautiful day here in south Florida, no sense poking a bear!

**Comment by tywrenn** [comment]
@adad20 We aren't using internal stylesheets for code anymore as most can be done externally. The file you want to append ur CSS to is /interface/themes/theme-defaults.scss

**Comment by adad20** [comment]
hi @tywrenn I put the css code inside the `/interface/themes/theme-defaults.scss` but it shows no effect

**Comment by sjpadgett** [comment]
@adad20 Did ya run npm run build?

**Comment by adad20** [comment]
hi @sjpadgett you saved me :)

**Comment by sjpadgett** [comment]
> you saved me

Does this mean i'm a hero and the Navy Blue Angels and Air Force Thunderbirds will give me a fly over too?:)

Will bring in after Travis if ya want.

**Comment by adad20** [comment]
> > you saved me
> 
> Does this mean i'm a hero and the Navy Blue Angels and Air Force Thunderbirds will give me a fly over too?:)
> 
> Will bring in after Travis if ya want.

Yeah 😃

**Comment by sjpadgett** [comment]
lol, I see i'm not the only one Travis dislikes!

**Comment by adad20** [comment]
> lol, I see i'm not the only one Travis dislikes!

Travis threw me
happy-minions-gif-10

**Comment by stephenwaite** [comment]
caught by the new theme style checker! :spider_web: :)
Screenshot from 2020-05-03 16-46-00

**Comment by adad20** [comment]
@stephenwaite I don't know why travis is failing again. I have provided indentation properly

**Comment by adad20** [comment]
Hi @stephenwaite I provided 2 space indentation only yet travis failed. Don't know why

**Comment by stephenwaite** [comment]
hi @adad20 , checkout @bradymiller 's [cool commit](https://github.com/openemr/openemr/pull/3476/commits/577d81756f14e2957f0184655e2bf5c201bb8b52) 

it makes it super easy to fix these pesky probs :)

**Comment by adad20** [comment]
@stephenwaite I think travis is happy now

**Comment by sjpadgett** [comment]
I've been working on encounters lately and thought about this PR. I'm not sure this is a good idea.
Sorry  so late bringing this up.

I already am aggravated when in UI I happenstance cross topnav on my way somewhere else and we get those items expanding. Though it makes sense in topnav.
Many practices could have 10, 20 or even a hundred(Mental Health fac it is common) encounters and this I fear is going to prompt unwanted feedback from users. Crossing that pulldown will happen frequently.
@adad20 , you sure you want users cursing you under their breath daily! That's gota generated some bad karma...:)

In the end i'll leave to you guys but, I think the disadvantages out weight the advantages. Maybe there is a delay that can be set.
@tywrenn @stephenwaite

**Comment by adad20** [comment]
@sjpadgett Ohh Now I understood the intensity😅. Thanks for bringing this up. Should I close the PR?

**Pull request closed without merging**
