### PR TITLE
use htmlpurifier to escape nation notes entry output

### PR DESCRIPTION
**Pull request by bradymiller**
inspired by @juggernautsei prior work

This is still a work in progress. When click on the textarea to edit, the popup still allows cross scripting attacks.

### CODE REVIEW

**Comment by bradymiller** [comment]
bump

**Comment by juggernautsei** [comment]
I will look into this and see if it is still an issue and update this PR.

**Comment by juggernautsei** [comment]
@bradymiller I just saw this is three years old. OMG! This was under you know 5.0.1.  I will redo this in 5.0.3. I am brushing up on the package, I found that there is a bundle for Symfony 2.3. I will see if it is an update date with the version of Symfony that is in the codebase. 

     composer require exercise/htmlpurifier-bundle

This what I have found so far.  I'll update you soon with a new repo and close this one.

**Comment by juggernautsei** [comment]
@bradymiller I guess I am a little over-excited. I see htmlpurifier is in the composer.lock. However, it is not being used in the codebase anywhere and I am speaking of 5.0.2.(1). 

If I am reading this correctly, the $htmlPurifier is instantiated on line 1258 at the time $data_type 34 is being called. But there is no use statement. I just brought in the htmlpurifier-bundle into my dev. I will report back once I have tested and coded it in.

**Comment by bradymiller** [comment]
bump

**Comment by bradymiller** [comment]
bump

**Comment by juggernautsei** [comment]
My latest report on this feature application. IMO it is not needed. CKEditor 4 has an Advanced Content Filter (ACF). https://ckeditor.com/docs/ckeditor4/latest/guide/dev_best_practices.html#security

This can be used as a prescreening tool for the information typed into the textarea1. 
https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html#configuring-acf

We can modify the config to remove tags that should not be used in the note that is being created. 
Which tags should be restricted?

The can be an issue with the HTML purifier removing all markup.
https://stackoverflow.com/questions/15678624/htmlpurifier-removes-all-the-formatting-done-by-ckeditor

IMO we should utilize what is inside the CKEditor to manage XSS.

**Pull request closed without merging**
