### PR TITLE
Patient menu hook

### PR DESCRIPTION
**Pull request by kchapple**
Added event and hook to allow 3rd party modules to modify the tab navigation in the patient dashboard, similar to the main menu

Fixes #

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @kchapple ,
Code looks good to me. Just let me know it's testing well for you, and then I'll bring it in (i can quickly fix the styling also). thanks! -brady

**Comment by kchapple** [comment]
@bradymiller yes, testing well. Thank you.

**Comment by sjpadgett** [comment]
I Jerry, being a great and powerful OpenEMR project Administrator hereby approves this fine work by Ken, a long time contributor.
Thus will now merge for the benefit of all.

I have spoken!

**Comment by bradymiller** [comment]
tenor (58)

**Comment by sjpadgett** [comment]
Brady and Stephen W. hoping for an Earldom.

**Comment by stephenwaite** [comment]
is this ok to cherry pick into `rel-600`?

**Comment by bradymiller** [comment]
i think it's ok to bring into rel-600 (we can try to be more aggressive on stuff that goes into rel-600 as long as stuff is testing well to avoid things getting difficult to patch over in future)

**Comment by bradymiller** [comment]
now the Earldom will be tougher...

**Pull request merged**
