### PR TITLE
changed the straightforward external site requests to use guzzle

### PR DESCRIPTION
**Pull request by bradymiller**

### CODE REVIEW

**Comment by sjpadgett** [comment]
Why?

**Comment by bradymiller** [comment]
Been working out csrf for the internal api calls (it has actually been a lot of fun learning about api/guzzle stuff). Noted the oeHttp class is sending headers with sensitive data in it. Figured might as well just use straight guzzle for the simple calls.

**Comment by bradymiller** [comment]
Or is there benefit using oeHttp for the simple external calls?

**Comment by sjpadgett** [comment]
The main benefit would be mainly using for REST interfaces and easier to setup different types of calls/responses. If oeHttp is sending the csrf then it shouldn't and is a bug. We/I need to figure that out. Is it just the csrf token or other types of data?

**Comment by bradymiller** [comment]
It's sending the session id and csrf out as header:
https://github.com/openemr/openemr/blob/master/common/http/oeHttpRequest.php#L189-L192

**Comment by sjpadgett** [comment]
The call could have been written as:
oeHttp::setApiContext(true)->get('https://npiregistry.cms.hhs.gov/api/', $query);
SetApiContext sets native or external: default native.
I really need to document client because there is a lot it can do. Where and how it fits, beats me but it is supposed to make life easier especially for more complicated rest calls. Also, I don't believe a body format needs to be set for gets. I sometimes add to demo it is available in the api. Again, I need to document.
You can leave this as is if you want just want to point out, external is covered in api unless it doesn't work then, oops:)

**Comment by bradymiller** [comment]
Would rather keep using oeHttp (then will at least have a couple working examples in the codebase). I'll try above and also will flip-flop the default to external since only being used internally in one place so far (so easy for me to adjust that). Just makes me feel better knowing we won't inadvertently send sensitive data via headers when we forget this discussion (in about 1 week or so :) ).

**Comment by sjpadgett** [comment]
Sounds good because it is more likely to be used external before internal due to the fact that most needs for internal calls can simply call the controller/service directly. I used in fhir client as mainly a demo of the client as I could just have easily called by controllers for the internal calls. You will need to adjust the internal calls in the phpfhir provider client though..

**Comment by bradymiller** [comment]
@sjpadgett ,
New PR related to this is here: https://github.com/openemr/openemr/pull/2401

**Pull request closed without merging**
