### PR TITLE
Fix Font Awesome Paths (#3554)

### LINKED ISSUE #3554: Font Awesome path issue
### Describe the bug

Font Awesome breaks due to path issues.

### Expected behavior

No bugs

### PR DESCRIPTION
**Pull request by tywrenn**
Fixes #3554

#### Short description of what this resolves:

Resolves Font Awesome paths issue

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @tywrenn , Looks good and bringing in. I'll miss the mahjong tiles. Thanks for the quick fix! -brady

**Comment by stephenwaite** [comment]
looks like we still have write (delete) access to your report @tywrenn?

**Comment by tywrenn** [comment]
@stephenwaite That was on purpose for org admins to fix issues with pulls if I ever make any.

**Comment by stephenwaite** [comment]
pretty trustworthy crew
external-content duckduckgo com
until dessert time :)

**Pull request merged**
