### PR TITLE
Port custom modules

### PR DESCRIPTION
**Pull request by sjpadgett**
Maybe you guys can check me. I don't think I missed anything but this is me, don't cha know.....

### CODE REVIEW

**Comment by bradymiller** [comment]
Since you are adding new classes, we will need ensure those work with patch only (since there will not be a `composer dump-autoload -o` run). Note it should work (the nice benefit of placing all the psr4 classes in src directory :) ), but we need to make sure.

**Comment by bradymiller** [comment]
Also, whenever you think this is ready, then bring it in. Since my goal is to get a patch out this weekend, would be nice for this to be in there (and I'll do some sanity testing on it to ensure classes are seen etc.).

**Comment by sjpadgett** [comment]
Since to install the module a composer require openemr/oe-module-faxsms is needed the classes will be taken care of in that event.
I'm going to do an install on a ubuntu v502 in the morning and if goes well will bring this in. Too tired tonight

**Comment by bradymiller** [comment]
A good test (without the module installed) will be to ensure the patient report screen works since that uses one of the new classes. I'll plan to test then when create the patch in the future.

**Comment by bradymiller** [comment]
Actually, maybe not :) (disregard my post above)

**Comment by sjpadgett** [comment]
hi @bradymiller I created a testing patch for everything in current v502 from Head through commit 35a67d1. I just use a command like `git archive -o ../patch/502p1.zip HEAD $(git diff --name-only 8ce9069 --diff-filter=ACMRTUXB)` for testing this stuff.

I've install 3 times on windows and 2 on ubuntu. Tested before oe-module-faxsms install and after.
All good so hopefully haven't missed anything so bringing this in....

**Pull request merged**
