### PR TITLE
move to psr12

### PR DESCRIPTION
**Pull request by stephenwaite**
moving away from deprecated psr-2

### CODE REVIEW

**Comment by bradymiller** [comment]
interesting that the travis psr check is throwing errors since it should be using the same rules from the ci/phpcs.xml script

**Comment by stephenwaite** [comment]
looks like have to use `"squizlabs/php_codesniffer": "4.*"` to get to `PSR-12`

**Comment by bradymiller** [comment]
looks like 3.5.5 is the current stable release. so prob gonna have to wait on this until they release 4

**Comment by bradymiller** [comment]
nice, just saw you most recent commit. so sounds like we are good staying on 3

**Comment by stephenwaite** [comment]
might be the worst travis fail in history lol
Screenshot from 2020-04-20 08-09-53

**Comment by stephenwaite** [comment]
will try again in #3403

**Comment by bradymiller** [comment]
you can be the travis decoy, so then travis won't bother anybody else

**Comment by stephenwaite** [comment]
gave travis quite the beating yesterday and finally had to kill a job that ran for 19 hrs :0

**Comment by bradymiller** [comment]
i have no sympathy for travis (modern day bloodsucker) :)

**Pull request closed without merging**
