### PR TITLE
Billing tools aronracho

### PR DESCRIPTION
**Pull request by rachoac**
Making pre billing issues report comply with new security practices
adding support for mode to htmlspecialchars.inc.php

### CODE REVIEW

**Comment by tmccormi** [comment]
@bradymiller Aron has picked the branch back up  and it's ready for review.

**Comment by rachoac** [comment]
Brady I did just one of the features first to get some initial feedback, if that looks ok I will do the rest similarly

**Comment by bradymiller** [comment]
Agree with doing one first. I'll look at it this evening.

**Comment by bradymiller** [comment]
Placed a review on both commits. Recommend getting conversion of interface/reports/pre_billing_issues.php squared away before spending time on converting the others.

**Comment by rachoac** [comment]
Thanks Brady. I will make a pass on that report first based on your latest comments.AronSent from Yahoo Mail for iPhoneAt May 27, 2015, 5:19:04 PM, Brady Miller wrote:Placed a review on both commits. Recommend getting conversion of interface/reports/pre_billing_issues.php squared away before spending time on converting the others.

**Comment by rachoac** [comment]
@bradymiller I went through and tried to apply your review to the checkin, and changed the following:

interface/reports/aging_report.php
interface/reports/api/PreBillingIssuesAPI.php
interface/reports/pre_billing_issues.php
library/htmlspecialchars.inc.php

Please have a look at my latest checkins and see if they look good from your end. Thanks for the review thus far.

**Comment by Wakie87** [comment]
Hi,

We thank you for your submitting a pull request to OpenEmr. Without contributions like this from the community these types of projects go stale.

Currently we are going through and doing a spring clean of old and outdated pull requests. We are giving contributors the chance to update the code they submitted if they think it is still relevant, close the pull requests themselves, or if we do not hear back within 3 days we will close the pull request ourselves. If you believe that closing the pull request is an error, let us know and we will look at re-opening it.

In case you do not already know, there is some documentation on the wiki for developers here: http://open-emr.org/wiki/index.php/OpenEMR_Wiki_Home_Page#Developer_Manuals

Just remember every single bit you contribute to an open source project counts. The more you contribute the better, but even fixing one small typo in a translation will make the final product better.

Thanks

The OpenEMR Team
http://www.open-emr.org/

**Comment by teryhill** [comment]
@Wakie87 I have incorporated some of these changes already in to OpenMER

**Pull request closed without merging**
