### PR TITLE
updated 3rd party composer packages

### PR DESCRIPTION
**Pull request by bradymiller**
Need to test.
The biggest update here is the symfony from 3.4 to 4.4 (4.4 was just released and is a LTS release).

### CODE REVIEW

**Comment by bradymiller** [comment]
Looks like some fixes will need to happen regarding the symfony 4.4 upgrade since getting white screen of death instead of login screen with following error:
```
The &quot;event_dispatcher&quot; service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.#0 /var/www/localhost/htdocs/openemr/vendor/symfony/dependency-injection/Container.php(225): Symfony\\Component\\DependencyInjection\\Container-&gt;make(&#039;event_dispatche...&#039;, 1)\n#1 /var/www/localhost/htdocs/openemr/vendor/symfony/dependency-injection/ContainerBuilder.php(555): Symfony\\Component\\DependencyInjection\\Container-&gt;get(&#039;event_dispatche...&#039;)\n#2 /var/www/localhost/htdocs/openemr/src/Core/Kernel.php(99): Symfony\\Component\\DependencyInjection\\ContainerBuilder-&gt;get(&#039;event_dispatche...&#039;)\n#3 /var/www/localhost/htdocs/openemr/src/Core/ModulesApplication.php(48): OpenEMR\\Core\\Kernel-&gt;getEventDispatcher()\n#4 /var/www/localhost/htdocs/openemr/interface/globals.php(582): OpenEMR\\Core\\ModulesApplication-&gt;__construct(Object(OpenEMR\\Core\\Kernel), &#039;/var/www/localh...&#039;, &#039;interface/modul...&#039;, &#039;zend_modules&#039;)\n#5 /var/www/localhost/htdocs/openemr/interface/login/login.php(25): require_once(&#039;/var/www/localh...&#039;)\n#6 {main}, referer: http://localhost:8082/setup.php?site=default
```
@adunsulag , any thoughts on this? Is upgrading symfony to 4.4 too ambitious at this time?

**Comment by adunsulag** [comment]
@bradymiller I'd have to dig into it.  The Kernel class has to be updated to use whatever 4.4 is now requiring since we can't directly use the $this->container->get('event_dispatcher') on line 99 in Kernel.php.  3.4 is supported as an LTS release until November 2020 https://symfony.com/releases/3.4

Was there a need to go 4.4 at this point in time?  Its a major release and I don't know what / if any ramifications downstream there may be.

**Comment by bradymiller** [comment]
hi @adunsulag ,
I basically just update all the composer packages every couple months. We can always stay at 3.4 for now (but we will need to jump to 4.4 at some point). If we should delay the 4.4 updates for now, just let me know, and then I'll keep it at 3.4 for this update.
thanks,
-brady

**Comment by adunsulag** [comment]
@bradymiller Can we stay at 3.4 for now and I'll put it on my task list to look at the 4.4 upgrade changes?  That is if you want me to look into it as it will be a few weeks off, if someone else wanted to look into it like @robertdown that's fine too.

**Comment by bradymiller** [comment]
Sounds good :)
I'll keep 3.4 and make an issue for going to 4.4.

**Comment by bradymiller** [comment]
This is testing well (dropped symfony back to 3.4 branch), so bringing into codebase.

**Pull request merged**
