### PR TITLE
Removing extraneous whitespace and condensing HTML

### PR DESCRIPTION
**Pull request by robertdown**

### CODE REVIEW

**Comment by bradymiller** [comment]
This code is Terry's baby, so I'll ask him to look at this.
@teryhill

**Comment by teryhill** [comment]
I like what you have done. I did notice on testing that the Blinking of the time over is outside the box on the bottom. The font is small for my old eyes. It title line does not stand out as well it blends in with the background.

Code wise I like what you have done to clean it up and condense it The look and feel is just different.

**Comment by robertdown** [comment]
I made the font smaller as there is so much information on this screen I thought it prudent to sacrifice some font size to better layout the content. I agree it's smaller than the ideal, but I think it's a solid compromise due to the large horizontal axis of info.

I feel like the title doesn't need to stand out as much as it did - people know that at the top of a table of data there is usually a header.

I need to look at the blinking issue.

Also, I'm going to submit some better default colors for the appointment statuses. I think the colors as they are now are much too saturated. I'm attaching a screenshot of the colors I want to move towards. 

screen shot 2015-08-04 at 02 29 39

**Comment by robertdown** [comment]
Thoughts on axing the PID column, moving the encounter to the Patient column and just appending the patient. Example: Last name, First name [encounterID]. Maybe renaming "Exam Room #" to just Room # and "Arrival Time" to "Arrived" and "Current Status Time" to just "Status Time"?

This would reduce the number of columns and the overall width of the table which means we *might* be able to bump the font-size back up.

**Comment by teryhill** [comment]
Defaults are changeable by the end user and are only meant as an example. Just as the end user can change the status codes , times and colors themselves to what they want.The PID was requested by an end user. The users currently using the code are satisfied with it.

 I would like to see it released as it was designed and as is. There was a large amount of opportunity for input on this code via the forum the entire time it was being produced, updates were regularly posted, and all input that was given was considered. The code is available and you can make the changes for your users as they request but right now I vote to release as is.. I will also say that if at sometime in the future the appearance needs to be changed, by being requested from the users , it is in my opinion the responsibility of the developer that changes it to upgrade the WIKI to reflect those changes.
Respectfully 
Terry

**Pull request closed without merging**
