### PR TITLE
fix log for viewing pid

### LINKED ISSUE #1568: view event in log storing pid in comments not pid column
can see this on this demo under admin->other->logs
https://one.openemr.io/a/openemr/interface/login/login.php?site=default

after choosing phil belford the entry in the log shows 

> Date | Event | Category | User | Certificate User | Group | PatientID | Success | Comments
-- | -- | -- | -- | -- | -- | -- | -- | --
2018-04-21 13:09 | view | view | admin |   | Default |   | 1 | 1
-- | -- | -- | -- | -- | -- | -- | -- | --

>

### PR DESCRIPTION
**Pull request by stephenwaite**
should fix #1568

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @stephenwaite ,
looks good and will bring into codebase (and also bring into 5.0.1)
(I also found 2 more place where this needs to be fixed and will do in a subsequent commit)
thanks for the fix! -brady

**Comment by bradymiller** [comment]
actually, there was just 1 other place, which fixed in a subsequent commit

**Comment by stephenwaite** [comment]
cool, didn't even think about looking for others, phpstorm noob here
came across while trying to hunt down a serious prob for a customer and found the below in the log, it seems like a pid is set but when they went back to vitals it grabbed the prior pid

> 

2018-04-20 13:37:40 | view | view | Chris |   | Default |   | 1 | 6874
-- | -- | -- | -- | -- | -- | -- | -- | --
2018-04-20 13:38:40 | patient-record-replace | Billing | Chris |   | Default | 2925 | 1 | REPLACE INTO form_vitals SET  `id` = '67650', `date` =  '20180420133700', `pid` = '6874', `activity` = '1', `bps` = '134',  `bpd` = '70', `weight` = '133', `pulse` = '72'
2018-04-20 13:38:40 | patient-record-insert | Encounter Form | Chris |   | Default | 2925 | 1 | insert into forms (date, encounter, form_name,  form_id, pid, user, groupname, authorized, formdir) values (NOW(), ?, ?,  ?, ?, ?, ?, ?, ?)  ('20180420','Vitals','67650','2925','Chris','Default','0','vitals')
2018-04-20 13:39:23 | view | view | DrDier |   | Default |   | 1 | 10394
2018-04-20 13:40:49 | patient-record-update | Billing | Chris |   | Default | 2925 | 1 | update form_dictation set pid =  ?,groupname=?,user=?,authorized=?,activity=1, date = NOW(), dictation=?,  additional_notes=? where id=?  ('2925','Default','Chris','0','Subjective:  Return visit for rheumatoid  factor positive, anti-ccp positive rheumatoid arthritis and  osteoarthritis with spondylosis and hypertension.  Increased generalized  discomfort.  Has also experienced anterior chest wall discomfort.  Seen  by Patricia Brown.  Abnormal EKG prompted further evaluation.   Subsequently ruled out for myocardial infarction.  Stress test and  echocardiogram are pending.  Tolerating gabapentin at 100 mg h.s.   Continues to sleep poorly.\r\n\r\nObjective:    Vital signs as  shown\r\n\r\nskin-  No rash\r\nHEENT-  \r\nneck-  \r\nheart-  Distant,  regular, no murmur.  Tenderness on palpation of the costochondral  margins and lower rib cartilage.\r\nlungs-  Decreased breath sounds,  prolonged expiratory phase.  No wheezing\r\nabdomen-  \r\nextremities-   Enlargement at the DIPs, PIPs and first MCPs again noted.  Trace  effusion at the right knee with trace dependent edema and bony  enlargement at the first MTPs.\r\nneuro-  Cranial nerves II-XII intact.    Normal and symmetric reflexes, strength and sensation.\r\n\r\nLab  Results:  \r\n\r\nAssessment:  Rheumatoid arthritis remains quiescent.   Osteoarthritis and spondylosis symptomatic but stable.  Chest wall pain  likely secondary to costochondritis. She is at increased risk for  vascular disease with hypertension, smoking and rheumatoid arthritis as  risk factors.\r\n\r\nPlan:  Increase gabapentin to 200 mg h.s. and if  tolerated, increase to 300 mg at h.s. Strongly encouraged her to  followup with her stress test and echocardiogram. Followup here  7/13/18.\r\n\r\nDouglas L Dier MD\r\nCc:  Patricia Brown,  NP\r\n','','25050')

**Comment by stephenwaite** [comment]
see how for user Chris who believed was working on pt id 6784 was in fact writing speech dictation into 2925?

**Comment by stephenwaite** [comment]
also interesting that when you create a new vitals form and save it the log shows it as a "REPLACE INTO"

**Comment by stephenwaite** [comment]
turns out the dictations were stored in the form_dication table under a previous patient id

nasty little bug somewhere...

**Comment by bradymiller** [comment]
My guess is related to a session leak(ie. open another openemr tab in same web browser in a vulnerable script). Although the code should not be vulnerable to this issue, this is why we are strict about following in the codebase:
https://www.open-emr.org/wiki/index.php/OpenEMR_System_Architecture#PHP_Sessions_and_Browser_Windows
(if code doesn't do this, then session leaks are possible)

**Comment by stephenwaite** [comment]
thanks Brady, looks like i introduced it for multi-site with an if statement here
https://github.com/stephenwaite/openemr/blob/ron_reports/interface/patient_file/report/patient_report.php#L180
with a different action based on site_id

**Pull request merged**
