### PR TITLE
utf8mb4 support

### PR DESCRIPTION
**Pull request by bradymiller**
Initial testing is good. Still a bunch more testing to do:
1. On all 8 mysql/mariadb version (UPDATE: now just six :) ) **DONE**
2. Ensure backward compatible for upgraders **DONE**
3. Ensure actually working in all contexts (core, calendar, gacl, doctrine, portal, zend) **DONE**

### CODE REVIEW

**Comment by bradymiller** [comment]
Looks like mariadb 10.1 and mysql 5.6 have rather strict key size limits which are gonna require some effort to fix. Thinking best option to to drop support for mariadb 10.1 and mysql 5.6 since they are at end of life in 10/2020 and 2/2021 anyways.

**Comment by bradymiller** [comment]
just a quick example of what utf8mb4 allows (emoticons in messages):

image

turns out utf8(which is utf8mb3) is limited since only uses 3 bytes, whereas pure utf8 should have 4 bytes (utf8mb4) and then allows many more characters (including some chinese characters and emoticons and bunch of other characters).

**Comment by tywrenn** [comment]
@bradymiller I enabled system emoticons through SCSS -- didn't realize that this was also a required step 😂

**Comment by bradymiller** [comment]
testing well and bringing this in (along with companion docker and demofarm changes). hopefully will not have to think about this again for another 8 years :)

**Pull request merged**
