### PR TITLE
Portal Update Forum Request 

### PR DESCRIPTION
**Pull request by sjpadgett**
- add disable patient ledger
- fix hide menu in Reports
requested here: https://community.open-emr.org/t/how-to-hide-appointments-menu-from-patient-portal/11223

### CODE REVIEW

**Comment by bradymiller** [comment]
looks good to me :)

**Comment by sjpadgett** [comment]
Changed my mind and will just remove Accounting menu if all items are disabled.
Bringing in after that Travis fella is done.

**Comment by hashimea** [comment]
now disabling Document Download is hiding Report Content too. I think it is a bug

**Comment by sjpadgett** [comment]
@hashimea Report Content is a document download! There is only one reason I allow turning off documents download in the first place, that being, mental health practices where physicians need some level of privacy in there notes and assessments. Otherwise, if it is in the patient chart, they have a right to have access. Note the period.

**Comment by hashimea** [comment]
@sjpadgett  
I think there is some misunderstanding, 
Point
1) I never asked a solution for hiding the reports or document download.
2) Hiding appointments and ledger (accounting) was my request and it was because I am not using appointment and billing. and the solution here is working fine now.

3)  In patient Portal, There is sidemenu entry "Reports" and 2 submenu as dropdown
    1) Report Content  2) Document Download
  I just reported a bug when I tested the hide "document download" option as i seen your comment above.

When hiding document download, I believe your plan was to hide the 2nd submenu (Document Download only and just showing Report Content ( 1st submenu) , Or Entire Reports Menu should disappear. 

But now when using that disable function, The Reports menu and Reports Content Submenu visible but not usable.  I just reported that. Hope you understood.

**Comment by sjpadgett** [comment]
@hashimea 
Nope, did not misunderstand. You said it is a bug and i'm saying it is not:) I left the Report Menu in tact and disabled so the patient knows that feature is available. A little sly but, that's me! Besides, there was a bug in that though the Document Download appeared  in the menu, it was still disabled. I merely took out the menu item. Document Download allows one to pull down all documents as a zip whereas, Report Content allows one to chose which documents. So in the end they do the same thing thus, disable one, disable both...
btw thanks for your work

**Comment by sjpadgett** [comment]
Works fine for me but i'm on windows right now.

**Comment by hashimea** [comment]
Worked now, 
Issue was empty documents. getting zero size zip. Better to add some message (Like "No Documents") than allowing corrupted zip download.

**Comment by sjpadgett** [comment]
Naw, chances are before portal access is ever turned on, patient will have a document but if you want to add, it can't hurt...

**Pull request merged**
