### PR TITLE
Portal credentials port from 503 PR #2715

### PR DESCRIPTION
**Pull request by sjpadgett**
@stephenwaite Did I not see some sql table changes for ICD10 external dataloads belonging in 502 patch.sql?

### CODE REVIEW

**Comment by stephenwaite** [comment]
don't think so 
been thinking of a simpler mechanism to upgrade that since there are only a few hundred codes that need to be fixed and are included in their own addenda file

**Comment by stephenwaite** [comment]
hmm, maybe you're right and they're only in the 5.0.2 to 5.0.3 upgrade, nice catch

**Comment by stephenwaite** [comment]
maybe this is the time to add the new mechanism that would read this file
[icd10cm_codes_addenda_2020.txt](https://github.com/openemr/openemr/files/3714619/icd10cm_codes_addenda_2020.txt)

**Comment by sjpadgett** [comment]
well i'll at least update the patch w/icd10 stuff. Did Brady bring back any code fixes that went with those table mods?

**Comment by stephenwaite** [comment]
no, would have to grab https://github.com/stephenwaite/openemr/blob/master/library/standard_tables_capture.inc#L55-L61

**Pull request closed without merging**
