### PR TITLE
5.0.2 med ex

### PR DESCRIPTION
**Pull request by ophthal**
API.php will only sync q60 minutes

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @ophthal ,
There are 5 commits here and some look rather old. Which commits do you want to bring into codebase? -brady

**Comment by ophthal** [comment]
Did I build this off an old branch?  What is the best branch to build from and I will do a new pull request to make sure only the needed stuff gets included?

**Comment by bradymiller** [comment]
hi @ophthal ,

Should be building new PR's from the most recent master branch:
https://github.com/openemr/openemr

Hopefully you can do that with your most recent PRs since I may not be able to spend time cleaning them up prior to the release in a couple days.

thanks, -brady

**Comment by ophthal** [comment]
OK I  was building from rel-502.  Here they come...

**Comment by bradymiller** [comment]
hi @ophthal ,
When you stated "here they come...", do you mean the other 2 PR's or did you make the changes to this PR?

**Pull request closed without merging**
