### PR TITLE
fix: Ensure proper bootstrap classes for PAMI list

### LINKED ISSUE #6965: bug: Divide By Zero Fatal Error if PAMI not authorized
On MRD, if the user does not have access to view allergies, problems, meds, and RX, `$cards` will be 0. Later, when determining the number of columns to use, `$cards` is the denominator. This could lead to a `PHP Fatal error:  Uncaught DivisionByZeroError: Division by zero`

### PR DESCRIPTION
**Pull request by robertdown**
Ensure `$cards` is never less than 1, render proper bootstrap classes. Resolves #6965

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @robertdown , Just ensuring that this tests ok for user with receptionist acl in your testing?

**Comment by robertdown** [comment]
You mean for "Front Office" ACL? Yes, it looks ok for that ACL.

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
2DV

**Comment by adunsulag** [comment]
@robertdown @bradymiller Can we bring this in?  I'm assuming we need this for release 7.0.1.

**Comment by bradymiller** [comment]
Bringing in and will bring into rel-702 branch.

**Pull request merged**
