### PR TITLE
creating ParseERA class and updating X12 5010 remit codes

### PR DESCRIPTION
**Pull request by stephenwaite**
this looks pretty ugly but it comes from the authority http://www.wpc-edi.com/reference/codelists/healthcare/remittance-advice-remark-codes/

### CODE REVIEW

**Comment by stephenwaite** [comment]
ok, found this nice guide, https://stackoverflow.com/questions/3446216/what-is-the-difference-between-single-quoted-and-double-quoted-strings-in-php#3446286, guess i'll redo with single quotes and escape the patient's

**Comment by bradymiller** [comment]
hi @stephenwaite . Code looks good to me. Just let me know when I can bring it in. thanks! -brady

**Comment by stephenwaite** [comment]
ok, it's testing well, thanks Brady

one thing that gave me trouble testing was the oeui class wasn't loading until i wiped out the docker with the `docker-compose down -v` and brought it back up. Am I missing a shortcut?

**Comment by bradymiller** [comment]
OEUI class required a new composer class directory that was added in composer.json, so the following would of likely got it working:
```
composer dump-autoload -o
```

**Comment by bradymiller** [comment]
And thanks for the new class! Bringing it into codebase now. -brady

**Comment by stephenwaite** [comment]
ok, thanks

**Pull request merged**
