### PR TITLE
Add zend component (mvc-console)

### PR DESCRIPTION
**Pull request by matrix-amiel**
Hi!

In our zend modules we are using with console functionallity. In the migration to Zend3 the actions from the console were stopped because the zend-mvc-console is missing.
Here I add that component.

We also found that zend-mvc-console is deprecated in Zend 3... but It's still working and we need it until we will find another solution... :) 

Thanks
Amiel

### CODE REVIEW

**Comment by adunsulag** [comment]
@matrix-amiel I'm ok with bringing the console back in but can you add to your comments in the source code by the package inclusion that the package is deprecated and is only there for legacy applications?  I took the console out because Zend said it was deprecated.  We don't want people trying to build future console applications on top of the deprecated code.

Has your team looked at Zend's recommended package to migrate to: https://github.com/zfcampus/zf-console
?

**Comment by matrix-amiel** [comment]
I already took a look on zf-console, it's not working with the existing routing and needed a lot of changes, we consider the possibility of use with that library in the future.

**Comment by bradymiller** [comment]
Thanks for looking at this @adunsulag . If your ok with this, then bringing this into codebase. I'll add the comment to composer.json -brady

**Comment by bradymiller** [comment]
Actually, it looks like I can't add comments to a json file. bummer.

**Comment by bradymiller** [comment]
oops, just realized what you meant. I just committed the comment at the use statement

**Pull request merged**
