### PR TITLE
Fix encounter permissions

### PR DESCRIPTION
**Pull request by matrix-amiel**
Hi!
Here I hide a details of encounter from user with low  sensitivity permission.
Now in the list of encounters there is access denied but not in the encounter screen.

Thanks
Amiel

image

### CODE REVIEW

**Comment by robertdown** [comment]
Hi @matrix-amiel, I'm cleaning up your extraneous merge commits before bringing this in to the codebase. See https://github.com/openemr/openemr/pull/707

**Comment by bradymiller** [comment]
@matrix-amiel @robertdown 
Fixing just this 1 instance won't fix the issue. Matrix has a central master branch that they work off (at least it did in the past). We just need to clean up that master branch to prevent this from happening in the future.

@matrix-amiel , Is your group still using a central master branch? If so, who can I contact to provide instructions on cleaning it up?

thanks,
-brady

**Comment by bradymiller** [comment]
@matrix-amiel @sharonco-matrix ,
I brought this code improvement into the codebase.

It's time for spring cleaning of your master branch. This can be done via the following instruction set:

A messy master branch is a relatively common issue. Two steps to fix this are, 1) clean up the master and then 2) ensure keep the master clean.
``````
step 1 (basically will drop your master branch and bring in a clean master branch):
git fetch upstream
git checkout -b temp
git branch -d master
git checkout upstream/master
git checkout -b master
(you now have a clean master that was taken from the main codebase)
And can then push this to your origin on github:
git push origin +master

step 2 (whenever update your master, use the following):
git checkout master
git fetch upstream
git pull upstream master
git push origin master
``````
You should never merge into your master and should never do work on the master. Then when you create a branch from master, it will be pristine.

**Comment by matrix-amiel** [comment]
O.K.
I did it.

Thank you!

**Pull request closed without merging**
