### PR TITLE
Simplified maintenance for service provider parameters

### PR DESCRIPTION
**Pull request by mdsupport**
Single screen access and addresses #376

### CODE REVIEW

**Comment by sunsetsystems** [comment]
Looking at this today... apologies for the delay.

**Comment by sunsetsystems** [comment]
Doing a fresh install I see some issues right away.
1. The widget is too small for its content and should not take up space when it's not being used.
2. Protocol does not appear in the list.
3. Aren't we using fancybox for modal dialogs? I don't like it much either, but we need to settle on a standard replacement for dlgopen() etc. and not re-invent it for each use case.

**Comment by sunsetsystems** [comment]
Sorry I should have included this screenshot.
screenshot at 2017-01-05 13-37-34

**Comment by mdsupport** [comment]
1. Needed bootstrap css - we have that as standard in all styles.
2. Needed font-awesome css -  we have that as standard in all styles.
3. There is no need for a dialog when that content can be displayed inline.

**Comment by sunsetsystems** [comment]
That's much better, looks very nice!  I'm not seeing any issues.  Just need to deal with the branch conflicts.

**Comment by sunsetsystems** [comment]
Noticed one bug... if you choose to edit a provider then cancel the iframe, the provider line remains highlighted.  It should go back to normal as it does when you save.

**Pull request closed without merging**
