### PR TITLE
Adding a review option to the about us page.

### PR DESCRIPTION
**Pull request by juggernautsei**
Public reviews will help to bring mainstream people to the OpenEMR platform. 

below added by bradymiller:
Up for grabs demo for this PR here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Mu_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by sjpadgett** [comment]
Adding a review option inside installed software is never a good idea, imo. It becomes a complaint rant outlet. In most cases that someone will actually take time to review, it is because of negative impressions and because of people, being people, satisfied users just assume that because the software is working to their expectation(they already reviewed when selecting OpenEMR) no positive review is necessary. So on balance, negative will always trump(no,no, not a pun) positive.
I get it Sherwin. We need good feedback. May I suggest that instead of a review we do something like a "We strive to be better partners, how can we improve?" which in the question itself leads the user to feel they are part of solutions. A follow on question could be "What do you most value in OpenEMR?" or something along those lines. I just would not hope to pin marketing from in application reviews.

**Comment by juggernautsei** [comment]
Thoughts well received. I worked in restaurants during the first part of my life and made it all the way to management. People do complain a lot and as in the thread, people have more zeal when they are complaining then when they are satisfied.  
An open question to people is a challenge because without specifics most people have a hard time voicing a concern or thinking of a concern. The question, how can we improve is too broad. How can we improve support? Is more specific and allows the user to focus on a specific issue rather than trying to sort through their mind and find something to talk about.  
Whether we want to admit it or not. Marketing in today's world is driven a lot by application reviews.  People value other peoples opinion especially if they don't know the person. More people shop by review than those who don't. We who don't look at reviews are in the minority. And as always majority rules. That is why we have Trump no matter how many complaints we are getting.

**Comment by sjpadgett** [comment]
What ever the question phrasing, I feel marketing a free application should be based on capabilities leading to getting feedback on improving those. Besides, where will the reviews be published once we get them back? Who will review for content if published straight to forum e.t.c? I like this idea Sherwin but we only have one shot at how any data from this being perceived as credible. Just saying the better opportunity here lies with feedback rather than review.
I don't oppose doing the review and just offering my opinion. Thanks.

**Comment by juggernautsei** [comment]
Jerry, I appreciate the conversation. It is very welcomed. The site is monitored by me since I found it 4 years ago.

**Comment by bradymiller** [comment]
Up for grabs demo for this PR here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Mu_-_Up_For_Grabs_Demo

**Comment by bradymiller** [comment]
the demo doesn't look very good :)
not your fault @juggernautsei (this codebase can't build because a insecure package was removed from the npm ecosystem)
I'll place this on another PR with updated codebase

**Comment by bradymiller** [comment]
Gonna close this since new PR for this is here:
https://github.com/openemr/openemr/pull/2021

**Pull request closed without merging**
