### PR TITLE
Edit openemr-api.yaml to to pass validation

### LINKED ISSUE #6967: openemr-api.yaml fails validation when generating client library with openapi-generator
### Describe the bug
/api/patient/{pid}/message/{mid} and /fhir/Group/{id}/$export do not pass validation when generating a client api with openapi-generator

I will submit a PR shortly to remedy.

### To Reproduce

1. Run openapi-generator on openemr-api.yaml
```bash
openapi-generator generate -i openemr-api.yaml -g python -o /tmp/test
```
```
openapi-generator generate -i openemr-api.yaml -g python -o /tmp/test
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 2, Warning count: 0
Errors:
	-paths.'/api/patient/{pid}/message/{mid}'. Declared path parameter mid needs to be defined as a path parameter in path or operation level
	-paths.'/fhir/Group/{id}/$export'. Declared path parameter id needs to be defined as a path parameter in path or operation level

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:668)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:695)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:503)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

### Expected behavior
No errors given and client api generated.

### PR DESCRIPTION
**Pull request by eva-val**
Fixes #6967

#### Short description of what this resolves:
Corrected field name on /api/patient/{pid}/message/{mid}

Added parameters to /fhir/Group/{id}/$export

### CODE REVIEW

**Comment by adunsulag** [comment]
@eva-val This file is generated automatically.  You should actually modify the [_rest_routes.inc.php](https://github.com/openemr/openemr/blob/master/_rest_routes.inc.php) file which is where the file is generated from using the ```bin/commander-runner -c CreateAPIDocumentation``` command.

**Comment by adunsulag** [comment]
@eva-val Were you still wanting to correct the  /api/patient/{pid}/message/{mid} endpoint?  Or is this ready to bring in?  The group endpoint fixes looks fine to me.

**Comment by eva-val** [comment]
Yes that was my intention and pushed the wrong commit. New to contributing so sorry if the pr is a little messy.
While further working with the api it appears that some endpoints are broken and I will have to open issues for those.
From what I can tell the fhir exports and standard insurance_company are not working. Should I open an issue for each endpoint?

**Comment by stephenwaite** [comment]
hi @eva-val , thanks for the PR, you can combine both endpoint fixes into 1 PR

**Comment by adunsulag** [comment]
@eva-val Are you saying the bulk fhir exports are not working? I'd be interested to know more details about that as I don't believe we've changed any of that functionality and our last checks passed the inferno test suite. I personally like separate issues if the behaviors are not related, keeps the PRs/review a bit cleaner but if the broken pieces are connected, fine to combine them.  That's my preference though so not a requirement on what you have to do as you can combine it.

**Comment by eva-val** [comment]
@adunsulag Yes unless I'm just doing something way wrong, but I tried it on the dev/prod docker and the demo servers and it was still erroring.

Trying again on another demo
https://demo.openemr.io/a/openemr/i

1. Generated JWT from here https://mkjwk.org/
-Key size: 2040
-Key use: Signature
-Algorithm: RS384
-Key ID: SHA-256
-Show X.509: Yes

2. Registered client on OpenEMR 
```bash
curl --location 'https://demo.openemr.io/a/openemr/oauth2/default/registration' \
--header 'Content-Type: application/json' \
--data-raw '{
    "application_type": "private",
    "redirect_uris": [
        "https://localhost:8180/redirect"
    ],
    "post_logout_redirect_uris": [
        "https://localhost:8180/logout"
    ],
    "client_name": "New JWT App 15",
    "initiate_login_url": "https://localhost:8081/launch",
    "token_endpoint_auth_method": "client_secret_post",
    "contacts": [
        "me@example.org"
    ],
    "scope": "openid fhirUser online_access offline_access launch launch/patient api:oemr api:fhir api:port system/Patient.$export system/Group.$export system/*.$bulkdata-status system/*.$export profile name address given_name family_name nickname phone phone_verified email email_verified site:default patient/AllergyIntolerance.read patient/Appointment.read patient/Binary.read patient/CarePlan.read patient/CareTeam.read patient/Condition.read patient/Coverage.read patient/Device.read patient/DiagnosticReport.read patient/DocumentReference.$docref patient/DocumentReference.read patient/Encounter.read patient/Goal.read patient/Immunization.read patient/Location.read patient/Medication.read patient/MedicationRequest.read patient/Observation.read patient/Organization.read patient/Patient.read patient/Person.read patient/Practitioner.read patient/Procedure.read patient/Provenance.read system/AllergyIntolerance.read system/Appointment.read system/Binary.read system/CarePlan.read system/CareTeam.read system/Condition.read system/Coverage.read system/Device.read system/DiagnosticReport.read system/DocumentReference.$docref system/DocumentReference.read system/Encounter.read system/Goal.read system/Group.read system/Immunization.read system/Location.read system/Medication.read system/MedicationRequest.read system/Observation.read system/Organization.read system/Patient.read system/Person.read system/Practitioner.read system/PractitionerRole.read system/Procedure.read system/Provenance.read user/AllergyIntolerance.read user/Appointment.read user/Binary.read user/CarePlan.read user/CareTeam.read user/Condition.read user/Coverage.read user/Device.read user/DiagnosticReport.read user/DocumentReference.$docref user/DocumentReference.read user/Encounter.read user/Goal.read user/Immunization.read user/Location.read user/Medication.read user/MedicationRequest.read user/Observation.read user/Organization.read user/Organization.write user/Patient.read user/Patient.write user/Person.read user/Practitioner.read user/Practitioner.write user/PractitionerRole.read user/Procedure.read user/Provenance.read",
    "jwks": {
        "keys": [
            {
                "kty": "RSA",
                "e": "AQAB",
                "use": "sig",
                "kid": "P-jTiSMNu79wVc7NjIuNKM_ozfLbIzxom4mS0xgTlwI",
                "alg": "RS384",
                "n": "oibF4m0Vbb9rf-JybLLdPp3LPW_IPUVfe0bemeuMZR_-tjzEFY_BejmPX2xM5CeqAi9FqmSv5jQyekVvZuQd5LPfjvqPdI3Hgv6wUafek4DzA9bBNKMoqgLPvI9fBVhy1i8CHiqoOLVQfhsBM6tPYOic8mmynqlCnRZvV_AVH_2aDVGuecjbf47ovOSdygrL_oIIbkUzPuu65KB-WMkuEIPGen2-4ZE-lIA3Vp7Mf_85dIq7WoLsx5novQRIvTSIuRLgiDqOMoJ6v6H1TQmrfUA6ifd7oPGz_dOb3XoDxs56JPMTqMhSPcrrETuekQRwuzQrSgp0JaCZaWSwzfdnSQ"
            }
        ]
    }
}'
```
3. Enable api client
4. Sign JWT payload https://jwt.io/
Header: 
``` json
{
  "alg": "RS384",
  "typ": "JWT",
  "kid": "P-jTiSMNu79wVc7NjIuNKM_ozfLbIzxom4mS0xgTlwI"
}
```
PAYLOAD where sub&iss = client_id returned from registering
```json
{
  "sub": "nQbdl7WPENlr8KhLK8-MpxdLyGFDv8T_bAAhU6NcQrw",
  "iss": "nQbdl7WPENlr8KhLK8-MpxdLyGFDv8T_bAAhU6NcQrw",
  "aud": "https://demo.openemr.io/a/openemr/oauth2/default/token",
  "jti": "asdfasdfddsakf"
}
```
Payload signed with private key
5. Test grab token
```bash
curl --location 'https://demo.openemr.io/a/openemr/oauth2/default/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--form 'client_assertion_type="urn:ietf:params:oauth:client-assertion-type:jwt-bearer"' \
--form 'grant_type="client_credentials"' \
--form 'scope="openid fhirUser online_access offline_access launch launch/patient api:oemr api:fhir api:port system/Patient.$export system/Group.$export system/*.$bulkdata-status system/*.$export profile name address given_name family_name nickname phone phone_verified email email_verified site:default patient/AllergyIntolerance.read patient/Appointment.read patient/Binary.read patient/CarePlan.read patient/CareTeam.read patient/Condition.read patient/Coverage.read patient/Device.read patient/DiagnosticReport.read patient/DocumentReference.$docref patient/DocumentReference.read patient/Encounter.read patient/Goal.read patient/Immunization.read patient/Location.read patient/Medication.read patient/MedicationRequest.read patient/Observation.read patient/Organization.read patient/Patient.read patient/Person.read patient/Practitioner.read patient/Procedure.read patient/Provenance.read system/AllergyIntolerance.read system/Appointment.read system/Binary.read system/CarePlan.read system/CareTeam.read system/Condition.read system/Coverage.read system/Device.read system/DiagnosticReport.read system/DocumentReference.$docref system/DocumentReference.read system/Encounter.read system/Goal.read system/Group.read system/Immunization.read system/Location.read system/Medication.read system/MedicationRequest.read system/Observation.read system/Organization.read system/Patient.read system/Person.read system/Practitioner.read system/PractitionerRole.read system/Procedure.read system/Provenance.read user/AllergyIntolerance.read user/Appointment.read user/Binary.read user/CarePlan.read user/CareTeam.read user/Condition.read user/Coverage.read user/Device.read user/DiagnosticReport.read user/DocumentReference.$docref user/DocumentReference.read user/Encounter.read user/Goal.read user/Immunization.read user/Location.read user/Medication.read user/MedicationRequest.read user/Observation.read user/Organization.read user/Organization.write user/Patient.read user/Patient.write user/Person.read user/Practitioner.read user/Practitioner.write user/PractitionerRole.read user/Procedure.read user/Provenance.read"' \
--form 'client_assertion="eyJhbGciOiJSUzM4NCIsInR5cCI6IkpXVCIsImtpZCI6IlAtalRpU01OdTc5d1ZjN05qSXVOS01fb3pmTGJJenhvbTRtUzB4Z1Rsd0kifQ.eyJzdWIiOiJuUWJkbDdXUEVObHI4S2hMSzgtTXB4ZEx5R0ZEdjhUX2JBQWhVNk5jUXJ3IiwiaXNzIjoiblFiZGw3V1BFTmxyOEtoTEs4LU1weGRMeUdGRHY4VF9iQUFoVTZOY1FydyIsImF1ZCI6Imh0dHBzOi8vZGVtby5vcGVuZW1yLmlvL2Evb3BlbmVtci9vYXV0aDIvZGVmYXVsdC90b2tlbiIsImp0aSI6ImFzZGZhc2Rmc2RkZHNha2YifQ.WP0jfRr1Spp0ZGPOvZDFxD_G5XhBWGkHJ-GHAnMvNludqAw97-od8G9pu-fgtdMuu5oyc4s2phO_pfVJXB-kvOSjum4F-tE-mJliAROiQGL6ZgBr1OyLu5ALpH5K7ibkJpWVT4wS5emLiq4HYsVrAntmkd4P74e_2lctM2fAH0iJtCdPjBrOfBACxQXDgzesn0dYZUnc_ryC8P1P6QPbJZse4G8C_grRk1TxVbG3G-6-hUvmWSZdBnA7_1nlp5Q82TuJVLZ3Q4KT8RKmsGDbf5M7Q8EQyvJq03DITgAe3WXnJMWziMdOpNNxynlzRl12w43htZiwgrtBK0VtTRssOg"'
```
6. Test fhir/Patient (Returns 200 and bundles)
```bash
curl --location 'https://demo.openemr.io/a/openemr/apis/default/fhir/Patient' \
--header 'Accept: application/json+fhir' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJuUWJkbDdXUEVObHI4S2hMSzgtTXB4ZEx5R0ZEdjhUX2JBQWhVNk5jUXJ3IiwianRpIjoiZmFlNDBkYzc1Mzk1ZGEwYzUxZjlhYjlhZGZkYzYwMDE3MzE3ZDI5NDU3YWY1MGI2MGU0MzBkYzZlZTg0YzdiYjcwNjA0NjNhN2ZlMjVmM2EiLCJpYXQiOjE2OTk0MDg4NTguNzg0OTM5LCJuYmYiOjE2OTk0MDg4NTguNzg0OTQyLCJleHAiOjE2OTk0MDkxNTguNzYxMDU5LCJzdWIiOiI5YThkZmE1Mi0yNjk4LTRkYzUtYTQxOS05NmY1NTg1YWMzODYiLCJzY29wZXMiOlsib3BlbmlkIiwiZmhpclVzZXIiLCJvbmxpbmVfYWNjZXNzIiwib2ZmbGluZV9hY2Nlc3MiLCJsYXVuY2giLCJsYXVuY2gvcGF0aWVudCIsImFwaTpvZW1yIiwiYXBpOmZoaXIiLCJhcGk6cG9ydCIsInN5c3RlbS9QYXRpZW50LiRleHBvcnQiLCJzeXN0ZW0vR3JvdXAuJGV4cG9ydCIsInN5c3RlbS8qLiRidWxrZGF0YS1zdGF0dXMiLCJzeXN0ZW0vKi4kZXhwb3J0IiwicHJvZmlsZSIsIm5hbWUiLCJhZGRyZXNzIiwiZ2l2ZW5fbmFtZSIsImZhbWlseV9uYW1lIiwibmlja25hbWUiLCJwaG9uZSIsInBob25lX3ZlcmlmaWVkIiwiZW1haWwiLCJlbWFpbF92ZXJpZmllZCIsInNpdGU6ZGVmYXVsdCIsInBhdGllbnQvQWxsZXJneUludG9sZXJhbmNlLnJlYWQiLCJwYXRpZW50L0FwcG9pbnRtZW50LnJlYWQiLCJwYXRpZW50L0JpbmFyeS5yZWFkIiwicGF0aWVudC9DYXJlUGxhbi5yZWFkIiwicGF0aWVudC9DYXJlVGVhbS5yZWFkIiwicGF0aWVudC9Db25kaXRpb24ucmVhZCIsInBhdGllbnQvQ292ZXJhZ2UucmVhZCIsInBhdGllbnQvRGV2aWNlLnJlYWQiLCJwYXRpZW50L0RpYWdub3N0aWNSZXBvcnQucmVhZCIsInBhdGllbnQvRG9jdW1lbnRSZWZlcmVuY2UuJGRvY3JlZiIsInBhdGllbnQvRG9jdW1lbnRSZWZlcmVuY2UucmVhZCIsInBhdGllbnQvRW5jb3VudGVyLnJlYWQiLCJwYXRpZW50L0dvYWwucmVhZCIsInBhdGllbnQvSW1tdW5pemF0aW9uLnJlYWQiLCJwYXRpZW50L0xvY2F0aW9uLnJlYWQiLCJwYXRpZW50L01lZGljYXRpb24ucmVhZCIsInBhdGllbnQvTWVkaWNhdGlvblJlcXVlc3QucmVhZCIsInBhdGllbnQvT2JzZXJ2YXRpb24ucmVhZCIsInBhdGllbnQvT3JnYW5pemF0aW9uLnJlYWQiLCJwYXRpZW50L1BhdGllbnQucmVhZCIsInBhdGllbnQvUGVyc29uLnJlYWQiLCJwYXRpZW50L1ByYWN0aXRpb25lci5yZWFkIiwicGF0aWVudC9Qcm9jZWR1cmUucmVhZCIsInBhdGllbnQvUHJvdmVuYW5jZS5yZWFkIiwic3lzdGVtL0FsbGVyZ3lJbnRvbGVyYW5jZS5yZWFkIiwic3lzdGVtL0FwcG9pbnRtZW50LnJlYWQiLCJzeXN0ZW0vQmluYXJ5LnJlYWQiLCJzeXN0ZW0vQ2FyZVBsYW4ucmVhZCIsInN5c3RlbS9DYXJlVGVhbS5yZWFkIiwic3lzdGVtL0NvbmRpdGlvbi5yZWFkIiwic3lzdGVtL0NvdmVyYWdlLnJlYWQiLCJzeXN0ZW0vRGV2aWNlLnJlYWQiLCJzeXN0ZW0vRGlhZ25vc3RpY1JlcG9ydC5yZWFkIiwic3lzdGVtL0RvY3VtZW50UmVmZXJlbmNlLiRkb2NyZWYiLCJzeXN0ZW0vRG9jdW1lbnRSZWZlcmVuY2UucmVhZCIsInN5c3RlbS9FbmNvdW50ZXIucmVhZCIsInN5c3RlbS9Hb2FsLnJlYWQiLCJzeXN0ZW0vR3JvdXAucmVhZCIsInN5c3RlbS9JbW11bml6YXRpb24ucmVhZCIsInN5c3RlbS9Mb2NhdGlvbi5yZWFkIiwic3lzdGVtL01lZGljYXRpb24ucmVhZCIsInN5c3RlbS9NZWRpY2F0aW9uUmVxdWVzdC5yZWFkIiwic3lzdGVtL09ic2VydmF0aW9uLnJlYWQiLCJzeXN0ZW0vT3JnYW5pemF0aW9uLnJlYWQiLCJzeXN0ZW0vUGF0aWVudC5yZWFkIiwic3lzdGVtL1BlcnNvbi5yZWFkIiwic3lzdGVtL1ByYWN0aXRpb25lci5yZWFkIiwic3lzdGVtL1ByYWN0aXRpb25lclJvbGUucmVhZCIsInN5c3RlbS9Qcm9jZWR1cmUucmVhZCIsInN5c3RlbS9Qcm92ZW5hbmNlLnJlYWQiLCJ1c2VyL0FsbGVyZ3lJbnRvbGVyYW5jZS5yZWFkIiwidXNlci9BcHBvaW50bWVudC5yZWFkIiwidXNlci9CaW5hcnkucmVhZCIsInVzZXIvQ2FyZVBsYW4ucmVhZCIsInVzZXIvQ2FyZVRlYW0ucmVhZCIsInVzZXIvQ29uZGl0aW9uLnJlYWQiLCJ1c2VyL0NvdmVyYWdlLnJlYWQiLCJ1c2VyL0RldmljZS5yZWFkIiwidXNlci9EaWFnbm9zdGljUmVwb3J0LnJlYWQiLCJ1c2VyL0RvY3VtZW50UmVmZXJlbmNlLiRkb2NyZWYiLCJ1c2VyL0RvY3VtZW50UmVmZXJlbmNlLnJlYWQiLCJ1c2VyL0VuY291bnRlci5yZWFkIiwidXNlci9Hb2FsLnJlYWQiLCJ1c2VyL0ltbXVuaXphdGlvbi5yZWFkIiwidXNlci9Mb2NhdGlvbi5yZWFkIiwidXNlci9NZWRpY2F0aW9uLnJlYWQiLCJ1c2VyL01lZGljYXRpb25SZXF1ZXN0LnJlYWQiLCJ1c2VyL09ic2VydmF0aW9uLnJlYWQiLCJ1c2VyL09yZ2FuaXphdGlvbi5yZWFkIiwidXNlci9Pcmdhbml6YXRpb24ud3JpdGUiLCJ1c2VyL1BhdGllbnQucmVhZCIsInVzZXIvUGF0aWVudC53cml0ZSIsInVzZXIvUGVyc29uLnJlYWQiLCJ1c2VyL1ByYWN0aXRpb25lci5yZWFkIiwidXNlci9QcmFjdGl0aW9uZXIud3JpdGUiLCJ1c2VyL1ByYWN0aXRpb25lclJvbGUucmVhZCIsInVzZXIvUHJvY2VkdXJlLnJlYWQiLCJ1c2VyL1Byb3ZlbmFuY2UucmVhZCJdfQ.mZFYuLlnqXHQ_8RhddrbjVbuOr1Y-cvcrinciAte4xO4cpHNvpWvFqwkDxyNTI4gXfZPJJ-Nfzm0-HynOpqTkm8OD2wCphe75156-dUoBZkbkCpG8HXODVdZGSSGNc8c7H0K3XrXN_6RQ45_JvzqxcZApLn8_XYel7ZhZJtL7tCnkYPy0T6dTIjjoqKp3_NSri1uUkSHdeI2S2AhPVtbXyyJscX0Ru2XygsN137mMdfKcLFDC1-9S61t1KFcYBR0xMrMZpism-kEMPRDOcL5qooKgnf95G-vMX6Q-_CsVtsDsSEgYIShaLaSxcgsR5J_dSN9yd6ewpsRAwG2IOasrQ'
```
7. Test fhir/Patient/$export (500 server error)
```bash
curl --location 'https://demo.openemr.io/a/openemr/apis/default/fhir/Patient/$export' \
--header 'accept: application/fhir+json' \
--header 'prefer: respond-async' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJuUWJkbDdXUEVObHI4S2hMSzgtTXB4ZEx5R0ZEdjhUX2JBQWhVNk5jUXJ3IiwianRpIjoiZmFlNDBkYzc1Mzk1ZGEwYzUxZjlhYjlhZGZkYzYwMDE3MzE3ZDI5NDU3YWY1MGI2MGU0MzBkYzZlZTg0YzdiYjcwNjA0NjNhN2ZlMjVmM2EiLCJpYXQiOjE2OTk0MDg4NTguNzg0OTM5LCJuYmYiOjE2OTk0MDg4NTguNzg0OTQyLCJleHAiOjE2OTk0MDkxNTguNzYxMDU5LCJzdWIiOiI5YThkZmE1Mi0yNjk4LTRkYzUtYTQxOS05NmY1NTg1YWMzODYiLCJzY29wZXMiOlsib3BlbmlkIiwiZmhpclVzZXIiLCJvbmxpbmVfYWNjZXNzIiwib2ZmbGluZV9hY2Nlc3MiLCJsYXVuY2giLCJsYXVuY2gvcGF0aWVudCIsImFwaTpvZW1yIiwiYXBpOmZoaXIiLCJhcGk6cG9ydCIsInN5c3RlbS9QYXRpZW50LiRleHBvcnQiLCJzeXN0ZW0vR3JvdXAuJGV4cG9ydCIsInN5c3RlbS8qLiRidWxrZGF0YS1zdGF0dXMiLCJzeXN0ZW0vKi4kZXhwb3J0IiwicHJvZmlsZSIsIm5hbWUiLCJhZGRyZXNzIiwiZ2l2ZW5fbmFtZSIsImZhbWlseV9uYW1lIiwibmlja25hbWUiLCJwaG9uZSIsInBob25lX3ZlcmlmaWVkIiwiZW1haWwiLCJlbWFpbF92ZXJpZmllZCIsInNpdGU6ZGVmYXVsdCIsInBhdGllbnQvQWxsZXJneUludG9sZXJhbmNlLnJlYWQiLCJwYXRpZW50L0FwcG9pbnRtZW50LnJlYWQiLCJwYXRpZW50L0JpbmFyeS5yZWFkIiwicGF0aWVudC9DYXJlUGxhbi5yZWFkIiwicGF0aWVudC9DYXJlVGVhbS5yZWFkIiwicGF0aWVudC9Db25kaXRpb24ucmVhZCIsInBhdGllbnQvQ292ZXJhZ2UucmVhZCIsInBhdGllbnQvRGV2aWNlLnJlYWQiLCJwYXRpZW50L0RpYWdub3N0aWNSZXBvcnQucmVhZCIsInBhdGllbnQvRG9jdW1lbnRSZWZlcmVuY2UuJGRvY3JlZiIsInBhdGllbnQvRG9jdW1lbnRSZWZlcmVuY2UucmVhZCIsInBhdGllbnQvRW5jb3VudGVyLnJlYWQiLCJwYXRpZW50L0dvYWwucmVhZCIsInBhdGllbnQvSW1tdW5pemF0aW9uLnJlYWQiLCJwYXRpZW50L0xvY2F0aW9uLnJlYWQiLCJwYXRpZW50L01lZGljYXRpb24ucmVhZCIsInBhdGllbnQvTWVkaWNhdGlvblJlcXVlc3QucmVhZCIsInBhdGllbnQvT2JzZXJ2YXRpb24ucmVhZCIsInBhdGllbnQvT3JnYW5pemF0aW9uLnJlYWQiLCJwYXRpZW50L1BhdGllbnQucmVhZCIsInBhdGllbnQvUGVyc29uLnJlYWQiLCJwYXRpZW50L1ByYWN0aXRpb25lci5yZWFkIiwicGF0aWVudC9Qcm9jZWR1cmUucmVhZCIsInBhdGllbnQvUHJvdmVuYW5jZS5yZWFkIiwic3lzdGVtL0FsbGVyZ3lJbnRvbGVyYW5jZS5yZWFkIiwic3lzdGVtL0FwcG9pbnRtZW50LnJlYWQiLCJzeXN0ZW0vQmluYXJ5LnJlYWQiLCJzeXN0ZW0vQ2FyZVBsYW4ucmVhZCIsInN5c3RlbS9DYXJlVGVhbS5yZWFkIiwic3lzdGVtL0NvbmRpdGlvbi5yZWFkIiwic3lzdGVtL0NvdmVyYWdlLnJlYWQiLCJzeXN0ZW0vRGV2aWNlLnJlYWQiLCJzeXN0ZW0vRGlhZ25vc3RpY1JlcG9ydC5yZWFkIiwic3lzdGVtL0RvY3VtZW50UmVmZXJlbmNlLiRkb2NyZWYiLCJzeXN0ZW0vRG9jdW1lbnRSZWZlcmVuY2UucmVhZCIsInN5c3RlbS9FbmNvdW50ZXIucmVhZCIsInN5c3RlbS9Hb2FsLnJlYWQiLCJzeXN0ZW0vR3JvdXAucmVhZCIsInN5c3RlbS9JbW11bml6YXRpb24ucmVhZCIsInN5c3RlbS9Mb2NhdGlvbi5yZWFkIiwic3lzdGVtL01lZGljYXRpb24ucmVhZCIsInN5c3RlbS9NZWRpY2F0aW9uUmVxdWVzdC5yZWFkIiwic3lzdGVtL09ic2VydmF0aW9uLnJlYWQiLCJzeXN0ZW0vT3JnYW5pemF0aW9uLnJlYWQiLCJzeXN0ZW0vUGF0aWVudC5yZWFkIiwic3lzdGVtL1BlcnNvbi5yZWFkIiwic3lzdGVtL1ByYWN0aXRpb25lci5yZWFkIiwic3lzdGVtL1ByYWN0aXRpb25lclJvbGUucmVhZCIsInN5c3RlbS9Qcm9jZWR1cmUucmVhZCIsInN5c3RlbS9Qcm92ZW5hbmNlLnJlYWQiLCJ1c2VyL0FsbGVyZ3lJbnRvbGVyYW5jZS5yZWFkIiwidXNlci9BcHBvaW50bWVudC5yZWFkIiwidXNlci9CaW5hcnkucmVhZCIsInVzZXIvQ2FyZVBsYW4ucmVhZCIsInVzZXIvQ2FyZVRlYW0ucmVhZCIsInVzZXIvQ29uZGl0aW9uLnJlYWQiLCJ1c2VyL0NvdmVyYWdlLnJlYWQiLCJ1c2VyL0RldmljZS5yZWFkIiwidXNlci9EaWFnbm9zdGljUmVwb3J0LnJlYWQiLCJ1c2VyL0RvY3VtZW50UmVmZXJlbmNlLiRkb2NyZWYiLCJ1c2VyL0RvY3VtZW50UmVmZXJlbmNlLnJlYWQiLCJ1c2VyL0VuY291bnRlci5yZWFkIiwidXNlci9Hb2FsLnJlYWQiLCJ1c2VyL0ltbXVuaXphdGlvbi5yZWFkIiwidXNlci9Mb2NhdGlvbi5yZWFkIiwidXNlci9NZWRpY2F0aW9uLnJlYWQiLCJ1c2VyL01lZGljYXRpb25SZXF1ZXN0LnJlYWQiLCJ1c2VyL09ic2VydmF0aW9uLnJlYWQiLCJ1c2VyL09yZ2FuaXphdGlvbi5yZWFkIiwidXNlci9Pcmdhbml6YXRpb24ud3JpdGUiLCJ1c2VyL1BhdGllbnQucmVhZCIsInVzZXIvUGF0aWVudC53cml0ZSIsInVzZXIvUGVyc29uLnJlYWQiLCJ1c2VyL1ByYWN0aXRpb25lci5yZWFkIiwidXNlci9QcmFjdGl0aW9uZXIud3JpdGUiLCJ1c2VyL1ByYWN0aXRpb25lclJvbGUucmVhZCIsInVzZXIvUHJvY2VkdXJlLnJlYWQiLCJ1c2VyL1Byb3ZlbmFuY2UucmVhZCJdfQ.mZFYuLlnqXHQ_8RhddrbjVbuOr1Y-cvcrinciAte4xO4cpHNvpWvFqwkDxyNTI4gXfZPJJ-Nfzm0-HynOpqTkm8OD2wCphe75156-dUoBZkbkCpG8HXODVdZGSSGNc8c7H0K3XrXN_6RQ45_JvzqxcZApLn8_XYel7ZhZJtL7tCnkYPy0T6dTIjjoqKp3_NSri1uUkSHdeI2S2AhPVtbXyyJscX0Ru2XygsN137mMdfKcLFDC1-9S61t1KFcYBR0xMrMZpism-kEMPRDOcL5qooKgnf95G-vMX6Q-_CsVtsDsSEgYIShaLaSxcgsR5J_dSN9yd6ewpsRAwG2IOasrQ' \
--header 'Cookie: apiOpenEMR=Q1MSVQ2tgN9H5K5TqezQ2suHng7m8uelTVwgchXb1rzDnF1k'
```

All of the $export endpoints return 500


The standard api/insurance_company fails because it looks like the validator on the api isnt getting called

**Comment by adunsulag** [comment]
@eva-val I'll go ahead and see if I can reproduce the issue on the demos and my local box.  The php error logs on the demo servers should give a clue of what is going on.

**Comment by adunsulag** [comment]
I was able to reproduce the bug.  Looks like there is a problem in the FhirOrganizationInsuranceService.php that is triggering the 500.  If you're done here in this PR we can bring this in and I'll put out a PR to fix the patient/$export endpoint.

**Comment by eva-val** [comment]
Yes thank you.

**Comment by bradymiller** [comment]
I just brought this into the rel-702 branch
(plan to bring in commits from master to rel-702 quickly (and in order of master) prior to release to avoid missing anything and avoiding merging issues)

**Pull request merged**
