### PR TITLE
add standard meta tags to every openemr page

### PR DESCRIPTION
**Pull request by bradymiller**
This will basically add these tags to every openemr script. @sjpadgett , @mdsupport , @ophthal ; does this make sense?

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @sjpadgett ,

Thanks for the guidance. Couple quick questions:

The bootstrap site also recommends at https://getbootstrap.com/docs/4.0/getting-started/introduction/ to place the shrink-to-fit=no into the meta \<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"\>, which upon some internet research looks like is to deal with a safari bug. Would it make sense to add that?

Regarding the DOCTYPE, I have been thinking about that also, Am thinking of creating another function in the HEADER class that does this and then placing a hook for this as the first line of every script. It would basically be \<!doctype html\> . Notably, I have noted that this does break some scripts a bit (I have noted this since need to add this when do the jquery migrate stuff; as an aside 1 of the goals in doing this is to support jquery migrate a "development" option in entire codebase when we increment jquery version). Does that makes sense?

thanks,
-brady

**Comment by mdsupport** [comment]
It will be better to let core/header do all header tags including doctype, html and title.  Not exactly sure why that is currently a static class.  If it were to be real class, you would get object at the beginning of php block. Then use its beginHeader, endHeader, beginBody, endBody methods to do basic plumbing.  We need that type of approach to move 3rd party javascript to the end of body.

**Comment by bradymiller** [comment]
hi @mdsupport ,
At this time, don't have a class that does that, but @zbig01 is working on something along those lines in the OeUI class, which we could consider expanding on in the future when it has more widespread use. It appears that the DOCTYPE has to be the actual first line of output (ie. even before the html tag), so no matter what we need a hook at that place (which could then be brought into a more complete class in the future). For example, the \<!doctype html\> only worked when it was the first line of output; otherwise it did not prevent quirks mode (ie. jquery migrate script does not work in quirks mode). My thought for now is to simply create another static function in Header class that outputs this DOCTYPE and then do the gruntwork of adding this hook to every script; is there an easier way?
-brady

**Comment by bradymiller** [comment]
btw, for that DOCTYPE function, it's also gonna have a parameter to allow turning it off in the specific script, since I have noted it does break some of OpenEMR's scripts (we are in early stage of js modernization with goal of getting to one single jquery/jquery-ui, which will require dropping some js packages; then next step is getting away from jquery-ui; then pure js; then vacation...).

**Comment by mdsupport** [comment]
@bradymiller Since you are addressing `V` of MVC, we should look at how frameworks handle this requirement.  A good starting point could be either [Zend View](https://docs.zendframework.com/zend-view/helpers/intro/) or even Laravel `resources/views`.  Specifically Zend class provides a preview of what we will encounter as the application starts getting more structured.

We can probably try the following:
1. Create a class e.g. oeClassView with most of the `"standard"` view.
2. In globals.php, instantiate oeClassView as objView
3. php code following globals.php can call objView->setAttr to control output.
4. Replace current `doctype` tag by output of beginHeader method of objView.
5. Remove `head` and `title` tags as their values should be set prior to beginHeader.
6. Replace `</head>` by echo of endHeader method of objView.
7. Repeat similar approach for `<body>`, later if needed.

Once objView is ubiquitous, you can propagate future changes without touching every script.

**Comment by robertdown** [comment]
I'd say this should be handled in the core/header class like Jerry recommends.

As far as the V in MVC, Twig is already integrated into the project. Plus whatever we land on in the JS world.

Sounds like the Header class needs to be expanded some, to include a proper header render.

**Comment by bradymiller** [comment]
But this solution is doing this through the Header class. The Header class calls this function.

Also, regarding twig, may make sense to migrate that to another discussion. Does it still make sense to go that route now that end goal is client JS for views?

**Comment by robertdown** [comment]
We'll never be 100% twig or 100% JS views - like so many things in this project, baby steps, for now we should work on getting raw PHP out of the views, use Twig where necessary and then use JS to do our UI/interactions.

If we write the meta tags in that file we just end up migrating it to a class in the future, might as well just expand the Header class now and not have to refactor a refactor :)

**Comment by bradymiller** [comment]
Regarding this PR, the code in this PR won't duplicate code (since the Header class is not used in every script yet; prob about half of scripts are still calling this function directly rather than using the Header class). If I bring it into Header class now, then I will need to duplicate the code. I do agree that when the Header class is only game in town, then we can migrate that function entirely within the header class.

**Comment by tywrenn** [comment]
Bump as I have a few tags to add to the core -- I already added one of them though

**Comment by tywrenn** [comment]
I'm closing this PR as #3839 fixes this issue

**Pull request closed without merging**
