### PR TITLE
ccda importing from commandline and other stuff

### PR DESCRIPTION
**Pull request by bradymiller**
ccda importing from commandline and other stuff

### CODE REVIEW

**Comment by bradymiller** [comment]
Can create a bunch of CCDA's with synthea (https://github.com/synthetichealth/synthea/wiki/Basic-Setup-and-Running).
Using this command to create 10 CCDAs:
```
java -jar synthea-with-dependencies.jar --exporter.fhir.export false --exporter.ccda.export true --generate.only_alive_patients true -p 10
```
Have created 10,000 to establish resource use needs for the goal of a million. Creation of 10,000 took about 3-4 minutes and the created xml files take up 6.4 GB of space on drive.

Using this command to then import these CCDAs into OpenEMR (note am just starting with 10 in order to improve performance before going higher) (i made a synthea directory and put 10 of the CCDAs in it):
```
php import_ccda.php synthea
```
It throws a bunch of php warnings that need to work on, but it does work. Here's log output (creates a log.txt file with log output in it) on several runs where can garner how it is not very efficient and also note that the efficiency worsens as the number of total imports grows over time (i bet i can fix this issue easily with a mysql index or 2).
```
Starting patients importing
5 patient's imported (50.475 seconds)
10 patient's imported (73.692 seconds)
Completed patients importing (10) (73.692 seconds)
Started uuid creation
Completed uuid creation (79.07 seconds)
Starting patients importing
5 patient's imported (58 seconds)
10 patient's imported (83 seconds)
Completed patients importing (10) (83 seconds)
Started uuid creation
Completed uuid creation (87 seconds)
Starting patients importing
5 patient's imported (67 seconds)
10 patient's imported (96 seconds)
Completed patients importing (10) (96 seconds)
Started uuid creation
Completed uuid creation (101 seconds)
Starting patients importing
5 patient's imported (75 seconds)
10 patient's imported (106 seconds)
Completed patients importing (10) (106 seconds)
Started uuid creation
Completed uuid creation (109 seconds)
Starting patients importing
5 patient's imported (78 seconds)
10 patient's imported (111 seconds)
Completed patients importing (10) (111 seconds)
Started uuid creation
Completed uuid creation (114 seconds)
Starting patients importing
5 patient's imported (89 seconds)
10 patient's imported (126 seconds)
Completed patients importing (10) (126 seconds)
Started uuid creation
Completed uuid creation (128 seconds)
Starting patients importing
5 patient's imported (98 seconds)
10 patient's imported (139 seconds)
Completed patients importing (10) (139 seconds)
Started uuid creation
Completed uuid creation (143 seconds)
Starting patients importing
5 patient's imported (108 seconds)
10 patient's imported (153 seconds)
Completed patients importing (10) (153 seconds)
Started uuid creation
Completed uuid creation (156 seconds)
Starting patients importing
5 patient's imported (116 seconds)
10 patient's imported (163 seconds)
Completed patients importing (10) (163 seconds)
Started uuid creation
Completed uuid creation (166 seconds)
```

**Comment by stephenwaite** [comment]
nice instructions! just imported 10 Massachusettsian!

**Comment by bradymiller** [comment]
Just added a commit with a critical sql index that speeds things up keeps things fast after multiple imports:
```
Starting patients importing
5 patient's imported (9 seconds)
10 patient's imported (20 seconds)
Completed patients importing (10) (20 seconds)
Started uuid creation
Completed uuid creation (24 seconds)
Starting patients importing
5 patient's imported (9 seconds)
10 patient's imported (19 seconds)
Completed patients importing (10) (19 seconds)
Started uuid creation
Completed uuid creation (23 seconds)
Starting patients importing
5 patient's imported (9 seconds)
10 patient's imported (19 seconds)
Completed patients importing (10) (19 seconds)
Started uuid creation
Completed uuid creation (22 seconds)
Starting patients importing
5 patient's imported (8 seconds)
10 patient's imported (19 seconds)
Completed patients importing (10) (19 seconds)
Started uuid creation
Completed uuid creation (23 seconds)
Starting patients importing
5 patient's imported (9 seconds)
10 patient's imported (19 seconds)
Completed patients importing (10) (19 seconds)
Started uuid creation
Completed uuid creation (23 seconds)
Starting patients importing
5 patient's imported (8 seconds)
10 patient's imported (19 seconds)
Completed patients importing (10) (19 seconds)
Started uuid creation
Completed uuid creation (23 seconds)
```

**Comment by bradymiller** [comment]
run of 1000 ccda (ie. patient) inserts (got is down to 4 secs per patient which is likely best we are going to do with current mechanism; put instructions for using the ccda import script in the script comments; gonna bring this in and look to see if can further improve performance of the mechanism within the care coordination module):
```
ccda directory: synthea
site: default
openemr path: /var/www/localhost/htdocs/openemr
development mode is on
Starting patients import
50 patients imported (275 total seconds) (6 average seconds per patient for last 50 patients)
100 patients imported (446 total seconds) (3 average seconds per patient for last 50 patients)
150 patients imported (589 total seconds) (3 average seconds per patient for last 50 patients)
200 patients imported (772 total seconds) (3 average seconds per patient for last 50 patients)
250 patients imported (923 total seconds) (3 average seconds per patient for last 50 patients)
300 patients imported (1106 total seconds) (3 average seconds per patient for last 50 patients)
350 patients imported (1281 total seconds) (3 average seconds per patient for last 50 patients)
400 patients imported (1464 total seconds) (3 average seconds per patient for last 50 patients)
450 patients imported (1628 total seconds) (3 average seconds per patient for last 50 patients)
500 patients imported (1812 total seconds) (3 average seconds per patient for last 50 patients)
550 patients imported (2028 total seconds) (3 average seconds per patient for last 50 patients)
600 patients imported (2209 total seconds) (3 average seconds per patient for last 50 patients)
650 patients imported (2445 total seconds) (3 average seconds per patient for last 50 patients)
700 patients imported (2696 total seconds) (3 average seconds per patient for last 50 patients)
750 patients imported (2921 total seconds) (4 average seconds per patient for last 50 patients)
800 patients imported (3136 total seconds) (4 average seconds per patient for last 50 patients)
850 patients imported (3394 total seconds) (4 average seconds per patient for last 50 patients)
900 patients imported (3728 total seconds) (4 average seconds per patient for last 50 patients)
950 patients imported (3935 total seconds) (4 average seconds per patient for last 50 patients)
1000 patients imported (4203 total seconds) (4 average seconds per patient for last 50 patients)
Completed patients import (1000 patients) (4203 total seconds) (4 average seconds per patient)
Started uuid creation
Completed uuid creation (5103 total seconds; 1.4175 total hours)
```

**Comment by sjpadgett** [comment]
Very nice Brady. Will this translate to the CCM imports slowing down? Was it indexing all along?

**Comment by stephenwaite** [comment]
added a few fixes for the warnings to #4436

**Comment by bradymiller** [comment]
@sjpadgett ,

For when reading from the audit details table (when importing patient from audit details to a new patient in OpenEMR), the new index will fix the issue where things take longer as the audit_details table gets bigger with data. This is because the amount of rows that get added to this vertical table is huge, so the seek without the audit id index gets longer as more elements are added. So, with the index, the time for the import never changes no matter how filled the table get with data.

For the case when importing the ccda and things are imported into the audit_details table, then the index will actually slow things down. Only notable in huge ccda files (which synthea sometimes creates).

All in all though, the index provides marked performance increase.

For development mode, which has highest performance, the index is removed and the audit tables are truncated after each patient is imported. Thus the ccda import into audit table is not slowed by the index and the read is fast without the index since the only data in the table is for the patient (ie. they all have the same audit id).

In the pursuit to import a million patients, next goal is make a development cli zend mechanism/action that bypasses the ccda import into the audit table (maybe a php array instead) and goes directly to a new patient import. This should fly.

**Comment by stephenwaite** [comment]
@bradymiller, turns out that the `easy_dev` docker was faster than my local stack :)

just imported 1 patient through the synthea mechanism and started investigating the data that's brought in which looks good except there is no encounter created; thought heard talk of that on the call today and just want to double check with you on that @sjpadgett

**Comment by sjpadgett** [comment]
@stephenwaite If the CCD contains at least one encounter then it should create the encounter. We were talking about how import will only create one encounter and not all the encounters the CCD may have.

I'd have to look at import code to see if there is a reason based on something else not contained in CCD as to why import wouldn't create encounter.

**Comment by stephenwaite** [comment]
what if the ccda has vitals, shouldn't we create an encounter for that?

**Comment by sjpadgett** [comment]
I don't think import will create any data associated to what we call an encounter form. It's just not that smart yet. I could be wrong as I going off my memory from 2018...

**Pull request merged**
