### PR TITLE
Additional Questionnaire changes

### LINKED ISSUE #5798: Dashboard Portal widget Plus(+) icon invalid href path
### Describe the bug
Invalid link when clicking the plus icon.
image

### To Reproduce
Click icon

### Expected behavior
toggle panel collapse

### PR DESCRIPTION
**Pull request by sjpadgett**
- add portal request valid form for patient
- remove mixed return type to be compatable with PHP -8

Fixes #5798

### CODE REVIEW

**Comment by stephenwaite** [comment]
welcome back Jerry!

windy

**Comment by bradymiller** [comment]
2DV-2

**Comment by sjpadgett** [comment]
From Portal Template Maintenance:

image

**Comment by sjpadgett** [comment]
I guess I'll merge soon for dev demo resets later tonight.
I'm pretty happy with all of this however I'll probably run back through code when doing endpoints and add debug and audit logging and no, I haven't forgotten, just lazy at the moment!:)

**Comment by sjpadgett** [comment]
Darn I need to move dependencies for patch.

**Comment by sjpadgett** [comment]
we're going to have to ignore the style.css syntax

**Comment by sjpadgett** [comment]
Don't know how I missed updates to lforms but I went ahead and updated in both places public napa and encounter.
After merge I'll start bringing back to v7 patch. Then build a quick patch and test. If anything else needs to go back let me know or bring back yourselves.

**Pull request merged**
