### PR TITLE
Resolve bug was caused after escaping a urls of calendar.

### PR DESCRIPTION
**Pull request by matrix-amiel**
Hi @bradymiller
I saw a problems that my fix caused in PR #1091 just today..
I push here a solution of the problem with create new category (prevent double escaping) and make a calendar safe from XSS attacks.
See this example  
image
It's simple to inject malicious code instead.
I think it's important to prevent it.

Thanks
Amiel

### CODE REVIEW

**Comment by matrix-amiel** [comment]
Discussion about  this bug - https://community.open-emr.org/t/adding-calendar-categories/9076/12

**Comment by bradymiller** [comment]
Where is this attack happening downstream (ie. which echo is sending this bad variable to the screen)?

**Comment by bradymiller** [comment]
ahh, this bug is starting to come back to me(just saw you link to this: https://github.com/openemr/openemr/pull/1091).

**Comment by matrix-amiel** [comment]
Example of attack.
I know it's a bit stupid.. but I believe a good hacker can find more ways.
If you create user with user name - "onmouseover="alert(344)", And your calendar will got a lot of alerts..
image
Any way the companies of security test consider those errors as high issues.

**Comment by bradymiller** [comment]
@matrix-amiel ,
Your example with "onmouseover="alert(344)" illustrates a good point. Click on that user on the screenshot you saw, and you'll see the alert show up (ie. is a xss vulnerability). So, that means the username is not being properly html escaped on the edit user script. Can do 1 of 2 things. Make a focused fix or sweep the entire script to convert it to the standard security model. Here's the sweep of the entire script I did which fixes this vulnerability and shuts down lots of other vulnerabilities:
https://github.com/openemr/openemr/pull/1226

And we basically need to do the same thing to the calendar scripts (smarty has a specific and easy way to do this, which is illustrated here: https://github.com/openemr/openemr/blob/master/templates/insurance_numbers/general_edit.html#L108)

Trying to do something globally and then try to keep track of double escaping etc. is fraught with issues down the road.

**Comment by bradymiller** [comment]
Regarding the xss attack on the calendar, I am not able to get it to show up. Are you doing anything special to get it to show (I'm trying to isolate where it's coming from).

**Comment by bradymiller** [comment]
Disregard. I found the bad code in the providers selector of the calendar.

**Comment by bradymiller** [comment]
Here's a focused vulnerability fix for the username "onmouseover="alert(344)" fix in the calendar:
https://github.com/openemr/openemr/pull/1227

**Comment by matrix-amiel** [comment]
Hi @bradymiller 
It's necessary fix in user's create screen. but we need to escape a html of calendar.

The attack could be in every parameter like this link-
openemr/interface/main/calendar/index.php?module=PostCalendar&func=view&tplview=default&viewtype=day&Date=20171115&pc_username=admin&pc_category=&pc_topic=%27onmouseover="alert(1388)"

image

I'll try to create function that prevent double escaping..

**Comment by bradymiller** [comment]
Doesn't this zap that vulnerability?
https://github.com/openemr/openemr/pull/1228

**Comment by bradymiller** [comment]
disregard above. that just broke it :)

**Comment by bradymiller** [comment]
ok, this is messy

**Comment by bradymiller** [comment]
ok, how about this strategy:
https://github.com/openemr/openemr/pull/1229

**Comment by matrix-amiel** [comment]
It's look good.
I push new PR #1230 that prevents double encoding in the html.
So if you prefer we can use with the old solution - `$url = attr($url);`  without worry.

**Comment by bradymiller** [comment]
Regarding double encode;
1. I wouldn't trust that 
2. It will make us lazy (and will end up with some hard to figure out bugs)

**Comment by matrix-amiel** [comment]
O.k.
Let's going with #1229.

**Comment by bradymiller** [comment]
actually, I think i have a much better solution. it will be option 4 :) (coming soon)

**Comment by bradymiller** [comment]
ok, here the winner (at least I think):
https://github.com/openemr/openemr/pull/1231

Does this shut down your vulnerability?

**Comment by matrix-amiel** [comment]
Yes. it's working well.
Thanks.

**Pull request closed without merging**
