### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by bradymiller**
lots of carnage gonna likely happen here :)
to do:
1. Testing of the packages

### CODE REVIEW

**Comment by bradymiller** [comment]
most recent commit on this PR will require most recent easy docker environment build (since need php7-inst), which just built and is on dockerhub:
```
docker pull openemr/openemr:flex
```

**Comment by bradymiller** [comment]
Main things are completed on this. In process of testing.

**Comment by bradymiller** [comment]
Anybody know what this codeclimate thing is and why it's now part of testing?

**Comment by stephenwaite** [comment]
you're going to need a couple days to reduce the code complexity

**Comment by bradymiller** [comment]
bringing this in (ignoring codeclimate :) ). here's summary of this:
- updated composer and npm packages   
    - was unable to update the dwv package (something was breaking)
    - fixes to support adodb (was also able to remove old workarounds/hacks)
    - fix to support twig
    - fixes to support select2-bootstrap4-theme
    - fix to support flot
    - fix to support dropzone

**Comment by stephenwaite** [comment]
88220254-ba0afc00-cc30-11ea-9dd4-503ca1172e0e

**Pull request merged**
