### PR TITLE
Signed-off-by: Sherwin Gaddis <sherwingaddis@gmail.com>

### PR DESCRIPTION
**Pull request by juggernautsei**
made a new repository for the code update.

### CODE REVIEW

**Comment by bradymiller** [comment]
Hi,
This looks like it is missing a bunch of the revisions you did in the prior pull request??
-brady

**Comment by juggernautsei** [comment]
Yes, I always do this
git fetch upstream
git merge upstream/master
git push origin master

then create a new branch then update that branch. I can do it again. No problem.

**Comment by bradymiller** [comment]
Hi,
I wouldn't use merge when building your local master since goal is to keep it the same as the main master. Could just use pull:
git fetch upstream
git pull upstream master
git push origin master

**Comment by juggernautsei** [comment]
Ok, I will redo and leave off the merge

**Comment by bradymiller** [comment]
closing this since using the prior pull request:
https://github.com/openemr/openemr/pull/299

**Pull request closed without merging**
