### PR TITLE
Fixed bug: https://sourceforge.net/p/openemr/bugs/422/

### PR DESCRIPTION
**Pull request by sharonco-matrix**
There was a bug when selecting a radio button as a conditional field. With this fix the issue is solved.
The only thing that is still open is the "alert" when setting the 	Data Cols	=0 and  Label Cols=0 (field for checking the condition).
This alert it stills appearing. What is the expected behavior when adding  Data Cols	=0 and  Label Cols=0 as the fields are created as plain text fields with no ids.

### CODE REVIEW

**Comment by bradymiller** [comment]
Hi,
I'll bring in this fix.

There are basically 4 columns available for each row of the layout. For a typical layout, use 1 for the label and 1 for the data. However, can play around with this if want to get more items in a line.To get an idea of what setting label col to 0 and data col to 0, check out the name fields in the demographics. It's a way to crowd entries together. It definitely is not meant to break conditionals though.

**Comment by bradymiller** [comment]
I just committed it. Let me know if you want me to close this pull request, or if want to keep it open for the label/data column 0 issue.

**Comment by matrix-olegsv** [comment]
@bradymiller thank you. do you know how it's supposed to work with 0 in both fields?

**Comment by olegsv** [comment]
You can close this for now.

**Pull request closed without merging**
