### PR TITLE
travis to do only one code styling run

### PR DESCRIPTION
**Pull request by bradymiller**

### CODE REVIEW

**Comment by sjpadgett** [comment]
A, yeah!!! Thanks.

**Comment by bradymiller** [comment]
No longer do we need to wait like 20-25 min to bring in our commits :)

**Comment by bradymiller** [comment]
(ie. submit a PR, take the dog for a walk, eat dinner, then come back to the computer)

**Comment by sjpadgett** [comment]
Now only if you cold get that guy Travis to stop my goofy coding mistakes.

**Pull request merged**
