### PR TITLE
Fix some missing updates

### PR DESCRIPTION
**Pull request by sjpadgett**
@bradymiller I'm not sure what is going on but I'm seeing issues with portal I know i've fixed before especially the RequestUtil.php rest library. Also, mail has php7.1 errors (this too thought was addressed) so there will be another commit to this but won't hurt to docker this branch so I can be sure the pathing works.

### CODE REVIEW

**Comment by bradymiller** [comment]
Hold off on this. let me take a closer look. also looks like some code changes are getting reverted on this pr.


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Jerry Padgett <notifications@github.com> Date: 1/8/18  6:29 PM  (GMT-08:00) To: openemr/openemr <openemr@noreply.github.com> Cc: Brady Miller <brady@sparmy.com>, Mention <mention@noreply.github.com> Subject: [openemr/openemr] Fix some missing updates (#1373) 
@bradymiller I'm not sure what is going on but I'm seeing issues with portal I know i've fixed before especially the RequestUtil.php rest library. Also, mail has php7.1 errors (this too thought was addressed) so there will be another commit to this but won't hurt to docker this branch so I can be sure the pathing works.



You can view, comment on, or merge this pull request online at:
  https://github.com/openemr/openemr/pull/1373

Commit Summary

  Fix some missing updates


File Changes

  
    M
    portal/home.php
    (3)
  
  
    M
    portal/messaging/messages.php
    (62)
  
  
    M
    portal/patient/fwk/libs/verysimple/HTTP/RequestUtil.php
    (157)
  
  
    M
    portal/report/pat_ledger.php
    (3)
  
  
    M
    portal/report/portal_custom_report.php
    (8)
  
  
    M
    portal/report/portal_patient_report.php
    (8)
  


Patch Links:

  https://github.com/openemr/openemr/pull/1373.patch
  https://github.com/openemr/openemr/pull/1373.diff


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/openemr/openemr","title":"openemr/openemr","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/openemr/openemr"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Fix some missing updates (#1373)"}],"action":{"name":"View Pull Request","url":"https://github.com/openemr/openemr/pull/1373"}}}

**Comment by sjpadgett** [comment]
If you are referring to the text escape for short date I believe I removed those but got side tracked doing the new dialog so I can't remember why(believe the escape was doing something to the format).  So don't worry with that.

**Comment by bradymiller** [comment]
commits found related to this:
https://github.com/openemr/openemr/commit/c9d9cdcad84a9724caf6b4ce6af0cf4ca1da13e3
https://github.com/openemr/openemr/commit/181b1adf84a475d2daf122074498b4f5a0f9b39c

**Comment by bradymiller** [comment]
oeFormatShortDate needs to be html escaped. Note that text() doesn't even do anything to properly formatted dates that are sent to oeFormatShortDate. It's only in the case where the date is not properly formatted (and basically then returns what it was sent) that text() then html escapes. Again, please test this to confirm bad behavior before removing. At some point in the not too distant future, the goal will be to have 0 cross-scripting vulnerabilities in OpenEMR :)

**Comment by bradymiller** [comment]
See this PR for why I think you decided to not go the route of HTTP_X_FORWARDED_PROTO :
https://github.com/openemr/openemr/pull/1232

**Comment by bradymiller** [comment]
I wonder if my recent work to support SSL mysql connections is the culprit (I thought i extensively tested this, but maybe I missed it):
https://github.com/openemr/openemr/pull/1274
https://github.com/openemr/openemr/pull/1300

**Comment by bradymiller** [comment]
Set up an Up For Grabs demo here:
http://www.open-emr.org/wiki/index.php/Development_Demo#Eta_-_Up_For_Grabs_Demo

**Comment by sjpadgett** [comment]
I don't think anything you have done with the ssl stuff is at issue. I've may have just missed something and I need to just step back and go over everything. I think i'm just a little burnt out but I had to add in the RequestUtil mod to get portal to work again. Just tested docker and everything is working and now I just need to fix mail. I must have forgotten to add the RequestUtil mod when I did the last update for the relative path fix but I'm sure we tested very well after that so....beats me.

**Comment by sjpadgett** [comment]
Still another commit to come because ccda is not honoring global settings. will fix travis then

**Comment by sjpadgett** [comment]
Bringing in after testing with php7.1 and new CCM

**Pull request merged**
