### PR TITLE
Pharmacy import from HHS

### PR DESCRIPTION
**Pull request by juggernautsei**
…moved from the system. We also wanted to make some items stand alone. The drug data can stay in the system. Weno will continue to provide new drug data every quarter. This interface will be permanent.

The prescription interface needs to be discussed. By default, the drug table is not populated with any drugs.  We are offering drug data not connected to having to enable weno in the Globals. How do you want the interface to look up drugs? That is the remaining issue to solve. 

Fixes #

#### Changes proposed in this pull request:
Adding a drug table data and moving the pharmacy import from under Weno admin.

### CODE REVIEW

**Comment by juggernautsei** [comment]
Bump...

**Comment by juggernautsei** [comment]
Hello, is this thing on???

**Comment by bradymiller** [comment]
hi @juggernautsei , is this a work in progress or ready for review?

**Comment by juggernautsei** [comment]
This is complete. The whole interface/weno folder has been removed. So for version 6, there is no conflict. @bradymiller

**Comment by juggernautsei** [comment]
I don't have the power to resolve conflicts through PHPStorm. I have tried to do a rebase of the changes. The conflict still exists. The rebase did not pull in the new codebase to my knowledge. In my experience, if I add the changes to my PR. It just makes the conflict worse not better in any way.
On the right is the conflict. On the left is the PS. I highlighted where the rebase command was executed in the terminal window. In my opinion, I don't have write permissions so I cannot solve any conflicts. Git says must have write permission. So, without that, I will never be able to resolve a conflict from my side. Unless I figure out another way to bring in the new code base and apply the PR on top of it.
 
image

**Comment by juggernautsei** [comment]
I will just start over and do a fresh request. This is too far gone! Agh

**Pull request closed without merging**
