### PR TITLE
Morphine eq calculator

### PR DESCRIPTION
**Pull request by juggernautsei**
more updates

### CODE REVIEW

**Comment by MatthewVita** [comment]
@juggernautsei sorry I've been incredibly busy in life/work/other opensource duties. I am still QAing it. It is on my list though.

**Comment by MatthewVita** [comment]
This is the latest branch to use instead of the other one, right?

**Comment by juggernautsei** [comment]
to my knowledge of GitHub, this is the latest branch. I will not use the other that is in caps.

**Comment by MatthewVita** [comment]
Okay, @juggernautsei, I just did my QAing (so sorry for the delay on this).

I think it's almost there, I looked at the database tables around encounters and the linkage is perfect. Calculator code seems to be in great shape too.

My _only_ remaining issues are:

- I just can't get the graph to display! I'm getting `Uncaught ReferenceError: Dygraph is not defined` - are you sure you are importing this correctly?

-  I had to change demographics.php like so: `$widgetButtonLink = "../morphine_fragment.php";` Maybe I didn't pull the latest, but please make sure this is in good shape.

Some questions:

- Have you thought about some you and I can document this on the Wiki feature's page?
- Do you want to do a blog post about this? It's a very useful feature for those in the US.

**Comment by juggernautsei** [comment]
Hi, can we get back to reviewing this feature add?

**Pull request closed without merging**
