### PR TITLE
composer update that brought in recent oauth2 package compatible with php8

### PR DESCRIPTION
**Pull request by bradymiller**
crossing fingers that this works (but that would be too easy)

### CODE REVIEW

**Comment by bradymiller** [comment]
Looks like private certification passphrase communication between and thephpleague/oauth2-server and lcobucci/jwt packages are broken in their most recent versions (ie. not an OpenEMR problem), but still looking into this.

**Comment by bradymiller** [comment]
Think have a solution to get this to work in the phpleague/oauth2-server library and posted the fix there:
https://github.com/thephpleague/oauth2-server/pull/1164

**Comment by bradymiller** [comment]
We are in a potential pickle here in supporting API with PHP8 for the next year. There are 3 choices here (unless able to submit fixes in upstream package, which is very unlikely):
1. Support PHP7.3 - 7.4 in API (and PHP8 everywhere else in OpenEMR)
2. Support PHP7.4-8.0 everywhere in OpenEMR (note no PHP 7.3 support, and we are way to early (a year to early) to drop that support)
3. Have 2 different packages for PHP7.3-7.4 and PHP 7.4-8.0 (simply would be to many resources to support something like this and most end users would likely install the wrong packages anyways)

Unless somebody has a better idea, I think we are heading towards option 1.

**Comment by stephenwaite** [comment]
if not too difficult to fix can we fork the v3.4 and make our own library until upstream is fixed?

**Comment by bradymiller** [comment]
It's complicated because it is a dependency of a dependency of a dependency. Something that may be possible is a mechanism to overwrite the script with the fixed script after the build process that is built into the npm builds (gulpfile thing). @tywrenn , is something like this possible (for example, if we had a script stored somewhere in OpenEMR's codebase that would then overwrite a script within the vendor dependencies)? It would just be a short-term (ie. one year) fix for this issue, but suppose the mechanism could be used in future if this issue ever arises again.

**Comment by stephenwaite** [comment]
ok like is composer able to say if php v7.3 then use oauth3.4 ...

**Comment by bradymiller** [comment]
flow is:
steverhoades/oauth2-openid-connect-server
brings in
thephpleague/oauth2-server
brings in
lcobucci/jwt

And if composer is set to platform php7.3, then lcobucci/jwt will bring in a package not compatible with php8
But if composer is set to platform php7.4, then lcobucci/jwt will bring in a package that is compatible with php8

**Comment by lcobucci** [comment]
Folks, the issue here is probably the usage of the lock file. 

Because the oauth2-server is compatible with the 2 versions (and only one of them is php8 compatible), you'd need to run a composer update with php8 (using php8 as platform or removing that entry). 
That would make composer pick the JWT v4 and everything should work(tm).

Could you adapt your matrix to do something like this for php8 only:

```sh
composer config platform.php 8.0
composer update
````

**Comment by bradymiller** [comment]
hi @lcobucci ,
Thanks for the suggestion. I did trial setting the composer platform to 7.4 (dropped the lock file and did a composer update which then brought jwt 4 into the build). But the problem was that the build then breaks when end users are using PHP 7.3 with the build (it does appear to work for PHP 7.4 and PHP 8 though).
```
Composer detected issues in your platform:
Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.24.
PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.24. in /var/www/localhost/htdocs/openemr/vendor/composer/platform_check.php on line 24
```

We are basically inheriting the dependency from thephpleague/oauth2-server (if php platform is PHP 7.4 or greater, then jwt 4 gets brought in on build otherwise jwt 3 gets brought in on build). If only composer could build the same build with 2 different versions of the same package that are then decided during runtime.

We don't have end users do builds (or build related things like composer update, npm etc.). We build the package(s) and then offer it out in tgz/zip/docker format, which is the crux of the problem here since the builds are not dynamically built for the end user (ie. one build needs to support PHP 7.3-8). (end users that use OpenEMR have a tough enough time with pre-built packages; to expect dynamic builds for OpenEMR end users would be asking too much and we'd all be busy providing support for this :) ).

**Comment by lcobucci** [comment]
> Thanks for the suggestion. I did trial setting the composer platform to 7.4 (dropped the lock file and did a composer update which then brought jwt 4 into the build). But the problem was that the build then breaks when end users are using PHP 7.3 with the build (it does appear to work for PHP 7.4 and PHP 8 though).

That's why my suggestion was to do that bit  **only** when on CI.

> We don't have end users do builds (or build related things like composer update, npm etc.). We build the package(s) and then offer it out in tgz/zip/docker format, which is the crux of the problem here since the builds are not dynamically built for the end user (ie. one build needs to support PHP 7.3-8). (end users that use OpenEMR have a tough enough time with pre-built packages; to expect dynamic builds for OpenEMR end users would be asking too much and we'd all be busy providing support for this :) ).

It sounds to me that you are bundling together testing and releasing. Although more complex, it's possible to ship two compressed files targeting different platforms.

Would you be open to explore that possibility? I'd be happy to help on scripts to create said files. I feel responsible for the trouble I'm potentially causing with my decisions.

**Comment by bradymiller** [comment]
@lcobucci ,
Yep, mostly focused on the releasing issue on making one build that will support PHP 7.3-8 (the testing issue will hopefully fall into place when that is sorted out). I'm happy to spend time on this. I just gotta get my brain wrapped around the "Although more complex, it's possible to ship two compressed files targeting different platforms" comment. I just always thought that composer could only bring in one version of a software package in a build (ie. not be able to support 2 different versions of the same package in the same build). But I seem to learn something new every day :)

**Comment by lcobucci** [comment]
Sorry, I meant the compressed files you provide to your users.

**Comment by sjpadgett** [comment]
@bradymiller 
Chances are that most all upgrades will not be on PHP 8 therefore best we ship JWT for 7.3-7.4. Then for those upgrading their PHP to v8 or doing new install in PHP 8 environment, we instruct in install doc to composer require the correct version JWT library.
User will need to be at command line anyway.

**Comment by bradymiller** [comment]
@sjpadgett ,
Yep, that may be the best that we can do. This is only specific to the API also. So PHP8 would work for other stuff and user would only need to update composer if they wanted the API. This would work short-term (couple months), but over the next year could be problematic (since then users would be bringing in other untested packages (newer versions of other packages) via composer on the update). I'm testing an "alternate" route (using gulpfile.js to bring in fixes to upstream package to work with PHP8) that may work, which has a 50% chance of success :)

**Comment by sjpadgett** [comment]
you wouldn't need to use composer update if I understand you correctly. a composer require would only act on the dependency in question where it would either upgrade or downgrade just the version in question.
user should not be doing any composer updates in production where if they do, we should void our strict warranty and send them to the corner on timeout.:)

How and where does the gulp get kicked off?

**Comment by bradymiller** [comment]
Just put up a potential gulp solution in this PR. Crossing fingers on the github actions `Test / PHP 8.0 - Nginx - MariaDB 10.5 (pull_request)` test. It of course failed PSR; dang it Actions! (https://github.com/openemr/openemr/issues/4073). gulp stuff happens after composer in the build

**Comment by sjpadgett** [comment]
So you're concerned with build testing now, correct?

**Comment by bradymiller** [comment]
no, focused on release. But the build testing will follow if the release works (the build test does a typical release build and runs a bunch of tests on it including API stuff).
Turns out the build testing works (also worked locally for me with extensive testing). Gonna test lots more and maybe bring in a gulp diff mechanism to ensure the original file and the one in vendor are not different (in case brings in a new version of upstream package); if doesn't match will then throw an error so we fix the build process.

**Comment by bradymiller** [comment]
@sjpadgett , Looked into composer events that you brought up and looks like this is also a possibility to do the same thing as gulp:
https://getcomposer.org/doc/articles/scripts.md#command-events

**Comment by sjpadgett** [comment]
Yep, i've done this in the past and works pretty well. I'm just trying to see when a user would need to run anything(composer or a gulp build) after initial install or follow on upgrades.

**Comment by sjpadgett** [comment]
Anyway, this is in good hands. I want to get the introspection endpoint done so off I go. Then I want to get some work done on CCM

**Comment by lcobucci** [comment]
@bradymiller since you're going into the direction of overriding files on the vendor folder to keep a single dist file, I'd suggest you to use the branch from your fork as reference.

You need to add it to the composer file as a vcs repository and lock to it on the requirement (add the explicit requirement with an alias). Something like:

```json
"requires": {
    "lcobucci/jwt": "dev-your-branch@dev as 3.4.99"
}, 
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/your-fork"
        }
]
```

That should be a much simpler path to make it work.

**Comment by lcobucci** [comment]
@bradymiller since you're going into the direction of overriding files on the vendor folder to keep a single dist file, I'd suggest you to use the branch from your fork as reference.

You need to add it to the composer file as a vcs repository and lock to it on the requirement (add the explicit requirement with an alias). Something like:

```json
"requires": {
    "lcobucci/jwt": "dev-your-branch@dev as 3.4.99"
}, 
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/your-fork"
        }
]
```

That should be a much simpler path to make it work. You do have to keep that in sync with the upstream repo, in case bug fixes are released. 

More info:
- https://getcomposer.org/doc/04-schema.md#repositories

**Comment by bradymiller** [comment]
@lcobucci , Thanks for the composer pointer! Went that direction and much better than the gulp hack. Testing well and bringing this in.

**Pull request merged**
