### PR TITLE
composer package updates

### PR DESCRIPTION
**Pull request by bradymiller**
Up For Grabs demo to test this is here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Beta_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by bradymiller** [comment]
@d3sandoval ,
Updated the doctrine to version that should be safe and also did a generic composer update which updated a lot of packages. Does it make sense bite the bullet and work on this stuff now to prepare for your work?
thanks, -brady

**Comment by d3sandoval** [comment]
@bradymiller this shouldn't affect my work at all. Once this is merged, I'll incorporate it into my branch that addresses #1600

**Comment by bradymiller** [comment]
fyi @sjpadgett ,
Updated mpdf to most recent version which required some changes that are testing well; these are in the second commit of this PR:
https://github.com/openemr/openemr/pull/1729/commits/40b9de0b77866e24c95402faf8d172a120c118d4

**Comment by bradymiller** [comment]
This is testing really well, so bringing into codebase.

**Pull request merged**
