### PR TITLE
Warning in usergroup_admin.php issue #1468

### PR DESCRIPTION
**Pull request by sssopen**
Code changes based on the suggested solution in the issue #1468.

### CODE REVIEW

**Comment by bradymiller** [comment]
oh, I gave slightly bad advice. Should instead use GET rather than POST in the substitute command :)

**Comment by bradymiller** [comment]
Actually, hold on that. It looks like you may of changed the stuff below to GET. Bit confused. Let me look at your branch a bit.

**Comment by bradymiller** [comment]
ok, we need to get your master branch updated(it's 5 years out of date :) ). And then can make the POST substitution after do that.
Are you able to do git from command line on your dev environment? (I'll give you the commands to do)
What are the contents of your .git/config file in your openemr git repo?
-brady

**Comment by bradymiller** [comment]
and don't worry; git is fun and git is your friend :)
@sjpadgett can attest to this :)

**Comment by sssopen** [comment]
No wonder the last modified date of the file was 4 years and 9 months ago :)

**Comment by sjpadgett** [comment]
yep, i'm just giddy with git.... git it?

**Comment by sssopen** [comment]
I don't know. This is driving me crazy. Whatever I do using GitBash, it doesn't update my fork. Even when I do a new clone, it is still pulling from the my fork which is 5 years old. How can I delete my fork in GitHub? Hopefully I will be able to re-create a new fork updated one. 

capture

**Comment by sssopen** [comment]
I guess I don't have any options other than delete my fork and create a new fork again from the OpenEmr repository.

**Comment by bradymiller** [comment]
hi @sssopen ,
No need to do that. just send me contents of your .git/config file(either here or via email) and then ill give you a couple commands to sort things out.

**Comment by sssopen** [comment]
Hi Brady,
Thanks for the Git commands you sent me in the email. Unfortunately nothing seems to be working for me. My fork is still showing old version files and my local is still the same.

I also tried commands from here: https://help.github.com/articles/syncing-a-fork/
Also did this:
git reset --hard upstream/master

**Comment by bradymiller** [comment]
hi @sssopen ,
don't worry; we'll turn you into a git expert in no time :)
What are you now seeing in your .git/config file?
-brady

**Comment by sssopen** [comment]
Now I can do a git admin job easily :) I tried so many things and I was ended up a few branches. After cleaning up some, below is my config file:

.git/config
_____________________________________________________________
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = git@github.com:sssopen/openemr-1.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[remote "upstream"]
	url = git@github.com:sssopen/openemr-1.git
	fetch = +refs/heads/*:refs/remotes/upstream/*
[branch "up-master"]
	remote = origin
	merge = refs/heads/master
	rebase = false
[branch "rel-412"]
	remote = upstream
	merge = refs/heads/rel-412
	rebase = false

**Comment by bradymiller** [comment]
:)
Now we need to fix the upstream (you have this directed to you repo, but it needs to go to the official repo)
Try this:
git remote set-url upstream git@github.com:openemr/openemr.git

Then do the following(this will update your master on github to most recent codebase):
git checkout master
git fetch upstream
git pull upstream master
git push origin master

Let me know how that goes

**Comment by bradymiller** [comment]
Also, to make things easier, place the following [alias] section under your [core] section in the .git/config file:
``````
[alias]
        st = status
        ci = commit
        br = branch
        co = checkout
        df = diff
        lg = log -p
        lf = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative
``````

**Comment by sssopen** [comment]
You the man, Brady! It's all good now.  Thanks!

**Comment by bradymiller** [comment]
Nice! Your master branch looks great.
Now, lets make your code change and push it to this PR. Do the following:

# first update the master from official codebase (very good to get in habit of doing this frequently)
git checkout master
git fetch upstream
git pull upstream master
git push origin master

# now lets fix your dev-branch branch (ie. delete and redo it)
git branch -d dev-branch
git checkout -b dev-branch

# now edit the interface/usergroup/usergroup_admin.php and make the code substitution to fix the bug

# now commit your new changes
git commit -a -m "fixed bug #1468"

# now push it to your github repo. in this case we are going to use --force, so you overwrite the branch on this PR
git push --force origin dev-branch

DONE (note this PR will now be using your new and updated branch)

**Comment by sssopen** [comment]
Thanks for the step by step details. I had created a new local branch dev-master then deleted the dev-branch. I will push the code changes for PR.

**Comment by bradymiller** [comment]
Closing this since this fix was done in a another PR.

**Pull request closed without merging**
