### PR TITLE
removed evals in js files

### PR DESCRIPTION
**Pull request by harshlele**
#2010 - removed evals in `library/js/CategoryTreeMenu.js` and `/library/js/DocumentTreeMenu.js`

### CODE REVIEW

**Comment by harshlele** [comment]
@danehrlich1 
Ok, so about this issue, 

1. I couldn't find the places in the UI where the other files -
- `interface/forms/fee_sheet/review/js/fee_sheet_core.js`
- `interface/main/calendar/modules/PostCalendar/pnincludes/overlib.js`
- `interface/main/calendar/modules/PostCalendar/pnincludes/overlib_mini.js`
are used. I tried searching in the Calendar Calendar and the Fees section, but couldn't find them. 
  
2. Similarly, I also couldn't find the place in the UI where `library/js/CategoryTreeMenu.js` is actually used, but it seems like `library/js/CategoryTreeMenu.js` is almost the same as `/library/js/DocumentTreeMenu.js`, so I've made changes to CategoryTreeMenu too.I hope that's ok.

**Comment by harshlele** [comment]
In `interface/modules/zend_modules/public/js/carecoordination/jquery-ui.custom.js` , the eval statement https://github.com/openemr/openemr/blob/dd8318b8c083ecfd4921329c06eea0e79d6343df/interface/modules/zend_modules/public/js/carecoordination/jquery-ui.custom.js#L491

is inside a for loop:

```
for (var attrName in this._defaults) {
			var attrValue = target.getAttribute('date:' + attrName);
			if (attrValue) {
				inlineSettings = inlineSettings || {};
				try {
					inlineSettings[attrName] = eval(attrValue);
				} catch (err) {
					inlineSettings[attrName] = attrValue;
				}
			}
		}
```
but the eval statement never executes, because the `target` elements(which are `<input>` tags) have no attribute beginning with `date:`. So should i just remove the entire for loop? 
(I think the same thing is happening in `interface/modules/zend_modules/public/js/carecoordination/jquery.ui.datepicker.js`)

**Comment by danehrlich1** [comment]
Yes go ahead and remove. I’ve seen stuff like this before.

Another one of the goals with this project is remove dead code like this. Main reason is because it forces ppl to spent extra time analyzing code and figuring stuff out that is pointless.

Great catch here.

**Comment by bradymiller** [comment]
hi @harshlele ,

Sorry for the delay on this. Will plan to test this soon.

btw, if looking for another good project to work on (while I figure out what the heck these eval functions are :) ), check these out:
https://github.com/openemr/openemr/issues/2126
https://github.com/openemr/openemr/issues/2145

-brady

**Comment by harshlele** [comment]
Hey, so for `interface/modules/zend_modules/public/js/scripts/file_uploader.js`, it seems like it's only used in the Documents Module. I've tried searching online, but I can't find any place what the Documents module actually does, or how/where to use it. Can you give me some pointers as to where to look?

**Comment by harshlele** [comment]
hey, any update on this? @bradymiller

**Comment by danehrlich1** [comment]
Harshlele, there is another issue recently created to delete unused functions and libraries in the codebase. There are many of them. Could this be something that can just be deleted outright?

**Comment by bradymiller** [comment]
hi @danehrlich1 and @harshlele ,

Looks like all 4 of these scripts are used, so can't delete them . I would not touch the jquery-ui.custom.js and jquery.ui.datepicker.js scripts; we are better off centralizing them upgrading these in the long run (note we are process of doing this for the main codebase and almost done; at some point we'll need to do this for the zend stuff).

The CategoryTreeMenu.js and DocumentTreeMenu.js seem reasonable as long as they test well. I am still trying to wrap my brain around the eval() function; think I just need a couple more cups of coffee to get it :)

-brady

**Comment by danehrlich1** [comment]
Brady can this be merged? We never went through with any deletes so we should be good?

**Comment by bradymiller** [comment]
hi @danehrlich1 ,
Check out my postabove. Basically need to:
1. revert the changes in jquery-ui.custom.js and jquery.ui.datepicker.js
2. Ensure the changes in CategoryTreeMenu.js and DocumentTreeMenu.js are testing well.

**Comment by danehrlich1** [comment]
Oh sorry didn’t see that. I’ll revert the changes in a couple days then, didn’t know they had actually been made.

**Pull request closed without merging**
