### PR TITLE
Mazdoc's Obstetrics Forms

### PR DESCRIPTION
**Pull request by bradymiller**
Based on the following PR by mazdoc:
https://github.com/openemr/openemr/pull/1073

up for grabs demo here:
http://www.open-emr.org/wiki/index.php/Development_Demo#Gamma_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @mazdoc ,

Here's a new PR with your code based on most recent codebase.

Also directed an up for grabs demo for folks to test it here:
http://www.open-emr.org/wiki/index.php/Development_Demo#192.168.1.135

-brady

**Comment by stephenwaite** [comment]
can't pull up login screen https://five.openemr.io/log/logPhp.txt

**Comment by bradymiller** [comment]
hi @stephenwaite ,
Looks like all the demos have crashed. I have 1 docker mysql instance that supports all of the 10 docker demos, and guessing it got overwhelmed with connections. Will reset them all when get home this evening and will optimize the mysql docker to prevent this in the future.
-brady

**Comment by bradymiller** [comment]
The link to this Up For Grabs demo has changed to:
http://www.open-emr.org/wiki/index.php/Development_Demo#Gamma_-_Up_For_Grabs_Demo

@mazdoc , I plan to do code review on this very soon. sorry for the delay.

**Pull request closed without merging**
