### PR TITLE
Alerts in pt demographics

### PR DESCRIPTION
**Pull request by mdsupport**
Mechanism to display alerts in a single box from multiple ajax requests.  Also provides recall functionality in case the alert is dismissed (within existing limitations).

below added by bradymiller:
Up For Grabs demo for this PR can be found here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Eta_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by mdsupport** [comment]
Realized when checking the demo - we use current stable qTip2 (3.0.3).  That path got in yaml config but the public assets files are missing.
If you have plans to bring in latest qTip, we could leave the commit alone otherwise add another commit with revised yaml.

**Comment by bradymiller** [comment]
hi @mdsupport ,
I just brought in qTip 3.0.3 into the codebase (note it was a little messy since the standard bower mechanism was not working, which is why have the dist/ added to the path):
https://github.com/openemr/openemr/commit/0199b9f336e46830a3560f3219b2318b60a08109

-brady

**Comment by bradymiller** [comment]
hi @mdsupport ,
If I set rules to be Active Reminders (rather than Passive), then odd things happen to the Alerts box (sometimes all alerts go to zero; other times they are missing words).
-brady

**Comment by mdsupport** [comment]
Closing this as we have moved away from demographics based reminders to a mechanism that pushes action items to staff based on background application of all rules.

Hoping developers actively switch to alerts mechanism provided by BS as javascript alerts stop processing completely.

**Comment by sjpadgett** [comment]
Hi @mdsupport , I think i'm following. I agree we definitely need to use BS style asynchronous and the dlgopen() function is set up to do that and may be easy to refactor many of our sync JS alerts. They are a huge bottleneck, especially for initial summary loads.
If you point me to a specific Alert that I can tackle as an example conversion to a dlgopen ajax mode alert(with promise), i'll give it a go and we can post the example on forum.

**Comment by mdsupport** [comment]
@sjpadgett, Unfortunately demographics.php, a container to display relevant pieces of information, is probably most used script.  Typical user will look at it and choose what they want to see in further detail or fix what is missing.  So its the delay between render and ready that frustrates users.
Alerts was first stab and we come up against code in CDR that creates ui elements(alerts) rather than returning flags and letting caller decide how to present them.
I restored the branch in case you want to look at what does not work for standard codebase.

**Pull request closed without merging**
