### PR TITLE
Gitignore Some Files

### LINKED ISSUE #3910: Git Ignore Generated Certs (This is Annoying)
### Describe the problem

Currently 3 files get generated every time I do a docker compose:
`/contrib/util/docker/couchdb-config-ssl-cert-keys/local.ini`
`/contrib/util/docker/ldap-ssl-certs-keys/easy/dhparam.pem`
`/contrib/util/docker/ldap-ssl-certs-keys/easy/server-key.pem`

### Describe the solution you'd like

Gitignore these files so we don't have to deal with them ruining pushing changes.

### PR DESCRIPTION
**Pull request by tywrenn**
Fixes #3910

The first thing this does is show what files are generated that need to be gitignored. @bradymiller you will have to tell me what the best course of action for these are.

### CODE REVIEW

**Comment by tywrenn** [comment]
btw these are from my easy dev so they don't link to anything when these certs and stuff are generated

**Comment by bradymiller** [comment]
This is not happening in my easy dev environment. Very strange. Will be better to fix the issue (ie. why this is happening) than ignore stuff.
What is your host operating system?
Are you using the standard docker-compose.yml easy dev script or are there modifications in it?

**Comment by bradymiller** [comment]
actually, let me check my easy dev environment in more detail. will get back to you on this,

**Comment by tywrenn** [comment]
Yep i'm using the stock one running Ubuntu 20.04 LTS

**Comment by bradymiller** [comment]
I can confirm the change in contrib/util/docker/couchdb-config-ssl-cert-keys/local.ini:
```
 ;admin = mysecretpassword
+admin = -pbkdf2-de80c92fa871490f377f75e3524510b65a89ed2e,30f3e5990129b16c299587e84125afdc,10
```

 but not seeing the contrib/util/docker/ldap-ssl-certs-keys/easy/dhparam.pem file

I'll look into the local.ini issue first since can reproduce and maybe fixing that will make your dhparem.pem issue also go away :)

**Comment by bradymiller** [comment]
The following PR I just brought in fixes this:
https://github.com/openemr/openemr/pull/3913

Note it fixes the contrib/util/docker/couchdb-config-ssl-cert-keys/local.ini issue.

regarding dhparam.pem, I can not confirm this and it should not be possible since there is no shared volume to that file (and the shared files in that folder are read only). So, hopefully that goes away with another docker rebuild (ensure volumes are removed) with fixed docker-compose.yml

**Comment by bradymiller** [comment]
oh man, i just realized the dhparam.pem is in the ldap directory. ok, on to fix that now :)

**Comment by bradymiller** [comment]
ok, the ldap one should be an easier fix. testing it now.

**Comment by bradymiller** [comment]
ok, got the ldap dhparam.pem thing fixed:
https://github.com/openemr/openemr/pull/3914

**Comment by bradymiller** [comment]
sigh, one more to fix it looks like:
contrib/util/docker/ldap-ssl-certs-keys/easy/server-key.pem
(this is because it gets permissions removed from it, so looks empty unless use sudo)
Figuring out a solution

**Comment by stephenwaite** [comment]
wallaceandgrommet

**Comment by bradymiller** [comment]
the server-key.pem issue has been fixed:
https://github.com/openemr/openemr/pull/3915

So, now the easy dev environment should be back to smooth sailing :)

**Comment by stephenwaite** [comment]
88220254-ba0afc00-cc30-11ea-9dd4-503ca1172e0e

**Comment by tywrenn** [comment]
Closing since it was fixed

**Pull request closed without merging**
