### PR TITLE
Panels - [WIP] This is for comments not for the code base yet

### PR DESCRIPTION
**Pull request by juggernautsei**
Fixes #

#### Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by juggernautsei** [comment]
@bradymiller I guess leaving this in draft mode did not escape your view. I was hoping that it would stay out of view if it was in draft mode. This is a project for GMU but I see it is open to the public. Thanks for looking in. I was trying to review the code changes here before bringing them into the GMU production server.

**Comment by tywrenn** [comment]
@juggernautsei What exactly is this doing? 😂

**Comment by juggernautsei** [comment]
This is a George Mason University project. They are creating something they call panels. It is a logical grouping of patients that are in the same study group. They did not like the way groups were set up in the program and asked one of the Information Technology students to design a new layout. She posted it here for me to review and comment. 
This is creating a new section in the demographics of the patient to show all the studies that the patient is enrolled in at any given time. It will be the tool used to manage those enrollments. It will be able to track when the patient was enrolled and when the enrollment ended for each of the studies.

**Comment by juggernautsei** [comment]
This was not meant for the codebase. This is a private project.

**Pull request closed without merging**
