### PR TITLE
Fixes #5536,#5537 stylesheet and care team

### LINKED ISSUE #5536: Carecoordination Stylesheet reference not being included in generated ccda
Leftover bug from some refactoring of the external stylesheet code I attempted to do previously.  Now the stylesheet isn't rendered at all.  So need to fix that.

### LINKED ISSUE #5537: Carecoordination dies when careteam only includes primary care provider
Carecoordination fails to generate the ccda when the careteam only includes the primary care provider.

### PR DESCRIPTION
**Pull request by adunsulag**
Fixes #5536 
Fixes #5537

### CODE REVIEW

**Comment by adunsulag** [comment]
@sjpadgett I have to step away for 10-15 minutes, but here is the serveccda I am working against, which fixes the crashes but  I'm now getting the following for Alice:
image

**Comment by sjpadgett** [comment]
> image

I saw and fixed this prior. I just can't remember where! Please lord, work with me here and let me remember stuff at least for one more week!:)

**Comment by sjpadgett** [comment]
did I forget to do a PR? rhetorical!

**Comment by adunsulag** [comment]
@sjpadgett This is the xml that is breaking, looks like the function code null flavor is what is breaking.
```xml
<component>
                                <act classCode="PCPR" moodCode="EVN">
                                    <templateId root="2.16.840.1.113883.10.20.22.4.500.1" extension="2019-07-01"/>
                                    <id root="09d878d5-ee7f-4bbd-9310-d498ac786f4a"/>
                                    <code code="85847-2" displayName="Care Team Information" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"/>
                                    <statusCode code="active"/>
                                    <effectiveTime xsi:type="IVL_TS">
                                        <low value="20220622"/>
                                    </effectiveTime>
                                    <performer typeCode="PRF">
                                        <functionCode nullFlavor="UNK">
                                            <originalText xmlns="urn:hl7-org:v3">
                                                <reference value="#teamMember1"/>
                                            </originalText>
                                        </functionCode>
                                        <assignedEntity>
                                            <id root="2.16.840.1.113883.4.6" extension="123456789"/>
                                            <addr>
                                                <streetAddressLine>2472, Rocky place</streetAddressLine>
                                                <city>Beaverton</city>
                                                <state>OR</state>
                                                <postalCode>97006</postalCode>
                                                <country>USA</country>
                                            </addr>
                                            <assignedPerson>
                                                <name>
                                                    <family>Davis</family>
                                                    <given>Albert</given>
                                                </name>
                                            </assignedPerson>
                                        </assignedEntity>
                                    </performer>
                                </act>
                            </component>
```

**Comment by sjpadgett** [comment]
Have you set Taxonomy for users? for nurse it's 163W00000X but still I need to correctly nullFlavor if that's is indeed the issue.

**Comment by adunsulag** [comment]
@sjpadgett I'm correctly passing now when the primary care provider is set and when the fallback provider is set in the carecoordination module with this last fix.

image

**Comment by adunsulag** [comment]
@sjpadgett just waiting on the tests to pass and then I can bring it in.

**Comment by sjpadgett** [comment]
Thanks Stephen!

**Pull request merged**
