### PR TITLE
Billing processor fixes

### PR DESCRIPTION
**Pull request by kchapple**
Dan found an issue while testing related to scope of some variable, so this is removing global keyword from some function-scoped variables and passing the variables into the function instead.

* fixed bug affecting HLcount and edi count (SE Trailer)

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @kchapple , bringing in. thanks for the fixes! -brady

**Comment by stephenwaite** [comment]
was wondering if `edi_counts` was meant to be used in this recent fix?

https://github.com/openemr/openemr/blob/master/src/Billing/BillingProcessor/Tasks/GeneratorX12Direct.php#L62

**Comment by kchapple** [comment]
@stephenwaite yep, I was helping Dan figure out how to keep track of the EDI count for each x-12 partner, but it looks like he created his own member"on the fly" rather than the one I created as an example. I'll clean it up, cause though it still works the same, it's confusing.

**Comment by kchapple** [comment]
Good catch! Thanks!

**Pull request merged**
