### PR TITLE
Requisition form

### PR DESCRIPTION
**Pull request by juggernautsei**
Submitting a new form for lab order requisitions. Some labs require a requisition form be sent with the patient. This has the basic information that is needed to send to the lab. 

I realized today that the lab name is hard coded into the page. I will update that to make it dynamic.

### CODE REVIEW

**Comment by bradymiller** [comment]
Hi Sherwin,
Is this code ready for another review (noted the new commit)?
-brady

**Comment by juggernautsei** [comment]
yes thanks!

**Comment by juggernautsei** [comment]
The form needs translating. Do I need to include any thing other than globals and and the 
<?php xlt(Collection Date/Time) ?> to everything that needs to be translated?

**Comment by juggernautsei** [comment]
It is ready for review now. I have added the translation to the form.

**Comment by juggernautsei** [comment]
I have made an update to the requisition form

**Comment by robertdown** [comment]
Closing this since outdated PR

**Pull request closed without merging**
