### PR TITLE
Php 7 MySQL second commit: Replaced mysql native functions with openemr's central functions

### PR DESCRIPTION
**Pull request by Dev2-PracticeProvider**

### CODE REVIEW

**Comment by bradymiller** [comment]
Hi,
Is this a review request? This code was already brought into the codebase a month or so ago:
https://github.com/openemr/openemr/commit/3b9d2b326ebc62f57f409968234946035738df6d
-brady

**Comment by Dev2-PracticeProvider** [comment]
Hi,

Brady the commit we want to add is "Replaced mysql native functions with central library functions"

When I created pull request it shows all the commits under this branch

**Comment by Dev2-PracticeProvider** [comment]
Brady I have created another committed related to mysql to mysqli conversion here https://github.com/practiceprovider/openemr/commit/656d853b564c071e24e33858df703e88926ab871

when I try to create pull request it still shows the previous commits that already merged

what is the right way to create pull request?

**Comment by bradymiller** [comment]
Hi,

But I already reviewed that commit here:
https://github.com/practiceprovider/openemr/commit/a04efa7055a2d952a3ef2613905555478c6a9d6a
Have you addresses the review issues anywhere?

-brady

**Comment by bradymiller** [comment]
I wouldn't worry about the pull request mechanism. The problem is that your branch has lots of merging. I wouldn't worry about merging in most recent codebase. Recommend placing a commit in the following branch to address the  "Replaced mysql native functions with central library functions" review issues:
https://github.com/practiceprovider/openemr/commits/php7-mysql02

I can then grab the commits and bring them into the codebase (no need to do the pull request).

After above is done, then can move onto your "mysql to mysqli conversion" commit.

-brady

**Comment by Dev2-PracticeProvider** [comment]
I didn't realize that you have already reviewed sorry my bad 

Working according to your suggestions

**Comment by bradymiller** [comment]
I rebased your original commit and your fixes here:
https://github.com/bradymiller/openemr/commit/7939f062a087b41efb9ec327b9da929822569fb2

I then did a review on it there and made some minor fixes here:
https://github.com/bradymiller/openemr/commit/c0ad96d0548c3f2083abae78be2119532e96fc2d

I then committed both of the above commits into the official codebase.

Next plan is to review your "Mysql to Mysqli conversion in central libraries" commit. I have placed this commit on a new branch (and based on most recent codebase):
https://github.com/bradymiller/openemr/commits/php7-more-stuff
 Recommend using this branch to continue your work on this (after I do the code review). You can bring this into your repository with following command:
git remote add bradymiller https://github.com/bradymiller/openemr.git
git fetch bradymiller
git checkout bradymiller/php7-more-stuff
(ignore the warning)
git checkout -b my-php7-more-stuff
Now you will have a branch in your repository called my-php7-more-stuff, which you can now work from.
(I also recommend in the future not using merge)

**Comment by bradymiller** [comment]
Hi,

Placed a review of your "Mysql to Mysqli conversion in central libraries" commit here:
https://github.com/practiceprovider/openemr/commit/656d853b564c071e24e33858df703e88926ab871

-brady

**Comment by bradymiller** [comment]
Hi,

I rebased all your commits for the mysqli-conversion (and placed onto most recent codebase) into 1 commit on the branch here:
https://github.com/bradymiller/openemr/commits/php7-more-stuff_3

The top commit there contains your code, which I placed a code review on (search the commit with bradymiller to see my comments):
https://github.com/bradymiller/openemr/commit/f689e951c3671d9bcc29cb7a169bd22e336451f5

For your next code changes, PLEASE WORK FROM THE 'php7-more-stuff_3' BRANCH IN MY REPO(otherwise, I need to spend a bunch of time dealing with merge conflicts). To get my repo and work from it, do the following:
git remote add bradymiller https://github.com/bradymiller/openemr.git
git fetch bradymiller
git checkout bradymiller/php7-more-stuff_3
(ignore the warning)
git checkout -b my-php7-more-stuff_3
Now you will have a branch in your local repository called my-php7-more-stuff_3, which you can now work from.

-brady

**Comment by bradymiller** [comment]
Hi,

I just committed your code that migrates mysql to mysqli to the official codebase. So, now the next thing to do is to test php7 on OpenEMR and see what breaks(check the php log). I recommend working and testing from the most recent development codebase branch here:
https://github.com/openemr/openemr/commits/master

-brady

**Pull request closed without merging**
