### PR TITLE
ccda advice

### PR DESCRIPTION
**Pull request by stephenwaite**
always forget this piece, plus haven't found that localhost setting for mirth matters anymore, at least on the demos, https://six.openemr.io/c/openemr/interface/login/login.php?site=default, just installed it :wrench:

### CODE REVIEW

**Comment by sjpadgett** [comment]
Demo may resolve an empty in socket address to 127.0.01 by default but for sure it needs to be set. I have seen issues if not(I could hard code but still the primary needs to be set). Also setup will not auto save!
I may need to add some pic'c.
image

**Comment by stephenwaite** [comment]
ok, by auto save, meant no need to search for a save button after clicking in config

**Comment by stephenwaite** [comment]
hooks is like that too but see what you mean in settings and mapper

**Comment by sjpadgett** [comment]
Also, check out Sourcetree app. I love it and makes trying to remember git commands easier. Especially if doing PR's and cherry pick. Brady is a command line kind of guy me, i'm too lazy:) You can still goto command line though!

**Comment by stephenwaite** [comment]
ok, cool, yeah, prefer the command line but sometimes a visual app can teach better, thanks

**Pull request merged**
