### PR TITLE
Build.xml update for assets directory

### PR DESCRIPTION
**Pull request by Wakie87**

### CODE REVIEW

**Comment by bradymiller** [comment]
Very nice. This can go into the codebase. I'll update the bower wiki page with this mechanism to remove the bad stuff. Very cool.

**Comment by bradymiller** [comment]
If you every become bored, with your impressive commits touching many files, feel free to take on this tedious project :)
https://sourceforge.net/p/openemr/discussion/202506/thread/249176ef/#d4a7
(my current plan is for this mechanism to operate like an aircraft controller for the assets; and once we have them all stacked there in a standardized fashion, can then begin to untangle the myriad web of version dependencies with the goal of 1 version per package(gasp...) )

**Comment by Wakie87** [comment]
Added to codebase. :smile:

**Comment by bradymiller** [comment]
great news
I'll update the bower wiki page with the new details.

**Pull request closed without merging**
