### PR TITLE
travis updates for more testing

### PR DESCRIPTION
**Pull request by bradymiller**
work in progress by @zerai

### CODE REVIEW

**Comment by bradymiller** [comment]
Still trying to get server going in travis. Looks like will need to do something like this:
https://docs.travis-ci.com/user/languages/php/#apache--php

**Comment by bradymiller** [comment]
Another odd things is that the test_build is failing on the e2e testing, however, travis is reporting a pass.

**Comment by stephenwaite** [comment]
is this saying that phing has an issue installing phpunit?

https://travis-ci.org/openemr/openemr/jobs/628496569#L543-L557

**Comment by bradymiller** [comment]
Actually, we may be able to use a flex docker instead here :)
https://docs.travis-ci.com/user/docker/

**Comment by bradymiller** [comment]
@stephenwaite ,
Composer suggestions are like php notices :)
(phing is actually installed via composer globally; so gets installed in the user's composer folder since only need the bindary) whereas all the other stuff is being installed in the main vendor folder)

**Comment by stephenwaite** [comment]
ok, it's installing php7.0?

https://travis-ci.org/openemr/openemr/jobs/628496569#L2609

**Comment by bradymiller** [comment]
@stephenwaite , was getting desparate there and trying to set up a apache server on travis ci; it didn't work. Trying another strategy now by using the flex docker.

**Comment by stephenwaite** [comment]
think you have to add stages to the travis.yml
https://docs.travis-ci.com/user/build-stages/#how-to-define-build-stages

**Comment by stephenwaite** [comment]
maybe not and still doesn't explain why the build is passing

**Comment by bradymiller** [comment]
Still hitting head against wall on getting a build that we can do real unit and api testing on. Will take a couple more tries tonight.
Once get it worked out, then staging would be neat to do for the build->test this->test that pipeline.
Regarding the ignoring error, guessing we just need to figure out how to catch the errors (for example, check out what we do for the lint_syntax testing.

**Comment by bradymiller** [comment]
@stephenwaite , woohooo, we got a live instance finally up and running with api turned:
```
<b>Configuration:</b><br/>
driver = <b>mysqli_mod</b>,<br/>
host = <b>mysql</b>,<br/>
user = <b>openemr</b>,<br/>
database = <b>openemr</b>,<br/>
table prefix = <b>gacl_</b>Testing database connection...<br/>
<font color="green"><b>Success!</b></font> Connected to &quot;<b>mysqli_mod</b>&quot; database on &quot;<b>mysql</b>&quot;.<br/>
Testing database type...<br/>
<font color="green"><b>Success!</b></font> Compatible database type "<b>mysqli_mod</b>" detected!<br/>
Making sure database "<b>openemr</b>" exists...<br/>
<font color="green"><b>Success!</b></font> Good, database "<b>openemr</b>" already exists!<br/>
<font color="green"><b>Success!</b></font> 
First Step of Access Control Installation Successful!!!<br><br/>
<html>
<head>
<title>OpenEMR ACL Setup</title>
<link rel=STYLESHEET href="interface/themes/style_blue.css">
</head>
<body>
<b>OpenEMR ACL Setup</b>
<br>
All done configuring and installing access controls (php-GACL)!
</body>
</html>
------------------------
Turn on the api to allow api testing
```
And 2 of the 3 functional http tests are passing :)
Note this will get a bit more complicated to test all php versions since the use of the flex dockers locks the testing into php 7.3. However, we also have the php-fpm openemr dockers that are used in the openemr insane docker dev env, which I bet can use to test 7.2, 7.3, and 7.4. Fun times!

**Comment by stephenwaite** [comment]
hi @bradymiller , cool, trying to follow the log and there's 2 places in the job log that mention turning it on and then executing the sql statement on the mysql docker
https://travis-ci.org/openemr/openemr/jobs/629578029#L246
https://travis-ci.org/openemr/openemr/jobs/629578029#L2788
sure would be nice to turn off the logging on the vendor clean unless there was an error i guess

**Comment by zerai** [comment]
hi @bradymiller, @stephenwaite,
we have a long pipeline, a lot of travis jobs
My assumption about the desired job is correct? Can you confirm?
php 7.2
- test yes
- lint_style no
- lint_syntax yes

php 7.3
- test yes
- lint_style no
- lint_syntax yes

php 7.4
- test yes
- lint_style yes
- lint_syntax yes

**Comment by stephenwaite** [comment]
hi @zerai, pretty surethat's what @bradymiller wants and has built on this pr, 

https://travis-ci.org/openemr/openemr/builds/629578023

**Comment by bradymiller** [comment]
yes @zerai, that is what we have now.
In the end, it will actually get more complicated since using the dockers for functional and api testing environment. i am seeing something like this:
php 7.2
- test nginx/php-fpm yes
- lint_syntax yes

php 7.3
- test nginx/php-fpm yes
- test apache/php yes
- lint_syntax yes

php 7.4
- test nginx/php-fpm yes
- lint_syntax yes
- lint_style yes

**Comment by bradymiller** [comment]
hi @stephenwaite ,
We'll be able to clean it up by sending non-error output to null device. Note that travis spits out all the commands at the beginning and end (simply just output of our commands and not where they are run). You can see where that line is actually run by searching for `Turn on the api to allow api testing `in the log (hint: it is not very exciting since the command produces no output, likely meaning it is working :)

**Comment by bradymiller** [comment]
couple more things to clarify @zerai ,
The e2e tests are no longer on the online demo, but are being done on a docker brought in by travis which is using the actual code. Note this docker also supports ssl in case need for api functional testing. On the current e2e testing the first 2 pass, but the 3rd fails (unclear why but guessing something simple). At this point, though, i think you can start working out more functional tests (feel free to use this PR as a base on your work until this PR is ready to get into the codebase).

**Comment by zerai** [comment]
Hi, can you explain to me how you test in your local machine?
Do you use another docker image for development?

I updated your latest changes, but also with the new file ci/docker-compose.yml (composer install, npm install, all the steps that are in the travis file) I don't have a test environment ready for use.

**Comment by bradymiller** [comment]
hi @zerai ,

I haven't been able to test this travis stuff in my local machine (that's why there are 25 commits on this PR since need to push to test it :) ).

For OpenEMR development and testing, I use the insane dev environment: https://github.com/openemr/openemr/tree/master/contrib/util/docker#insane-development-docker-environment
(this thing has a large number of docker images that allow testing all php versions and mysql/mariadb versions)

**Comment by zerai** [comment]
Hi @bradymiller can you check this travis file [https://github.com/openemr/openemr/pull/2867](https://github.com/openemr/openemr/pull/2867)

I think there is a bug/error in the docker instance or in the configuration,

in my local pc after login the server return a withe page (only little logo top/left corner),
maybe is the same on travis.

**Comment by stephenwaite** [comment]
hi @bradymiller , looks like there's a [docker for travis](https://stackoverflow.com/questions/21053657/how-to-run-travis-ci-locally#35972902)

maybe we can add it to the insane-dev eniro?

**Comment by bradymiller** [comment]
hi @zerai ,

I wouldn't get to into the weeds on organizing jobs and sub functioning things out, since there's still quite a bit of work to be done to support the other php version dockers for functional testing. When all the components are laid out and working, then will be a better time to organize/subfunction things out.

Even though early, a couple quick things for us to think about while organizing:
1. Is there a benefit to having less jobs?
2. The lint_style check is very long and only needs to be done for 1 version
3. Would be nice for the build to be done like is done for core OpenEMR (this is where I was thinking stages would be helpful with stages of Build Main -> Build Testing -> Install OpenEMR -> phpunit tests -> functional tests for those jobs). Then we can see if the Build Main fails, which is very helpful, since it flags us that PR or commit breaks the Build.

btw, I had no idea we could test PHP 8. pretty awesome that we can do that.

Regarding the current functional testing failing, agree that something odd must be happening for the first 2 tests to work, but not the third, and will look into this (I am guessing something simple like a permissions issue). Was planning to test out the steps in my dev environment since use that docker there and if that doesn't identify something, then will check out the travis docker @stephenwaite pointed out.

**Comment by bradymiller** [comment]
Regarding the bug, have pinpointed it down to the "user not in any phpGACL group".
This is actually really odd, since the auto install should set up the user and also place the user in the admin phpGACL group (and the other mechanisms that also use the auto install script, like the online demos, are working correctly). Still looking into this, but it looks like the functional travis tests may of identified it's first bug :)

**Comment by bradymiller** [comment]
got functional test #3 finally working; it turns out the registration request on the login screen was breaking it (had nothing to do with gacl :) ). Fixed it by setting it to opt-out via a mysql call.

**Comment by bradymiller** [comment]
hi @zerai and @stephenwaite ,
Got all the pieces now up and working on travis. Also took lots of lessons from @zerai PR at https://github.com/openemr/openemr/pull/2867 to break the functions down and hopefully catch the errors. Note that a job will timeout if go over 10 minutes (we had this problem on the openemr devops repo where doing docker builds in travis), so is better to have more jobs than combining items in 1 job (ie. keeping the syntax/style/testing things separate). Let me know if have thoughts on this strategy since am definitely flexible on direction we go (especially considering i do not know much about travis best practices). -brady

**Comment by bradymiller** [comment]
btw, here's what a travis run now looks like:
image

**Comment by pMononoke** [comment]
The default timeout setting for job execution on the public repository is 50 minutes,  the problem on openemr/devops depend from something else,
see the [suggestion](https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts) on the official guide about the '10 minute timeout' message.

Your assumption about the job's number  (more is better than less) is not correct, in my opinion.
Especially if you rely on the free time of developers/contributors, and if you consider time total execution time of the pipeline, a key factor for all developers.
```Is there a benefit to having less jobs?``` is not the right question.
As a developer, how long do you want to wait for feedback (green/red) from the pipeline? 5 minutes? 10 minutes? 30 minutes? 50 minutes?  I think less is better, so optimizing the pipeline has its advantages.

What is the advantage if not using the composer cache?
What advantage is there to download composer packages 3 times even if they are the same in all PHP versions?
What is the advantage of having the total running time of 10 minutes
if we can have it 5 minutes? 

However, the optimization can be done at another time if necessary.

The most important thing now is to define (and document somewhere) the procedure for testing on the local developer machine.

I suppose
- clone the repo
git clone .....

- run the docker
docker-compose -f ci / .... ??

- install dependencies
composer install

- install dependencies
npm install

- exec some magic script
docker-compose exec .. ???

- run all test
 php vendor / bin / phpunit

(Optional)
- run only unit test
 php vendor / bin / phpunit --testsuite unit

In the next few days, I will try the procedure.

Happy New Year!!

**Comment by zerai** [comment]
hi, sorry for the confusion, for the comment above I used my wife's github account (she is a doctor, and has an interest in EMR software).
Happy New Year!! -zerai

**Comment by bradymiller** [comment]
hi @zerai .

Agree that the time it takes to run them all is most important. It is currently at about 9 minutes. It would actually be more like 5 minutes if we weren't maxed out at 5 concurrent jobs (then the limiting step is the style run, which takes 4-6 minutes). Wordpress was able to convince travis to give them 15 concurrent jobs, so maybe we can convince travis to give us 10 :)

Regarding the cache, it just makes me nervous since this is a cache across the entire project. Thus runs of different openemr versions will have marked different composer.json files and package versions and them running all simultaneously seems like would cause issues (on the internet, there are instructions for removing composer travis cache when things go awry, which also makes me nervous. ). Are we sure that a composer cache will be robust across simultaneous use of marked different package versions?

Regarding local testing, phpunit should be straightforward. Just load in the phpunit via composer and run the script in local dev environment. Running the functional tests will be more complicated since need the chrome thing installed and that the testing path is hard-coded in tests to http:/localhost; thus if using a port for local testing environment rather than standard 80/443, then it won't work.

Looking forward to seeing the automated testing grow exponentially :)

Happy New Year!
-brady

**Comment by zerai** [comment]
You can try to increase the number of concurrent jobs.
[here](https://docs.travis-ci.com/user/customizing-the-build/#limiting-concurrent-jobs), from the guide.
Screenshot_2019-12-31 Travis CI Documentation

**Comment by bradymiller** [comment]
yep, that is not set by default. Tried to set to 20 and still stuck at 5. I found this web entry regarding wordpress: https://make.wordpress.org/core/2017/05/18/increased-concurrent-jobs-on-travis-ci-builds/
(couldn't find clear documentation of this on travis, but appears open source projects get 5 by default)

**Comment by bradymiller** [comment]
btw,
test fails work for syntax jobs
but fails are not working for the styling or build/test jobs

**Comment by bradymiller** [comment]
found reference for travis concurrent jobs limit. interestingly, they state get only 3 here for open source projects:
https://travis-ci.com/plans

**Comment by zerai** [comment]
The plans on travis-ci.org and travis-ci.com are a little bit different I guess,
we are on travis-ci.org. (5 concurrent job)
 When the current pipeline start the process it runs more than 3 concurrent jobs. 
theoretically  http://travis-ci.com plans dont affect us

**Comment by bradymiller** [comment]
Testing well and bringing this in :)
I placed summary of the jobs at the end of the logs to get an idea of what PASS/FAILS without needing to scan entire log.

**Pull request merged**
