### PR TITLE
Misc fixes version 5.0.1

### PR DESCRIPTION
**Pull request by sjpadgett**
Couple bug fixes. Please leave open for a few days in case I have more. Just wanted to get the PR up in case anyone comes across these problems.

### CODE REVIEW

**Comment by bradymiller** [comment]
Hi @sjpadgett ,
Just let me know when I can bring this PR into the codebase.
thanks,
-brady

**Comment by sjpadgett** [comment]
@bradymiller Last commit to add some date picker defaults to prevent nuisance scrolling when hovering on date input field and/or scrolling months when picker pops up.
You can merge if you find changes okay. I'll commit others in ub04 initial soon:)

**Comment by sjpadgett** [comment]
Addresses issue https://community.open-emr.org/t/jquery-datetime-picker-odd-behavior/8884?u=sjpadgett

**Comment by bradymiller** [comment]
will bring these in. thanks for the fixes! -brady

**Pull request merged**
