### PR TITLE
new password dialog box in user screen

### PR DESCRIPTION
**Pull request by visolve-openemr**
Hello Brady,

We have implemented the new password confirmation feature in openemr dev version and committed to our git instance. This is the pull request for the commit .
Please check and let us know if any changes .

Thanks,
[Visolve](http://www.visolve.com/hc/l)

(added below by bradymiller)
demo:
http://www.open-emr.org/wiki/index.php/Development_Demo#Theta_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by robertdown** [comment]
Hi @visolve-openemr, I think @robertogagliotta may have beaten you to this script. Also, we're migrating away from fancybox usage. Take a look at http://getbootstrap.com/javascript/#modals for the next generation of dialog boxes :)

**Comment by bradymiller** [comment]
related to this forum thread:
https://community.open-emr.org/t/adding-users/8771

**Comment by bradymiller** [comment]
Directed an Up For Grabs demo to this PR at:
http://www.open-emr.org/wiki/index.php/Development_Demo#Theta_-_Up_For_Grabs_Demo

**Comment by robertdown** [comment]
Closing this since outdated PR

**Pull request closed without merging**
