### PR TITLE
Demographic layout fix for comprehensive form

### LINKED ISSUE #4883: Restyle new install demographics and current Insurance
### Describe the bug
Title says it all.
Both required change for better UX.

### PR DESCRIPTION
**Pull request by sjpadgett**
Fixes #4883

#### Short description of what this resolves:
Add changes to demographics layout for better UX in new/search comprehensive form

### CODE REVIEW

**Comment by sjpadgett** [comment]
image

**Comment by bradymiller** [comment]
nice!

just noted couple changes in edit_options fields (very possible you meant to do this; I have no idea what these things do, but just noted these differences):
suffix - 'EP' was removed
birth_fname - 'K' was added
pubpid - 'ND' was removed
name_history - 'EP' was removed

**Comment by bradymiller** [comment]
2DV

**Comment by robertdown** [comment]
May I recommend we keep Birth Name and Previous names _off_ of the New Patient Form - they are very low-use fields. I would even go so far as to suggest they go into the Miscellaneous group.

**Comment by sjpadgett** [comment]
A little late @robertdown I already brought in. I don't see an issue if you want to move them or next time i'm in layouts, I can change.

**Pull request merged**
