### PR TITLE
A security fix for the process of creating a new patient

### PR DESCRIPTION
**Pull request by eyalvo-matrix**
Hi all, 

I encountered a security problem when creating a new patient
for example if you enter a new patient name with a comma you get an SQL error 
execpt from the error ,  this screen allows SQL injection 
This fix will address the problem and similar ones in this screen

Thanks
Eyal.V
name

### CODE REVIEW

**Comment by bradymiller** [comment]
There is something much more systematic going on here. In prior OpenEMR versions, all the layout engines were protected from sql injection.

**Comment by bradymiller** [comment]
I wonder if I caused this problem with the prior code change:
https://github.com/openemr/openemr/pull/736/files#diff-849cb333e9fa26c89e4d01d46866ddd3

**Comment by bradymiller** [comment]
I am pretty sure I caused this with above. Will need to create another flag for just this situation to fix this rather global sql-injection vulnerability. I'll add this to my queue.

**Comment by bradymiller** [comment]
Actually, I'll add another parameter to get_layout_form_value() function to toggle on/off sql escaping of returned value.

**Comment by eyalvo-matrix** [comment]
It seems indeed that you are right 
Just to make sure I understood you correctly will the get_layout_form_value() will be able to support
fields like names that can contain special chars ?

**Comment by bradymiller** [comment]
Should not be an issue
What specific special chars?
Note escaping will only be done where it is missing (ie. get it back to the way it was). Next step should then be dealing with those places that are requiring this to be done(hopefully this will be just a interim necessity).
This is the function that does the escaping:
https://github.com/openemr/openemr/blob/master/library/formdata.inc.php#L30

For the get_layout_form_value(), is your group ever using the 2nd parameter in any of your custom code?
(it's not being used in the main codebase, so i am planning to place the sql-escape flag in the second parameter to make it easier(and move current 2nd param to 3rd param); unless your group is using the 2nd parameter in your code)

**Comment by bradymiller** [comment]
@eyalvo-matrix  ,
cleaned up the escaping in the layouts engine (it is all done during the sql queries rather than upstream), which also fixes above issue. So will close this item.
Here's the PR that had the fix which is now in the codebase:
https://github.com/openemr/openemr/pull/834

just let me know if there are any issues

**Comment by eyalvo-matrix** [comment]
Thanks, we will pull from the codebase , do QA and check if it does fix the issue
about the chars we need the 
Char	Dec	Hex	        Oct
  '	          39	   27	         47

**Comment by bradymiller** [comment]
The solution brought into the codebase won't break special characters.

**Pull request closed without merging**
