### PR TITLE
ccda import speed up and fixes

### PR DESCRIPTION
**Pull request by bradymiller**
ccda import speed up and fixes

### CODE REVIEW

**Comment by bradymiller** [comment]
fixes:
1. More than 1 prescription is now imported
2. More than 1 immunization is now imported
3. Vitals now are always anchored to an encounter (an encounter is created if patient does not have one)
4. PHP 8 fixes

Performance:
Much faster now (@stephenwaite :fireworks: ). Here is a run of 2000 patients:
```
ccda directory: /root/synthea/output/ccda
site: default
openemr path: /var/www/localhost/htdocs/openemr
development mode is on
Starting patients import
50 patients imported (17 total seconds) (0.34 average seconds per patient for last 50 patients)
100 patients imported (36 total seconds) (0.38 average seconds per patient for last 50 patients)
150 patients imported (55 total seconds) (0.38 average seconds per patient for last 50 patients)
200 patients imported (74 total seconds) (0.38 average seconds per patient for last 50 patients)
250 patients imported (93 total seconds) (0.38 average seconds per patient for last 50 patients)
300 patients imported (113 total seconds) (0.4 average seconds per patient for last 50 patients)
350 patients imported (133 total seconds) (0.4 average seconds per patient for last 50 patients)
400 patients imported (153 total seconds) (0.4 average seconds per patient for last 50 patients)
450 patients imported (175 total seconds) (0.44 average seconds per patient for last 50 patients)
500 patients imported (196 total seconds) (0.42 average seconds per patient for last 50 patients)
550 patients imported (219 total seconds) (0.46 average seconds per patient for last 50 patients)
600 patients imported (240 total seconds) (0.42 average seconds per patient for last 50 patients)
650 patients imported (265 total seconds) (0.5 average seconds per patient for last 50 patients)
700 patients imported (290 total seconds) (0.5 average seconds per patient for last 50 patients)
750 patients imported (314 total seconds) (0.48 average seconds per patient for last 50 patients)
800 patients imported (339 total seconds) (0.5 average seconds per patient for last 50 patients)
850 patients imported (364 total seconds) (0.5 average seconds per patient for last 50 patients)
900 patients imported (390 total seconds) (0.52 average seconds per patient for last 50 patients)
950 patients imported (417 total seconds) (0.54 average seconds per patient for last 50 patients)
1000 patients imported (444 total seconds) (0.54 average seconds per patient for last 50 patients)
1050 patients imported (471 total seconds) (0.54 average seconds per patient for last 50 patients)
1100 patients imported (497 total seconds) (0.52 average seconds per patient for last 50 patients)
1150 patients imported (524 total seconds) (0.54 average seconds per patient for last 50 patients)
1200 patients imported (552 total seconds) (0.56 average seconds per patient for last 50 patients)
1250 patients imported (579 total seconds) (0.54 average seconds per patient for last 50 patients)
1300 patients imported (609 total seconds) (0.6 average seconds per patient for last 50 patients)
1350 patients imported (640 total seconds) (0.62 average seconds per patient for last 50 patients)
1400 patients imported (676 total seconds) (0.72 average seconds per patient for last 50 patients)
1450 patients imported (711 total seconds) (0.7 average seconds per patient for last 50 patients)
1500 patients imported (742 total seconds) (0.62 average seconds per patient for last 50 patients)
1550 patients imported (775 total seconds) (0.66 average seconds per patient for last 50 patients)
1600 patients imported (808 total seconds) (0.66 average seconds per patient for last 50 patients)
1650 patients imported (838 total seconds) (0.6 average seconds per patient for last 50 patients)
1700 patients imported (871 total seconds) (0.66 average seconds per patient for last 50 patients)
1750 patients imported (906 total seconds) (0.7 average seconds per patient for last 50 patients)
1800 patients imported (942 total seconds) (0.72 average seconds per patient for last 50 patients)
1850 patients imported (978 total seconds) (0.72 average seconds per patient for last 50 patients)
1900 patients imported (1016 total seconds) (0.76 average seconds per patient for last 50 patients)
1950 patients imported (1056 total seconds) (0.8 average seconds per patient for last 50 patients)
2000 patients imported (1090 total seconds) (0.68 average seconds per patient for last 50 patients)
Completed patients import (2000 patients) (1090 total seconds) (0.545 average seconds per patient)
Started uuid creation
Completed uuid creation (1101 total seconds; 0.30583333333333 total hours)
Completed run for following number of random patients: 2000
```

**Comment by bradymiller** [comment]
dang @adunsulag ! , 2k patients with all their baggage (immunizations, vitals, prescriptions, medical probs) took only 11 seconds to create all the uuids :)

**Comment by stephenwaite** [comment]
southpark_cheering

**Comment by adunsulag** [comment]
@bradymiller I'm glad it went well with the uuids.  I like optimizing stuff, its a fun puzzle to solve.

**Comment by adunsulag** [comment]
@bradymiller Do you have a target timeframe you're trying to reach for the imports.  Do you need help with the optimizations?

**Comment by bradymiller** [comment]
@adunsulag @stephenwaite ,
Goal of couple patients per second without inflation (ie. getting longer as more patients are added) and without messing to much with the current importing mechanism, which have currently met. here's a run of 10K patients:
```
ccda directory: /root/synthea/output/ccda
site: default
openemr path: /var/www/localhost/htdocs/openemr
development mode is on
Starting patients import
50 patients imported (18 total seconds) (0.36 average seconds per patient for last 50 patients)
100 patients imported (37 total seconds) (0.38 average seconds per patient for last 50 patients)
150 patients imported (54 total seconds) (0.34 average seconds per patient for last 50 patients)
200 patients imported (70 total seconds) (0.32 average seconds per patient for last 50 patients)
```
...
```
9900 patients imported (3523 total seconds) (0.34 average seconds per patient for last 50 patients)
9950 patients imported (3540 total seconds) (0.34 average seconds per patient for last 50 patients)
10000 patients imported (3558 total seconds) (0.36 average seconds per patient for last 50 patients)
Completed patients import (10000 patients) (3558 total seconds) (0.3558 average seconds per patient)
Started uuid creation
Completed uuid creation (3629 total seconds; 1.0080555555556 total hours)
Completed run for following number of random patients: 10000
```

**Comment by bradymiller** [comment]
@adunsulag , no need to spend time on this regarding performance (ie. now as fast as we need it). FHIR more important :)

**Comment by bradymiller** [comment]
man, am still blown away by the uuid stuff (making thousands each second); must be like a hundred fold increase in performance on the uuids. @adunsulag , OpenEMR is just one big performance puzzle waiting to be solved :)

**Comment by bradymiller** [comment]
testing well and bringing this in (will also rebuild the 6.1.0-dev docker later tonight).

**Comment by stephenwaite** [comment]
PICKLE

**Comment by stephenwaite** [comment]
hi @bradymiller , on the easy dev docker am getting this after about 2800 patients imported
```
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /var/www/localhost/htdocs/openemr/vendor/laminas/laminas-config/src/Reader/Xml.php on line 209
```
should we add 
```
ini_set("memory_limit", -1);
```
to the script?

**Comment by bradymiller** [comment]
agreed (think i recall getting that every once in a while; it doesn't kill
it enitre import, but the one patient that it happens to does not get
imported; likely because the ccda is very large and the data array holding
all the data breaks the memory limit)

**Pull request merged**
