### PR TITLE
Improved style of tabs layout by Robert

### PR DESCRIPTION
**Pull request by bradymiller**
This is really nice styling work by Robert of the main stuff in the main top panel of the tabs user interface.

I added a little integration work to it.

Note also need to add it to the Administration->Appearance->Enable Group Therapy module
(this is basically the same gui as interface/main/tabs/templates/patient_data_template.php, but is the interface/main/tabs/templates/therapy_group_template.php script)

### CODE REVIEW

**Comment by robertdown** [comment]
Hm, the "View Past Encounters" dropdown is covering the button upon clicking. I'll look at this

**Comment by bradymiller** [comment]
there's also an odd little black dot at the top right of the pull down (let me know if you need a screenshot, which I can do later this evening)

**Comment by robertdown** [comment]
Ha I thought that was a smudge on my monitor! I'll look at it later, probably an errant period or something

**Comment by robertdown** [comment]
Fixed the dot, fixed the position so the dropdown now correctly shows up under the button instead of covering it up.

Still need to fix the dropdown list - it is not displaying the "review" button and encounter detail properly

**Comment by bradymiller** [comment]
@robertdown ,
Let me know if I can help out at all on this to get it moving (btw, this is a really nice improvement). -brady

**Comment by bradymiller** [comment]
@robertdown ,
Just brought in a commit to do following:

1. Applied a fix to allow more than 2 links within a menu row:
https://stackoverflow.com/questions/15844533/bootstrap-dropdown-menu-two-links-on-same-horizontal-row

2. Placed Review to the left (note that this Review link is going to be much less used than the main link, so makes sense to place it to the right)

If your ok with this, then I'll bring it over to the interface/main/tabs/templates/therapy_group_template.php script

thanks, -brady

**Comment by robertdown** [comment]
Will try to get this in over the weekend

**Pull request merged**
