### PR TITLE
Fix #2219 Codebase Security Scan

### LINKED ISSUE #2219: Run Static Analysis on Codebase
https://github.com/psecio/parse

Use the above tool. Let us know the results.

### PR DESCRIPTION
**Pull request by adunsulag**
Ran the Parse Scan tool on the codebase to get a list of all the potential security vulnerabilities.
@prondubuisi did some of this work but was unable to post the entire scan as the file was huge.  Checking this into the codebase either to have it there completely or the file can just be referenced and the pull request ignored.

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @adunsulag ,

Are you to able ignore directories on this? If so, recommend ignoring following directories:
vendor
public/assets

-brady

**Comment by adunsulag** [comment]
@bradymiller I went ahead and updated the pull request to exclude the vendor and public/assets files.  Also saw the html2pdf had a vendor directory so I excluded that as well.

**Comment by bradymiller** [comment]
hi @adunsulag ,
Looking better. Lets also ignore `node_modules` directory. Also before the next run do a rebase from main master branch since 2 of the 3 errors at the top will now go away on most recent codebase.

**Comment by adunsulag** [comment]
So in addition to the node_modules should the following directories be ignored?
/projects/emr/open-emr/src/openemr/portal/patient/fwk/libs/verysimple
/projects/emr/open-emr/src/openemr/gacl/docs/examples/

**Comment by bradymiller** [comment]
hi @adunsulag ,
I would not ignore those 2. I am going to look through the gacl directory now to removed unneeded stuff, so that examples directory will likely go away :)

**Comment by bradymiller** [comment]
btw, this is another nice things about these scans; points out places in codebase that have not had much attention.

**Comment by bradymiller** [comment]
hi @adunsulag ,
Is there a mechanism to ignore certain rules in this? -brady

**Comment by adunsulag** [comment]
@bradymiller Yes there is.  The rules can be blacklisted using this command: 

```
psecio-parse scan --blacklist-rules=Rule1,Rule2,Rule3
```

Here are the rules available
image

**Comment by bradymiller** [comment]
Would ignore the following rule for now:
GlobalsUse

I am guessing that these rules should also be ignored, but lets wait on that and see how much noise they add to the report first:
ExitOrDie
OutputWithVariable

**Comment by danehrlich1** [comment]
Printed out the first 30 pages and went line by line...lol it's mainly yelling at us for $_GLOBALS and $_REQUEST.

Actual interesting things it found that I think are worthy of attention:

- using `||` and `&&` instead of `AND` and `OR`. I guess the latter are vulnerable to race conditions?
- using strict type checking in the [`in_array()`](https://www.php.net/manual/en/function.in-array.php) function...apparently it has a 3rd option you can set to true
- we kind of knew this but using `===` when possible instead of `==`

**Comment by adunsulag** [comment]
So running with GlobalsUse cuts the file in half.  Are you still wanting the RequestUse as its pretty much the same problem as GlobalsUse? Turning both of those off cuts the file down to ~9300 lines.

@danehrlich1 The || and && are due to some rare precedence bugs you can get.  If you look at the operator precedence in PHP https://www.php.net/manual/en/language.operators.precedence.php  there are five operators that have higher precedence than AND/OR that your casual developer may not know and could create situations where the code behaves differently than the author intended.

**Comment by bradymiller** [comment]
hi.
Does anybody know why this is an issue and how we could address this kind of issue:
'header()' calls should not use concatenation directly

**Comment by bradymiller** [comment]
Also, for the next report run, lets ignore the following rules (in addition to the globals and requests rules already ignored):
ExitOrDie
OutputWithVariable

**Comment by adunsulag** [comment]
@bradymiller Header calls that use concatenation directly can be used to modify the response object if the variable is not properly sanitized.

https://www.netsparker.com/blog/web-security/crlf-http-header/

I'll go ahead and rerun that report later today.

**Pull request closed without merging**
