### PR TITLE
Add custom module config support to Zend Module Manager

### PR DESCRIPTION
**Pull request by sjpadgett**
- depends on module having a moduleConfig.php in module root.

This is a baby step. Still much to do with custom modules validation/error checking in zend Module Manager. ie modules states in code can get away from us quick. Thanks @mdsupport for the code snippet.
See oe-module-faxsms https://github.com/openemr/oe-module-faxsms/tree/rel-2.0.0_oe5.0.3
for example

### CODE REVIEW

**Comment by sjpadgett** [comment]
Note that faxsms v2.0.0 is fully v5.0.3 compatible now.
composer require openemr/oe-module-faxsms:2.0

**Comment by bradymiller** [comment]
ignore the travis psr2 issue (it's from a prior commit and now fixed in codebase)

**Comment by sjpadgett** [comment]
Ignore Travis! umm, gladly:)

**Comment by sjpadgett** [comment]
image

**Comment by sjpadgett** [comment]
Bringing in to work on FHIR. Everyone has given some great insights in to modules and i'm slowing getting them implemented.

**Pull request merged**
