### PR TITLE
quick fix for last commit

### PR DESCRIPTION
**Pull request by stephenwaite**
move the function call

### CODE REVIEW

**Comment by bradymiller** [comment]
code looks good to me . worse thing is it won't work which is current status quo :)

**Comment by stephenwaite** [comment]
you mean checking `LBFs`?
Screenshot from 2021-12-18 16-38-31

**Comment by bradymiller** [comment]
sorry to confuse, just meant the script was completely broken at this time, so couldn't really get worse :)

**Comment by bradymiller** [comment]
Willing to bet your fix will get it to work as @mdsupport intended though.

**Comment by stephenwaite** [comment]
Testing well

**Comment by bradymiller** [comment]
2DV-2

**Comment by mdsupport** [comment]
We had patched the location identified by @stephenwaite sometime ago. So the diff with prior never picked it up that and the code tested ok.

The empty check should apply centrally. Caller should not have to worry about parameters.

Sorry for the confusion.

**Pull request merged**
