### PR TITLE
Wrong form fetch pid for questionnaires from auditing

### LINKED ISSUE #6205: Wrong form fetch pid for questionnaires from auditing.
### Describe the bug

During Portal Audit the current patient pid is used by API instead of patient documents correct pid when retrieving questionnaire from table.

### To Reproduce
Select any other patient besides an audited patient document associated pid.
Exception is thrown or at least now one is.

### Client configuration

- Browser:
- OpenEMR version: v7
- Operating system: windows 11 pro

### PR DESCRIPTION
**Pull request by sjpadgett**
Fixes #6205 

#### Short description of what this resolves:
Fixed where selection is by the table id

### CODE REVIEW

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
dance-bear

**Comment by sjpadgett** [comment]
If not mistaken I believe we have patterns in next release that require PHP 8.1+
Current
```
"require": {
        "php": ">=8.0.0",

"platform": {
            "php": "8.0"
        },
```

**Comment by bradymiller** [comment]
Next release minimum is 8.0, so hopefully no 8.1+ required code (haven't note any brought in but could of missed it).

**Comment by sjpadgett** [comment]
@bradymiller Any idea why maria 10.6 fails?

**Comment by bradymiller** [comment]
hi @sjpadgett , ok to ignore 1-2 random fails on the Test categories (Can correct it by rerunning that one test, but we generally don't do anymore for these random fails; saving github some electricity :) ).

**Pull request merged**
