### PR TITLE
chart_tracker.php bootstrap convertion

### PR DESCRIPTION
**Pull request by robertogagliotta**
@bradymiller @robertdown  Unit Testing Ok. script ready for code review.

### CODE REVIEW

**Comment by bradymiller** [comment]
@robertogagliotta ,
You're getting much more proficient at bootstrap :)
To make it more clear, I added a commit in thiss PR to do the following:
Used `well` class to separate out the 2 different forms on this gui.
I also placed the 2 different forms in separate rows if the screen is wide enough.
I placed the alert messages within bootstrap alert classes

Test it out and let me know your thoughts on it. -brady

**Comment by robertogagliotta** [comment]
@bradymiller  screen shots before bootstrap upgrade
screen1_before_boot
screen2_before_boot

**Comment by robertogagliotta** [comment]
@bradymiller   screen shots after bootstrap upgrade
screen1_after_boot
screen2_after_boot

**Comment by robertogagliotta** [comment]
@robertdown  @bradymiller  GOOD UI IMPROVEMENT

**Comment by robertogagliotta** [comment]
Hey Brady, After I digest the code you made I will move foward

**Comment by bradymiller** [comment]
@robertogagliotta ,
Sounds good and I'll bring this into the code base. Main learning point I brought in were using the bootstrap alert class, which makes the error/success messages look nice. The other minor learning points of the well class and supporting 2 columns are also helpful (albeit, I only use these in a minority of cases).

**Pull request merged**
