### PR TITLE
Login Page Overhaul (#3654)

### LINKED ISSUE #3654: Login Page Overhaul
As pointed out by @juggernautsei - the landing page is in need of an update. Once #3626 is merged I plan to do a huge task: unifying the login page design for every theme and redesigning it from the ground up. The main thing i'll do is shrink the size of the box and then possibly do a really cool gradient or something of that nature. This is gonna be awesome. 🙂

All credit for this design change will go to @juggernautsei even though i'm coding this part.

### PR DESCRIPTION
**Pull request by tywrenn**
Fixes #3654

#### Short description of what this resolves:
Completely overhauls the login page, making it so much more elegant!

emrportal

### CODE REVIEW

**Comment by tywrenn** [comment]
@bradymiller Ready to merge

**Comment by tywrenn** [comment]
Already see a bug with the dark theme

**Comment by tywrenn** [comment]
emrportal-dark
emrportal-superhero

**Comment by tywrenn** [comment]
@bradymiller Now all fixed -- ready to review/merge now

**Comment by bradymiller** [comment]
@tywrenn , I just tested this and:
**wowsers!!**
Bringing this in now.

And, of course, the OpenEMR fans are ecstatic:
2DV

And travis is, of course, pouting:
tenor (5)

**Pull request merged**
