### PR TITLE
Move to FHIR current R4 release

### PR DESCRIPTION
**Pull request by sjpadgett**
- delete STU3
-  Add R4
- api's next

### CODE REVIEW

**Comment by sjpadgett** [comment]
i'm going to bite bullet and fix classes for travis and push new commit

**Comment by bradymiller** [comment]
Hi @sjpadgett ,
I have a method to try this automatically. Let me know can push that to this PR. If we can't do all these automatically, then we can skip the directory here:
https://github.com/openemr/openemr/blob/master/ci/ci.sh#L44-L50
(ie. if you can't beat them, then ignore them :) )

**Comment by bradymiller** [comment]
as an aside, I'm gonna see what happens when try to remove a couple of those ignored directories :)

**Comment by sjpadgett** [comment]
A TOTAL OF 47134 ERRORS WERE FIXED IN 894 FILES
is what I come up with so i'll push and see what travis says. or do you want to do it?

**Comment by bradymiller** [comment]
go for it

**Comment by bradymiller** [comment]
travis is passed!

**Comment by sjpadgett** [comment]
okay, good to go. will bring in unless something else

**Comment by bradymiller** [comment]
great. after this is in, I'll see about trying to remove a couple of the ignored directories.

**Pull request merged**
