### PR TITLE
changed AMC_304b_1_STG2 and AMC_304b_2_STG2 Denominators to reflect t…

### PR DESCRIPTION
**Pull request by venambati**
…he prescriptions that are transmitted only and not medentry

### CODE REVIEW

**Comment by venambati** [comment]
@bradymiller here are the changes to fix AMC report for eprescriptions, please let me know if you see any problems or defects.

Thank you

**Comment by bradymiller** [comment]
@venambati ,

According to the MU2 docs, the denominator needs to be all prescriptions. It looks like this will include in the denominator only erx prescriptions.
https://www.healthit.gov/sites/default/files/170%20314(g)(1)(g)(2)-v2.4.pdf
(see page 41)

I recall you posted your use case issue somewhere. Can you provide the link here, so I can look at it, and then we can figure out where to go from there.

thanks,
-brady

**Comment by venambati** [comment]
@brady miller
sorry I did not get back to you on this earlier. Here is my usecase:
Patients who are referred to us by other physicians come with their current medications that they are actively taking, when this patient comes to us - we enter their medications from other provider in newcrop MedEntry, but we never prescribe these or transmit to the pharmacy. On the other hand we may prescribe new medications to the same patient and these we send to pharmacy by going to MedEntry-> Compose Rx and transmit them to Pharmacy.
The medications we enter into MedEntry are for record keeping or tracking purpose only. When we are calculating AMC measures and E-Prescibing we should only count the prescriptions that  we transmit to the pharmacy. 

But openem 5.1 is calculating/counting both entered as well as transmitted prescriptions into the the denominator. This is not the case before openemr 5.1.
The patch I submitted is to fix this issue. please let me know if there is any misunderstanding on my end. We are still including all prescriptions into the denominator for MU2 purposes but we are just excluding the prescriptions that are active but only entered into openemr for tacking purposes by the physician.
please let us know if this helps and if we can accept this patch.
Thank youVenkat  

 
Venkat Ambati

**Comment by bradymiller** [comment]
hi @venambati ,
Thanks for the explanation. Will look into this over the next couple days.
-brady

**Pull request closed without merging**
