### PR TITLE
Fix encounter POS

### PR DESCRIPTION
**Pull request by sjpadgett**
-  Add Telemedicine POS ie. 02
- Fix encounter newpatient form logic flow
- Fix POS default logic
- Fix not selecting saved POS on encounter view(chance of selecting multiple POS on list init)
- Back ported to v5.0.1 for patch
Back port 5.0.1 commit is here:https://github.com/openemr/openemr/pull/1895/commits/43cd97c48427169c7bd3506526a49b7a9d1bb11c

### CODE REVIEW

**Comment by sjpadgett** [comment]
Main issue is on last restyle, POS pull down was moved ahead of facility init's causing POS default and view selection to not initialize properly.
Also the Place of Service does not have to be a billing location. Previous code only set POS if facility was a billing location so changed to users default facility POS regardless of facility type.
@stephenwaite and @juggernautsei Check me on this please.

**Comment by stephenwaite** [comment]
ok, wow, thanks for this work

**Comment by bradymiller** [comment]
hi @sjpadgett , Code looks good to me. Thanks! -brady

**Comment by sjpadgett** [comment]
Guessing nobody has issue with this so bring in.

**Pull request merged**
