### PR TITLE
fix: faxsms psr7 vendor fix

### LINKED ISSUE #7793: bug: report pdf error with faxsms module installed
### Describe the bug

https://community.open-emr.org/t/unable-to-create-pdf-report-error-with-mpdf/23729/2
### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #7793

### CODE REVIEW

**Comment by stephenwaite** [comment]
how's this @sjpadgett ?

**Comment by sjpadgett** [comment]
Nice and should work. I'll let you know from my testing. I was working on taking out reference in autoloader.
I still don't understand how autoloader in namespace allows core psr reference in core. It's not caused by 
`//$classLoader->registerNamespaceIfNotExists('OpenEMR\\Modules\\FaxSMS\\', __DIR__ . DIRECTORY_SEPARATOR . 'src');`
but autoloader instead.

It may turn out to be a learning experience or i'm just getting bad at my job.:)

Your way is the best way for an easier implementation, much appreciated @stephenwaite as I was just lazy to empty all those files:)

However, I just need to know why this is an issue because this will come up again!

**Review by sjpadgett — APPROVED** [review]
This is working well and saves having to delete directory. Nice work @stephenwaite and mush appreciated.

**Comment by sjpadgett** [comment]
lol mush Stephen

**Comment by stephenwaite** [comment]
```bash
#!/bin/bash

list_files=$(find src/openemr/interface/modules/custom_modules/oe-module-faxsms/vendor/psr -name "*.php")
while read -r file; do
  echo "$file"
  truncate -s 0 $file
done <<< "$list_files"  

exit
```

**Comment by bradymiller** [comment]
kung-fu-baby-funny

**Pull request merged**
