### PR TITLE
Restyled fully responsive Message Center

### PR DESCRIPTION
**Pull request by zbig01**
Restyled messages, dated reminders and added styling to integrate Recall Board
with overall themes

Message captions more meaningful, changed links to buttons, restyled dated
reminders to have the ability to display more than 5 reminders by
adding scroll bar

Now all aspects of the message center are fully responsive

Of course added a help file ;)

library/MedEx/API.php
interface/main/messages/messages.php
interface/main/messages/message_center_help.php
library/dated_reminder_functions.php
interface/main/dated_reminders/dated_reminders.php
interface/main/dated_reminders/dated_reminders_add.php
interface/main/dated_reminders/dated_reminders_log.php

Some screeshots

The new message center

01-messages-openemr

Reminders with scroll bar

02-messages-openemr

Recalls

03-messages-openemr

New Message

04-messages-openemr

Edit Existing Message

05-messages-openemr

Toggle to show all messages

06-messages-openemr

Send a remider

07-messages-openemr

Dated Message log

08-messages-openemr

Resized Dated message log with messages

09-messages-openemr

Dated Message Log with filter section hidden

10-messages-openemr

New Recall

11-messages-openemr

Default Recall Board

13-messages-openemr

MedEx Enabled Recall Board

14-messages-openemr

MedEx Enabled Message Center with SMS Zone

15-messages-openemr

SMS Zone

17-messages-openemr

Last but not the least - The help page

18-messages-openemr

Below added by bradymiller:
Up For Grabs demo for this PR is at:
https://www.open-emr.org/wiki/index.php/Development_Demo#Mu_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by bradymiller** [comment]
Added an Up For Grabs demo to test this PR at:
https://www.open-emr.org/wiki/index.php/Development_Demo#Mu_-_Up_For_Grabs_Demo

**Comment by zbig01** [comment]
Thanks, looks great :+1:

**Comment by mdsupport** [comment]
This may not be correct place but still sharing few of the features we have incorporated to make messages easier to "take care of" -
1. Merge messages and reminders into a single list.  5 or less due reminders always appear at the top of messages.  That removes a common excuse/reason for delay in completion of planned tasks - "I forgot to check the reminders".
2. Click on a line opens the details inline.
image
3. Use bootstrap navbar for full screen.
image
4. Use status as dropdown for commonly used actions that perform ajax updates without need for details screen.
image
5. Drop-downs on navigation bar are great for showing popup / inline reports for reminders etc.
image
6. Since we use CDR engine to manage recalls, that part is skipped.  However conceptually recall is just a message from the system.

Due to different approaches taken by developers, it is hard to unify various action items into a single app.

**Comment by bradymiller** [comment]
@zbig01 ,
Just checking if it makes sense for me to rebase this to most recent codebase to make it simpler (ie. would remove all the styling file changes)?
-brady

**Comment by zbig01** [comment]
@bradymiller 
Please close this PR. I will submit a new PR for the Message Center along with help file poining to the wiki for the MedEx enabled  features

**Pull request closed without merging**
