### PR TITLE
Replaced qtip2 tooltip with plain javascript tooltip

### LINKED ISSUE #2071: Create Javascript Feature That Replaces qtip2
hi @sjpadgett , @danehrlich1 , @harshlele ,

I've been concentrating on migrating to new jquery version for last month or so (have gotten rid of 5 or 6 versions at this point i think):
https://github.com/openemr/openemr/issues/842

And some things I've noted:
1. jquery-ui and jquery related packages are dying (for example, jquery-ui last release was 2 year ago and last commit to their github repo was 18 months ago!)
2. Agree this doesn't bode well for jquery's future (still a commit on their repo several times per month)

Goal at this point is to get all the jquery's to most recent jquery version (then will begin to drop jquery-ui support). On the jquery front, a good very specific js exercise would be to drop use of qtip2 in the following script (it breaks with most recent jquery and qtip2 is a dead project):
https://github.com/openemr/openemr/blob/master/interface/main/display_documents.php#L45

Objective:
1. Create that tooltip with pure js (ES6). Note this will also drop reliance on the jquery-ui in that script and allow use of most recent jquery. And we can then leverage this mechanism for a couple other places that use qtip2.

To see that script at work in OpenEMR:
1. create a patient
2. go to patient dashboard->Documents
3. add a jpg image to the Lab Report category
4. In OpenEMR menu, go to Procedures->Lab Documents
image
5. Hover over your filename
image
6. Click on the image in the tooltip (it zooms in):
image

-brady

_Originally posted by @bradymiller in https://github.com/openemr/openemr/issues/2064#issuecomment-450032073_

### PR DESCRIPTION
**Pull request by harshlele**
Fixes #2071 

below added by bradymiller:
Up For Grabs demo for this PR:
https://www.open-emr.org/wiki/index.php/Development_Demo#Gamma_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by harshlele** [comment]
@danehrlich1 
I was a bit confused in the beginning,because the qtip2 tooltip actually seems to behave differently on chrome and firefox. On chrome, it opens zoomed in by default, while on firefox, it starts with the entire image visible, and zoom-in when you click on the image. In my commit, I've made it so that on both browsers, the image is visible, and it zooms-in when you click the image.

**Comment by danehrlich1** [comment]
@harshlele Yeah the browsers all respond slightly differently to CSS. This is changing though. Microsoft just switched to the same browser engine as Chrome. Firefox will probably do this at some point too.

1. You can use Javascript to check for which type of browser the user has and then render different CSS based off of that.

2. Have you looked at using the Dev Tools for inspecting CSS? If not it will save you a TON of time. You can edit the CSS live and a lot more: https://developers.google.com/web/tools/chrome-devtools/css/

**Comment by sjpadgett** [comment]
Try setting a doctype.

**Comment by bradymiller** [comment]
Up For Grabs demo for this PR:
https://www.open-emr.org/wiki/index.php/Development_Demo#Gamma_-_Up_For_Grabs_Demo

**Comment by bradymiller** [comment]
hi @harshlele ,

Very nice! I just realized that it needs to also work for pdf files. For example, here's how a pdf works in the main development demo:
image

-brady

**Comment by harshlele** [comment]
ah ok that will need changes then

**Comment by bradymiller** [comment]
hi @harshallele ,
Code looks great and it tests well. Going to bring this into codebase and thanks for doing this! -brady

**Comment by bradymiller** [comment]
fyi,
Did a little more work on this and script is now using most recent jquery. thank you @harshallele for making this possible! -brady
https://github.com/openemr/openemr/pull/2082/files?w=1

**Pull request merged**
