### PR TITLE
Layout item display when list entry are missing

### PR DESCRIPTION
**Pull request by mdsupport**
Display key value for the layout item when key is not found in associated list(s)

### CODE REVIEW

**Comment by bradymiller** [comment]
Bring it on in :)
Agree on the dirname thing; neat trick to know.

**Comment by sjpadgett** [comment]
@bradymiller How do you highlight/comment code when you review. Can't seem to figure it out:)

**Comment by bradymiller** [comment]
hopefully below helps
image

**Comment by bradymiller** [comment]
To clarify, when the mouse is in that position where the blue plus sign is, then you can click on the blue plus sign and it will open the comment.

**Comment by sjpadgett** [comment]
Great thanks and my goodness, do 'ya have enough tabs opened? :)

**Comment by bradymiller** [comment]
lol, have even more opened now:
image
(trying to figure out docker swarm, which is about half of those tabs :) )

**Pull request merged**
