### PR TITLE
Add Inhaled Oxygen Concentration for ccda.

### PR DESCRIPTION
**Pull request by adunsulag**
Cleaned up a bit of vitals and added the inhaled_oxygen_concentration
field.  @sjpadgett Does this work for you?

### CODE REVIEW

**Comment by adunsulag** [comment]
image

Here's a screenshot of the additional field.

**Comment by sjpadgett** [comment]
@adunsulag Inhaled Oxygen is a percentage

**Comment by adunsulag** [comment]
@sjpadgett Hopefully that's all resolved now.

**Comment by bradymiller** [comment]
hi @adunsulag , Looks good and bringing in. thanks!

**Comment by stephenwaite** [comment]
labresult

**Pull request merged**
