### PR TITLE
Readme docs updated more meaningful, opened the issue and linked it

### PR DESCRIPTION
**Pull request by Shoaib7889**
Elaborated the instructions of the readme file as per suggestions, where I found it difficult to understand.

Fixing issue #4909

### CODE REVIEW

**Comment by adunsulag** [comment]
Thanks for the documentation updates @Shoaib7889.  We hope you can continue to contribute in the future!

**Comment by bradymiller** [comment]
2DV

**Comment by stephenwaite** [comment]
excited_elephant

**Comment by Shoaib7889** [comment]
> Thanks for the documentation updates @Shoaib7889. We hope you can continue to contribute in the future!

It is a pleasure for me that my little effort is merged & will be helpful for the community 😊.

**Pull request merged**
