### PR TITLE
More Changes and Fixes Modules

### LINKED ISSUE #7758: Template access from Demographics several issues
### Describe the bug
Several bugs like 404 when calling a document, saving and limits from history larger than 20 activities(pagination).

### PR DESCRIPTION
**Pull request by sjpadgett**
- add update to log sync for erx changes
- rename Weno Provider ID to  Weno User ID in Users

Fixes #7758 

#### Short description of what this resolves:
for patch 2

### CODE REVIEW

**Comment by sjpadgett** [comment]
Finally able to tune up Dashboard styling.
image

**Comment by bradymiller** [comment]
2DV-2

**Comment by sjpadgett** [comment]
The Patient Documents is shaping up to be a very useful feature, finally!

image
Able to now filter out Locked status and orderBy

image
image

**Comment by sjpadgett** [comment]
added an alert to lists save. on my system save isn't obvious. looking at the more than 40 codes in fee sheet list not saving the 40 - total.
btw: the alert is from using the asyncAlertMsg() in utility.js so almost always in scope. If you want to use persist and got it button use alertMsg() from dialog class.

image

**Comment by sjpadgett** [comment]
ho hum!

**Comment by sjpadgett** [comment]
Finally. It took a hurricane to prompt me but added option by audit user to delete! ta da....
next let reviewer send comment to patient and send a sms or email notification whenever user sends a secure message to patient that they have a secure message waiting for them. This way patient doesn't wait until logging in. I think i'll default to email.
Somebody buy me a Mountain Dew.....

image

**Comment by bradymiller** [comment]
2DV

**Pull request merged**
