### PR TITLE
Refactor: refine the message section pages

### PR DESCRIPTION
**Pull request by stu01509**
#### Short description of what this resolves:
- Remove the nested grid system.
- Remove outdated and unnecessary code.
- Adjust the form-group style.
- Fix the form and table responsive overflow issue.
- Fix the button style and broken icon.

image

image

image

image

image

image

image

### CODE REVIEW

**Comment by stu01509** [comment]
Hello @tywrenn  and @bradymiller 

I would like to convert the dated reminders to the Bootstrap list or table style, What do you think?

image

**Comment by bradymiller** [comment]
hi @stu01509 , Code looks good to me and is testing well. Will bring this in when get blessing from @tywrenn . Regarding converting the dated reminders to bootstrap list/table style, go for it if you think it will look better.

**Comment by stu01509** [comment]
Hello @bradymiller 

Thanks for your feedback, I will be waiting for @tywrenn suggestion to decide.

**Comment by tywrenn** [comment]
@stu01509 Describe to me specifically what this changes as it looks pretty similar to master

**Comment by stu01509** [comment]
@tywrenn 

Yeah, although it looks like a similar master branch, but in this PR, I change those below

- Remove the nested grid system.
- Remove outdated and unnecessary code.
- Adjust the form-group style.
- Fix the form and table responsive overflow issue.
- Fix the button style and broken icon.

**Comment by stu01509** [comment]
Hi @tywrenn 

Thanks for your mention, I updated the commit.

image

**Comment by bradymiller** [comment]
hi @stu01509 , bringing this in. thanks for the improvements! -brady

**Pull request merged**
