### PR TITLE
Updated Procedure order and Electronic Report

### PR DESCRIPTION
**Pull request by sjpadgett**
#### Short description of what this resolves:
- updated filters
- fetch results all or by each lab provider
- labcorp requisition and custom HL7
- results parse handles more labs
- specimen labels

### CODE REVIEW

**Comment by sjpadgett** [comment]
Brady i'm still testing and need to do fresh install. However, i'm sure you'll find some escaping issues or anything else.
I almost rather be doing CCDA!!
Getting close, maybe week to finish project.

**Comment by bradymiller** [comment]
dang, lot of code :)
can't we bring in tcpdf package via composer.json?

**Comment by sjpadgett** [comment]
no because not php7.4,8.0,8.1 compatible.
Lots of case statement errors.

**Comment by bradymiller** [comment]
Did you have to fix these manually?
(i could just do what we did with the jwt library where we hold our own repo with working code)

**Comment by bradymiller** [comment]
to add to above, if you are looking to get this into a 6.0.0 patch, then how you have it now is best. (then can figure out how to get it in composer.json in the future and maybe by then tcpdf will get its act together :) )

**Comment by sjpadgett** [comment]
I've been waiting a year for that to happen. I may just pull the 2d PDF417 barcode from requisition and use fpdf for 1d labels.
I don't need it in code right now and will figure it out when I bring in my Quest classes later.
I'm going to revert and try again tomorrow. I was hoping I had all the php 8 done but guess not.

**Pull request closed without merging**
