### PR TITLE
Adding the Amendment class

### PR DESCRIPTION
**Pull request by robertdown**
This is the result of yet another tangent. While working on the updated demographics page I was trying to figure out the best way to remove fancybox. One of the dialogs I was spending a lot of time on was the amendments. It was (not surprisingly) _very_ intertwined. So I began to untangle and ended up with this. It's not quite complete, but I'd say about 70% finished. This fully separates the business level logic of CRUD'ing the amendment info, offers a pseudo-controller class which allows for easy interaction with the service. It also breaks out the HTML and introduces Twig as an improved templating engine. Oh, it also converts the dialog to bootstrap.

@MatthewVita this is kind of modernization. It untangles a lot of stuff that impacts my project quite a bit, but also obviously is up your alley as well. I know the module isn't really in the file system location you've been working on, would you be ok if this lives under `library/Amendment`?

I'm hoping this provides some clarity for developers looking to write modernized code. I'd love to get the demographics page finished, but it seems like I have to get fancybox out before it gets finished.

(Sorry for the novel)

### CODE REVIEW

**Comment by MatthewVita** [comment]
Hi @robertdown,

Whether you use the existing `services/`, `repositories/`, `entities/` pattern or a more fractal pattern such as the `library/amendment` approach you're taking, I'm happy as long as the business logic is separated from the view. We'll consolidate everything later.

I took a look at the diffs, and I can't tell what you added/edited because of the new vendor stuff. Can you point me to the files that I'll be interested in from an early review perspective?

Also, you checked in some git conflicts (I noticed the `=====` markers) if you're wondering why Travis is complaining.

**Comment by robertdown** [comment]
I noticed the conflicts..... very rare I miss those before committing, though it was very late last night. As far as the files, look at 'library/Amendment' that's where most of the changes are. I should have committed the vendor stuff separately 😐

**Comment by MatthewVita** [comment]
Ah, I sorry have put that together >.<.

Good looks good so far!

**Comment by MatthewVita** [comment]
BTW, an aside, I'm so happy to see modernization code being developed. I need to step it up on my end, however.

It would be really neat to set up a basic REST API (set up as a "sidecar" in OpenEMR) once we get enough of the domain separated :).

**Comment by bradymiller** [comment]
Couple quick things for now:
1. Bring in the composer related items(only the items that this specific feature needs; ie. not phpunit for now :) ) on a separate PR (just so we can do a quick once over), so we can get that into codebase asap. (even if we in the end don't go with twig, it's simple to remove the packages). This makes review and testing of the real changes must easier.
2. Some broad questions on the twig stuff. Is there a mechanism to html escape and translate? Are we confident twig will last (ie. commit history looks like it is mostly a 1 man show) or would it be straightforward to break it out into pure php if twig didn't last?

**Comment by robertdown** [comment]
I think Twig is stable and will last - it's part of the Symfony project, which is a top PHP project. Breaking out into pure PHP is something we need to move away from, separation of content is a key part of moving to a modern codebase. I'll start a new PR that pulls in the composer stuff strictly related to this PR

**Comment by robertdown** [comment]
Twig isn't just a one-man show: https://twig.sensiolabs.org/contributors

**Comment by robertdown** [comment]
As far as escaping and translations... yes and no. They have a way we can add functions to the engine, will do that

**Comment by robertdown** [comment]
Closing this mess of a PR and creating a new one that actually only touches the files that we've changed

**Pull request closed without merging**
