### PR TITLE
Cleaning up libary dir moving JS and CSS files.

### PR DESCRIPTION
**Pull request by Wakie87**

### CODE REVIEW

**Comment by bradymiller** [comment]
Hi,

Won't these changes break all the custom forms that folks have created?

Note that shouldn't stop us from placing all the third party stuff in public/assets via bower, but not sure if just moving them into css or js is worth breaking all the custom forms that have been created by users.

-brady

**Comment by sunsetsystems** [comment]
To the degree that you do change references to .js files, how about also implementing the new convention to insulate users from browser caching errors when those files change.  See this in version.php:

// Version for JavaScript includes. Increment whenever a .js file changes.
// Also whenever you change a .js file, make sure that all URLs referencing it
// end with "?v=$v_js_includes".  Search the code for examples of doing this.
// All this is to keep browsers from using an older cached version.
$v_js_includes = 1;

**Comment by sunsetsystems** [comment]
By the way I haven't tested it but I think that may work for .css files too.

**Comment by sunsetsystems** [comment]
Wow.  You may have won the prize for the most files changed in one commit!  :)

**Comment by Wakie87** [comment]
Hahah  :laughing: I will be signing autographs later :stuck_out_tongue_winking_eye: 

Thankyou sublime text for the help. On a side note, I did not replace any of the JS in phpmyadmin.

**Comment by bradymiller** [comment]
I agree that this commit warrants a prize and I will also wait in line for the autograph :)
(also plan to try out sublime text; perhaps it's time to do away with vim...)

Regarding the css/js re-organization, rec discussing this on the forum since it will break all customized patient forms(this is the most common customization that users do) when they upgrade to OpenEMR 5.0.0. Need to ensure that this is worth it. For the third-party scripts, will be more efficient to just send them right to public/assets .

**Comment by bradymiller** [comment]
Another though on the css/js reorg. Id there a way to leave behind a script stub that will redirect(ie. include) the new script place. This could then be kept around for awhile until we give the community time to fix their custom patient forms.

**Comment by sunsetsystems** [comment]
I think css can do that with @import but it's not so simple with javascript.  Maybe document some redirect rules for Apache?

**Comment by Wakie87** [comment]
My thoughts on this were that the JS files will most likely move again (but at least they are centralised for future moving) and since we are bumping up to 5.0.0 means there will be backward compatability issues right? When people update....they will also need to update their own pre-built forms...

**Comment by bradymiller** [comment]
There is likely going to be a bit of carnage with the INNODB migration already for upgraders to 5.0.0 (I would not be surprised if we get hit with some nasty bugs right after release when it gets heavy use).

Just have a hard time explaining to users that they need to modify all their custom forms because we wanted to organize the scripts into js/css. And then we will need to tell them again in the future when we organize them again. I think will be better to do this in 1 swoop(ie. 1 release rather than over severla releases) (so when we bring the standard 3rd party libraries from the forms to public/assets, we also do this js/css organization of the non 3rd party scripts).

thoughts?

**Comment by sunsetsystems** [comment]
It's a good opportunity to remind those with custom forms that this is a reason to share them with the project. :)

**Comment by bradymiller** [comment]
actually, are there even any 3rd party assets being used by the standard forms?
also, the xmlformgen code will need updating

**Comment by bradymiller** [comment]
disregard xmlformgen comment. that has been done.

**Comment by bradymiller** [comment]
Also, lets discuss this on the forums so the community can prepare and/or voice opinions on this.
-brady

**Comment by robertdown** [comment]
Closing this since outdated PR

**Pull request closed without merging**
