### PR TITLE
fix: expand/collapse widgets on dashboard

### LINKED ISSUE #6993: bug: expand/collapse of widgets on dashboard summary javascript error when click on the font-awesome icon
### Describe the bug

write concise description of what the bug is.

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #6993

#### Changes proposed in this pull request:
starting with prescriptions and hopefully is similar fix for most

### CODE REVIEW

**Comment by sjpadgett** [comment]
Works fine on windows! Change renders the same result though better readability

**Comment by stephenwaite** [comment]
hah, yeah!

cleaner code but will close this and work on why immunizations widget collapse persist isn't sticky

**Comment by bradymiller** [comment]
To clarify, on my prior testing, clicking on the actual labels works fine with the persistence. When click on the actual icon though is when have problems (throws a javascript error and does not persist)

**Comment by sjpadgett** [comment]
Yep, I see that

**Pull request closed without merging**
