### PR TITLE
Escape chart tracker location data

### PR DESCRIPTION
**Pull request by MatthewVita**

### CODE REVIEW

**Comment by MatthewVita** [comment]
Hi @bradymiller, this will escape the chart tracker data. Sorry I missed this in the review.

@kofiav just a note that this must be done in future.

**Comment by bradymiller** [comment]
looks good to me and thanks for doing this. bring it in! -brady

**Comment by MatthewVita** [comment]
Thanks!

**Comment by kofiav** [comment]
It's all good, thanks, I will keep this in mind.

**Pull request merged**
