### PR TITLE
Updates a few Dependencies, including Bootstrap

### LINKED ISSUE #3973: Update Bootstrap to 4.5.3
https://blog.getbootstrap.com/2020/10/13/bootstrap-4-5-3/

### PR DESCRIPTION
**Pull request by tywrenn**
Fixes #3973

#### Short description of what this resolves:

This updates Bootstrap to 4.5.3. It also updates some gulp dependencies as well as stylelint. It also updates Font Awesome to the latest version.

### CODE REVIEW

**Comment by bradymiller** [comment]
@tywrenn ,
All the travis builds are showing this error (Are you seeing this on your local testing?):
```
[18:03:04] 'rtl_style_color' errored after 1.42 s
[18:03:04] Error in plugin "gulp-postcss"
Message:
    PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
Details:
    fileName: /home/travis/build/openemr/openemr/interface/themes/colors/style_ash_blue.css
    domainEmitter: [object Object]
    domainThrown: false
Stack:
Error: PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/home/travis/build/openemr/openemr/node_modules/postcss/lib/processor.js:167:15)
    at new Processor (/home/travis/build/openemr/openemr/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/home/travis/build/openemr/openemr/node_modules/postcss/lib/postcss.js:55:10)
    at /home/travis/build/openemr/openemr/node_modules/gulp-postcss/index.js:50:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[18:03:04] 'default' errored after 1.44 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openemr-interface@0.2.0 build: `gulp -b`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openemr-interface@0.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2020-10-16T18_03_05_476Z-debug.log
```

**Comment by tywrenn** [comment]
Sounds like a dependency needs updating for a dependency 😂

**Comment by tywrenn** [comment]
@bradymiller Fixed it -- now ready for review

**Comment by bradymiller** [comment]
hi @tywrenn , Testing well and bringing in. Thanks for the improvements! -brady

**Pull request merged**
