### PR TITLE
turn off repeat for provider out of office event

### PR DESCRIPTION
**Pull request by stephenwaite**
fix typo

### CODE REVIEW

**Comment by stephenwaite** [comment]
hmm, in office and lunch are also set as repeat, maybe there's something more going on...
plus will probably have to decipher the recurring event syntax :0

**Comment by dimitristsilis** [comment]
Why do you think these need to change?

**Comment by dimitristsilis** [comment]
@stephenwaite Why do you think these need to change?

**Comment by stephenwaite** [comment]
hi @dimitristsilis , not sure it's necessary to default to repeating with these provider events

**Comment by dimitristsilis** [comment]
@stphenwaite Well, it's not necessary, but it is sensible. If I reserve some time for lunch, I will do it every day. If I have to visit a patient at home to inject LMW heparin, I will probably do it at the same time for a few more days.

**Comment by mdsupport** [comment]
@stephenwaite These are proxies for practice hours or physician's daily schedule.  The standard logic does need a change where administrator sets a "Practice or Facility" schedule to be applied to all calendars and the start date is automatically rolled forward everyday.  Calculating recurring events is expensive.

**Pull request closed without merging**
