### PR TITLE
wrong fax file destination in dialog.

### PR DESCRIPTION
**Pull request by sjpadgett**

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller So Doctor, is there a diagnosis code for scatter brain? Bet you could find a snomed for it at least!

**Comment by bradymiller** [comment]
This is the closest I could find :)
SCTID: 406506008

**Comment by bradymiller** [comment]
btw, looks good to bring in

**Comment by bradymiller** [comment]
just pinging this since plan to work on the next 5.0.1 patch soon :)

**Comment by bradymiller** [comment]
another ping :)

**Comment by sjpadgett** [comment]
Sorry Brady, I missed this, even back in May. I thought this was done. I have a billing manager PR going up tonight i'd like to get in next patch. Assuming it will back port with the styling changes done recently. Will see when I test against 5.0.1. I've added ability to create/edit MBO from the billing manager when setting up claims.

**Pull request merged**
