### PR TITLE
CCM and CCDA local service updates

### PR DESCRIPTION
**Pull request by sjpadgett**
Removed background service ssmanager and add on-demand ccda service start.
Added/fixed cda templates in document generator.
Security fixes in dependency libraries to support document generator.
Easier install

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller Still another commit for CCM CCD encounters import and service support coming.

**Comment by bradymiller** [comment]
If you think code is ready, then bring them in :)
(and I'll bring it over to the 5.0.1 release)

**Comment by bradymiller** [comment]
Also, feel free to place the blue button repo you use in ccdaservice/package.json on openemr's project where you can maintain it.

**Comment by sjpadgett** [comment]
I'll wait on BB and make one more attempt to get library authors to fix but I doubt it. Plus looking to do an auto install so in flux. I'm just out of time...

**Comment by sjpadgett** [comment]
FYI, going to try to do DICOM import auto mime test for easier user support today.

**Comment by bradymiller** [comment]
Wouldn't hold this for BB stuff (ie. feel free to go with what you got using your repo), and can always update it later in a patch, if needed.

**Comment by sjpadgett** [comment]
Okay this is ready to go but will hold off a bit while I troubleshoot why after 200 imports, import and gui slows to a craw, especially in docker. It slows on gets and database io even openemr background dated-reminders task, tho not as badly. It's document fetch in ccm where it shows most.

**Comment by sjpadgett** [comment]
Seems the query used to retrieve documents in ccm import uses 2 joins and 6 left joins across four tables.  Probably don't need to say more. A better query needs to be written using indexing or sub queries. Bringing this in and may consider a fix later. Not a docker issue is what is most important for now.

**Pull request merged**
