### PR TITLE
Patient image fixups

### PR DESCRIPTION
**Pull request by MatthewVita**
@robertdown noticed the following issues with the new patient image picture feature:

1. `alt` text was showing while the image was being loaded in.
2. `/openemr` is not safe to hard code for public images.
3. His custom picture is not loading :(.

I have fixed the first 2 issues and incorporated his bootstrap css change recommendations in. However, the custom picture not loading needs to be tested out. Perhaps the category was not `Patient Photograph` and was the `Patient ID card` which shouldn't be shown as the patient picture.

### CODE REVIEW

**Comment by MatthewVita** [comment]
Okay, @robertdown has confirmed he uploaded the picture to the right category.

First test: can you manually navigate to `/controller.php?document&retrieve&patient_id=YOUR_PID&document_id=-1&as_file=false&original_file=true&disable_exit=false&show_original=true&context=patient_picture` (obviously swap out YOUR_PID) to see if the image loads?

**Comment by bradymiller** [comment]
Hi,

This tested well just fine for me(and looking nicer with new styling).

Items 1 and especially 2 were good pickups by @robertdown !

Something to consider in future is to throw out a modal with a larger picture if the user clicks on the pic.

-brady

**Comment by MatthewVita** [comment]
> Something to consider in future is to throw out a modal with a larger picture if the user clicks on the pic.

Yeah. I have a list of improvements like this. I would like to have Jeffrey give these a spin because now that the baseline work is in place, he should be able to understand how the code works so it's less stressful.

Thanks for reviewing. I'm going to wait on @robertdown to test out item 3 before we merge. I'm super surprised that his picture is not loading considering this code is definitely on the simpler side. I honestly have no clue what could be going wrong.....

**Comment by MatthewVita** [comment]
@robertdown no pressure, I just wanted to know if you had a chance to give this another test

**Comment by bradymiller** [comment]
I vote to bring this in since you are fixing a potential path bug with this. And can fix Robert's bug later after it's characterized.

**Comment by bradymiller** [comment]
meant to say, lets just bring this in now :)

**Comment by MatthewVita** [comment]
Okay, I'm fine with that, but I'll leave it to @robertdown to make the final say.

**Comment by bradymiller** [comment]
just brought this in as a squash. we should avoid bringing in any merges that span beyond the recent psr2 megacommit.
thanks for this nice feature!!

**Pull request merged**
