### PR TITLE
Donating Entities to the codebase

### PR DESCRIPTION
**Pull request by juggernautsei**
I have been taking some courses at the SymfonyCasts and in the process of building some things. I had to build these entities. I have some repositories but I think they are more specific to my projects than to the project as a whole. I thought it would be good to get these in to hopefully inspire others to take steps toward the modernization journey.

### CODE REVIEW

**Comment by sjpadgett** [comment]
Hi Sherwin @juggernautsei ,
You've been a busy man. I think @robertdown and/or @MatthewVita will need to comment on this as I haven't an opinion either way. A first, I know and I get the irony.:)

**Comment by MatthewVita** [comment]
Hi @juggernautsei - I'm so happy you got the Ar entity stuff worked out.

The code looks fine to me, but, in my opinion it would be nice to see you write up a separate PHP script that went and performed various **core** operations on the entities just to give confidence in merging. Doing it on your local computer would be fine - nothing fancy that the reviewers would have to run.

Certainly don't want to make you do more work, but this may be a good idea since it's just the entities. Would be interested in others' opinions as well.

**Comment by juggernautsei** [comment]
I have done a bunch of work with these entities and would be happy to post the work that was done. They work even though the project is not complete. You may be able to get a sense of where it is headed.  I will add that later tonight.

**Comment by juggernautsei** [comment]
Here is the rest of the files that go with the Entities. I will send you my dev server to log in and see how this report performs right now. I hope I uploaded all the parts.

**Comment by juggernautsei** [comment]
I am having a problem bring this report to working order. The report is supposed to be like the patient ledger but for insurance companies. It should show the check that was posted and all the distributions for that check. This is as far as I have gotten.

**Comment by MatthewVita** [comment]
(Just emailed Sherwin - sharing with the group here that I'm moving across the country... talk to y'all next year!)

**Comment by juggernautsei** [comment]
@robertdown I am following up on this code commit. I can see now that although my intentions are in the right place. There is no place in the codebase for code that does nothing or has a future purpose. Should I close this commit until a future time when these entities can actually be used in the system?

**Comment by bradymiller** [comment]
Agree with closing this.
And then can focus on getting Weno code in (very excited to get first piece of twig code into the codebase! )

**Pull request closed without merging**
