### PR TITLE
Update X12Partner.class.php to pad spaces for 2 ISA fields

### LINKED ISSUE #5794: X12 partner fields not fixed width and padded for spaces
### Describe the bug

write concise description of what the bug is.
https://community.open-emr.org/t/x12-isa-segment-availity-claims/

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #5794

### CODE REVIEW

**Comment by stephenwaite** [comment]
sorry for not seeing that originally in your post Sandra, thank you for debugging and helping others down the road

**Comment by stephenwaite** [comment]
testing well and bringing in

**Comment by bradymiller** [comment]
2DV-2

**Comment by gutiersa** [comment]
Thanks so much for fixing this!!

**Pull request merged**
