### PR TITLE
Adding a review option to the about us page.

### PR DESCRIPTION
**Pull request by bradymiller**
This is by @juggernautsei from the following PR:
https://github.com/openemr/openemr/pull/1987

Up for grabs demo for this PR here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Mu_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @juggernautsei ,
This looks good and bringing it into the codebase. Just keep us updated how the reviews are doing.
Thanks for the neat feature!
-brady

**Comment by juggernautsei** [comment]
@bradymiller 
Thanks for bringing this in. I will update the board on any changes to the reviews. The goal is to introduce OpenEMR to a whole new class of people.

**Comment by sjpadgett** [comment]
@juggernautsei  Hmm, something wrong with the "class" of people we have now? :)

**Comment by juggernautsei** [comment]
@sjpadgett broadening our horizons. =)8

**Pull request merged**
