### PR TITLE
Layout editor fixes to preserve sensitive column names.

### LINKED ISSUE #4406: LBF leaves patient_data columns unprotected
### Describe the bug

write concise description of what the bug is.
https://community.open-emr.org/t/dangerous-bug-in-lbf-forms/10880

### To Reproduce
play with LBF on a  demo and modify a column in demographics 

### Expected behavior
shouldn't be allowed to edit col names in core tables (summarizing Jerry here :) )

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by sunsetsystems**
Fixes #4406

Layout editor was too permissive as to which columns can be deleted or renamed. Also fixes a bug where checking for columns with existing data was not working.

Would like to get some more eyes on this, as I am guessing in some cases which column names are hard-coded elsewhere. Do you see any that are missing?

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @sunsetsystems , Code looks good to me. If testing well for you, then bring it on in. Thanks for making the layout editor a safer place :)

**Comment by sunsetsystems** [comment]
OK I'll bring it in and adjust later if there is any feedback re column names.

**Comment by stephenwaite** [comment]
southpark_cheering

**Comment by stephenwaite** [comment]
just cherry-picked it and have it in rel-600 locally which i can push if it's ok by you @sunsetsystems , thank you!

**Comment by sunsetsystems** [comment]
> just cherry-picked it and have it in rel-600 locally which i can push if it's ok by you @sunsetsystems , thank you!

@stephenwaite  Yes of course. Thanks!

**Comment by kchapple** [comment]
Hi @sunsetsystems @stephenwaite I notice that validation rules don't appear to save for the core layouts (they do for LBF forms). I'm particularly interested in creating a DOB validation, so dates like 01/01/199 cannot be entered for a DOB. Just curious if you noticed this as well, and if a fix was in this recent batch of changes to layouts?

**Comment by kchapple** [comment]
Looks like it works as expected in the Dev demo, so I'll try updating and see if it's fixed.

**Comment by sunsetsystems** [comment]
> Looks like it works as expected in the Dev demo, so I'll try updating and see if it's fixed.

@kchapple Yep there were many layout-related fixes and improvements over the past 3 months or so.

**Pull request merged**
