### PR TITLE
proposing increasing minimum php version to 5.6.0

### PR DESCRIPTION
**Pull request by bradymiller**
see here for reason why:
https://github.com/robertogagliotta/openemr/commit/6989b55aea7674524d39de8a133b812a41b986cb#commitcomment-22393359

### CODE REVIEW

**Comment by robertdown** [comment]
A thousand times yes

**Comment by sunsetsystems** [comment]
Seems right to me.

**Comment by MatthewVita** [comment]
Very good work @bradymiller and @robertogagliotta !

I've updated the CI build to reflect our new minimum version: https://github.com/openemr/openemr/commit/e94778c02b57096e4ee7c3805bd02e5a11e04b1e

Is it okay if I update the documentation as well: http://open-emr.org/wiki/index.php/Development_Policies ?

Thanks,
Matthew

**Comment by bradymiller** [comment]
@MatthewVita ,
Please always feel free to update/improve the wiki :)

**Pull request merged**
