### PR TITLE
Update of P.R #1612 by Daniel Pflieger to 5.0.2

### PR DESCRIPTION
**Pull request by sjpadgett**
- Statement reflects the service facility and billing facility specified in encounter. The default logo if a logo is selected is 'practice_logo.gif' but the end user has the ability to change this. The logo has been placed left. Formatting issues if the service facility has a long name should auto size up to 40-50% of header width.
 - statement header should now auto size w/w/o logo.
 - moved logo to left where most logo appear on letterheads.
 - added insurance names to adjustment notes.
 - changed logo file logic.

### CODE REVIEW

**Comment by sjpadgett** [comment]
see https://github.com/openemr/openemr/pull/1612

**Comment by bradymiller** [comment]
hi @sjpadgett ,
Code looks good to me (I didn't test it though). The only thing that initially seemed odd was the removal of the $direction parameter, however, I could not find anywhere that it was actually used, so in the end removing that does make sense.
-brady

**Comment by sjpadgett** [comment]
I'm satisfied, bringing in. Over to you @stephenwaite

**Comment by stephenwaite** [comment]
thanks @sjpadgett , go to fees->posting choose invoice search and then due pt looking for bills and it logs you out 

very secure ;)

however choosing open lets you find a statement for testing and it looks great with the service facility and the billing facility in the right spots, is getting the return remit to the top difficult? thanks

**Comment by sjpadgett** [comment]
@stephenwaite Can't duplicate logout however searching All has issues. I have patients with pt due so may be different with no patients to return on search. Is that your case or do you have patients with balance due?
re:"getting the return remit to the top": not sure what you mean. What top? are you referring to cutoff remit to?

**Comment by stephenwaite** [comment]
could be docker overloading my old laptop 😬 
have 1 pt with balance due
making the returnable remit at bottom the header

**Comment by stephenwaite** [comment]
i can scan and upload a custom statement of mine that is streamlined, it basically has pt and practice info at top and only detail below

**Comment by stephenwaite** [comment]
ok, thanks, it might not be until tmrw

**Comment by bradymiller** [comment]
hi @sjpadgett and @growlingflea ,
Thanks for these improvements. If needed to get @growlingflea as author of commit, I can always do a revert the commit and then bring in as author. Or can leave as is since you did give @growlingflea credit on the commit comments. Happy to do whatever @growlingflea wishes.
Thanks,
-brady

**Comment by bradymiller** [comment]
hi @sjpadgett and @growlingflea ,
Thanks for these improvements. If needed to get @growlingflea as author of commit, I can always do a revert the commit and then bring in as author. Or can leave as is since you did give @growlingflea credit on the commit comments. Happy to do whatever @growlingflea wishes.
Thanks,
-brady

**Comment by sjpadgett** [comment]
Okay i'm fine however it goes. This script really needs to be rewritten into templates

**Comment by bradymiller** [comment]
hi Jerry,
Github is still recovering from recent issues, so guessing that's why where
is still lags in the PR's: https://status.github.com/messages
-brady

**Pull request merged**
