### PR TITLE
fix declaration fatal errors with empty array assignment

### PR DESCRIPTION
**Pull request by stephenwaite**
https://github.com/openemr/openemr/pull/4772#issuecomment-983089582

### CODE REVIEW

**Comment by stephenwaite** [comment]
will start to add fixes to the other declarations

**Comment by bradymiller** [comment]
2DV-2

**Comment by stephenwaite** [comment]
there's gotta be an award for best PR title of the year and am submitting this as a finalist :)

**Comment by bradymiller** [comment]
It is officially in the running :)

image

**Pull request merged**
