### PR TITLE
some fhir work

### LINKED ISSUE #3232: DOB vs dob naming in lookups.
### Describe the bug
Lets follow DOB naming convention from table name. Some services not getting/saving DOB. So generally, use DOB in all usage.

### PR DESCRIPTION
**Pull request by sjpadgett**
- refactor dob to DOB
- make Publish test jig BS4
- start questionnaire response for PRO use

Fixes #3232

### CODE REVIEW

**Comment by sjpadgett** [comment]
I wanted to get dob refactor in... forgot!
Also, Publish UI to BS4 although I have plans to pull this from core and make into a module. 
As is, it is a security problem where until I get to be functional to talking to other servers for providing transfer of care etc, it's useless!!

The Questionnaire will require some stretching our current capabilities and will need to interface in several key areas of core. CDR PRO and so forth. It's going to be interesting, stay tuned....

**Comment by sjpadgett** [comment]
some of this styling stuff is plain nitpicking. who cares if one or two lines after use statements!!!
is some other developer looking at code going to go "Oh my goodness! two lines after a use! Well heck, no way i'll understand this code now..." :) Just seems silly.

**Comment by bradymiller** [comment]
coming to theaters soon:
Nightmare on Travis Street

tenor (5)

**Comment by sjpadgett** [comment]
Of this we are assured:)

**Pull request merged**
