### PR TITLE
mfa u2f oauth fixes and php8 fixes

### PR DESCRIPTION
**Pull request by bradymiller**
Overall is testing well.
(reminder for self to check to ensure patient login still works)

### CODE REVIEW

**Comment by sjpadgett** [comment]
Merry xmas @bradymiller 
I was going to do a PR later today. It will touch several server files so i'm thinking it may be easier for me to resolve conflicts from this. Any idea how long this will be?

**Comment by bradymiller** [comment]
about 5 more minutes (just one more test) and then bringing in :) 
(then gonna do the scope permission stuff in another pr :) )

**Comment by sjpadgett** [comment]
I've finished most of the scopes setup throughout by app role. Including the scope repository were we'll maintain all our default scopes with permissions.
Here's example of smart well known:
```
{
  "authorization_endpoint": "https://opensourcedemr.us/oauth2/default/authorize",
  "token_endpoint": "https://opensourcedemr.us/oauth2/default/token",
  "registration_endpoint": "https://opensourcedemr.us/oauth2/default/registration",
  "scopes_supported": [
    [
      "openid",
      "fhirUser",
      "online_access",
      "offline_access",
      "launch",
      "launch/patient",
      "api:oemr",
      "api:fhir",
      "api:port",
      "api:pofh",
      "profile",
      "name",
      "given_name",
      "family_name",
      "nickname",
      "phone",
      "phone_verified",
      "address",
      "email",
      "email_verified",
      "patient/AllergyIntolerance.read",
      "patient/CareTeam.read",
      "patient/Condition.read",
      "patient/Encounter.read",
      "patient/Immunization.read",
      "patient/Location.read",
      "patient/MedicationRequest.read",
      "patient/Observation.read",
      "patient/Organization.read",
      "patient/Organization.write",
      "patient/Patient.read",
      "patient/Patient.write",
      "patient/Procedure.read",
      "system/AllergyIntolerance.read",
      "system/CareTeam.read",
      "system/Condition.read",
      "system/Encounter.read",
      "system/Immunization.read",
      "system/Location.read",
      "system/MedicationRequest.read",
      "system/Observation.read",
      "system/Organization.read",
      "system/Organization.write",
      "system/Patient.read",
      "system/Patient.write",
      "system/Practitioner.read",
      "system/Practitioner.write",
      "system/Procedure.read",
      "user/AllergyIntolerance.read",
      "user/CareTeam.read",
      "user/Condition.read",
      "user/Encounter.read",
      "user/Immunization.read",
      "user/Location.read",
      "user/MedicationRequest.read",
      "user/Observation.read",
      "user/Organization.read",
      "user/Organization.write",
      "user/Patient.read",
      "user/Patient.write",
      "user/Practitioner.read",
      "user/Practitioner.write",
      "user/Procedure.read"
    ]
  ],
  "response_types_supported": [
    "code",
    "token",
    "id_token",
    "code token",
    "code id_token",
    "token id_token",
    "code token id_token"
  ],
  "introspection_endpoint": "https://opensourcedemr.us/oauth2/default/introspect",
  "capabilities": [
    "launch-ehr",
    "context-banner",
    "context-ehr-patient",
    "context-style"
  ]
```
Based on currently supported fhir resources.

**Comment by bradymiller** [comment]
bringing in (u2f now functional); btw, all this mfa stuff is really cool
merry xmas @sjpadgett and thanks for the scope listing!

**Comment by sjpadgett** [comment]
Agreed on mfa! See ya on my PR

**Pull request merged**
