### PR TITLE
Patient Portal Layout, Nav and mobile fixes

### PR DESCRIPTION
**Pull request by benmarte**
No particular issue for this, I just fixed it because I know it was broken.

#### Short description of what this resolves:
Fixes navigation not being displayed when on a mobile device or smaller resolution.

#### Changes proposed in this pull request:
- added portal-content class to patientportal-style.scss to add a margin to the portal content area.
- removed duplicate nav entries from sidebar that were part of the patient drop down
- pages that do not load into the current layout open in a new page now, ie: documents, messages etc.

Please review and let me know if any further changes are needed.

Is there any reason why we are not leveraging the API for most of the patient portal? It seems like it's a great candidate to refactor it a bit I would like to use Twig templates so we can specify content/block areas which might help make editing/creating pages much easier and the project as a whole easier to maintain since there would be less repetition of things.

Anyways I just wanted to get this out there and I will continue trying to get Twig working in another PR.

### CODE REVIEW

**Comment by sjpadgett** [comment]
@benmarte You need to wait 'til i'm done. I've reorg'ed portal (now a SPA) with major changes to documents. Fix responsiveness etc.
While I love the idea you are taking an interest and want to develop portal, let me bring my stuff in then see what i've missed that concern you.

This is why I create forum topics in developer so folks know what I'm doing or others can collaborate.
https://community.open-emr.org/t/patient-documents-for-portal-and-staff-rework/16303/4

**Comment by benmarte** [comment]
> @benmarte You need to wait 'til i'm done. I've reorg'ed portal (now a SPA) with major changes to documents. Fix responsiveness etc.
> While I love the idea you are taking an interest and want to develop portal, let me bring my stuff in then see what i've missed that concern you.
> 
> This is why I create forum topics in developer so folks know what I'm doing or others can collaborate.
> [community.open-emr.org/t/patient-documents-for-portal-and-staff-rework/16303/4](https://community.open-emr.org/t/patient-documents-for-portal-and-staff-rework/16303/4)

@sjpadgett sounds good I was just concerned since the portal was not working on mobile, I will keep my changes in my local branch until you are done, feel free to close this.

Thanks.

**Comment by sjpadgett** [comment]
Cool. Don't go away though.:) @tywrenn went through it a couple months ago and got it very close to mobile but, I think I messed it up with some post changes. I keep trying to hit a sweet spot between desktop and small devices but patient document feature is the hard one. Now i've pulled in everything under Home page it becomes a little more difficult however workflow is better for patient.
Now collapse works for Home page and documents was changed to use flexbox so columns will be easier to stack in documents. Still, screen real estate on mobile is premium when editing a document.

Maybe by tonight i'll have PR up you can pull down or I may bring in tonight and let you fix up as you see fit. My main goal is structural in nature with side glances at styling.:)

**Comment by tywrenn** [comment]
Rigging the patient portal up for mobile was definitely what I'd call painful as it's layout wasn't really that great to start out. Hopefully you can fix it.

**Pull request closed without merging**
