### PR TITLE
fix #5558 prevent previous name and address with session pid in new patient form

### LINKED ISSUE #5558: Bug in Display of "Previous Names" and "Additional Addresses"
When you are in a window where a patient is associated with the window,
i.e. a patient name is in the upper left of the window,
AND you select from the menu Patient -> New/Search:

All of the input fields SHOULD BE EMPTY.

However, if the selected patient has "Previous Names" and "Additional Addresses",
the input fields shown after selecting Patient -> New/Search will show the "Previous Names" and "Additional Addresses" for the patient associated with the window.

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #5558 

#### Short description of what this resolves:
removes global pid which was causing the previous contact address to load

#### Changes proposed in this pull request:
use clearPatient() which calls restoreSession() immediately, drawback is the removal of autoloading the finder tab from clearPatient()

### CODE REVIEW

**Comment by bradymiller** [comment]
I don't think this will cover when select from the menu Patient -> New/Search
(generally when submit a new patient form it does a good job of resetting patient; hopefully can fix this without needing to clear the patient when click to show the form)

**Comment by bradymiller** [comment]
for example, some sort of flag that when is a new form, the entries are blank (ie. the new patient form shouldn't ever try to collect or submit data until user clicks Save).

**Comment by bradymiller** [comment]
looks great! (i didn't test it)

2DV

**Comment by stephenwaite** [comment]
testing well, bringing in

**Pull request merged**
