### PR TITLE
Light style updates

### PR DESCRIPTION
**Pull request by robertdown**
Updating the style_light.css file and making minor changes to the patient_files/summary/demographics.php file to better support enhanced development. Removed table-based layout of header information and replaced with section, nav, and header tags. Does not change PHP code, only HTML tags. Some PHP was modified (i.e. moving HTML tags out of echo statements)

Changes to the CSS include:

- Default font now Source Sans Pro (using base64 encoding)
- Overhaul of the Patient Summary screen title
- Better table UI
- Top nav color change
- Left navigation enhancements
- Changes to the gulpfile for enhanced development

### CODE REVIEW

**Comment by olegsv** [comment]
Are the changes in demographics screen compatible with other themes?

**Comment by bradymiller** [comment]
Hi Robert,

As Oleg points out, I am pretty sure the demographics changes won't be compatible with the other themes; if this is the case, then would suggest making as little changes as possible to the html stuff(which will ensure backward compatibility with prior themes).

I also noted that the text is a bit small and light in many places (and in some places the text is invisible like in the history edit section).

-brady

**Comment by robertdown** [comment]
The old themes are slightly affected but I tried to keep those changes to a minimum. Let me see if I can find a way to make even fewer changes.

Text size and colors noted and will fix.

**Comment by robertdown** [comment]
Ok, brought back the demographics page to master, added some classes (and tidied up some white space and indentation. I also updated the font sizes and fixed the white labels on a white background.

I was also able to keep most of the changes I originally wanted, you can see the up for grabs demo tomorrow after it resets.

**Comment by robertdown** [comment]
@bradymiller I know you have plenty of PR's to deal with, have you had a chance to review the changes here?

**Comment by robertdown** [comment]
Also, I am going to begin writing some documentation on the "anatomy of a theme" and use my SASS based theme as a guide for future development.

The thought process goes a little something like this:
* Every `<body>` tag will get a class with the following syntax: `folder-subfolder-page_name` so for instance `patient_file-summary-demographics` is patient_file/summary/demographics.php
* In the SCSS files there is a `.patient_file-summary-demographics` tag with any and all definitions for that particular page. This allows each page to be styled uniquely and not bloat the main CSS namespace.
* SCSS files can be included in other SCSS files. Bootstrap is a common example (They break out each component into it's own .scss file)
* There is a style_light.scss which includes all the sub pages

This way we are ablet to easily locate specific changes but the compiled, finished CSS is still just one file.I'll put together some documentation, tidy up my git repo and post to the wiki

**Comment by robertdown** [comment]
Actually, scratch that idea.... that ties CSS classes to file locations, which is a bad idea. I'll come up with some other way of naming

**Comment by bradymiller** [comment]
Hi Robert,

This is near the top of my queue (I'm working on getting the releases out first(likely tomorrow) and finishing up an MU2 related code review). Plan to look at this in the next couple day.

In future, recommend separating the tidying up changes from the real code changes. This makes it easier to see what is being modified and what requires testing.

-brady

**Comment by robertdown** [comment]
Will make sure my tidying code and real changes are separate in the future

**Comment by bradymiller** [comment]
Hi Robert,

Tested it out a bit and looks promising(I also noted that the old themes still work, which is good).

Agree that using the path names in the class names is not the way to go.

Highly recommend making this a separate theme from your original one. Couple reasons for this:
1. since this will be much different and some users may want to stick with your original
2. since there seems to be a cache issue (I had to empty my browser cache for the new theme changes to show up)

Also will be helpful to rebase these all into 1 commit and redo the pull request (when they are all in 1 commit, then can have github ignore whitespacing changes when viewing the commit via ?w=0, so can focus on the meaningful code changes on the review). Then can also point a up for grabs demo at it to gets folks to test it out.

-brady

**Comment by bradymiller** [comment]
Something else is the Deceased alert. I noted that it has lost it's styling on the old themes and is not very obvious on your new theme (Note from a clinical standpoint, it should be very obvious that a patient is deceased when go into the electronic record).

**Comment by robertdown** [comment]
1. I think for the class names I want to go with a module/submodule idea. For example, "patient" is a module (in a very abstract sense) and inside of a patient you have demographics, history, etc. Any page related to demographics would have the body class "patient-demographics" -- it doesn't matter what the actual file is called, all that matters is that the page is dealing with patient demographics. When in doubt, the body tag could also just be "patient" (if a page is dealing with multiple submodules.

This creates a loose association between file names and class names, but only in the sense that generally speaking, file names accurately describe what the file is doing.

2. Will split these changes into a second theme

3. Does this accomplish what you're looking for? https://github.com/openemr/openemr/pull/120/files?w=1 I really don't like rebasing all of these down to 1 commit just for whitespace issues. It's not a workflow I see widely used and it always makes me nervous. Since we don't actually bring code into the SF repo from here, I have forked the source on SF and once you approve *this* PR I wlll do a merge commit (SF's equivalent of PR) on SF so you can merge this branch in easily.

4. Have refactored the deceased logo and it is now *very* apparent a patient is deceased. Updated code coming shortly

Also, I'll definitely separate simple code refactoring (fixing whitespace, etc) from actual code changes--too much of a pain for everyone involved.

**Comment by bradymiller** [comment]
Yep, w=1 works to deal with the whitespace. So, no need for a rebase.
Do note I generally rebase multiple commits into 1 before bringing them into the codebase unless there are multiple authors that wish to get credit for the code changes.

**Comment by bradymiller** [comment]
And I wouldn't worry about doubling your repo work on sourceforge. Sourceforge repo stuff is very clunky and buggy. Easier for the code integrators to just grab the branch/commit(s) from github commandline and bring them into sourceforge via commandline (literally can be done in several seconds):
http://www.open-emr.org/wiki/index.php/Git_for_dummies#Committing_to_the_official_git_repository_on_Sourceforge_.28merge_method.29_.28For_Integration_Developers.29

**Comment by bradymiller** [comment]
Also agree with the module/submodule idea for class names.

**Comment by bradymiller** [comment]
Hi Robert,
Just checking in if this is ready for another round of code review and testing?
-brady

**Comment by robertdown** [comment]
I worked on it quite a bit tonight. You had suggested I split the theme into two as there were significant changes. I spent a lot of time going back to various commits trying to figure out where to rollback to in order to effectively split. I got frustrated after a while and did something else. Hopefully I'll have something this week, including a fix to the button problem on the Admin --> Layouts screen.

**Comment by bradymiller** [comment]
It sounds like it's not as simple as removing the light css file?

**Comment by robertdown** [comment]
No, a bit more complicated. But I've got it all worked out now 😊

**Comment by robertdown** [comment]
Go ahead and take a look now, the Admin --> Layout display error should now be fixed and I have some left_nav subtle UI improvements for the Radiant theme. style_light and style_radiant should now be two different files

**Comment by bradymiller** [comment]
Hi,
There are still a lot of changes in the light style?
In radiant style, the calendar widgets look odd.
-brady

**Comment by bradymiller** [comment]
Hi,

Can you point me to what is needed for the Admin --> Layout display fix; I'll bring this focused fix in.

Also appears to be another styling bug starting to brew here:
https://sourceforge.net/p/openemr/discussion/202505/thread/04180149/#bcdb

thanks,
-brady

**Comment by robertdown** [comment]
If you pull this PR in the admin layouts bug should be fixed along with the older style_light you wanted. I had to roll back a lot of the changes, that's why the diff is so big. And I'm about to send your a separate PR for the inventory bug. For some reason when Rod made that page way back when, he decided to make that button background transparent by putting a `style` attribute on that element. I'd love to know why he did that, it makes no sense at all. But that was causing no background on the button, and my buttons have white text, the page background is also white... you can see where this is going. The PR just removes that style tag (which should absolutely have not been put there to begin with)

**Comment by bradymiller** [comment]
Hi Robert,

I was getting this ready to integrate into the codebase. First I did a rebase of all your commits here:
https://github.com/bradymiller/openemr/commit/6ea395209fc618929d929962ac454c653eafaf0b

I placed some comments on above code for issues and addressed them in this commit:
https://github.com/bradymiller/openemr/commit/23885e5ceff42efb3f5b0127cb9ca0fe1b8a4ef9
(note the deceased styling fix makes your radiant theme look bad though)

However, when I tested the style light it looks way different visually than the original style light. So, I stopped the integration.

-brady

**Comment by robertdown** [comment]
Ok let's give this another go... I did a checkout of `master`, copied `style_light.css` to the desktop, checked out `2016ui` copied the style_light.css **back** to my openemr repo. Made an addition to fix the layouts bug (which also included added a class to `body` of `edit_layout.php`. I really think we should be good now... hopefully.

**Comment by bradymiller** [comment]
Now we are going somewhere :)

I just need to test the following elements in the demographics page (and then will bring it in):
test onsite portal, offsite portal, rxnorm, delete, deceased, and newcrop elements

**Comment by bradymiller** [comment]
Hi Robert,

I brought this into the codebase here:
https://github.com/openemr/openemr/commit/a82491cfb3abcf7d99eb6595d3e355923165e359

Note I made several small fixes in a following commit which are explained in the commit comments:
https://github.com/openemr/openemr/commit/9e2329e31fd1bf7ae9653d9c692301c284f3e9e7

Will close this pull request now.

Here are several things I noted in the Radiant them that will require fixing:
1. The calendar widgets look very funny
2. Many of the scripts have no styling for the Save/Cancel buttons/links

-brady

**Pull request closed without merging**
