### PR TITLE
fix: openemr-cmd up modifies the ccdaservice/package-lock.json file. …

### LINKED ISSUE #6979: add ccdaservice/package-lock.json to .gitignore
### Describe the bug
Every time I start the development-easy dockers, the ccdaservice/package-lock.json file is updated, which causes the "git status" command to say that file has changed & lists it under "Changes not staged for commit:"

### To Reproduce
1. $ git checkout master
2. $ cd docker/development-easy
3. $ openemr-cmd up
4. $ cd ../..
5. $ git status gives the following output:

`
`
#
```shell
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   ccdaservice/package-lock.json

``` 
### Client configuration

-Standard Development-Easy environment.

### PR DESCRIPTION
**Pull request by DrBassman**
… tell git to ignore this file.

Fixes #6979

### CODE REVIEW

**Comment by DrBassman** [comment]
After experimenting with this, adding ccdaservice/package-lock.json to the .gitignore file doesn't seem to have the effect of 'git status' ignoring when the ccdaservice/package-lock.json file changes?  I can't figure out why?

**Comment by bradymiller** [comment]
hi @DrBassman , We can't ignore that file anyways (it needs to be in the main codebase). Recommend PR with the changes in your ccdaservice/package-lock.json file since it does occasionally get changed over time during the ccdaservice builds.

**Comment by DrBassman** [comment]
> hi @DrBassman , We can't ignore that file anyways (it needs to be in the main codebase). Recommend PR with the changes in your ccdaservice/package-lock.json file since it does occasionally get changed over time during the ccdaservice builds.

Thank you for your help.  I thought you meant a PR with updated .gitignore file...

**Comment by DrBassman** [comment]
New PR opened.  This DOES seem to fix the issue...

**Pull request closed without merging**
