### PR TITLE
Jerry 702 picks

### PR DESCRIPTION
**Pull request by sjpadgett**
Cherry picks to current

Fixes #

#### Short description of what this resolves:
See commit

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @sjpadgett , Are you able to do a commit revert on the CDR stuff? I was gonna bring in all the cdr commits separately to keep Hank's authorship credit. Just need to do:
`git revert 3a33b4e09447f0bd0921f6a62f7bd6c8495c1566`
(if unable to do, won't be the end of the world; I'll get a PR ready tonight if you are able to do this)

**Comment by sjpadgett** [comment]
let me see Brady. If not I'll close and create a new PR tomorrow.

**Comment by sjpadgett** [comment]
@bradymiller Let me know if this will work if not it's no biggie to redo this PR!

**Comment by bradymiller** [comment]
@sjpadgett , that will work just fine :) I'll bring in my PR (#7395) after you bring in yours.

**Pull request merged**
