### PR TITLE
converted SOAP form to bootstrap

### PR DESCRIPTION
**Pull request by bradymiller**
https://github.com/openemr/openemr/issues/635

### CODE REVIEW

**Comment by bradymiller** [comment]
Converted the soap form to use bootstrap.
this is ready for review :)

**Comment by bradymiller** [comment]
soap-bootstrap

**Comment by bradymiller** [comment]
Testing well and did a phone review with Robert (thank you Robert!). So, will bring this into the codebase.
-brady

**Comment by robertdown** [comment]
Thought we go old school for the review and whip out the phones!

**Comment by robertogagliotta** [comment]
I m having Cluster headache 🤓

**Pull request merged**
