### PR TITLE
Signature in portal pdf fix and Template import changes

### LINKED ISSUE #6017: HTMLPurifier removes signature image in portal pdf build
### Describe the bug
Causes all signature for portal form reports to be removed.

### PR DESCRIPTION
**Pull request by sjpadgett**
- added a HTMLPurifier config option for base64 data in img src
- reconfiged template editor to use `<br>` tag instead of auto `<p>` on enter. Works much better.

Fixes #6017 

#### Short description of what this resolves:
allow images in pdf

### CODE REVIEW

**Comment by omegasystemsgroup** [comment]
@sjpadgett, you deleted the branch? Please how can i get the code change?

**Comment by sjpadgett** [comment]
It's in master anyway just files for fix
[signature_pdf_fix.zip](https://github.com/openemr/openemr/files/10250199/signature_pdf_fix.zip)

**Comment by omegasystemsgroup** [comment]
Alright, thanks much

**Comment by omegasystemsgroup** [comment]
This is the error i get in my php error log:

`PHP Warning:  unlink(): No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/openemr-7/vendor/ezyang/htmlpurifier/library/HTMLPurifier/URIScheme/data.php on line 97`

**Pull request merged**
