### PR TITLE
Fix for moving Amazon target

### PR DESCRIPTION
**Pull request by jesdynf**
Amazon gates access to Elastic Beanstalk environments based on the age of the account -- the newest of the new accounts can't access older environments that lack new features or security enhancements. This updates the stack to use the new v2.4.3 environment, instead of the deprecated v2.4.2.

### CODE REVIEW

**Comment by MatthewVita** [comment]
@bradymiller please work your release magic :)

**Comment by bradymiller** [comment]
@MatthewVita , @jesdynf ,
Just brought this into main codebase and also on the rel-500 branch(this is where the guide links point to). Didn't increment rel-500 patch version though (don't see a reason to do that, but let me know if you have different thoughts).

**Comment by jesdynf** [comment]
That's correct, I think -- this will probably come up again, to be honest. Only way to avoid it would be to step away from Beanstalk and go to a more manual autoscaling group with golden masters, and that would tremendously complicate updates.

**Comment by MatthewVita** [comment]
I will protest if we get rid of Beanstalk :) :) :).

It's so easy to deploy against. I just hope Amazon gets their stuff together really

**Pull request merged**
