### PR TITLE
Remove legacy JS

### PR DESCRIPTION
**Pull request by Wakie87**
Modified code to use built in php rather than JS. Will need someone who has the offsite portal with ZH Healthcare to test.

### CODE REVIEW

**Comment by bradymiller** [comment]
This looks solid. Recommend asking on the forums for somebody currently using the offsite portal to try it (Arnab could do this, but don't want to useruse his testing time since he recently tested the email stuff for us; will ask him if nobody volunteers on the forums).

**Comment by arnabnaha** [comment]
I will test this out

**Comment by Wakie87** [comment]
Thanks Arnab 😄

**Comment by kevinelong** [comment]
Do we have a requirement not to send unencrypted password over the wire? I
think this is why this was done in JS.


Kevin Ernest Long
Clever Clever Consulting Partners
www.cleverclever.com

503.888.6879
kevin@cleverclever.com
@kevinelong

**Comment by bradymiller** [comment]
Hi Kevin,

I think general best practices are to rely on https to secure them. Note this script was already sending the password, random number, and salted password via wire. The changes just migrate the sha1 calculation to the php server.

As an aside, there was a time in OpenEMR's past when the main OpenEMR login hashed the password on javascript end and then send this over the wire. We all thought that was more secure. But then some security folks became in our project and showed us the errors of our ways. It turns out this opened up OpenEMR to a pass the hash vulnerability (ie. could authenticate via the hash only). Turns out it was much more secure passing the password over https and then hash/salting it on the server end. Some think but what if a user is using http only; in this case even trying to salt/hash the password before secure over the wire is still not secure because when using only http, the server script can be intercepted and modified (strip out the salt/hash code) and could still get the clear password.

hope this makes some sense,
-brady

**Comment by arnabnaha** [comment]
Tested it 
1. Created a new instance of openemr with the file_cleanup branch
2. Enabled offsite portal in globals
3. Created a new profile with ZH offsite portal for testing
4. Entered the username, password and provider ID as needed in globals->Portal
5. Set up the VPN client for the new instance using the downloaded file
6. connection failure shows on clicking Portal Activity ->Check Connection
7. I guess there are some issues

**Comment by bradymiller** [comment]
Couple helpful links regarding above:
http://www.open-emr.org/wiki/index.php/Codebase_Security#Analysis_by_SANS_Institute
http://www.open-emr.org/wiki/index.php/Codebase_Security#Optimize_password_security

**Comment by bradymiller** [comment]
Hi Arnab,
Did you have an already existant offsite portal instance that works?
-brady

**Comment by arnabnaha** [comment]
Hi Brady,
Just checked the working offsite instance, its showing connection success and working fine. This is inmy production version.

**Comment by bradymiller** [comment]
Thank you Arnab! This can go into the codebase then.
(If Kevin replies and points something out regarding security, then we can revert it if needed)

Scott, now you get to do a rebase on 3 commits. It is basically the same thing, but now it will look like:
``````
pick    ....
squash    ....
squash    ....
``````
Note you can also use s instead of squash for shorthand
``````
pick    .....
s    .....
s    .....
``````
(the 's' will prove handy when you do a rebase on the many commits in the freeb cleanup commit)

**Comment by bradymiller** [comment]
also, the commit to rebase 3 commits is:
``````
git rebase -i HEAD~3

**Comment by arnabnaha** [comment]
The existing portal that I have is on the older codebase, it works...I dont know whether that will work or not based on the code change now as the new instance developed on current code doesnt work.

**Comment by bradymiller** [comment]
Oh, I misunderstood.

On your working instance, are you able to just swap the following file with your current myportal/index.php file:
https://github.com/Wakie87/openemr/blob/9a26ba6628547f25501b5bd81e92ff231f2a2c15/myportal/index.php
(save your original index.php file somewhere, so you can copy it back when done with the test)

And then in OpenEMR, click the 'Portal Activity' in the left menu. And does it work and log into your portal correctly?

thanks,
-brady

**Comment by arnabnaha** [comment]
Hi Brady,
Changed the file as u said...it works fine...The connection is success..

(I guess, there is an issue in the offsite portal for those who want a new connection to the portal. I think its a new bug which ZH needs to fix.)

**Comment by bradymiller** [comment]
great news and thanks!

Agree that there is possibly a bug in the offsite portal. I know Visolve relatively recently set up a working offsite portal for the MU2 testing, so hopefully it's just a temporary issue.

-brady

**Comment by Wakie87** [comment]
Added to codebase.

**Pull request closed without merging**
