### PR TITLE
Simple Eye Bug Fix

### PR DESCRIPTION
**Pull request by ophthal**
BUG:  ROS was not being saved.  Fixed.
Simple css change to fit PMSFH titles in one line on PMH panel.

Signed-off-by: ophthal <magauran@ophthal.org>

### CODE REVIEW

**Comment by robertdown** [comment]
Hm, I just noticed this PR was against rel-502, any specific reason @ophthal? Could this be pulled into `master` instead?

**Comment by robertdown** [comment]
I only noticed that after merging, so let me know I may have to revert this PR

**Comment by bradymiller** [comment]
I'll fix this up real quick (bring it into master along with a version cache break increment) and revert this and add it to the patch commit list (since we sometimes need to build the docker from rel-502 branch can't bring in patch commits until we actually release a patch)

**Comment by ophthal** [comment]
No problem with waiting for more “volume”. Plus this bug has been present for some time...

**Pull request merged**
