### PR TITLE
Fix: Curly brace style in RestController methods

### PR DESCRIPTION
**Pull request by harshbawari**

### CODE REVIEW

**Comment by harshbawari** [comment]
How do I link this PR to this issue: https://github.com/openemr/openemr/issues/3220

**Comment by bradymiller** [comment]
hi @harshbawari ,
In your main comment, add following to top:
Fixes #3220

**Comment by prondubuisi** [comment]
> How do I link this PR to this issue: #3220

By adding
fixes #issue_number to the commit message like bellow

Fix: Curly brace style in RestController methods
fixes  #3200

**Comment by prondubuisi** [comment]
Looks like I will review this @bradymiller

**Comment by bradymiller** [comment]
hi @prondubuisi , Sounds good. Just let me know if you think its ready for codebase and then will bring it in.

**Comment by bradymiller** [comment]
thanks for the review @prondubuisi !
hi @harshbawari , bringing this into codebase. Thanks for the fix! -brady

**Comment by harshbawari** [comment]
Thanks for the merge

**Pull request merged**
