### PR TITLE
add patient with debt filter and patient pid to the table.

### PR DESCRIPTION
**Pull request by matrix-drorgo**
Hi,
like in billing report there is no way to view only patient with debt .
so I have added this filter.
also it will be nice to have the pid in the table . I have added this also .

thanks
Dror G.

image

image

### CODE REVIEW

**Comment by sunsetsystems** [comment]
How is this different from choosing "Credits" in the dropdown (instead of "Open")?

**Comment by matrix-drorgo** [comment]
Hi, I have no "Credits" in the drop down :  

image


Thanks,
Dror G.

**Comment by sunsetsystems** [comment]
Never mind, I thought this was the Collections Report. :)

**Comment by bradymiller** [comment]
This looks very reasonable and with very minimal code changes; no testing needed. Will bring this in.

**Pull request merged**
