### PR TITLE
New erx 3 

### PR DESCRIPTION
**Pull request by juggernautsei**
Not for sure if I am supposed to create a new pull request after you forked the take 3 from your repository. But that would make sense since I can't update your repository.  So, here are all the requested updates and fixes for take-3.

### CODE REVIEW

**Comment by MatthewVita** [comment]
@juggernautsei looks like you may have checked in your `.idea` files. If it's okay with @bradymiller and @robertdown, I say you can sneak in a commit with this PR that `.gitignore`s `.idea/`

**Comment by robertdown** [comment]
My suggestions for the `.gitignore` file https://www.gitignore.io/api/vim%2Ceclipse%2Cnetbeans%2Cphpstorm%2Cintellij%2Csublimetext%2Cvisualstudiocode

You could also add `.idea/` to your global exludefile which would apply it to all your git repos

**Comment by bradymiller** [comment]
Considering OpenEMR's non-standard codebase, rec going with minimalist approach on the gitignore. Maybe just add the .idea dir ignore for now :)

**Comment by bradymiller** [comment]
@juggernautsei ,
Something went wrong here on the second commit. Do you want me to get this updated into most recent codebase along with the code I brought in previously? Then I can pass you that branch and you can work from that.
-brady

**Comment by juggernautsei** [comment]
Yes, let's do that.

**Comment by bradymiller** [comment]
sounds good and almost done; will post it this evening.

**Comment by bradymiller** [comment]
reminder for myself:
bring in the gitignore rule to ignore .idea with the commit

**Comment by bradymiller** [comment]
btw @juggernautsei ,

Congrats on winning the 1000 PR award, a "virtual"(ie. only pictures :) ) OpenEMR tshirt:
shirt_1
shirt_2
(if anybody is interested, these shirts were worn by several students, Rhonda and Destiny, for a presentation project at a Masters program for Health informatics to demo and sell OpenEMR with the following presentation: https://docs.google.com/presentation/d/10qIbMn6l2XR0XoXwFSnv2g4PuWjAykOF-xuIzgHT0Xo )

**Comment by bradymiller** [comment]
continued here:
https://github.com/openemr/openemr/pull/1007

**Comment by juggernautsei** [comment]
Now, I get it.

**Pull request closed without merging**
