### PR TITLE
Master to 702 patch 2 Cherry Picks

### PR DESCRIPTION
**Pull request by sjpadgett**
#### Short description of what this resolves:
For 7.0.2 patch 2 

#### Changes proposed in this pull request:
see commits

### CODE REVIEW

**Comment by sjpadgett** [comment]
this is as far as I can go til I do PR to move #7196 back because of version and database then I'll pick up from there to the top. I'll merge weno daily before then. Please leave cherry picks alone til I ensure no conflicts after pr.
I'll merge this unless you see a commit I missed previous to this pr head.

**Comment by stephenwaite** [comment]
ok thanks @sjpadgett , how about https://github.com/openemr/openemr/commit/74279455c5881de6b4f5b9e38e5176a9d989bc76, https://github.com/openemr/openemr/commit/4bafa598b3c2e2ffe8ca61f38dfc24e251aa6480 and https://github.com/openemr/openemr/commit/07259944e3a9d84a39b4d6afc0d3d3b77a901e79?

I'll do a special 1 for the chart.js needed for eye form since it's more involved like the ckeditor one and can include these if you'd rather.

**Comment by sjpadgett** [comment]
7207 will need to wait til i catch up weno. will merge daily then create pr for commit with DB stuff then new cherry pick pr for rest. need to figure out what you guys want to do with insurances. it may need to be stand alone pr.

**Comment by stephenwaite** [comment]
southpark_cheering

**Pull request merged**
