### PR TITLE
fix styling clash in navbar-toggle class; now can see this toggle cle…

### PR DESCRIPTION
**Pull request by bradymiller**
…arly in Administration->Practices gui

### CODE REVIEW

**Comment by bradymiller** [comment]
@zbig01  , Note I also added this fix to the style_flat_red.css theme.

**Comment by zbig01** [comment]
Sorry will add it to the new stylesheet.  I restyled Fees > Batch Payments  by adding a nav bar to batch payments and used some tricks to change the dropdown toggle background from transparent to a solid color. See the screenshots.


________________________________

**Comment by bradymiller** [comment]
@zbig01 and @robertdown ,
This change then caused the text to turn white in the modern buttons on the light and other themes (didn't seem to affect the flat red theme though :) ). So, I had to revert this change. So, back to the drawing board on dealing with the menu icon clash.

**Comment by bradymiller** [comment]
REVERTED

**Comment by zbig01** [comment]
My commit was based off the latest master . Are you getting this problem with the stylesheets that were in my PR?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bradymiller** [comment]
Hi @zbig01 ,
Luckily, you did your rebase right before I brought this broken code into the codebase :)
In your theme, this bug does not show as an issue since in Administration-Practices, the menu toggle is on top of a darker background, thus the white shows up fine.
-brady

**Comment by zbig01** [comment]
I see it on the current Demo site

**Pull request merged**
