### PR TITLE
fix php warnings for Rules

### PR DESCRIPTION
**Pull request by stephenwaite**

### CODE REVIEW

**Comment by stephenwaite** [comment]
yeah, not sure how to do this here
https://github.com/openemr/openemr/blob/master/interface/super/rules/base/library/BaseController.php#L22

**Comment by sjpadgett** [comment]
If I remember correctly, a var define in a class is considered as Public thus it follows a define of Public viewBean = new stdClass() would work. For me, a constructor is more appropriate. For the other two just ensure they are objects before defining. I could swear I touched on this in another PHP7.1 issue dealing with these classes, i'll look.

**Comment by sjpadgett** [comment]
@stephenwaite Sorry buddy took a look and can't define var like I suggested forgot what language im in:) also var is depreciated so....
This will work:
public $viewBean;
public $ruleManager;
public $codeManager;

public function __construct()
    {
        $this->viewBean = new stdClass();
    }

**Comment by bradymiller** [comment]
@sjpadgett , Why do the var need to be public here? Aren't they all running within their respective classes?
@stephenwaite , I think would do above __construct call for the BaseController class, which I repeated below:
``````
public function __construct()
{
    $this->viewBean = new stdClass();
}
``````
And then for the other classes(since they extend BaseController class), would do:
``````
public function __construct()
{
    parent::__construct();
}
``````

**Comment by bradymiller** [comment]
@sjpadgett , Disregard my question above; you are right that var is deprecated and public is good.

**Comment by sjpadgett** [comment]
@bradymiller I don't think the abstract/extended class'es call a construct so base class constructor is implicitly called. I'd be careful calling the parent(won't hurt I guess). @stephenwaite Have I properly gotten you completely turned around. Sorry:)

**Comment by stephenwaite** [comment]
yes, wondered about the use of `__construct` in abstract class... thank you, guess that's why the other classes that extend must have the `__construct` as well...

**Pull request closed without merging**
