### PR TITLE
This is base integration for this application into the program

### PR DESCRIPTION
**Pull request by juggernautsei**
Please review and comment...
I have requested a single sign-on for the program interface from the site owner.

### CODE REVIEW

**Comment by MatthewVita** [comment]
Hmm, I wonder if this should be documented in the wiki instead of in the core codebase seeing as this is a non-free 3rd party service. I'm not sure though.

@bradymiller, @robertdown, or @sunsetsystems would know better than I

**Comment by sjpadgett** [comment]
I'm not so sure this is a good idea. Couldn't this maybe be part of contrib form stuff. Incorporating into menu of system gives appearance that openemr endorses the service...

**Comment by juggernautsei** [comment]
@sjpadgett  
Jerry, I am not trying to be mean or flippid but my question to what you ask is does OEMR endorse NewCrops?

**Comment by juggernautsei** [comment]
I agree that there should be a setting to turn this on if someone wishes to use it and maybe a disclaimer that anyone wishing to use the software is using it at their own risk and OEMR takes no responsibility or liability for the content of the site. use at our own risk button.

**Comment by sjpadgett** [comment]
@juggernautsei Not mean or flip. You have every right to defend your position or question mine and I take no offence at all. Concerning NewCrops, there were other ways to go without getting in bed with them and I was never a fan.  Concerning this feature, I am only one voice and not a clinician so if this proves to be useful and community doesn't have a problem then, nor do I. Too me though, hanging external web apps off our menu tree insinuates acceptance along with some responsibility to support. Also, could this turn into a security hole? Does this set a precedent for other's that may wish to write offline fee base modules and expect to hook into menu tree.
In the end that's why we have Admin's and I'm perfectly content with however you and they decide. Just needed to put my concerns out there. Btw: it's great that you are adding so many great features and keep 'em coming...

**Comment by juggernautsei** [comment]
@sjpadgett Thanks for the banter. I really do appreciate the points of view. 
This site came to me to integrate their application. I can be done via API instead I took the path of least resistance. The thought of spending 6 months to a year building out API calls to their application was not appealing because there was going to be no compensation for doing the work. I spent a year on the Weno project with no pay for the work that was being done.  I learned a lot for doing that project with a possible promise of pay down the road. (A very long road) We all have to be selective about how we spend our time. I did think about the URL link being a security hole but they are using an SSL connection to the site so maybe it would not constitute a man in the middle attack.  
The drug-drug interaction is an API that did not take long to build. But the complexity of this site is too great. So, that is the reason for the frame redirect.  Thanks for listing.

**Comment by bradymiller** [comment]
hi @juggernautsei ,

Wouldn't a web browser link do the same thing (and also avoid security issue of including openemr js session data)?

If there was active integration using the api's(we have multiple examples of this such as Direct, Newcrop, MedEx soon, and several more), then could consider this (but would require a global to turn on).

-brady

**Comment by juggernautsei** [comment]
Here is a compromise. Can this be put into a Wiki? 
Leave the PR here for anyone that finds it and can integrate it this way or use it as a bookmark.
Thought.

**Comment by MatthewVita** [comment]
@juggernautsei I think that's a great idea.

I'm planning on doing something similar with a Twilio integration!

**Comment by bradymiller** [comment]
Agreed :)

**Comment by bradymiller** [comment]
And could place it here (this page is also listed in the wiki Downloads section):
http://www.open-emr.org/wiki/index.php/OpenEMR_Tools

**Pull request closed without merging**
