### PR TITLE
Fix gulp build deprecated warning

### LINKED ISSUE #6542: Gulp theme build deprecation warning
### Describe the bug
DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($input-padding-x, 2) or calc($input-padding-x / 2)
More info and automated migrator: https://sass-lang.com/d/slash-div

Turns out it is caused only in one place:  public\assets\@ttskch\select2-bootstrap4-theme\src\_multiple.scss which is our select2 theme for bootstrap.

How's this?

image

### Client configuration

- Browser: All
- OpenEMR version: All
- Operating system: All

### PR DESCRIPTION
**Pull request by sjpadgett**
- move and modify @ttskch/select2-bootstrap4-theme/src/select2-bootstrap4 to public/modified 
- remove package @ttskch/select2-bootstrap4-theme/src/select2-bootstrap4

Fixes #6542 

#### Short description of what this resolves:
May be a better way but this was pretty straight forward. Let me know if have a different idea.

### CODE REVIEW

**Comment by sjpadgett** [comment]
Full install and build < 3 minutes. We can consolidate and improve this I'm sure.

**Comment by stephenwaite** [comment]
thought you'd get schmancy with 
Screenshot from 2023-06-12 17-26-12
where #6543 was headed

**Comment by sjpadgett** [comment]
The only issue are two calc in select2 bs4 upstream so just needed to own the theme. There are no other upstream issues.
If I understand what you are asking....

**Comment by sjpadgett** [comment]
I’m not sure Stephen. It’s only that select two bootstrap for sass that’s at issue. We could bring in another theme however we’d have to modify gulp to compile.
This was just the quickest and easiest way without having to re-factor a bunch of code.
Although I’m not married to this

**Comment by bradymiller** [comment]
Since it looks like upstream will never fix this (last commit in that repo in 2021 and there is even a PR that has been submitted to fix this a long time ago :) https://github.com/ttskch/select2-bootstrap4-theme/pull/77 ). So seems like simplest thing is to take it over and do what @sjpadgett did (less moving pieces than fixing on fly since this will never be fixed anyways :)).

**Comment by stephenwaite** [comment]
freedom-roadtrip

**Comment by macomeza** [comment]
Great job!

**Pull request merged**
