### PR TITLE
robots.txt

### PR DESCRIPTION
**Pull request by morg0n**
robots.txt: adding global denial to search engines

fixes !2058

### CODE REVIEW

**Comment by sjpadgett** [comment]
This may or may not work depending if search engines will honor. I bet not. An apache directive is far more likely to be effective ie Deny from env=bots
Maybe do both by adding to our recm'ed apache config.

**Comment by danehrlich1** [comment]
Jerry that sounds like a really good idea for the env= thing

I actually have a pull request for changing our Apache config opened over
at OpenEMR-devops and will look at how to do this

**Comment by bradymiller** [comment]
hi @morg0n , Looks good and will bring into codebase. thanks for the contribution! -brady

**Comment by bradymiller** [comment]
and thanks @danehrlich1 for creating this item!

**Pull request merged**
