### PR TITLE
twig changes to work with expedited weno updates

### PR DESCRIPTION
**Pull request by bradymiller**

### CODE REVIEW

**Comment by bradymiller** [comment]
This is super expedited code working towards get weno updatesinto codebase asap and into patch before 1/1/20. Bringing this in after passing travis.

**Comment by juggernautsei** [comment]
Don't be in a hurry, to merge this code. There are more changes on the way as I just found out that the multiple medication code that I wrote is incorrect. To me, the documentation leaves a lot to be desired as a development document.

**Comment by juggernautsei** [comment]
Happy Holidays!

**Comment by juggernautsei** [comment]
I think I did the rebase

Administrator@WIN-H9ONBE9S18B MINGW64 ~/openemr (weno-newRx-standard)
$ git rebase -i master
[detached HEAD b7fd0ebb0] Weno new standard build update
 Date: Tue Dec 24 10:56:48 2019 -0500
 25 files changed, 5155 insertions(+), 125 deletions(-)
 create mode 100644 interface/weno/prescriptionOrder.php
 create mode 100644 interface/weno/transmitRx.php
 create mode 100644 library/js/prescription-autocomplete/prescription-autocomplete.js
 create mode 100644 src/Entities/PatientData.php
 create mode 100644 src/Entities/Pharmacies.php
 create mode 100644 src/Entities/Prescriptions.php
 create mode 100644 src/Repositories/AddressesRepository.php
 create mode 100644 src/Repositories/PatientDataRepository.php
 create mode 100644 src/Repositories/PharmaciesRepository.php
 create mode 100644 src/Repositories/PrescriptionsRepository.php
 create mode 100644 src/Rx/Weno/GenMessageId.php
 create mode 100644 src/Rx/Weno/NarcoticRxController.php
 create mode 100644 src/Rx/Weno/NewRx.php
 create mode 100644 src/Rx/Weno/NewRxData.php
 create mode 100644 src/Rx/Weno/PatientPharmacyController.php
 create mode 100644 src/Rx/Weno/PharmaciesController.php
 create mode 100644 src/Rx/Weno/SetPharmacyController.php
 rename src/Rx/Weno/{TransmitData.php => ValidateRxData.php} (72%)
 create mode 100644 templates/weno/admin.html.twig
 create mode 100644 templates/weno/css/prescription-autocomplete.css
 create mode 100644 templates/weno/layout.html.twig
 create mode 100644 templates/weno/narcotic.html.twig
 delete mode 100644 tests/Unit/NumberToTextTest.php
Successfully rebased and updated refs/heads/weno-newRx-standard.

**Comment by bradymiller** [comment]
hi @juggernautsei ,

Happy Holidays!

Regarding twig, your code is the first actual code using twig, so congratulations. The twig changes I made were to support translation/escaping in twig.

Agree with using twig/symfony going forward. To clarify, I only need to untwig the code that will be going into the the 5.0.2 patch (5.0.2 does not support twig), but should be straightforward (plan to do after your twig code gets into main codebase) since you are only using twig on 1 script.

On your rebase, are you sure that your master branch (which you are using in the rebase) is updated to most recent official master branch?

On your PR, there's still some work I want to do on it before it can get into codebase (which I then need to have you test after). Just let me know when you have it working like you want and then I'll do that.

**Comment by juggernautsei** [comment]
Here is a screenshot of my local server. I pulled down the changes.
git fetch upstream
git pull upstream master
git push origin master

So I have the new codebase. Then I squashed the commits by running git rebase -i master.
So, it should be all the commits in one.  Here is a screenshot of my local server. 
image

I heard from Kevin at Weno and he hinted this will not be a quick approval. Also, the code that I uploaded contains the test server location, not the production. Since Weno has to separate environments, I was thinking of adding a way to have the system in test mode before going to production. I have had people in the past ask me about that. That way, they can figure out how to use the system before going live. The new add is that there has to be vitals and diagnosis code added to the prescription. There is more information required if the patient is under 18.

**Comment by stephenwaite** [comment]
hi @juggernautsei , be glad to help testing 
for the rebase think @bradymiller means now that you've updated your master you can run the `git rebase -i master` from inside your `weno-newRx-standard` branch and follow the instructions

**Comment by juggernautsei** [comment]
Hi, @stephenwaite I did run that command and it squashed all my commit and rebased. 
I checked it out and it should be good. Thanks for being will test the functionality. It would be a big help. I think I missed a file or two but not sure until someone else runs the feature. Not worried about the error message coming back. Working with Kevin at Weno to clear that up.

**Comment by stephenwaite** [comment]
hi @juggernautsei , after I enable in globals how should I go about testing?

**Comment by stephenwaite** [comment]
btw here's newcrops fix for the new vitals and diagnosis requirement, https://github.com/openemr/openemr/commit/09555dba351bac9739c267efc60e0c0014fb11c8

**Comment by juggernautsei** [comment]
Line 164 of src/Rx/Weno/NewRx.php has the vitals include in the script message.
Go to weno admin, and install the drug data and pharmacies.
Create a prescription. Click on the transmit button, set the pharmacy. Click confirm, then transmit. 
https://youtu.be/2BM6_o1vobI

You should receive a return message
Array ( [WENOOnlinePostRxResult] =>

2019-12-26T08:41:27
* Post Rx Schema doesn't validate )
Array ( [WENOOnlinePostRxResult] =>

2019-12-26T08:41:28
* Post Rx Schema doesn't validate )

We are working on this.

**Comment by stephenwaite** [comment]
ok, thanks, kind of funny on the first prescription or maybe on any that you have to click save before clicking done or else you lose it

**Comment by stephenwaite** [comment]
the transmit button should probably spin around until the ajax is satisfied?

**Comment by juggernautsei** [comment]
You have the same issue about saving before done. That is confusing. Save most likely should not be at the top of the form. It is missed every time. 
The system use to have a spinner while the ajax was being satisfied. I will get that back in there while waiting on Weno to fix the schema issue. I have the script you sent logged on the gateway server success!
Thanks for testing this out.

**Comment by bradymiller** [comment]
hi @juggernautsei ,
Screenshots looks good on the rebase. To update your PR with your rebased branch, you will need to do a forced push:
```
git push --force origin weno-newRx-standard
```

**Comment by juggernautsei** [comment]
Command complete.
Doing some more tweaking while waiting on Weno support to figure out the schema issue.

**Pull request merged**
