### PR TITLE
MRD Card Events

### PR DESCRIPTION
**Pull request by robertdown**
Introduce Card events so modules can add cards to MRD programmatically

### CODE REVIEW

**Comment by robertdown** [comment]
I'd like to get this in and then move over each current card one-by-one to ensure a smooth transition. This is testing well from a practical perspective and assuming unit tests and lint tests pass will likely bring in this weekend.

**Comment by bradymiller** [comment]
2DV

**Comment by stephenwaite** [comment]
can't edit demographics or insurance
Screenshot from 2022-05-02 21-32-59

**Comment by stephenwaite** [comment]
looks like those sections of `demographics.php` have `btnText` not `btnLabel`

**Comment by bradymiller** [comment]
@robertdown @stephenwaite , is this breaking all of the sections in demographics.php ?

**Comment by stephenwaite** [comment]
just couldn't edit demos/insurance without the fix in #5271

**Pull request merged**
