### PR TITLE
DICOM viewer mime detection update

### PR DESCRIPTION
**Pull request by sjpadgett**
No longer requires .dcm extension in zips or single file to determine dicom. Detects mime from file header and will add extensions if appropriate.

### CODE REVIEW

**Comment by sjpadgett** [comment]
Tested with a 53 view CAT zipped without extensions(download from Radiology Lab). Single xrays with/without extensions and a few MRI's. Drag and drop up to 10 mixed dicoms e.t.c. PHP 7.1 Windows 10. Still need Linux test which i'll do for PHP 5.6.4 but will test in docker when ready.
@bradymiller This is from the rel-5.0.1 branch but if you need me to put up on 5.0.2 let me know.

**Comment by bradymiller** [comment]
Gonna bring this in (expediting) now and will also bring it over to 5.0.2.

**Comment by bradymiller** [comment]
btw, thanks Jerry!
(I'll also restart the 5.0.1 testing dockers on farm very soon; I'll let you know).

**Comment by bradymiller** [comment]
hi @sjpadgett ,
I just restarted the 5.0.1 demo dockers (there are 3 of them there to cover php 7.0, 7.1, and 7.2) which are at : 
https://www.open-emr.org/wiki/index.php/Development_5.0.1_Demo

**Comment by sjpadgett** [comment]
All three demos work fine except for upload size attributes are set to low. 413 Request Entity Too Large
nginx/1.13.7. Guess this is fixed in client_max_body_size nginx and php.ini. Okay on my Linux server and Windows. The Drag and Drop is nice and I think this is good to go with this PR documenting the upload size restraints.

**Comment by bradymiller** [comment]
Sounds great. Gonna build 5.0.1 packages soon then (with this included). thanks! -brady

**Pull request merged**
