### PR TITLE
Added a Healthcare Disclaimer to licensing

### PR DESCRIPTION
**Pull request by bradymiller**
This seems like a good idea, and I found this on the following OpenMRS website:
http://openmrs.org/license/

### CODE REVIEW

**Comment by Wakie87** [comment]
Yep, this is a good idea.

**Comment by Wakie87** [comment]
Do we actually need some legal advice on this?

**Comment by teryhill** [comment]
That is a really good Idea.

**Comment by aethelwulffe** [comment]
We will have that commit finished up on LibreHealth/LibreEHR shortly.  I am pretty sure this is in the works for review by the legal advisor.  Then you should just be able to commit a modified version from LibreEHR.  We are incorporating it into the windows/xampp installer package as well, and the final build script makefile for that package (and the deb etc...) will be posted in case you want to build from that.

**Comment by bradymiller** [comment]
@Wakie87 

The GPL provides already removes liability:
15. Disclaimer of Warranty.
THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

16. Limitation of Liability.
IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

My thoughts are this disclaimer just makes it more explicit for healthcare apps. I'm gonna bring this into the codebase(ie. to keep the momentum going) and will post on the forums to get more input.

**Pull request merged**
