### PR TITLE
Remove color themes to just two plus oe_themes

### LINKED ISSUE #6534: Limit core themes to five.
### Describe the problem
Reduce the available themes to five. This means removing all but the five from our build process.

Surely we want dark and light. Maybe a green and blue.

Speak up if have preference.

### PR DESCRIPTION
**Pull request by sjpadgett**
- leave dark,light,solar,manilla, green and blue

Fixes #6534

### CODE REVIEW

**Comment by sjpadgett** [comment]
Whoever did the gulp made this pretty easy.

**Comment by bradymiller** [comment]
so simple. neat. plus looks like you put in code previously in globals.php to default to light when theme does not exist which should manage upgrading (ie. if a user has a theme selected that no longer exists).

**Comment by sjpadgett** [comment]
Ready to finish portal theme. Pretty cool.
image

I'll bring this in if you want

**Comment by bradymiller** [comment]
go for it :)

**Review by bradymiller — APPROVED** [review]

**Pull request merged**
