### PR TITLE
Adding edi_sequence table for billing

### PR DESCRIPTION
**Pull request by juggernautsei**
Fixes # Does not fix anything yet
https://community.open-emr.org/t/report-eligibility-270-inquiry-batch/1782/38
#### Short description of what this resolves:
Trying to solve the mystery. This is the first step in the journey requested by Stephen Waite

#### Changes proposed in this pull request:
Trying to process Eligibility under version 6.0.0 (3). Not working for us.

### CODE REVIEW

**Comment by sjpadgett** [comment]
umm this requires more thought!

**Comment by juggernautsei** [comment]
I agree.
https://community.open-emr.org/t/report-eligibility-270-inquiry-batch/1782/45

**Comment by stephenwaite** [comment]
Updated to `easy issue` :)

**Comment by stephenwaite** [comment]
we'll be able to leverage this in the 837s too, thank you @juggernautsei

**Comment by juggernautsei** [comment]
Not needed or Jerry said...

**Pull request closed without merging**
