### PR TITLE
Keyboard shortcut support

### PR DESCRIPTION
**Pull request by robertdown**
Not the most extendable solution, but this is a start of supporting keyboard shortcuts. For now it support `alt+1` (Go to calendar), `alt+2` (Go to Patient Finder), and `alt+shift+w` (Clear the patient). Would like to also support `alt+r` as a refresh of the current tab, but was having some issues getting that working.

I think this is a good starting point. Some basic navigation. Eventually I'd love to have more robust support but for now, let's run with this.

### CODE REVIEW

**Comment by sjpadgett** [comment]
I like this and is something I thought was lacking when I first was introduced to openemr.

**Comment by bradymiller** [comment]
looks very cool! would document this on a quick new wiki page so it does not get lost (guessing folks will be adding to this over time) and will be a very nice new feature in next release

**Review by bradymiller — APPROVED** [review]

**Comment by robertdown** [comment]
Will definitely get a wiki page up

**Comment by stephenwaite** [comment]
excited_elephant

**Pull request merged**
