### PR TITLE
Suggestion : Adding ss to the patient_data API

### PR DESCRIPTION
**Pull request by im-Amitto**
We are using the SSN on the main table of patient data in openemr but it's not supplied in the rest API call.
Screenshot from 2020-04-04 16-58-33
SSN can be used to easily filter out a patient in a long list so adding it will be beneficial.
Also, API returns the phone_contact where in openemr we are displaying the home_contact so I think it may cause some misunderstanding.
App view generated using information from rest api
Screenshot_20200404-170329

Let me know your thoughts:
@bradymiller @sjpadgett @mdsupport @stephenwaite

### CODE REVIEW

**Comment by stephenwaite** [comment]
hi @im-Amitto , good point, `ssn` probably shouldn't be on the dashboard any more. In US we're trying to move away from it due to [identity theft](https://www.cms.gov/Medicare/New-Medicare-Card/Providers/Providers-and-office-managers). So while it's incredibly useful for identification it's on shaky footing due to privacy concerns. We probably don't want to add that to our API and keep it protected/hidden for now.

**Comment by im-Amitto** [comment]
@stephenwaite Thanks for the explanation.

**Comment by mdsupport** [comment]
@im-Amitto, SSN is an identification number issued by federal/central govt and central to identity theft.  From interface design perspective, clinicians will definitely use their gifted memory to remember DoB of 100s of patients before their SSNs.  As for patients, few patients remember their SSN but then EMR app is the last thing they will use it to find themselves!

Also, the columns in patient finder are configurable.  In light of recent delinking of CMS id from SSN in US, project should change the default view.

**Comment by bradymiller** [comment]
hi @im-Amitto , @mdsupport , @stephenwaite ,
There is a more systemic issue here than just the ssn. The current api for patient post(insert)/put(update)/get is bare bones at this point. It should actually mimicking saving/editing/showing patients like is done in OpenEMR. And in that case, it will then automatically support ssn or any other of the standard (and custom) data points. And note the api also uses acl, so anything the user can see within OpenEMR, will be able to see in API (so, if you wanted to make ssn a private/encrypted field, you could build this feature in OpenEMR itself and then the api will also do this (after the patient api is properly done)).

**Comment by bradymiller** [comment]
Regarding this specific PR, I have no problem with passing the ss, since again, the user's api access controls will mimick what they can already see if the login to OpenEMR. I think the following would be acceptable:
1. Bring in this PR for @im-Amitto ongoing work
2. Create an Issue to upgrade the patient api calls

**Comment by sjpadgett** [comment]
I'll just mention that the VA never ask for or records ssn electronically. Instead they will use ssn for verifying patient by phone or in person. I don't believe they even allow on labs, medications or reports that I recall.
I think this is why CMS went to new system. Anyway just noting for any interested besides, I didn't want to feel left out:)

**Comment by im-Amitto** [comment]
@bradymiller I think let's close this PR without merging and create an issue in the openemr a having or not having ssn is not causing any issue in my side and after reading a little about ssn I think we should keep it in an encrypted format.

**Comment by stephenwaite** [comment]
hi @im-Amitto , after following @bradymiller 's logic, why let go of this nice commit and instead do as suggested which will lead us to a better outcome, more complete api and ssn encrypted?

**Comment by im-Amitto** [comment]
Let's merge it then :)

**Comment by bradymiller** [comment]
Just brought this in. Thanks for the improvement @im-Amitto !
And thanks to others for the reviews!

**Pull request merged**
