### PR TITLE
deduplication changes

### PR DESCRIPTION
**Pull request by sjpadgett**
- display header using modulus 12
- enc dedupe changes

### CODE REVIEW

**Comment by sjpadgett** [comment]
@adunsulag 
I haven't been able to fix the dedupe for CMS130 on SLI. I stared at this for two hours last night and can't decide if this is on the test or me for patient Ferguson, Ryan. 
There is not an encounter with a relevant period  to copy the Procedure Activity Act template into.

Give me a call so I can explain and hopefully a fresh set of eyes will help!

**Comment by sjpadgett** [comment]
@adunsulag I'm not sure I'm happy with my solution however, I am with results:

image

image

**Comment by adunsulag** [comment]
@sjpadgett Hooray!  I'm just back in internet reception, thought I was going to be able to get to this earlier.  I'll be able to give you a call in about 15 minutes.  Do you still need to talk?

**Comment by sjpadgett** [comment]
@adunsulag We probably should go through my logic in case you have a thought on my approach.

**Comment by sjpadgett** [comment]
@adunsulag @stephenwaite Once test are done I'll merge. I set the actions merge or deduplication to auto detect which to use. This way it shouldn't matter which is selected from UI in case of misjudgment of which to use from import.

**Comment by sjpadgett** [comment]
@adunsulag @stephenwaite 
The two bundles for SLI and my local are the same best I can tell.
The default patients in the bundles are the ones that get randomized and duplications are created. This happens when product is set up and measures for testing are created i.e each measure has random patient deck created from the bundle default patient.
Therefore I don't see importing the bundle from SLI will get what you hope to achieve. You can try though if you want.

**Comment by adunsulag** [comment]
@sjpadgett maybe what I'll try and do is use the CVU+ and do the vendor patient import and see if that can get us our c1 stuff.

**Comment by bradymiller** [comment]
tenor99

**Pull request merged**
