### PR TITLE
a5 onc 2015, comment

### PR DESCRIPTION
**Pull request by cpcplus**
Comment support

### CODE REVIEW

**Comment by bradymiller** [comment]
continue from https://github.com/openemr/openemr/pull/2920

**Comment by sjpadgett** [comment]
bump

**Comment by cpcplus** [comment]
What happened. I have been working with Brady Miller. He does not follow that thread anymore?
    On Saturday, June 27, 2020, 11:51:19 AM PDT, Jerry Padgett <notifications@github.com> wrote:  
 
 


bump

**Comment by sjpadgett** [comment]
Hi @cpcplus I'm unsure status for this but I didn't want PR to auto close. I'll bump Brady so he can respond as to his take @bradymiller .

**Comment by bradymiller** [comment]
bump

**Comment by cpcplus** [comment]
Hi Brady,What more do you want me to do with this? I thought you reviewed it.ThxTT
    On Friday, September 25, 2020, 04:59:44 PM PDT, Brady Miller <notifications@github.com> wrote:  
 
 


bump

**Comment by bradymiller** [comment]
hi @cpcplus ,
I'll check this PR out in detail over the next couple days. We are pushing to get ONC 2015 cert completed by year end, so these things are now high priority :)

**Comment by bradymiller** [comment]
bump

**Comment by bradymiller** [comment]
this pr is continued here:
https://github.com/openemr/openemr/pull/4254

**Pull request closed without merging**
