### PR TITLE
api updates

### PR DESCRIPTION
**Pull request by bradymiller**
Still need to test this

### CODE REVIEW

**Comment by bradymiller** [comment]
@sjpadgett , Here's api token authentication updates to prevent "pass the hash" type issue. I would of preferred making the bearer token encrypted/signed (like you did in the portal), but couldn't solve multisite issue and was worried about possible characters that may need escaping. So instead went with this solution where doubled the size of the bearer token and used the first half to query for the token and the second half to authorize the token. Just let me know if this is completely loony :)
Plan to test it tomorrow.

**Comment by sjpadgett** [comment]
Process looks fine to me. Even a new table column doesn't bother me. lol I'm not sure why i'm so frugal about new table columns. Maybe patient_data is always on my mind... Be nice to split all layout columns into a linked foreign table and made relational.

Anyway, this mod will help setup an authorization and authentication pattern. Where authorization will be for a pre approval of client application by the practice and authentication for the transaction session.
I see authorization set up in what we'll call usage classes namely, application(say only pre approved by openemr clients), patient(of course), server to server(treat as a client however different handshake) and internal.  This allows openemr users to determine how much data they wish to expose. God forbid, I may even have to create some new tables:)

**Comment by bradymiller** [comment]
Just added one more column to store a salt also (went to a much more secure salt/hash mechanism for the authentication part of the token, which basically makes it impossible to get/derive the full token even if have access to both database and keys on drive :) ).
Now looking into if there is a way we can do encrypt/sign of the bearer token (like you did to the portal tokens), which should make brute force attacks on api more impossible; fingers crossed :)

**Comment by sjpadgett** [comment]
hmm, is there an encryption quota you're up against:) kidding, you go brother....

**Comment by bradymiller** [comment]
Got it working :)
```
curl --insecure -X POST -H 'Content-Type: application/json' 'https://localhost:9082/apis/api/auth' \
> -d '{
>     "grant_type":"password",
>     "username": "FKP-admin-23",
>     "password": "FKP-admin-23",
>     "scope":"default"
> }'

curl --insecure -X GET 'https://localhost:9082/apis/api/facility'   -H 'Authorization: Bearer eyJ0b2tlbiI6IjAwNkdZR0RuR1JPcjRycGR4dTlXZE5ZSzlpak0wd3dQcnUrWURNU3VGK09xdUhxTG9WMHRKb2VLWDJqV3BISitGY1hhNjlLeitQU2Z0OW9VQ2lyWjEzNStoRGJLQ3RadUtVdmhmU1wveDY5N3VzbmVPRlFlZ3ZUTE5XamJGVE5jMzNId0c4TWg4Z3NycVczTDJhSjhEcmoyYnRJSzJncXFvUU9Cbys4a1B3Y3I4NWtzU2o5UE45MzJIcGVFVkltNVlzUGciLCJzaXRlX2lkIjoiZGVmYXVsdCIsImFwaSI6Im9lbXIifQ=='
[{"id":"3","name":"Your Clinic Name Here","phone":"000-000-0000","fax":"000-000-0000","street":"","city":"","state":"","postal_code":"","country_code":"","federal_ein":"","website":null,"email":null,"service_location":"1","billing_location":"1","accepts_assignment":"0","pos_code":null,"x12_sender_id":"","attn":"","domain_identifier":"","facility_npi":"","facility_taxonomy":"","tax_id_type":"","color":"#99FFFF","primary_business_entity":"0","facility_code":"","extra_validation":"1","mail_street":"","mail_street2":"","mail_city":"","mail_state":"","mail_zip":"","oid":"","iban":""}]
```
Now just gotta do lots of testing :)

**Comment by bradymiller** [comment]
Testing going well so far. A bit more testing to do; then will remove all the debug stuff.

**Comment by bradymiller** [comment]
testing well and bringing in :)

**Comment by bradymiller** [comment]
hi @stephenwaite ,
doh, i completely broke the demos without demo data (no user is being created; the demo data bring this in, so why that isn't broken) and auto installer. Thanks for reporting this and I'll get a fix in.

**Comment by bradymiller** [comment]
fixed and also brought into rel-502 branch:
https://github.com/openemr/openemr/pull/2758
(also removed a redundant include of Installer class since the autoload.php now takes care of that)

**Comment by stephenwaite** [comment]
guess am off the hook on rel-502 :smirk: will take a look at what you fixed, thank you

**Pull request merged**
