### PR TITLE
add style lint check to travis

### PR DESCRIPTION
**Pull request by bradymiller**

### CODE REVIEW

**Comment by tywrenn** [comment]
Looks like it failed yet I believe this can be easily `--fix`'d

**Comment by bradymiller** [comment]
hi @tywrenn ,
I was failing it on purpose to ensure the travis check was functional. Just reverted that change I made, so it should now pass :)
As with the psr12 lint, plan to place a command in easy dev docker tools that will do following:
```
npx stylelint "**/*.css"
npx stylelint --fix "**/*.css"
npx stylelint "**/*.scss"
npx stylelint --fix "**/*.scss"
```

**Comment by bradymiller** [comment]
@sjpadgett , just thought you'd like to know we have another travis lint checker to add to the travis lineup :)

tenor (13)

**Comment by sjpadgett** [comment]
image

**Pull request merged**
