### PR TITLE
bug: No custom function call in "btnLink"

### LINKED ISSUE #6840: bug: Generate Demographic Widget/Cards from Modules - No custom function call in "btnLink"
I'm developing a module to openemr and one of the functionalities is a widget. 
This widget will have the edit button active with a custom function call. The problem is never called due to a possible bug on demographics.php.

In the block of code that generates the widgtes/cards from the modules, lines [1621](https://github.com/openemr/openemr/blob/d25d771cc211874d02ff9052c84807ffd7ea7f15/interface/patient_file/summary/demographics.php#L1621)-[1650](https://github.com/openemr/openemr/blob/d25d771cc211874d02ff9052c84807ffd7ea7f15/interface/patient_file/summary/demographics.php#L1650), in the line [1646 ](https://github.com/openemr/openemr/blob/d25d771cc211874d02ff9052c84807ffd7ea7f15/interface/patient_file/summary/demographics.php#L1646)there is the code 

`'btnLink' => "javascript:$('#patient_portal').collapse('toggle')"`

shouldn't this line receive a custom btnLink property? 
and btw the btnLabels the same?

### PR DESCRIPTION
**Pull request by dcvidigal**
Fixes  #6840

### CODE REVIEW

**Review by adunsulag — APPROVED** [review]
Looks good.  Thank you for the PR!

**Comment by dcvidigal** [comment]
no problema 👍

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
Thanks for the fix! Bringing in.

**Comment by stephenwaite** [comment]
nice

**Pull request merged**
