### PR TITLE
php8 support

### PR DESCRIPTION
**Pull request by bradymiller**
No really even close, but at least got the composer build working now :)

### CODE REVIEW

**Comment by tywrenn** [comment]
image

**Comment by bradymiller** [comment]
wooohoooo, got OpenEMR working on PHP 8.0:
image

We need to wait for doctrine orm 3.0 production to be released before can bring this PR in. Am now using doctrine 3.0-dev. Additionally, when we do this, then will need to remove support for php 7.2 (doctrine orm 3 will not support php 7.2), which isn't that big of a deal since php 7.2 end of life is 11/20.

Plan to keep this PR updated to most recent codebase in order to be able to test and work on all the php warnings etc.

**Comment by tywrenn** [comment]
@bradymiller Do we have a devops that runs php 8? Doesn't seem like we have one.

**Comment by bradymiller** [comment]
@tywrenn , Can run php8 from the insane development docker environment:
https://github.com/openemr/openemr/tree/master/contrib/util/docker#insane-development-docker-environment
(note it is called insane for a reason :) )

**Comment by bradymiller** [comment]
Spent some time on this today and appears to have gotten even more complicated (was unable to rebase and rebuild a new composer.lock since it appears the doctrine/dbal dev-missed-commits package is nowhere to be found). Just weird stuff all around. And not finding out much online regarding doctrine and PHP8. Gonna try to track down a doctrine guru.

**Comment by tywrenn** [comment]
I found out some dependencies require php 8 when I updated some of them -- this might be REALLY difficult for backwards compatibility.

**Comment by bradymiller** [comment]
@tywrenn , At this point the only showstopper that is stopping us from supporting PHP8 in master branch is doctrine. My concern is we'll need quite a bit of time to fix all the new php warnings (there are a lot of them) and now I can't even get the roundabout mechanism in this PR to work on the most recent codebase (for what appears to be because of things out of our control). I found the doctrine chat and asked about PHP8 support in their ORM channel. Hopefully get more information soon (maybe there is something simple I am missing).

**Comment by bradymiller** [comment]
Considering following drastic measure :)

**Comment by bradymiller** [comment]
Considering following drastic measure :) 
https://github.com/openemr/openemr/pull/3923

**Comment by bradymiller** [comment]
Closing this since addressed by the following PR: https://github.com/openemr/openemr/pull/3923

**Pull request closed without merging**
