### PR TITLE
Minor fixes in client side validation

### PR DESCRIPTION
**Pull request by matrix-amiel**
1. We fix the line 2331 at library/options.inc.php to print right class in the tab of edit LBF screens. (before the fix the function doesn't run). This fix enable to mark the tab when have error.   

2. fix in library/validation/validation_script.js.php - before validation the script clean of all the disappear inputs else the validation will check them also and may fail.

### CODE REVIEW

**Comment by bradymiller** [comment]
I just committed this to the codebase.
-brady

**Comment by bradymiller** [comment]
Hi,

Following critical bugs after bringing this into the codebase:
1. When try to save a new patient nothing happens and get following javascript error:
Error: Syntax error, unrecognized expression: #form_race[]
2. When try to edit a patient get weird message (ok to leave page ) and get following javascript error:
Error: Syntax error, unrecognized expression: #form_race[]

Will reopen this tracker item.

-brady

**Comment by bradymiller** [comment]
Since it's the weekend for your group, will revert this commit for now until there is a fix.
-brady

**Comment by matrix-amiel** [comment]
Hi Brady.
sorry about the bugs.
I fixed them and now it's work correctly.

thanks.
Amiel

**Comment by bradymiller** [comment]
Looks good. I just committed this to the codebase. thanks!
-brady

**Pull request closed without merging**
