### PR TITLE
multi site disable file/perm checks

### LINKED ISSUE #2943: multi site install permissions checking
instead of having to change permissions on already existing sites to proceed with multi-site setup tried to disable $checkpermissions in setup.php but it needs some :love_hotel:

### PR DESCRIPTION
**Pull request by stephenwaite**
fixes #2943

### CODE REVIEW

**Comment by stephenwaite** [comment]
closing #2944

**Comment by stephenwaite** [comment]
testing fine

**Comment by stephenwaite** [comment]
testing well

**Comment by bradymiller** [comment]
this looks good and would bring this into rel-600 also :)

**Comment by bradymiller** [comment]
btw, thanks for the fix!

2DV

**Pull request merged**
