### PR TITLE
Add portal flag and supervisor to users

### PR DESCRIPTION
**Pull request by sjpadgett**
Fixes #

#### Short description of what this resolves:

- need to select what users may appear for portal
- add a supervisor for user.
- add feesheet default supervisor to rendering supervisor.

### CODE REVIEW

**Comment by bradymiller** [comment]
The code here appears to be reverting all the stuff in the recent registration commits.

**Comment by sjpadgett** [comment]
I just going to close and do over. ya stuck in a PR and my merge to local didn't work.

**Comment by bradymiller** [comment]
I think I see what happened. Let me know if you want me to sort it out.

**Comment by sjpadgett** [comment]
easier to just do a new PR. I don't mind...

**Pull request closed without merging**
