### PR TITLE
Gad7

### LINKED ISSUE #5659: improved GAD7 form
### Describe the problem

small improvement needed in layout of the form, simpler legend on 'close without saving' button, improvements to coding style, question 8 default should be 'undefined' , better use of included files

### Describe the solution you'd like
four files amended - gad7.inc.php, new.php, report.php, view.php

### PR DESCRIPTION
**Pull request by ruthkonyn**
Fixes #5659

#### Short description of what this resolves:
small improvements in layout, better button legend, default answers to question 8, improved coding style

#### Changes proposed in this pull request:
various changes to 4 files - to resolve the issues

### CODE REVIEW

**Comment by stephenwaite** [comment]
looks good @ruthkonyn , just did a quick review

**Review by stephenwaite — APPROVED** [review]

**Comment by ruthkonyn** [comment]
many thanks stephen

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
agreed code looks good! thanks for the improvements!

**Comment by stephenwaite** [comment]
nice job @ruthkonyn , bringing in and will be in patch 2

**Pull request merged**
