### PR TITLE
Set secure_upload on as default

### LINKED ISSUE #2242: file upload whitelisting. have this setting on by default with good default configuration
This is an important setting we need to have on and properly configured by default:
https://www.open-emr.org/wiki/index.php/Administration_Globals#Secure_Upload_Files_with_White_List

### PR DESCRIPTION
**Pull request by a-mt**
Fixes #2242.

- Set `secure_upload` on as default
- Whitelist `image/*`, `text/*`, `audio/*`, `video/*` as default  
  [Full list of MIME types](https://cdn.rawgit.com/jshttp/mime-db/master/db.json)

Is that correct?

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @a-mt ,

You are definitely going down the right path on this. We should be more specific on the mime types and not use any of the wild card types. Would start with:
application/dicom+zip
application/dicom
application/pdf
application/zip
image/gif
image/png
image/jpeg
text/plain

-brady

**Comment by a-mt** [comment]
Note to self: do not update before pushing. Give me some time to fix my commit.

**Comment by a-mt** [comment]
There you go, I updated the SQL inserts with the list you gave me.

**Comment by bradymiller** [comment]
hi @a-mt ,
This looks perfect. Bringing into codebase now. Thanks for the code improvement! -brady

**Pull request merged**
