### PR TITLE
Billing Manager x12 partner fix.

### PR DESCRIPTION
**Pull request by sjpadgett**
- add onchange event to update x12 partner selected on payer change
- remove some script tags that made no sense.
- give margin to partner pull down.

### CODE REVIEW

**Comment by sjpadgett** [comment]
going to add some feesheet changes to this PR next commit.
fyi @stephenwaite and @juggernautsei

**Comment by juggernautsei** [comment]
@sjpadgett 
What are the plans for the fee sheet?

**Comment by sjpadgett** [comment]
@juggernautsei I already did the commit and merge. See my last commit where I removed the alert popup for number of codes found in search and replaced by scrolling the page to the search results automatically.

**Comment by juggernautsei** [comment]
Ok

**Comment by sjpadgett** [comment]
@juggernautsei Was there something about the feesheet that you thought needed to be addressed? I've always thought it was well done but there are always new use cases cropping up. Plus I think it's getting a little busy, code wise.

**Comment by juggernautsei** [comment]
Nothing I can think of at the moment. I went back and looked and most everything is user interaction. Nothing that structurally or workflow that needs to be addressed. Thanks for asking.

**Pull request merged**
