### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by sjpadgett**
html_header_show removal causes existing implemented contrib's to break.

### CODE REVIEW

**Comment by sjpadgett** [comment]
I'll see if I can fix something else before merge

**Comment by bradymiller** [comment]
hi @sjpadgett ,
Is there anything in the codebase we can fix or is this for contrib stuff outside codebase? If only contrib stuff outside codebase, then we can:
1. Bring this PR in asap (and then I'll also bring it into rel-502 branch before 5.0.2 release)
2. Then remove it for future 5.0.3 codebase (gives users time to fix their custom code)

**Comment by sjpadgett** [comment]
@bradymiller None I can think of. Ya gotta remember that there are many, many user who have implemented encounter forms from the contrib directory. These encounter forms never get updated on releases. So the code state the form was in when enabled in past versions, remains the same. Without this then we are going to have issue with installed base. This is not custom code relief!

**Comment by bradymiller** [comment]
To clarfiy, though, we have fixed this in what is currently in the contrib directory? (ie. more worried about folks that integrated a form from a prior version contrib directory, correct?)

**Comment by bradymiller** [comment]
(Makes sense to keep this empty function for 5.0.2, and not 5.0.3. Note we have had to do similar things when phasing out the old calendar widgets; ie. users need to update their forms that were taken from contrib)

**Comment by sjpadgett** [comment]
Yes I doubled checked current which is fine. It's prior form implementation that's the concern.

**Comment by sjpadgett** [comment]
Okay by me, I just want to avoid taking down a bunch of forms...

**Comment by bradymiller** [comment]
I'll bring this commit into rel-502 directly and then no need to bring into master.

**Comment by bradymiller** [comment]
It's now in 5.0.2:
https://github.com/openemr/openemr/commit/7552601e994e53007437a33ee28c73c4ff1af4e1
(this then gives folks more warning for when it will go away in 5.0.3)

**Comment by bradymiller** [comment]
If agree, then we can close this PR :)

**Comment by sjpadgett** [comment]
Closing...

**Pull request closed without merging**
