### PR TITLE
Setting printed date/flag 

### PR DESCRIPTION
**Pull request by juggernautsei**
Fixes #

#### Short description of what this resolves:
This adds a printed date to the prescriptions. The function will only show the last printed date

#### Changes proposed in this pull request:
Adding a date to the prn column of the prescription table.
-
-
-

### CODE REVIEW

**Comment by juggernautsei** [comment]
This is the first step in adding more functionality to the prescriptions. But I am going to start a complete new build of the prescription section over in Symfony.  Instead of trying to migrate the old code, it would be better to build it from scratch new. I will be using new crops as guide for the new interface. I want to remove it from the popup and give it its own tab. There are other bells and whistles to add because I am getting input from practice fusion interface also.
It will 6 months to a year in the making.

**Comment by sjpadgett** [comment]
So @juggernautsei I recommend adding an entire PR for the new module when done.
What happens to existing weno module? Does it work? I foresee version 6.0.0 release within next 3-4 months!

**Comment by juggernautsei** [comment]
the weno module works and I am going to revive that PR this weekend to get it in the codebase. There are some entities that are in there that will be needed going forward. I will hold and submit the completed module when it is functional.

**Comment by sjpadgett** [comment]
Okay that's find but, if weno module needs these entities then, submit this commit there. Are you hoping to bring in this PR to support exist weno?

**Comment by juggernautsei** [comment]
No, it is a standalone thing. While I was working on the prescriptions for someone else this came up and I thought it would be good to add but if I am planning to move away from this module in the future. It really does not matter. I think I will remove this PR and plan on the future module. Adding it there.

**Comment by sjpadgett** [comment]
Yep, I think that best or this will just be hanging around. Not trying to be a harda## just practical. Thanks.

**Comment by juggernautsei** [comment]
Save for later...

**Pull request closed without merging**
