### PR TITLE
Add comments to constants

### PR DESCRIPTION
**Pull request by dimitristsilis**
Added comments to constant "None" to ease translation

### CODE REVIEW

**Comment by bradymiller** [comment]
Hi @dimitristsilis ,
Just to clarify, will the 'None' translation be different within the 2 different contexts of "Patient" and "Encounter"?
thanks, -brady

**Comment by dimitristsilis** [comment]
Yes, it's "Κανένας" and "Καμία"

**Comment by bradymiller** [comment]
very cool. thanks. will bring this into the codebase.

**Comment by dimitristsilis** [comment]
Thank you.

**Pull request merged**
