### PR TITLE
try PSR-12 again with added test on src directory

### PR DESCRIPTION
**Pull request by stephenwaite**
fooling around with #3392 and #3394

### CODE REVIEW

**Comment by stephenwaite** [comment]
hi @bradymiller , hoping it's okay to leave a couple of comments in the `.travis.yml` and the extra `ci/phpcs_src.xml` file for a bigger PR

**Comment by bradymiller** [comment]
hi @stephenwaite , This looks good and all changes are benign (yes, I actually looked at the changes in all 2700+ files). The only real changes were in Billing stuff, which looks good (assuming is testing well). If this is testing well for you, then I think it's ready (and you'll join the hall of fame for most file changes in a commit with the prior PSR2 gang; @robertdown and @TheToolbox ).

**Comment by stephenwaite** [comment]
where's that hall of fame? cleveland?

**Comment by bradymiller** [comment]
currently just in my head. my memory is waning though. we need an openemr blockchain to permanently store this vital information.

**Pull request merged**
