### PR TITLE
Update CCDA  phase 1.

### PR DESCRIPTION
**Pull request by sjpadgett**
Add HIE data hook for local ccda service. CCM data discrepancies and bugs.

### CODE REVIEW

**Comment by bradymiller** [comment]
Code looks good to me. Just let me know whenever the code you brings in needs to get into the 5.0.1 patch (as you have been doing already). -brady

**Comment by sjpadgett** [comment]
@bradymiller Still more to come. In process of moving the forked BB template library then will register with npm otherwise one has to install git on production in order to install the library from openemrs or my git repository! A drawback of npm imo.

**Comment by sjpadgett** [comment]
Also note the README in ccdaservice directory for instruction on install and use.

**Comment by bradymiller** [comment]
@sjpadgett , Code looks great to me. Looks like a heck of a lot of fun work :)

**Comment by sjpadgett** [comment]
Well it certainly will make you appreciate the FHIR spec improvements. Which I am close to getting back on and what was learned with the ccdaservice will be beneficial to that development.

**Pull request merged**
