### PR TITLE
Implemented global setting for onset/hospitalization date in main encounter form.

### PR DESCRIPTION
**Pull request by sunsetsystems**
This makes Onset/Hospitalization date optional.

### CODE REVIEW

**Comment by sunsetsystems** [comment]
Would also like to put this in rel-600 if there are no objections.

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
@sunsetsystems , looks good. let me know if you need me to put it into rel-600.

**Comment by sunsetsystems** [comment]
Thanks Brady! I'll update rel-600.

**Comment by sunsetsystems** [comment]
@bradymiller I can't seem to push it from the command line, I guess because 2FA? So doing this via web, but if you have suggestions for the future let me know.

**Comment by stephenwaite** [comment]
hi @sunsetsystems, are you using this for your upstream?
```
upstream        git@github.com:openemr/openemr.git (fetch)
upstream        git@github.com:openemr/openemr.git (push)
```

**Comment by sunsetsystems** [comment]
@stephenwaite I am now, it was https. Thanks.

**Pull request merged**
