### PR TITLE
Lots of user interface improvements by zbig01, revision 2.

### PR DESCRIPTION
**Pull request by bradymiller**
This is a new revision from the following PR:
https://github.com/openemr/openemr/pull/709

Screenshots:
vitals-light-bootstrap-

speech-dictation-light-bootstrap-

soap-light-bootstrap-

roschecks-light-bootstrap-

ros-light-bootstrap-

vitals-bootstrap-

speech-dictation-bootstrap-

soap-bootstrap-

ros-bootstrap-

roschecks-bootstrap-

### CODE REVIEW

**Comment by bradymiller** [comment]
@zbig01 ,
Been testing this out over last several days and looking through the code.

One issue I noted on the review of system form:
When large width, it looks good. When small width, it looks good. But when medium width, it is hard to tell which yes/no toggles go where.

Couple question:
1. Would there be a way to have just 1 theme file which could support multiple files. Check out this commit for a mechanism that allows modification of css via global settings:
https://github.com/openemr/openemr/commit/015259540048911657930c1e698777a6953957db
(if we figured out something, I would then also likely migrate the current legacy themes into just 1)
(doing this is important, because it's tough to maintain numerous style sheets)

2. We are trying to move away from inline styling. I noted there is some in your code, especially in the forms. Can this be removed?

thanks,
-brady

**Comment by bradymiller** [comment]
@zbig01 ,
Another thing I forgot to mention above. Plan to bring in all the gif changes into the codebase as a first step.

**Comment by zbig01** [comment]
Hi Brady


Here is the fix. I added a media query. I guess this is something which will crop up all the time especially in tab view when more then 2 tabs are locked together. BTW I have restyled Encounter > Administrative> Feesheet, Misc Billing Options HCFA, New Encounter form and Procedure order with bootstrap using a similar style as the other pages. Some minor issues that  I a trouble shooting right now. I might need some help, will ask after I figure out  some more things. Meanwhile some screen shots to whet your appetite ;)


 I am working on the other issues. We definitely need to have a conversation about stylesheets.


R


________________________________

**Comment by robertdown** [comment]
When did you update the procedure order form? We just migrated that one about 3 weeks ago

**Comment by zbig01** [comment]
Yesterday


________________________________

**Comment by robertdown** [comment]
Are you working off of `master`?

**Comment by zbig01** [comment]
Sorry let me clarify what I have done so far. I had forked the openemr repo a couple of months ago and I created a branch https://github.com/zbig01/openemr/tree/flat_style_master that that Brady had originally  issued a pull request for.  Meanwhile I noted that a lot of changes, especially bootstrap related ones,  had been committed to the master branch. I then pulled  and did a fast-forward merge of the openemr repo with the master in my local repo and created a new branch off of it called flat_bootstrap. I then did a bunch of commits to it and uploaded it to my repo on github https://github.com/zbig01/openemr/tree/flat_bootstrap the last commit on the master at that time was:


commit acaf2efd46d4c756e6345d06c65e90864aead111
Author: Brady Miller <brady.g.miller@gmail.com>
Date:   Sun May 21 01:27:19 2017 -0700

This resulted in a second pull request - revision 2 that you now see. Since then I have restyled the above mentioned pages though still off the master with the above commit, my local master is up to date. I am still debating whether to rebase or merge my updated local master with the local flat_bootstrap branch.

[https://avatars2.githubusercontent.com/u/12654295?v=3&s=400]<https://github.com/zbig01/openemr/tree/flat_bootstrap>

zbig01/openemr<https://github.com/zbig01/openemr/tree/flat_bootstrap>
github.com
openemr - Official OpenEMR repository


[https://avatars2.githubusercontent.com/u/12654295?v=3&s=400]<https://github.com/zbig01/openemr/tree/flat_style_master>

zbig01/openemr<https://github.com/zbig01/openemr/tree/flat_style_master>
github.com
openemr - Official OpenEMR repository




________________________________

**Comment by zbig01** [comment]
fee_sheet_bootstrap-
misc_billing_options_bootstrap-
new_encounter_form_bootstrap-
procedure_orders_bootstrap-

**Comment by robertdown** [comment]
Some suggestions. keep your local `master` branch up to date (You'll need a clean working area for this)

```bash
git checkout master
git pull --rebase upstream
```

from there I suggest keeping your working branch up to date via:

```bash
git push
git merge master
```

that will get the changes from the main repo into you branch, I suggest then pushing those changes back to your branch on github. the pull request will automatically stay updated.

Hope that makes sense.

**Comment by zbig01** [comment]
I have been regularly doing this on my local repo

```
git checkout master
git pull upstream master
git push origin master
```
`git log` - to see the new commits
I intend to do
`git checkout master`
Whether to merge/rebase is the question. 
`git rebase flat_bootstrap`
 or 
`git merge flat_bootstrap`

My limited understanding on this subject says that once commits are pushed out to github and shared rebasing should be avoided. I base my knowledge on this article https://www.atlassian.com/git/tutorials/merging-vs-rebasing that says 

> "The golden rule of git rebase is to never use it on public branches."

Are the above commands the right ones to merge/rebase the commits on my local master onto the local branch?

I guess this is now veering into a completely different topic.

**Comment by bradymiller** [comment]
@robertdown and @zbig01 ,

This is a tough one since there are going to be many merge conflicts while working on this. It may actually be easier to rebase these all into 1 commit (keep all the titles of the commits in the comment of the commit though). Then when rebase it to master branch, which should do frequently, it will be much easier. As we figure out how to integrate this into the codebase, we will be pulling out pieces anyways (having them all in separate commits isn't going to be very helpful anyways), of which those pieces will then disappear when rebase it to master. I hope I am making sense.

-brady

**Comment by bradymiller** [comment]
btw, once we are on the same page in terms of merge/rebase strategy, then will gladly provide the command set to get you there.

**Comment by zbig01** [comment]
At the risk of sounding pedantic I quote from the same article:

> For example, think about what would happen if you rebased master onto your feature branch:
> 
> The rebase moves all of the commits in master onto the tip of feature. The problem is that this only happened in your repository. All of the other developers are still working with the original master. Since rebasing results in brand new commits, Git will think that your master branch’s history has diverged from everybody else’s.
> 
> The only way to synchronize the two master branches is to merge them back together, resulting in an extra merge commit and two sets of commits that contain the same changes (the original ones, and the ones from your rebased branch). Needless to say, this is a very confusing situation.
> 
> So, before you run git rebase, always ask yourself, “Is anyone else looking at this branch?” If the answer is yes, take your hands off the keyboard and start thinking about a non-destructive way to make your changes (e.g., the git revert command). Otherwise, you’re safe to re-write history as much as you like.

This is the point that has been bugging me. I have not yet been able to wrap my head around this issue

**Comment by bradymiller** [comment]
Hi @zbig01 ,

When to use merge and/or rebase can be difficult especially with some of the rigid documentation out there. If you were working on an official development repo then would be forced to use merge (since can't change commit history). But in your case, rebase makes the most sense. And if you have all your work in 1 commit, it will make the rebase far easier. What I recommend is to keep this branch for historical purposes or in case things gets messed up on the rebase and then do the following:

# update the official master
git checkout master
git fetch upstream
git pull upstream master
git push origin master

# now make another branch to work on
git checkout flat_bootstrap
git checkout -b flat_bootstrap_2

# now to the big rebase (the the number behind is the number of commits to rebase; I count 23 on your
# public flat_bootstrap; if there are more on your local repo, then use that number)
git rebase -i HEAD~23

# Note the above command opens a text editor.
# Keep the top row 'pick' at the left unchanged, and change all the other rows from 'pick' to 's'
# (note s is short for squash)
# Now, close and save the text editor
# Now, the text editor will show the long commit message of the rebased commit. keep them all, so then close and save the text editor.

# You now have a branch that has all your code in 1 commit.

# Now can rebase off of master and fix the merge conflicts
git rebase master

# To fix merge conflicts, type `git status` and this will provider instructions on what to do.

# And note that even if things get messed up, can also abort; and note your original branch will be just fine since you are doing this in another branch.

-brady

**Comment by zbig01** [comment]
The break points of the above 4 forms are:
New Patient Encounter - 768 x 1280  WXGA - portrait mode
Misc Billing Options for HCFA-1500 - 320 x 480 HVGA - portrait mode
Fee Sheet  640 x 960 DVGA - portrait mode
Procedure Order - 768 x 1280  WXGA - portrait mode

Quick question, What in your opinion would be the resolution we need to shoot for?

I have a 23" monitor which I find adequate for viewing data, anything smaller the screen size/fonts become too small.  I understand that not everybody will have a 23" 1920 x 1080 screen, IPAD 1 10" version has 1024 x 768 XGA resolution. Anything below that the data being viewed is too much to be crammed into a small screen in a meaningful way.
Please note that though these forms are responsive up to the above resolution  the menu on top is not. Hence everything on top does not collapse gracefully

**Comment by zbig01** [comment]
Thanks for your suggestion. I will get to work on it .

**Comment by zbig01** [comment]
Is the OpenEMR\Core\Header namespace here to stay?


________________________________

**Comment by bradymiller** [comment]
yes,

Sorry, forgot to mention that the header as changed recently from a template file to a class. Can see here for details on use:
https://community.open-emr.org/t/bootstrap-standard/8547/9?u=brady.miller

There are also examples of use here, including a specific smarty function:
https://github.com/openemr/openemr/blob/master/library/core/src/Header.php#L34-L60

And can see bunch of examples of conversion from the template to the class here:
https://github.com/openemr/openemr/commit/2a5d62c831a5610e6d659922c789c3918645c7e0

**Comment by zbig01** [comment]
Thanks. I was poking around and  figuring it out

**Comment by zbig01** [comment]
Here is a screen s
clinical_instructions_bootstrap-
hot of the 9th form - Clinical Instructions, now includes namespace refrence

**Comment by zbig01** [comment]
Screenshot of Care Plan - fully bootstrapped, with namespace reference and font-awesome icons

care-plan-bootstrap-

**Comment by robertdown** [comment]
I'm looking through some of this code and it looks like you're still pretty far behind master. For instance you have lots of places that put the `fake_register_globals` back in the code, though we've removed those.

**Comment by zbig01** [comment]
You are right. My original effort was based on rel-500 branch which is the stable branch. You can see it on https://github.com/zbig01/openemr/tree/flat_styling. However as per Brady's suggestion I started to work on the master branch.

Your indefatigable effort and rapidity with which changes that have been added to the codebase lately has me playing catchup. It is only after you added the SOAP form to the codebase I started to get a sense of  which way the styling of forms was heading. I therefore started to work on some forms to get them to conform to the bootstrap standard. After I spent some time modifying the Encounter forms  I turned around only to find that the namespace for header was added.  I therefore had to start incorporating that into my changes. Each time a change happens it takes me a little while to figure out what has happened and to incorporate it. My initial idea was to modify the styling for a majority of the user facing forms.  I decided narrow my focus somewhat and to work on the encounter forms. I am slowly working through them. I have so far managed to change 10 forms and currently working on the Observation form.  So far I have posted only screenshots of the completed forms. I intended to post some commits soon. I will be basing it off the most current master.

So far the newly styled forms are looking good and stay responsive and usable even when 3 or 4  tabs are locked in tab view. They also work with the various 'official' stylesheets. I have spent a significant amount of time converting these forms, do you think that there is a chance that this styling approach could be adopted ?


________________________________

**Comment by bradymiller** [comment]
Hi @zbig01 ,

Yep, there's been a bit of a user interface revolution(a good one) going on and things have been happening very fast. The good thing is that you'll be an expert in git once your caught up to the main codebase :)

Regarding styling approach, goal is to make the forms work with the 3 categories of styles:
1. Light (modern)
2. Legacy (other ones currently offered; note tan is a bit special since this has been modernized a bit)
3. your styles

Regarding your styles, what would be very helpful is having a mechanism to have 1 stylesheet of which the colors were a global option (check out the recent mechanism added to change the font and font size to get an idea of how to go about doing this). I'd then also leverage your solution here to reduce the current legacy style in openemr to 1 style sheet.

Another thing we are trying to avoid is inline styling and styling embedded in the scripts themselves.

-brady

**Comment by zbig01** [comment]
I created a new branch https://github.com/zbig01/openemr/tree/flat_bootstrap_rev_3 and made 2 commits. It is now based off a new master the last commit on it was
```
commit c0f02e14761b900c4c8225271be34db810b7a4dc
Merge: b4ac1ce be74a7e
Author: Brady Miller <brady.g.miller@gmail.com>
Date:   Tue Jun 6 00:45:51 2017 -0700
```
The `fake_register_globals` has been removed, the encounter forms are now in bootstrap style and use the
` OpenEMR\Core\Header` namespace reference 

Some minor issues with the buttons on the Fee sheet

**Comment by bradymiller** [comment]
great (you are turning into a git expert :) ),
Now recommend making a pull request from your branch.
At:
https://github.com/zbig01/openemr/tree/flat_bootstrap_rev_3
Click the 'New Pull Request' Button

Then click 'Create Pull Request'

This is a neat feature in github, because it will update it whenever you update your branch, and is easy for folks to review/test the code.

**Comment by bradymiller** [comment]
closing this PR, since there is a new PR:
https://github.com/openemr/openemr/pull/837

**Pull request closed without merging**
