### PR TITLE
Some portal fixes and changes

### LINKED ISSUE #6410: Portal logo not scaled as before
### Describe the bug
image

### LINKED ISSUE #6411: Portal add some usability suggestions
### Describe the bug
Based on some of the suggestions from a usability study by a group at Columbia

### PR DESCRIPTION
**Pull request by sjpadgett**
#### Short description of what this resolves:
- style nav bar logo to be responsive
- change Top Nav menu toggle to indicate menu state in button.
- fix profile save alert to show in correct alert box.
- add Dismiss Form button to top and bottom of editor
- change edited document in select list to blue from red to indicated form is active.
- change My Documents to Document Actions to be clearer with instructions.

Fixes #6410 
Fixes #6411

### CODE REVIEW

**Comment by sjpadgett** [comment]
This may seem minor however based on the useability study these small changes make a difference.
I'd like to publish and open a couple ongoing issues to entice others to perhaps help out and pick off the items in the report.

**Comment by sjpadgett** [comment]
@bradymiller 
I'm working on auto popup signer dialog if template sign returns a signature not on file. This will alleviate a rather big issue with Columbia students.
However if I haven't finished and you want to build then go ahead and bring this in.

**Comment by sjpadgett** [comment]
I think I'll have to wait for the auto signer dialog. I'll have to figure out a scoping issue and will take longer than I have just now. See it in first patch!:)
Merging

**Comment by bradymiller** [comment]
dance-bear

**Pull request merged**
