### PR TITLE
fix: plot multiple points on growthchart

### LINKED ISSUE #6365: bug: growthcharts not plotting multiple points
### Describe the bug

growth charts aren't populating more than 1 vital

would like to see more than 1 on a growth chart

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #6365 which was previously fixed but was missing these

### CODE REVIEW

**Comment by sjpadgett** [comment]
umm you going to leave some for others to fix!:)

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
2DV

**Comment by stephenwaite** [comment]
testing well

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
dance-bear

**Pull request merged**
