### PR TITLE
Fix feesheet option list to include modifier if available.

### LINKED ISSUE #6361: Adding modifier causes fees not to show.
### Describe the bug
https://community.open-emr.org/t/modifier-handling-in-fee-sheet-list/20289

### Expected behavior

The fees and description are to be added to the fee sheet when selecting the CPT4 code. 

### Client configuration
This happens in the demo system. 

https://demo.openemr.io/openemr/

### PR DESCRIPTION
**Pull request by sjpadgett**
Fixes #6361 

#### Short description of what this resolves:
modify code selectors to pass around the code modifier if available
forum issue https://community.open-emr.org/t/modifier-handling-in-fee-sheet-list/20289

### CODE REVIEW

**Comment by stephenwaite** [comment]
nice

**Comment by stephenwaite** [comment]
how do you feel about displaying the modifier in the `find_code_dynamic`?

Screenshot from 2023-04-20 19-14-08

**Comment by sjpadgett** [comment]
yeah I try to add. I don't understand yet why the decryption isn't displaying in list after save!

**Comment by stephenwaite** [comment]
I think I have an old branch where I started working on this, lemme see if can find it and offer it up if it's useful.

**Comment by sjpadgett** [comment]
I misspelled. I meant I'll add it. I see where to do it and will also try to add to feesheet list.

**Comment by sjpadgett** [comment]
Okay that's it for fee sheet options. I think it's enough to be clear.
image

fee sheet. I soften the yellow search. If want diff color let me know soon.

image

**Comment by sjpadgett** [comment]
The end!

image

**Comment by sjpadgett** [comment]
@bradymiller You can merge this if you're okay with!

**Review by stephenwaite — APPROVED** [review]
smaller

**Comment by sjpadgett** [comment]
I think I'll wait to merge 'til later in case I see something to add.

**Comment by bradymiller** [comment]
dance-bear

**Comment by bradymiller** [comment]
bringing this over to rel-701 (in process of making sure rel-701 has all the most recent fixes from master)

**Pull request merged**
