### PR TITLE
ACL fix - hide forms data in the encounter with high sensitivity  

### PR DESCRIPTION
**Pull request by matrix-amiel**
Hi.

I've found that  in the encounter with high sensitivity the forms data is available to all user even if user is with normal sensitivity in the acl system. 
So I fixed it.. and hide all the encounter data.

Thanks
 Amiel

### CODE REVIEW

**Comment by bradymiller** [comment]
@sunsetsystems ,
This seems reasonable, but just wanted to make sure this is in line with what you envisioned the sensitivity ACOs to do.

**Comment by sunsetsystems** [comment]
Yeah I think this is OK. However it appears the variables $auth_* used to serve a similar purpose and are now still set but no longer queried. So those should be removed.

**Comment by sunsetsystems** [comment]
By the way see the description of function acl_get_sensitivities() in acl.inc for more insight.

**Comment by matrix-amiel** [comment]
O.k. I changed it..

**Comment by bradymiller** [comment]
@sunsetsystems and @matrix-amiel ,
I am going to rework this a little to remove all the $auth_* stuff since it's not being used in this script (just let me know if I have missed something). Plan to do this evening.

**Comment by bradymiller** [comment]
proposed commit for this feature is now here:
https://github.com/openemr/openemr/pull/864

**Pull request closed without merging**
