### PR TITLE
changed modern classes to use standard UpperCamelCase (PR was started to rename 2 files causing autoloading to fail)

### PR DESCRIPTION
**Pull request by robertdown**
There may be more files, however, these two were causing fatal errors.

### CODE REVIEW

**Comment by bradymiller** [comment]
Odd that this error hasn't shown on prior testing. Will be good to get modern class guru @MatthewVita 's eyes on this :)

**Comment by robertdown** [comment]
Already discussed it with him :)

**Comment by MatthewVita** [comment]
@bradymiller: This doesn't impact the standard XAMPP or deb installs. It's just with the PHP-FPM/Nginx for local development.

@robertdown: Hope you don't mind me "passing back the ball to you". I added a commit on this branch that changes all other modernization project files to use the standard UpperCamelCase naming convention. I just tested and I think all is well... can you double check for me? Basically just test product registration feature, the about page (should show version), office notes, and if the webapp works that means the `Checker` is working.

**Comment by bradymiller** [comment]
@robertdown and @MatthewVita ,
This tested well (per Matthew's) testing, so will bring this into the codebase.
-brady

**Comment by MatthewVita** [comment]
Thanks Brady!

**Pull request merged**
