### PR TITLE
Remove old patient portal

### PR DESCRIPTION
**Pull request by bradymiller**
Still testing

### CODE REVIEW

**Comment by sjpadgett** [comment]
The only suggestion I can think of is to ensure we leave behind the disable flag in globals table. Maybe with a depreciated comment or hard code off in globals.php.

**Comment by bradymiller** [comment]
Hi @sjpadgett ,
All use of the old portal flags have been removed from the codebase (it is like it never existed :) ) . Since this is a new release, we can just announce removal of old portal in the changes. Either way, users will quickly figure this out :)

**Comment by sjpadgett** [comment]
great, guess I could look at the commits in the future

**Comment by bradymiller** [comment]
where's the fun in that :)

**Comment by bradymiller** [comment]
testing well
fare thee well :)

**Pull request merged**
