### PR TITLE
Create Central Style Folder (#3792)

### LINKED ISSUE #3792: Add Area In SCSS Themes to Allow Centralizing Stylesheets
I will be making a PR that creates an area where we can migrate all of our CSS that is in different folders to one centralized location.

### PR DESCRIPTION
**Pull request by tywrenn**
Fixes #3792

#### Short description of what this resolves:

Creates a central style folder.

### CODE REVIEW

**Comment by tywrenn** [comment]
@bradymiller Ready for testing

**Comment by bradymiller** [comment]
hi @tywrenn , Neat stuff. If testing well for you, then just let me know, and then I'll bring it in.

**Comment by tywrenn** [comment]
@bradymiller This is testing well. Ready for merging.

**Comment by bradymiller** [comment]
hi @tywrenn , bringing in. thanks for the improvements! -brady

**Pull request merged**
