### PR TITLE
Batch Payments bug fixes v5.0.2

### PR DESCRIPTION
**Pull request by sjpadgett**
- add dialog full width
- add back full screen dialog for search payments id, date, insurance radios.click
- still use modal for rest
- fix remainder bug
- fix missing brace causing big portion of edit script to not run
- add Global account amount charge off to Payment history

Fixes numerous Forum issues!

#### Short description of what this resolves:
Major bugs causing much user shagrin!

### CODE REVIEW

**Comment by sjpadgett** [comment]
Still testing math.

**Comment by bradymiller** [comment]
code looks good, but travis pounced

Agree with the promotion :)
I'm gonna promote myself either to Sr. Vice President of Lesser Stuff or maybe the Assistant of "cat in the bowl" (still undecided)

tenor (29)

**Comment by sjpadgett** [comment]
@stephenwaite  This is getting mind boggling....
Added Global charge off read only.
image

 Notice the missing 200.00 allocation. When sent remdr to global on finish payment check out how AR session was written!

image

Note how an AR activity allocation was automatically written for the remaining 200.00 which I didn't allocate!!!

image

**Comment by sjpadgett** [comment]
Last thing to fix is number formatting. @bradymiller Do we have any formatting functions for international> ie in JS?
Note currency values breaks math..
image

**Comment by stephenwaite** [comment]
> Do we have any formatting functions for international> ie in JS?
Note currency values breaks math..

could you detail this a little more to me @sjpadgett , if i understand correctly the values that you have that you'd like to compute with are not able to handle translation?

**Comment by sjpadgett** [comment]
The problem here @stephenwaite is we don't set input values as numbers is many places but write string representations to the table cells as innerHtml. Ho hum, this can cause several problems namely comma as one. For international some locals use comma as decimal place holder.. go figure and we tend to only * 1 to convert string (not reliable).
I'm just going to write a new function to straighten this all out eventually using locale global for how to format. Just for JS as we have this covered for PHP....

**Comment by sjpadgett** [comment]
@stephenwaite I'm tired of looking at this. Not fun!
Anyway, this is the best i'm going to do for now. I added some new functions that may not make a lot of sense now but will when I get around to doing some in UI status reports. I did add a table refresh button to recalculate if need arises.

When travis is done, i'm bringing in. I will build a pre patch i'll give you if you will get with the forum folks to test for us. If anything, what i've done here can't hurt any worse than what's out in the world now. 
I still have to now bring this forward to v6.0 again... back port, no no forward port umm where am I again?:)

**Comment by sjpadgett** [comment]
@stephenwaite 
Here is pre patch 4. Has all patches plus current for patch 4. Thanks
[patch1-patch3_prepatch_4.zip](https://github.com/openemr/openemr/files/4856080/patch1-patch3_prepatch_4.zip)

**Pull request merged**
