### PR TITLE
Migrated the forms menu to forms.php

### PR DESCRIPTION
**Pull request by bradymiller**
Migrated the forms menu to forms.php.
This does several things:
1. Does not show the forms menu when editing a form.
2. Because of 1, it allows using bootstrap on the menu.
3. Makes the code more clear.

This is really just an interim step to allow @robertdown to do bootstrap magic on this menu and the encounter gui. Didn't change any of the menu code since @robertdown has already been working on this and this will make it easier to copy/paste that code over while working on it. Then can clean it up and organize it better after that is done.

### CODE REVIEW

**Comment by mdsupport** [comment]
Just a side comment - since we don't know the final design : 
We converted the encounter menu to something more compact as a constant nav bar on all encounter pages.  Then it was realized that you already have the main items (list of forms) in the top menu.  That was the point where we split patient menu into patient and encounter as separate top levels.

emr

**Comment by robertdown** [comment]
Horizontal encounter menu is going away all together, there will be a vertical sidebar instead of the current menu on top. Should have this ready by the weekend, I had most of it complete but was getting stuck on the forms issue.

**Comment by mdsupport** [comment]
One approach we are testing out is attaching content specific menus to tab headers.  So far that seems to work out well.

**Comment by bradymiller** [comment]
@robertdown ,
Is it ok if I bring this PR in?
1. Then we can see what community thinks of having no menu in the forms themselves.
2. And @stephenwaite needs to do some work (making it so misc_billing can only have 1 form per encounter) in interface/patient_file/encounter/load_form.php , and bringing this in will avoid conflicts and simply his work.

**Comment by robertdown** [comment]
Go for it - this will allow me to merge in the new encounter summary menu

**Pull request merged**
