### PR TITLE
remove encount undefined variable notice

### PR DESCRIPTION
**Pull request by stephenwaite**

### CODE REVIEW

**Comment by bradymiller** [comment]
looks good and will bring into codebase. thanks for the fix! -brady

**Comment by stephenwaite** [comment]
thanks Brady, do you think that when the sql_admin successfully completes there should be a link at the bottom of the page to         http://<server_name>/openemr/acl_upgrade.php?site=<site_id>

**Comment by stephenwaite** [comment]
i mean sql_upgrade which you are directed to following multi site instructions

**Comment by bradymiller** [comment]
For each site, it should walk users through what is behind by providing the upgrade links (including acl if that is behind).

**Comment by bradymiller** [comment]
another thing is that sql_upgrade also will try to do acl_upgrade

**Pull request merged**
