### PR TITLE
Tonys floating messages

### PR DESCRIPTION
**Pull request by teryhill**
This was gotten from Tony McCormick at MI2. The work was done by Julia
Longtin. I made some changes to add a case if the allergy is fatal and
to give floaters for patient alert messages.

### CODE REVIEW

**Comment by mdsupport** [comment]
Onsite portal already uses a jquery popup addon.  In addition I think ZH contribution may be using another one in deep in zend.  

Wouldn't it be better to use that or one of many other third party add-ons that have lot more formatting features?

**Comment by teryhill** [comment]
Sounds good to me go for it. This has been sitting since the end of april.

**Comment by bradymiller** [comment]
Hi,
Did you mean to close this?
-brady

**Comment by teryhill** [comment]
Yes I think MDsupport has a better plan and am looking forward to their option, or did I miss something?

**Comment by bradymiller** [comment]
Nope. You didn't miss anything. Just need another cup of coffee over here.

**Pull request closed without merging**
