### PR TITLE
Fix #3307: remove body_top class

### LINKED ISSUE #3307: Fix body_top margins/padding and Remove body_top class (Sub-issue to #3302)
This is a sub-issue to #3302.

The goal is to fix the `body_top` class margin/padding.
Current Output:
image

Expected Output:
image

Also, this issue will remove the `body_top` class as we shouldn't be using it.

### PR DESCRIPTION
**Pull request by stu01509**
Fixes #3307

#### Short description of what this resolves:
Removed all body_top class.

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller Why is this necessary. This is almost the entire codebase for one edit. This is how we introduce bugs. All we need to do is make the class empty in css. Also, you never know if that body_top class may be needed in future. Just saying...

**Comment by tywrenn** [comment]
@sjpadgett Surprisingly this edit will not introduce bugs because when you declare what the body element style is in CSS and remove the body_top class; if any remnants of body_top was still declared it would do nothing at all and since the body element style is set in place it would automatically default to that as the setting. The only bug that would happen is if someone was declaring JavaScript on it which is highly unlikely to be the case as I've never seen it delcared in JavaScript.

**Comment by tywrenn** [comment]
I still will need to test this so wait for me to make sure this is correct

**Comment by sjpadgett** [comment]
It's not the removal that bothers me it's the act:) Seems like everytime we do these mass edits, things break. Other than that, I don't care

**Comment by bradymiller** [comment]
big acts got OpenEMR to bs4
sure, sometimes a bug may get in :)

tenor (8)

**Comment by stu01509** [comment]
Should I divide it into many parts in next time?

**Comment by sjpadgett** [comment]
> Should I divide it into many parts in next time?

You won't find many times you'll need to do this. This is fine

**Comment by stu01509** [comment]
Hi @tywrenn 

I fixed the error code and remove unnecessary spacing, should I need to figure out the SCSS file `.body_top` class  where is getting triggered?

**Comment by tywrenn** [comment]
@sjpadgett @stu01509 After some thought about this, I realized that `body_top` changes in ways that could conflict code if I were to pursue this.

Some ways it can conflict:
- In the SCSS, if you don't have `body_top` set on the body tag (and you didn't want the formatting of `body_top` there), we would have to individually go in each file and test each one to see if they need the formatting or not which makes this issue not really worth fixing as it's a general code improvement.
- Redesigning the body margins/padding for each file is time consuming

For these reasons, i'm asking this pull request be closed as it takes too much time to attempt to fix and since it ain't broke we might as well leave it.

**Comment by sjpadgett** [comment]
It's okay with me. We could keep an eye out for where the class adversely affects the UI and fix.

**Comment by tywrenn** [comment]
Well if we are to actually do this, we should do it in GSoC cause we are gonna be doing a ton of work when that comes around.

**Comment by stu01509** [comment]
Hi @tywrenn 

I got it! Thanks for your explanation :)

**Comment by stu01509** [comment]
So should I close this PR?

**Comment by tywrenn** [comment]
@stu01509 Yes you may close this

**Pull request closed without merging**
