### PR TITLE
Show message indicator and several tab layout changes

### PR DESCRIPTION
**Pull request by bradymiller**
The demo for this code is here:
http://www.open-emr.org/wiki/index.php/Development_Demo#192.168.1.131

Also integrated several tab layout changes by MDSupport from:
https://github.com/openemr/openemr/pull/277

Also updated legacy themes with Ray's buttons from the tan theme.

### CODE REVIEW

**Comment by robertdown** [comment]
Suggest not creating a separate button and instead adding a bubble icon with the number of unread items on the actual "Messages" menu item.

**Comment by bradymiller** [comment]
There are 2 issues with using the Messages menu item to show this:
1. I have no idea how to do that.
2. The menu will be customizable in the likely near future and thus is very possible that the "Messages" entry will get nested into the menu(ie. then entry won't show up at the top).

**Comment by bradymiller** [comment]
This code is ready for community review.

Demo is here:
http://www.open-emr.org/wiki/index.php/Development_Demo#192.168.1.131

**Comment by bradymiller** [comment]
No further objections, so bringing this code in.

**Pull request merged**
