### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by bradymiller**
Still testing (fixes a security vulnerability)

### CODE REVIEW

**Comment by bradymiller** [comment]
odd unrelated psr2 issues here. will do a travis repeat testing tomorrow.

**Comment by stephenwaite** [comment]
looks like codesniffer bumped up to 3.5 and may have caused this

**Comment by bradymiller** [comment]
@stephenwaite , Brought in the codesniffer changes from 3.5 version in a separate PR, so all good now. We should look at version 3.5 in more detail, though, since it looks like it provides support for more code styling (via PSR12).

**Comment by bradymiller** [comment]
Actually, will be best to simply die rather than having the false stuff. Gonna simplify and rework this.

**Comment by bradymiller** [comment]
Closing PR, since submitted better bug fix for this issue in this new PR:
https://github.com/openemr/openemr/pull/2698/files

**Pull request closed without merging**
