### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by stephenwaite**
bug fix

### CODE REVIEW

**Comment by bradymiller** [comment]
code looks good
Would just make sure that $eid is never meant to be empty in this script or else i think this would exit in those cases.(i didn't look through the script to figure that out)

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
118382341-53d9d600-b5c2-11eb-8b7e-220bbab8468a

**Comment by stephenwaite** [comment]
>Would just make sure that $eid is never meant to be empty in this script or else i think this would exit in those cases.(i didn't look through the script to figure that out)

good call, will add that since later down there's a multi providers case where it's acting on an empty `$eid`

**Comment by stephenwaite** [comment]
think I've got this working ok, thanks @bradymiller

**Pull request merged**
