### PR TITLE
UX - Expandable Search Patient By Any Demographics - Take 3

### PR DESCRIPTION
**Pull request by zbig01**
After a lively discussion in the previous PR #2513 here is a solution to address the key issues raised
 1 - Whether or not to have the Search Any button have dual behavior
    - to open a filtered set of results in Patient Finder based on a non-empty search string in the search any text box
    - to directly open Patient Finder and display the entire patient list 
 2 - Whether or not to hide the entire input box behind the search button and to only allow filtered results if the 
 search any text box contained a non-empty string
 
 There is a case to be made for and against both these arguments and the current solution is to have both these options available
 and let the administrator or individual user choose what they want.
 
 The two options are called 'Dual' and 'Comprehensive'.
 
 Dual - lets the user either access the Patient Finder directly by clicking the Search Button or open a filtered set of results 
 in Patient Finder based on a non-empty search string in the search any text box.
 
 Comprehensive - hides the input search box behind the search button and only allows filtered results if the 
 search any text box contains a non-empty string
 
 The default option is 'Dual';)
 
 To change the option as an administrator go to 
 Administration > Globals > Appearance > Search Patient By Any Demographics
 
 To change the option as an individual user go to 
 User Name > Settings > Appearance > Search Patient By Any Demographics

below added by bradymiller:
Up For Grabs demo for this PR is at: https://www.open-emr.org/wiki/index.php/Development_Demo#Zeta_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by bradymiller** [comment]
Up For Grabs demo for this PR is at: https://www.open-emr.org/wiki/index.php/Development_Demo#Zeta_-_Up_For_Grabs_Demo

**Comment by zbig01** [comment]
@bradymiller 
Thanks, demo is testing well. Any pending issues ?

**Comment by bradymiller** [comment]
hi @zbig01 , Code and testing looks good to me. @sjpadgett , this appears to address concerns; let us know if have issues. -brady

**Comment by sjpadgett** [comment]
Really didn't address but hid it. I still don't understand why having that slider is important.  As they say: Those that do the work , get it their way...

**Pull request merged**
