### PR TITLE
Add support for special sql in module install script

### PR DESCRIPTION
**Pull request by eyalvo-matrix**
Fixes # can't run triggers , and SQL with ; 

#### Short description of what this resolves:

extend the ability to run SQL that contain ; in module install.sql

### CODE REVIEW

**Comment by eyalvo-matrix** [comment]
Hi @bradymiller , hope that all is good in the US with all of this COVID-19 mess . 
I encounter a problem running triggers and other SQL that contains ;  in the module install.sql 
I propose adding a special comment like in the upgrade ( for example #IfNotColumnType ) to enable this ability

**Comment by bradymiller** [comment]
hi @eyalvo-matrix ,
Great to hear from you!
What would be an example of use for this (just so I can see what this is meant to do)?

**Comment by eyalvo-matrix** [comment]
Hi @bradymiller 
here is a real case sql that does problems : 
#specialSql
INSERT INTO `layout_options` (`form_id`, `field_id`, `group_id`, `title`, `seq`, `data_type`, `uor`, `fld_length`, `max_length`, `list_id`, `titlecols`, `datacols`, `default_value`, `edit_options`, `description`, `fld_rows`, `list_backup_id`, `source`, `conditions`, `validation`) VALUES
('DEM', 'mh_payment_body', '3', 'Payment body', 80, 2, 1, 10, 100, '', 1, 1, '', '', 'Payment body', 0, '', 'F', 'a:1:{i:0;a:5:{s:2:"id";s:20:"mh_fee_participation";s:6:"itemid";N;s:8:"operator";s:2:"ne";s:5:"value";s:3:"YES";s:5:"andor";s:0:"";}}', '');
#endSpecialSql

**Comment by eyalvo-matrix** [comment]
you can easily have fun with the regex in 

https://www.phpliveregex.com/p/wEp  (just press the "preg-match-all"  in the link )

**Comment by eyalvo-matrix** [comment]
Hi @bradymiller can you please see if you have any remark on this pull request? 
cause without it it is impossible to install modules that have semicolon in their install.sql including triggers and such

**Comment by sjpadgett** [comment]
Hi @eyalvo-matrix , Brady may be gone for the night. I don't see any problems with this except it looks like if there's not special sql then the regex passes query unmolested, is this true from your testing?

**Comment by eyalvo-matrix** [comment]
Hi @sjpadgett , Yes I have checked the regex quit a lot and even discovered that preg_replace() has a backtrack limit defined. 
(https://bugs.php.net/bug.php?id=63651) it means that for large files and inefficient regex the function will return null. 
I have checked that does not happen at least for the file I have checked (I tested for up to 100 MB of sql)

**Comment by sjpadgett** [comment]
Good enough for me. I'm in Zend code now bring it up to PHP 7.4 and dealing with the static function calls. I still don't understand why it was written this way in the first place.

Bringing in. Have a good one and be safe.

**Pull request merged**
