### PR TITLE
removed several unused mysql database tables

### PR DESCRIPTION
**Pull request by bradymiller**
Did a database analysis (try to do this before every release) and updated the following wiki page:
https://www.open-emr.org/wiki/index.php/Database_Structure#Tables

Noted  5 tables that appear to no be used and can be removed.

### CODE REVIEW

**Comment by bradymiller** [comment]
Actually, looks like the `notes` table may be used by the Notes.class.php class in documents code. Looking into.

**Comment by mdsupport** [comment]
notes is used by lab orders and documents.  Not sure why the developer decided to not use pnotes.  It consistently causes confusion for new developers and extra lookup for all.

**Comment by sunsetsystems** [comment]
Where is notes used by lab orders? I'm not seeing that.

**Comment by bradymiller** [comment]
k, added back notes. this is now testing well, and removed the 5 unused tables and related code. gonna bring this into codebase.

**Comment by bradymiller** [comment]
quick code from the past :)
https://github.com/openemr/openemr/commit/c968a3994c66c2f42f5f6d422368baa024136399

**Comment by mdsupport** [comment]
For what it is worth, had to go back and check about notes.  
Look like notes is used to attach comments to documents.  Then it gets referenced wherever documents are shown - e.g. [lab orders](https://github.com/openemr/openemr/blob/d6745196f564e492fc433f069cd9c7047596ba36/interface/orders/single_order_results.inc.php#L267), [encounters](https://github.com/openemr/openemr/blob/07fdb653dd34e96efe500e3eac942be6825e096e/interface/patient_file/history/encounters.php#L91).

Although technically documents can live without any links to patient, it probably is rare.  Would still prefer a central notes storage.

**Pull request merged**
