### PR TITLE
new datetimepicker

### PR DESCRIPTION
**Pull request by bradymiller**
Can see the date picker at:
Reports->Visits->Appointments

Can see the date/time picker at:
Administration->Other->Logs

It also supports translations via OpenEMR and supports RTL.

Date picker screenshot:
image

Date and time picker screenshot:
image

### CODE REVIEW

**Comment by sunsetsystems** [comment]
Looks nice, some quick questions...
Can you easily go back a year or more at a time?
Can the time be more granular than hours?
Can you still just type in the date/time?
Is the tool being actively maintained?

**Comment by bradymiller** [comment]
Year can be scrolled by clicking the year at top.
Can make time more granular, but then would be a lot of scrolling.
yes, can just type in date/time
Last code change to the github repository was 8 months ago, so there is risk of it going stale. This is more of a stepping stone, since when we go to bootstrap in the future, can then potentially convert to a bootstrap datetimepicker.

some notes to myself for improvements:
Will need to set 'yearStart' setting to 1900 (to ensure can go back far enough to capture birthdates)
Should incorporate the start day of week global into the 'dayOfWeekStart' setting

**Comment by bradymiller** [comment]
Will not set the dayOfWeekStart for now since the related global in OpenEMR is meant to state when the work week starts, not which column should be at left on the calendar.

**Comment by bradymiller** [comment]
Couple improvements:
1. Added yearstart to be 1900 to allow entering of birthdates long ago (note can scroll very fast, so can get to dates in past really quick)
2. Changed time to 30 minute intervals (as above can scroll really quick).

I also incorporated the datetimewidget in the group of reports at Reports->Clients. Please test it out and let me know how they are working. Would like to ensure feedback is positive before beginning the relatively long process on converting to the new datetimepicker (note am also upgrading to most recent jquery library as do this since it's a good opportunity because need to test each script after change the picker)

**Comment by mdsupport** [comment]
just brainstorming here
Since date/time library is so pervasive, leave current code untouched and leverage current call
`Calendar.setup({inputField:"date_field", ifFormat:"%Y-%m-%d", button:"img_from_date"});` - 

Replace Calendar.setup code should:
- inspect script stack and add necessary js and css
- Like many other jquery plugins, add a text field with id 'dtpk'+inputField after inputField with initial value = inputField value
- hide inputField and button
- On update of 'dtpk'+inputField, update inputField
- May be better to use json to provide translations rather than invoking php in the middle of script tag.

Later, existing date_field code should be replaced by a simple input tag for hidden text field without need for any other attributes.

May also be better to explore [bootstrap datepicker](http://eonasdan.github.io/bootstrap-datetimepicker/) for ui flexibility.

**Comment by bradymiller** [comment]
If you provide me with a working example of this in the code, then I'd have a better idea of what you are proposing.

Was planning to use this reason to clean up the code a bit and would rather remove the unneeded code and make it more straightforward.

bootstrap's datepicker would require bootstrap css in every script which OpenEMR doesn't support yet (this will likely happen in the future; when we can do this, it then will be straightforward with a little more elbow grease to bring that in; this is also assuming the bootstrap datepicker will do everything we need it to do).

Internationalization in javascript packages can be hit or miss since many of them depend on locales which then places the control of the translations outside of OpenEMR, which we are avoiding. This is why have the "odd" template mechanism to bring in the translations and locale settings. Note there is another "alternative" mechanism being used for the patient portal code (currently under development) where php does not have access to the javascript listener call, so instead creates the javascript variables prior to the javascript script:
https://github.com/sjpadgett/openemr/blob/d24cb6efdeee65598e7402ee1bc687ce9832b352/library/js/xl/jquery-datetimepicker-2-5-4-alternate.js.php

**Comment by mdsupport** [comment]
Will try to put snippets of a common file we use for all scripts.

Ideally you want to load javascript stuff at the end of body.  There you can examine all script tags -

```
// Public assets
var scripts = document.querySelectorAll( 'script[src]' );
var emr_root = scripts[ scripts.length - 1 ].src.split( '/' );
emr_root.splice(-2,2);
emr_root = emr_root.join( '/' );
```
You can also declare stuff you want to bring in *on demand* - this also provides a centralized mapping hook to upgrade versions - 

```
var link_assets = {
    "qTip.css": emr_root + "/public/assets/qtip2-2-2-1/jquery.qtip.min.css",
    "qTip.js":  emr_root + "/public/assets/qtip2-2-2-1/jquery.qtip.min.js",   
};
```
Now have a common routine to dynamically bring in needed stuff -
```
function dynamic_link($, link_type, link_href) {
    if (link_type=='css') {
        $('<link>')
        .appendTo('head')
        .attr({
            type: ('text/css'), 
            rel: ('stylesheet'),
            href: link_href
        });
    } else {
        $.getScript(link_href);
    }
}
```

Now you can bring in a 'css' or 'js' file  dynamically -
```
    dynamic_link($, 'css', emr_root + "/custom/zcss.bootstap.dropmenu.css");
    dynamic_link($, 'js', emr_root + "/custom/zcss.bootstap.dropmenu.js");
```

**Comment by mdsupport** [comment]
Translations do not seem to need server contexts.  In that case, specially for js libraries every user script does not need to repeat code.  Couple of options to share translations in js world would be : 

1. Make a json call to server to fetch translated object - e.g. 
- build an js object of multiple English strings (e.g. 
`var lbls = { dt_from: 'From', dt_to: 'To', .........};`.  
- At run time, client make a single call to server which will run xl on all input strings and return results.
- Returned string is processed to replaces original lbls object.
- The jquery code which constructs html should use lbls.dt_from, lbls.dt_to etc. 

2. Other option would be to push translated strings to client, ideally at the time of login when language is selected in some form of local database or object.  All other scripts can then invoke strings without any further involvement from server.

**Comment by bradymiller** [comment]
Hi @mdsupport ,
Check out the following discussion and let me know if it changes your thoughts:
https://github.com/openemr/openemr/pull/293
thanks, -brady

**Comment by mdsupport** [comment]
Pretty much same view as noted in my comment there too.  Client computing capacity continues to explode.  So server should execute models and let clients manage views.  From this projects perspective that means the php scripts should have more php code and less echos (hopefully none) and html lines and more flexible, self contained js scripts.  That was the basic intent of original comment.

As far as current PR is concerned, your approach is much welcome cleaner implementation.  Thx.

**Comment by bradymiller** [comment]
Just brought these changes into most of the reports. Looks like I have the ok to bring this into the codebase :)

So gonna bring in the PR and then make another one as continue the code walk through.

**Pull request merged**
