### PR TITLE
oauth updates

### LINKED ISSUE #4030: oauth stuff
Goal to have these completed prior to 6.0.0 release :
1. incorporate csrf (for the login.php script). gotta analyze this a bit especially since sameSite needs to be set to Lax; possibly won't need to do this.
3. Remove user_id and user_role from client table and entity
4. Regarding php8 (gotta wait for this to be completed and releases in league package: https://github.com/thephpleague/oauth2-server/pull/1146)

### PR DESCRIPTION
**Pull request by bradymiller**
fixes #4030 

@sjpadgett , this is still a work in progress (functional for both users and patient roles, but needed to hard-code the user_role (https://github.com/openemr/openemr/blob/ad12c9c559a11284b038ac9709b7aeeb3ce31810/src/RestControllers/AuthorizationController.php#L674-L677) until have your hook mechanism in there). also still a bunch more stuff and testing for me to do (gonna get a up for grabs demo on this so i can finally test across origin with the client - keeping fingers crossed that Lax will work :) ).

Up For Grabs demo for this PR is here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Delta_-_Up_For_Grabs_Demo
(dang, gotta update the demo farm to use a more recent version of alpine or ubuntu to get to php version 7.3!)

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller 
Lax is working for me today from chrome using the origin https://openidconnect.net/ ! so go figure. The way to tell is if the consent scopes don't show in consent dialog. Still don't trust yet however, i'm going to pull this branch, test using it while I finish session persist. Having a little problem here of getting the encrypted code for lookup identifier because persistNewAuthCode() is the entity before encryption.  Only way is to parse it out of the redirect GET query.  Easy enough but seems like a hack to me so, still poking around for a better way to id the session cache.

Do you want me to just pull/push from/to this PR or do you want dueling PRs?

**Comment by bradymiller** [comment]
@sjpadgett , Regarding PR, just do whatever is easiest for you (use my PR or your own PR). I'm happy to adapt my PR whenever needed.

**Comment by bradymiller** [comment]
Just let me know if you will be using my PR (then I'll hold off on pushing anything to it until you give the all clear :) ).

**Comment by bradymiller** [comment]
Another option is to just bring this PR into codebase (if so, would just take me an hour or so to do a extensive code review to make sure i didn't do anything stupid :) ).

**Comment by sjpadgett** [comment]
> Another option is to just bring this PR into codebase

Will break master until I fix session which i'm about an hour from finishing that then testing. I can just push to you then put in master.

**Comment by sjpadgett** [comment]
Almost done. I have working but I think I should encrypt session data store in trusted user. You want to do or me, I don't care?

**Comment by bradymiller** [comment]
happy to do that. lets see what it is storing first.

**Comment by sjpadgett** [comment]
```
{"site_id":"default","enable_database_connection_pooling":"1","nonce":"b313b048372f0f5aa1b32a5d5e899b3f","csrf":"d6a807c60136440c3c0e46f98162bb47","scopes":"openid api:fhir email","client_id":"kbyuFDidLLm280LIwVFiazOqjO3ty","user_id":"91e65743-aa8c-4a7e-a183-706912c92436","user_role":"users","persist_login":0}
```
I think we'll be okay. I pulled sensitive unneeded session vars. I'll push to you as soon as I get organized

**Comment by sjpadgett** [comment]
Hope I got it. Seems to work but limited testing so you can move on but here is an access token decode;
```
{
  "aud": "kbyuFDidLLm280LIwVFiazOqjO3ty8KH",
  "jti": "e0a274c05d57a75267d22cb509aade5e4f732bbd502f7d7b3d85a0ba48058e874e47bb34d2846772",
  "iat": 1605474673,
  "nbf": 1605474673,
  "exp": 1605478273,
  "sub": "91e65743-aa8c-4a7e-a183-706912c92436",
  "scopes": [
    "openid",
    "profile",
    "email",
    "phone",
    "address",
    "nonce",
    "site:default",
    "user_role:users"
  ]
}
```
Guess I could have did one with api scopes but anyway, there it is.

**Comment by bradymiller** [comment]
this is testing well and code looks sane. bringing in!

**Pull request merged**
