### PR TITLE
GH-2220: simplify OpenEMR directories

### PR DESCRIPTION
**Pull request by danehrlich1**
- simplify OpenEMR directory structure 
- Entities / Repositories are part of Matthew's attempted Doctrine migration and will preserve them on another branch

### CODE REVIEW

**Comment by danehrlich1** [comment]
Removed three directories.

Entities and Repositories will be preserved in another branch (e.g. `feature/doctrine-migration` or something) since they contain Matthew's attempted Doctrine migration.

**Comment by danehrlich1** [comment]
gacl - move to Library eventually?
images - should be in public?
modules/sms_email_reminder - move to library or interface?
patients - old simple patient portal - delete for version 5.0.2?

a few others I'll add later...appreciate anyone's thoughts...including Jerry's... :)

**Comment by bradymiller** [comment]
gacl is basically a module. Guessing there is some files in there that could be removed, though.
agree images should go to public (should check each one though and see if they are even being used)
modules/sms_email_reminder appears to have both interface and library components in it. Maybe good to keep in module then.
The old patient portal just was removed a couple hours ago :)

**Comment by danehrlich1** [comment]
Saw that and that was awesome.

Can moving Images to Public be one of our “first-timers-only” issue? Figured it was a good start for someone who is new or just joined a few weeks ago. 

If not will do it myself.

Thanks :)

**Comment by bradymiller** [comment]
Definitely a good first user project. Steps would be:
1. Search codebase to see if even used
2. If not used, delete it
3. If used, then migrate it to public/images and change to corresponding path to where it is used (with the goal of using the either one of these variables for the path if possible (note would not be able to use this if the path is in a styling only script): https://github.com/openemr/openemr/blob/master/interface/globals.php#L194-L198)

**Comment by bradymiller** [comment]
hi @danehrlich1 ,
Is this the doctrine PR? Don't these files need to be moved rather than deleted?

**Comment by danehrlich1** [comment]
Doctrine files were moved to another branch. Let me check not from my phone in 60 mins.

**Comment by danehrlich1** [comment]
@bradymiller I created a branch called `feature/doctrine` off of master. All the Doctrine code is safely there. 

Can you merge in this branch to master? It will remove the folders `entities` and `repositories`, but those are now preserved on the `features/doctrine` branch.

**Comment by danehrlich1** [comment]
> hi @danehrlich1 ,
> Is this the doctrine PR? Don't these files need to be moved rather than deleted?

Yes, moved to another branch AND THEN deleted on master.

**Comment by bradymiller** [comment]
I am not seeing the commit that does this in that branch:
https://github.com/openemr/openemr/commits/feature/doctrine

**Comment by bradymiller** [comment]
also, more ideal to use personal repo branches (and create a PR from that) rather than push them as new branches to the openemr repo.

**Comment by danehrlich1** [comment]
@bradymiller Do you just want to do it? It's a weird non-intuitive Git thing to do, but you can probably knock it out in 3 mins from your side.

Sry not to dump work on you though.

**Comment by bradymiller** [comment]
hi @danehrlich1 ,
Trying to get clarification on plans for the code in entities and repositories folders. Note that code is actively used by the codebase, so can't be removed. Are we migrating them to another directory?

**Pull request closed without merging**
