### PR TITLE
update admin users gui

### PR DESCRIPTION
**Pull request by bradymiller**
Still need to work out a bug when save (it takes over the entire browser). And the algorithm on the receiving script is a bit complicated and needs to be able to throw a popup if an issue arises (not as simple to do an ajax call and then refresh like in other examples).

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @sjpadgett ,

The user script that catches the popup form output is pretty complicated and unable to do a simply ajax call of the script via strategy at https://github.com/openemr/openemr/blob/master/interface/usergroup/facility_user_admin.php#L42-L55

Is there a way for the form output to be directed at the original frame that called the popup?

**Comment by sjpadgett** [comment]
@bradymiller See, I told 'ya that fancybox would regroup and mount a defense but I did not expect a counter attack.:) 
You also have a onClosed: 'function' that will execute before the dlgclose() callback that may be used. In both cases the callbacks are called after dialog is closed and destroyed. Do you mind if I go ahead and do this one in case I need to add some facility to my dialog?

**Comment by sjpadgett** [comment]
Actually I'll pull this and look at first then go from there.

**Comment by sjpadgett** [comment]
@bradymiller In the script facility_user.php try adding an exit() after line 42 in the save/ insert post if. facility_user_admin.php saves to facility_user.php and if that script does not exit then all bets are off.

**Comment by bradymiller** [comment]
@sjpadgett , Is there a way to pass the origin frame name through dlgopen. Then if can work this into the target at https://github.com/bradymiller/openemr/blob/2bfeb55585b30500e39be883205e5a3ac05a9c5a/interface/usergroup/usergroup_admin_add.php#L187, then all would be good (this would also be helpful for other scripts/dialogues that do this). To confirm this, if I hard-coded target to be `adm` in the tabs ui, then things worked out well.

**Comment by bradymiller** [comment]
Also, definitely feel free to take this over (or I can keep plugging away on it).

**Comment by sjpadgett** [comment]
Biggest problem is doing the submit outside the form as unless the submit is initiated inside the form the onsubmit event never fires. Plus form validation. FF will allow you to target a frame name however others will simply open a new window. I can't understand how this worked previous to my dialog in other browsers. Note, the other two forms in the script submit inside the form.
 I'll be happy to take over and it's nothing on you but simply I solved this somewhere else plus I will take a look at maybe improving dlgopen. Lets just bring this in as it is and I'll pull and modify some time today...

**Comment by bradymiller** [comment]
k, will bring it in and await your magic :)

**Pull request merged**
