### PR TITLE
Added stripe package

### PR DESCRIPTION
**Pull request by bradymiller**
requested by @juggernautsei

### CODE REVIEW

**Comment by zbig01** [comment]
@bradymiller 
FYI  I have installed  and working stripe credit card payment system with reports etc since openEMR 4.2.2.  I had developed it with help from @juggernautsei . I wonder if you would be interested in our experience.

**Comment by juggernautsei** [comment]
Sure, can you post it on git?

**Comment by bradymiller** [comment]
@zbig01 , Agree with @juggernautsei that any posted related code will be helpful.

**Comment by zbig01** [comment]
Done. Check out PR #1099

**Pull request merged**
