### PR TITLE
updates to registration

### PR DESCRIPTION
**Pull request by bradymiller**
Thanks to @jesdynf 's newly created registration infrastructure, we can now send/store more data (added date and openemr version). Also the email address is now the identifier for the registration which makes most sense (the uuid has been removed).

### CODE REVIEW

**Comment by bradymiller** [comment]
Testing well and bringing into the codebase. This is part of a huge improvement in the registration cloud mechanism that @jesdynf did over the weekend (super cool stuff involving aws lamdba/dynamoDB).
Thank you @jesdynf !! The OpenEMR fans are going crazy :)

2DV

**Comment by stephenwaite** [comment]
Gonna save the org some dinero too !

**Comment by bradymiller** [comment]
yep, looking like gonna be at least 30% decrease in costs :)

**Comment by stephenwaite** [comment]
external-content duckduckgo com

**Pull request merged**
