### PR TITLE
Auto Styling with PHPCBF

### PR DESCRIPTION
**Pull request by TheToolbox**
In accordance with @bradymiller's desire to get all the big automatic code-style improvements done roughly all at once (see #928), the missing rules from PSR2 were added one by one. Roughly each commit below represents an added rule, to give some separation in case errors are discovered. One ruleset was able to be _mostly_ fixed, but required fixes to about 50 files. That commit (32b4f63) will likely need more scrutiny than the others, particularly because the files in question are difficult to parse.

The good news is that some very interesting code patterns were caught:
In several instances (interface/forms/misc_billing_options/report.php, interface/eRxSOAP.php, among others) had issues with switch statements, principally missing `break` statements and what appears to be accidental semicolons instead of colons. Hopefuly this means that we're proactively catching some edge-case bugs!
The most amusing pattern, however, was `<?php (400 spaces) } ?>`, making some control statements very difficult to parse until you scroll to discover these characters (or have text-wrap set up in your IDE).

I thank anyone and everyone in advance for being willing to pull it apart and make sure it should all work, or point out where I've done something wrong. I have run through superficial menus across open-emr, and haven't seen any glaring errors so far, so hopefully it shouldn't pose too much of an issue. If there is anything I can do to improve this PR, make it easier to work with, or otherwise reduce burden, please feel free to let me know.

### CODE REVIEW

**Comment by bradymiller** [comment]
awesome! this is like a megacommit X10 :)
Thanks for separating it into separate commits which makes it easier to digest. Let me do some code sleuthing and testing on this (note when bring it in, will actually bring it in as 1 commit to make easier for ongoing project to break trough this).

**Comment by bradymiller** [comment]
note to myself:
(will likely keep the commit with manual changes separate since this will be necessary for ongoing projects that need to merge into the codebase)

**Comment by TheToolbox** [comment]
I really really appreciate it. Squashing them into one commit when they come in seems like a great call as well. If there any spots you'd like me to take further look at, feel free to let me know!

**Comment by bradymiller** [comment]
Still some code sleuthing to do and testing to do(so far, things are looking really clean and this is forcing me to be an expert in PSR2 now that am literally seeing hundreds of code structure changes times 10 or so... :) ). Quick question on the commit with manual changes; when that happens, does the script shut down, or does it simply skip them and state that there were items that could not be fixed?

**Comment by TheToolbox** [comment]
Part of the reason that I added one rule at a time when running phpcbf is that there are some errors that it believes it can correct, but doesn't. It runs through the code in passes (up to 50), detecting errors and correcting them. Certain errors are sometimes created by the way that it fixes certain others, occasionally creating a loop, and leading it to kill off its attempts at 50 passes. This mostly happens when php is heavily mixed with html (and especially when control structures are embedded like `<?php if (1>0) { ?>`, as it has trouble judging how much indentation it actually has). When that happens, about 50% of the time phpcbf reports an error and skips the file, and the other 50% of the time it believes the file to be fixed on the 50th pass. To be sure, I ran phpcs over it afterwards, which always caught remaining errors.   phpcs's `-a` flag is really useful for fixing errors one-by-one, bringing up an interactive prompt that will let you check whether you fixed each specific issue.

**Comment by bradymiller** [comment]
@TheToolbox ,
Awesome job on this. Sanity code checks looked good and extensive testing went well with no hiccups. I just brought this into the codebase. Both you and @robertdown are basically now in the hall of fame for most files ever edited in a single commit :)
-brady

**Pull request closed without merging**
