### PR TITLE
mariadb fix

### PR DESCRIPTION
**Pull request by bradymiller**
This is to begin to try to fix a nasty mariadb issue. The most recent version of mariadb released 7/31/19 breaks OpenEMR (10.2, 10.3, and 10.4 are all affected). Basically the form_eye_neuro table is to big in size and breaks install and ugprade. Can see more details why this happened in mariadb here:
https://jira.mariadb.org/browse/MDEV-19292
This is a good summary from above link of the issue
"
Prior to MariaDB 10.2.26, 10.3.17, and 10.4.7, MariaDB didn't properly calculate the row sizes while executing DDL, so "unsafe" tables could be created, even with innodb_strict_mode=ON set. This was fixed by MDEV-19292. As a side effect, tables that could be created in previous versions may get rejected after the latest releases.
"
The goal here is to reduce the size by converting to text for the fields. Install is testing well, but am not sure yet of the impact on eye form use and also what happens when convert a field that may have NULL in it to a TEXT field.
@ophthal , do you see any obvious issues that these changes may cause to the eye form?
Goal is to get this fix in as soon as possible and then release patch 1 asap after that (need to rebuild the main packages with this patch; @jesdynf , note the cloud and appliance are special cases that are not affected by this bug since the all use mysql (not mariadb), so no need to rebuild packages for this (ie. the simple patch will suffice).

### CODE REVIEW

**Comment by ophthal** [comment]
Am I correct in reading your message that you wish to change only the varchar(X) fields to TEXT?
I used varchar(x) as I believed it should be “smaller”, faster and more efficient than TEXT fields.
There are no indexes on any of these fields either.

From a clinical perspective, most people really avoid neuro-ophthalmology…  
Far too complex and never reimbursed adequately.
On most encounters, all these varchar(x) values will just default to NULL.  

From the eye form perspective, making them all TEXT is fine.  
The other option is to make more tables.  More work, and probably not necessary.

If changing to TEXT is what Brady Miller and Monty Widenius <https://en.wikipedia.org/wiki/Michael_Widenius> (@gith) wants for OpenEMR and MariaDB, well then we should do it!

**Comment by bradymiller** [comment]
Thanks @ophthal for the info.
Testing is looking good so far. Plan to test on upgrade tomorrow and will then bring it into codebase (shooting for getting out patch 1 and new tar/zip/docker packages out over the weekend).

**Comment by bradymiller** [comment]
Testing well on upgrade, so bringing this in.

**Comment by bradymiller** [comment]
btw, thank you @robertdown for reporting this issue!

**Comment by robertdown** [comment]
The issue is not with VARCHAR vs TEXT but with allocation issues in how the table is created. While intuitively you’d think VARCHAR would be smaller, the number of columns seems to be the issue.

Could alternatively reduce all that content into 1 field that is TEXT and contains a JSON array.

**Comment by sjpadgett** [comment]
that's actually a good idea. I do it with audits in the portal. Usually just a couple lines of code to bust array into vars.
You could add the columns you want to index by then a column holding the json for the rest.
Wasn't there a similar problem with mysql? Thus the new tables.

**Pull request merged**
