### PR TITLE
consolidate attr_url function

### PR DESCRIPTION
**Pull request by bradymiller**

### CODE REVIEW

**Comment by mdsupport** [comment]
Since csrf and urls go together, maybe the function should be attr_url_csrf which will add csrf token as well - something enforced as part of standard.

**Comment by bradymiller** [comment]
hi @mdsupport ,
Then we'd have too many functions (we already kind of do), since csrf also sometimes gets just a attr or a js_url or a js_escape :)

**Comment by bradymiller** [comment]
btw, this is just meant to standardize the attr_url() call. mid-way through the security codebase walkthrough I created this function, and am just using in the places that were I used attr(urlencode()) prior to the creation of the attr_url() function. Since we are having more new developers participating in the project, just trying to keep the call standard.

**Comment by bradymiller** [comment]
testing well and gonna bring this in (got some more of this type of stuff to do in near future btw)

**Pull request merged**
