### PR TITLE
new feature - custom assets

### PR DESCRIPTION
**Pull request by matrix-amiel**
Hi.

Here I add option to inject custom js and css into any file in the system.
How to use - 
Add new file config/custom.yaml with same syntax as  config/config.yaml.
In that file you can add links to your custom assets.
I add new attribute called `loadInFile` for config file, This attribute enables to inject js and css only in specific file.
Example of custom.yaml
```
assets:
    custom:
        basePath: %webroot%/custom/public/
        script: js/fix_messages.js
        link: css/custom.css
        loadInFile: interface/main/messages/messages.php

```
Files js/fix_messages.js and css/custom.css will inject into interface/main/messages/messages.php

Thanks
Amiel

### CODE REVIEW

**Comment by mdsupport** [comment]
@matrix-amiel,
We ran into similar requirement earlier.  You can find #1695 using a parameter in yaml to override standard assets.  Would love to see your approach allow overriding the standard configuration as well.

Suggest we establish a generic class for asset config files (e.g. _clsAssetConfig_).  All config file related code from _Header_ can be moved to _clsAssetConfig_.  We can either have constructor accept an array of config file names or have a method (e.g. appendConfig) which will encapsulate the logic of adding to or overriding the standard asset configuration.  It is cool to have not only project-wide standard and custom assets but ability to add assets at the individual scripts level.

One of the challenges of _loadInFile_ would be lack of self documentation .. e.g. unless messages.php notes in comments that fix_messages.js will be injected by custom.yaml, a casual developer will need to discover that magic.  However if _clsAssetConfig_ provides method _tagAsset_ that maps html tags for individual assets, you can add a line in messages.php itself.  Now the developers will be able to invoke any asset anywhere in the script.  This will also address the challenge you will find if an asset like fix_messages.js is to be used in multiple scripts.

Finally, Header class can maintain current functionality as:
```
class Header extends clsAssetConfig {
...
}
```

**Comment by mdsupport** [comment]
Also suggest the custom file be moved to /custom directory to make it easier to save and restore custom code during version upgrades when directories are replaced.  We typically use path as java type file names .. e.g. we would place custom yaml in /custom/config.custom_assets.yaml.

**Comment by sjpadgett** [comment]
We do requires and includes for one off dependencies all the time. Same goes for javascript dependencies. Just add the dependency where it's needed.
I think the Header class was meant for normally used dependencies needed in most scripts and makes version control of dependencies much easier. I have nothing against a new asset class extended from header base but just don't know how much it would get used.
A ifCondition type to assets config would be useful but then one would need the evil eval function.
btw: I hate that everyone wants to dismiss this useful function. It has its place and can be safely used depending on where and how it's used. Many developers use and you may note that Smarty and Twig plugins use for situations like doing true/false evals or stop gap throwing an exception for bad code in template parsing. Note also that PHP docs give a warning on use case and not "O my gosh!, never use this anywhere".
lol, i've been wanting to do that rant on eval() for a long time:)

**Comment by matrix-amiel** [comment]
Hi friends.

The goal of this PR is to enable making small changes mainly cosmetic changes for opnemr customers without having to send pull request and add new global setting for minor personal issue. Such requirements were appeared in the forum every several weeks and I think my feature is good solution for  customize fixes. 
I don't think it's good idea to make big changes with this feature and sure not overwrite the exist assets, it's make the integration with new version of openemr very difficult.
I agree with Jerry that the new mechanism of  javascript dependencies is working well and is very  simple to add new library if we need. 
In my opinion the Header class is enough and not need extended.

Regarding the documentation.. agree there are a lot of magics in the code.. I would happy if will be wiki or website that contains explanations about all the feature and globals settings in openemr (the informations in current wiki is very limited), I think it's need be required in every merge of new feature, Of course to write it for the the exist features is huge work but let's beginning with the news.

**Comment by bradymiller** [comment]
hi @matrix-amiel ,

Would consider the following.
1. Use directory /custom/assets/
2. In that directory, create a file called /custom/assets/custom.yaml.example with your example code in it
3. In that directory, create a /custom/assets/README with quick instructions on using this
4. In that directory, create a /custom/assets/js and /custom/assets/css directory and use this place for storing your custom assets.

This then:
1. Makes is usable by others
2. Easy to carry customization during version upgrades

-brady

**Comment by matrix-amiel** [comment]
Done..

**Comment by bradymiller** [comment]
hi @matrix-amiel , Code looks great and I'm assuming it's testing well for you. Bringing into codebase. Thanks for the nicely documented feature! -brady

**Pull request merged**
