### PR TITLE
return empty array plus fix path to chart.js in eye form

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes couple other things in #5040

### CODE REVIEW

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
tenor99

**Comment by stephenwaite** [comment]
hi @jl1dvg, mind checking these fixes out?

**Comment by jl1dvg** [comment]
I’m sorry, I think I made a mistake loading the pull request, I just wanted to propose the change in the drug finder file. A thousand apologies

**Comment by stephenwaite** [comment]
no problemo @jl1dvg , easy to restore into your branch, feel free to ask for advice over on your PR #5071

**Comment by stephenwaite** [comment]
going to bring in @jl1dvg

**Comment by adunsulag** [comment]
@stephenwaite I think this broke the find_code_popup.php selector when a default codetype is not sent as a query parameter.  I noticed this in the CarePlan code selector as there is nothing in the $allowed_codes on Line 180 for this case.  I'm going to code up a fix by setting allowed_codes to be the same as the $code_types array codetypes when no default codetype is passed in. I wanted to double check I'm not breaking anything for this fix though if I make that change.

**Comment by stephenwaite** [comment]
Ok, sounds good, thank you.

**Pull request merged**
