### PR TITLE
Travis CI: PHP 8 parameter deprecation fix

### LINKED ISSUE #3101: php8 fun
### Describe the bug

image

PHP8-dev travis syntax checker is noting the following issues:
```
PHP Deprecated:  Required parameter $search_term follows optional parameter $form_code_types in ./custom/code_types.inc.php on line 835
PHP Deprecated:  Required parameter $patient_id follows optional parameter $proc_type in ./custom/qrda_functions.php on line 226
PHP Deprecated:  Required parameter $components follows optional parameter $send in ./interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php on line 469
PHP Deprecated:  Required parameter $list_id follows optional parameter $option_id in ./interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php on line 1302
PHP Deprecated:  Required parameter $htmlin follows optional parameter $pid in ./interface/billing/ub04_dispose.php on line 96
PHP Deprecated:  Required parameter $pid follows optional parameter $page in ./interface/eRx_xml.php on line 167
PHP Deprecated:  Required parameter $justify follows optional parameter $modifier in ./interface/forms/CAMOS/content_parser.php on line 41
PHP Deprecated:  Required parameter $provider follows optional parameter $authorized in ./src/Billing/BillingUtilities.php on line 1350
PHP Deprecated:  Required parameter $contentType follows optional parameter $formBody in ./src/Billing/EDI_270.php on line 878
PHP Deprecated:  Required parameter $auditvals follows optional parameter $type in ./portal/lib/appsql.class.php on line 139
PHP Deprecated:  Required parameter $doc_id follows optional parameter $patient_id in ./controllers/C_Document.class.php on line 376
PHP Deprecated:  Required parameter $to follows optional parameter $title in ./portal/lib/portal_pnotes.inc on line 220
PHP Deprecated:  Required parameter $to follows optional parameter $title in ./portal/lib/portal_mail.inc on line 314
```

More about the above deprecated message can be found in the PHP8 upgrade doc:
https://github.com/php/php-src/blob/master/UPGRADING#L145-L151

Feel free to fix them and push a PR to see if the PHP8-dev travis syntax checker has no more errors. Note OpenEMR does not work with PHP8-dev because some of OpenEMR's dependencies are breaking (am confident they will be fixed by upstream packages as PHP8 gets closer to release time, which I am guessing is many, many, many months away).

### PR DESCRIPTION
**Pull request by Hackinet**
Fixes  #3101

#### Short description of what this resolves:
This PR fixes the PHP8 syntax errors that Travis CI checker encounters.

#### Changes proposed in this pull request:

- Moved optional parameters after the required parameters in multiple functions.
- Modified the calls for each of those functions to reflect the same.

### CODE REVIEW

**Comment by Hackinet** [comment]
@bradymiller I need some help :)
I was able to fix the PHP 8 Syntax Issue.
image
However, it still fails on the last job(https://travis-ci.org/github/openemr/openemr/jobs/668533025).

```
FAILED - JOB SUMMARY
--------------------------------------------
PASSED - Start up the appropriate testing docker system to allow testing below
FAILED - Main OpenEMR Build
PASSED - CCDA OpenEMR Build
FAILED - Install and Configure OpenEMR for testing (remove registration modal on login and turn on api)
FAILED - Run Unit Tests
FAILED - Run E2e Tests
FAILED - Run Api Tests
```

- The `Unit`, `E2e` and `Api Tests` throw this message: 
```
Could not open input file: vendor/bin/phpunit
```

- The `Main OpenEMR Build` throws this message:
```
Deprecation Notice: Required parameter $path follows optional parameter $schema in phar:///home/travis/.phpenv/versions/master/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php:62
Deprecation Notice: Required parameter $path follows optional parameter $schema in phar:///home/travis/.phpenv/versions/master/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php:108
```
---------------------------------------------------------------------
It looks like, in the case of the `Main build`, the composer dependancy violates PHP 8 Syntax, but I am not sure why the tests throw `Could not open input file: vendor/bin/phpunit`. What do I do?

**Comment by bradymiller** [comment]
hi @Hackinet ,
The goal is to deal with the syntax issues (which you have done). The problem with the other test is that composer won't work because of:
```
- phpdocumentor/reflection-docblock 5.1.0 requires ext-filter ^7.1 -> the requested PHP extension filter has the wrong version (8.0.0-dev) installed.
```
This is not something we can address and will need to wait for upstream fixes/adjustments in that package.

**Comment by bradymiller** [comment]
btw nice job on ridding all those php8 issues and strategy looks good. I'll plan to do some extensive testing on this over next couple days.

**Comment by bradymiller** [comment]
Ended up pursuing a strategy that did not reorder the parameters, since less chance for bugs and to allow third party code to remain backward compatible:
https://github.com/openemr/openemr/pull/3422

**Comment by Hackinet** [comment]
Yep, saw it. Just wondering why I didn't think of that. Great idea @im-Amitto . :)

**Pull request closed without merging**
