### PR TITLE
Refactor: remove outdated code and adjusted grid system.

### PR DESCRIPTION
**Pull request by stu01509**
Remove outdated code and adjusted grid system.

Fixes #

#### Short description of what this resolves:
Remove outdated bootstrap class ` page-header`.
Adjust the bootstrap grid system.

### CODE REVIEW

**Comment by tywrenn** [comment]
Seems like there's a file conflict - please rebase

**Comment by stu01509** [comment]
@tywrenn  Resolve it.

**Comment by tywrenn** [comment]
@stu01509 Looks like Travis isn't happy

**Comment by stu01509** [comment]
Hi @tywrenn 

@bradymiller  sir told me Travis CI was just fixed by Jerry in the main codebase so wouldn't worry about that.

**Comment by bradymiller** [comment]
Looks like in addition to the php8 issue that can be ignored, there are a couple psr12 infractions :)

image

**Comment by tywrenn** [comment]
@bradymiller

**Comment by bradymiller** [comment]
@stu01509 , bringing in. thanks for the improvements! -brady

**Pull request merged**
