### PR TITLE
report to list patients' latest encounters

### LINKED ISSUE #5656: new report: list the latest encounters for each patient
### Describe the problem
staff would like to be able to see a list of encounters for all patients - either most recent or specifying a date range - for a specified provider or for all providers. Need to see time of the encounter, reason for the encounter, patiens' gender and generate a csv file of the results

### Describe the solution you'd like
 
a new report that shows the latest encounters for all patients with above data and generate csv file. access via menu 'reports/clients/Latest Encounters'

### PR DESCRIPTION
**Pull request by ruthkonyn**
Fixes #5656

#### Short description of what this resolves:
staff would like to be able to see a list of encounters for all patients - either most recent or specifying a date range - for a specified provider or for all providers

#### Changes proposed in this pull request:
a new report that shows the latest encounters for all patients. access via menu 'reports/clients/Latest Encounters'

### CODE REVIEW

**Comment by stephenwaite** [comment]
hi @ruthkonyn , re-running those failed tests, quite often they fail as flukes so we disregard

do you mind creating a feature request at https://github.com/openemr/openemr/issues/new/choose that will describe what this PR entails please? It can be short and sweet like you describe above, thank you

**Comment by stephenwaite** [comment]
nice, thank you @ruthkonyn , now you can edit your original post here and use  issue 5656 after the fixes # to tie this together please

**Comment by stephenwaite** [comment]
hi @ruthkonyn , this is pretty much the same report as found at Reports->Visits->Encounters so not sure if this is needed.

**Comment by ruthkonyn** [comment]
hi steve,
there are quite a few differences 
 - the new report only shows most recent encounter, visits->encounters shows all - although choosing 'new' works for this
 - the information displayed is different, e.g. the new one includes the reason for the encounter (important for our staff)
 - also important is to display the time of the encounter, which the new form does
 - the new form generates a csv of the data
 - the patient's gender is displayed

**Comment by ruthkonyn** [comment]
yes, I see your point. I've put that suggestion to our team. The new form is succinct in that it only shows the data our staff are interested in, but one could do something with options. I think defaults would be needed too so that people aren't having to choose options each time they generate a report.

**Pull request closed without merging**
