### PR TITLE
fix user settings - customized top pane patient search fix

### PR DESCRIPTION
**Pull request by matrix-drorgo**
I have fixed the bg when user select a customized top view pane . somehow the  $GLOBALS['default_top_pane']  gets the correct but when going to main screen there is no value there . so I have used the code from globals to collect this param again.

thanks
Dror G.

### CODE REVIEW

**Comment by bradymiller** [comment]
Hi Dror,

I think there is a systemic bug looming here where the user settings are not working in certain places. Related bug reports include:
https://sourceforge.net/p/openemr/bugs/451/
(note that this bug does not exist for Craig)

I also noted this strange behavior when trying to make the layout setting a per user setting:
https://github.com/openemr/openemr/blob/master/interface/main/main_screen.php#L106-L109

It would be much more ideal to fix the bug here than make a work around.

-brady

**Comment by matrix-drorgo** [comment]
Hi,
debugging the code I can see in globals that when enetering to open emr there is a requet for 
  if (!empty($_SESSION['authUserID']))  line 197 in globals . there problem is that there is no authUserID yet.

this what cause the problem for getting the user selected top screen.

I can move the logic I have written  to the bottom of the globals page or after calling to auth.inc in line 407.

if (!isset($ignoreAuth) || !$ignoreAuth) {
  include_once("$srcdir/auth.inc");
}

$gl_user = array();
if (!empty($_SESSION['authUserID'])) {
    ....
....
...


what do you think?
thanks.
 Dror G.

**Comment by bradymiller** [comment]
Thanks for the analysis. Would be nice to place a systemic fix in globals, but not sure if that will be possible (am pretty sure that calling auth.inc prior to setting the globals will break it). I suppose could separate out the user setting logic and migrate it below the include to auth.inc.
Any ideas Rod? @sunsetsystems

**Comment by bradymiller** [comment]
Possible solution:
At here:
https://github.com/openemr/openemr/blob/master/interface/globals.php#L197
If $_SESSION['authUserID'] is empty,
then try to see if $_POST['authUser'] is not empty,
if not empty, then collect the user id from the $_POST['authUser'] setting and use that.

**Comment by bradymiller** [comment]
To better explain, $_POST['authUser'] is the username from the login. So this will map to username sql column in the users sql table. Then the user id is the id sql column.

**Comment by matrix-drorgo** [comment]
o.k. I used your logic.It works. thanks.

**Comment by bradymiller** [comment]
Hi Dror,

I just committed a fix for this to the codebase(tested well and was simple, so I committed it without further code review):
https://github.com/openemr/openemr/commit/4ecb7957018fe04516a5659e27c5961e5cc84946
(btw, I meant to make you the commit author, but I messed up; I haven't had enough coffee today)

-brady

**Pull request closed without merging**
