### PR TITLE
Login screen improvements and added favicon

### PR DESCRIPTION
**Pull request by bradymiller**
Based on very nice work by Ray to incorporate the new logo, a favicon, and modernize the login screen!

### CODE REVIEW

**Comment by bradymiller** [comment]
To keep the current flexibility of the login screen (for custom logos and titles etc), check out these flags in globals->Appearance:
Show Title on Login	
Show Extra Logo on Login	
Show Mini Logo 1	
Show Mini Logo 2

**Comment by bradymiller** [comment]
Can test this on this up for grabs demo:
http://www.open-emr.org/wiki/index.php/Development_Demo#192.168.1.131

**Comment by robertdown** [comment]
Think we should go ahead and remove all the tables from this page since it is being updated and move to a bootstrap-based design meaning `divs` not `tables`. 

Also, I don't like adding a `png` file just as a background, we should use CSS-based gradients, no need to add bloat to the codebase.

Also, I think we need a default login css but also standardize the classes so that the login page can be fully customized via theme styles.

I dislike forcing the logo on the login screen, I know we do it now, but, shouldn't a user be able to whitelabel the login page? I can't think of anywhere else we forcibly display the OpenEMR logo.

Lastly, I think we should finalize the logo before we make this change.

My 2 cents.

**Comment by bradymiller** [comment]
Hi Robert,
I agree with your points but:
The OpenEMR 5.0.0 release is very imminent. This was just a quick modernization by Ray to get the logo and favicon in there. If the goal is to finalize a logo before the release, then it needs to be done asap. I am guessing that like the website, the logo(especially the color schemes) will be changing a couple times over the next year as we find the best one. I'd hate to have to ship OpenEMR 5.0.0 with the old logo and login page because of the delay in finalizing the logo.
-brady

**Comment by robertdown** [comment]
Let's ship 5.0.0 with this PR and we can work on the logo without adding the pressure of making it a blocking item.

**Comment by bradymiller** [comment]
That's a bit annoying. I did a squash/merge from github and instead of giving authorship to the original commit (Ray), it gave it to me (the last commit). Sorry Ray; you were supposed to be the author of the commit. Lesson learned.

**Comment by bradymiller** [comment]
ok, fixed it by basically reverting the commit and then adding it again with the right author.

**Pull request merged**
