### PR TITLE
.inc files migration to .inc.php

### LINKED ISSUE #5894: change .inc scripts to .inc.php scripts
.inc is not specific for php, which will make it difficult to play nicely with source code editors that support different coding languages (ie. VS Code).
Plan:
Migrate .inc to .inc.php scripts
Leave a stub in original .inc that runs the .inc.php script (will place in header when safe to remove this since is specific to script; ie. 2023, 2024, never )

### PR DESCRIPTION
**Pull request by bradymiller**
fixes #5894

### CODE REVIEW

**Comment by bradymiller** [comment]
This ended up being a bit more work than I thought it was going to be :)

**Comment by stephenwaite** [comment]
birdofparadise_agadvgeaaii3jgq

**Comment by bradymiller** [comment]
testing well :)
gonna bring this in soon since high chance for tough merging issues if sit to long on this

**Comment by bradymiller** [comment]
time to pull the trigger :)

**Comment by stephenwaite** [comment]
Screenshot from 2022-11-01 15-34-22

**Comment by sunsetsystems** [comment]
567 files, wow. :)

**Pull request merged**
