### PR TITLE
fix ccda import dupl category

### LINKED ISSUE #6038: CDA Patient import to chart fails.
### Describe the bug
If I import 8 rapidly one after the other. I get this error message.
image

Reported by @juggernautsei 
Error occurs because if empty encounters(section nulled) in doc or duplicate category for calendar. Though I dupl check it looks like if a cat isn't resolved in doc import it fails.

### Client configuration

- Browser:
- OpenEMR version: master, v7.0.0 (2)
- Operating system:

### PR DESCRIPTION
**Pull request by sjpadgett**
improved appt event category create

Fixes #6038

### CODE REVIEW

**Comment by sjpadgett** [comment]
@juggernautsei This should fix your issue

**Comment by sjpadgett** [comment]
@bradymiller I put a couple cool pain questionnaires I'm working up on https://three.openemr.io/a/openemr/interface/login/login.php?site=default
if ya want to look at.

**Comment by bradymiller** [comment]
@sjpadgett , Looks like i missed it; if reupload, let me know and i'll check it out :) Note i just migrated over the ubuntu dev demo to another one (it uses node 18):https://www.open-emr.org/wiki/index.php/Development_Demo#Alternate_Demo_.28Ubuntu_22.04_-_uses_php_8.1.29

**Comment by sjpadgett** [comment]
@bradymiller https://six.openemr.io/openemr/interface/login/login.php?site=default
in encounter New Questionnaire form and select from Questionnaire Repository select2
Still working but okay so far.

**Comment by bradymiller** [comment]
@sjpadgett , very cool stuff! What is the difference between Save Current and Register New?

**Comment by sjpadgett** [comment]
Save Current will just do a one time form to the same encounter. Register New will register to form registry as a new encounter form to be available from Questionnaire menu.

**Comment by sjpadgett** [comment]
They are available in portal also.

**Comment by bradymiller** [comment]
On prior testing was able to Register it as new and then go through the portal dashboard stuff to bring it over as a form from the portal. I ignored the Save Current then since didn't allow me to use it in the portal. It all makes sense now. very neat!

**Comment by bradymiller** [comment]
dance-bear

**Comment by sjpadgett** [comment]
Thanks for looking at @bradymiller 
I'm not getting a lot of feedback on forum which is a good thing I guess. Still I need it to stop me from doing crazy stuff:)
Just to clarify, registering the form in encounter doesn't automatically make available to portal. For that you still have to create a template in Dashboard where I've added tools to do automatically when you import the FHIR Questionnaire.

I'm now on a mission to make reminders and notifications as easy as possible for user. Sherwin has done a lot of work on this plus my stuff. I'm hoping for a combination of the two efforts. The problem mostly is vendor signup can be tricky.

**Pull request merged**
