### PR TITLE
bug-fix: new encounter cancel not returning in tabs ui.

### PR DESCRIPTION
**Pull request by sjpadgett**
Also made form appearance consistent by adding class styles to selects and inputs.

### CODE REVIEW

**Comment by sjpadgett** [comment]
Fix return to blank dialog if $GLOBALS['sql_string_no_show_screen'] is in effect. Return now goes straight to history after save. For some reason toencounter() is sometimes not in scope for redirect(in frames, resides in main_title.php) so I change to use left_nav proxy loadframe.
This PR is companion to PR https://github.com/openemr/openemr/pull/1323 and issue #1321
@eyalvo-matrix I'm sure you will want to note this change.

**Comment by bradymiller** [comment]
Code looks great and if tests well for you, then rec bringing in.
(btw, I started working on removing fancybox from the user facility settings stuff; hopefully will have PR on it this weekend)

**Comment by sjpadgett** [comment]
Okay, let me know if I can help. I'm taking a little break from fancybox and have been looking at FHIR. I have a couple thoughts I'm looking at and am anxious to explore... Will do custom templates next, maybe this weekend...

**Comment by bradymiller** [comment]
Yep, you've definitely earned a break from fancybox :)
Looking very forward to your FHIR magic.

**Pull request merged**
