### PR TITLE
- db fix

### PR DESCRIPTION
**Pull request by sjpadgett**
quick fix

### CODE REVIEW

**Comment by sjpadgett** [comment]
The patient report never rendered PDF to patient report. I went back to pre v5.0. 
Pdf documents will fall through to image.  So, i'm not adding the logic but did fix some php7.4 errors/warnings.

**Comment by stephenwaite** [comment]
so @juggernautsei , looks like this would be an enhancement referring to your [community post](https://community.open-emr.org/t/report-document-attachment-broken/15627?u=stephenwaite)

**Comment by juggernautsei** [comment]
I have a 4.1 system that I support. In the reports section, the documents don't show at all.

**Comment by sjpadgett** [comment]
@juggernautsei @stephenwaite 
Decided instead of patching out that last mime type doc catch which, was/is for an imageMagic render btw, to at least let user know the available doc that won't get rendered in report. It looks like images and text docs will populate in this part of report.
image

**Comment by sjpadgett** [comment]
the end
jerry out!

**Pull request merged**
