### PR TITLE
Changed Add Facility checkboxes to new UI following Edit Facility

### PR DESCRIPTION
**Pull request by skshahnawaz**
Fixes 

> #3065 

#### Short description of what this resolves:
This resolves the UI consistency issue for Toggle elements in Facility Add/Edit

#### Changes proposed in this pull request:

- Changed the checkboxes in "Add Facility" to new toggle buttons as per the "Edit Facility" form
Screenshot 2020-03-04 at 2 57 02 AM
Screenshot 2020-03-04 at 2 57 08 AM

### CODE REVIEW

**Comment by skshahnawaz** [comment]
> Hey @skshahnawaz, it looks great but I think you did't mean to add `.DS_store` files in the commit.

Sorry I had forgotten that. Now I have removed that .DS_Store. Please review @im-Amitto

**Comment by im-Amitto** [comment]
@skshahnawaz Can you verify if all .DS_Store has been removed?
@bradymiller Should be add `.DS_Store` to `.gitignore`?

**Comment by skshahnawaz** [comment]
> @skshahnawaz Can you verify if all .DS_Store has been removed?
> @bradymiller Should be add `.DS_Store` to `.gitignore`?

Now I removed all the .DS_Store files. Please check

**Comment by im-Amitto** [comment]
@skshahnawaz All are gone now :smile:.
It's a good practice to squash the commits doing the same thing.

**Comment by skshahnawaz** [comment]
> @skshahnawaz All are gone now 😄.
> It's a good practice to squash the commits doing the same thing.

Yeah thanks. I'll remember from next time👍

**Comment by im-Amitto** [comment]
@skshahnawaz You can squash your commits at any point of time and their are multiple ways though i like terminal. For ex. if you wanna squash all your commits on this PR into one just follow this : https://www.loom.com/share/eff09fee82be40499b542dab57103d2a

**Comment by skshahnawaz** [comment]
> @skshahnawaz You can squash your commits at any point of time and their are multiple ways though i like terminal. For ex. if you wanna squash all your commits on this PR into one just follow this : https://www.loom.com/share/eff09fee82be40499b542dab57103d2a

okay shall I do now?

**Comment by im-Amitto** [comment]
@skshahnawaz it's your call :smile:

**Comment by skshahnawaz** [comment]
> @skshahnawaz it's your call 😄

I did the squash. Thanks for your tutorial. Please check

**Comment by bradymiller** [comment]
hi @skshahnawaz , nice!
1. Also need to add the fancy toggle to the 'Primary Business Entity' toggle
2. Feel free to add .DS_Store to .gitignore to avoid pain in future
3. Would revert the changes in composer.json (unless those changes are enforcing good practice standards)
(btw @im-Amitto , very nice use of video to detail a complicated process)

**Comment by skshahnawaz** [comment]
Sure! I am working on it. Will commit soon

**Comment by skshahnawaz** [comment]
@bradymiller @im-Amitto please check. I made the following changes :-

- added fancy toggle to "Primary Business Entity"
- added .DS_Store to .gitignore


Screenshot 2020-03-04 at 9 43 55 PM

**Comment by skshahnawaz** [comment]
Also , the edits in composer.json are due to indentation correction. The code was not properly indented. So, I also indented it properly

**Comment by bradymiller** [comment]
hi @skshahnawaz , Code looks good and testing well so bringing into codebase. Thanks for the improvements and congrats on your first OpenEMR commit!

If you are looking for another issue to work on that is related to this, then would consider making both of these modals consistent in appearance, styling, and responsive behavior (note the Add new modal does a much better job supporting responsive than the Edit modal). It's just odd for 2 forms that are requesting the same data fields to look different.

**Comment by bradymiller** [comment]
This is odd. Github made me author on this commit for some reason. I'm gonna fixit by reverting it and then bringing it back in with correct author.

**Comment by skshahnawaz** [comment]
Yes , please

**Comment by bradymiller** [comment]
hi @skshahnawaz , I sorted out the author issue and the commit now gives you authorship. If you are interested in the issue to make both the Add and Edit modals to be consistent, then recommend creating an issue for it (and then I'll assign it to you). thanks! -brady

**Comment by skshahnawaz** [comment]
> hi @skshahnawaz , I sorted out the author issue and the commit now gives you authorship. If you are interested in the issue to make both the Add and Edit modals to be consistent, then recommend creating an issue for it (and then I'll assign it to you). thanks! -brady

Yeah , I am creating an issue for that

**Pull request merged**
