### PR TITLE
Bug Fixes Amendments

### LINKED ISSUE #5581: adding amendment from dashboard bug
### Describe the bug

https://community.open-emr.org/t/adding-amendment-no-longer-works-in-v6-1/18701/2

### To Reproduce

1. Open a chart
2. Click on Amendments from Dashboard
Screenshot from 2022-07-13 11-16-51
3. Click add amendment
Screenshot from 2022-07-13 11-15-59

5. See error

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### LINKED ISSUE #5597: Fatal Error: Argument 1 passed to getPatientFullNameAsString
### Describe the bug

 I was looking through my error log and noticed this fatal error in the system. 

      [Tue Jul 12 09:01:29.303679 2022] [php7:error] [pid 14487] [client 17.1.2.18:55055] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to getPatientFullNameAsString() must be of the type int, null given, called in /var/www/html/hb600/src/OeUI/OemrUI.php on line 76 and defined in /var/www/html/hb600/library/patient.inc:785\nStack trace:\n#0 /var/www/html/hb600/src/OeUI/OemrUI.php(76): getPatientFullNameAsString()\n#1 /var/www/html/hb600/interface/patient_file/transaction/add_transaction.php(466): OpenEMR\\OeUI\\OemrUI->__construct()\n#2 {main}\n  thrown in /var/www/html/hb600/library/patient.inc on line 785, referer: https://e.healthbrigade.org/interface/main/messages/messages.php?showall=no&sortby=pnotes.date&sortorder=desc&begin=0&task=edit&noteid=124740&form_active=1

### To Reproduce
don't know how to reproduce the error

1. Add a '....'

### Client configuration

- Browser: Firefox
- OpenEMR version: 6.1.1
- Operating system: ubuntu 20.04LTS

### LINKED ISSUE #5601: Header falsely report error for missing no_* includes
### Describe the bug
The error explains most of it:
[14-Jul-2022 10:12:58 America/New_York] [2022-07-14T10:12:58.443338-04:00] OpenEMR.ERROR: Not all selected assets were included in header {"selectedAssets":["no_textformat"],"foundAssets":["jquery","bootstrap","utility","main-theme","compact-theme","dialog"]} []

The service will exclude the dependency thus the result dependency includes array count will not match the requested.

### PR DESCRIPTION
**Pull request by sjpadgett**
- converted to render in tab instead of dialog.
- remove rx_modal class reference in widget

Fixes #5581
Fixes #5597 
Fixes #5601

#### Short description of what this resolves:
Originally Amendments were a dialog. After twig conversion the class event reference to call modal wasn't in scope any longer.
Converted to render in tab as other widget do.

### CODE REVIEW

**Review by stephenwaite — APPROVED** [review]
excited_elephant

**Comment by sjpadgett** [comment]
@stephenwaite Am I missing anything else bug wise I can fix in this PR?

**Comment by stephenwaite** [comment]
southpark_cheering

**Comment by bradymiller** [comment]
118382341-53d9d600-b5c2-11eb-8b7e-220bbab8468a

**Pull request merged**
