### PR TITLE
Fix #3409: multiple fee sheet bug

### LINKED ISSUE #3409: Multiple fee-sheet bug
### Describe the bug

Multiple fee-sheet bugs, 

image

https://i.imgur.com/DJER21F.mp4

### To Reproduce

1. Open Encounter tab
2. Click Navbar Fees > Payment
3. Click Navbar Fees > Fee Sheet
4. Go to the summary tab
5. Click Click Administrative > Fee Sheet
6. See the two Fee Sheet

### Client configuration

- Browser: Firefox 75
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by stu01509**
Fixes #3409

#### Short description of what this resolves:
Fixed multiple fee sheet bug.
https://i.imgur.com/c8qTgsI.mp4

### CODE REVIEW

**Comment by stu01509** [comment]
Hi @bradymiller and @stephenwaite 

In here I used ` top.execute` variables to save the Fee Sheet open status, Is it a good idea? If yes I would start to build completely function to manage encounter tabs and fix #3382.

Also, could you guide me,  which type tabs need to prevent multiple open, Thanks :)

**Comment by stephenwaite** [comment]
hi @stu01509, nice, looks good i think but am pretty novice with js so hopefully @bradymiller will give the go ahead

would say all tabs except procedure orders would be silly to have multiples, however giving the local admin the ability to override is important and would encourage creating a global in `Features` category

**Comment by stu01509** [comment]
Hi @stephenwaite 

Thanks for your explanation. It sounds like a big plan, If possible we can create a new section or page to provide the user to configuration setting their tabs. Am I right?

**Comment by stephenwaite** [comment]
hi @stu01509 , it's not too bad, the globals are already well defined in `library/globals.inc.php`

**Comment by bradymiller** [comment]
hi @stu01509 and @stephenwaite ,
I'd consider making this an option in the forms registry (then user can support any form with this behavior):
image

**Comment by stu01509** [comment]
Hello @bradymiller  and @stephenwaite 

Thanks for your suggestion, It seems a good place to provide the user to configure their tabs, I will start to develop global tabs setting feature after this issue fix 😁.

**Comment by tywrenn** [comment]
This is being closed due to the branch somehow disappearing.

**Pull request closed without merging**
