### PR TITLE
Dynamic Finder AJAX Fix

### PR DESCRIPTION
**Pull request by psoas**
Bug:  
AJAX Error when searching all fields when using search box at top right of main (not patient finder).  It was created when multiple address datatype was introduced to the demographic layout form.

I'm surprised no one caught this minor bug of a big core feature before 7.0 release.  This might warrant a quick patch to the release.

Really simple fix.

### CODE REVIEW

**Comment by stephenwaite** [comment]
nice fix @psoas

**Review by stephenwaite — APPROVED** [review]

**Comment by stephenwaite** [comment]
fixes #5630

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
2DV-2

**Comment by stephenwaite** [comment]
bringing into master and will push to rel-700 for 1st patch, great job @psoas

**Pull request merged**
