### PR TITLE
Minor fixes for internationalization of new style of patient file

### PR DESCRIPTION
**Pull request by matrix-amiel**
Hi.

I send here 2 fixes we have found in the new style of patient file in our language.
1. rtl issue.
2. We have problem the translation of 'Dashboard', the meaning of dashboard is very general and not match  in Hebrew. I suggest to replace the title to 'Medical record' I think is more  understandable.   

Thanks

Amiel.

### CODE REVIEW

**Comment by zbig01** [comment]
@matrix-amiel 
לוח מחוונים רפואי
http://context.reverso.net/translation/english-hebrew/dashboard
Does this convey the meaning adequately?

**Comment by bradymiller** [comment]
hi @matrix-amiel (and @zbig01) ,
This type of thing can also be fixed on the translation side of things (ie. keep Dashboard and translate it to whatever makes the most sense in the pertinent language).
-brady

**Comment by matrix-amiel** [comment]
@bradymiller @zbig01 
Thank you, I thought on this solution but I think is problematic to translate 'Dashboard' to word that not match exact. because 'Dashboard' can be found with another meaning in another screens and this can create conflicts.. this is very general word.. I think we need select title that describes more exact the content of screen.
Or to create constant like - Dashboard{patient file}    

Would you agree with me?

**Comment by bradymiller** [comment]
Hi @matrix-amiel ,
Good point. Would rec using the following constant then:
```
Dashboard{{patient file}}
```
(@zbig01, those brackets are basically comments to translators and also allow duplicate words with different meanings; they do not get shown on the output)

**Comment by bradymiller** [comment]
btw, I will keep my fingers crossed that those brackets do not blow up the menu engine :)

**Comment by matrix-amiel** [comment]
Good! I'm testing it now..

**Comment by matrix-amiel** [comment]
Fixed.
Working well.

**Comment by bradymiller** [comment]
hi @matrix-amiel , looks good and will bring this in. Thanks for the improvement! -brady

**Pull request merged**
