### PR TITLE
Appointments and Flow Board issues

### PR DESCRIPTION
**Pull request by sjpadgett**
1. add edit event fails when save edited single provider recurring events for future and current. sql insert fails form_provider is array.
2. ensure provider is user.
3. ensure while loop doesn't race.

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller Notice the statement `$occurance = &__increment($nd, $nm, $ny, $rfreq, $rtype);`.
There are several places in codebase where the library function &__increment() has been formatted to =&  __increment(). Seems PHP is not too bothered by this but maybe the future not so. & is a reserved operator so i'm troubled by its use in function define. Am I missing something?

**Comment by bradymiller** [comment]
hi @epsdky ,
I was hoping to get your thoughts on @sjpadgett 's comments above regarding `&` use and whether he is missing something.
thanks,
-brady

**Comment by epsdky** [comment]
( @sjpadgett ) So the code on the Alpine/PHP7.0 install is older than about 2-3 weeks ago? (That is when the checkEvent function went into the codebase).

**Comment by sjpadgett** [comment]
Yep, it is. led to believe otherwise :) Still need to figure out how they were able to get here. May have something to do with single provider recurring event save problem that I need to commit fix for. Thanks

**Comment by sjpadgett** [comment]
Looks to be April 12 file dates. Here is PR for save issue. https://github.com/openemr/openemr/pull/1638

**Comment by bradymiller** [comment]
hi @epsdky , Thanks for reviewing the code and catching the issue! -brady

**Comment by bradymiller** [comment]
hi @sjpadgett ,

Let me know if you need guidance on dockers workflows. Can see if there are updated dockers here:
https://hub.docker.com/r/openemr/openemr/tags/

I am assuming Alpine/PHP7.0 code is the 5.0.1 docker, which we only update when a patch goes out(it basically takes code from the rel-501 branch). Note you need to do a `docker pull openemr/openemr:5.0.1` to get the most recent docker.

-brady

**Pull request merged**
