### PR TITLE
New Sass tool for developing css for LTR and RTL languages easily

### PR DESCRIPTION
**Pull request by matrix-amiel**
Hi.

As I have suggested in my issue #1877,  I made refactor of the way we developing css for RTL languages. Instead to overwrite every style for RTL we can do it using  advanced Sass tools. using [Directional-SCSS](https://github.com/tysonmatanich/directional-scss) project we get collection of function and variables for sass files. 
Here I removed all the duplicate settings and use variables instead (default of variables is LTR) -
For example instead -
```
In the  - openemr/interface/themes/core/patient/notes.scss
#pnotes #namecontainer_pnotes {
    float:left;
}
And in rtl.scss
#pnotes #namecontainer_pnotes {
    float:right;
}
```
Simple - 
```
In the  - openemr/interface/themes/core/patient/notes.scss
#pnotes #namecontainer_pnotes {
    float:$left;
}
```
As I had agreed with Daniel all the settings are overwrite inline css I left in the Sass mixin and it will be loaded only in rtl file.

@d3sandoval I would need your help to finish this PR.. we need to merge it into glup tasks. we need to change the $dir to 'rtl' and to load the mixin rtl_style (in the openemr/interface/themes/rtl.scss)  in the end of every css file.

Thank you

Amiel.

### CODE REVIEW

**Comment by matrix-amiel** [comment]
Until the development in the glup tasks this feature can't be tested..

**Comment by d3sandoval** [comment]
@matrix-amiel looking at this now. Will submit a PR to your branch with updates to the gulp tasks :)

**Comment by matrix-amiel** [comment]
Merged.
Looks good! amazing! 
Thank you @d3sandoval

**Comment by matrix-amiel** [comment]
Tested. and works well for me.

**Comment by bradymiller** [comment]
Looks great. To fix the package-lock.json conflict, I had to rebase this to most recent codebase, remove the package-lock.json file and then rebuild it. Here's the PR where I did this:
https://github.com/openemr/openemr/pull/1904
(so going to close this PR and then merge in the code from that PR which also includes all the other commits in this PR)

**Comment by bradymiller** [comment]
Theses commit are now in the codebase. Thank you @matrix-amiel and @d3sandoval !!!!
(btw, @d3sandoval, just let me know if I did something wrong in removing the package-lock.json and rebuilding it in order to fix the merge conflict)

**Pull request closed without merging**
