### PR TITLE
couple quick minor fontawesome fixes

### PR DESCRIPTION
**Pull request by bradymiller**

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @tywrenn and @stu01509 , Just fixed a couple main icons that noted missing.

**Comment by stu01509** [comment]
Hi @bradymiller 

You're amazingly fast! I just try to find the lost icon. 💯

**Comment by bradymiller** [comment]
And looks like travis is down; so don't even need to wait for that to happen. So gonna bring this in. Looks like there is a refresh icon missing at top of calendar with the empty blue button.

**Comment by bradymiller** [comment]
image

**Comment by bradymiller** [comment]
I'll let others take on the other missing icons. Gonna review/test some more PRs :)

**Comment by stu01509** [comment]
I am looking forward to finding the lost icon and sending the PR 😁

**Pull request merged**
