### PR TITLE
Fix Zend module SQL upgrade

### LINKED ISSUE #6808: Zend module installer upgrade broken for custom modules
### Describe the bug
Several PHP8 errors and missing pathing for sql upgrade checks for custom module.

### PR DESCRIPTION
**Pull request by sjpadgett**
add custom module pathing

Fixes #6808 

#### Short description of what this resolves:
Missing pathing for SQL upgrade checks for custom module.

#### Changes proposed in this pull request:
Fix missing pathing for SQL upgrade checks for custom module.

### CODE REVIEW

**Comment by sjpadgett** [comment]
image

**Comment by stephenwaite** [comment]
hi @sjpadgett, noticed that the `sqlUpgradeService` is looking for the progress status js when was playing around with the PatientFilter zend module.
Screenshot from 2023-08-29 17-09-41

**Comment by sjpadgett** [comment]
This is really weird! allows having a sql dir path for version and version upgrade but not the actual require for the sql script!
Almost not practical as is.

**Review by adunsulag — APPROVED** [review]

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
dance-bear

**Pull request merged**
