### PR TITLE
Doctrine removal (since does not appear to be supporting PHP8 anytime soon)

### PR DESCRIPTION
**Pull request by bradymiller**
This may be a bit controversial, but with doctrine not supporting PHP8 now or in near future, it is going to indefinitely delay the release of OpenEMR 6.0.0 (ie. not only do we need to wait for it to release, but we need to wait for it to even test PHP8 in OpenEMR, of which there are now a huge amount of warnings to fix). At this point, 6.0.0 could be ready for release in about 4 weeks and just seems odd that a doctrine dependency (which is only minimally used) should delay this.

Still testing.

Thoughts?

### CODE REVIEW

**Comment by bradymiller** [comment]
bug:
registration not working as expected (getting error when submitting email address)

**Comment by bradymiller** [comment]
Bug:
v_acl is not updating on upgrade

**Comment by sjpadgett** [comment]
I have oeHttp token persist cache figured out so will post PR next chance I get so,...

**Comment by bradymiller** [comment]
This is getting close. Plan here is to have the remove doctrine in one commit, so won't be tough to bring it back if wish in future. At that point would be on doctrine ORM 3 likely, so would then need to follow that with the changes that upgrade doctrine code in this PR: https://github.com/openemr/openemr/pull/3719

**Comment by stephenwaite** [comment]
einstein

**Comment by bradymiller** [comment]
Testing well and bringing this in. Fare thee well doctrine. Hopefully we will see you again when you support PHP8.

**Pull request merged**
