### PR TITLE
bye bye jquery 1.7.2, 1.9.1, 1.10.2 and jquery-ui 1.10.4, 1.11.4

### PR DESCRIPTION
**Pull request by bradymiller**
Part of following issue: https://github.com/openemr/openemr/issues/842

### CODE REVIEW

**Comment by bradymiller** [comment]
We are now down to only one version of jquery and jquery-ui :)

**Comment by sjpadgett** [comment]
Great @bradymiller , certainly a braver man than me...

I'd recommend turning on User Debug as default for 503 dev cycle. It may make any compat issue a little more glaring.

**Comment by bradymiller** [comment]
testing well and bringing into codebase.

Next goal is to rid the codebase of jquery-UI (this is basically a dead project and am guessing that newer versions of jquery no longer work with jquery-UI); first step will be to identify places of use.

**Comment by sjpadgett** [comment]
All over. dialogs and help modals use for resize so that would need a new lib.

**Comment by bradymiller** [comment]
jquery-ui hasn't released anything for 3 years. I'll plan to take stock of jquery-ui uses and see what can be done (for example, use bootstrap instead). See this more of a longer term project since there will be a day in the future when jquery will no longer work with jquery-ui (and then, of course, at that time we'll get to deal with migrating jquery to js/components. Would there be another current lib that could be used for the main dialogs/modals/resize?

**Comment by sjpadgett** [comment]
Not sure but the only one I think is really useful is drag. I could be okay with losing resize. I think zbig was reluctant to add to helps so he may be okay with losing as well.

**Comment by sjpadgett** [comment]
Also BS4 has a nice class to open modals full length from top, sides and bottom.

**Pull request merged**
