### PR TITLE
Smarty2 to smarty3[pr1] phpgacl admin (ongoing Testing)

### PR DESCRIPTION
**Pull request by thesmallstar**
I am still testing this, as said by @bradymiller there was not much to do in phpgacl module but I tried to keep the code up to date. 

After testing will move to other smarty2 modules. 

below by bradymiller:
Up For Grabs demo for this PR is here: https://www.open-emr.org/wiki/index.php/Development_Demo#Beta_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by bradymiller** [comment]
Up For Grabs demo for this PR is here: https://www.open-emr.org/wiki/index.php/Development_Demo#Beta_-_Up_For_Grabs_Demo
(this demo updates daily at around midnight pacific time using the code in this PR)

**Comment by thesmallstar** [comment]
@bradymiller  I have tested the PHPgacl module, everything looks good. Code is now up to date with smarty3. Next, I will proceed and change core OpenEMR and then calendar :)

**Comment by bradymiller** [comment]
nice @thesmallstar ! Guessing core will be more challenging, but will keep :crossed_fingers: and :pray:

**Comment by bradymiller** [comment]
And, of course the OpenEMR fans need to weigh in:

2DV

**Comment by bradymiller** [comment]
Note there is a "crutch" that can be used to allow php in smarty3, which could use for the calendar to allow it to continue to limp along :)
https://www.smarty.net/docs/en/bc.tpl

**Comment by thesmallstar** [comment]
@bradymiller sorry for a  long break, I first had a bedridden fever and then pending college assignments.
Back now :D

**Comment by bradymiller** [comment]
Priorities:
1. Health
2. Grades
3. GSoC
:)

**Comment by stu01509** [comment]
> @bradymiller sorry for a long break, I first had a bedridden fever and then pending college assignments.
> Back now :D

Take care, bro :)

**Comment by prondubuisi** [comment]
> Priorities:
> 
> 1. Health
> 2. Grades
> 3. GSoC
> 
> :)

Agreed! Lol

**Comment by bradymiller** [comment]
bump

**Comment by bradymiller** [comment]
bump infinity

**Comment by bradymiller** [comment]
bump infinity infinity

**Comment by stephenwaite** [comment]
bumpity

**Comment by bradymiller** [comment]
bump

**Comment by stephenwaite** [comment]
Screenshot from 2021-03-10 13-06-10

**Pull request closed without merging**
