### PR TITLE
FHIR Medication Resource

### PR DESCRIPTION
**Pull request by silvistershebin**
#### Short description:
FHIR Medication Resource - GET methods

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @silvistershebin , To clarify, is this meant to get medications of patients? Or is this meant to just get medications from a dispensary?

**Comment by silvistershebin** [comment]
Hi @bradymiller Sir, as per the specifications given by fhir for Medication Resource (https://www.hl7.org/fhir/medication.html), it is just to get the medications available from the dispensary.

**Comment by sjpadgett** [comment]
@silvistershebin 
I suppose this is on me. I assumed we were talking patient centric resources and not inventory. So this should be a MedicationStatement. 
FHIR has an entire medication module which we'd probably would benefit from most all the resources but, for now, we need to concentrate on patient prescribed and medications list. 

Recommend cloning this resource as a starting point for the MedicationStatement then submit a new PR. We'll go ahead and keep this resource for those practices that run inventory.

**Comment by silvistershebin** [comment]
Okay no issues, I'll start working on the MedicationStatement resource. Maybe we'll need this Medication resource as a Reference for the 'medicationReference' attribute of MedicationStatement. I'll check that out.

**Comment by bradymiller** [comment]
hi @silvistershebin , Code looks good and bringing this into codebase. Thanks for the improvements! -brady

**Pull request merged**
