### PR TITLE
edi 270 batch eligibilty fixes

### PR DESCRIPTION
**Pull request by stephenwaite**
segment counts were off :|

### CODE REVIEW

**Comment by stephenwaite** [comment]
will probably be working on this for a little bit to help https://community.open-emr.org/t/eligibility-checks-clearinghouses/9742/22?u=stephenwaite :)

**Comment by bradymiller** [comment]
hi @stephenwaite , Just let me know when you want this PR in, and then I'll bring it in. -brady

**Comment by stephenwaite** [comment]
ok, it's testing fine, good to bring in and i'll just start other pulls when appropriate, thank you brady

**Comment by bradymiller** [comment]
hi @stephenwaite . Bringing in now. Thanks for the fix! -brady

**Pull request merged**
