### PR TITLE
Pharmacies are no longer required to be imported

### PR DESCRIPTION
**Pull request by juggernautsei**
Please add this to the next patch.

### CODE REVIEW

**Comment by sjpadgett** [comment]
btw: this will be great for getting new user's I believe.

**Comment by juggernautsei** [comment]
Ok, I'll make that happen.

**Comment by bradymiller** [comment]
hi @juggernautsei , Code looks good and will bring into codebase. Thanks for WENO! -brady

**Comment by bradymiller** [comment]
btw, I'll fix PSR2 issues on commit following this.

**Comment by bradymiller** [comment]
Also, recommend updating the wiki page at with your marked simplifications on using WENO:
https://www.open-emr.org/wiki/index.php/OpenEMR_ePrescribe#Weno

**Pull request merged**
