### PR TITLE
fax_dispatch.php bug fix

### PR DESCRIPTION
**Pull request by bradymiller**

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller  This tested okay for me. I'm starting a patch 8 PR and will bring this back to 501. Thanks for the fix.

**Comment by bradymiller** [comment]
hi @sjpadgett ,
Thanks for testing. Will bring in now. And thanks for fixing in 501. Sounds like we have patch 8 starting in the pipeline :)
-brady

**Comment by sjpadgett** [comment]
Yep and to think you had to bring me kicking and screaming to git:) I think patch 8 may be a quick one as I plan to have the ins eligibility feature done for both versions soon. Have we ever done like just feature enhancement patches or is that too hard to keep up with?

**Comment by bradymiller** [comment]
@sjpadgett , Would likely be tough to have multiple lines of patches (ie. we may need to pre-purchase straightjackets :) ). Probably better to just keep them all in same patch line and definitely ok to include feature enhancements in the patch line.

**Pull request merged**
