### PR TITLE
fix: silence Undefined global variable $gbl_time_zone warning

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #

### CODE REVIEW

**Comment by sjpadgett** [comment]
@stephenwaite  Why? I already fixed this in my last commit in weno_new PR.

**Comment by stephenwaite** [comment]
my bad with the merge request, it looks like github remembered my merge commit choice from last commit instead of squash and merge

**Comment by sjpadgett** [comment]
oh well great minds and all that!

**Comment by bradymiller** [comment]
kung-fu-baby-funny

**Pull request merged**
