### PR TITLE
Fixed bug with handling radio buttons in LBF skip conditions.

### PR DESCRIPTION
**Pull request by sunsetsystems**
Fixes improper interpretation of operators in skip conditions that check the state of radio buttons.

### CODE REVIEW

**Comment by sunsetsystems** [comment]
This should be patched in 6.0.0 as well.

**Comment by bradymiller** [comment]
hi @sunsetsystems , sounds good. i'll bring it over to rel-600 after you bring in the PR :)

**Comment by sunsetsystems** [comment]
Thanks Brady!

**Comment by bradymiller** [comment]
thanks for the fix! (just brought it over to rel-600)

2DV (1)

**Pull request merged**
