### PR TITLE
use int cast for compares with php8 fatal errors in payment scripts

### PR DESCRIPTION
**Pull request by stephenwaite**
…ee sheet

starts fixing #4320 

#### Changes proposed in this pull request:
also  add space and colon to `policykeyup()` for mods in fee sheet

### CODE REVIEW

**Comment by bradymiller** [comment]
saving the world, one bad cast at a time :)

tenor (65)

**Comment by sunsetsystems** [comment]
I wonder if my old trick of "0 + $something" still works.

**Comment by stephenwaite** [comment]
think so @sunsetsystems and guessing it was a null value that caused the prob, will test on php8 maybe in the insane enviro

insane

**Comment by bradymiller** [comment]
the null should be compatible with any cast (I had to utilize null in some of the more complicated calculation intensive places to get it to avoid PHP8 errors)

**Comment by bradymiller** [comment]
The likely issue here is that the $_REQUEST['hidden_patient_code'] was populated with a non-int (ie. if the variable were empty, then the null should of worked there). your solution is better though without the ugliness of the null :)

**Review by bradymiller — APPROVED** [review]

**Pull request merged**
