### PR TITLE
back port of  502 eligibility feature PR #2276

### PR DESCRIPTION
**Pull request by sjpadgett**
- pulled in new translations/escaping functions from 502
- added guzzle to support oeHttp client backport

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller Hope I did the guzzle composer add correctly. Never maintained vendor in master before so educated guessing going on here. :)
I don't plan to merge this anytime soon but did bring back oeHttp client from 502. I have plans :) When do I not huh!

**Comment by bradymiller** [comment]
hi @sjpadgett ,
Supporting changes in packages like this will complicate things a but, but it can be done. Note we can't expect users to do anything composer related, so we'll need to include all the changed composer elements in the patch. Also need to be a surgical as possible, which is appears you have done (ie. composer lock file only contains changes related to the new package). It does look like you forgot the `composer dump-autoload -o` step, though.

**Comment by sjpadgett** [comment]
lol, just emailed ya about that. I may abandon the back port if I can't get it smooth. So far it has not gone well in testing. TBD...

**Comment by sjpadgett** [comment]
@bradymiller I want to squash & merge this soon so I can move on if you have any comments.
- add an Update Status button for single patient checks. Kind of cool.

**Comment by sjpadgett** [comment]
Number of commits travis error free: 1 ... :)

**Comment by bradymiller** [comment]
@sjpadgett , code looks great and looks like you got composer under good control also :)

**Comment by sjpadgett** [comment]
Cool, thanks bringing in and will create a testing patch for those waiting. This was fun!

**Pull request merged**
