### PR TITLE
Better Page Heading UI

### PR DESCRIPTION
**Pull request by robertdown**
Better wrapping for Page Heading - it is now a flex div and pushes icon to the right, sizing down the icons. Previously, they were nested inside the `h2` element, this puts all the icons in a better place.

(Screenshot has a wrench icon... that is a side effect from some other work, just pretend it is not there)

image

### CODE REVIEW

**Comment by sjpadgett** [comment]
I don't see a reason to have title Medical Record Dashboard taking up valuable real estate.
We know the patient and we also know we're in the Dashboard so it serves no purpose.

**Comment by robertdown** [comment]
Oh I agree with you! However, I don't want to fully remove it in this PR. I think it can be better styled, but I've started to focus on small, easy to integrate PRs.

I actually want to move the menu of the MRD into a navbar, which already supports both a page title and menu. But it would require more refactoring than I want to do right now.

However - for the meantime, what if we just make the page heading smaller? Like this

image

instead of 

image

**Comment by sjpadgett** [comment]
Sounds good thanks but if you are coming back to this then I'd just leave as is and fix in the more in-depth styling PRs.

**Comment by robertdown** [comment]
Work is already done :) would prefer to get this in the codebase. Not sure how complicated the refactor will be to move a menu into a different part of the render logic, incremental improvement is better than a long refactor.

**Comment by sjpadgett** [comment]
Okay, thanks for the adjustment. 
lol once you get started styling it seems like it never ends! At least for me....

**Comment by robertdown** [comment]
> Okay, thanks for the adjustment. 
> 
> lol once you get started styling it seems like it never ends! At least for me....

Agreed. That's why I just have to say "ok, this is a good stopping point - I can't fix it all in 1 PR" tomorrow is another day.

**Comment by robertdown** [comment]
I can't react to the label add directly, so I have to do it here

image

**Comment by bradymiller** [comment]
2DV

**Pull request merged**
