### PR TITLE
Cat iii fixes

### PR DESCRIPTION
**Pull request by kchapple**
Work-in-progress branch for Cat iii fixes.

@sjpadgett I fixed some low-hanging fruit here. Still a lot of cloudy stuff to figure out.

### CODE REVIEW

**Comment by sjpadgett** [comment]
Cool, Cat1's are testing well except, as you've mentioned, darned dates returning the 0000-00-00 stuff! I have to refactor all those dates and get rid of the fixdate() in CCM!
I could use an intern about now.:)

**Comment by kchapple** [comment]
@sjpadgett I fixed the order export when no result was present. Our export of still doesn't match 66_Terri_Rogers.xml because we don't put a 'Rank' and I'm unsure if it's needed, or where to query it from.

**Comment by sjpadgett** [comment]
problem is we are getting a careplan order template and not a procedure
template here is what we send

<entry>
  <act classCode="ACT" moodCode="RQO" >
    <templateId root="2.16.840.1.113883.10.20.24.3.130" extension="2019-12-01"/>
    <code code="SPLY" codeSystem="2.16.840.1.113883.5.6"
displayName="Supply" codeSystemName="ActClass"/>
    <entryRelationship typeCode="SUBJ">
      <supply classCode="SPLY" moodCode="RQO">
        
        <templateId root="2.16.840.1.113883.10.20.22.4.43"
extension="2014-06-09"/>
        
        <templateId root="2.16.840.1.113883.10.20.24.3.9"
extension="2019-12-01"/>
        <id root="1.3.6.1.4.1.115" extension="6909199b3d669b99aa88c554"/>
        <text></text>
        <statusCode code="active"/>
        <participant typeCode="DEV">
          <participantRole classCode="MANU">
            <playingDevice classCode="DEV">
              
                <code code="360006004"
codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMED-CT"/>
            </playingDevice>
          </participantRole>
        </participant>
      </supply>
    </entryRelationship>
  </act>
</entry>

should be

<entry>
  <procedure classCode="PROC" moodCode="EVN" >
    
    <templateId root="2.16.840.1.113883.10.20.22.4.14" extension="2014-06-09"/>
    
    <templateId root="2.16.840.1.113883.10.20.24.3.7" extension="2019-12-01"/>
    <id root="1.3.6.1.4.1.115" extension="6257ac0363623902e9d97fcb"/>
    <code code="360030002" codeSystem="2.16.840.1.113883.6.96"
codeSystemName="SNOMED CT" displayName="application of device"/>
    <text>Frailty Device</text>
    <statusCode code="completed"/>
    <effectiveTime><low value='20200624080000'/><high
nullFlavor='UNK'/></effectiveTime>
      
      <author>
        <templateId root="2.16.840.1.113883.10.20.24.3.155"
extension="2019-12-01"/>
        <time value='20200624080000'/>
        <assignedAuthor>
              <id nullFlavor="NA"/>
        </assignedAuthor>
      </author>                <participant typeCode="DEV">
      <participantRole classCode="MANU">
        <playingDevice classCode="DEV">
          
            <code code="360006004" codeSystem="2.16.840.1.113883.6.96"
codeSystemName="SNOMEDCT"/>
        </playingDevice>
      </participantRole>
    </participant>
  </procedure>
</entry>


I cherry picked your commit and i'm also getting all zero's in cat3 so
I don't know

**Comment by kchapple** [comment]
I understand. Looks like that QRDA template for device applied was missed, it is not in our code base.

**Comment by kchapple** [comment]
@sjpadgett this PR is closely tied to your current work. I'd either bring this in, or merge this whole branch with your current PR.

**Comment by sjpadgett** [comment]
I can't because you appear to be missing the negate fixes you sent me. Or maybe it doesn't matter but it concerns me you're testing with old code.

**Comment by sjpadgett** [comment]
I'll just bring this in and rebase my PR

**Pull request merged**
