### PR TITLE
Phase 1 FHIR on PHP- Provider Client and implement classes.

### PR DESCRIPTION
**Pull request by sjpadgett**
This is a start and opens many possibilities by supporting fhir profile and resources in php. This commit makes creating resource's and populating a fhir server fairly straight forward. I include a start on a client app meant to selectively manage reading and publishing patient resource by the provider/user. (Link in demographics summary next to External Data). Also, globals for server management are in the Connector Tab. Check out classes/src/oeFHIRResource.php for a Patient resource example for how to create.

(below added by bradymiller)
Up for grabs demo with demo data for this PR can be found here:
http://www.open-emr.org/wiki/index.php/Development_Demo#Gamma_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller Any chance you can try this out on a docker with patient data. The provider client automatically points to a public HAPI JPA for testing. I'm hoping we may get a discussion going on forum about where I am going wrong or right. Also it is my hope some will get a fhir to help do some profiles and resources.

**Comment by bradymiller** [comment]
wooohoooo! FHIR!!

Setting up an up for grabs demo here that has the "standard" demo data in it (this is one of the neat things that the demo can support):
http://www.open-emr.org/wiki/index.php/Development_Demo#Gamma_-_Up_For_Grabs_Demo
(since it does some weird things to support the demo data, it will take a couple minutes before the demo is up and going)

**Comment by bradymiller** [comment]
Just published a patient from above demo:
image

And then after the publish, did a read:
image

And then did a get history:
image

**Comment by bradymiller** [comment]
@sjpadgett ,
Quick question to figure out best filesystem architecture to use for this code. In the https://github.com/sjpadgett/openemr/blob/82cb492d189cc42816e630abcfb8a33d4629a42a/phpfhir/composer.json script:
1. Is the /HL7/FHIR/STU3/src stuff from a standard library?

**Comment by sjpadgett** [comment]
The class library for Stu is generated from an open source class generator that downloads latest xsd schema  and generates the classes as you see them. I made them static for now but they can be generated on the fly in our app or made static as I have done. I want to get with the generator's author to make some changes but for now we can develop against these and integrate a better install later.

**Comment by sjpadgett** [comment]
Also Brady, I wanted to keep the FHIR module somewhat loosely integrated and as self contained as reasonable for now because I'm just not sure how it is going to evolve thus making any pull backs easier.

**Comment by bradymiller** [comment]
Agree on the loose integration for now. It looks like in the end we'll be able to turn this all into a composer module as a separate repo, which will be straightforward (but agree we shouldn't do this until things are more worked out). Do you think this is ready for the codebase (ie. no security issues such as scripts that can be run without authentication; my quick look didn't find anything).

**Comment by sjpadgett** [comment]
I just pulled the classes from the provider app and re-purposed them for a rest abstract controller. Also want to add a couple more resource(maybe org and practitioner) then if it makes it easier to put in codebase, sure.

**Comment by sjpadgett** [comment]
@bradymiller I went ahead and put up my latest and will wait for new resources as I feel the oauth calling me today. Should go ahead I suppose and bring this in to make it easier for others to contribute. If we can get enough resources done i'll concentrate on the publish app for maybe inclusion in next release. Once travis is done i'll bring in unless you say otherwise or you can if I haven't yet...

**Comment by sjpadgett** [comment]
Bringing in so others may contrib if they wish. I just ask that they notify the rest of us of what is being worked so we haven't any cross purpose foo pa's. Creation of basic resource's is paramount starting with types like observation, encounters, medication statement e.t.c. or take on the provider client.
I'm not married to any code structure here so, if you see an improvement feel free as my feelings only stay hurt for exactly 23.5 seconds:).

**Comment by bradymiller** [comment]
@sjpadgett,

What would be a good really easy resource to take on (so I and others can get a feel for how to do this)?

Regarding oauth stuff, just to ensure I am thinking right, is this to allow pulls from OpenEMR via a FHIR entity?

thanks,
-brady

**Comment by sjpadgett** [comment]
@bradymiller ,
I'm working now on an encounter resource that will give an example of a more specific resource that has to point back to the patient resource. However, i've modified the resource class to handle resource id's better using an id scheme of resource type-openemr id i.e patient-pid, encounter-eid and so on. I'll put up here in next couple hours. I suggest checking out this: http://hl7.org/fhir/resourcelist.html then going to the jpa test server and look at an example of the resource. Remember all possibilities of the resource don't need to be used, only required. 
For building a resource from the hl7 classes start with a FHIRDomainResource class which you may add elements from FHIRResource or FHIRElement classes. The various methods are documented for what the are. Key is to not approach FHIR as being as complicated as the spec tends to lead people. Once you have reviewed the classes the spec become more clear. Maybe look into doing an observation or a medication. Don't forget if you need a helper method or even new helper class to help build resources, go for it. So, if you can 'till tonight I will put up my changes of new id format, an encounter resource, saving encounter from forms and selecting resource to act on in provider client.

For oauth I am speaking about authentication on our FHIR server. For OpenEMR, it should be discussed in full because we most likely would have to create our own provider/auth server and using public provider's scare me. (still looking into this)

**Pull request merged**
