### PR TITLE
Patient finder improvements

### LINKED ISSUE #4066: Patient search table cursor doesn't indicate that row is clickable
When hovering mouse cursor over list of patients, the cursor defaults to a text selector. It should change to a pointer to indicate it's possible to click on the names to open further screens.

Current:
Patient Finder 1

Expected:
Patient Finder 2

### PR DESCRIPTION
**Pull request by spyrkob**
Fixes #4066 

#### Short description of what this resolves:
Small UI improvement for patient finder table. Makes it clearer that the patient rows listed in the table are interactive and can be clicked.

#### Changes proposed in this pull request:
When user hovers over table row, changes the cursor to a pointer instead of text selection/default. Also wraps the user name in table in a link.

### CODE REVIEW

**Comment by stephenwaite** [comment]
thanks for the contribution @spyrkob , looks nice, did you notice the focus switch back and forth from the dashboard to the patient finder page before finishing on the dashboard?

**Comment by spyrkob** [comment]
Hi @stephenwaite I tested with Chrome, Safari and Firefox but I didn't see any focus switching. Are there any steps to reproduce this or does it happen every time selecting patient?

**Comment by stephenwaite** [comment]
hi @spyrkob , was happening when selecting every patient but can't reproduce at the moment so was prob my test environment :man_shrugging:

**Comment by bradymiller** [comment]
hi @spyrkob , Code looks good and testing well. Bringing in. Thanks for the improvements! -brady

**Pull request merged**
