### PR TITLE
Adding a function to the appointment service

### PR DESCRIPTION
**Pull request by juggernautsei**
Fixes #

#### Changes proposed in this pull request:
Working on a project where I need to get the title of the appointment. I looked over the appointment service and this information was not handled. So, that is why I am posting this request.

### CODE REVIEW

**Comment by stephenwaite** [comment]
hi @juggernautsei, what if you add an optional `$date` to the `getAppointmentsForPatient()` and the `pc_title` to the select?

**Comment by juggernautsei** [comment]
My reply to that is that there will still be more information coming back than needed.  I know the mentality is to get it all and ignore what you don't need. It bothers me. Seems like the call for unnecessary data is a waste of resources.

**Comment by stephenwaite** [comment]
ok, the only remaining issue would be that you're call is only grabbing one appointment which most often won't be a prob but for adding the function to this service should probably be more complete.

**Comment by juggernautsei** [comment]
Good question and that would have to include the encounter to get the correct title. Also, I have it wrong anyway. The title is not the pc_catid. I just ran the code and it did not produce what I wanted. So, I will change this one to what I was trying to get in the first place.

**Comment by bradymiller** [comment]
This class is not collecting appointments correctly (it will miss recurrent appointment). There should be a getAppointments function that basically wraps fetchAppointments() in library/appointments.inc.php.

**Comment by juggernautsei** [comment]
Since I am working on the telehealth module this is in area. I will pick it up again and see if I have the chaps to make a wrapper.

**Pull request closed without merging**
