### PR TITLE
Convert table-based form to proper bootstrap form-groups

### PR DESCRIPTION
**Pull request by robertdown**
@juggernautsei This is how I would approach improving the UI -- I'd replace the table-based forms with the better `form-group` form.

Note the `container` wrapper and the use of the `col-md-<int>` classes to place the form in the center.

One random note, there was a bug in the style_light css file that was adding extraneous padding to the top of all `container` classes instead of just `menuBar > container`. Not sure why/how it was put there, but I pulled it.

screen shot 2017-03-27 at 17 41 33

### CODE REVIEW

**Comment by juggernautsei** [comment]
When I grow up...

**Comment by bradymiller** [comment]
Noted following bugs on this code:
-All the buttons, except for 'Cancel', are not working.
-On the other themes, the encounter menu does not show right (it is hidden by the elements on the procedure form  and guessing has to do with z-index setting).

I noted the following bug on Sherwin's code that is now in the codebase:
-When click Add procedure the elements added to the form are not being styled by bootstrap

**Comment by robertdown** [comment]
Noted, will look into the issues mentioned

**Comment by juggernautsei** [comment]
I have an idea why the buttons are not working. But I thought I had fixed the elements that were being brought in by add were being styled. I will check again.

**Comment by robertdown** [comment]
What in the world... How did this branch get so bizarre? I have no idea why there's now 67 modified files.....

**Comment by bradymiller** [comment]
yep, merging can do some strange things sometime. current official still looks good. To better visualize the commits, I have the following in my .git/config in the alias section:
``````
lf = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative
``````
then can do following:
``````
git lf master
``````
To continue work on this file, I'd rec copying out this file, making a clean branch from master, and then copying your file back in.

**Comment by robertdown** [comment]
Closing this in favor of cleaner PR #617

**Pull request closed without merging**
