### PR TITLE
Add patient portal rest api

### PR DESCRIPTION
**Pull request by bradymiller**
Appears to be working, but still some more testing to do

### CODE REVIEW

**Comment by sjpadgett** [comment]
I'm trying to gleen what the end goal is.

**Comment by bradymiller** [comment]
@sjpadgett ,
This will allow support of patient centric apps (for example, the ongoing flutter app) in a secure manner. By separating out the patient centric api requests into its own route category (and not allow any crossover between the fhir/oemr/portal routes) we can be confident that the patient will only be able to access their own data in the patient app. And we can overlay this with a very simple access control mechanism if needed (for example, if we want to provide and option where don't want patient's to be able to change their demographics, would be straightforward to add). The auth is working on top of the auth you use for the patient portal (and won't work until new password has been entered in the portal and also supports placing email address in auth if that is turned on). At some point, we can also encapsulate/migrate the full portal auth into the auth class (but that is for another day).

**Comment by bradymiller** [comment]
Also forgot to mention. Ended up breaking out the rest api globals selections into 3 different categories:
1. core api
2. fhir api
3. patient portal api
(so, have more granularity with which api categories to turn on/off)

**Comment by sjpadgett** [comment]
@bradymiller looks good. organized much better for handling different apis. I haven't tested but, I don't see any issues with code anywhere.
I just need to screw up the ambition to make some other auth options available but, AuthUtil will make  a easier go of it.

**Comment by im-Amitto** [comment]
@bradymiller Looks great.

**Comment by bradymiller** [comment]
I just realized that it would be really simple to also offer a separate fhir route for patient centric apps, so just added that. I'm gonna do lots of testing and code audits over next couple days before bringing this in since it involves code changes in authentication. Also gonna make sure all potential breaking points are logged as much as possible.

**Comment by bradymiller** [comment]
hi @bradymiller , Testing well and bringing this into codebase. Thanks for the improvements! -brady
:)

**Comment by im-Amitto** [comment]
@bradymiller Time to add it into the mobile app

**Pull request merged**
