### PR TITLE
default

### PR DESCRIPTION
**Pull request by shannonmae999**
Fixes #

### CODE REVIEW

**Review by shannonmae999 — COMMENTED** [review]
Review red

**Comment by adunsulag** [comment]
@shannonmae999 What is this pull request for?  I can see you are adding the github codeql piece which is nice and all but what's with the CNAME and that html cloudflare analytics piece?  What are you trying to accomplish here?

**Comment by shannonmae999** [comment]
> @shannonmae999 What is this pull request for?  I can see you are adding the github codeql piece which is nice and all but what's with the CNAME and that html cloudflare analytics piece?  What are you trying to accomplish here?

I am trying to set up open emr.

**Comment by adunsulag** [comment]
@shannonmae999 I'm pretty sure the OpenEMR project can't accept a pull request for the analytics tracking due to privacy concerns, right @bradymiller? I suggest that you keep this in your own forked version of OpenEMR.

**Pull request closed without merging**
