### PR TITLE
Allow items exclude in Portal Profile

### PR DESCRIPTION
**Pull request by sjpadgett**
- from layouts UOR = unused and/or new Exclude in Portal edit option

#### Short description of what this resolves:
Allows users to select if demographic items from DEM layout are excluded in Portal Profile
and yes I relented. only took four years!

#### Changes proposed in this pull request:
Add new Exclude in Portal edit option to super layouts
Honor UOR unused option

### CODE REVIEW

**Comment by sjpadgett** [comment]
Exclude logic is:
- if uor = unused and/or edit option = EP
- or uor = optional/required but edit option = EP. Allows item in chart demographics but excludes in portal.
image

Going to try and get some of @gutiersa asks in this PR. So, hold on to your hats!

**Comment by gutiersa** [comment]
Very nice. I think this is already active in EMR no? I went into my mom's chart yesterday, I used teamviewer, and I noticed that in the provider field she had the field, but she could only pick administrator. She could not pick me. It was also a required field. She could not hit next, or previous. We had hit the X button on the upper right. She could not complete her profile.

**Comment by sjpadgett** [comment]
Just some running documentation.
- New patient is qualified first with check for existing email and dob match otherwise continues with first, last, dob then a final before chart is created of all terms: first, last, dob and email. This covers a shared email if use by care groups/long term care or family members etc.
- Register profile requires a provider be selected by patient for some obvious reasons. This is not true in portals profile edit. So, only authorized users will show in provider selection.
- If email failure, we now send a notice to clinic and still create chart.
image
image
Message
image
image

So going to wrap up this PR. For god sake, will somebody tell me to go to bed!:)

**Comment by sjpadgett** [comment]
If no objections, i'm going to bring this in after I try to ensure I haven't missed any files again. (reminders):)

I need to spend some time in v6.0 plus bring this stuff forward.

**Comment by sjpadgett** [comment]
@gutiersa You feel like documenting some of this? Put some concentration on email setup. I'd be greatly appreciated.
I'm also going to try and get a few patient template dashboard improvements in before I get too bored with portal again!

**Comment by gutiersa** [comment]
Yes, I am keeping track
*Sandragutierrezmd*
*THINK BEFORE YOU PRINT*
This message, together with any attachments, is intended only for the
addressee. It may contain information that is legally privileged,
confidential, and exempt from disclosure. If you are not the intended
recipient, you are hereby notified that any disclosure, copying,
distribution, use, or any action or reliance on this communication is
strictly prohibited. If you have received this e-mail in error, please
notify the sender immediately by telephone, fax, or return e-mail and
delete the message, along with any attachments.

**Comment by sjpadgett** [comment]
@gutiersa 
Here is a patch for you to test. I did find a couple bugs fixed here and may help in your endeavors.
https://drive.google.com/file/d/1to72gq_yySrr4qe1lkr8AN0shb3WZPEY/view?usp=sharing

**Comment by gutiersa** [comment]
on it

**Comment by gutiersa** [comment]
AcctReg2_LI

**Comment by sjpadgett** [comment]
you have to run sql_patch.php. install like a normal patch!

**Comment by gutiersa** [comment]
again duh

**Comment by gutiersa** [comment]
Nice, so I tried to register and it did not allow me to. Hopefully, people will not make errors in data entry. However, they often do. I wish the patient portal profile was just that, a profile. I would like to control the actual connection to the portal chart. In other words. One thing is the profile another is the patient chart. Sure, they should all be the same thing, but there are so many little things that you have to consider in healthcare. One thing is that we are aging. Some patients for example are not even managing their own patient charts. Some have alzheimers. I am working with their children. The son is the power of attorney and the daughter is the caretaker. The patient herself is clueless.

Hence, one thing is the patient chart which is in my end, and for me to protect. Another is the portal chart and how much of the data we, the doctor want to share. 
The profiles are just the profiles of those who have access to the portal chart of the patient.

This is just food for thought. These issues affect primary care and many other in US

**Comment by sjpadgett** [comment]
I don't understand! For one, I can't be responsible if people mess up entering their name, birthdate, address or any thing else in profile.
Second, You can now exclude what profile data is entered by the patient in layouts by setting the Exclude in Portal option. You have a choice to exclude in both the demographics chart by setting the UOR to unused which automatically excludes in portal or leave UOR as optional/required to record in chart and set the Exclude in Portal options flag if you don't want patient to see the field.

As for what gets in to chart, that is what the Audit review is for in Portal Dashboard. There is where admin decides if patient profile request change is allowed.

No matter how you want to look at it, the patients demographics is their profile! Also, hiding patient data from the patient defeats the whole purpose of giving patient access to their medical information. The days of hidden chart notes or the attitude that patient won't understand something about their health information so, we just won't let them see it, are gone...

The VA got called out on this very issue and had to relent. Another that gets me ramped up is gender and race. Not asking those questions may be politically correct and allows people to think they are so enlightened but, you can't tell me they are not important question when it comes to diagnosis or labs!!!

End of rant. I don't know what more I can do concerning this.

**Comment by sjpadgett** [comment]
Oh, thanks for testing.:)

**Comment by gutiersa** [comment]
Points very well taken and you do an outstanding job! I am not trying to hide data, actually. I do agree that patients need to be proactive in their care. I am a I am actually attempting to protect their data and manage duplicates. That is all! In fact, my point is if they were to make duplicates I could just leave them. But listen. It is not an ask. It is not a feature request. It is just meant to be a discussion. I tell you my experience, you tell me yours. That is all. I will check out the UOR's. I will test some more.

**Comment by sjpadgett** [comment]
Really I don't mind the asks especially if my attention is currently on a project because we both want it the best it can be.
I just don't know how much more validation wise I can do.

**Comment by gutiersa** [comment]
I agree with you. Validation is pretty good as it is. There isn't much more you can do. I guess what I was trying to say is that one thing is a profile, and another is the owner of the chart. So it is akin to ACL type thing? But that would be for some future planned feature.

**Comment by sjpadgett** [comment]
I'm an engineer and really just use deductive reasoning when it comes to the clinical side of things.
So, It's okay to keep me honest.

**Comment by gutiersa** [comment]
So there may be other bugs, or maybe it's just me not know how to use the program. Do you want them here? Or a new post in the forum?

**Pull request merged**
