### PR TITLE
Adds OBR-15 aka specimen type to lab procedure orders HL7 message

### PR DESCRIPTION
**Pull request by DennisonWilliams**

### CODE REVIEW

**Comment by sjpadgett** [comment]
Ya need to get the current file from master then, make your modification. Also, not seeing where you included the OBR segment!

**Comment by DennisonWilliams** [comment]
I see what went wrong.  I am going to make a new pull request

**Comment by sjpadgett** [comment]
@DennisonWilliams 
Just push to same pull request with updated file. don't need new PR...

**Comment by DennisonWilliams** [comment]
@sjpadgett oops, I already closed this one, can you please take a look at [PR2643 ](https://github.com/openemr/openemr/pull/2643)

**Pull request closed without merging**
