### PR TITLE
Integration of BigBlueButton for Video Consultation

### PR DESCRIPTION
**Pull request by pithonsoft**
Integration of BigBlueButton, an opensource project for video consultation.
Work Flow.
Create an appointment and select "video consultation" as category.
When the meeting to be started change the appointment status to "start Video Consultation"
Configurations:
In globals enter BBB - Secret and URL .
This is the output of command : bbb-conf --secret after configuration of BBB server
Big Blue Button links
https://docs.bigbluebutton.org/2.2/install.html
https://docs.bigbluebutton.org/dev/api.html

### CODE REVIEW

**Comment by tywrenn** [comment]
looks like it can use some php/html beautification

**Comment by pithonsoft** [comment]
Is there a plan to review this in coming days?

**Comment by tywrenn** [comment]
Needs to be rebased to master first

**Comment by sjpadgett** [comment]
I'd be interested in helping get this integrated when I have time. I like the fact it is based on WebRTC which is the way I always planned on going.
My biggest concern is ease of install for user base. @pithonsoft Can you  just give a brief outline how that would happen and if project is compatible across Windows, Mac and the various Linux flavors we support including AWS and Docker.

**Comment by pithonsoft** [comment]
Thank you @sjpadgett for your interest.
The BBB project officially support: Ubuntu 16.04 64-bit OS running Linux kernel 4.x.  It will work on AWS. Not tested on docker.

**Comment by sjpadgett** [comment]
Hi @pithonsoft ,
Yeah it's a problem if Mac and Windows support is not readily available. Although, it should be doable.

**Comment by mdsupport** [comment]
> Yeah it's a problem if Mac and Windows support is not readily available. Although, it should be doable.

@sjpadgett, I think @pithonsoft meant server installation requirements as [stated by that project](https://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements). It is pure HTML5 client inheriting known browser platform compatibility issues not much different from EMR.

@pithonsoft, is it possible for developers to see a working demo without going through complete setup even if for few days? 

Chances are televisits will continue in post-covid world. So if this can be made into a openemr specific docker or a packaged addon, it will be really useful for a wide range of installations.

**Comment by sjpadgett** [comment]
Thanks @mdsupport , I've got some sponsor money to do telemedicine right. I've been putting off taking the work because this is a project that needs a team.
Again, for this project i'm more than willing to help integrate into codebase but, I can't spend a lot of time helping with the engineering.

**Comment by mdsupport** [comment]
We have been putting off work on this for same reason. Unlike emr, moderately hefty streaming server is needed for audio/video coding along with decent bandwidth. It is still hard to make a compelling value proposition for in-house hosting vs paying $20-$30 for the service. Integrating this in portal does make sense as patient can review and update their records while _waiting_ for their televisit to begin.

**Comment by sjpadgett** [comment]
> It is still hard to make a compelling value proposition for in-house hosting vs paying $20-$30 for the service

Agreed. Especially for our user base which tends to be on the small practice side. Also, generally the video service provider world is getting better everyday with way too many choices to try and maintain a local server of one type over another. 

I think best approach is to provide the service via a gateway interface class to seek video services by way of their API's. Much like one would do with labs or credit card providers. In this way, we can offer a choice to our users and they're not stuck with what we(dev's) consider the best service.

Portal and core would then concentrate on management to their purpose e.g scheduling, billing etc.
As an EMR we are behind the curve here and playing catch up which drives me nuts!:)

If not for ONC, i'd be all over this now.

**Pull request closed without merging**
