### PR TITLE
Ccda import work 4 y

### PR DESCRIPTION
**Pull request by bradymiller**
- binary support for clone database in multisite
- fix for laminas commandline enable/disable (they were doing opposite of what they were supposed to do :) )
- support commandline laminas module acl modification

We can now turn on carecoordination from commandline with the following commands (using paths in the easy dev docker):
```php /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/public/index.php register --mtype=zend --modname=Immunization
php /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/public/index.php register --mtype=zend --modname=Syndromicsurveillance
php /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/public/index.php register --mtype=zend --modname=Documents
php /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/public/index.php register --mtype=zend --modname=Ccr
php /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/public/index.php register --mtype=zend --modname=Carecoordination
php /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=install --modname=Immunization
php /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=install --modname=Syndromicsurveillance
php /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=install --modname=Documents
php /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=install --modname=Ccr
php /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=install --modname=Carecoordination
php /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=enable --modname=Immunization
php /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=enable --modname=Syndromicsurveillance
php /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=enable --modname=Documents
php /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=enable --modname=Ccr
php /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=enable --modname=Carecoordination
php /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/public/index.php acl-modify --site=default --modname=Carecoordination --aclgroup=admin --aclaction=enable

```

### CODE REVIEW

**Comment by bradymiller** [comment]
btw, this is testing well and plan to bring in when passes testing.

**Comment by stephenwaite** [comment]
shocked_cat

**Comment by bradymiller** [comment]
btw,
Here's an example of InstallerAuto.php script that works in the easy dev docker to make a multisite clone:
```
php InstallerAuto.php rootpass=root server=mysql loginhost=% login=run1 pass=run1 dbname=run1 site=run1 source_site_id=default clone_database=yes
```

**Comment by stephenwaite** [comment]
```
bash-5.1# php interface/modules/zend_modules/public/index.php register --mtype=zend --modname=Ccr
Successbash-5.1# php interface/modules/zend_modules/public/index.php register --mtype=zend --modname=Ccr
Successbash-5.1# php interface/modules/zend_modules/public/index.php register --mtype=zend --modname=Documents
Successbash-5.1# php interface/modules/zend_modules/public/index.php register --mtype=zend --modname=Carecoordination
Successbash-5.1# php interface/modules/zend_modules/public/index.php register --mtype=zend --modname=Immunization
Successbash-5.1# php interface/modules/zend_modules/public/index.php register --mtype=zend --modname=Syndromicsurveillance
Successbash-5.1# php interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=install --modname=Documents

--- Run command [install] in module:  Documents---
start process - 2021-06-07 02:02:43
module [Documents] was find
command completed successfully
bash-5.1# php interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=install --modname=Ccr

--- Run command [install] in module:  Ccr---
start process - 2021-06-07 02:03:59
module [Ccr] was find
command completed successfully
bash-5.1# php interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=install --modname=Immunization

--- Run command [install] in module:  Immunization---
start process - 2021-06-07 02:04:12
module [Immunization] was find
command completed successfully
bash-5.1# php interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=install --modname=Syndromicsurveillance

--- Run command [install] in module:  Syndromicsurveillance---
start process - 2021-06-07 02:04:22
module [Syndromicsurveillance] was find
command completed successfully
bash-5.1# php interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=install --modname=Carecoordination

--- Run command [install] in module:  Carecoordination---
start process - 2021-06-07 02:04:36
module [Carecoordination] was find
command completed successfully
bash-5.1# php interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=enable --modname=Documents

--- Run command [enable] in module:  Documents---
start process - 2021-06-07 02:06:17
module [Documents] was find
command completed successfully
bash-5.1# php interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=enable --modname=Ccr

--- Run command [enable] in module:  Ccr---
start process - 2021-06-07 02:06:24
module [Ccr] was find
command completed successfully
bash-5.1# php interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=enable --modname=Immunization

--- Run command [enable] in module:  Immunization---
start process - 2021-06-07 02:07:01
module [Immunization] was find
command completed successfully
bash-5.1# php interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=enable --modname=Syndromicsurveillance

--- Run command [enable] in module:  Syndromicsurveillance---
start process - 2021-06-07 02:07:10
module [Syndromicsurveillance] was find
command completed successfully
bash-5.1# php interface/modules/zend_modules/public/index.php zfc-module --site=default --modaction=enable --modname=Carecoordination

--- Run command [enable] in module:  Carecoordination---
start process - 2021-06-07 02:07:19
module [Carecoordination] was find
command completed successfully

 php interface/modules/zend_modules/public/index.php acl-modify --site=default --modname=Carecoordination --aclgroup=admin --aclaction=enable

--- Run command [enable] [admin] in module:  Carecoordination---
start process - 2021-06-07 02:25:30
groupaclid is 11
command completed successfully - 2021-06-07 02:25:30
bash-5.1#

**Comment by bradymiller** [comment]
this will be coming to a flex docker near you soon :)

**Pull request merged**
