### PR TITLE
Encounter Menu Hook

### PR DESCRIPTION
**Pull request by robertdown**
Support for `EncounterMenuEvent`. Currently only support for `MENU_RENDER` which is used to populate the Twig variable for output.

Forms.php builds traditional forms menu and zend hooks. Both of those were wrapped in event listeners to streamline a future project to move those out of forms.php and into a better location. (Just means technically this page both adds 2 listeners and then fires the dispatch()).

Is testing well

### CODE REVIEW

**Comment by robertdown** [comment]
Note I also brought in `Symfony\Contracts\EventDispatcher\Event` in favor of `Symfony\Component\EventDispatcher\Event` which has been deprecated as of 4.3. We need to migrate over, but for now thought it best to not introduce new code with deprecated dependencies.

**Comment by bradymiller** [comment]
tenor99

**Comment by adunsulag** [comment]
@robertdown I reviewed your code and didn't see any problems.

**Comment by DennisonWilliams** [comment]
This is great.  It will help me pull out some label printing code I am maintaining in core (in a clone of openemr/openemr).  When is this scheduled for release?

**Comment by robertdown** [comment]
Generally this kind of thing doesn't get included in patches, just the next release. @bradymiller thoughts? @DennisonWilliams Expect to see quite a few new hooks coming into high-touch points areas in the coming months

**Comment by bradymiller** [comment]
Yep, will be in next release (6.1.0), which is likely gonna be in about 2 months or so.

**Pull request merged**
