### PR TITLE
Initial Custom Module support and installer.

### PR DESCRIPTION
**Pull request by adunsulag**
This pull request contains the work for both zend and custom modules to be used and installed via composer.  Its intent is to continue to allow customization and vendor support of the OpenEMR codebase without requiring all the changes to be done directly in the core system files.

Before this code, the only workable modules were zend modules and developers were finding it cumbersome to implement.  This work makes it possible to have a custom module that connects to OpenEMR via a single file the openemr.bootstrap.php file.  Module developers can now use either whatever programming style they want (procedural, oop, functional, etc) as well as whatever framework they want without impacting the core OpenEMR code.

I changed the ModuleApplications class to load the openemr.bootstrap.php file for each enabled custom module.  

I also changed the zend application code so that the custom modules are not loaded as zend applications.

In testing this code on the docker environment you may have to manually apply the changes to interface/modules/zend_modules/application.config.php as the docker images pulls that file as readonly from the openemr master code.
 
To have modules auto install via composer you have to have your composer package type be 'openemr-module'  You can see an example of this in the composer.json file for the sample openemr module oe-module-faxsms.

You can see how the sample works by doing the following command:
```
composer require openemr/oe-module-faxsms:@dev
```

You can then go on the Admin GUI and from the Modules Installer menu item you can install the faxmodule and enable it just like you would the Carecoordination module.

The fax/SMS module gets added and its appropriate hooks are executed.  You will have to logout and login again to see the menu change take effect which is the easiest hook to verify.

A future improvement for this is to have the OpenEMR module installer grab the descriptive name of the module from the composer.json file.  Right now it grabs a descriptive name from the first line of a Info.txt file at the root of the module folder.

Also important to note is that right now all of the zend modules will execute first before the custom modules.

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @adunsulag , awesome stuff!
Quick clarification on the interface/modules/zend_modules/config/application.config.php file. I thought we made it so that file does not need to be writable?

**Comment by sjpadgett** [comment]
@bradymiller Will you go up on Packagist.org (not Packagist.com) create an account so one of us can add you as a maintainer? Also, auto update with git web hooks require our repo ownership permissions but i'm unsure we want to allow, would you look at.

**Comment by adunsulag** [comment]
@bradymiller It doesn't need to be writeable as this is a one time code change, its just a small disconnect while the code changes haven't been merged into the master release of OpenEMR.  If we make a change in the code to the application.config.php the docker setup does not update it as it uses the file version checked into the OpenEMR master release on the flex docker instance.  So if you are working on a branch or in this case this pull request and you've modified the application.config.php the docker file won't update it until your changes have been merged into OpenEMR master.  Does that make sense?

**Comment by sjpadgett** [comment]
I keep coming back to staying out of our views with dispatcher events for now. At least 'til we decide how we will be doing views. Feedback?


@bradymiller I may bring this in today as I have several changes that need to be done. Stephens not back until Tuesday so i'll fix travis when I do my PR.

**Comment by bradymiller** [comment]
hi @sjpadgett ,
Feel free to bring this in now. I can do a quick travis fix on the codebase later this evening.

**Comment by bradymiller** [comment]
@adunsulag , Thanks for the explanation; makes sense.
@sjpadgett , I'm gonna bring this in now and will fix the travis with a following commit. And I'll look into the packagist stuff tonight(or tomorrow night)

**Pull request merged**
