### PR TITLE
DIsplay Pat image in Calendar view

### PR DESCRIPTION
**Pull request by ophthal**
Hover/Onmouseover green patient icon in calendar day week or month views, if there is a patient image/photo on record, it will be displayed in the left column under the calendar, providers and facilities widgets. Onmouseout it will disappear.

### CODE REVIEW

**Comment by mdsupport** [comment]
@ophthal, how about using either qtip2 or bootstrap-4's popover with ajax html content?

**Comment by ophthal** [comment]
Love to see it!

**Comment by bradymiller** [comment]
@ophthal , oh my goodness. That is really cool (especially for us physicians you can never remember who any of the patients are...). I just brought your commit for this into the codebase:
https://github.com/openemr/openemr/pull/1792/commits/a66328ae4a9afb5d8d1ab2246961d70dcc09589d

@mdsupport , definitely would be cool to see this mechanism improved

@d3sandoval , please ensure the new change in the interface/themes/ajax_calendar.css is not lost on the theme migration project

**Comment by bradymiller** [comment]
@ophthal , btw, another really nice place to work this kind of mechanism into would be into the patient flow board.

**Pull request closed without merging**
