### PR TITLE
Care plan

### PR DESCRIPTION
**Pull request by juggernautsei**
The care plan works much like the idea behind CAMOS. When new encounter is opened. The entire care plan is pulled into the new encounter. So, rows of data can be deleted or amended as the goals and objectives are met and it creates a running history of what the patient was seen for at each encounter like with any other encounter based document in the system. So the physician can go back two encounters and see what the care plan was at that time.

### CODE REVIEW

**Comment by tmccormi** [comment]
Why are the care plan and the payment modules mixed up in this pull request?

**Comment by juggernautsei** [comment]
cause I am still trying to figure out how to properly use the github. It's coming slowly. Not real intuitive tome at this point. I just figured out how to properly make a branch. And yes I have watched the video over and over and it is too bad that I still don't fully get it cause I am using windows but I have been talking with github support and they have been enlightening me was to what is really happening so my next branch should be better. Apologies if I have over explained.

**Comment by tmccormi** [comment]
Sherwin,
   I'd be happy to help you, contact me directly... you have my number :-)
--Tony

**Comment by juggernautsei** [comment]
What is a good time to contact you? I will be more than willing to redo all of the requests.

**Pull request closed without merging**
