### PR TITLE
Bug fixes for nation notes, lbf

### LINKED ISSUE #6787: Bug fixed mostly related to Layout based form & nation note
### Describe the bug

**Nation notes:** OpenEMR allows to share the Categories from the Context to other users but then it was not sharing the Context because of that even though the categories are shared other user who has not created context or category was not able to use it. We have rectified that bug.

**Printing bug of the LBF form:** In the patient report if values are coming from nation notes defined categories and pretext printing was getting al jumbled up.

**OEMR LBF Request - Required fields :**
 Previous behavior - When a field's UOR is marked as Required, it makes it required for the entire layout. 
 Current behavior - The Required UOR field would only apply when the Introduction group is selected within the layout. 

**predefined LBF selections was not working this has been fixed.**

### Feature

If we add HCPCS or CPT or ICD code at the list and if the list is selected at patient encounter based layout based form the we auto populate that in the fee sheet.

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by gauravsontakke**
Nation notes
Printing bug of the LBF form
OEMR LBF Request - Required fields
LBF Text - formatting issue
predefined LBF selections are not working
Codes from LBF form to flow to fees sheet

Fixes #6787

### CODE REVIEW

**Comment by robertdown** [comment]
Hi @gauravsontakke 

It looks like this PR tackles several different bugs. It would be better to split out each bug to it's own issue and PR to keep the changes concise.

**Comment by gauravsontakke** [comment]
> 



> Hi @gauravsontakke
> 
> It looks like this PR tackles several different bugs. It would be better to split out each bug to it's own issue and PR to keep the changes concise.

**Comment by gauravsontakke** [comment]
Hi All ,

based on the discussion in the weekly meeting created new issue 

[https://github.com/openemr/openemr/issues/6787](https://github.com/openemr/openemr/issues/6787)

As discussed since majority of the changes are interlinked thats why not creating individual pull request.

Thank you. 

Regards
Gaurav

**Comment by sjpadgett** [comment]
Be sure to turn on Text Nation Note in config for text fields in encounters and test as you make changes.
There are several hooks in NN code.
Once turned on, double click in any encounters text area or input to use.
image

**Comment by gauravsontakke** [comment]
> Be sure to turn on Text Nation Note in config for text fields in encounters and test as you make changes. There are several hooks in NN code. Once turned on, double click in any encounters text area or input to use. image

Yes. We have turned it on and using the way you are suggesting and corrected code for the similar functionality.

**Comment by sjpadgett** [comment]
I linked your issue with this PR by adding the issue number to Fixes in description. You can add as many issues as you need.

**Comment by stephenwaite** [comment]
set up an [up for grabs demo](https://four.openemr.io/a/openemr/index.php)

**Comment by stephenwaite** [comment]
Hi @gauravsontakke, here's link to the [openemr-cmd](https://github.com/openemr/openemr-devops/tree/master/utilities/openemr-env-installer) which can help you fix the php styling easily.

**Comment by adunsulag** [comment]
I'm interested in testing out these fixes but scanning through the code there's enough changes that it doesn't look like it will happen for this patch.  Bumping to next patch.

**Pull request closed without merging**
