### PR TITLE
Remove inline styling: font-size #784

### PR DESCRIPTION
**Pull request by apX9**
his is my first PR. Let me know if you have any feedback!

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @apX9 ,
Congrats on your first PR!
If only it were as simple as removing the inline styling. The problem is that rather than remove, actually need to migrate the styling. We should pick out 1 script and go through the process. @zbig01 or @robertdown ; do you know of any good starter scripts to work on for this (ie. an easy script that can highlight the process of migrating away inline styling)?

**Comment by danehrlich1** [comment]
1. @bradymiller So are you saying @apX9 needs to both delete AND migrate to a separate CSS file?

2. Also if Item 1 is true, does the same need to be done at some point for (a majority of) our inline Javascript/Jquery?

**Comment by apX9** [comment]
So I should do the following:
1. Migrate the  inline styles i'v removed to separate CSS file.(Is this some existing  file or should I create a new one?)
2.Do the same for  Javascript/Jquery?

**Comment by danehrlich1** [comment]
Armin:

For now, create a new CSS file and move all styles to it from the php file. Same for creating a JS file as well.

Brady please correct me if I misspoke.

**Comment by sjpadgett** [comment]
Instead of removing inline css to another file why not just re style to meet existing theming. All this does is create another styling mess. For any Javascript, inline or not, there needs to be a plan ie some engineering.
@robertdown Inline styling removal has been by your insistence, do you have any guidance here?

**Comment by danehrlich1** [comment]
Jerry I agree with all your points.

Moving to separate file is a temp fix / more of a staging area for now I’d like to think.

**Comment by bradymiller** [comment]
Agree to defer to @robertdown on the plan for migrating inline styling.

Also, would rec not touching the javascript stuff; that code is embedded in the php scripts and requires php interpreter for them (not helpful to migrate and would be very difficult).

**Comment by zbig01** [comment]
Hi @apX9 ,

Welcome to the UI modernization project. As you have no doubt found out there are a lot of different ways the scripts have been coded over the years and the the styling used was a mixture of inline, internal and external stylesheets. You will also find that html attributes like `<font size="3" color="red">This is some text!</font>` has also been used. In addition the original pages used a table based layout and used frames.

With version OpenEMR 5.0 two important changes were made - a newer tab based layout was introduced and Bootstrap 3 and font-awesome were included with the application. It was done with the hope of moving to a more modern responsive layout using Bootstrap 3 and to remove the inline styling and using html attribute itself to style elements. In OpenEMR 4 there were some external stylesheets that were present in the interface/themes directory. With OpenEMR 5 a more modern "light" theme was introduced. There were 3 categories of stylesheets - light, tan and the legacy stylesheets. Subsequently the flat stylesheets were introduced which introduced flat color schemes and design principles. The legacy stylesheets were dropped from the package and the tan stylesheet was renamed manila. Thus currently there are three types of stylesheets - light, manila and the flat or colored stylesheets.

The next step in  modernization was the splitting the stylesheets into scss files and compiling each individual stylsheet with `node.js` and a `gulpfile.js `scipt. The `gulpfile.js` script is run when you work on the the development branch with `npm run build` command. This parses the scss files in `/interfaces/themes` directory and compiles a minified css stylesheet that exists in `/public/themes` directory. This process simplifies the task of updating all stylesheets at once. If you open one of the minified stylesheets in a text editor you will see that the end of the file is filled with a whole bunch of what appears to be gibberish. This is the `sourceMappingURL`, it provides a way of mapping code within a compressed file back to it’s original position in a source file. [More info on sourcemaps](https://blog.teamtreehouse.com/introduction-source-maps)

The way to use the sourcemap is to right click an element whose style you want to inspect using the developer tools in either Firefox or Chrome and check the displayed style. It will point to the line number on the relevant scss file. There is a tiny esoteric bug that makes it point to the scss file in the `/public/themes` directory, instead take it to mean `/interface/themes.` You can use any online tool to un-minify the complied css stylesheet to get an idea of how it looks. Any change you make to the stylesheet in `public/themes` will be overwritten when `npm run build` is run. To make these changes permanent you will need to edit the relevant scss files.

In order to appreciate the changes that have been made over time I suggest you create an instance of a OpenEMR 4.2.2 on your machine, then compare the user facing pages on that instance with the identical page on the official working demo of the latest release  [OpenEMR 5.0.1](https://demo.openemr.io/c/openemr) and the  [development demo](https://seven.openemr.io/a/openemr/interface/login/login.php?site=default). To fully see the impact of styling changes I would suggest switching to an identical flat color theme in the OpenEMR 5.0.1 demo and in the development demo. `Administration > Globals > Appearance > General Theme`. Choose any page that has been restyled and look at its history on the master branch at github, you will be able to see the code changes as they were merged into the master.

Is is a painstaking task to remove all inline styling, the question of where to put it then arises. It will eventually have to go into the existing external stylesheets in order to not break what already exists. You can begin by adding to the existing scss files or creating new ones and placing them appropriately in the `interface/themes` directory. Of course you are at liberty to create an entirely new stylesheet if you so choose ;)

As you proceed with this task it will become apparent that not all of the styling can be migrated to an external stylesheet. Some of them are best served by leaving them as an internal stylesheet, the trick is to minimize such instances.

I would urge you to think of removing inline styling in the greater context of restyling the whole page with a view to improving the user experience (UX). Ideally each user facing page needs 
    - to be converted to a div based bootstrapped responsive lay out (not always possible)
    - the inline styling to be initially moved to an internal stylesheet
    - the internal stylesheet to be moved to an external stylesheet (where feasible)
    
Cheers :)

**Comment by apX9** [comment]
Great explanation, clarifies a lot.Thanks!! I will dive in the following week and come back with a useful commit as soon as possible.

**Pull request closed without merging**
