### PR TITLE
New use RxNORM table for drug lookups.

### LINKED ISSUE #4398: Add ability to search RxNORM in prescriptions
Fairly straight forward. If rxnconso (RxNORM free) external table is installed then user has option to search and select drug from there.
Lookup uses the SAB of RXNORM so licensing is valid for free version.

image

### PR DESCRIPTION
**Pull request by sjpadgett**
- if installed option to use rxnorms
- fudge dialog size and replace Done button with Quit.

Fixes #4398

### CODE REVIEW

**Comment by sjpadgett** [comment]
I think I should go a head and include RxCUI native load lookup if it is thought to be useful.
I'm not sure what users prefer to load.
@bradymiller @sunsetsystems @stephenwaite

**Comment by stephenwaite** [comment]
only thing easier than the nlm lookup is the monthly prescribe imho

**Comment by sjpadgett** [comment]
what's the best way to check if native rxcui is installed?

**Comment by stephenwaite** [comment]
check if anything in `RXCONSO`?

**Comment by sjpadgett** [comment]
native loaded rxcui is loaded in codes table.

**Comment by sjpadgett** [comment]
Okay so we can't say I took easy way here I added native loaded RxCUI for lookup. 
- if a code set is not enabled then radio will disable for that code set.

Will merge shortly.

image

**Comment by bradymiller** [comment]
2DV (1)

**Pull request merged**
