### PR TITLE
PHPCBF Autofixed Code Standards

### PR DESCRIPTION
**Pull request by robertdown**
Run via:
`phpcbf -n --extensions=php
--ignore=*/vendor/*,*/gacl/*,*/bower_components/*,*/node_modules/*,*/public/assets/*,*/Documentation/*,*/tests/*,*/images/*,
--standard=phpcs.xml --tab-width=4` .

### CODE REVIEW

**Comment by stephenwaite** [comment]
pretty cool way to clean up

**Comment by robertdown** [comment]
I spot checked a bunch of different points in this PR and it looks good to me.... @bradymiller this (although automated, and touching thousands of files) seems like a fairly safe PR. How do we really test every file that's changed? I propose we test the code in a few places, ensure it's working as expected and merge. Of course it'd be good to have 3 people look at it, just because it's such a large commit

**Comment by bradymiller** [comment]
I'll spend some time looking through this (I also plan to look at the file list in more detail to ensure no weirdness there). There is a commit by Matrix that I would like to get in before bring something like this in (since it will be tough to do any code merging after we do this); ie. would basically repeat the run when we have a window with no large commits pending. Gonna notify couple others to get opinion on how to go about this:
@MatthewVita @sunsetsystems

**Comment by bobinson** [comment]
I am running with these changes for couple of days based on the latest code, did a high level testing and couldn't find issues  (Disclaimer: I have limited know how of the software).
My environment : macos, PHP7.1, Apache 2.4, MariaDB

**Comment by bradymiller** [comment]
Plan to hunt down the 3rd party library dirs/files since plan to ignore those places.

**Comment by robertdown** [comment]
Yeah, I think a couple of 3rd party libs were in non-standard locations so they were probably included

**Comment by MatthewVita** [comment]
Should we have a plan for helping folks update their forks and fork branches? I realize most will know how to do this, but we should at least give a fair warning because this will cause every forks branch to conflict upstream.

**Comment by MatthewVita** [comment]
Where would be the best place to announce this?

**Comment by robertdown** [comment]
Yes, we'll definitely make several announcements with plenty of notice well in advance of the change. It will definitely break upstream commits, which will require (likely) a rebasing of all forks. We've got some time before we reach that point though

**Comment by MatthewVita** [comment]
Would the forums be the best place for this announcement when we get there?

**Comment by sjpadgett** [comment]
If you could include the short but sweet guide @bradymiller gave me to clean up and keep clean my git, it becomes really easy and it sticks. May be in developers manual already but including it in announcement will help I'm sure.

**Comment by robertdown** [comment]
Forums will probably be best

**Comment by robertdown** [comment]
As well as reaching out to our most active developers personally and notifying them of the change

**Comment by bradymiller** [comment]
If somebody does get left behind(or is basing a lot of customized code on OpenEMR), then will be good to make clear the exact phpcbf command that was used(when we have it, of course), which may get them out of trouble.

**Comment by bradymiller** [comment]
btw, here's the quick set of commands I sent to Jerry to clean a local master branch:

A messy master branch is a relatively common issue. Two steps to fix this are, 1) clean up the master and then 2) ensure keep the master clean.
``````
step 1 (basically will drop your master branch and bring in a clean master branch):
git fetch upstream
git checkout -b temp
git branch -d master
git checkout upstream/master
git checkout -b master
(you now have a clean master that was taken from the main codebase)
And can then push this to your origin on github:
git push origin +master

step 2 (whenever update your master, use the following):
git checkout master
git fetch upstream
git pull upstream master
git push origin master
``````
You should never merge into your master and should never do work on the master. Then when you create a branch from master, it will be pristine.

**Comment by MatthewVita** [comment]
Looks good @bradymiller

**Comment by stephenwaite** [comment]
agreed, i think i'll add this to the git for dummies openemr wiki

**Comment by stephenwaite** [comment]
github can't reference individual comments, bummer....

**Comment by bradymiller** [comment]
Another git tip :)
I can't live without the following alias stuff in the .git/config script (I heavily use lf, which give an awesome view of a branch, merge paths etc:
``````
[alias]
        st = status
        ci = commit
        br = branch
        co = checkout
        df = diff
        lg = log -p
        lf = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative

``````

**Comment by TheToolbox** [comment]
Where is the state of affairs with this process or #492? I'd love to add phpcs to the CI pipeline (and tests soon after) so that nobody has to be checking style in reviews.

I have a [branch](https://github.com/TheToolbox/openemr/tree/ci) (with commits that need to be squashed) running phpcs (which has a weird ldap extension dependency). This can be done by adding the following to the `.travis.yml` script section:
```yaml
      - echo "extension = ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      - composer require "squizlabs/php_codesniffer=*"
      - ./vendor/bin/phpcs -p --standard=phpcs.xml --report-width=120 --report=source --report=info --report=summary .
```

Additionally, there are a few things that aren't enforced that might be reasonable to add, depending people's feelings:
 - spaces surrounding assignment operators `$var=3;` => `$var = 3;`
 - enforcing all (code?) files requiring doc comments

**Comment by bradymiller** [comment]
@robertdown will be very happy to see interest in this. Should we proceed with PHPCBF automatic conversion of the codebase before enforcing it on CI? The next OpenEMR release will likely be in 6-8 weeks, so now would be a good time to do this.

**Comment by TheToolbox** [comment]
I'd definitely agree with merging a phpcbf-ified version of the code (although we probably want to do that on as updated a master as possible) before flipping the switch on CI. What are the current blocks for this?

**Comment by bradymiller** [comment]
I think the only bottleneck is identifying the 3rd party scripts not within /vendor. I can likely do a quick screen (via human eyes) to identify those. There are 2 big ongoing code reviews (weno and medex) that can easily deal with this (since they are only touching a couple main scripts). There is another minor code review with acl that may be somewhat more impacted(but also should be straightforward to deal with). I think, though, now is a good time to do this to ensure enough testing time before the next release.

**Comment by bradymiller** [comment]
Whoever does this commit will pretty much have an undefeatable record of files touched in 1 commit :)

**Comment by TheToolbox** [comment]
Seems like a good time to push all 3rd party code into /vendor as well then! Seems only fair that @robertdown would get the honor, since he's the one who started the process.

**Comment by TheToolbox** [comment]
it's also worth noting ./phpcs.xml has a set of directories to ignore already, so we can build on those.

**Comment by bradymiller** [comment]
I think we've pushed all third party packages that didn't require mods and can be installed via composer already to /vendor
(goal is to not touch anything in vendor and allow it to be fully populated by composer at some point in the distant future)
they are tracked here:
http://www.open-emr.org/wiki/index.php/Composer#Dependencies_to_migrate

I think most of the third party packages that are left outside vendor required mods to work.

-brady

**Comment by bradymiller** [comment]
good point on phpcs.xml and good point on @robertdown getting the honors

**Comment by robertdown** [comment]
I'd be honored! [Commence global takeover in 3...2...1...] 😆

**Comment by bradymiller** [comment]
here's a quick listing of 3rd party packages not in above phpcbf command:
library/html2pdf/
library/classes/fpdf/
library/classes/smtp/
library/classes/PDF_Label.php
library/custom_template/
library/fonts/

**Comment by bradymiller** [comment]
waiting for global takeover :)

**Comment by TheToolbox** [comment]
Should this PR be closed and a new one started? or is there a smart rebasing way to bring it up to date without a huge merge?

**Comment by bradymiller** [comment]
@TheToolbox
We can keep this PR. @robertdown will basically run the command on the most recent codebase and then do a force push into the branch for this PR. So, will just have 1 mega commit on top of the most recent codebase, which we will quickly bring in (maybe a day of sanity testing), and announce that new projects need to work from the most recent codebase(and I'll help weno and medex code get updated) to avoid massive merge conflicts.
-brady

**Comment by TheToolbox** [comment]
Ah of course. Good luck @robertdown!

**Comment by MatthewVita** [comment]
Great job!

**Comment by MatthewVita** [comment]
@TheToolbox and I were just saying how nice it is to see this in place. Will make life easier moving forward and CI is always a great option here too

**Comment by robertdown** [comment]
Thanks! Hopefully we get the phpcs script into CI soon, shouldn't be a problem now that the codebase is basically up to standards

**Pull request closed without merging**
