### PR TITLE
adding more warnings for missing demographics in X12 837.

### PR DESCRIPTION
**Pull request by stephenwaite**
adding more warnings for missing demographics in X12 837 like when claims would fail for missing city state zip, this way can see the trouble in the log and while the claims are still selected in the billing manager can navigate to the pt demos and fix and then regen the x12 837

### CODE REVIEW

**Comment by stephenwaite** [comment]
it's testing fine

**Comment by sjpadgett** [comment]
Brought in for ya.

**Comment by stephenwaite** [comment]
nice, thank you Jerry

**Comment by stephenwaite** [comment]
hi @sjpadgett , Cady in my office just mentioned your red shading of those folks in the billing manager that are missing some important demographics. It's really cool, thanks.

**Pull request merged**
