### PR TITLE
Applying PSR Code Standards

### PR DESCRIPTION
**Pull request by robertdown**
See #657 for more details, had a hiccup with github.

### CODE REVIEW

**Comment by bradymiller** [comment]
sorry, couldn't help myself:
1mng0gxc5tpcs

**Comment by TheToolbox** [comment]
For reference, the vast majority of remaining errors seem to be: `The opening PHP tag must be the first content in the file`, which I'm sure coincides with a lack of file documentation comments as well, and will be trivial to fix manually (< 30 instances I believe)

**Comment by matrix-amiel** [comment]
@bradymiller @robertdown 
Hi.
This commit contains changes in sqlconf.php file and it cause to conflicts in installed projects.
What do you recommend to do? I think it is right to revert this file.

Thanks
Amiel

**Comment by bradymiller** [comment]
hi @matrix-amiel ,
Another large code styling commit is coming into the codebase in the next day or two that will touch this file again. Lets reassess this issue at that point.
-brady

**Pull request merged**
