### PR TITLE
replace old calendar with the new one

### PR DESCRIPTION
**Pull request by avi-matrix**
when adding a new issue in the patient file, it uses the old datepicker, which is not usable in rtl languages in ie.
this change replaces the old datepicker with the new one introduced in openemr, which fixes the problem.

### CODE REVIEW

**Comment by bradymiller** [comment]
hi,

This was already done in the most recent codebase. check out this commit(was checked into main codebase 5 days ago):
https://github.com/openemr/openemr/commit/55dcc8af4589ead345deae7647bf7f053e0a4b82

Let me know if that works for you and then will close this PR.

thanks,
-brady

**Comment by bradymiller** [comment]
@avi-matrix , Let me know if I can close this pull request (since this script has already been converted to the new date picker).

**Comment by avi-matrix** [comment]
thank you, you can close this pr

**Comment by bradymiller** [comment]
@avi-matrix,
as an aside, there is now a mechanism in place to also support formatting of the actual input field. Placed an example in the following PR:
https://github.com/openemr/openemr/pull/502

**Pull request closed without merging**
