### PR TITLE
fix: easy development docker environment - allow development and testing in public folder

### LINKED ISSUE #6147: bug: Logo service throwing fatal error when images_static_absolute/logos/$type is not found
When the changes made for PR #6135 were brought it appears to break existing docker installations.  Supposedly the public folder is set in our docker-compose to be read/write but when I pulled down the latest codebase on an existing docker launched from our development-easy environment I'm getting the following fatal errors:

PHP Fatal error:  Uncaught Symfony\\Component\\Finder\\Exception\\DirectoryNotFoundException: The "/var/www/localhost/htdocs/openemr/public/images/logos/core/login/primary/" directory does not exist. in /var/www/localhost/htdocs/openemr/vendor/symfony/finder/Finder.php:592\nStack trace:\n#0 /var/www/localhost/htdocs/openemr/src/Services/LogoService.php(100): Symfony\\Component\\Finder\\Finder->in()\n#1 /var/www/localhost/htdocs/openemr/src/Services/LogoService.php(75): OpenEMR\\Services\\LogoService->findLogo()\n#2 /var/www/localhost/htdocs/openemr/interface/login/login.php(47): OpenEMR\\Services\\LogoService->getLogo()\n#3 {main}\n  thrown in /var/www/localhost/htdocs/openemr/vendor/symfony/finder/Finder.php on line 592

I can see that the directory /var/www/localhost/htdocs/openemr/public/images/logos/core/login/primary/ does not exist in my docker image, but it does exist in the mapped underlying OS /home/ubuntu/openemr/public/images/logos/core/login/primary/

I haven't tested this on the production docker images but I think we should probably figure out what is going on here before the changes @robertdown made for the logos get pulled into a release patch.

@bradymiller If you have any ideas here on whether this is something oddly configured in my environment, or if this is something we need to fix in code or with the dockers that'd be great.

### PR DESCRIPTION
**Pull request by bradymiller**
fixes #6147

For the easy development docker environment, allow development/testing in the public folder

### CODE REVIEW

**Comment by robertdown** [comment]
Why only do this for two folders? We have several inside of public:
* assets
* certs
* fonts
* images
* smart-styles
* themes

Why have a volume for each of those?

**Comment by bradymiller** [comment]
It's part of the docker black magic that allows development/testing directly from a developer's openemr git repo. By using volumes within volumes, we are effectively hiding things in the docker that the host git repo can not see (the pitfall though is that changes in these places on the host will not be in the docker). Those 2 new shared volumes are put there to hide them in the docker and not show from the host repo (so if I were to make a commit it would not include this stuff in the commit). When we were doing the entire public directory this meant that if developers made changes to anything in that directory on their git repo that these changes would not be made in the docker environment.

**Comment by bradymiller** [comment]
btw, the way in think about this (for it to make some sense).
The main openemr folder is set to a volume that is on the host

Then if i make openemr/public/themes a shared volume (ie. a volume within a volume), then following happens:
1. When make changes to the themes directory in the docker, these changes are stored on the shared volume and for some reason are not changed on the host
2. When make changes to the themes directory in the host, these are not stored on the shared volume and are not changed on the docker

**Comment by stephenwaite** [comment]
so the easy dev isn't easy for working on themes since you'd have to either work entirely inside of the docker or `docker cp` them in

**Comment by bradymiller** [comment]
Note that themes (and assets) are part of the build, so there should be no reason to need to "develop" in those places. A better example would be the following 2 places:
public/assets/modified (directly that hold at this point just one asset that required manual changes)
sites (this is a good one to know in case making script changes in sites/default/)

So, if for example you made changes to something in the sites directory, then you would need to directly modify it also within the docker itself (ie. the price that is paid to test/develop from same repo; if were doing significant work in that directory would change workflow a bit where separate the development and testing).

**Comment by stephenwaite** [comment]
remember being flummoxed when working on `sites/default/statement.inc.php` :)

**Comment by bradymiller** [comment]
I'll bet :) Why are my changes not registering??? Maybe it is the cache??? Still not working even after resetting cache ... :)

**Comment by stephenwaite** [comment]
one more comment since this is the place to chat today, my vote for most seen console err:
Screenshot from 2023-01-31 16-39-27

**Comment by bradymiller** [comment]
testing well and bringing in

**Comment by bradymiller** [comment]
@stephenwaite , dang, i just made same mistake on the PR (it defaulted to use commit comment instead of the PR name so didn't get the `fix:` on it)

**Pull request merged**
