### PR TITLE
Issue Fix #2947: Add dark and superhero themes

### LINKED ISSUE #2947: Step 7 in setup.php need to add selections for the 2 new themes
Need to add selections for two recently added themes:
Dark
Superhero

image

### PR DESCRIPTION
**Pull request by stu01509**
Fixed Issue: #2947
Add dark and superhero theme screenshot.
Untitled

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @stu01509 

dark should look something like this:
image

and superhero should look something like this:
image

**Comment by bradymiller** [comment]
@stu01509 ,
Let me know if it is looking different on your install. Note you can change to these themes in Administration->Globals->Appearance->General Theme
(rec doing logout/login when change the theme)

**Comment by stu01509** [comment]
@bradymiller 
I have been modified screenshot file, Thank you :)
Untitled

**Comment by bradymiller** [comment]
hi @stu01509 , Looks good and bringing into codebase! It just hit me that all the other screenshots are outdated (we recently had a large code factor to support bootstrap 4 and sass styling and it changed all the login screens for all the styles); let me know if your up for updating them all (note this is totally optional since it's a super tedious thing to do and is very low impact; ie. no biggie to just let them stay outdated since they are close enough).

**Comment by stu01509** [comment]
Hi @bradymiller , I created another PR to updated all theme screenshot, Please check it.

**Pull request merged**
