### PR TITLE
New ACO for custom reports  

### PR DESCRIPTION
**Pull request by matrix-amiel**
Hi.

I added new ACO that allows to see the hooks of zend modules in the menu in the report label.
Without this fix only admin can see those.

Thanks.
Amiel

### CODE REVIEW

**Comment by sunsetsystems** [comment]
This is missing a few things:
1. In acl_setup.php add the new ACO to default permissions for Administrators.
2. Corresponding changes are also needed in acl_upgrade.php and version.php.
3. Corresponding changes are also needed in menu_data.php.
4. Add the new ACO to the comments in acl.inc. This is where we've been keeping track of them all.
For examples of doing all the above, see this commit:
https://github.com/openemr/openemr/pull/530/files

**Comment by matrix-amiel** [comment]
I've pushed better solution.. I think..
with this code we can add permission for any hook with the exist zend ACL tables.
what do you think?

**Comment by sunsetsystems** [comment]
I'm not familiar with the ZH ACL tables, but if it works then it seems OK to me.  However you are still missing a solution for the tab style menus; again, see the commit I referenced for some example code.

**Comment by matrix-amiel** [comment]
o.k. I think tabs menu doesn't support zend hooks in the report label.. but I will check..

**Comment by sunsetsystems** [comment]
I'm guessing you want to look at interface/main/tabs/menu/menu_updates.php.

**Comment by bradymiller** [comment]
I think this is the only thing that is missing in the tabs interface (support for the Zend module report hooks)
Also, note that the Travis CI tool(the thing at bottom of this screen showing All checks have failed) noted a php parsing error. See the bottom of this screen for details on the php parsing error: https://travis-ci.org/openemr/openemr/jobs/213558691

**Comment by matrix-amiel** [comment]
Hi.
I fixed the error and also I allow access for admin for all hooks.
So let's merge it without the tabs menu and we fix it in the future when the menu will support zend hooks..

**Comment by sunsetsystems** [comment]
OK I see menu_updates.php generates zend menu items for modules but not reports.  Seems puzzling but I'm OK with leaving that for another day. I expect you have tested so will merge it.

**Pull request merged**
