### PR TITLE
Pin tab feature

### PR DESCRIPTION
**Pull request by eyalvo-matrix**
This feature enables to bind an alert before closing a tab in the system 
The functionality works from anywhere in the system as long as pin_tab.js 
is available in the code scope    

pinTab function receive (Tab name, Message, 0/1 to alert when patient is being switched)

Usage Example:
run in the console (inspect element X of a tab)
pinTab('pat','please babe dont close me','1');
try to close "search or add patient" tab  
to disable message: 
unpinTab('pat');

msg

### CODE REVIEW

**Comment by matrix-amiel** [comment]
I just note that the goal of this feature is to prevent closing of tab in the middle of working on form.
This feature also enables to prevent moving between patients because the moving close all the forms of the encounter and remove them without saving.

**Comment by matrix-amiel** [comment]
Hi @bradymiller 
I added an example of the use in the Care plan, I hope the feature will be more clear now. the tab of the form can't be closed if something in the form is changed.
I think this can be a very useful feature.

**Comment by bradymiller** [comment]
bump

**Comment by bradymiller** [comment]
double bump

**Pull request closed without merging**
