### PR TITLE
Upgrade with special sql

### PR DESCRIPTION
**Pull request by eyalvo-matrix**
Short description of what this resolves:
Adding 2 tags #SpecialSql and #EndSpecialSql for the upgrade module script 

Changes proposed in this pull request:
With the new tags one can now run install and upgrade of the modules 
which contains SQL with semi-column and SQL procedures  

[Example](https://www.php.net/manual/en/mysqli.quickstart.stored-procedures.php) 
```
DROP PROCEDURE IF EXISTS p;

#SpecialSql
CREATE PROCEDURE p(IN id_val INT) BEGIN INSERT INTO test(id) VALUES(id_val); END;

#EndSpecialSql
```

Few words about mysqli and PROCEDURE
1. mysqli does not support DELIMITER
2. using "--" to write comments inside PROCEDURE did not work either

### CODE REVIEW

**Comment by eyalvo-matrix** [comment]
another example for a more complex test 

,,,

DROP PROCEDURE IF EXISTS PatientSumMinimal;

#SpecialSql

CREATE PROCEDURE PatientSumMinimal(
    IN p_facilities VARCHAR(255),
    IN p_from_date DATE,
    IN p_to_date DATE
)
BEGIN
	select
			f.name AS facility_name,
			(select pc_catname from openemr_postcalendar_categories opc where opc.pc_catid = fe.pc_catid) as sug_bikur,
			COUNT(1) AS count_patients
	from form_encounter fe
	LEFT JOIN facility f ON f.id = fe.facility_id
	WHERE fe.date BETWEEN p_from_date AND concat(p_to_date, ' 23:59:59') AND
		(
			FIND_IN_SET(fe.facility_id, p_facilities) > 0 OR p_facilities IS NULL
		)
	GROUP BY
		f.name,
		fe.pc_catid ;
END;
,,,

**Comment by bradymiller** [comment]
hi @eyalvo-matrix , merge conflict needs to be addressed. thanks! -brady

**Comment by eyalvo-matrix** [comment]
Hi @bradymiller  I fixed the merge conflict , thanks for noticing

**Comment by bradymiller** [comment]
hi @eyalvo-matrix , Code looks good and bringing this in. thanks! -brady

**Pull request merged**
