### PR TITLE
Feature/docs

### PR DESCRIPTION
**Pull request by robertdown**
Following the instructions on [Read The Docs](http://docs.readthedocs.org/en/latest/getting_started.html), this PR sets up `docs/` at the top level and inserts the basic files required to build documentation. It also contains the first few documentation changes. Goal is to centralize our documentation into a sphinx-backed (Based on RTD) Markdown system.

See [openemr.readthedocs.org](openemr.readthedocs.org)

### CODE REVIEW

**Comment by bradymiller** [comment]
Hi Robert,
The docs look really nice, but all the current documentation is kept on the wiki(and a huge number of documentation is there). Because of this, doesn't seem like will be very helpful and would hate to have to maintain docs within the project and on the wiki. Note the wiki also allows non-developers to add to the documentation in a visual fashion. Is there any way to try to combine these things (wiki docs and the docs within the codebase) in order to create these nicely formatted docs without any additional work?
-brady

**Comment by robertdown** [comment]
I'd happily work on converting from wiki to these markdown based docs; most projects keep their documentation inside the repo anyway. There's a great utility called `pandoc` that allows easy conversion to/from various text formats. I used this to convert 95% of the pages in this PR and then went in by hand and tidied up the last 5%. This has a couple of benefits. First, it allows us to get eyes on all of our docs and make sure they are up-to-date. Second, It gives an opportunity to improve the docs, it's always good to review documentation.

As for keeping two separate doc bases (which is unreasonable), updating these docs is actually very easy. A user can actually do it right on GitHub (they support editing files inline and since this is just a text file it's simple. It's essentially the fork/edit/PR we all know and love.

**Comment by robertdown** [comment]
Actually, it's even easier than I thought, RTD has an "Edit" button built in to the docs, although it's not working right now (I think it's because I have RTD setup to read from my feature branch and not the master branch)

**Comment by tmccormi** [comment]
Robert,
   The community choose to do the wiki model so that non-programmers would
participate.  Github and merging changes is and was a big barrier to that
process.  We appreciate the idea, but the wiki is a better place for the
documentation to reside, in my opinion.

  Our master source code is not kept on GitHub, just a copy so we can use
the pull requests and diff tools.

Tony

-- 
Please be aware that e-mail communication can be intercepted in 
transmission or misdirected. Please consider communicating any sensitive 
information by telephone.  The information contained in this message may be 
privileged and confidential. If you are NOT the intended recipient, please 
notify the sender immediately with a copy to hipaa-security@mrsb-ltd.com and 
destroy this message.

**Comment by robertdown** [comment]
Can we run some statistics to see if the wiki is being contributed to by a significant number of non-programmers? It seems that the entry would be about the same between learning wiki and markdown, especially considering RTD has the edit button which takes the user right to the markdown source.

If it turns out that the wiki is being contributed to mostly by programmers I say we reconsider this issue. Github allows such a fluid workflow it is worth reviewing, in my opinion.

**Comment by tmccormi** [comment]
The wiki is mostly maintained by Harley and FSGL.  They are both
non-programmers

Tony

-- 
Please be aware that e-mail communication can be intercepted in 
transmission or misdirected. Please consider communicating any sensitive 
information by telephone.  The information contained in this message may be 
privileged and confidential. If you are NOT the intended recipient, please 
notify the sender immediately with a copy to hipaa-security@mrsb-ltd.com and 
destroy this message.

**Comment by bradymiller** [comment]
Agree most of the valued wiki work is by Harley and FSGL whom would not do well on github(this stuff becomes intuitive for most developers, but others are at a loss).
http://www.open-emr.org/wiki/index.php/Special:ActiveUsers

**Comment by bradymiller** [comment]
Hi Robert,

Can these nice type of docs be creating for the development docs, though?

I was doing this in the past with 'phpdoc', which is documented here:
http://www.open-emr.org/wiki/index.php/OpenEMR_API

Would be nice if there is a more modern tool out there.

-brady

**Comment by robertdown** [comment]
PHPDoc is still the king of PHP auto-documentation. Here's some templates http://phpdoc.org/templates. I'll generate some docs and see what we can do. The big difference between the Wiki documentation and the developer docs is the automation factor. I'll see what I can do over the weekend

**Pull request closed without merging**
