### PR TITLE
Certification Tests & Test dir cleanup

### PR DESCRIPTION
**Pull request by MatthewVita**
**TODO:**
1. ~~update md file to mention to do “ctrl-f” to search for OpenEMR feature mappings in this document~~
2. ~~create a list (github comment is fine) with OpenEMR major features and any minor features to match with MU tests~~
3. ~~enter some feature mappings to serve as an example~~
4. ~~merge early version into master to get things started~~
5. ~~update http://open-emr.org/wiki/index.php/Development_Policies#General_Development_Best_Practices testing area~~
6. ~~let Robert know about the new "unit" folder~~
7. finish feature mappings
8. Map Newcrop and other 3rd party testing tools in the tools column.
9. Integrate Visolve's test videos in with the "Testing Procedures" column.
10. inform community of this document so they are aware of it for regular development and certification testing later on
11. update project page to complete
12. think about additional data that would possibly be useful: relevant pages, more test videos, more test cases (similar to what Visolve put together)

### CODE REVIEW

**Comment by MatthewVita** [comment]
Hi @bradymiller,

Please see my TODO list above. You can see the new folder here: https://github.com/MatthewVita/openemr/tree/tests/Tests and (most importantly) the new test mappings document here: https://github.com/MatthewVita/openemr/blob/tests/Tests/certification/tests.md

I hope I can bug you to help me map MU tests to OpenEMR features :)

Thanks,
Matthew

**Comment by bradymiller** [comment]
Hi Matthew,

I like where this is headed, however, those scripts may be a bit complicated and in some cases require third party modules (such as Newcrop) or 3rd party testing tools(such as Cypress for CQM calculations). Also note the pdf links to the testing scripts may change as the version is upgraded.

Would it make sense to change Test to test since making all the other changes anyways.

Regarding feature mapping, just flag the ones that you are not sure of, and I can provide some off the top of my head details.

**Comment by bradymiller** [comment]
And just let me know if you want me to bring this into the codebase. Glad to bring it in even though it is still under construction.

**Comment by MatthewVita** [comment]
Thanks for the response. I will add a testing tools column and will start to add the feature mappings once the site is done :)

- Matthew

**Comment by MatthewVita** [comment]
@bradymiller,

I just added more data to the document. Still a lot of gaps, but please review and, perhaps, check in this early version of the document to start things off.

Thanks,
Matthew

**Comment by bradymiller** [comment]
@MatthewVita ,

Looks like a good starting point. The OpenEMR Test Procedure links are a great idea since these are the clear steps to follow in OpenEMR. There are actually 5 videos for 5 of the MU2 items that were just made for the ongoing usability testing. When we are done, I'll ensure Visolve places them somewhere permanent, so we can link to those (note that several of the MU2 items requires use of the third party Newcrop module, so will not be able to feasibly enforce testing of this; but this is only on several of the items).

I committed this to the codebase. Do you want me to keep this PR open to track this or do you want me to close this PR?

thanks,
-brady

**Comment by MatthewVita** [comment]
Hi Brady,

Thanks for committing this as a starting point. Let's keep the PR open as it has a master TODO list at the root comment.

Here's some responses to your post as well as other items for discussion:

- I think it would make sense to link those videos in the "Testing Procedures" column. Let me know when they are formalized. For now, I'm adding it as a task to the TODO list at the root comment.
- With respect to the Newcrop tool, I did a search for "tool" in all of the MU pdfs and only found the NIST stuff. Can you map the Newcrop to the appropriate cells and link it to a new wiki page explaining who to contact to get ahold of the tool. I realize there are probably finite licenses but this tool should be captured in the table.
- I'm having a hard time mapping OpenEMR features to MU "Drug-drug, drug-allergy interaction checks" tests. I can't find any matching feature on the master OpenEMR features list... am I missing something?
- Do you know of any wiki pages or documents containing information on how to test/use HL7 with Clinical decision support?
- I got in touch with Free Code Camp about getting a team together to work on this project. It's purely a QA project so I figured there are surely folks interested in starting a career in QA and need experience. Free Code Camp said we need to be formally blessed by the IRS as non-profit before moving forward. My thought/pipedream is that I can manage a small team that makes test cases like those Visolve provided for some of the MU items. Would also be nice to fill in gaps where video recordings of testing would be useful. This wanted to mention this for the sake of completeness. No actionables for this at the moment. Would also serve my personal agenda of getting this work done quicker so I can get to focus on the fun stuff with Robert (Zend modernization project :) )

Thanks,
Matthew

**Comment by bradymiller** [comment]
Hi Matthew,
Yep, the non-profit thing is not helping things. I am optimistic we will be getting it in a month or so (due date for next information request is 9/1 and they actually responded to our last one within a couple weeks), so hopefully will get good news there soon. I will keep the above pertinent stuff as a TODO for me which I should be able to hack away at during my downtime.
thanks,
-brady

**Comment by MatthewVita** [comment]
@robertdown please note the recently checked in https://github.com/openemr/openemr/tree/master/tests/unit folder. Figured you'd want to know about this with your work on the modernization efforts (yaay unit tests!)

-Matthew

**Comment by robertdown** [comment]
Closing this since outdated PR

**Pull request closed without merging**
