### PR TITLE
Improved Code Sniffing

### PR DESCRIPTION
**Pull request by TheToolbox**
This makes `ci.sh` a little more robust:

 - Adds `lint_style_new_code` as an option for `CI_JOB`, which uses the full ruleset of PSR2, so all *new or modified* code will be compliant, even if older code can't be converted right now. This is run by Travis. This **behavior change** seems reasonable to me, but I want to highlight it because it will require modified files to be cleaned when they're changed.
 - Adds `lint_style_staged` as an option for `CI_JOB`, which runs PSR2 sniffing over staged files, meant to be used by devs before they commit. I still recommend installing an editor extension to help you as you write, as well as running `ci.sh` with all options before pushing to ensure Travis will be happy with you.

Notable, but not part of this PR is the fact that there are many codesniffs (most whitespace sniffs, no-inline-control-statements) that can be automatically fixed, but were not caught during the last phpcbf due to the permissive settings currently in `phpcs.xml`. The possibility of iterating over those might be worth discussing, as would the possibility of adding a `auto_fix` option in `ci.sh ` for pre-commit use.

### CODE REVIEW

**Comment by TheToolbox** [comment]
This would make the common workflow for changes something like 
```bash
code interface/somefile.php
git add interface/somefile.php
CI_JOB=lint_style_staged ci/ci.sh && git commit -m "This commit passed PSR2!"
```
I'll update the wiki (unless @MatthewVita has a burning desire to) if this PR gets merged.

**Comment by robertdown** [comment]
Not sure we can expect a dev to run any extra commands on code before committing. However, most IDEs have some type of linting baked-in. For instance, PHPStorm gives me real time feedback in the IDE based on phpcs.

**Comment by bradymiller** [comment]
To clarify:
Will this require developer to do extra steps on commit?

Also, should we substitute ci/phpcs.xml with ci/phpcs_strict.xml and do a run and bring this into the codebase (then we are officially PSR2 and the phpcs_strict.xml looks nice and clean too) ?

-brady

**Comment by TheToolbox** [comment]
This does not require any extra steps. All it really does is simplify the [instructions for running CI tasks locally](http://www.open-emr.org/wiki/index.php/Continuous_Integration), as well as add stricter settings for new commits. I would be totally on board with pushing PSR2 to the whole codebase, and last night I gave it a try, rule by rule. The issue is that there are a good number of rules that are not automatically fixable (i.e. camelcase rules). The additional whitespace/control structure rules I would certainly recommend for inclusion, as I was able to get them all running last night without too much effort.

**Comment by bradymiller** [comment]
Sorry for not completely understanding this code. When you say "Add stricter settings for new commits" what do you mean?

**Comment by TheToolbox** [comment]
The current `phpcs.xml` is actually very permissive. For example, it will not correct inline control statements, which is a big PSR2 rule. The code that I applied tells Travis to check any new or modified code against `phpcs_strict.xml`, which is the full ruleset of PSR2.

**Comment by bradymiller** [comment]
thanks for the quick explanation.  so, if i made a quick security fix in a script, would i then be on the hook to ensure entire script was psr2?

in addition to the inline control statements, which other psr2 rules could we support automatically?(makes sense to get these into the codebase and id rec a seaparate mega pr to bring these in :) )

**Comment by TheToolbox** [comment]
You would be on the hook for that yes. If it was time sensitive or you otherwise felt that that burden would be inappropriate, you could add the file to the ignore patterns in `phpcs_strict.xml`.

There are a great number of whitespace rules that are not currently enforced (space after comma in function call, after semicolon in for loops) that would improve things quite a bit. I killed the branch I was experimenting on last night, since my methods were fairly dirty, but I'll try to put a new list together systematically tonight.

**Comment by MatthewVita** [comment]
@robertdown PHPStorm didn't have any built in mechanisms as far as I could tell, so I've been doing it the old fashioned way: http://www.open-emr.org/wiki/index.php/Continuous_Integration

:)

**Comment by robertdown** [comment]
We need CI for sure, but it is possible to see what's going on at the developer-level as well. https://www.jetbrains.com/help/phpstorm/code-sniffer.html

**Comment by sunsetsystems** [comment]
I don't much care for creating a lot of new work for developers who just want to fix something. Would rather see standards compliance as a separate project.

**Comment by TheToolbox** [comment]
My apologies for some of the confusion above, as my intent was to add zero overhead over the current expectation to conform to PSR2. The hope is that this would actually reduce work for new developers (like me!), since as it is right now, I don't know of my code style violations until someone notes it in review. This way, they get feedback from CI faster. I shouldn't have included the example bash script above. It's absolutely not a required (nor even necessarily recommended) usage, but rather just a simplification for those working with workflows like @MatthewVita's.

**Comment by bradymiller** [comment]
Hi @TheToolbox ,

Recommend removing the part of this code that puts developers on the hook for cleaning up scripts that they touch. This is something that can be revisited in the future when the codebase is more mature on the modernization front. Otherwise, this will bottleneck stuff and developers will avoid touching the legacy scripts. For now, would instead make sense to start getting developers(including ourselves) to hook the ci/phpcs_strict.xml script into their editors, so we can start to migrate over to full psr2 support over time(ie. gives developers time to acclimate and learn all this new, cool stuff).

Definitely agree, though, with optimizing entire codebase as much as possible to follow as much psr2 rules as possible via the automated script(hopefully in 1 more mega-commit run, of which you will get the honors :) ). 

-brady

**Comment by bradymiller** [comment]
as an aside, are we getting close to supporting phpunit testing via ci(there's some phpunit tests in tests/unit, but haven't been used for about 5 years or so).

**Comment by TheToolbox** [comment]
This above commit leaves in the improved usability of ci.sh, but now prevents CI from strictly checking modified files. An exercise for the developer for now!

**Comment by bradymiller** [comment]
looks good! will bring into codebase.

**Pull request merged**
