### PR TITLE
incrementing to 7.0.0-dev in master to prepare for 6.1.0 release

### PR DESCRIPTION
**Pull request by bradymiller**
incrementing to 7.0.0-dev in master to prepare for 6.1.0 release

### CODE REVIEW

**Comment by bradymiller** [comment]
btw, here's the release checklist; goal is release of 6.1.0 in about 2 weeks:
https://www.open-emr.org/wiki/index.php/QA_and_Release_Process#Version_6.1.0

If interested in release process, can also check this out:
https://www.open-emr.org/wiki/index.php/Steps_for_an_official_release

**Comment by stephenwaite** [comment]
can help with `Mastodon` :()

**Comment by bradymiller** [comment]
you are officially responsible for the TOOT! :)

**Comment by sjpadgett** [comment]
attaboy

**Pull request merged**
