### PR TITLE
Adding loop 2420E ordering provider

### LINKED ISSUE #7403: Ordering Provider Loop 2420E missing
### Describe the problem

In building a 837 claim, the ordering provider information is missing. It can be set in the MBO but the information is not pulled to the claim in that loop.  

### Describe the solution you'd like

Pull the information form the MBO into the claim.

### PR DESCRIPTION
**Pull request by juggernautsei**
Fixes #7403 

#### Short description of what this resolves:
Adds loop 2430E to the 837 claim

#### Changes proposed in this pull request:
Add loop 2430E

### CODE REVIEW

**Comment by juggernautsei** [comment]
Hi @stephenwaite, that means there has to be an interface to select the ordering provider. Is that correct?

**Comment by stephenwaite** [comment]
think something like [PR 7405](https://github.com/openemr/openemr/pull/7405)

Be nice if we could setup a trigger on the insurance to help with the selection...

**Comment by juggernautsei** [comment]
> Be nice if we could setup a trigger on the insurance to help with the selection..

@stephenwaite the trigger would be ordering labs, or procedures or prescriptions. Those are the triggers. The question would have to be prompted in the system who is the ordering provider. There is no way to automatically know because those are verbal conversations. 

The key difference between a rendering provider and an ordering provider in medical billing (specifically for an 837 claim format) lies in their role within the patient's care:

    Rendering Provider: This is the individual or facility that directly delivers the service to the patient.

 They perform the examination, treatment, or procedure documented in the claim.

  For instance, if a patient undergoes a blood test, the lab technician who analyzes the blood is the rendering provider.

Ordering Provider: This is the healthcare professional who initiates the request for the service.

     They determine the need for the test, procedure, or equipment and authorize it for the patient.  Going back to the blood test example, the physician who decided the blood test was necessary would be the ordering provider.

In essence, the rendering provider is the one doing the service, while the ordering provider is the one who prescribed it.

Here are some resources that provide a more detailed explanation of these terms:

    National Uniform Claim Committee: https://www.nucc.org/
    Centers for Medicare & Medicaid Services: https://data.cms.gov/provider-characteristics/medicare-provider-supplier-enrollment/order-and-referring

**Comment by juggernautsei** [comment]
> Hi @juggernautsei. I thought it was for just 1 insurance, Oklahoma Medicaid?
Yes, that is true for Brad. That is why I posted the repo so he could get the code. It just become a habit to do a pull request.

**Comment by stephenwaite** [comment]
fixed in 0cbafca

**Pull request closed without merging**
