### PR TITLE
php8 fixes for batch payments

### LINKED ISSUE #5688: previous int cast fix prevented posting cents payments
### Describe the bug

in Batch payments a [php8 fix](https://github.com/openemr/openemr/blob/master/library/payment.inc.php#L64) to cast as int caused a logic error since the value could be cents which int casts to zero.

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #5688

### CODE REVIEW

**Comment by stephenwaite** [comment]
thanks to @surfacehazard for the report and fix

**Comment by stephenwaite** [comment]
if this looks like what's working for you @surfacehazard we'll bring it in

**Review by surfacehazard — CHANGES_REQUESTED** [review]
I think ceil() returns a float. Do you still need an (int) cast in front of it because of #4320?

**Comment by stephenwaite** [comment]
shouldn't, it's ok to compare 2 numbers (float and int) with >.

**Comment by sjpadgett** [comment]
ceil() will round up however you may want to ensure how the ceil() value signing is used further on in script. i.e is a negative float wanted!

**Comment by stephenwaite** [comment]
I guess an individual entry from the form could be a negative value, say an item is recouped, but overall the check is still a positive value (something to deposit and use batch entry in the first place) so we might want to use `abs()` instead so that the insert is distributed.

**Comment by stephenwaite** [comment]
makes more sense to use floatval instead

**Review by surfacehazard — APPROVED** [review]

**Pull request merged**
