### PR TITLE
feat: implement chart review mechanism

### LINKED ISSUE #6553: feature: use patient filter to assist remote chart review
### Describe the problem

Need to be able to limit the view for a remote user assigned to an insurance company for a chart review.

### Describe the solution you'd like

Use the neat patient filter mechanism originally contributed by @kchapple to create a blacklist of pids  of those people who have insurance based on that payer id.

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #6553

### CODE REVIEW

**Comment by stephenwaite** [comment]
testing well

**Comment by mdsupport** [comment]
When we implemented this requirement few years ago the concern was allowing an external user an access to internal interface. Pre-FHIR the closest restrictive interface available was patient portal. So we used the App approach to open portal as single tab in the main frame of main interface script. Instead of regular menu a drop down was added for patient selection where the the patient entries were fed by a sql recordset with user specific filter. This permitted a highly controlled view of data specific for multiple external users - basically a custom "custom report", documents and demographics.

@sjpadgett , this is one of the scenarios where portal as an module will be extremely useful. Maintenance and upgrades are simplified if the core code deals with data management that is increasingly becoming more complex.

Best.

**Comment by stephenwaite** [comment]
hi @mdsupport, where do you implement your features? Do you have your own customized version of OpenEMR? thank you

**Comment by mdsupport** [comment]
Used to maintain customized version but in the process of moving to [database-centric approach](https://community.open-emr.org/t/new-features-improvements/12089/15).

**Comment by stephenwaite** [comment]
What's the name of your company? It'd be great to have more assistance from them.

**Comment by sjpadgett** [comment]
Simply moving the portal somewhere else in the source tree doesn’t necessarily solve anything.
What is important is decoupling the portal components from core components. Will do this by Converting each portal component into an app. Each app will have its own security and front and backend logic.
They have in each app a module then a controller for the front end can be written to call each app via API and so forth
I hope this makes sense

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
If testing well, then looks good to me. Unclear how this works (looks like there is a cli script that is used, but also a custom menu), so very brief documentation would be helpful.

**Comment by stephenwaite** [comment]
it's kind of clunky in that you run the cli script and then edit the blacklist.php so will focus on documenting the module and then add a codicil regarding the chart review in the wiki

**Comment by stephenwaite** [comment]
https://www.open-emr.org/wiki/index.php/OpenEMR_Modules#Patient_Filter_Module

**Comment by bradymiller** [comment]
documentation looks good!

**Pull request merged**
