### PR TITLE
Optimized docker for development

### PR DESCRIPTION
**Pull request by Jeffrey-P-McAteer**
Docker now lets you mount outside files inside /var/ww/html, which means changes made in your favorite editor are now live in the container and changes the container makes go into existing files. I botched moving things around in git when I noticed running the docker container changed some files (e.g. sites/default/sqlconf.php) which hold information specific to one person's machine/setup, I was going to use .gitignore to keep them out of future commits. If anyone has a better idea I'd love to hear it. (like selectively picking files for commits - I have a script which just pushes everything in the working directory (shame on me)).

### CODE REVIEW

**Comment by Jeffrey-P-McAteer** [comment]
Interesting idea at http://stackoverflow.com/questions/6964297/untrack-files-from-git:
`git update-index --assume-unchanged sites/default/sqlconf.php`
ought to make git ignore changes to that file. I'm going to give it a whirl.

**Comment by Jeffrey-P-McAteer** [comment]
^^ Works fine, I love how much I'm learning about git. Really beats the textbook stuff.

**Comment by Jeffrey-P-McAteer** [comment]
! Don't merge this yet, I just noticed a bug in the mysql setup in the docker container.

**Comment by Jeffrey-P-McAteer** [comment]
Ok it looks like the setup script properly configures openemr on first run (changing sites/default/sqlconf.php), but mysql database gets blown away across container builds (making those changes incorrect). I'm going to look for whatever convinces openemr that it has already been 'setup' and force it to re-run the initial setup every time the docker container is brought up (bad for deployment, good for development).

**Comment by Jeffrey-P-McAteer** [comment]
Setting `$config = 0;` in sites/default/sqlconf.php on every startup & running the autoconfig script works fine. I'd also suggest keeping that file untracked with `git update-index --assume-unchanged sites/default/sqlconf.php`, as individual setups (I assume) should not clutter the repo.
Bug squashed, merge away.

**Comment by robertdown** [comment]
We suggest keeping a developmental copy and running basically an 'rsync' to your web server so your compiled templates, caches and sql files don't get intermingled with various got stuff. Somewhere @bradymiller has a script that does this (I use a modified version of it).

This could still be accomplished using docker, but trying to develop on the same files that's powering your local server is rough (it gets me tangled up whenever I try it)

**Comment by bradymiller** [comment]
It's also easier for me to develop outside the testing directory. Here's a link to the script @robertdown referred to, which I use in ubuntu to copy current git working branch over to the testing directory (and remove the database):
https://gist.github.com/bradymiller/478814

**Comment by bradymiller** [comment]
btw, agree that git rocks :)

**Comment by bradymiller** [comment]
Just brought in this code. thanks! -brady

**Pull request merged**
