### PR TITLE
commits for Rel 700 p2

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #5695 and #5701 for rel-700

#### Short description of what this resolves:
will add other ones here when the time is right

### CODE REVIEW

**Comment by sjpadgett** [comment]
The files I currently have in my patch PR are complete and encompass all the file coming back if you're worried about conflicts

**Comment by stephenwaite** [comment]
ok thanks @sjpadgett , thinking I might for once try bringing in the icd10 stuff into a patcj which can do after your stuff is in

**Review by bradymiller — APPROVED** [review]

**Comment by stephenwaite** [comment]
going to bring in this monstrosity :japanese_ogre: and test out on the demos to make sure didn't mess up these merges :grimacing:

**Comment by bradymiller** [comment]
2DV-2

**Pull request merged**
