### PR TITLE
add php tag to cqm reports

### PR DESCRIPTION
**Pull request by stephenwaite**
found this after running Reports->Clinic->Quality Measures(CQM)

### CODE REVIEW

**Comment by stephenwaite** [comment]
didn't use phpstorm and it shows :( , i'll repair and replace

**Comment by stephenwaite** [comment]
also noticed some php errors related to the cqm reports, https://two.openemr.io/log/logPhp.txt, but fixing these looks like a slippery slope

guess some of the code sniffing hasn't been applied to this part of the codebase

**Comment by bradymiller** [comment]
Looks good and will bring into codebase. thanks! -brady

The sniffer shouldn't of skipped this, but note we have phpstorm set to show us all psr2 issues:
https://github.com/openemr/openemr/blob/master/ci/phpcs_strict.xml#L6

While the sniffer skips some psr2 rules (since these will require manual fixing over time):
https://github.com/openemr/openemr/blob/master/ci/phpcs.xml#L6-L13

**Comment by stephenwaite** [comment]
ok, yeah, had it set to /openemr/ci/phpcs_strict.xml instead of /openemr/ci/phpcs.xml

**Pull request merged**
