### PR TITLE
New ACO for manage modules

### PR DESCRIPTION
**Pull request by matrix-amiel**
Hi.

This PR contains creation of new ACO for manage modules.
Without the new ACO every user with one of ACO of admin section (Calendar Settings, Pharmacy Dispensary etc.) in the old menu or every user with ACO Modules->menus in the new tabs menu can edit/remove all the modules of the clinic.

Thanks.
Amiel

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @matrix-amiel ,
Nice job on this. Just let me know that it is testing well for you (also please test the upgrade; if you can't, let me know and I'll do it) and then I'll bring it into the codebase.
-brady

**Comment by matrix-amiel** [comment]
I tested the upgrade also and it's working well.

**Comment by bradymiller** [comment]
Looks good and will bring this into the codebase. Thanks for the improvement! -brady

**Comment by bradymiller** [comment]
Regarding this, also added a quick fix:
https://github.com/openemr/openemr/commit/5ad0791c976240d89764da461ade3a7cb315968c

**Pull request merged**
