### PR TITLE
New requirements for NewCrop

### PR DESCRIPTION
**Pull request by kchapple**
Added vitals to NewCrop erx message, and a warning if patient is under age 19 years old and vitals are not present. I will also need to backport this to 502 and 501 if possible.

### CODE REVIEW

**Comment by sjpadgett** [comment]
Looks good to me Ken. Make travis happy and we're golden.

**Comment by sjpadgett** [comment]
> I will also need to backport this to 502 and 501 if possible.

v5.0.2 would still get in a patch but v5.0.1 we don't patch any longer(at least, I don't)

**Comment by sjpadgett** [comment]
I'll cherry pick this to v502.

**Comment by kchapple** [comment]
Thank you!!! What is the next date for getting this into a “patch” for those providers out there that use newcrop but we don’t have access to their server?

Ken

**Comment by sjpadgett** [comment]
Very soon. I think Brady has just been waiting for Stephen and me to give a go. lol, Poor Brady, everytime he gets ready to release, he gets a wait, just one more:)

I will ask Brady though so I bet with in a week we'll see a patch.

**Comment by stephenwaite** [comment]
hey @kchapple, @sjpadgett shared this git tip with me and might enable you to roll your own rel-502 zip a little easier

> Here is a neat git command I use often for quickly creating a patch zip for testing. Make your local repository up to date then, if you just want last commit use:

`git archive -o /path/patch.zip HEAD $(git diff --name-only HEAD^)`

> or for a range of commits starting at head:

`git archive -o /path/patch.zip HEAD $(git diff --name-only f65613a --diff-filter=ACMRTUXB)`


> Where f65613a represents the commit id plus one commit ie commit id not included. Very handy.
```

**Pull request merged**
