### PR TITLE
back to main screen after delete action

### PR DESCRIPTION
**Pull request by visolve-openemr**
Hello Brady
"Redirection issue once transaction is deleted "- has been  fixed .
Solution - We have provided Back button after delete, to getback to the main screen.
The following is the Commit link -  https://github.com/visolve-openemr/Openemr_features_enhancements/commit/d7b770cde0d9e12831e572ddd8a27a86821a3906

Thanks,
[ViSolve](http://www.visolve.com/hc)

### CODE REVIEW

**Comment by bradymiller** [comment]
@visolve-openemr ,
There are some strange things taking place when delete other things (like patient, encounter, issues). Rec checking those out and coming up with a solution that works for all the possibilities. Also, rec working on making code PSR2 compliant: https://travis-ci.org/openemr/openemr/jobs/286892789

**Comment by bradymiller** [comment]
Also, I tested this feature in the main codebase. When delete a transaction and ok the deletion it appears to do just fine. Are you sure you tested most recent codebase. That being saide, Close button/link does not work and there are still weird things (ie. not consistent) happening when delete other thing.

**Comment by bradymiller** [comment]
Restested this in tabs, and when delete a transaction, then get the following error in the landing screen:
```The requested URL /openemr/interface/main/tabs/transaction/transactions.php was not found on this server.```
(I am guessing this is an easy fix and I will look into it)

**Comment by sjpadgett** [comment]
@bradymiller Where is this occurring, batch payments, posting?

**Comment by bradymiller** [comment]
@sjpadgett , happening when:
Patient Summary screen -> Transaction:
1. Make a transaction via Add
2. Then Delete transaction
3. After click 'Yes, delete and log' on the modal, it then shows the following:
``````
Not Found

The requested URL /openemr/interface/main/tabs/transaction/transactions.php was not found on this server.
`````

**Comment by bradymiller** [comment]
Also, to clarify, this is not a financial transaction, but actually a referral.

**Comment by sjpadgett** [comment]
lol, Oh! :) jeez, i've been all over this code and am still learning....I've got this.

**Comment by sjpadgett** [comment]
Suppose this does it. Tested in frames and tabs. The deleter issues resolved themselves with recent dialog upgrade and deleter rework.
https://github.com/openemr/openemr/pull/1380

**Comment by bradymiller** [comment]
thanks @sjpadgett !

**Pull request closed without merging**
