### PR TITLE
Return to confirm screen in batch payments

### LINKED ISSUE #4260: batch new payments return to confirm payments on submit
### Describe the bug
Not a bug as I intended to patch that workflow out simply because the confirm screen is ambiguous.
Dropping through from the new payment submit provides the same info but still allows editing.
But, I don't care as in the end one user will like and another will not. 
As it's legacy, i'll return.

Also will add some niceties like fix table styles to fit screen and auto select payment amount so user doesn't have to delete content before entering payment amount... annoying for sure and whatever else...

### PR DESCRIPTION
**Pull request by sjpadgett**
- restyle insurance and patient select popups
- fix new payment table to fit screens better

Fixes #4260 #4265

### CODE REVIEW

**Comment by sjpadgett** [comment]
image
image

Also added auto select for Payment Amount so user doesn't have to delete 0.00 to enter payment. how annoying that must be.
image

Would have gotten rid of the "Do you want to Allocate" confirm dialog after clicking the Allocate button(why yes I do. I did click the allocate button after all!:)) but i'll be darn if I could find the darn thing....

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
tenor99

**Comment by sjpadgett** [comment]
@stephenwaite Do you think we should remove that annoying "Do you want to Allocate" confirm after Allocate button click?
I keep going back and forth on it!

**Comment by stephenwaite** [comment]
don't know @sjpadgett , never use it and the community doesn't seem to complain too much about it, thanks for fixing this up

**Pull request merged**
