### PR TITLE
added standard header template with examples

### PR DESCRIPTION
**Pull request by bradymiller**
Added standard header template with 2 bootstrap conversion examples
Changed custom label class to label_custom class to prevent clash with bootstrap label class

This is for an ongoing discussion here:
https://community.open-emr.org/t/bootstrap-standard/8263

### CODE REVIEW

**Comment by robertdown** [comment]
Seems like a decent stop-gap as we improve the UI

**Comment by bradymiller** [comment]
Just added a commit to bring in changes in interface/main/onotes/office_comments_full.php to update it to the new UI(it's not beautiful, but it definitely an improvement and matches with the new ui; at least I hope it does :) ).

**Comment by bradymiller** [comment]
This is ready for prime time. Awaiting any review or input.

**Comment by robertdown** [comment]
What is the rationale for adding `label-custom` instead of just `label`?

Also, highly discourage manually editing the style_light.css file.... instead suggest updating the SCSS file and regenerating the CSS file. In fact, I suggest minifying the CSS output as to discourage the manual editing

**Comment by bradymiller** [comment]
Hi @robertdown ,

label is clashing with bootstrap and looks awful because of it. And label in terms of bootstrap is not what we want in those place (they look like buttons/tags). So it seemed the simplest thing to do was to move this class out of the way of bootstrap (and would allow using bootstrap label class in other places).

there has already been a number of manual edits to style_light.css (https://github.com/openemr/openemr/commits/master/interface/themes/style_light.css). Since openemr development has been going at a lightning speed, we should avoid doing something that may cause folks to avoid not updating styling (for example, the radiant style is tougher to do manual edits and is buggy and seems to keep getting buggier as time goes on). If we need to go the scss route, then would need an scss file along with instructions for developers on how to use it (like we do for bower and composer stuff) to build the light and radiant styles(would also require somebody going back in to update the prior manual changes and perhaps doing a occasional cleanup for manual things that get into it). Definitely open to this, but don't think we should lock it out by minimizing it (or the code may just simply go the path of least resistance and not update that style).

-brady

**Comment by robertdown** [comment]
Will figure out a way to get the SCSS into the main codebase, but once it's there the CSS becomes generated and can no longer be manually edited or will get out of sync with the SCSS file.

I'll work on an elegant solution to this

**Comment by bradymiller** [comment]
@robertdown ,
Just let me know if you want me to hold this commit or if ok to bring this in and begin to proceed with the bootstrap ui code walk through.
-brady

**Comment by robertdown** [comment]
Ok by me, this will likely only be a short-term solution until I work out templating/asset management

**Pull request merged**
