### PR TITLE
Style Updates

### PR DESCRIPTION
**Pull request by robertdown**
Updates to the main menu and top bar for tabs_style_full and some changes to the gulpfile to allow tabs_*_*.scss to be monitored. Very minor changes. Just not sure if the final `.css` needs to be built and sent to `public/`?

Also a _little_ bit of infrastructure to help improve file structure

# Before
before

# After
after

# Before w/ Hover
before_menu

# After w/ Hover
after_menu

### CODE REVIEW

**Comment by bradymiller** [comment]
@d3sandoval , can you take a look at this?

**Comment by sjpadgett** [comment]
Also you may want to test where there is a Message pending and at least one Portal Alert(an audit or secure message from a portal patient) so both alerts are turned on in header. Doubt it will harm your changes but you never know.
image

**Comment by d3sandoval** [comment]
You might want to remove some of the Lorem Ipsum copyrite text. Otherwise looks good to me! Much cleaner than the previous light theme. You may want to check the bootstrap themes, just in case. Your changes shouldn't affect them at all, though.

IIRC correctly, we haven't committed the output CSS since we moved over from Babel. But @bradymiller has been keeping a closer eye on the build steps than I have.

**Comment by robertdown** [comment]
Doh, PHPStorm auto added the dumb Lorem Ipsum stuff, will remove

**Comment by tywrenn** [comment]
Bumped so I can review for future use

**Comment by tywrenn** [comment]
Closed. The changes that were proposed here were cool at the time, yet I believe we have moved on from them.

**Pull request closed without merging**
