### PR TITLE
Rules UI Restyle

### LINKED ISSUE #4890: Fix CDR Rules UI and restyle
### Describe the problem
Numerous styling issues with the Rules UI and some possible bugs.
I'm not going to completely restyle however try to at least give a better UX than is currently.
Eventually would like to remove the jquery-ui dependency and replace with new sortable drag and drop library. Also rid us of interact.

Updated final restyles:

image

image

image

image

you get the idea....

### PR DESCRIPTION
**Pull request by sjpadgett**
Fixes #4890

#### Short description of what this resolves:
Clean up rules engine UI

### CODE REVIEW

**Comment by sjpadgett** [comment]
@juggernautsei 
I strongly advise, since you're having issues with rules, ya go check all your rules tables for corruptions.
Some item and category labels where returning un-wanted html from the options.inc datatypes where an empty result would return the now annoying fa fa-explanation icon wrapped in a span. The way the rules views render these returned html would populate inputs and thus get saved to tables!

**Comment by sjpadgett** [comment]
Geesh! More involved than I wanted to do but it looks much better and fixed a few bugs too boot..
@juggernautsei will bring in before dev demo reset if you'll jump up on demo farm and test to see if some of your issues are resolved...

**Comment by juggernautsei** [comment]
Sure, I will. LEt me know when

**Comment by bradymiller** [comment]
2DV-2

**Comment by juggernautsei** [comment]
@sjpadgett the changes work well.

**Pull request merged**
