### PR TITLE
weno pharm list fix

### PR DESCRIPTION
**Pull request by bradymiller**
weno pharm list fix

see: https://github.com/openemr/openemr/commit/d56a08640c6fef1b71cfccb9f97277e7eb03795d#r46609148

### CODE REVIEW

**Comment by stephenwaite** [comment]
thanks for the quick fix @bradymiller

@juggernautsei, do Weno patients not use out of town pharmacies or am i missing something here?

**Comment by juggernautsei** [comment]
@stephenwaite I can vaguely remember what I was trying to accomplish with this mod.  The idea is that the program does not handle the list of pharmacies very well in the dashboard. When there are a lot of pharmacies on the table and you click on pharmacies in the patient chart. There is this humongous list that makes it harder to find and assign a pharmacy. In my attempt to make the list more manageable, I added the limiter of displaying only pharmacies that are in the same area code as the patient. This was ok but not ideal because as you have asked the question outside the patient's living area. I am doing this work for George Mason University. They are migrating away from Practice Fusion and in that program, the pharmacy selection is handled this way.
image

So, I am mimicking what they did in our program.

image

I left the dropdown to operate the same as it does now. But added the Alt Pharmacy button so that the user can search anywhere for a pharmacy.  I hope this explains what I was trying to accomplish. It is not a weno thing but an OpenEMR thing.

**Comment by juggernautsei** [comment]
If this is an undesired behavior, remove it altogether. I just put it out there as a possible way to handle the pharmacy list issue.

**Comment by stephenwaite** [comment]
ok, nice, thank you @juggernautsei

**Comment by juggernautsei** [comment]
@stephenwaite while I got your ear. dealing with this vaccination stuff at GMU. We have come across that the inventory management is lacking. Do you know where to input the QOH?

**Comment by stephenwaite** [comment]
hi @juggernautsei, no, what's the `QOH`?

**Comment by juggernautsei** [comment]
Quantity on Hand 
https://community.open-emr.org/t/drug-inventory-qoh/15955/2

**Comment by bradymiller** [comment]
so sounds like removing this line is best. will do that and get it into rel-600 also.

**Pull request merged**
