### PR TITLE
Expandable forms

### PR DESCRIPTION
**Pull request by zbig01**
A mechanism by which certain enabled forms, called expandable
forms can toggle between expanded (full screen) vs contracted
(centered) mode.

As a trial applied to Fees > Feesheet, Billing, Batch Payments
and Posting

An Expand/Contract icon  lets the user toggle between the two states

Furthermore it will remember the state this form was in and replicate the state if
the form is posted to itself or directed to another linked form

There is a built in ability to set the default state as expanded/contracted
to let all expandable forms open in their chosen default state and let user toggle
to a different state if needed

It is in Contracted mode by default but can be set to open in Expanded
mode by checking the check box under Administration > Globals > Features > Expand Form

Some screenshots

Fee sheet centered mode

expandable-01

Fee sheet expanded mode

expandable-02

Billing Manager centered mode

expandable-03

Billing Manager expanded mode

expandable-04

Payments centered mode

expandable-06

Payments expanded mode

expandable-07

EOB Posting centered mode

expandable-12

EOB Posting expanded mode

expandable-13

below added by bradymiller
Up for grabs demo for this PR is here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Mu_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @zbig01 ,
Would it make more sense to use a session variable for this instead of GET/REQUEST variables in combination with a automatic user setting (see the demographics screen how it records a expand/collapse per user so that it expands/collapses same things when reopen the screen)? Then, the logic would be if a user expands something, it will then expand all forms, and if they compact it, it will then compact all forms (this should then not even require a new global setting, although having a default setting before a user does anything would be fine).
-brady

**Comment by bradymiller** [comment]
Up for grabs demo for this PR is here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Mu_-_Up_For_Grabs_Demo

**Comment by zbig01** [comment]
@bradymiller 
I have been looking at the mechanism use to set the state of the expand and collapse links in `demographics.php `using the `getUserSetting` and `setUserSetting` functions. It provides an elegant way to store the state value by writing it to table `user_settings`. It works well in `demographics.php`. One issue that crops up is that as the value is written to the DB it persists thereafter and becomes the de facto default setting for that particular link for the user and the user has to toggle to hide the widget data at a subsequent encounter to get it back to the collapsed mode.

It works well for a single form. I suppose I can best explain the issue with this method by pointing to the `Documents tree view`. If you expand the tree to include a particular branch then all subsequent patient records will have their document tree opened in the exact fashion and you have to adjust it subsequently to get to the default collapsed view. This can sometimes be annoying when you are accessing documents in different patient records.

The way I envisaged the use of this feature is for the expandable form to stay in the default centered state, the data will still be displayed adequately in the centered mode, but to give the opportunity for the user to expand the form to full screen mode on a temporary basis. This will hopefully keep the UI consistent i.e. majority of the pages open in the centered mode.  In case the user decides to always have the forms in the expanded mode I have added the ability to do so per user by including a `Features` tab in `Edit User Settings` page and letting the user set it. The ability of the administrator to set it globally also exists under `Administration > Globals > Features`.

By not writing the POST/GET data to the DB the toggled state of the the form only persists for the session. My method is a one trick pony but designed to be easily applied to multiple pages. I realize there are pros and cons to both these approaches and I welcome your further input :)

**Comment by bradymiller** [comment]
hi @zbig01 ,
I've been thinking about this a bit lately. Lets remove the session idea from the mix. Would it be helpful to use the expand/collapse (via getUserSetting/setUserSetting) for each page that you incorporate this into? So, then the token in user_settings table for the search_payments.php would be something like search-payments-page-full and 1 means full and 0 means not (and could then even set a default for it). This then allows the user to set it to their preference and openemr will automatically then keep it there (that's why the expand/collapse works so nicely in the demographics since it is basically trained by the user's preference automatically). Then each page gets it's setting by each user that sticks. Would this mechanism make sense for what you are doing?
(the nice thing about this mechanism is don't need to pass a bunch of GET/POST variables and assume that just because a user likes one screen in expand mode, we don't assume they want the next screen in expand mode)
-brady

**Comment by bradymiller** [comment]
Just as a quick example, the user may really like the patient summary screen in full mode, but like the other screens in centered mode. With the above mechanism, this will automatically be done by the user just clicking the expand/collapse icon once in patient summary screen, and then the setting will stick. Otherwise, the user would have to click it every single time they went to the patient summary screen.

**Comment by bradymiller** [comment]
(btw, in the end, this is your call; when you figure out the way you want to go, then I will proceed with another code review :) )

**Comment by zbig01** [comment]
@bradymiller 
I too thought about the user defined page-specific state. One of the issues I had to deal with is for pages like `Fees > Batch Payments` .  As you are aware it consists of thee separate pages - `new_payment.php, search_payments.php, era_payments.php` they are consistently styled to look like tabbed pages having a common nav bar. If we implement the stored state solution then you could get into a situation when the three pages can get out of sync and if after setting the default state you select the opposite state then the user will need to manually reset all the pages to match. I suppose one could argue that once set the user might never change it anyway. 
The one thing that I  am afraid  will happen is that a lot of pages that were carefully designed for the centered mode will end up being in the expanded mode permanently and not look as nice :(

**Comment by bradymiller** [comment]
closing this PR since the new revision for this PR is here:
https://github.com/openemr/openemr/pull/1888

**Pull request closed without merging**
