### PR TITLE
Now the system can save some clicks by populating …

### PR DESCRIPTION
**Pull request by juggernautsei**
…the default x12 partner that is set in the insurance company profile

### CODE REVIEW

**Comment by sjpadgett** [comment]
Thought maybe something like that. Let me look at the class a bit.

**Comment by juggernautsei** [comment]
> Hi Sherwin Would it not be better to use the existing Insurance classes for this? If you really need a new function for the lookup then best to add to an existing class. insurance company class already has a default x12 lookup it appears get_x12_default_partner_id() etc. Also hopefully there exists an onchange event to update the partner if insurance is changed in UI.

See, I looked at the class and looked at the include file. The reason I went for the include instead of the class is that I did not want to mess up anything in the class. I am sure I could have added the same function to the class and called it. I was uncertain so I chose the safe route of the include file even though I know we are moving to more class work. 

It can easily be moved to the class if that would be where you want it.

@stephenwaite  what looks weirdness you see?

When I followed the logic of the class, I did not see a clear call to the default x12 partner set to the insurance company in the class. The words default x12 in the class refers only to the partner that is set after the billing has been saved/claim downloaded. Not before. So, it is ambiguous at best. And I reloaded the page for hours troubleshooting the logic to see what was loading and what was not. That is why I built the function to get the data that was missing. The select was only built to show/match the x12 to claims that had been batched only. (That is another way to say the same thing)

**Comment by juggernautsei** [comment]
@sjpadgett I am looking now at the x12Partner.class.php file and I could not find a function that cross-referenced the patient primary insurance with the assigned x12 partner. 

Question: Is it safe to add the get_Default_X12($pid) function to the class?

**Comment by juggernautsei** [comment]
I moved the function to the x12Parner.class.php file and called it. 
$pri_patient_insur_x12 = $x->get_Default_X12($iter['enc_pid']);

Works the same. I will upload the new version and you all can decide which one you like better?

**Comment by sjpadgett** [comment]
First in my testing it works as designed. Not sure I like the recursive call but okay. Give me a minute as I finish looking at the classes.

**Comment by juggernautsei** [comment]
@sjpadgett can verbalize "work as designed".

**Comment by sjpadgett** [comment]
Yep, if insurance has a default partner set and partner exists (it should unless deleted) and patient has primary insurance then the correct partner is selected. Now this is testing in almost current master.
If you are experiencing problems then something funny is going on that may be environment or something. I'm on windows but testing on demo couldn't hurt.

**Comment by juggernautsei** [comment]
@sjpadgett Please refer to the bottom image. 
What you are saying is correct and does work as designed. What I am getting at is in the bottom image with the orange arrow. 

https://community.open-emr.org/t/connecting-the-default-x12-partner-to-the-billing-manager/11357

**Comment by sjpadgett** [comment]
hmm, why did ya close. Something I said:)

**Comment by stephenwaite** [comment]
def seen the behaviour before as well in the image you attached

**Comment by sjpadgett** [comment]
Okay, lets catch up. The select in UI should be rewritten in such a way that unassigned is at top of option list instead of a blank fall through. Also, would really be helpful to add an onchange event to insurance selection pull down to update default partner. Doubtful user can remember what partners go with what insurance company.

**Comment by stephenwaite** [comment]
def no user memory on a monday :)

**Comment by sjpadgett** [comment]
lol, now that i've seen this deficiency, I can't let go so think i'll add the onchange event unless someone else wants to take a wack at it....

**Comment by juggernautsei** [comment]
@sjpadgett  what happened is that I went over to the OEMR demo site and tried to recreate the issue and could not on the first try.

image

**Comment by juggernautsei** [comment]
@stephenwaite  @sjpadgett  apologies

**Comment by stephenwaite** [comment]
no worries @juggernautsei , it may pop up only when there are multiple charges

please do @sjpadgett , will learn something new :)

**Pull request closed without merging**
