### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by stephenwaite**

### CODE REVIEW

**Comment by sjpadgett** [comment]
This was me, sheepishly stated! This most likely will fix issue on demo, true?

**Comment by stephenwaite** [comment]
guessing so, trying to test but looks like docker openemr/openemr:flex will need to be updated since class reorg @bradymiller ?

**Comment by sjpadgett** [comment]
I'm fairly certain it will so going to bring in so available for demo resets tonight. Meantime will test local.

**Comment by sjpadgett** [comment]
@stephenwaite I can't win and I must be dyslexic because the biggest issue is the table and column are backwards in statements:
`#IfMissingColumn eligibility_id insurance_companies
ALTER TABLE `insurance_companies` ADD `eligibility_id` VARCHAR(32) DEFAULT NULL;
#EndIf
#IfMissingColumn x12_default_eligibility_id insurance_companies
ALTER TABLE `insurance_companies` ADD `x12_default_eligibility_id` INT(11)  DEFAULT NULL;
#EndIf` 

No worries i'll fix when I do your batch fix PR

**Comment by bradymiller** [comment]
oh goodness, I am guilty of the last bad EndIf :)

**Comment by bradymiller** [comment]
hi @stephenwaite , The flex dockers are basically empty containers that grab the codebase and build them when run the docker for the first time. So, no need to rebuild the main flex dockers for any codebase/class/library changes. -brady

**Comment by stephenwaite** [comment]
thank you @bradymiller , the vendor directory had to be removed :blush:

**Pull request merged**
