### PR TITLE
add mod to past encounter billing view

### PR DESCRIPTION
**Pull request by stephenwaite**

### CODE REVIEW

**Comment by bradymiller** [comment]
This is very straightforward and will bring this into the codebase. thanks for the contribution! -brady

**Comment by robertdown** [comment]
Would prefer to follow coding standards on new PRs. Gladly would have done this but it was merged so quickly I didn't even get a chance to see it.

Perhaps we can add a tag "Code Standards Approved" (Along with "Code Standards Exception Approved" for times when we are willing to bring in code w/o it complying with standards)? I'll also look to see if Travis could do this check automatically

**Comment by bradymiller** [comment]
@robertdown Didn't note that when i brought it in. What code standard did this break?

**Comment by robertdown** [comment]
http://www.php-fig.org/psr/psr-2/#if-elseif-else

**Comment by bradymiller** [comment]
Isn't a unnested 1 line ternary ok?

**Comment by bradymiller** [comment]
oh wait, its not a ternary. just a simple if :)
this would be tough to filter via travis since there are many instances of this structure in the codebase

**Comment by bradymiller** [comment]
@robertdown , just committed a fix for this:
https://github.com/openemr/openemr/commit/fa387da4ac19ec2f0e1e5051daa7407a77b724e2

And will start to incorporate code standards into reviews.

thanks, -brady

**Comment by MatthewVita** [comment]
@robertdown, @bradymiller 

> I'll also look to see if Travis could do this check automatically

See this conversation I'm having with bobison:

https://github.com/openemr/openemr/pull/492#issuecomment-294306859

**Pull request merged**
