### PR TITLE
Finish front payment exit strategies.

### PR DESCRIPTION
**Pull request by sjpadgett**
Shouldn't be anymore abandoned screens requiring user to close via back or x outs. Also added an exit button for generated receipt screen to allow saving without having to print or clean exit for after print.

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller I think front payments is working very well now and the screens are all consistent and clean but, I suppose the user will be the judge of that.

**Comment by bradymiller** [comment]
Looks good to me :)

**Comment by bradymiller** [comment]
travis was acting up, it appears. did a travis rebuild and it finally passed.

**Comment by sjpadgett** [comment]
Okay thanks. I'm going to go a head and remove the old dialog stylings from the tab style sheets and the X style is already in the core.css so dialog is consistent throughout. Make this PR a little more useful:)

**Pull request merged**
