### PR TITLE
Remove broken endif for twig for erx newcrop

### LINKED ISSUE #4921: Fatal when NewCrop enabled. Twig
### Describe the bug
Enable NewCrop erx in globals connectors. 
Bring up a patient dashboard.

```
[18-Feb-2022 12:52:30 America/New_York] PHP Fatal error:  Uncaught Twig\Error\SyntaxError: Unexpected "endif" tag (expecting closing tag for the "block" tag defined near line 10). in C:\xampp\htdocs\openemr\templates\patient\partials\erx.html.twig:12
```

image

### PR DESCRIPTION
**Pull request by adunsulag**
Fixes #4921 

Fix the broken endif statement in twig that was throwing a fatal error on the patient demographics screen.

When the dashboard pieces were refactored into twig files one of the
global options was not tested.

### CODE REVIEW

**Comment by adunsulag** [comment]
@robertdown I think this came about from your refactor.  From my testing this all looks good but if there was supposed to be an if statement in this file, please let me know. 

If this is urgent @sjpadgett then we can just pull this in if the tests all look good.

**Comment by sjpadgett** [comment]
I'm concerned why the errant endif however, still issues with module i.e.
[18-Feb-2022 13:36:51 America/New_York] PHP Fatal error:  Uncaught Error: eRxGlobals::__construct(): Argument #1 ($configuration) cannot be passed by reference in C:\xampp\htdocs\openemr\interface\eRx.php:38

and

[18-Feb-2022 13:37:25 America/New_York] PHP Fatal error:  Uncaught Error: eRxGlobals::__construct(): Argument #1 ($configuration) cannot be passed by reference in C:\xampp\htdocs\openemr\interface\soap_functions\soap_accountStatusDetails.php:41

Still without good test account set up it's difficult to debug or test for functionality. This is where we need @kchapple and/or Harley to weigh in.

**Comment by sjpadgett** [comment]
aw I see issue. web root is not being passed to build url. i.e href="/interface/soap_functions/soap_accountStatusDetails.php"

**Comment by adunsulag** [comment]
@sjpadgett I'm confused, where are you seeing the fatal error still? I'm wondering if I don't have data setup correctly as I don't see the exception thrown.  I do see warning in stats.php with an undefined variable for $rxArr, but nothing else.

**Comment by sjpadgett** [comment]
umm, found another bug.
PHP 8 put the hammer down on loosely referenced vars passed as a reference. $GLOBALS in this case.
namely calls to the eRxGlobals class constructor.
I'll just open new issue and PR as I don't think MI2 has tested for PHP8+

again note @kchapple

**Review by sjpadgett — APPROVED** [review]

**Comment by bradymiller** [comment]
2DV-2

**Pull request merged**
