### PR TITLE
Replace popup dialog with inline iframes

### PR DESCRIPTION
**Pull request by mdsupport**
Transitional replacement of popup dialogs with inline iframes with minimal code and logic changes.

### CODE REVIEW

**Comment by bradymiller** [comment]
Pointed an Up For Grabs demo to this PR here:
http://www.open-emr.org/wiki/index.php/Development_Demo#Zeta_-_Up_For_Grabs_Demo

**Comment by bradymiller** [comment]
Note I made an error in the link above and edited to fix it (changed Zeta to Eta).

**Comment by bradymiller** [comment]
hi @mdsupport ,

I was going to close this out since @sjpadgett is closing in a solution for a universal modal here:
https://github.com/openemr/openemr/pull/1269

Just wanted to makes sure you were ok with it.
thanks, -brady

**Comment by mdsupport** [comment]
Most of fancy box usage in current code reflects old user interface approach.  In current environment of multiple form factors, these popups are prone to unexpected behavior.    Few links related to this view : 

- [Google / Material Design : Use dialogs sparingly because they are interruptive.](https://material.io/guidelines/components/dialogs.html)
- [Bootstrap Modals : Nested modals aren’t supported as we believe them to be poor user experiences.](https://v4-alpha.getbootstrap.com/components/modal/)

This PR was meant to illustrate ease with which the popups could be brought inline until we improve the underlying process.

**Pull request closed without merging**
