### PR TITLE
Direct message empty content text/plain and text/html rejected

### LINKED ISSUE #4970: Direct Send with empty message body fails with M7 Error
For ONC certification on (b)(1) we need to be able to handle a Direct message that has a subject but an empty body with attachments.  Right now it just returns an M7 error message (which @lcmaas) introduced for better error reporting.

### PR DESCRIPTION
**Pull request by sjpadgett**
See issue.
Basically we would reject Direct mime types text/plain and text/html received message with empty body.

Fixes #4970 #4964

### CODE REVIEW

**Comment by sjpadgett** [comment]
I think we need to address resolving incoming CCDA documents a little better.
Looks like we store empty messages as docs. Need to address.
Need to inform user to go to CCM to import if CCDAs. Maybe a link.
For now making mods to get through § 170.315(b)(1) testing. Going well so far and Direct seems to be working very well once you unscramble setting up!:)

Still trying to understand our Direct directory in sites/documents.

**Comment by bradymiller** [comment]
Hopefully you don't need to understand how stored in sites/default or else there is likely an issue with the standard mechanism to get the document. This is because getting a document should be abstracted out (ie. collecting the document via the standard mechanism to get the document will get you a unencrypted form of the document no matter how it was imported and whether it is stored on couchdb instead).
fyi, if it is stored to drive (and not couchdb), then it will be stored in `sites/*/documents/direct/<random-directory-from-0-10000/<uuid-name-of-document>`

**Comment by sjpadgett** [comment]
> Hopefully you don't need to understand how imported direct documents are stored in sites/*/documents

I'm pretty sure we have an issue here however I didn't look at too closely and maybe not. On one test I wasn't able to open a html document after moving to patient and category.

**Comment by bradymiller** [comment]
Another thing i should of mentioned is that documents never get moved anymore on the drive. So they stay wherever they initially get imported. And changes to document name, patient, or category are just lightweight changes (ie. changes in the sql entry in the documents table).

**Comment by sjpadgett** [comment]
> Still trying to understand our Direct directory in sites/documents.

Retested this a.m and appears documents are being moved to patient and category correctly when done from documents.

**Comment by sjpadgett** [comment]
Testing well. Bringing in when can.

image

**Comment by sjpadgett** [comment]
@adunsulag Any questions before I bring in?

**Comment by adunsulag** [comment]
Thanks @sjpadgett It all looks great!

**Pull request merged**
