### PR TITLE
Start of REST controller

### PR DESCRIPTION
**Pull request by MatthewVi**

### CODE REVIEW

**Comment by bradymiller** [comment]
Very neat stuff. So, what would path look like if requested all patients (the GET /patient thing)?

**Comment by mdsupport** [comment]
Great to see the application getting ready to play with outside world in a structured fashion.  Quick thoughts re. this:
The project has had discussions about "modernizing" for years that always end with minor tweaks due to constraints imposed by current gui supported by existing code.  Any new API offers a clean slate where we should leverage industrial frameworks and use existing logic as a minor part.  With that perspective, if we are going to use zend then is there any reason not to bring in zf3, now 2+ years out?  Or start with apigility or something that newer developers can hit the ground running?

**Comment by sjpadgett** [comment]
While this attempt is very doable, I've always had it in the back of my mind that we would use the Symfony Routing Component for all our REST. It is proven and is the core to many frameworks routing.
Also for services/controllers the class should allow dynamic data sets in calls rather than hard coding what gets returned i.e a select query should return all columns by column names in table or a data set array required (based on columns) pass to method.
The Symphony approach jumps starts this by foregoing reinventing a routing scheme and allows us to get to the meat quicker.

**Comment by sjpadgett** [comment]
@MatthewVi Take a quick look at this: https://code.tutsplus.com/tutorials/set-up-routing-in-php-applications-using-the-symfony-routing-component--cms-31231

**Comment by MatthewVi** [comment]
Hi all,

Just a quick note that I have made more progress on the REST API. It is now living in https://github.com/GoTeamEpsilon/openemr-rest-api. The team thus far is just Sherwin and I. Please let me know if you'd like to join in - we're just committing to master on this fork until it's done.

- The project goal is to "provide an easy-to-use JSON-based REST API for OpenEMR's most common functions. All code will be done in classes and separate from the view to help with codebase modernization efforts."
- I have documented the current endpoints here: https://github.com/GoTeamEpsilon/openemr-rest-api#endpoints (not using Swagger yet)
- Here's the project management TODO list: https://github.com/GoTeamEpsilon/openemr-rest-api#project-management

This is obviously going to be a big effort, but it will be well worth it.

​Thanks,

**Pull request closed without merging**
