### PR TITLE
fix payment method in receipts report - alerted by forum post

### PR DESCRIPTION
**Pull request by stephenwaite**
https://community.open-emr.org/t/payment-method-showing-as-unknown-in-reports-financial-pmt-method/12314?u=stephenwaite

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @stephenwaite , Just let me know if it's testing well, and will then bring it in. -brady

**Comment by stephenwaite** [comment]
thank you Brady, it's working fine

**Comment by stephenwaite** [comment]
whoops, hold on a sec :)

**Comment by stephenwaite** [comment]
here we go :)

**Comment by bradymiller** [comment]
I'm happy to fix travis stuff, if needed (I just run a command on it). Just let me know and then I'll bring this in.

**Comment by stephenwaite** [comment]
thanks Brady, @MedC reported back and might need to keep tweaking for now although mine is testing ok

**Comment by bradymiller** [comment]
No hold up here(even after I branch the repo(plan this weekend), still plan to bring in new commits into the branch for 1-2 more weeks). Just let me know when you think it's ready, and I'll bring in it. thanks! -brady

**Comment by stephenwaite** [comment]
ok nice, this is ready, thank you

**Comment by bradymiller** [comment]
hi @stephenwaite , Code looks good and bringing into codebase. Thanks for the fixes! -brady

**Pull request merged**
