### PR TITLE
Batch Payments and other listed changes

### PR DESCRIPTION
**Pull request by sjpadgett**
- remove unfinished Questionnaire resources
- fix portal button show when 0 notifications
- change remainder table col to Bal duh!
- restyle tables to BS4
- insurance dynamic color change routine fix(int casting conditionals)

Issues:
- insurance only advances. can't reset insurance to say pri from posted to secondary!
- payment amount edit/change unstable
- umm what if we don't want a form-control class from generate_select_list()?
- Search fails Pay Status search. sql error
- insurance auto advances even if still charges not paid for encounter i.e if !allocate all in same ar session, all get advanced.
- encounter last billing statuses not updated! I'm befuddled why this is...or bug

### CODE REVIEW

**Comment by sjpadgett** [comment]
I have half a mind to pull this module! Edit payments just has too many calculation bugs if you don't follow an exacting pattern for edits. How has this feature been carried forward for so long w/o addressing these deficiencies????

**Comment by stephenwaite** [comment]
think because it was a zh contrib, they must have worked all of this out on their fork

**Comment by sjpadgett** [comment]
God forbid if fixes would get donated back! This is one reason we need to clean out recommended vendor list.

**Comment by sjpadgett** [comment]
Another bad for this feature is it can screw up billing. A propagation of unnoticed errors. This is a reason we get weird billing error complaints showing elsewhere and are dumbfounded why. Error may have started 6 months before hand with AR screwed up...... To do this right and beside fixing the many ways AR gets messed up, perhaps we need a verification routine to verify that AR makes sense then star problematic areas in billing. i.e some of billing needs to be rewritten....

**Comment by tywrenn** [comment]
> fix portal button show when 0 notifications
@sjpadgett Hey i was fixing this xD

**Comment by sjpadgett** [comment]
I have some more performance tuning coming that affect this so went ahead and added this.

**Comment by sjpadgett** [comment]
Sometimes these crud tables can be crudding to style:)

image

**Comment by sjpadgett** [comment]
@stephenwaite Can you think of a situation where we would need to allocate to a cpt where there is not an encounter? My goodness, the bugs, the bugs.. Swat one down and another pops up! How in the world am I going to get all this back to v502?
image

**Comment by stephenwaite** [comment]
good luck getting it back to v502 but even if you don't bring it all back it will be encouraging to those folks

i can think of a situation where would need to allocate to a cpt where there's not an encounter, like charging for a records request

**Comment by sjpadgett** [comment]
Aww, right, but; how would that get inputted without a charge in feesheet which needs an encounter?

**Comment by sjpadgett** [comment]
@stephenwaite Check out this major bug in v502 and v503:
```
$Modifier =$RowSearch['modifier'];
    if ($Modifier!='') {
        $ModifierString=", $Modifier";
    } else {
        $ModifierString="";
        $Fee=$RowSearch['fee'];
        $Encounter=$RowSearch['encounter'];
        ....
```
Should be:
```
$Modifier =$RowSearch['modifier'];
    if ($Modifier!='') {
        $ModifierString=", $Modifier";
    } else {
        $ModifierString="";
    }
    $Fee=$RowSearch['fee'];
    $Encounter=$RowSearch['encounter'];
    ....
```
Just imagine the trouble this out of place brace will cause? 

We just have to do a better job testing restyles before release and the rest of us admins need not put this all on Brady during reviews. umm, did I just rebuke myself!!! :)
Man O'Man ....

**Comment by stephenwaite** [comment]
jeez, this must be a major part of the bug report on the form

good point about the charge being inputted btw

**Comment by sjpadgett** [comment]
> jeez, this must be a major part of the bug report on the form

Yeah we prob should put a be on the lookout notice on day to day forum thread. At least to keep folks from digging in deeper before I can get a fix out. I will make a point to have one before weekends out.

It might even be ideal to put up a forum topic of up and coming or coming patch items. Unless we have something like that we use now!

**Comment by stephenwaite** [comment]
don't think we have ever been that forward thinking :) 
be glad to update the post and maybe we could get some help testing with a couple of the users on the thread

**Comment by sjpadgett** [comment]
@stephenwaite The apply balance to Global for allocate/finish payments balance of payment distribution will set payment to fully paid effectively hiding that balance. I can't figure out why or what use Global amount was intended, do you have any idea?

Also looks like payment edits don't touch encounter last levels(is bug y/n?). I'm wondering if we should add a display and reset option in encounters or maybe billing manager or EOB posting for these persisting values?

**Comment by stephenwaite** [comment]
can only think it was meant to hide small differences btw ins payment and bal due on the account, like differing by $.01 or other negligible amount

i thought the `Done with Ins1` on invoice posting handled that so maybe need it here too?

**Comment by sjpadgett** [comment]
> be glad to update the post 

Yep should let the folks know. Admit nothing though! Or we can blame one of my brothers, they're use to it. :)

**Comment by sjpadgett** [comment]
@bradymiller if you want to look over i'm getting close. @stephenwaite You think you could pull my branch and take a look to give me an impression?

**Comment by stephenwaite** [comment]
sure @sjpadgett , will do

**Comment by bradymiller** [comment]
Code looks good to me. The "cat in the bowl" also voices approval :)

tenor (29)

**Comment by sjpadgett** [comment]
thanks Brady and Stephen. 
I think i'll add some new features to this such as ability to get out of trouble with some billing point in time resets. It should be a new feature with its own menu item and include it as part of an overall review of billing states. Not a report but an active UI.
This PR will have any new hooks to support then new PR for feature. Maybe an active pre installed module.

Working to bring important fixes back to v502 in meantime.

**Comment by stephenwaite** [comment]
just tested a little, huge improvement @sjpadgett , great job

**Comment by sjpadgett** [comment]
Brought this in but will still keep on trucking to clean up further. @stephenwaite You can use the sync or async alerts depending on which you like best. There is a dialog.confirm example also.
Hope to have 502 done tomorrow!

**Pull request merged**
