### PR TITLE
Chart tracker service

### PR DESCRIPTION
**Pull request by kofiav**
Created a service to replace SQL queries on the `chart_tracker` table. Still in the process of untangling the queries in `custom/chart_tracker.php` and replacing them with calls to the service object.

### CODE REVIEW

**Comment by MatthewVita** [comment]
Looks good so far!

**Comment by MatthewVita** [comment]
@kofiav, looks like this is coming along.

You can pass in a `\entities\ChartTracker` instead of an array to the `trackPatientLocation`, even if it is only partially hydrated (more DDD style).

**Comment by kofiav** [comment]
@MatthewVita 

Good call!

**Comment by MatthewVita** [comment]
The code is looking good!

Is this ready for my testing then?

BTW, I generally don't mind checking in a commit or two with a branch, but it looks like you have a decent amount of commits, so I would recommend squashing (cuts down on noise). This is my squashing method (it's like rebase, but a little simpler and doesn't rewrite history). Feel free to simply do rebase if this doesn't appeal to you:

```
git checkout master
git fetch
git pull
git checkout your_branch
git merge origin/master # Creates a new commit on your_branch, that contains all changes from master
git reset --soft origin/master # Generates a set of staged changes
git add -A
git commit -m 'Your squashed commit message here'
```

**Comment by kofiav** [comment]
@MatthewVita 

My bad, will that allow me to squash what I've already checked in or will it only work for all subsequent commits? I have some uncommitted changes so `\custom\chart_tracker.php` is not ready for testing yet but it will be in the next pile of stuff I check in.

**Comment by MatthewVita** [comment]
> My bad, will that allow me to squash what I've already checked in

Yup

**Comment by kofiav** [comment]
@MatthewVita Code is ready for review!!

**Comment by MatthewVita** [comment]
Cool! Looking into it now

**Comment by MatthewVita** [comment]
Okay, here's my code review:

### chart_tracker.php

 `foreach($activeUser as $users)` should be ` foreach($users as $activeUser)`. You are certainly a Java programmer :)

### chart_location_activity.php

The query at line 165 should be centralized in a service. For now, you can literally copy/paste it in a `PatientService::getChartTrackerInformationActivity($pid)`. I don't think it should go in the `ChartTrackerService` because it's mainly using the patient data to get relevant information... hmm, what are your thoughts?

### charts_checked_out.php

The query at line 75 should be centralized in a service. For now, you can literally copy/paste it in a `PatientService::getChartTrackerInformation($pid)`. I don't think it should go in the `ChartTrackerService` because it's mainly using the patient data to get relevant information.. hmm, what are your thoughts?

Good work, btw. Almost there! Let me know if you need help testing this feature or need to know how to add more chart tracker storage locations to the OpenEMR list!

**Comment by MatthewVita** [comment]
@kofiav see above :)

**Comment by kofiav** [comment]
>foreach($activeUser as $users) should be foreach($users as $activeUser). You are certainly a Java programmer :)

It's a wonder to me that that even worked in the first place ... good catch. I guess my testing hasn't been as good as I thought it was. My testing has so far consisted of:
1. Maneuvering to `Miscellaneous` -> `Chart Tracker`
2. Searching for a patient using their pid
3. Clicking `Save`
4. Checking to see if the `chart_tracker` table has been updated with a new entry

If this doesn't sound comprehensive enough I'd welcome any further suggestions.

**Comment by kofiav** [comment]
Had another look and I agree that the queries in `chart_location_activity.php` and `charts_checked_out.php` are an appropriate addition to `PatientService`. However, since work on that is still in progress it will require co-ordination between me, you and @robertdown

**Comment by MatthewVita** [comment]
@kofiav I'm writing up a wiki page explaining the Chart Tracker feature (notes about it are currently found in old forum threads... not good).

BTW, just create the PatientService, we can merge with Robert's stuff later.

**Comment by MatthewVita** [comment]
Hot off the press: http://open-emr.org/wiki/index.php/Chart_Tracker

**Comment by kofiav** [comment]
Great! and thanks, the Wiki page will be useful for testing. 

Also I'm putting the SQL queries in the (new) Patient service like you suggested. What did you use to format / indent the SQL queries in the Facilities service? (see below)

        $sql  = " SELECT FAC.id,";
        $sql .= "        FAC.name,";
        ...
        $sql .= " FROM facility FAC";

**Comment by MatthewVita** [comment]
Formatting was done by hand. Low tech solution :)

**Comment by robertdown** [comment]
Question - why are you doing 
```php
$sql = "SQL HERE";
$sql .= "MORE HERE";
$sql .= "AND EVEN MORE HERE";
```

Why not just:
```php
$sql = "SQL HERE
             MORE HERE
             AND EVEN MORE HERE";
```

**Comment by MatthewVita** [comment]
@robertdown good call. The simpler the better!

**Comment by kofiav** [comment]
I will try to get this ready for another review by tonight.

**Comment by kofiav** [comment]
@MatthewVita I looked at this briefly and made the required changes. Please have a look. Also thanks again for the chart tracker tutorial - it was useful for testing.

**Comment by MatthewVita** [comment]
@kofiav awesome! I will do a review and get back to you.

**Comment by MatthewVita** [comment]
@kofiav great work! Tested well and the code is great.

**Comment by bradymiller** [comment]
very nice @kofiav !!

**Pull request merged**
