### PR TITLE
Lots of user interface improvements by zbig01

### PR DESCRIPTION
**Pull request by bradymiller**
Work in progress.

Each commit does something different and there are about 20 or so commits!

### CODE REVIEW

**Comment by MatthewVita** [comment]
New (modern) images look great!

**Comment by arnabnaha** [comment]
Have created a seperate instance of openemr with the above changes. the icons look great..The save button in the add new appointment popup window do not work. Nothing happens on clicking it.

**Comment by bradymiller** [comment]
@robertdown, Regarding font-awesome usage, I think the author is doing this. But basically changing the icon libraries in the calendar library directly which could be considered a nice shortcut to get the nice icons without needed to included font-awesome and change all the calls throughout the related code.(long-term goal will be to of course direct these place to the main font-awesome library as modernize the codebase)

**Comment by bradymiller** [comment]
New revision is in the following PR (so will close this PR):
https://github.com/openemr/openemr/pull/786

**Pull request closed without merging**
