### PR TITLE
QRDA Parsing

### PR DESCRIPTION
**Pull request by sjpadgett**
fix missing low/high dates for substance medication activity
@kchapple If want grab the src/Services/Cda directory from my repo

### CODE REVIEW

**Comment by sjpadgett** [comment]
Display code in care plan

image

**Comment by sjpadgett** [comment]
@kchapple I think I got em all for care plan. I still need to modify the encounter form so user can input this stuff. No idea how I going to do that yet. The way QRDA does negate is just weird and certainly doesn't translate to CCDA! Same with observations.

image

**Comment by kchapple** [comment]
Hi @sjpadgett I wanted to get this code, so just merged this branch into my branch. I'm not sure why, but I got a bunch of files that I don't think are relevant (it just didn't look right). Are you able to bring this into master so I can pull and test?

```
{22-04-06 8:33}iMac:~/Dev/openemr/master@qrda-care-plans % git checkout -b qrda-care-plans-jerry-merge
Switched to a new branch 'qrda-care-plans-jerry-merge'
{22-04-06 8:34}iMac:~/Dev/openemr/master@qrda-care-plans-jerry-merge % git pull jerry more-qrda
From https://github.com/sjpadgett/openemr
 * branch                more-qrda  -> FETCH_HEAD
Merge made by the 'recursive' strategy.
 Documentation/help_files/add_edit_transactions_dashboard_help.php                                                          |  19 ++++-
 Documentation/help_files/cqm_amc_help.php                                                                                  | 112 ++++++++++++++++++++++++++
 interface/forms/care_plan/new.php                                                                                          |   2 +-
 interface/forms/eye_mag/php/eye_mag_functions.php                                                                          |  12 +--
 interface/forms/eye_mag/view.php                                                                                           |   4 -
 interface/modules/zend_modules/module/Application/src/Application/Controller/IndexController.php                           |   3 +
 interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php |   8 +-
 interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php                |  12 ++-
 interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php           |  85 +++++++++++++++++---
 interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncountermanagerTable.php                |  30 ++++---
 interface/patient_file/encounter/find_code_popup.php                                                                       |   2 +-
 interface/patient_file/summary/add_edit_issue.php                                                                          |   2 +-
 interface/patient_file/transaction/add_transaction.php                                                                     |  28 ++++++-
 interface/reports/amc_full_report.php                                                                                      | 225 +++++++++++++++++++++++++++++++++++++++++++++++++++
 interface/reports/cqm.php                                                                                                  | 748 ++++++++++++++++++++++++++++---------------------------------------------------------------------------------------------------------------------------------------------
 library/ajax/execute_cdr_report.php                                                                                        |   2 +-
 library/classes/rulesets/Amc/library/AMC_Unimplemented.php                                                                 |  22 ++++-
 library/classes/rulesets/Amc/library/AbstractAmcReport.php                                                                 | 280 +++++++++++++++++++++++++++++++++++++++++++--------------------
 library/classes/rulesets/Amc/library/AmcItemizedActionData.php                                                             |  83 +++++++++++++++++++
 library/classes/rulesets/Amc/library/IAmcItemizedReport.php                                                                |  16 ++++
 library/classes/rulesets/Amc/reports/AMC_304i_STG2.php                                                                     |  11 +++
 library/classes/rulesets/Amc/reports/AMC_304i_STG2/Denominator.php                                                         |   2 +
 library/classes/rulesets/Amc/reports/AMC_304i_STG2/Numerator.php                                                           |  36 +++++++++
 library/classes/rulesets/Amc/reports/AMC_315g_2c.php                                                                       |   2 +-
 library/classes/rulesets/Amc/reports/AMC_315g_2c/Denominator.php                                                           |  96 ++++++++++++++++++++--
 library/classes/rulesets/Amc/reports/AMC_315g_2c/Numerator.php                                                             |  79 +++++++++++++++++-
 library/classes/rulesets/Amc/reports/AMC_315g_7.php                                                                        |  58 ++++++++++++++
 library/classes/rulesets/Amc/reports/AMC_315g_7/Denominator.php                                                            |  77 ++++++++++++++++++
 library/classes/rulesets/Amc/reports/AMC_315g_7/Numerator.php                                                              | 161 +++++++++++++++++++++++++++++++++++++
 library/classes/rulesets/ReportTypes.php                                                                                   |   1 +
 library/clinical_rules.php                                                                                                 |  68 +++++++++++++---
 library/report_database.inc                                                                                                | 119 +++++++++++++++++++++++++--
 sql/6_1_0-to-7_0_0_upgrade.sql                                                                                             |  52 ++++++++++--
 sql/database.sql                                                                                                           |  22 ++++-
 src/Billing/BillingProcessor/Tasks/AbstractGenerator.php                                                                   |   8 --
 src/Billing/BillingProcessor/Tasks/GeneratorHCFA.php                                                                       |   6 +-
 src/Billing/BillingProcessor/Tasks/GeneratorHCFA_PDF.php                                                                   |  23 ++++--
 src/Billing/BillingProcessor/Tasks/GeneratorX12.php                                                                        |   2 +
 src/Common/Twig/TwigExtension.php                                                                                          |  43 ++++++++++
 src/Reports/AMC/Trackers/AMCItemSkipTracker.php                                                                            |   2 +-
 src/Reports/AMC/Trackers/AMCItemTracker.php                                                                                |  10 ++-
 src/Services/Cda/CdaTemplateImportDispose.php                                                                              |  10 ++-
 src/Services/Cda/CdaTemplateParse.php                                                                                      |  95 +++++++++++++++++++---
 templates/error/404.html.twig                                                                                              |   5 ++
 templates/reports/cqm/_results-table-main-sub.html.twig                                                                    |   5 +-
 templates/reports/cqm/_results-table-patient-details.html.twig                                                             |  67 ++++++++++++++++
 templates/reports/cqm/_results-table-provider-group.html.twig                                                              |  11 +--
 templates/reports/cqm/_row-provider-display-name.html.twig                                                                 |  19 +++++
 templates/reports/cqm/_row-provider-group-display-name.html.twig                                                           |  10 +++
 templates/reports/cqm/amc-full-report.html.twig                                                                            |  46 +++++++++++
 templates/reports/cqm/amc-results-patient-details.html.twig                                                                |  21 +++++
 templates/reports/cqm/cqm-form.html.twig                                                                                   | 153 +++++++++++++++++++++++++++++++++++
 templates/reports/cqm/cqm.html.twig                                                                                        | 195 ++++++++++++++++++++++++++++++++++++++++++++
 version.php                                                                                                                |   2 +-
 54 files changed, 2351 insertions(+), 861 deletions(-)
 create mode 100644 Documentation/help_files/cqm_amc_help.php
 create mode 100644 interface/reports/amc_full_report.php
 create mode 100644 library/classes/rulesets/Amc/library/AmcItemizedActionData.php
 create mode 100644 library/classes/rulesets/Amc/library/IAmcItemizedReport.php
 create mode 100644 library/classes/rulesets/Amc/reports/AMC_315g_7.php
 create mode 100644 library/classes/rulesets/Amc/reports/AMC_315g_7/Denominator.php
 create mode 100644 library/classes/rulesets/Amc/reports/AMC_315g_7/Numerator.php
 create mode 100644 templates/error/404.html.twig
 create mode 100644 templates/reports/cqm/_results-table-patient-details.html.twig
 create mode 100644 templates/reports/cqm/_row-provider-display-name.html.twig
 create mode 100644 templates/reports/cqm/_row-provider-group-display-name.html.twig
 create mode 100644 templates/reports/cqm/amc-full-report.html.twig
 create mode 100644 templates/reports/cqm/amc-results-patient-details.html.twig
 create mode 100644 templates/reports/cqm/cqm-form.html.twig
 create mode 100644 templates/reports/cqm/cqm.html.twig

```

**Comment by kchapple** [comment]
ahh, ok that makes sense. Maybe I can cherry-pick jerry's last 5 commits

**Comment by sjpadgett** [comment]
@kchapple i'll merge this and you can pull in

**Comment by kchapple** [comment]
Thanks @sjpadgett I'll have some code ready soon for the negations, hopefully that will resolve care plans

**Pull request merged**
