### PR TITLE
fix SBR group name, number and fix duplicate onset date

### PR DESCRIPTION
**Pull request by stephenwaite**
debugging thanks to the forum, https://community.open-emr.org/t/1500-form-box-12-box-14-box-24-i-j/10361/15

### CODE REVIEW

**Comment by bradymiller** [comment]
Hi @stephenwaite ,
If this is testing well for you, then I'll bring this in. Just let me know. Also let me know if it needs to go into the next 5.0.1 patch.
thanks! -brady

**Comment by stephenwaite** [comment]
thanks @bradymiller , it's testing well and should go in the next patch.

**Comment by bradymiller** [comment]
thanks for the fix! Bringing in now and will get it in the next patch. -brady

**Comment by stephenwaite** [comment]
cool, thanks Brady

**Pull request merged**
