### PR TITLE
Document drag and drop support (Finally got around to updating this feature).

### PR DESCRIPTION
**Pull request by juggernautsei**
Here is the reintroduction of the drag n drop file uploader.
Added the Global to turn it on if not is stays hidden.

### CODE REVIEW

**Comment by bradymiller** [comment]
I can help out with the assets (ie. using bower), but I don't even see in this code where you are including the drag-n-drop css or js scripts.

**Comment by bradymiller** [comment]
Additionally, aren't these the original files:
https://github.com/enyo/dropzone/tree/master/dist
(if so, why were the filenames changed?)

**Comment by juggernautsei** [comment]
@bradymiller  I changed the names as that they are public files as a slight of hand security measure, in my mind. It's a habit I have because if I have a public facing server, I want to minimize attacks on known public files. So I change their names.

**Comment by juggernautsei** [comment]
@robertdown  I can move the upload.php file anywhere you want. Would it be best to place it in the library folder?

**Comment by bradymiller** [comment]
@juggernautsei ,

I just brought the dropzone asset into the codebase as an official asset:
https://github.com/openemr/openemr/tree/master/public/assets/dropzone-4-3-0

So you should remove the library files you copied/renamed and use the files in above folder (to place it in your repo, if don't want to update to most recent codebase, then simply recommend copying the public/assets/dropzone-4-3-0 folder into your codebase).

Note that public/assets is where we store unmodified client side libraries, so @robertdown is correct that your custom php script needs to find another home (maybe interface/documents/ or something like that).

-brady

**Comment by bradymiller** [comment]
this has been migrated to another PR:
https://github.com/openemr/openemr/pull/628

**Pull request closed without merging**
