### PR TITLE
Implemented #251

### PR DESCRIPTION
**Pull request by rishabhemr**
Implemented #251

### CODE REVIEW

**Comment by bradymiller** [comment]
Hi,
Thanks for taking this fix on. Strange things happen here on testing. For example, if I open 4 tabs, and then move them around a bit, and then open the tab on far right and close it, all the tabs disappear, but the pertinent iframes still seem to exist. Guessing there is a simple issue that needs to be addressed.
-brady

**Comment by bradymiller** [comment]
#260 #290 #251 
Is this PR addressing all 3 above issues?

**Comment by rishabhemr** [comment]
@bradymiller yes the last code committed by us is addressing 3 issues which you have mentioned
#260 #290 #251 .

Rishabh Software

**Comment by bradymiller** [comment]
Hi @rishabhemr 
Is this the same as the new PR here:
https://github.com/openemr/openemr/pull/662

If so, then I'll close this PR. 
thanks, -brady

**Comment by rishabhemr** [comment]
@bradymiller,  Yes its the same PR for the issue number #260 #290 #251

**Comment by bradymiller** [comment]
thanks, I'll close this PR then (and plan to review/test your new PR soon :) ).

**Pull request closed without merging**
