### PR TITLE
Docker setup utilities

### PR DESCRIPTION
**Pull request by Jeffrey-P-McAteer**
For devs who like docker, this dockerfile constructs a fresh install of openemr on a debian-based system. The script does a quick setup of the new system.

(full disclosure this was my way of creating a personal dev environment, I'm not 100% certain it's appropriate for everyone...? Very new here, but eager to help.)

### CODE REVIEW

**Comment by bradymiller** [comment]
Very nice to see this!
Just needs standard headers and then will bring this into the codebase:
http://www.open-emr.org/wiki/index.php/How_to_Document_Your_Code_Properly#Page-Level_DocBlock
(basically just need gpl license, your copyright, and your author)

**Comment by MatthewVita** [comment]
Great!

**Comment by Jeffrey-P-McAteer** [comment]
Duly updated, anything else?

**Comment by bradymiller** [comment]
Very nice! just brought it into the codebase.

**Comment by MatthewVita** [comment]
@Jeffrey-P-McAteer I just tagged you on the ticket for entity generation. Let me know if you don't see it.

**Comment by Jeffrey-P-McAteer** [comment]
I saw it, I'm going to have fun learning Doctrine.

**Pull request merged**
