### PR TITLE
escape column names in sql statements #2141

### PR DESCRIPTION
**Pull request by prondubuisi**
first iteration, others to follow if this looks good

### CODE REVIEW

**Comment by danehrlich1** [comment]
You’re the man!

**Comment by bradymiller** [comment]
hi @prondubuisi ,

Looking through this, it looks like $cols generally is one of the following:
1. *
2. one column name
3, multiple column names separated by commas

Note that escape_sql_column_name() calls will now only currently work with number 2 above. It will breaks if $cols is 1 or 3 above.

Recommend:
1. modify escape_sql_column_name() to accept either a string or array on the first parameter. If string, then just run the function as normal. If array, then will loop through each item with the escape_sql_column_name() function.
2. Make another function called process_cols_escape() in that library that will convert $cols into an array of column names

Then the final product will look something like
escape_sql_column_name(process_cols_escape($cols), array('patient_data'))

And then lets just focus on the the following 2 functions:
getBillingByEncounter() (good example of number 1 and 3 above)
getRegistryEntry() (good example of number 2 above)

btw, if we find functions that are not used in the codebase, then we can remove them :)

**Comment by prondubuisi** [comment]
good catch @bradymiller I Will try to modify the Pr to work for all three us cases

**Comment by bradymiller** [comment]
Related code was brought in via recent PR:
https://github.com/openemr/openemr/pull/2215
hi @prondubuisi , do you want me to leave this PR up (since it identify spots where $cols needs processing) or close it?

**Comment by prondubuisi** [comment]
@bradymiller let's close this, I prefer working with branches now since they make for an easier workflow.

**Pull request closed without merging**
