### PR TITLE
added option to turn on/off database connection pooling

### PR DESCRIPTION
**Pull request by bradymiller**
Related to Issue: https://github.com/openemr/openemr/issues/3904

Still testing and more of a demonstration of what needs to be done to turn this on and off globally.

outcome:
Testing well and have decided to offer the option.

### CODE REVIEW

**Comment by mdsupport** [comment]
1. This PR introduces pConnect as an option which at least in adodb code appears to be default. If intent is to ensure every connection is new, use nConnect.
2. Small memory overhead of persistent connection (some mention of about 500K) is a bargain compared to the hit of establishing new connection which includes user validation. So why promote such setting?

In general mysql settings defaults are tuned for minimal impact on the server resources in idle state. It is good for any application to centralize db operations. Let db admins do their thing at the database configuration/tuning level for large installations.

**Comment by bradymiller** [comment]
hi @mdsupport ,

See the https://github.com/openemr/openemr/issues/3904 issue for details and note this is meant to demonstrate having database connection pooling on and off.

1. The PR did not introduce pConnect. It was already being used by 2 of the 3 adodb connection schemes (core and gacl) and not by 1 of them (calendar), which was using connect. pConnect sets ups a persistent connection (pooled) and connect does not (the connection dies with the script). This achieves objective where sleeper/pooled connections do not remain that may exceed the max_connections limit (ie. no reason to force a new connection since there aren't any pooled connections remaining anyways).

2. The overhead @dummys  is concerned with is the absolute overhead requirement when setting max_connections, which can see impact on in this calculator: https://www.mysqlcalculator.com/

This PR highlights several issues.
1. We have 6 different schemes to connect to the database as pointed out by @zerai , which is a bit much :) Is there a way to reduce this?
2. Of those schemes, only half are even using pooled connections. Should we make them all pooled?
3. Does it make sense to give the instance the option of supporting pooled or not. For example, somebody on a rasberry pi in a low resource area supporting lots of users, they may be ok with having a slower OpenEMR that actually works (ie. do not need to set max_connections high which it could not do and keep the active connections low as to avoid breaking memory limitations).

**Comment by sjpadgett** [comment]
For day to day i'd say use connection pooling if feasible however, there are occasions you don't want connection pooling such as sql upgrade.
e.g. you start a long running query via browser client then exit browser. Come back and restart query.  Now you have an arbitration issue(contention) on server because the previous query is still running! Now for mysql, you can lock up cpu on occasion(I know, has happened twice on me). Don't see issue on maria.
On this type of process, i'd like to set a global to init ado with connect so connection is abandon because user abandoned...

I'm here to say that if I can't get these quirks worked out, we are going to have some pissed off user even before they see the great work that is v6.0...

**Comment by bradymiller** [comment]
hi @sjpadgett ,
Would be easy to support an override globals that killed pooling before calling globlals.php (I'd just include it in the if statements in this PR and voila). Are we confident though that a rogue connect (versus pConnect) call will stop when exit the browser, though?

**Comment by sjpadgett** [comment]
Not certain of anything since starting this @bradymiller . My past impressions were it should but there may be a server config that prevent. Still i'll test on both servers...

**Comment by bradymiller** [comment]
@sjpadgett ,
Just added commit to support per script turning off of database connection pooling with flag added to the sql_upggrade.php script.

**Comment by sjpadgett** [comment]
Cool, i'll test. also i've been able to echo almost real time sql statement and the comments you added to upgrade script so now instead of seeing the result of a query request after it completes, we now see it before being sent to server. It's an old php trick you've prob seen but, now following the upgrade is not as confusing. And tell me again why this matters to me!!!!

**Comment by bradymiller** [comment]
Here's a good read for folks regarding php pooling/persistent connections:
https://www.valinv.com/dev/mysql-mysql-persistent-connections-in-php

**Comment by bradymiller** [comment]
Another link arguing against persistent connections:
https://meta.wikimedia.org/wiki/Why_persistent_connections_are_bad

**Comment by mdsupport** [comment]
No comment on technical merits of changes anyone wishes to make to their databases.
Just could not figure out how setting that affects any type of connect can be stored and accessed from database table?
All the best.

**Comment by sjpadgett** [comment]
Hi @bradymiller Why trying to translate the query comments I get this in the same place during upgrade so I removed the translations for those with success. The error does present due to the sql_upgrade xlt calls but gets reported during poll.
Best way to do these I guess is to set the translated comments to a variable at top of script instead of calling xlt during.
Don't pay attention to not masking status, turned off.
image

Concerning the pooling. Abandoned browser session will not end a process thread which makes sense now i've thought about it. I'm thinking of a server client running in scope. oh well duh. I did learn though that Maria does a great job running at min, two of the same queries started separately. Mysql, the results are still out.

Upgrade just seems to run better(more reliably) using connect. I know it doesn't make sense but, neither does prostate shrinkage!

I agree though that allowing turning off pooling is a good option to have..

**Comment by bradymiller** [comment]
appears that pooling can cause problems with "complicated" sql stuff, which the upgrade is doing, so kind of makes sense it runs better.

Agree that turning off pooling is a nice option, so will bring this PR in (which is testing well).

**Comment by sjpadgett** [comment]
Umm can you pull the sql_upgrade stuff as i'm putting up a new PR?

**Comment by bradymiller** [comment]
Do you need me to revert all the connection_pooling_off stuff (the use and setting of the variable in sql_upgrade and then the use of it in all the conditionals)? If so, I can revert that code from the codebase. Just let me know.

**Comment by sjpadgett** [comment]
just the sql_upgrade flag you added to turn polling off i.e any changes to sql_upgrade.

**Comment by bradymiller** [comment]
will do

**Comment by sjpadgett** [comment]
thanks.

**Comment by bradymiller** [comment]
will be just easier to revert the whole connection_pooling_off mechanism for now and then will bring it back in later to confirm with your sql upgrade stuff.

**Comment by sjpadgett** [comment]
whichever you want. just go ahead and bring yours in and i'll retest.

**Comment by bradymiller** [comment]
done on the revert. will hold on bringing in @eyalvo-matrix PR until your stuff is done also.

**Comment by sjpadgett** [comment]
lol hope @eyalvo-matrix doesn't get too mad at me!

**Comment by bradymiller** [comment]
This setting has been added to the guide (with enough description so we hopefully don't need to research this again :) ):
https://www.open-emr.org/wiki/index.php/Administration_Globals#Enable_Database_Connection_Pooling

**Comment by eyalvo-matrix** [comment]
@sjpadgett  I am a very calm person ;)

**Comment by sjpadgett** [comment]
@bradymiller Another collaboration between us. Ya know, folks may begin to talk!

**Pull request merged**
