### PR TITLE
[WIP] php 8 fun fix

### LINKED ISSUE #3101: php8 fun
### Describe the bug

image

PHP8-dev travis syntax checker is noting the following issues:
```
PHP Deprecated:  Required parameter $search_term follows optional parameter $form_code_types in ./custom/code_types.inc.php on line 835
PHP Deprecated:  Required parameter $patient_id follows optional parameter $proc_type in ./custom/qrda_functions.php on line 226
PHP Deprecated:  Required parameter $components follows optional parameter $send in ./interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php on line 469
PHP Deprecated:  Required parameter $list_id follows optional parameter $option_id in ./interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php on line 1302
PHP Deprecated:  Required parameter $htmlin follows optional parameter $pid in ./interface/billing/ub04_dispose.php on line 96
PHP Deprecated:  Required parameter $pid follows optional parameter $page in ./interface/eRx_xml.php on line 167
PHP Deprecated:  Required parameter $justify follows optional parameter $modifier in ./interface/forms/CAMOS/content_parser.php on line 41
PHP Deprecated:  Required parameter $provider follows optional parameter $authorized in ./src/Billing/BillingUtilities.php on line 1350
PHP Deprecated:  Required parameter $contentType follows optional parameter $formBody in ./src/Billing/EDI_270.php on line 878
PHP Deprecated:  Required parameter $auditvals follows optional parameter $type in ./portal/lib/appsql.class.php on line 139
PHP Deprecated:  Required parameter $doc_id follows optional parameter $patient_id in ./controllers/C_Document.class.php on line 376
PHP Deprecated:  Required parameter $to follows optional parameter $title in ./portal/lib/portal_pnotes.inc on line 220
PHP Deprecated:  Required parameter $to follows optional parameter $title in ./portal/lib/portal_mail.inc on line 314
```

More about the above deprecated message can be found in the PHP8 upgrade doc:
https://github.com/php/php-src/blob/master/UPGRADING#L145-L151

Feel free to fix them and push a PR to see if the PHP8-dev travis syntax checker has no more errors. Note OpenEMR does not work with PHP8-dev because some of OpenEMR's dependencies are breaking (am confident they will be fixed by upstream packages as PHP8 gets closer to release time, which I am guessing is many, many, many months away).

### PR DESCRIPTION
**Pull request by im-Amitto**
Fixes #3101

#### Short description of what this resolves:
php8 Travis warnings

### CODE REVIEW

**Comment by im-Amitto** [comment]
@bradymiller Let me know if this goo fix.
I didn't wanna re-order the function parameter as it can cause an error in so many unexpected ways and sometimes method may lose logical reading so I tried fixing it but placing `Type` in front of the optional parameters.

**Comment by bradymiller** [comment]
hi @im-Amitto , Very nice! Agreed that avoiding re-ordering is vital to prevent bugs. Is this still a `WIP`? If not, then I'll test it out and then bring it into codebase. thanks! -brady

**Comment by im-Amitto** [comment]
@bradymiller it's ready.

**Comment by bradymiller** [comment]
hi @im-Amitto , This appears to be testing well, so bringing into codebase. PHP8, here we come :) thanks for the improvements! -brady

**Pull request merged**
