### PR TITLE
Added ability to use Stripe from within openEMR to charge credit cards

### PR DESCRIPTION
**Pull request by zbig01**
/interface/main/tabs/menu/menus/standard.json
 /interface/main/left_nav.php
 /interface/super/edit_globals.php
 /library/globals.inc.php
 /sql/database.sql

The scripts that are used in stripe are:
    A. To collect, charge and store credit card information
        /interface/payment_processing/stripe/index.php
        /interface/payment_processing/stripe/confirmation.php
        /interface/payment_processing/stripe/charge.php
        /interface/payment_processing/stripe/config.php
        /interface/payment_processing/stripe/receipt.php
        /interface/payment_processing/stripe/stripe_help.php

    B. Reports to view and 'assign' the collected payments
        /interface/payment_processing/reports/credit_cash_check_charges_detailed_totals_assign_pp.php
        /interface/payment_processing/reports/credit_cash_check_charges_detailed_totals_pp.php
        /interface/payment_processing/reports/process_payment.php

Below added by bradymiller:
Demo is here:
http://www.open-emr.org/wiki/index.php/Development_Demo#Iota_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by bradymiller** [comment]
Set up an Up For Grabs demo for this PR here (for now giving absolute path since openemr website/wiki is down; username:admin password:pass):
[https://four.openemr.io/f/openemr/interface/login/login.php?site=default](https://four.openemr.io/f/openemr/interface/login/login.php?site=default)

**Comment by zbig01** [comment]
Give it a whirl. Super easy to try out. After installing this PR
Step 1: Administration > Globals > CC Gateway
stripe-1
Step 2: Select a patient , Fees > Stripe Credit Card
stripe-2
Step 3: Use the Help icon to get further info
stripe-3

**Comment by juggernautsei** [comment]
Beautiful!! and up to date.

**Comment by juggernautsei** [comment]
@bradymiller I see where there have been some updates the original code.  I see where the code needs to go from where it is to make it into the code base.  Or can this go into the code base as is? I realize you may not have reviewed the code yet.  The $lang = array bothers me.  @zbig01 where you going to bring the code up to the current standards?

**Comment by bradymiller** [comment]
hi @juggernautsei ,
This is in code review phase(I haven't looked at the code yet). Definitely feel free to do a code review on this (we are always in shortage of code reviewers and it's a really good way to learn more; and don't feel the need to cover everything, even just a couple review comments is very helpful, such as the lang array thing).
-brady

**Comment by juggernautsei** [comment]
@bradymiller I did not know I could do a code review.

**Comment by bradymiller** [comment]
@juggernautsei , heck ya you can do code reviews! Anybody in the community can do them and you are definitely ready to do them (they are a really good way to learn more about the codebase and openemr also). -brady

**Pull request closed without merging**
