### PR TITLE
Fixed php8 issue, added method for ccda.

### PR DESCRIPTION
**Pull request by adunsulag**
Clinical notes was breaking on php8.  Added a method @sjpadgett needs for CCDA.

### CODE REVIEW

**Comment by sjpadgett** [comment]
@adunsulag 
As I mentioned we now know why the contrib clinical_notes form exist. It was for MU2.
As for `fetchFormValues($pid, $encounter, $formTables)` calling encounter form reports this is for creating html unstructured documents. That workflow may be useful for FHIR api.

Merging and moving on. Thank you sir!

**Comment by sjpadgett** [comment]
umm finally got to test my changes. I'm so happy!:)

image

**Comment by stephenwaite** [comment]
channel panel? :love_you_gesture:

**Comment by adunsulag** [comment]
Congratulations @sjpadgett Also @stephenwaite  what does channel panel mean?

**Comment by stephenwaite** [comment]
flower power for cardios?

Screenshot from 2021-07-02 17-37-43

**Pull request merged**
