### PR TITLE
couple places top_restore was needed

### PR DESCRIPTION
**Pull request by stephenwaite**
loads correct encounter after opening a pt in a new window from from patient finder

#### Changes proposed in this pull request:
couple restoreSession()s

### CODE REVIEW

**Comment by bradymiller** [comment]
2DV (1)

**Review by bradymiller — APPROVED** [review]

**Comment by stephenwaite** [comment]
didn't seem to have any effect on the demos, have also noticed the datatables warning from the main tab that was used to open the pt in a new window
Screenshot from 2021-04-11 09-54-45

**Comment by sunsetsystems** [comment]
@stephenwaite So is this still broken? I was looking at this as well (without your fix here). The datatables warning seems to be caused by a CSRF error in dynamic_finder_ajax.php, maybe caused by yet another missing restoreSession call. This script is supposed to return valid JSON and the die() message is not that.

**Comment by stephenwaite** [comment]
hi @sunsetsystems, yep, still broken.

**Comment by bradymiller** [comment]
@stephenwaite , this popup should now be fixed (also put fix in rel-600)

**Comment by stephenwaite** [comment]
88220254-ba0afc00-cc30-11ea-9dd4-503ca1172e0e

**Pull request merged**
