### PR TITLE
docs: add command to view php logs within openemr docker

### PR DESCRIPTION
**Pull request by prondubuisi**
docs: add command to view php logs within openemr docker
fixes issue  #3144

### CODE REVIEW

**Comment by prondubuisi** [comment]
> thanks @prondubuisi, there's also this variation
> 
> ```
> docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c 'tail -f /var/log/apache2/error.log'
> ```

Hello @stephenwaite do I add the Variation too?

**Comment by stephenwaite** [comment]
just saw where Brady gave you the go ahead so disregard my variation, think it would be better as part of step 5 though

**Comment by prondubuisi** [comment]
> just saw where Brady gave you the go ahead so disregard my variation, think it would be better as part of step 5 though

Something like this

5. Make changes to any files on your local file system. Most changes will appear after a refresh of the page or iFrame you're working on.
    - An exception to this is if making changes to styling scripts in interface/themes/. In that case will need to clear web browser cache and run the following command to rebuild the theme files:
    ```
    docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c 'cd openemr; npm run build'
    ```
    -  To check PHP error logs run
   ```
   docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c 'cat /var/log/apache2/error.log'
   ```

**Comment by bradymiller** [comment]
hi @prondubuisi , your changes posted above look good (ie. placing it in item 5).

**Comment by prondubuisi** [comment]
> hi @prondubuisi , your changes posted above look good (ie. placing it in item 5).

Fixed @bradymiller

**Comment by bradymiller** [comment]
hi @prondubuisi , Looks good and bringing into codebase. Thanks for improving the docs! -brady

**Comment by bradymiller** [comment]
I just realized @stu01509 's sh was removed (it was just brought in, so your branch didn't have it). I'll add that back real quick and place a sh on the other block also.

**Comment by prondubuisi** [comment]
> I just realized @stu01509 's sh was removed (it was just brought in, so your branch didn't have it). I'll add that back real quick and place a sh on the other block also.

Super thanks @bradymiller

**Pull request merged**
