### PR TITLE
Remove empty in-line <script> tags

### PR DESCRIPTION
**Pull request by harshlele**
Fixes Issue #2012

### CODE REVIEW

**Comment by danehrlich1** [comment]
@bradymiller Can you look at this and approve if it's okay? I'm sure it's dead code that should go, but you should definitely look at it first. 

@harshlele Are there other instances of this in the codebase? If so can you fix them? Don't have to hunt them all down but 90% deleted (assuming Brady OK's it) would be good.

**Comment by bradymiller** [comment]
hi @harshlele  , Code looks good and bringing this into the codebase. Thanks for the contribution! -brady

**Comment by bradymiller** [comment]
And congrats on your first OpenEMR commit!

**Comment by harshlele** [comment]
Thanks!

**Pull request merged**
