### PR TITLE
fix can not add user to group attendance report 

### PR DESCRIPTION
**Pull request by eyalvo-matrix**
Pressing add patient causes 

image

image

### CODE REVIEW

**Comment by eyalvo-matrix** [comment]
a related issue to that 
https://github.com/openemr/openemr/issues/1313

**Comment by eyalvo-matrix** [comment]
@bradymiller  @sjpadgett  can you approve this?

**Comment by sjpadgett** [comment]
Does it fix the issue?

**Comment by sjpadgett** [comment]
@eyalvo-matrix brought in. Thanks

**Comment by eyalvo-matrix** [comment]
Thanks :) one more down

**Pull request merged**
