### PR TITLE
update to the connected pharmacies

### PR DESCRIPTION
**Pull request by juggernautsei**
This list is for importing into the pharmacy list of all the connected Weno pharmacies in the US

### CODE REVIEW

**Comment by sjpadgett** [comment]
Duuude, you're killing me! Just finished making code base version work but this looks like the original csv layout so will change code but I see a problem in that nobody will want to import pharmacies for the entire state (could be hundreds). Recommend add lookup for city and add that as a restriction i.e only import by city.

**Comment by bradymiller** [comment]
@sjpadgett ,
Was this addressed in your recent PR? If so, let me know, and I'll close this PR.
-brady

**Comment by sjpadgett** [comment]
yes it was

**Comment by bradymiller** [comment]
thanks!

**Comment by sjpadgett** [comment]
@bradymiller Sorry but this needs to be merged as it is an updated list plus it match the csv I just did in code.

**Comment by bradymiller** [comment]
@sjpadgett , just brought this into codebase.
@juggernautsei , thanks for the contribution!
-brady

**Pull request merged**
