### PR TITLE
Immunization and other

### PR DESCRIPTION
**Pull request by sjpadgett**
#### Short description of what this resolves:
- fixup dialog alert/confirm
- fix dlgclose() to catch non iframe content.
- fix immunization registry report and add dialog confirm.

### CODE REVIEW

**Comment by sjpadgett** [comment]
image

@bradymiller Why do we have two sets, immunization registry and syndromic(Reports and CCM)?
Both are broken in CCM where I find it difficult to believe they ever work fully! One has a dependencies that becomes out of scope on form submit while the other, the darn dependency overwrite itself causing reset of previous form var persistence.
Plus immunization doesn't do anything except display and poorly at that! Can't select a patient to do any reporting against and was written that way. umm, what in the world did I get into!:)

I'm for removing from CCM thus saving all the jquery-ui junk rewrites and make CCM a very good import/export module. I can bring our Report->reports hl7 and dispatch up to date(current hl7 version) and maybe integrate with API's for HIE.

Also, we have HIE menu options in various spots that don't make any sense. Like if module->hie hook is turned on, you can't select any other CCM modules except HIE then, what the heck is it supposed to do, look pretty!

In the past, I remember trying to use these two modules with no success all the way back to v4.2.3(never released skipped to v5) so again, do you remember these ever working correctly?

**Comment by sjpadgett** [comment]
Actually I think i'll bring in for the dialog stuff and folks may need for restypes etc. Example of dialog.confirm in here and dialog.alerts elsewhere in code already.

**Comment by sjpadgett** [comment]
image

pretty neat huh!

**Comment by sjpadgett** [comment]
managed not to revert any code this time, yeah! bringing in... ta da.

**Comment by bradymiller** [comment]
I think i remember at one point being able to create some hl7 like thing from the immunization thingy in CCM, but it was a very long time ago. Like idea of focusing on the non-CCM one if possible and demolishing some CCM code :)

**Comment by bradymiller** [comment]
btw, the duplicitous features (i think there are a couple of these things) is likely because ZH went all out on Zend for their MU2 code contributions (whereas MU1 related stuff was not in Zend).

**Comment by bradymiller** [comment]
goodness, duplicitous is not what i meant to say. meant to say duplicated features.

**Comment by sjpadgett** [comment]
Hi @bradymiller I agree that we should remove much of CCM if not all except the module manager, multitable and validation module which I believe is Matrix contribution. I think CCM functionality should be more tightly integrated into OpenEMRs  dependency tree and templates for ease of maintaining. It's been six years and no one has touched CCM except to be aggravated trying to keep up with dependencies.(I won't again go into my dislike for frameworks for long term projects like ours. Purity, is golden!)

**Pull request merged**
