### PR TITLE
fix: sql syntax alter table x12_partners Update 7_0_1-to-7_0_2_upgrade.sql

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #

### CODE REVIEW

**Comment by stephenwaite** [comment]
after dropping the `AFTER` statement forgot to drop the field name

thecoffeecup_agadfaadkp2afq

**Comment by stephenwaite** [comment]
also fixes `x12_submitter_id` which should have been `smallint`

**Comment by stephenwaite** [comment]
used the github editor to create a branch and PR but had a side effect of not being able to view the simple change to `database.sql` however the link, https://github.com/openemr/openemr/pull/6459/files?w=1, will reveal it here on github

**Comment by stephenwaite** [comment]
it was testing fine with the `openemr-cmd drid` database but once the users table had more than 127 loaded it would only allow an `x12_submitter_id` max of 127 :)

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
2DV(1)

**Comment by bradymiller** [comment]
it's weird that database.sql has what appears to be a whitespace change on every line. Did it put windows line endings in or something like that?

**Comment by stephenwaite** [comment]
nope, just an oddity with using the github browser editor :zany_face:

**Pull request merged**
