### PR TITLE
decreased size of menu icons in frames gui

### PR DESCRIPTION
**Pull request by bradymiller**

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @ophthal ,
The double size icon was added by @zbig01 for his themes where the larger icons do make more sense. Interesting, the light style overrides this and only shows normal size icons; I'd recommend going that avenue for Manila theme instead (I agree the smaller icons looks better on the Manila theme).
-brady

**Comment by ophthal** [comment]
Hi Brady,

I started a new branch from the master Reminders-5.0.1 and pushed one tweak to messages.php.
I see the new datepicker now and z-index is not an issue for this one.
It looks fine and is much better than the old datepicker, at least the one that was in 4.3.

I don’t think changing the themes for frames is relevant.  In fact I am not sure the themes as they exist today should stay - moving towards a mobile-friendly professional-looking framework with a true MVC(L) structure like Matt and Robert suggest will change all these things.  Today however is like the seventh day, a day of rest…  This day will last at least a month though.  

Ray

**Comment by bradymiller** [comment]
hi @ophthal ,
Yep, the codebase is heading in a good modern direction, albeit slowly. Agree that at some point the themes and themes mechanism will drastically change.

And thanks for the messages.php fix, which I just brought into the codebase.
-brady

**Comment by bradymiller** [comment]
Also, enjoy your one day of rest :)

**Pull request closed without merging**
