### PR TITLE
fix: Custom report exception and installer UI improvements

### LINKED ISSUE #6218: Cleanup Module Installer Interface
### Describe the bug
Make more responsive. Give more screen space for module setup scripts. This I'm not sure if e want inserted scrips contained to container or container-fluid i.e legacy!
Plus some of the colors need to be more neutral and not so horrible imo...
image

### LINKED ISSUE #6219: Patient report breaks on esign encounter report includes.
Because the pdf and fax flags are passed in and included in report parsing(no earthly reason as to why) both will break several sections of encounter reports

### PR DESCRIPTION
**Pull request by sjpadgett**
Fixes #6218 
Fixes #6219 

#### Short description of what this resolves:
Above issues

### CODE REVIEW

**Comment by sjpadgett** [comment]
@adunsulag @juggernautsei  Does this look better or worst or in between. It seems more useable to me!

image
image

I did notice what seems to me to be a minor annoyance of when you click the [Click Here to get credentials after subscribing] you get stuck on page without a way back to front page if wanted.

**Comment by robertdown** [comment]
@sjpadgett Mind if I add a couple more improvements?

**Comment by sjpadgett** [comment]
@robertdown okay with me.

**Comment by robertdown** [comment]
Eh, go ahead and pull this in, I'm about done for the day, I'll just submit a PR later this week.

**Comment by juggernautsei** [comment]
I think it looks better

**Comment by sjpadgett** [comment]
Eh, go ahead and pull this in, I'm about done for the day, I'll just submit a PR later this week.
What did you want to do and i'll look at

**Comment by bradymiller** [comment]
dance-bear

**Pull request merged**
