### PR TITLE
optimize dev bulk ccda import

### PR DESCRIPTION
**Pull request by bradymiller**
- optimize dev bulk ccda import (by bypassing use of the audit_* tables)
```
Completed patients import (1000 patients) (2545 total seconds) (2.545 average seconds per patient)
Started uuid creation
Completed uuid creation (2805 total seconds; 0.77916666666667 total hours)
```
- gender fix for synthea ccda import

### CODE REVIEW

**Comment by stephenwaite** [comment]
excited_elephant

**Comment by stephenwaite** [comment]
>Completed patients import (999 patients) (2706 total seconds) (2.7087087087087 average seconds per patient)
Started uuid creation
Completed uuid creation (2877 total seconds; 0.79916666666667 total hours)

**Comment by bradymiller** [comment]
brought in one more optimization (skips the import/storing of the xml document which should save significant space in the instance). here's output in the log after run of 1000 patients:
```
ccda directory: /var/www/localhost/htdocs/openemr/contrib/util/ccda_import/synthea
site: default
openemr path: /var/www/localhost/htdocs/openemr
development mode is on
Starting patients import
50 patients imported (36 total seconds) (0.72 average seconds per patient for last 50 patients)
100 patients imported (92 total seconds) (1.12 average seconds per patient for last 50 patients)
150 patients imported (160 total seconds) (1.36 average seconds per patient for last 50 patients)
200 patients imported (228 total seconds) (1.36 average seconds per patient for last 50 patients)
250 patients imported (327 total seconds) (1.98 average seconds per patient for last 50 patients)
300 patients imported (415 total seconds) (1.76 average seconds per patient for last 50 patients)
350 patients imported (507 total seconds) (1.84 average seconds per patient for last 50 patients)
400 patients imported (586 total seconds) (1.58 average seconds per patient for last 50 patients)
450 patients imported (684 total seconds) (1.96 average seconds per patient for last 50 patients)
500 patients imported (810 total seconds) (2.52 average seconds per patient for last 50 patients)
550 patients imported (939 total seconds) (2.58 average seconds per patient for last 50 patients)
600 patients imported (1097 total seconds) (3.16 average seconds per patient for last 50 patients)
650 patients imported (1277 total seconds) (3.6 average seconds per patient for last 50 patients)
700 patients imported (1405 total seconds) (2.56 average seconds per patient for last 50 patients)
750 patients imported (1570 total seconds) (3.3 average seconds per patient for last 50 patients)
800 patients imported (1772 total seconds) (4.04 average seconds per patient for last 50 patients)
850 patients imported (2037 total seconds) (5.3 average seconds per patient for last 50 patients)
900 patients imported (2318 total seconds) (5.62 average seconds per patient for last 50 patients)
950 patients imported (2504 total seconds) (3.72 average seconds per patient for last 50 patients)
1000 patients imported (2745 total seconds) (4.82 average seconds per patient for last 50 patients)
Completed patients import (1000 patients) (2745 total seconds) (2.745 average seconds per patient)
Started uuid creation
Completed uuid creation (3016 total seconds; 0.83777777777778 total hours)
```

Bringing this in :)

**Comment by bradymiller** [comment]
btw, notably the import runs get slower as the number of patient's in the instance increase. So more room for optimizations :)

**Comment by stephenwaite** [comment]
southpark_cheering

**Pull request merged**
