### PR TITLE
Function to provide list of sections in a layout

### PR DESCRIPTION
**Pull request by mdsupport**
Split display_layout_tabs function to get access to list of sections without embedded html output.

below added by bradymiller:
Up For Grabs demo for this PR is here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Nu_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by mdsupport** [comment]
Added option to pull in 'latest' library components through config+header mechanism.
To test/deploy _boostrap 4_ without affecting production setup, perform following:
1. Put latest bootstrap files in assets_static_relative / bootstrap directory.
2. Modify config.yml to include **_orlatest_** and **_subdir_** settings as follows:
```
    popper:
        basePath: %assets_static_relative%/popper.js/dist/
        orlatest: true
        subdir: popper.js/dist
        script: popper.min.js
        autoload: true
    bootstrap:
        basePath: %assets_static_relative%/bootstrap-3-3-4/dist/
        orlatest: true
        subdir: bootstrap/dist
        script: js/bootstrap.min.js
        link: css/bootstrap.min.css
        autoload: true
        rtl:
            basePath: %assets_static_relative%/bootstrap-rtl-3-3-4/dist/
            link: css/bootstrap-rtl.css

```

**Comment by bradymiller** [comment]
Up For Grabs demo for this PR is here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Nu_-_Up_For_Grabs_Demo

**Comment by bradymiller** [comment]
hi @mdsupport ,
As an aside, what happens when you go to bootstrap 4 (in terms of things breaking)?
-brady

**Comment by mdsupport** [comment]
To be sure, bs4 was just an example for 'latest' option.

Re bs4 itself:
Since most of the code in this project is still relying on lot of base stylesheet with several inline styles, bs4 impact is limited .. mainly at container level.  So bulk of work is in stripping inline styles and attaching classes.

However it is great to have many helper functions and use of jQ to push correct classes to entire screen in few lines.

**Comment by sunsetsystems** [comment]
Are these 2 unrelated enhancements in this PR?
Also what am I looking for in the UFG demo?

**Comment by mdsupport** [comment]
Yes, two changes in this PR are unrelated.  When the demo refreshes, for every script using Header class, there would be a script block following Header generated scripts and links : 

`<script>var included_assets = {"jquery":{"scripts":["\/public\/assets\/jquery-min-3-1-1\/index.js"]},"bootstrap":{"scripts":["\/public\/assets\/latest\/bootstrap\/dist\/js\/bootstrap.bundle.min.js"],"links":["\/public\/assets\/latest\/bootstrap\/dist\/css\/bootstrap.min.css"]},"main-theme":{"links":["\/interface\/themes\/style_1.Default.css?v=41"]},"jquery-ui":{"scripts":["\/public\/assets\/jquery-ui-1-12-1\/jquery-ui.min.js"]}}};console.log(included_assets);</script>`

Header functions don't pluck versions otherwise it would better to just include package & version rather than file paths.  Regardless, this makes it possible now to check if e.g. jq-ui is loaded in the script rather than having examine dom and different objects -
```
if (!("jquery-ui" in included_assets)) {
  ... do something;
}
```
Both the changes in this PR are useful but not critical.

**Comment by mdsupport** [comment]
Just noticed that the demo is pointing to another repo.  Since there is a single file per (unrelated)feature, please swap files if interested.

**Comment by bradymiller** [comment]
hi @mdsupport ,

Sorry about that on the demo. I just fixed this and the demo is again using your repo:
https://www.open-emr.org/wiki/index.php/Development_Demo#Nu_-_Up_For_Grabs_Demo

-brady

**Comment by mdsupport** [comment]
Here is the log on console for 3 different scripts - (will disable it before merge).
image

**Pull request closed without merging**
