### PR TITLE
Billing Details Report

### PR DESCRIPTION
**Pull request by tmccormi**
New report that has extreme information on each encounter related to billing process and status.

### CODE REVIEW

**Comment by tmccormi** [comment]
@bradymiller @sunsetsystems please review ...

**Comment by bradymiller** [comment]
Need to use "new" security model:
http://www.open-emr.org/wiki/index.php/Codebase_Security#Plan

Let me know if want me to review this to show how to convert it.

**Comment by sunsetsystems** [comment]
Suggest replacing the tabs with spaces; different text editors will interpret tabs differently.

Also those subselects are wrong. Insurance in effect depends on the encounter date, you don't want to just pick the most recent insurance. See function getEffectiveInsurances() in patient.inc.

**Comment by tmccormi** [comment]
Adding @kchapple to the watch list since this is his code ... :-)

**Comment by Wakie87** [comment]
Hi @tmccormi @kchapple, 

We thank you for your submitting a pull request to OpenEmr. Without contributions like this from the community these types of projects go stale.

Currently we are going through and doing a spring clean of old and outdated pull requests. We are giving contributors the chance to update the code they submitted if they think it is still relevant, close the pull requests themselves, or if we do not hear back within 3 days we will close the pull request ourselves. If you believe that closing the pull request is an error, let us know and we will look at re-opening it.

Thanks

The OpenEMR Team
http://www.open-emr.org/

**Pull request closed without merging**
