### PR TITLE
refactor(ccdaservice): improve DataStack class

### PR DESCRIPTION
**Pull request by raskolnikov-rodion**
Some improvements for the DataStack class of ccdaservice:

- extract it to separate file
- encapsulate properties
- create tests for class

Tested changes by running the OpenEMR app and generating 10 random patients:

image

image

### CODE REVIEW

**Review by adunsulag — APPROVED** [review]
This looks fine.   First time I think in our project that we are introducing private javascript variables/methods (# prefix), but browser support at this point (using MDN as a reference) is pretty widespread so I'm fine with bringing this in.

We haven't really had any discussions on the preferred JS testing framework for the project, but I'm fine with jest and happy to see JS unit tests.

**Comment by bradymiller** [comment]
For sanity testing, rec ensuring that able to produce a ccda (this js ccda stuff is for producing ccda's, not importing them). To do this, rec bringing in the random patients as you already have done, and then exporting one by going to Modules->Carecoordination in top menu and there will see listing of encounters (below screenshot) and can click on the first icon in the last column ('View') (when hover over it, it will show 'Create CCDA') (below screenshot). 

Also, something I do when really want to have broad testing capabilities is bringing in the demo data (then have several users with different access controls set up and also have portal setup for several patients: https://www.open-emr.org/wiki/index.php/Development_Demo#Special_Demo_Credentials_in_Demos_WITH_Demo_Data), then bringing in the 10 random patients:
```
openemr-cmd drid
openemr-cmd irp 10
```
(note the disadvantage of the demo data is that it brings in database changes via the sql upgrade scripts, which is a great way to test the sql upgrade scripts, but would miss bugs in the main database.sql script; for this reason, I usually only use it when need to test access controls and patient portal, but i think for newer developers to the project, it's nice to have these things all set up for testing and playing around with things)

---

image

image

**Comment by bradymiller** [comment]
hi @raskolnikov-rodion , Would there be a way to get the jest testing into the github actions ci pipeline?

**Comment by raskolnikov-rodion** [comment]
Hey @bradymiller , thanks for sharing instructions for further testing. Here's what I got for one of the generated patients:

image

> Would there be a way to get the jest testing into the github actions ci pipeline?

Good point! I created a new step for JS unit testing, check it out. I put it in a new file, but if you think it's better placed somewhere else just let me know. I also included some integration for ESLint and Jest, and improved the lint:js-fix script. It's now referencing the original one, which means if we decide to update the lint script in the future, we just need to change in one place :slightly_smiling_face:

**Comment by bradymiller** [comment]
@raskolnikov-rodion , looks great and bringing in. thanks for another very nice code contribution!

**Comment by bradymiller** [comment]
@bradymiller , note to self, to add this to the devtools/openemr-cmd

**Pull request merged**
