### PR TITLE
Final 502 batch payments. Yeah right!

### PR DESCRIPTION
**Pull request by sjpadgett**
- honor follow up flag for denied claims
- add a link in EOB Invoice to only change/save selected Done with(last level closed)
- some styling

Please read this forum thread:
https://community.open-emr.org/t/major-billing-issues-with-5-0-2-please-help/14641/35

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller 
I'm going to bring this in and then do a final 502 patched up install and test yet once again.  Then forwards this to v6.0.

@stephenwaite 
I think I may have got us there for batch payments. Maybe I can talk @gutiersa into updating the wiki so she can have a life(her words, not mine so PC police, leave me alone:)). I've spotted several areas in billing we can greatly improve in v6. I'd still like to do a claims builder instead of just per encounter based claims.

**Comment by sjpadgett** [comment]
Review for missing files proves neg. I've been horrible at this of late but hey, i'm on the right branch this time.:)

Bringing in with fingers crossed!

**Comment by gutiersa** [comment]
Lol, my health is challenged. So use me for testing!

**Comment by bradymiller** [comment]
2DV

**Pull request merged**
