### PR TITLE
Organize Admin. menu, Remove items from Miscellaneous-relative to #2301

### PR DESCRIPTION
**Pull request by dimitristsilis**
below added by bradymiller:
Up For Grabs demo for this PR here: https://www.open-emr.org/wiki/index.php/Development_Demo#Lambda_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @dimitristsilis ,
Note that the folders also need to do the pertinent acl_checks to avoid showing empty folders. For example, see the acl_checks that the entire Administration folder does (basically need to check for what is checked in the elements inside the folder):
https://github.com/openemr/openemr/blob/master/interface/main/tabs/menu/menus/standard.json#L1100-L1136

**Comment by dimitristsilis** [comment]
@bradymiller Should be ok now

**Comment by dimitristsilis** [comment]
Noticed that some pre-existing menu folders don't have the "acl_req" part, even though their children do. Same with "global_req". Do they need fixes or am I missing something?

**Comment by bradymiller** [comment]
Up For Grabs demo for this PR here: https://www.open-emr.org/wiki/index.php/Development_Demo#Lambda_-_Up_For_Grabs_Demo

**Comment by dimitristsilis** [comment]
Hello @bradymiller. Should I do something for this PR to be merged?

**Comment by bradymiller** [comment]
sorry @dimitristsilis , Am 3 PRs behind :) Will get to this very soon. -brady

**Comment by bradymiller** [comment]
Place the Lists entry in the Forms folder

**Comment by bradymiller** [comment]
For the Administration folder, can remove the following acl_req:
admin:database
admin:superbill
admin:drugs

**Comment by bradymiller** [comment]
hi @dimitristsilis , Just a couple more things to address (see my 2 posts above) and then this will be ready for the codebase. -brady

**Comment by dimitristsilis** [comment]
@bradymiller Done!

**Comment by bradymiller** [comment]
hi @dimitristsilis , Looks good and bringing this into codebase (I am going to follow it with a commit with a couple minor fixes). Thanks for the code improvements! -brady

**Pull request merged**
