### PR TITLE
portal fixes

### PR DESCRIPTION
**Pull request by sjpadgett**
- sidebar responsiveness
- secure message style fix and bug

#### Short description of what this resolves:
BS fixed sidebar was my bad. Made it sticky and other styles to be responsive. Still flex.
Fixed up mail

### CODE REVIEW

**Comment by sjpadgett** [comment]
restoreSession why didn't I do this two years ago.

**Review by bradymiller — APPROVED** [review]

**Comment by sjpadgett** [comment]
@bradymiller I'm close on this form and got rid of jquery-ui. I'd take some translations and escaping and a little more smarty fixups but, i'm not sure it'd get used in the community version. You'd know best if worth the effort. I know you can't tell a lot from screenshot but imagine some. Most the text areas have templates.
image
image

**Comment by bradymiller** [comment]
@sjpadgett , Form looks good and guessing would get good amount of use (reminds me of the eye form with everything contained in 1 form). Happy to help on it.

**Comment by sjpadgett** [comment]
@bradymiller okay thanks. Let me get it closer responsive wise and finish testing the prints etc then i'll send to you to take a look. it's all one smarty directory form so easy install...

**Comment by sjpadgett** [comment]
Doubtful i'll have anymore for this but, more will come. bringing in and back to v6

**Pull request merged**
