### PR TITLE
remove adldap2/adldap2 package since migrated to native php ldap library

### PR DESCRIPTION
**Pull request by bradymiller**
related to following PR:
https://github.com/openemr/openemr/pull/2746

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @sunsetsystems , just making sure we can now remove this package. thanks, -brady

**Comment by sunsetsystems** [comment]
LOL I was just preparing a PR for this too. :)
Yes, please do.
Thanks.

**Comment by sunsetsystems** [comment]
By the way I'm aware that adldap2 was forcing PHP >= 7.2. Can this removal permit use of older PHP versions if other package versions set in composer.json are changed accordingly?

**Comment by bradymiller** [comment]
thanks @sunsetsystems . bringing this into codebase. Regarding php min version, I think still just need 7.1.2 or greater still. I bumped it to 7.2 since the next release will go out when 7.1 is no longer supported ( https://www.php.net/supported-versions.php ).

**Comment by bradymiller** [comment]
btw, if possible, would go with php 7.3 (openemr docker uses 7.3 :) ) since then get to use a nice new php security feature that prevents cross site forgery request:
https://github.com/openemr/openemr/blob/master/src/Common/Session/SessionUtil.php#L57

**Comment by sunsetsystems** [comment]
Thanks Brady. Current Ubuntu LTS has 7.2 by default so I guess we want to stick with that for a while.

**Pull request merged**
