### PR TITLE
Add edit event size

### PR DESCRIPTION
**Pull request by juggernautsei**
Update the windows sizing for the add calender event. It has gotten 
bigger over the years and the template has not been updated. I know I am tired of dragging back and forth to see the whole screen. Now everyone can see the whole thing as intended.

### CODE REVIEW

**Comment by tmccormi** [comment]
The code changes look fine.  (I've done this a few times but never committed)  Thanks.   The branch is messy, so perhaps Brady or I can just cherry-pick the changes over.

**Comment by bradymiller** [comment]
Looks like this commit contains the code changes:
https://github.com/openemr/openemr/pull/110/commits/38d72b6cd1cf2229bf804b68e807aa397ec88d0a

There are also several more places to change. Rec doing following grep command to find them:
``````
grep -R "dlgopen.*add_edit_event.php" /var/www/openemr/

**Comment by bradymiller** [comment]
Actually, here's a better grep command which also picks up the call in the patient board script:
``````
grep -R "open.*add_edit_event.php" /var/www/openemr/

**Comment by juggernautsei** [comment]
I went back in and found all the links and references and updated them to
the larger format.

Sherwin
757-328-2736
Open Med Practice

“For those who believe, no proof is necessary. For those who don't believe,
no proof is possible.” ― Stuart Chase
<http://www.goodreads.com/author/show/1051789.Stuart_Chase>

**Comment by bradymiller** [comment]
Hi Sherwin,

I just rebased your work into 1 commit and brought it into the main codebase. Thank you for the contribution!

-brady

**Pull request closed without merging**
