### PR TITLE
Consolidate ccdaservice to file based project

### LINKED ISSUE #4131: Update current node CDA server/generator to support v2.1
### Describe the problem
Currently CDA document generation mostly supports HL7 Release 1.1. Need to update to a minimum Release 2.1 however while here, will try to bring current to meet 2020 ONC. I believe after rel 2 the Consolidated document is of import and may I say, yuck! 
### Describe the solution you'd like
Need to add several new sections requiring new template leafs and xpaths. Also need to add in all the human readable tables for those missing in rel  1.1(Vitals and Immunizations) and new for rel 2.1+

I'm begging anyone looking to get involved in some interesting engineering and coding to jump on my team. Even if it was to do just the table templates for display. 
This is all JavaScript running on a node server so, come on, it'd be fun, I promise.:)

### PR DESCRIPTION
**Pull request by sjpadgett**
Fixes #4131 

#### Short description of what this resolves:
ONC 2015

#### Changes proposed in this pull request:
Move templates and template engine to local

### CODE REVIEW

**Comment by sjpadgett** [comment]
To install:
- On windows you need to have windows compile tools installed. See README in ccdaservice.
- From ccdaservice dir run npm install.

To debug:
- cd ccdaservice
- node serveccda
- create cda from CCM or portal
- two files are created in ccdaservice: ccda.xml and ccda.json.

Or, just run export in CCM or portal and grab test files from ccdaservice directory.

Remember to stop node service between development mods. This is why I debug from phpStorm or command line.

I just can't find a good reason to run utility node service using express....

**Comment by stephenwaite** [comment]
created the cda from ccm but not seeing the 2 files in ccdaservice/

Screenshot from 2021-03-07 10-56-44

**Comment by sjpadgett** [comment]
hmm, doesn't work for me either. I forgot that the exec command that auto starts server redirects any output to error or null. Sorry!
Ya have to start node from command line. Only other way is to setup a node debug project in ide or download the xml from CCM.

**Comment by stephenwaite** [comment]
so then you run the xml through a validator to follow up on errors?

**Comment by sjpadgett** [comment]
Yes. 
I did some custom attribute and effectiveDate changes for a HIE and turns out was a no no. I haven't tested against validator since C32 and errors are more extensive than I thought.
I'm doing some changes today to the core templates and their leafing(z schema) where you'll get a better idea of how works.
Or we can have a call to discuss. The javascript isn't too difficult and mainly just dealing with populating json arrays.

**Comment by sjpadgett** [comment]
Actually running against normative R1.1 not to bad
7 Schema errors
21 Schematron errors

**Comment by bradymiller** [comment]
CCDA moonwalk!

tenor99

**Comment by sjpadgett** [comment]
I'm somewhat relieved this phase of project is finished. We now have the solid base to improve compliance above passing normative IG. Surprisingly, having only 20-30 warnings is not bad considering many other CDAs I've tested tend to average 15 warnings. 

If we have anyone whom may want to test and improve while I work on interop please, don't be frightened to take on where I'll help explain how the templating and schema engine works(actually a pretty interesting design and easily adaptable to future). It's mostly dealing with json to xml/xml to json and javascript object and array manipulations.

Now that I no longer have to worry about having a build environment setup for windows installs(changed library to one that has binaries available) we may be able to auto install. Total build size is 50MB so don't think I have it small enough yet to ship in release build. Otherwise, the features footprint in master is around 1.5MB. Maybe this can get worked out with @kchapple node stuff implementation.

Anyway, anyone interested in development I'll be happy to have a phone call to explain the details.

**Comment by sjpadgett** [comment]
An example of a Cerner C-CDA TOC gives ya an idea how close we are with others.
image

**Comment by stephenwaite** [comment]
mind_blown

**Comment by sjpadgett** [comment]
Careful! we already have the DEA for preventing drug addiction. If not careful we may see the GEA. Gif Enforcement Agency!
Complete with new ICD10 e.g GIF10.4 Gif addition (Moderate)

**Comment by bradymiller** [comment]
tenor (63)

**Comment by sjpadgett** [comment]
Check out my gif:)
image

**Pull request merged**
