### PR TITLE
added dwv package and dependencies

### PR DESCRIPTION
**Pull request by bradymiller**
Also worked out the modernizr stuff and is documented here(and added a commit with the dist/modernizr-build.js script in it):
http://www.open-emr.org/wiki/index.php/Bower#modernizr-3-5-0

At this point the PACS stuff should now have all the needed libraries (ie. fingers crossed).

### CODE REVIEW

**Comment by bradymiller** [comment]
Ok, worked out the modernizr stuff here(and added a commit with the dist/modernizr-build.js script in it):
http://www.open-emr.org/wiki/index.php/Bower#modernizr-3-5-0

**Comment by kofiav** [comment]
Sweet 😄

Thanks for looking into this - I believe those are all the dependencies and we won't need to worry about this again.

**Comment by bradymiller** [comment]
@kofiav ,
Cool. Will bring this into the codebase then and will update the bower wiki page.
-brady

**Comment by bradymiller** [comment]
Note to self. I need to go through and mark the the directories that need to be removed (tests etc.) and then run phing.

**Comment by bradymiller** [comment]
Note to self. DONE cleaning up the directories and removed them via phing: https://github.com/openemr/openemr/pull/1218

**Pull request merged**
