### PR TITLE
SNOMED RF2 support.

### PR DESCRIPTION
**Pull request by bradymiller**
Support for SNOMED RF2 standard. Author is Roberto.

Continued from this PR:
https://github.com/openemr/openemr/pull/452

Prior revision code review was here:
https://github.com/bradymiller/openemr/commit/f6f40d0c31964ab67a7f20c99750868eda1d880a

### CODE REVIEW

**Comment by bradymiller** [comment]
@robertogagliotta , placed your code on this PR :)

**Comment by MatthewVita** [comment]
Is this feature a candidate for the 5.1.0 release?

Also, when it is released, please update the following areas:
- http://open-emr.org/wiki/index.php/OpenEMR_Features#Medical_Billing
- http://open-emr.org/wiki/index.php/Import_RxNorm_and_SNOMED_Tables
- http://open-emr.org/wiki/index.php/Code_Types

**Comment by robertogagliotta** [comment]
No problema Matthew.
I think this Snomed RF2 support feature will be ready for the 5.1.0 release.

**Comment by bradymiller** [comment]
Hi @robertogagliotta ,
Sorry for the delay on this. Got a bit stuck on the MU2 portion testing (need to test CCDA to ensure it doesn't affect MU2 certification items). Sounds like your learning a lot about AWS now, which is definitely a cool skill. I should be able to get through testing and review of this by the end of this week.
-brady

**Comment by bradymiller** [comment]
by the way @MatthewVita , next version will be 5.0.1 (need to do this to keep MU2 certification)

**Comment by MatthewVita** [comment]
@bradymiller Cool. However, is there any way we can bump the 5.**x**.0 number?

Otherwise, I'm happy with bumping the patch.

**Comment by robertdown** [comment]
@MatthewVita we have to maintain 5.0.x for MU. So we probably won't see 5.1 ever

**Comment by MatthewVita** [comment]
Ouch.

**Comment by sjpadgett** [comment]
My impression is only major version could not be bumped but minor and patch could. Curious from where this requirement comes. Minor and patch are used when backwards comparability is maintained and then when changes no longer maintain compatibility does major version change.

**Comment by bradymiller** [comment]
If we go to 5.1, we will lose MU2 certification (and would require 22K and likely 4 months to certify it :) ).

**Comment by sjpadgett** [comment]
That's what I don't get! Where does this come from? Is it the people doing the certification or is it a federal position that dictates how we do versioning? @bradymiller  I'm not trying to start an argument over this really trivial semantic but I get very annoyed when someone, somewhere institutes these measures that make no sense. Example: The DOT revised their medical examination two years ago with an expiration of end of 2018 and have since moved a disclaimer paragraph and are requiring all reporting on the new form, regardless of impact. So when it was pointed out they have to follow their own regulations on expiration of forms they simply made a requirement, on the fly, that in order to re-certify to issue the certification, the provider has to sign a waiver honoring the new form. Millions are at stake so the DOT can be king.
Point is, if this comes from the certification agent without a federal cite then they are suspect, but, if this comes from a federal cite, it is a battle I would readily take on! As long as we maintain MU2 backwards compatibility, it is no ones business how we version our software. Sorry guys but; "Give me liberty or give me death" :)

**Comment by bradymiller** [comment]
@sjpadgett ,
As you likely know with experience with regulations; if one were to make a stink about this, then it would just hurt us (ie. direct attention towards our project and requests for huge amount of paperwork detailing all code changes). With 100% confidence, I can tell you that 5.0 is MU2 certified and that 5.1 will not be MU2 certified. With 100% confidence, I can tell you that any complaints or requests for "further clarification"(note we have confirmed this multiple times with both testing bodies that we have used in the past) on this issue would snowball into overregulation hell for the OpenEMR project :)
-brady

**Comment by bradymiller** [comment]
@sjpadgett ,
Just another quick point to put things into context. One of the big reasons that MU2 was delayed was the absolute rigidity of the certification/regulation guidelines which led to some really ridiculous endpoints; and the more questions and clarifications that were asked, the more ridiculous things became. It was almost like you were punished for asking questions and clarifications(ie. the cat was let out of the bag, so to speak). And then certification became much more smooth when a group (I won't mention name, but there name starts with a V.. :) ) came along whom just confidently moved testing along whom just addressed issues with minimal clarifications(it was almost like an art to watch); and the solutions also became less ridiculous :)
-brady

**Comment by sjpadgett** [comment]
@bradymiller Not a rebel I see. Guess we will just have to disagree!

**Comment by sjpadgett** [comment]
@bradymiller Trust me, I truly appreciate the tremendous effort put forth by all you guys and I suppose I'm a little late to the party so, forgive the rebel in me.

**Comment by bradymiller** [comment]
@sjpadgett ,
lol, very true, rebel inside me has been squashed by MU. definitely need rebels, such as yourself, on the project to keep things sane.

**Comment by sjpadgett** [comment]
Okay, guess it will be v5.0.99aaaaaaaaa 'till we run out of alphabet :) I now return you to your regularly scheduled thread...

**Comment by MatthewVita** [comment]
Looks like it's one of those "choose your battles" situations. I'm happy with bumping patch, in this case :).

Sorry for derailing the PR!

**Comment by robertdown** [comment]
Bumping this back to the top, it's lingering and really want to see it in

**Comment by robertdown** [comment]
@bradymiller Anything blocking this PR?

**Comment by bradymiller** [comment]
Still testing and some more code work to do here. I'll try to prioritize testing/review of this PR.

**Comment by bradymiller** [comment]
Note some details can be found on prior Issue for this: https://github.com/openemr/openemr/issues/410

**Comment by robertogagliotta** [comment]
Hi Brady

**Comment by bradymiller** [comment]
Yep, goal has been to get this thing done, but I keep getting distracted :)

**Comment by robertdown** [comment]
I just tried installing RF2 and it's still not working. @bradymiller can you test this? If not I'll take it over, this PR has been hanging for over a year now :)

**Comment by bradymiller** [comment]
hi @robertdown ,
That would be great since I am swamped with other stuff.
(note I haven't been able to test this for some time, but as I recall, it was bringing in RF2 codesets, however several more minor changes were needed in terms of the tracking and dealing with RF1 codeset)
thanks, -brady

**Comment by bradymiller** [comment]
If needed, I could likely get this rebased into most recent codebase (That would only take me several minutes likely). Just let me know if you need me to do this. -brady

**Comment by robertdown** [comment]
I'll work on getting it rebased

**Comment by bradymiller** [comment]
continued her: https://github.com/openemr/openemr/pull/2329

**Pull request closed without merging**
