### PR TITLE
Add combined Nationality and Country list.

### LINKED ISSUE #6891: Add a combined nationality with country list to Demographics Stats group
### Describe the problem

Title says it all. List has 249 items with search.
I don't remember if I put the list with search datatype in or not whatever the case very nice addition. Needed to change inline style from align center to normal. Even for display: Grid it is better than trying to center on list that are not multi select or grids.

### PR DESCRIPTION
**Pull request by sjpadgett**
update database and upgrade for new list and layout option in Stat.

Fixes #6891 

#### Changes proposed in this pull request:
update database and upgrade for new list and layout option in Stat.

### CODE REVIEW

**Comment by sjpadgett** [comment]
Found new issue with List select dialog and wouldn't be notice unless view in console or user debug is turned on!

image

**Comment by stephenwaite** [comment]
related to #5667

**Comment by stephenwaite** [comment]
I think this package, https://github.com/mledoze/countries, is a better solution than adding this custom csv list.

**Comment by sjpadgett** [comment]
Same list and who is going to import the list after install? There is only a certain number of countries and one list is as good as another. What about maintaining legacy is an admin going to try and merge changes to existing lists.
The only diff in the project you like is more geo info etc is available.

**Comment by sjpadgett** [comment]
@stephenwaite I'll look at how much csv changes I need to make toi import to list if you feel more comfortable with this project generated list.

**Comment by stephenwaite** [comment]
ok, thanks @sjpadgett , was wondering if we don't have to save the csv list to the db but that probably presents other issues for the list stuff.

**Comment by sjpadgett** [comment]
I've already justified adding list and for many non profit refugee centers and international alone is justification to have list permanent. I have tried to justify list in DB otherwise if I didn't feel comfortable with my integration I would not have taken on the project.
However if this is still uncomfortable or of concern to others I will pull the PR.

**Comment by stephenwaite** [comment]
was just thinking the dropdown would hit that value from the package but this is probably better, thanks

**Comment by sjpadgett** [comment]
I'd be worried about legacy i.e. if field option id values change etc. I get your worry about DB size though Stephen.

**Comment by stephenwaite** [comment]
not worried about DB size just trying to think of an easy way to update, also to combine country and nationality seems odd but fits Ruth's requirement and if I remember Brady was fine with it.

**Comment by stephenwaite** [comment]
great job getting all these pieces working, just tested it and it's working well!

**Comment by sjpadgett** [comment]
My original plan was two lists but after testing the combined list it seemed easier for user.
Thanks for testing for me!

**Comment by bradymiller** [comment]
dance-bear

**Pull request merged**
