### PR TITLE
fix support of rtl on datepicker openemr

### PR DESCRIPTION
**Pull request by oshriromatrix**
Hi, I just fix the rtl of the date picker, month and years are now in rtl current direction.
thanks oshri.

### CODE REVIEW

**Comment by bradymiller** [comment]
Is this for the new datepicker?

**Comment by oshriromatrix** [comment]
yes it for the new datepicker

**Comment by bradymiller** [comment]
The new datepicker is set up to use rtl already. Is there something specific that is not working?
https://github.com/openemr/openemr/blob/master/library/js/xl/jquery-datetimepicker-2-5-4.js.php#L52

**Comment by oshriromatrix** [comment]
yes but in Hebrew we need to reverse the triangles and the next button and prev button.
we need the month and years to be in rtl, now they are in ltr.
so I have fix the bug created for rtl code in css only.

image

**Comment by bradymiller** [comment]
(sounds reasonable; just a couple quick clarifications below)
To clarify, in your opinion, is this a Hebrew specific issue or a issue for all RTL languages?
Also, to clarify, just want to make sure you are not modifying the date formatting in the input textbox itself?

**Comment by oshriromatrix** [comment]
we do not know how to read another rtl language, but in Hebrew it need to be like that.
we don't change the formatting of the textbox.

**Comment by bradymiller** [comment]
sounds good. will bring this into the codebase. thanks! -brady

**Pull request merged**
