### PR TITLE
Fixed directory names to match lowercase standard

### PR DESCRIPTION
**Pull request by Wakie87**

### CODE REVIEW

**Comment by bradymiller** [comment]
This makes me very nervous, because there are likely lots of downstream links dependent on this. I used to believe that all paths and names needed to be lowercase, but then I realized things work just fine in cases where classes and packages (including the paths) use uppercase a lot. Do you know of situation where things break when not using lowercase?

**Comment by robertdown** [comment]
Disagree with this PR. Symfony, ZF2, and plenty of other large libraries use uppercase folders throughout the keep things in line with namespaces and classes. My logger code (and subsequent modernization code) will do the same thing (i.e. `Patient/src/Patient/Demographics.php`).

PHP-FIG PSRs don't seem to take a stand on this. Those are the standards I suggest we stick to (will post on forums separately about the PSR standards).

**Comment by bradymiller** [comment]
Too funny. I just sent Scott a message on slack that I was warming up to this commit.

**Comment by bradymiller** [comment]
As long as we follow the standards or change to the standards, if needed. Is there a nice site that covers the PSR standards (will link this in the Modernization wiki page).

**Comment by robertdown** [comment]
http://www.php-fig.org/psr/

**Comment by bradymiller** [comment]
thanks,
I posted the link on the modernization wiki page.

**Pull request closed without merging**
