### PR TITLE
MedEx Tweaks

### PR DESCRIPTION
**Pull request by ophthal**
Apply hipaa_override to all message group.
Delete MedEx Preference "Assume patients permit Messaging" from the interface.
Will need an additional PR to remove the corresponding field from DB.

### CODE REVIEW

**Comment by stephenwaite** [comment]
Hi Ray @ophthal , guessing something broke on `v7`. Can you checkout this forum thread or fill us in on anything you can please? Thanks

**Comment by ophthal** [comment]
Looks like these changes are not in your master and probably not the user’s either.
Please confirm and if so  I think it just needs to be reviewed and added to a patch.

**Review by stephenwaite — APPROVED** [review]
thanks @ophthal

**Review by bradymiller — APPROVED** [review]

**Comment by stephenwaite** [comment]
nice @ophthal , just let us know when to pull the trigger :)

**Comment by ophthal** [comment]
There is also one change needed in save.php in interface/main/messages.  I’ll send that later today.

**Pull request closed without merging**
