### PR TITLE
Linode Demo

### PR DESCRIPTION
**Pull request by ophthal**

### CODE REVIEW

**Comment by openemr** [comment]
Most recent review here:
https://github.com/bradymiller/openemr/commits/ophthal-optho-module_4

**Comment by ophthal** [comment]
> On Mar 12, 2015, at 1:43 AM, OpenEMR <notifications@github.com> wrote:
> 
> Most recent review here:
> https://github.com/bradymiller/openemr/commits/ophthal-optho-module_4 <https://github.com/bradymiller/openemr/commits/ophthal-optho-module_4>
> —
> Reply to this email directly or view it on GitHub <https://github.com/openemr/openemr/pull/39#issuecomment-78427145>.
> 
I think I have the github thing working with a fresh base at:
https://github.com/ophthal/openEMR_1.git <https://github.com/ophthal/openEMR_1.git>

Please let me know so I can try it out and test it.  Still working on the extracts, at least of the main $_REQUEST and $_SESSION ones.

Ray

**Comment by bradymiller** [comment]
Hi,

Sorry didn't get to it this weekend. Will plan to look through it sometime this week.

It looks like you have created a new repository, which is generally never needed. Much better to instead create new branches on your original repository. What was the reason for the new repository?(this will help me to figure out what to recommend doing next)

-brady

**Comment by ophthal** [comment]
Short answer: I have no idea what I am doing! 

GitHub updated its program and now it keeps crashing. Very frustrating.  

There is a lot of code there - would be nice to have access to programmers. What I hacked up in 4 months they'd have done in a few weeks!  

Though there are a lot of changes the form is functioning well enough I think for testing by a wide audience. 

I am nearly done removing the extract $_REQUEST AND $_SESSION.  

I did not address the table changes for past ocular hx etc yet.

There is no delete eye_mag and revert back to original unscathed yet. 

 I haven't started the higher order logic for customizing the form on a user basis over time - this will be interesting but I do not think it is needed to get a functioning form out the door.  

I am learning how to integrate a form into openemr and use the pre existing code.  

The ROS needs to be done.  I will revise the preexisting form and link to it using the menu system you built in the framed version.  In the full screen view, there is a new menu which I am getting ready to tackle. I will need to see how the framed menu is built to learn how items are chosen for display to do it correctly.  

The imp plan needs to be built. It is just two pitiful fields today. With user actions, we should be able to prepopulate the icd9/10 codes. Also it should have a way of displaying past codes... It needs to have separate sections for each issue, so it may need a new table.  

Although you can have more than one Chief complaint, I limited the form to three.  If someone needs more, then it will require a new table too. The new table will allow a one-to-many relationship. One encounter, many options. I see this as possible with not only the chief complaint and the imp plan area but also refractions and glasses.  Some people show up with 5 pairs of glasses and the eye doc has to figure out what's up! 

Well with that the form should be something an eyedoc would actually enjoy using. Key is to wrap it up in such a way that it speeds up the encounter.  That is my real goal. 

Ray

**Comment by bradymiller** [comment]
The joys of git. Just keep doing your developing. This weekend, Ill point a demo to this repo/branch and when it's ready for review then will make another super commit.

**Comment by ophthal** [comment]
Hi Brady,
I just uploaded the latest eye_mag stuff to

https://github.com/ophthal/openEMR_1.git

I decided to scrap the sketch.js and built out another canvas script which utilizes client side image functions allowing undo and redo's with multiple canvases on the same page.   These HTML5 options are getting better but to really be effective I would have to figure out how to do layers to drag and drop objects.  This may be something for freelancer.com...

I think most of the worrisome extracts are removed.

Ray

**Comment by bradymiller** [comment]
Here's the online "up for grabs" demo to your master branch on your openemr_1 repo:
http://www.open-emr.org/wiki/index.php/Development_Demo#192.168.1.130

**Comment by ophthal** [comment]
I just tried it and noticed some issues, perhaps related to "extract"...

**Comment by bradymiller** [comment]
This is an outdated PR so will close this(note this form will be in the codebase in the near future, which is very exciting).

**Pull request closed without merging**
