### PR TITLE
Fee sheet review hangs if the justify field in the database is empty

### PR DESCRIPTION
**Pull request by juggernautsei**
I have encountered this again. In our database, the justify field does not always contain data. So when the review button is clicked. The console error is shows that the justification justify_codes is null. I believe you can test this out on any system. Leave the justification null and it should hang or from the users view cause the Review button not to work.

### CODE REVIEW

**Comment by MatthewVita** [comment]
@juggernautsei,

Looks good. Would recommend switching around the code a bit to this (untested, but it should work):

```
if (json_source.justify !== null) {
    var justify_codes = json_source.justify.split(":");
    for (var idx = 0; idx < justify_codes.length; idx++) {
        var justify_parse = justify_codes[idx].split("|");
        if (justify_parse.length == 2) {
            var new_code = {};
            new_code.code_type = justify_parse[0];
            new_code.code = justify_parse[1];
            new_code.descriptions = "";
            new_code.selected = true;
            var ko_code = new code_entry(new_code)
            ko_code.priority = idx + 1;
            retval.justify.push(ko_code);
        }
    }
}

```

**Comment by juggernautsei** [comment]
I will put this in the production environment and test. I was taught, do the simplest thing that works. But that leaves whatever I do open for better.

**Comment by juggernautsei** [comment]
Updated

**Comment by MatthewVita** [comment]
@juggernautsei great stuff. I agree that simple/working software is always best. I think the update makes it a tad easier to follow but it's still in line with the simple/working philosophy.

Great work.

**Pull request merged**
