### PR TITLE
Changing contact information

### PR DESCRIPTION
**Pull request by juggernautsei**
Fixes #

#### Short description of what this resolves:
Change company information

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @juggernautsei , bringing this in (will also bring into rel-600 and the wiki)

**Comment by juggernautsei** [comment]
Thanks!

**Comment by bradymiller** [comment]
quick question @juggernautsei ,
Is the new weno code in master branch testing well?
(once it is confirmed that it is testing well, then plan to get it into rel_600 for next 6.0.0 patch)

**Comment by juggernautsei** [comment]
Yes, the code was tested before, during, and after putting it into the PR. Here is a video of the code in action. 

https://user-images.githubusercontent.com/834958/105933315-333e3e00-601c-11eb-9255-7413b7f27a14.mp4

**Comment by bradymiller** [comment]
cool, i just brought it into the rel-600 branch. so it will be in the next 6.0.0 patch :)

**Comment by stephenwaite** [comment]
thank you @juggernautsei  @bradymiller 

could i take this for a test drive @juggernautsei ?

**Comment by juggernautsei** [comment]
Yes, you can. It is ready to go. @stephenwaite 
If you don't have a Weno Exchange account you have to sign up at https://online.wenoexchange.com. In the registration process select EHR EZ Integration
image

The select OpenEMR Community version.
image

**Pull request merged**
