### PR TITLE
Suggestion: using btn-group on action button can be confusing

### PR DESCRIPTION
**Pull request by im-Amitto**
Previous: 
Screenshot from 2020-03-30 16-50-59
New:
Screenshot from 2020-03-30 16-51-51

### CODE REVIEW

**Comment by im-Amitto** [comment]
@stu01509, @tywrenn  What you think about it?

**Comment by stu01509** [comment]
Hello @im-Amitto 

In my opinion, I prefer to follow the in this comment styling guide.
https://github.com/openemr/openemr/issues/3160#issuecomment-600342688

**Comment by adad20** [comment]
hi @im-Amitto as per the #3160 two or more button should be in `btn-group` class. That's why I made it like that.

**Comment by im-Amitto** [comment]
@stu01509 I am following that thread that's why I just raised it as a suggestion and not as an issue.
IMHO I think it just doesn't look right and may not be liked by users as it's not a common practice.
@adad20 I know you were following the rules and nice work, it's just a suggestion :smile:

**Comment by stu01509** [comment]
Hello @im-Amitto 

Maybe we wait for @tywrenn to explain his opinion.

**Comment by bradymiller** [comment]
hi @tywrenn , Note that the most important thing on this modal is that users select `Submit`. The users only see this screen once, so how it looks is not as important. Seems like to avoid users clicking "No Thanks" that having it a danger color might help in this regard. And making the Submit happy and blue might also get users to click on it.

**Comment by bradymiller** [comment]
Note I am ok with either way. I am just thrilled we no longer have the jquery-ui modal there anymore.

**Comment by adad20** [comment]
hi @bradymiller the main purpose why I put btn-danger is this only so that the user don't select it accidentally.

**Comment by im-Amitto** [comment]
UI when using `btn-secondary` for both buttons
Screenshot from 2020-03-31 10-21-32

**Comment by bradymiller** [comment]
hmm, I like the colored buttons in this case. Think it will decrease frequency of users clicking No Thanks.

**Comment by tywrenn** [comment]
@bradymiller The original setup that we had didn't have any color to it that's why I felt like it should be that way. I am planning to add another issue where we (might) change btn colors to more like the way we had them cause BS4's button colors are a bit too sharp

**Comment by bradymiller** [comment]
@tywrenn , will defer to you since you are much better at this stuff (i can't even match my clothing, much less styling pages) :)

**Comment by im-Amitto** [comment]
@tywrenn I also think that BS4 buttons are a little sharp, we can customize them to use a gradient approach.

**Comment by im-Amitto** [comment]
@tywrenn So should I change them to `btn-secondary`?

**Comment by tywrenn** [comment]
@bradymiller it's still your decision though and I don't mind which option you go with

**Comment by adad20** [comment]
Let's vote 😂😂
image

Just kidding,  go for it @bradymiller

**Comment by bradymiller** [comment]
woohooo, I get to decide :)
Lets stick with @tywrenn and go with the btn-secondary
Thanks @tywrenn , @im-Amitto , @stu01509 , and @adad20 for the active discussion. It's these type of discussions that are going to lead the project to a modern style and styling guide!

**Comment by im-Amitto** [comment]
@tywrenn Done :smile:

**Pull request merged**
