### PR TITLE
Refactor: remove oudated javascript attribute

### LINKED ISSUE #3542: Remove outdated tag code.
### Describe the bug

According to this comment https://github.com/openemr/openemr/pull/3497#discussion_r424760810, In our codebase  have a lot of outdated code.

### Expected behavior
Remove and replace it.

Please assign this issue to me.

### PR DESCRIPTION
**Pull request by stu01509**
Fixes #3542

#### Short description of what this resolves:
Remove outdated javascript attributes. e.g. `language='JavaScript'`

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @stu01509 , Looks good and bringing in. Thanks for the improvements! -brady

**Comment by bradymiller** [comment]
I just realized that this is commit number 8000 in to OpenEMR's codebase!!!!

time for a celebration!!!

from the fans:
2DV

from burning elmo:
tenor (4)

from travis:
tenor (5)

and of course from the cat in the bowl:
tenor (29)

**Comment by tywrenn** [comment]
OMGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG

**Comment by tywrenn** [comment]
@bradymiller wait I thought that #3674 was the one

**Comment by bradymiller** [comment]
yep, I messed up :)

**Comment by bradymiller** [comment]
I've made a couple mess ups in PRs tonight. Gotta drink a couple more cups of coffee :)

**Pull request merged**
