### PR TITLE
Final on sql upgrade

### PR DESCRIPTION
**Pull request by sjpadgett**
#### Short description of what this resolves:
This may be all overkill but, I feel better about upgrades!

#### Changes proposed in this pull request:
- add a force flush to immediate display progress messages
- add a server polling pause toggle.
- add no pooling flag

### CODE REVIEW

**Comment by sjpadgett** [comment]
This turned out pretty cool in my humble opinion. Having activity I think will prevent user confusion in long run:
bringing in once travis gives okay
image

**Comment by sjpadgett** [comment]
Check out how now process progress show the current sql activity. this alone will avoid much confusion.
image

**Comment by sjpadgett** [comment]
btw: production run on 4121 patients/6 years of charting ran 1hr 25mins on windows.

**Comment by sjpadgett** [comment]
Is he done or is he not? We all ponder!

**Comment by bradymiller** [comment]
2DV

If not done, I have an idea for the next PR title:
"Grand Finale on sql upgrade, no really, I mean it, this is it, really, I do"

**Comment by bradymiller** [comment]
I'll bring in the global override mech now

**Pull request merged**
