### PR TITLE
Feat: update all theme screenshot

### PR DESCRIPTION
**Pull request by stu01509**
I've been updated all theme screenshot, Please review it.
Untitled

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @stu01509 , From above screenshot, 'Forest Green', 'Mauve', 'Mustard Green', 'Olive', 'Pink' screenshots don't look updated (I can tell because the logo was changed to svg and takes on the color of the theme). As an aside the screenshot of all those is really neat. When all updated, will likely do something with it.

**Comment by bradymiller** [comment]
@stu01509 ,
Actually I think you are good (maybe you had some images cached when you made the screenshot) since the 'Forest Green' image looks fine in your PR. Let me test this.

**Comment by stu01509** [comment]
@bradymiller 
Okay, I've been creating screenshots again, 
If you want to change, I will submit a new commit.

**Comment by bradymiller** [comment]
Testing looks great:
image
 Bringing this PR in now. Thanks for the fix! -brady

**Pull request merged**
