### PR TITLE
secured the mechanism for oauth key pair and encryption key

### PR DESCRIPTION
**Pull request by bradymiller**
1. Encryption key is created when needed and stored in encrypted form in database.
2. Key pair is created when needed with keys stored in filesystem and key passphrase
   stored in encrypted form in database.
3. No access to oath unless api is turned on.

### CODE REVIEW

**Comment by bradymiller** [comment]
@sjpadgett ,

Did some work on securing the key pair and encryption key in this PR. Was hoping you could make sure it works on the entire flow (it should, but as noted below I have not been able to get entire flow to work for me yet).

My main issue at this time is unable to get the authorization code grant to work. When I try, I just get the following returned (note I have this issue without the changes in this PR):
```
{
    "error": "invalid_client",
    "error_description": "Client authentication failed",
    "message": "Client authentication failed"
}
```

The client registration works for me as illustrated in the forum (and oauth_clients row populates well in database):
image

But then when try to send the code grant type request (using the client id obtained from above request), get following:
image

**Comment by bradymiller** [comment]
On some debugging, this line is where the exception is getting thrown:
https://github.com/openemr/openemr/blob/ab217ad05024352251714faf8f5d769e444c2130/src/RestControllers/AuthorizationController.php#L424

**Comment by bradymiller** [comment]
also, here is the exception when output it to the log:
```
League\\OAuth2\\Server\\Exception\\OAuthServerException: Client authentication failed in /var/www/localhost/htdocs/openemr/vendor/league/oauth2-server/src/Exception/OAuthServerException.php:154\n
Stack trace:\n#0 /var/www/localhost/htdocs/openemr/vendor/league/oauth2-server/src/Grant/AbstractGrant.php(221): League\\OAuth2\\Server\\Exception\\OAuthServerException::invalidClient(Object(Nyholm\\Psr7\\ServerRequest))\n
#1 /var/www/localhost/htdocs/openemr/vendor/league/oauth2-server/src/Grant/AuthCodeGrant.php(258): League\\OAuth2\\Server\\Grant\\AbstractGrant->getClientEntityOrFail('T4EGkWW02PsBFQs...', Object(Nyholm\\Psr7\\ServerRequest))\n
#2 /var/www/localhost/htdocs/openemr/vendor/league/oauth2-server/src/AuthorizationServer.php(157): League\\OAuth2\\Server\\Grant\\AuthCodeGrant->validateAuthorizationRequest(Object(Nyholm\\Psr7\\ServerRequest))\n
#3 /var/www/localhost/htdocs/openemr/src/RestControllers/AuthorizationController.php(426): League\\OAuth2\\Server\\AuthorizationServer->validateAuthorizationRequest(Object(Nyholm\\Psr7\\ServerRequest))\n
#4 /var/www/localhost/htdocs/openemr/oauth2/authorize.php(52): OpenEMR\\RestControllers\\AuthorizationController->oauthAuthorizationFlow()\n
#5 {main}
```

**Comment by sjpadgett** [comment]
i don't know. maybe port or using an http instead of https(though doubtful). I upgraded my clinic in plant city to master yesterday so I'll test against that and see.

**Comment by bradymiller** [comment]
may just be related to missing a redirect url if lucky:
https://github.com/thephpleague/oauth2-server/blob/ffbeb6012bacb70a08b8caca156605c2d7ca7dcc/src/Grant/AbstractGrant.php#L219-L221

**Comment by sjpadgett** [comment]
no i missed something in p.r i think because broke on clinic(same as you) and works on my local where I got p.r from.
i'll figure out here in a min...

**Comment by bradymiller** [comment]
it's a race to the bug.
looks like something wrong in getClientEntity not getting the client stuff on the query

**Comment by bradymiller** [comment]
is client_id sql field too short (ie. is it truncating stuff?)

**Comment by sjpadgett** [comment]
I'll look

**Comment by bradymiller** [comment]
hehe, i think that is it since things work better if i use the truncated id stored in the database (i can push a quick fix to deal with that in master; just let me know if you confirm that is issue and then i'll change the varchar(40) to varchar(80))

**Comment by bradymiller** [comment]
also looks like client_secret and registration_access_token are also truncated

**Comment by sjpadgett** [comment]
yep thanks, I adjusted those before pr while doing sql upgrade. forgot i 64 encode ie base64url_encode(\random_bytes(32))
80 should work. for secret I $client_secret = $this->base64url_encode(\random_bytes(64));

**Comment by bradymiller** [comment]
placed fix in master and rebased this PR

**Comment by sjpadgett** [comment]
thanks Brady.

**Comment by sjpadgett** [comment]
Hi @bradymiller 
It looks to me that you only create key pair if not exist, is this true? You prob know that the same public has to be used as generated from private for both access token and dynamic jwk endpoint for client to verify token signatures if they do(they should).

I will bring in if okay so I can test and I want to add the server logout and revoke tokens endpoints.

**Comment by sjpadgett** [comment]
Bringing in so I can verify JWK in my client. Thanks for doing this Dr. Miller....

**Comment by bradymiller** [comment]
hi @sjpadgett ,
Thanks for bringing it in. If the private key is not there, then it will create a new pair (both public/private) in addition to a new passphrase for the private key.

**Comment by sjpadgett** [comment]
Seem to be broken on windows at $keys = openssl_pkey_new returning false. Looking into...

**Comment by bradymiller** [comment]
probably means that windows environment does not have openssl set up

**Comment by sjpadgett** [comment]
The default_md should be sha256 correct?

**Comment by bradymiller** [comment]
that's a good point actually. rather than rely on default of the system (openssl default is now sha256), we should add that setting to the openssl_pkey_new call. Happy to add that setting to master in very near term.

**Comment by sjpadgett** [comment]
okay, prob need to do that. my config was default which is sha1 even though my openssl is latest so I don't know why. I thought default was sha256 but on my xampp not true.

**Comment by sjpadgett** [comment]
Okay, turns out that somehow my JWK generator didn't get in so i'll be making a PR and will add default_md.
Was able to verify token signature via client that is using my generated JWK so, were good.

**Pull request merged**
