### PR TITLE
Minor npm version bumps for dwv and moment

### PR DESCRIPTION
**Pull request by TheToolbox**
This greatly reduces (about 200 fewer 'low' vulnerabilities) the complaints that `npm audit` produces while only touching two dependencies. This change involves minor version bumps for both the `dwv` (0.21.0->0.25.2, [changelog](https://github.com/ivmartel/dwv/releases)) package and `moment` (2.13.0->2.22.2, [changelog](https://github.com/moment/moment/blob/develop/CHANGELOG.md)) package. Any downstream effects should probably be spot-checked, but after checking the changelogs, it's likely there aren't any issues with updating them.

below added by bradymiller:
Up for grabs demo for this PR at:
https://www.open-emr.org/wiki/index.php/Development_Demo#Gamma_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by bradymiller** [comment]
Up for grabs demo for this PR at:
https://www.open-emr.org/wiki/index.php/Development_Demo#Gamma_-_Up_For_Grabs_Demo

**Comment by bradymiller** [comment]
hi,
This will require some road testing.
@kofiav , do you see any obvious issues with trying to upgrade the dwv asset?
-brady

**Comment by kofiav** [comment]
@bradymiller, did some tests and didn't find any issues. Feel free to move ahead with the version bump.

**Comment by bradymiller** [comment]
Thank for this fix @TheToolbox ! and thanks for the testing @kofiav ! Moment also appears to test well on the version bump, so will bring this into codebase.

**Pull request merged**
