### PR TITLE
easy dev dockers on raspberry pi

### LINKED ISSUE #4012: Fix Raspberry Pi Docker Builds
The purpose of this issue is to fix the docker ARM builds to work with Raspberry Pi. Currently they do not work for it which is what I'm planning to fix.

Things Needed To Change To Get It Working:
- [x] Merge in #3892 to help with speed as that is causing a lot of issues
- [x] Change the `phpmyadmin/phpmyadmin` image to just `phpmyadmin` for ARM Docker File
- [x] Disable CouchDB on 32-bit ARM builds as it isn't supported (we might want to create 2 different docker files, one for 32 bit and one for 64 bit)
- [x] Convert from regular node SASS to dart SASS as regular node SASS isn't supported on ARM
- [ ] Fix and/or disable CCDA service

### LINKED ISSUE #4102: Fatal Crash When Editing Patient
### Describe the bug
PID mix-up causes demographics screen to crash when navigating from Billing Manager. @growlingflea found this while working on a different issue.

### To Reproduce

From the billing manager, click the "Patient" button on a row of the billing manager.
Screen Shot 2020-12-15 at 3 47 14 PM
This button sets the active patient and opens the past-encounters/documents and the "edit patient" screen. Click "save" on the newly active patient and there's an error displayed:
`Internal error: Attempt to change patient data with pid = '2' when current pid is '0' for id '2'`
Screen Shot 2020-12-15 at 3 45 25 PM

### Expected behavior

Patient should save as usual.

### Client configuration

- Browser: Firefox
- OpenEMR version: latest master
- Operating system: Mac OS

### PR DESCRIPTION
**Pull request by bradymiller**
fixes #4012 #4014

### CODE REVIEW

**Comment by bradymiller** [comment]
@tywrenn , this build is working on the 32bit raspberry pi. Still gotta test the 64bit raspberry pi.
I am not noting issues with ccda stuff.

**Comment by sunsetsystems** [comment]
Just curious, what would you use for the 64-bit OS? I didn't think that was released yet.

**Comment by bradymiller** [comment]
https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2020-08-24/

**Comment by bradymiller** [comment]
actually @tywrenn   , seeing some issues on 32bit. still work in progress :)

**Comment by bradymiller** [comment]
btw @sunsetsystems , pretty sure that is a beta version for 64 bit

**Comment by bradymiller** [comment]
ok, the 32bit setup is now testing well

**Comment by bradymiller** [comment]
well, that 64bit OS crashed and burned (errored out during startup). So, for now will bring in this PR and will test the 64bit docker-composer.yml when get 64bit working on pi.

**Pull request merged**
