### PR TITLE
Autosave

### PR DESCRIPTION
**Pull request by juggernautsei**
Here is a working implementation of auto save function Draft one

### CODE REVIEW

**Comment by bradymiller** [comment]
Hi Sherwin,
Does Rod's solution get what you needed? If so, can I close this pull request?
thanks,
-brady

**Comment by juggernautsei** [comment]
I will be testing this today and update you on the results. That is why I asked Rod the question.

**Comment by juggernautsei** [comment]
I just reviewed the code and it appears that this would address the issue of the system timing out and loss of work product. While I feel it is not a true auto save it addresses some fundamental issues with auto save and gets the job done. Great work by Rod as always. When I grow up I wana be just like y'all

**Comment by bradymiller** [comment]
Thanks for the reply Sherwin. Gonna close this item then.

**Pull request closed without merging**
