### PR TITLE
Added a docker-compose.yml

### PR DESCRIPTION
**Pull request by bradymiller**
Added a docker-compose.yml to support robust and easy local development/testing

Instructions are in the docker-compose.yml file:
``````
# This is for building a local OpenEMR development and testing environment.
# (Recommend not running it from your git repo and instead mirroring your
#  git repo to a testing directory (such as your web directory).)
#
# How to use:
#   1. docker-compose up -d
#   2. http://localhost:8080 to run setup in openemr (alpine 3.7 with PHP 7.1)
#      or
#      https://localhost:8090 to run setup in openemr with SSL (alpine 3.7 with PHP 7.1)
#      or
#      http://localhost:8081 to run setup in openemr (alpine edge with PHP 7.2)
#      or
#      https://localhost:8091 to run setup in openemr with SSL (alpine edge with PHP 7.2)
#  On the main setup input screen:
#   1. for Server Host, use either 'mysql' or 'mariadb' (have both mysql/mariadb dockers ready to go make testing either one easy)
#   2. for Root Pass, use 'root'
#   3. for User Hostname, use '%'
#  And when need to tear it down and restart it
#   1. docker-compose down -v
#   2. docker-compose up -d
#  Can see databases via:
#   -mariadb via http://localhost:8100
#   -mysql   via http://localhost:8101
``````

TODO for me:
add stuff missing (in https://github.com/openemr/openemr/blob/master/contrib/util/docker/Dockerfile) to the flex docker at https://github.com/openemr/openemr-devops/blob/master/docker/openemr/flex/Dockerfile ; also need to do same to flex-edge docker ), which are:
``````
apk add --no-cache php7-phar nodejs unzip vim nano bash bash-doc bash-completion tree
RUN npm install -g bower
RUN curl -sS https://getcomposer.org/installer | php7 -- --install-dir=/usr/bin --filename=composer
``````

### CODE REVIEW

**Comment by MatthewVita** [comment]
@bradymiller All good except for:

```
# This is for building a local OpenEMR development and testing environment.
# (Recommend not running it from your git repo and instead mirroring your
#  git repo to a testing directory (such as your web directory).)
```

Surely we can make this easier. I don't think git is the answer. Maybe you and I can work a nice little executable script file (bash and bat) to automate some of the git pain away that has come up a few times now. Just thinking out loud.

**Comment by bradymiller** [comment]
hi @MatthewVita ,
If we had a way to do this without the repo getiing bashed by changes, smarty cache, patient docs, and assortment of other disk uploads, then would be great to remove this recommendation. But we don't :)
I generally recommend a degree of separation between a developer's repository and testing code. Here's a script I use related to this:
https://gist.github.com/bradymiller/478814
-brady

**Comment by bradymiller** [comment]
@MatthewVita ,
Regarding the script I linked above, I generally only use it when change branches (ie. need to redo openemr install). Nicely, PHPStorm has a feature where all my edits are mirrored to the testing directory; thus is easy to develop/test my code while working.

**Comment by bradymiller** [comment]
Have updated the flex series dockers to include the development stuff within them, so gonna bring this into the codebase. We can continue to work on a ideal workflow to use docker development environments.

**Pull request merged**
