### PR TITLE
Fix wrong passed variable name

### PR DESCRIPTION
**Pull request by sjpadgett**
oops

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller Quick question. Wht do we need to run code travis compliance checks on all versions of PHP we support?  Why not just PHP 7.1 or 7.2 because if it fails for one it fails for all.

**Comment by bradymiller** [comment]
@sjpadgett , agreed on the styling checks.
@TheToolbox , does it make sense to only have the travis styling check run through one version of php (and keep the syntax checks for all versions of php)?

**Comment by TheToolbox** [comment]
Makes sense to me. After a quick review I don't thiiiiink I see anything in styling that should vary between versions. Is travis taking too long?

**Comment by sjpadgett** [comment]
Seem's so. Plus I think it adds some confusion to some as to what to fix where.

**Comment by bradymiller** [comment]
It significantly increases travis to run these seemingly redundant checks (since PSR2 is not different between PHP versions).

**Pull request merged**
