### PR TITLE
This is so the lbf defaults to the provider that is logged in.

### PR DESCRIPTION
**Pull request by juggernautsei**
This has been a bug for a while. Small fix

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @juggernautsei , This looks very reasonable and bringing this into codebase. Thanks for the fix! -brady

**Comment by juggernautsei** [comment]
Bump??

**Comment by bradymiller** [comment]
hi @juggernautsei , this was merged in in late-2019.

**Comment by juggernautsei** [comment]
My apologies. I am having a moment.

**Pull request merged**
