### PR TITLE
Js fix for fee sheet

### PR DESCRIPTION
**Pull request by eyalvo-matrix**
Hi all,

I noticed that view_model.js file is being loaded in the fee sheet 
and it uses knockout.js and jquery.js
The problem is that both files are not loaded before view_model.js is loaded 
This causes a JavaScript error : ko is undefined 

Thanks 
Eyal

### CODE REVIEW

**Comment by bradymiller** [comment]
I just committed a more straightforward fix for this into the codebase (this makes the includes of standard libraries in interface/forms/fee_sheet/new.php more clear). Tested well over here. Let me know if it works for you and fixes this bug(then i will close this PR):
https://github.com/openemr/openemr/commit/46a98f9b3e7b51e3ee1b04252cda6cf7b683ac3a

**Comment by eyalvo-matrix** [comment]
Thanks 
I will check and will tell you  :)

**Comment by bradymiller** [comment]
Waiting for the good news :)

**Comment by eyalvo-matrix** [comment]
I am not sure if it is related to your fix or not yet
but I noticed that now I only see 1 Past Appointments 
despite the GLOBAL Past Appointment Display Widget is set for 3 
Can you please check if this happens to you too ?

**Comment by bradymiller** [comment]
I am assuming you are talking about the widget on the patient summary screen. I couldn't confirm this bug on the development demo which is using current development codebase: http://www.open-emr.org/wiki/index.php/Development_Demo

It worked fine when set 3. Are you using recurrent appt?
And this code won't affect this issue.

btw, is the fee sheet issue ok with this fix.

-brady

**Comment by eyalvo-matrix** [comment]
Hi 
Yes , I am using the recurrent appt I will try to test it again this week 
After I will make sure we have the latest version of the OpenEMR 

Regarding the fee sheet, indeed it is working fine , thank you for the fix :)

-eyal

**Comment by bradymiller** [comment]
Hi,
The Past Appointments widgets does not support reccurrent appt. Would be nice to get this working for recurrent appt's though.
-brady
cc @epsdky

**Comment by bradymiller** [comment]
Going to close this thread since the the main issue in the fee sheet has been fixed.

**Pull request closed without merging**
