### PR TITLE
add password trusted user

### PR DESCRIPTION
**Pull request by sjpadgett**
#### Short description of what this resolves:
add a trusted user for password. allows for admin revokes and security checks

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller I'm leaving nonce alone for now as for some grants it is required though the OIDC spec for code flow has it optional. For me, we may want to require to prevent replay attacks and session verification with id token.

From everything I gather, it is moreso an industry standard to require clients to use nonce.
I still may before night is over add a signature verification to our war chest:)

Now can we put password to bed?

**Comment by bradymiller** [comment]
good night password!

2DV

**Comment by bradymiller** [comment]
@sjpadgett , Should the password grant request be supporting state and nonce? (on testing I am noting that these are not supported when used in the password grant request)

**Comment by bradymiller** [comment]
btw, Happy Thanksgiving!

tenor (56)

**Comment by sjpadgett** [comment]
No, is simple answer. Did you see a problem?
Happy thanksgiving to you as well...

**Comment by bradymiller** [comment]
nope, no problem (since the nonce is empty in both session cache and id token, it passes the revoked token check). Was just curious. Moving on :)

**Pull request merged**
