### PR TITLE
Portal fixes back port

### PR DESCRIPTION
**Pull request by sjpadgett**
Don't know if this works!

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller lol, well what do 'ya think? Only I, can somehow get into a double revert just to wind up where I wanted to be in the first place.:)
Don't know if I can do this so portal is current in 5.0.1 but, let me know and I can just revert the reverts then go back to bed:)

**Comment by sjpadgett** [comment]
@bradymiller Hey I discovered a working use for stash. Not sure what to do with all this but I feel better it is available for 5.0.1 users.

**Comment by bradymiller** [comment]
hi @sjpadgett ,
This is good place to put this. When I do the next patch, I can then just bring this in.
-brady

**Comment by sjpadgett** [comment]
@bradymiller Okay. We'll leave open and I can keep adding to it. FYI, i'm looking into adding feature to do language text translations to messages in Patient Chat with an eye toward a work flow where users may maintain a chat conference with selective users during a video conference e.q user may carry a private chat with one or more other users during a video conference. Something like, "Hey Brady, what the heck are they talking about" or "Can you believe that tie Joe is wearing?" :)
Seriously though, i'm thinking multi language chat could prove useful toward telemedicine and emergencies.

**Comment by sjpadgett** [comment]
Add fix for LBF options P.R  https://github.com/openemr/openemr/pull/1966

**Comment by sjpadgett** [comment]
port of PR https://github.com/openemr/openemr/pull/2057

**Comment by sjpadgett** [comment]
Added port of https://github.com/openemr/openemr/pull/2068

**Comment by sjpadgett** [comment]
Added port of https://github.com/openemr/openemr/pull/2114

**Comment by sjpadgett** [comment]
@bradymiller Actually several good fixes in this PR and some extra features from v5.0.2 like the addition of portal alert, POS now works as expected and LBF isOption fix(important). If you can't think of anything else, lets go ahead and bring this in but you may have to help out with the patch, or teach me.
Btw: I loaded this branch and tested the main fixes in commits plus these commits are tested in 5.0.2 as well. Not sure where you find the energy to keep up with all these thankless tasks but, I appreciate all your help.

**Comment by sjpadgett** [comment]
@bradymiller Do I rebase my local branch and push or merge and rebase from master?

**Comment by bradymiller** [comment]
hi @sjpadgett ,

Are you able to do a interactive rebase. It would look something like:
```
git rebase -i HEAD~9
```
Then pick the top commit and squash all the others. This will then give you one commit. Then do a force push into this PR branch:
```
git push --force origin portal-backport
```

**Comment by sjpadgett** [comment]
@bradymiller I'm guessing we need to just merge this rebased commit to master then build patch zip for entire rel or do I need to pick a commit to build patch?

**Comment by bradymiller** [comment]
@sjpadgett ,
Still got 3 more commits to squash into 1 :)
```
git rebase -i HEAD~3
```

**Comment by bradymiller** [comment]
Then next step is to go cherry-pick this singular commit into rel-501 branch, along with the other 2 commits:
```
d85a1449c93a32ac1e3a1798bd78a39ce3928d94 (QRDA reporting fixes for php 7.1 - fixed by Brady Miller)
057382026c520d9cedd99b6c8acfeb0b6a3efabc (rxnorm fix - reported by Craig Sparks, fixed by Stephen Waite)
```
(if you get a merge conflict, then abort from the cherry-pick and will postpone it until next patch)
Then you should have 3 commits in rel-501. Then to make patch:
1. create an empty directory outsite openemr
2. unzip most recent patch (#6) in it
3. then go through each commit with following command:
```
git show --pretty="" --name-only 8e0d86a
```
(use the hash of the commin in place of 8e0d86a)

Now things get fun; you basically will manually copy each file listed from the rel-501 branch (with your new commits in it) into the patch directory; you need to be super anal on this (ie. triple check) or things will come tumbling down on the patch release :) )

Then ensure always bring over:
version.php
sql_patch.php

And then ensure all following files are blank files in the patch:
setup.php
portal/sign/assets/flashcanvas.js
portal/sign/assets/flashcanvas.swf

then build the patch:
zip -r 5-0-1-Patch-7.zip .

**Comment by sjpadgett** [comment]
Okay. No explaining needed but is there a reason you don't use git archive? yes or no works for me 'cause my puny brain is refusing to retain non essential info any longer:)

**Comment by bradymiller** [comment]
hi @sjpadgett , Never tried git archive. Just quickly looked at it and looks like it will copy entire codebase.

**Comment by sjpadgett** [comment]
> Still got 3 more commits to squash into 1 :)

This will result in an empty commit for the two reverts essentially rolling that empty into the top pick. This is okay right? also believe archive allows to pick commits to archive. I'm looking at that.

**Comment by sjpadgett** [comment]
@bradymiller This is pretty cool
` git archive -o ../test/portal_branch.zip  HEAD $(git diff --name-only HEAD^)`
or could be a list of commits etc. Anything then copy files one by one.
Also the commits you want me to rebase were part of previous rebase but where left behind as they cancel each other. either I leave in tree or delete. I just want this done so I can move on.

**Comment by bradymiller** [comment]
sorry @sjpadgett , I just saw your above post. Could just rebase them all into 1 commit, or do a git reset --hard to delete the empty commit or just leave them, since we'll just need to cherry-pick the commit with stuff in it. I'll look into the archive thing and see what we can do to expedite the next patch :)
-brady

**Comment by sjpadgett** [comment]
@bradymiller I accidentally reverted my original commit so I reverted the revert thus the smile:) When I rebased, the two reverts were left behind and now won't let me rebase them into the new rebased commit.
I will go ahead and cherry pick the rebased commit with the other two and leave the two reverts as is.

**Comment by bradymiller** [comment]
Sounds good. Bring them into rel-501 branch and then we can work on making the patch.

**Comment by sjpadgett** [comment]
Hi @bradymiller , i'm going to try and get this done. I'm pretty sure that I can't get into too much trouble but, hopefully, Murphy is busy elsewhere. :) I think I figured out how to use archive for this and makes the zip much easier to build (can't even imagine how the boys at git dev do this stuff).
I also need to say that after trying to keep up with this admin stuff and code reviews, this community owes you a thank you. So, from me, thank you.

**Comment by sjpadgett** [comment]
> Then next step is to go cherry-pick this singular commit into rel-501 branch, along with the other 2 commits:

I get the cherry pick of merged commits from 502 but having trouble understanding why you want me to cherry pick my portal-backport rebased commit to rel-501 branch. Why can't I just merge my branch? if I do cherry pick portal branch to 501-rel, what happens to my commit pending to be merged into master. Also if I do cherry pick all of them should/can I do from local 501-rel then have to push or do it from upstream

**Pull request merged**
