### PR TITLE
fix: minor prior auth bugs and some php8 warns in graphs

### LINKED ISSUE #6129: bug: prior auth module fatal error on create table
### Describe the bug
Screenshot from 2023-01-22 16-47-45

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #6129

### CODE REVIEW

**Comment by stephenwaite** [comment]
hi @juggernautsei, it looks there might be a missing table.

Screenshot from 2023-01-31 21-41-54

**Comment by juggernautsei** [comment]
Thanks @stephenwaite

**Comment by stephenwaite** [comment]
hi @juggernautsei, also looks like some formatting issue in the display:

Screenshot from 2023-01-31 21-08-48

**Comment by juggernautsei** [comment]
@stephenwaite  This is what mine looks like

image

**Comment by stephenwaite** [comment]
thanks @juggernautsei , it's not displaying properly in master on the easy dev docker.

**Comment by juggernautsei** [comment]
I addressed the issue. I don't have permission to push to this repo. I have merged the code with what I have from this repo. 
Here is the updated file that is working on my v7 installation. Lines 151-174 were not right when I did the diff.
https://github.com/juggernautsei/MedBoss_v7/tree/main/interface/modules/custom_modules/oe-module-prior-authorizations/public
image

**Comment by stephenwaite** [comment]
testing well and bringing in, thanks @juggernautsei

**Comment by juggernautsei** [comment]
it is not an unrelated feature. The clinic this was built for asked to have the ability to mark a patient as active or inactive. I seem to have forgotten to add the table to the module table file.

**Comment by stephenwaite** [comment]
just mean it's unrelated to prior auth and should have it's own PR

**Comment by juggernautsei** [comment]
Understood.

**Comment by bradymiller** [comment]
2DV(1)

**Pull request merged**
