### PR TITLE
Change deprecated 'each' functions to 'foreach'

### PR DESCRIPTION
**Pull request by clairenoelle**
Only did a few to make sure I'm doing them correctly. Will do more if this works :)

### CODE REVIEW

**Comment by bradymiller** [comment]
These each to foreach conversions always give me a bit of a headache, but need to be done. Anybody out there want to become an expert on this and review/test this code? :)

**Comment by bradymiller** [comment]
bump

**Comment by bradymiller** [comment]
double bump

**Comment by bradymiller** [comment]
bump

**Comment by stephenwaite** [comment]
bump, will have a PR soon that fixes these in edihistory

**Pull request closed without merging**
