### PR TITLE
Update oeHttp client to authorization code grant type.(phase 1)

### LINKED ISSUE #4043: Update Publish Provider Client
### Describe the problem

Publish is behind current APIs and authentication.

### Describe the solution you'd like
- Will need to update client to support OIDC authorization grant type and/or resource grant.
- This will allow queries to both outside and our APIs and server though, for FHIR only.

If someone wants to help here, please.....

### PR DESCRIPTION
**Pull request by sjpadgett**
- OIDC started
- auto refresh
- lacks state persist in client
- lacks nonce
- lacks code challenge

Fixes #4043

#### Short description of what this resolves:
Start of updating oeHttp client to support OIDC,OA2 then SMART
Mainly for the Publish Provider Client however, classes could be pulled out and included in a separate client project.

### CODE REVIEW

**Comment by sjpadgett** [comment]
For the Publish client(which is main feature this will support), i'm only going to take as far as example of how to use oeHttp client classes for authentication/grant flows and add a FHIR Patient resource read and put to our local APIs and same for an external HAPI public server.
Going to start a documentation thread on forum to companion this PR with the hopes some folks may want to use in their clients and help mature the feature. I promise once it's shown how it works, it is very easy to use.

**Comment by sjpadgett** [comment]
@bradymiller 
There is just way too much to do to make the Publish useful and as it stands now it is only good for a testing jig.
The main good thing is I got the oeHttp client updated so it can be used for OIDC logins which I'll end up using for ONC HIE type transactions instead of SOAP or other such nonsense.

I'll try to document the client better so perhaps others may find it useful however, because Publish does not serve a purpose as of yet, i'm going to pull it from v6.0.0.

I really would like to see an ability for users to have a core client to query patient records from other FHIR servers but this needs to wait and my time is better spent getting ready for ONC.

Plan: Will bring in this updated oeHttp client PR then open a separate PR to pull the Publish provider client from Demographics, Globals and directory tree(phpfhir).

I'm working a HIE client UI for passing CCDA which is already integrated with my ccda service that i'll bring in later. It uses the oeHttp client.

Sooo comments!
@dixonwhitmire Guessing you're no longer interested in client?

**Comment by bradymiller** [comment]
@sjpadgett , Plan sounds great to me. We can always bring back in the publish feature (via a commit revert) in future is somebody (such as @dixonwhitmire ) wants to take it on.

**Comment by sjpadgett** [comment]
For posterity sake. This hurts a little:)
image
image
image

**Comment by dixonwhitmire** [comment]
@sjpadgett @bradymiller Hi Folks. Thanks for checking in. That's correct, at this point in time I don't have the "spare cycles" to take on client development. Thanks!

**Pull request merged**
