### PR TITLE
More complete support for activity flag in list_options table.

### PR DESCRIPTION
**Pull request by sunsetsystems**
A while back the "activity" column was added to the list_options table so that list items can be marked inactive.  However most code that reads lists was left unchanged so the feature was incomplete.  This commit fixes code that should skip inactive list items.

### CODE REVIEW

**Comment by bradymiller** [comment]
Quick question. The current implementation of an active element is a bit flexible. For example, if a user has already selected an item that has then been made inactive, the mapping will not be lost. Will the current changes maintain this or will the mappings be lost?
https://github.com/openemr/openemr/blob/master/library/options.inc.php#L185

**Comment by sunsetsystems** [comment]
Hi Brady, I thought about that and it seemed like confusion would result if making an item inactive behaved any differently from deleting it.  But that raises the question, what was the original motivation for creating the feature?  For us it was to be able to try out changes that might need to be reverted, or to keep a record of deviations from a "standard" list.

**Comment by sunsetsystems** [comment]
And... I found a bunch more modules that need changing for this.  There will be another commit for those.

**Comment by bradymiller** [comment]
Hi Rod. Agree with your logic. I think the list flexibility was biased (in my brain) by the backup list work that was done.

**Comment by sunsetsystems** [comment]
Now I see the Care Coordination code is doing stuff with the activity flag.  Guess I better not mess with that.  Do you have any idea what that's about?

**Comment by bradymiller** [comment]
Hi,
The activity flag was basically added because ZH added some large lists (such as ethnicity as I recall) where it only made sense to make several of them active, but allow activating more if needed by the practice. Your logic described above shouldn't break anything in the care coordination module. I also don't know why we made it activity rather than active (probably did not drink enough coffee during that code review :) ).

**Comment by sunsetsystems** [comment]
Added a commit for the additional modules that I think needed attention.  I did not touch anything under modules/zend_modules or forms/eye_mag or super/rules because it looked like the authors had already considered the activity flag for those.

Would appreciate some more eyeballs on this in case there's anything I'm missing.

**Comment by bradymiller** [comment]
Hi @sunsetsystems 
The changes all look good to me (I didn't test it).

**Pull request merged**
