### PR TITLE
bug fix for note save return after fancybox replace.

### PR DESCRIPTION
**Pull request by sjpadgett**
@bradymiller Example of replace a form target with ajax promise using dialog callback for refresh.

### CODE REVIEW

**Comment by sjpadgett** [comment]
Also note you can give dlgclose(function, arguments) simple arguments to pass to callback function call like 'encounterid, pid'  or pid e.t.c. Maybe one of our javascript guru's could help create a defer'ed action for the dlgopen lib...

**Comment by sjpadgett** [comment]
@stephenwaite Here is your dialog spruce up.:) Also added the new facility taxonomy to the facility new add unless you only wanted user to edit. Let me know and i'll remove.
@bradymiller Think i'll add one more fancy replace to this PR unless you want them in separate PR's.

**Comment by bradymiller** [comment]
hi @sjpadgett , thanks! Regarding PR's is up to you :) -brady

**Comment by stephenwaite** [comment]
great! thanks @sjpadgett , whoops on the facility_add

**Comment by sjpadgett** [comment]
@stephenwaite no worries, trust me, i've missed a few this week. example! :) @sharonco-matrix Dialog in frames was using the wrong window to calculate size when a dialog is stacked causing full height always. Also I fixed left nav to style correctly in IE11.
Bringing in after travis.

**Pull request merged**
