### PR TITLE
Namespacing the Checker class to meet PSR-4

### PR DESCRIPTION
**Pull request by robertdown**

### CODE REVIEW

**Comment by MatthewVita** [comment]
Hi @robertdown, please see the comment I put in the class:

> // No namespace here because this class is mostly required outside of the
> // OpenEMR context.

I'm at work so I just took a quick glance at your PR here, but I'm not sure this will work. Can you verify?

**Comment by robertdown** [comment]
We should still namespace any custom code, not just because it's part of `PSR-4` but just because it's good practice. There's no reason this won't work

**Comment by MatthewVita** [comment]
My concern is that this is outside of the OpenEMR "context" in terms of not being autoloaded.

**Comment by robertdown** [comment]
It doesn't have to be, because you're `require_once`'ing it, PHP recognizes the namespace. Instead of autoloading you're requiring, the result is the same

**Comment by robertdown** [comment]
If you dig very deep into how autoloading works (at least in Composer) you'll find an actual `require` command :)

**Pull request merged**
