### PR TITLE
minor bug fixes in weno code

### PR DESCRIPTION
**Pull request by bradymiller**
hi @juggernautsei ,

I'm just doing some minor security hardening the codebase and this shouldn't change the weno featureset.

One question I have is that the following scripts are not called anywhere:
drug-drug.php
formularyUpdate.php
formularyInsert.php
import_pharmacies.php
RxLog.php

Is that because these scripts are not used?

thanks,
-brady

### CODE REVIEW

**Comment by bradymiller** [comment]
TEsting well and bringing this in.
@juggernautsei , just let me know (when you have time) regarding the files above. thanks! -brady

**Comment by juggernautsei** [comment]
These all were left behind in the wake of getting the module launched.

Do you need an explanation for each file?

**Comment by bradymiller** [comment]
hi @juggernautsei ,

No explanations needed. I just need to know whether you want to keep them in the codebase or not :)
(I am removing unused scripts as part of the security code walk through)

thanks,
-brady

**Comment by sjpadgett** [comment]
Haven't looked since I worked on prior to credential changes but, I recall working on the pharmacy import along with drug import.

**Comment by juggernautsei** [comment]
The pharmacy import has gone through some iterations since we began. Most
people don't use it. I reviewed the list, and there is nothing essential as
you pointed out.
The Rx.log, drug-drug, and formularies can be removed. Keep the rest.

**Comment by sjpadgett** [comment]
"Most people don't use it." Oh well, at least it's pretty:)

**Comment by bradymiller** [comment]
@juggernautsei and @sjpadgett ,

Thanks for the pointers. I finished up the clean up of weno here, which tested well:
https://github.com/openemr/openemr/pull/2000

-brady

**Pull request merged**
