### PR TITLE
Issue Fix #2989: Form label field alignment issue

### LINKED ISSUE #2989: UI Issue: Message Center add new form table
### Describe the bug

Message Center add new form table, The table field didn't alignment each one, And Button color may create identification problems.

I will fix this issue, Please assign me.

### To Reproduce

1. Click Message
2. Click Add New Button
3. See Add form

Untitled

### Client configuration

- Browser: Google Chrome 79.0.3945.130 (Official Build) (64-bit)
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by stu01509**
Fixed Issue: #2989
Fixed form label field alignment issue, and Improve button style.
Untitled

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @tywrenn ,
Can you check this PR out regarding the use of different classes impacting coloring; just want to make sure consistent with work you have done or if there is a better way to do this while continuing to support light/dark/superhero/color themes. thanks, -brady

**Comment by stu01509** [comment]
Hi @bradymiller  @tywrenn, 

If have any change request, Please let me know.
I just think some buttons color look like confused.

**Comment by tywrenn** [comment]
@bradymiller This gets my seal of approval

**Comment by bradymiller** [comment]
thanks @tywrenn !
@stu01509 , bringing this into codebase. thanks for the code improvements! -brady

**Comment by stu01509** [comment]
Hi @tywrenn,

If I want to modify UI style, I just follow the BS4 style, Am I right?

**Comment by tywrenn** [comment]
@stu01509 yep 👍

**Pull request merged**
