### PR TITLE
Fix - In the Add New Issue / Edit Issue window the Title list box is …

### PR DESCRIPTION
**Pull request by epsdky**
In the Add New Issue / Edit Issue window the Title list box is populated with list IDs instead of list Titles (which are not translated).

### CODE REVIEW

**Comment by epsdky** [comment]
Not sure that it is necessary to translate the Issues list Titles since they are entered locally...

**Comment by sunsetsystems** [comment]
Translation seems right because a single site can have users who speak different languages.  This does happen.  Note this translation is an option in global settings.

**Comment by bradymiller** [comment]
The general translation of the list titles is very nice for clinics that support multiple languages.

This example is a special case where it's not all that helpful, though, since the title gets stored in the database anyways(if a dutch user selects the dutch translation of diabetes, the dutch translation is what goes into the database). Especially since we don't translate these titles elsewhere in OpenEMR.

In the end, though, not worth breaking the current "standard" of translating list items if the translate_lists global is turned on, of which this is a bug fix to that behavior. So, will bring in this fix.

It may make sense to have another global translate_list_issues that only covers the translation of the issues titles here and in the Lists editor for the pertinent lists(note that when working in non-english languages the translation of the title is shown in the Lists editor when translate_list is on).

**Comment by sunsetsystems** [comment]
Yeah... I would not make another global setting just for this.  True that the issue title selected will be stored as if it were free text (which is also an option), and thus not translated after that.

**Pull request merged**
