### PR TITLE
update cert/key management script to be future proof

### PR DESCRIPTION
**Pull request by bradymiller**
related to this:
https://community.open-emr.org/t/proposal-to-remove-administration-system-certificates-script/14888

### CODE REVIEW

**Comment by sjpadgett** [comment]
Somewhere on the forum or issues I did a mod for a OSX user for creating/importing clients. I gave options on cert create. It was pretty nice but i've lost the source.

**Comment by stephenwaite** [comment]
https://community.open-emr.org/t/client-certificat-install-on-safari/14328/24

**Comment by bradymiller** [comment]
Added devtools to make testing this stuff much easier to do:
https://github.com/openemr/openemr-devops/commit/9d0788b72d2435866cfaf59216cf81873fdf41c7

**Comment by bradymiller** [comment]
testing well so far. likely bringing into codebase tomorrow after some more testing.

**Comment by bradymiller** [comment]
btw @sjpadgett , also incorporated your passphrase stuff.

**Pull request merged**
