### PR TITLE
weno drug sql import fails window

### PR DESCRIPTION
**Pull request by sjpadgett**
- best to parse for all eol's

### CODE REVIEW

**Comment by sjpadgett** [comment]
will leave open till couple production tests

**Comment by bradymiller** [comment]
code looks good to me :)

**Comment by sjpadgett** [comment]
Something up with escaping on transmit. can't tell if it's decrypt password. getting like ...CH6J with start double quote missing... weird. Also couple other things so....

**Comment by bradymiller** [comment]
Does this happen when try to:
1. Bring in the weno drug table during upgrade?
2. Bring in the weno drug table on new install at Administration->Other->Weno Management->Import Formularies?

**Comment by sjpadgett** [comment]
No, i've fix import i'm working on transmitting requests to weno. All the json build looks good up to the ajax post where somehow account password gets corrupted because array escaping is corrupted. So not decrypt it's just weird.
@juggernautsei How about checking weno server for my account(cofpc) and let me know what the message looks like. Weno is returning 
`Weno Exchange LLC|2019-06-06|02:21:42.96557Z|900|Transaction rejected - invalid message|.xml`

**Comment by sjpadgett** [comment]
@juggernautsei there something wrong with either the request object structure being sent or weno changed.
You need to let me know why weno is erroring. The request is url encoded and doesn't look like weno wants json so what is the spec?
Also, this could not have worked (drug_ids were wrong) so do you have this working somewhere

**Comment by bradymiller** [comment]
@sjpadgett  ,
I just brought in a minor related fix into the codebase (more details in the PR):
https://github.com/openemr/openemr/pull/2470

**Comment by bradymiller** [comment]
oops, here is the right PR for above:
https://github.com/openemr/openemr/pull/2471

**Comment by juggernautsei** [comment]
Jerry,
There is a problem with my server generating the message ID's. I am working on that now but what is up with the decrypt on the Weno account password?

**Comment by sjpadgett** [comment]
Decrypt is okay. I not sure why ajax encoding was breaking the request message at the beginning of password. Working now so may be a fluke with browser but worth keep an eye on.
Also any reason weno doesn't use json for requests because this is working as if using a post in lieu of a get request(urlencode instead of json body)?

Anyway i'll leave this open till you let me know to send a prescription.

**Comment by juggernautsei** [comment]
Weno uses WSDL. In short, OEMR is creating a JSON to transmit to the intermediate server that takes that JSON and converts it to XML which is then transmitted to Weno. 
https://apa.openmedpractice.com/apa/interface/weno/success/newRx_out_29911726929124.xml
This is the final result being transmitted to Weno who sends the message to the pharmacy. The return message is collected and sent via ajax return to the starting point.  One of the things I added was a way to track the message by the return error message. 

If someone gets an error message like this:
       Weno Exchange LLC|2019-06-06|16:44:33.66269Z|900|Transaction rejected - invalid message|29911726929124.xml
They should be able to give me that message ID number in front of the .xml so I can plug it into the browser and locate the message. Like in the link above.  
Then that XML can be plugged into the message validator to see what is wrong with the message. 
https://live.wenoexchange.com/Validator/ValidateSchema.aspx.
One day we will be able to link all of this together.  Hope this helps.

**Comment by sjpadgett** [comment]
Okay thanks. I'm just trying to understand if you're going to ship json you'd think the request would be a json content type and not urlencode content type. But if it works, it works.
Just let me know so I can bring in the PR then get back to fishing:)

**Comment by sjpadgett** [comment]
@juggernautsei are you looking into fix on weno side for the Weno Exchange LLC|2019-06-06|02:21:42.96557Z|900|Transaction rejected - invalid message|.xml i'm still getting at clinic.

**Comment by juggernautsei** [comment]
You should not be getting that now. I have seen new messages go through today.
Message 3904 at the very end of the list is the latest message that went through.
image

**Pull request merged**
