### PR TITLE
New dictation 2

### PR DESCRIPTION
**Pull request by juggernautsei**
As requested to add text colors and sizing and fix the spacing.

### CODE REVIEW

**Comment by bradymiller** [comment]
TODO for me:
bring in "full" version of ckeditor via bower (rather than directly touching stuff in public/assets dir )

**Comment by bradymiller** [comment]
from prior PR:
https://github.com/openemr/openemr/pull/879

**Comment by juggernautsei** [comment]
I think I should explain. The "full menu" is not something you download. It is a configuration file that is created. I did a diff between the standard/sample config and "full" and the only files that were changed/added are the two you see uploaded the config.js and the build-config.js.

**Comment by bradymiller** [comment]
this doesn't work. i get the following js error:
TypeError: d is undefined

I'm gonna work on this a bit by bringing in the full version and then creating a external config that we can then modify.

**Comment by juggernautsei** [comment]
I guess I will study up on how to work the composer. I have it installed on my server but I need to learn the proper way to access it and use it.

**Comment by bradymiller** [comment]
btw, the assets are done using bower :)
(I'm glad to do this stuff while you keep on adding all these nice new feature)

**Comment by juggernautsei** [comment]
Brady,
I updated my repository and noticed that CKEditor was in the assets folder. So, I removed my current working version and loaded the new code base to my working environment. I worked for three hours trying to get CKEditor working. I finally checked the repository to see if the sample was working. It was not. I downloaded a fresh copy of CKEditor full and replaced the one in the code base. Then it popped right up. I am not sure how you brought in the CKEditor into the codebase. But it is broken and missing lots of stuff. 
I'm uploading what I have working now to this PR.

**Comment by bradymiller** [comment]
@juggernautsei ,

Placed next iteration here:
https://github.com/openemr/openemr/pull/893

I'll place more details regarding in that PR.

**Pull request closed without merging**
