### PR TITLE
Applied new dynamic code picker to most remaining places that can use…

### PR DESCRIPTION
**Pull request by sunsetsystems**
… it.

More porting from client work. :)

(below added by bradymiller)
demo is here:
http://www.open-emr.org/wiki/index.php/Development_Demo#Epsilon_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by stephenwaite** [comment]
pretty cool how you took this on this afternoon

so you found all locations of find_code_popup and switched it out for the dynamic version...

i'll have to study the ???_related functions to see if i can make sense of what you're doing there, thanks Rod

**Comment by sunsetsystems** [comment]
This is something I did a while back for a client, just needed to port it.
Best thing you can do is testing.

**Comment by bradymiller** [comment]
Set up a Up For Grabs demo for this here:
http://www.open-emr.org/wiki/index.php/Development_Demo#Epsilon_-_Up_For_Grabs_Demo

**Comment by stephenwaite** [comment]
thanks @bradymiller it's testing well so far, prob next thing to do is turn off ICD9 as default :)

**Comment by sunsetsystems** [comment]
I guess ICD9 should be made inactive by default for new installations?

**Comment by bradymiller** [comment]
@sunsetsystems ,

As I recall, there is a mechanism (via a global), to select the default code type here(looks like was done for fee sheet, but could also do in this case to avoid selecting icd9):
http://www.open-emr.org/wiki/index.php/Administration_Globals#Default_Search_Code_Type

Also, if a user selects a code in the gui by mistake, then how do they unselect it?

-brady

**Comment by bradymiller** [comment]
Also, for new installations, could turn off ICD9 in administration->Lists->Code Types settings . Seems reasonable to do this on new installs(database.sql). I wouldn't carry this over to the sql upgrade script since may break mapping of ICD9 codes to descriptions in older installs (that still have ICD9 being used in "legacy" patient encounters).

**Comment by sunsetsystems** [comment]
Merged this in. ICD9 can wait for another day. :)

**Comment by stephenwaite** [comment]
just kidding :)

**Pull request merged**
