### PR TITLE
Snomed rf2 - complete it already...

### PR DESCRIPTION
**Pull request by bradymiller**
RF2 support for SNOMED

references:
https://github.com/openemr/openemr/issues/410
https://github.com/openemr/openemr/pull/720

### CODE REVIEW

**Comment by bradymiller** [comment]
Testing well and will bring in after pass travis.
This support RF2 format for SNOMED (supports US Versions, International English version, and International Spanish version).
Thank you @robertogagliotta for this awesome feature! and sorry it took me so long to get it into the codebase. -brady

**Comment by robertogagliotta** [comment]
Thanks to you Brady, it RF2 was a good skill to learn.

**Comment by adunsulag** [comment]
@bradymiller How relevant / applicable are the tests in tests/unit/code_types/ since there is a bunch of snomed_code lookups there but it looks like nothing there was updated as part of this PR.

**Comment by bradymiller** [comment]
hi @adunsulag ,
Those should still work (the snomed changes won't impact this). That being said, wonder if it makes sense to remove those testing scripts since those were done a long time ago via a "legacy-type" testing method and are never used.

**Comment by adunsulag** [comment]
So I've spent many hours trying to get the snomed tests to work inside the testing framework.  They rely on a lot of globals, database insertions, etc that don't work for the unit testing framework.  I'm going to go ahead and remove them as part of my unit test updates.

**Comment by bradymiller** [comment]
Agreed on removal :)

**Pull request merged**
