### PR TITLE
Moved phpmyadmin to vendor, basic composer setup

### PR DESCRIPTION
**Pull request by robertdown**

### CODE REVIEW

**Comment by bradymiller** [comment]
Hi Robert,

If only phpmyadmin integration were that simple :)

Check out the following wiki page for specifics on integrating phpmyadmin into OpenEMR:
http://www.open-emr.org/wiki/index.php/PhpMyAdmin

I am guessing that the requirement to modify the phpmyadmin scripts will remove this from the vendor directory.

Excited to see work on getting composer into the codebase, though. Advice for now:
1. Simply do a commit to bring in the composer pieces separately.
2. Avoid whitespace changes in your commits (unless the commit is only to fix the whitespaces).

-brady

**Comment by bradymiller** [comment]
Actually, disregard the whitespacing removal issue above. It is ok to fix trailing whitespace when doing other work (easy to have github not show these).

**Comment by robertdown** [comment]
Because editorconfig is set to trim the white space, we may see some commits with mixed case. Hopefully it's minor as those files with trailing ws get weeded out



On Thu, Jul 7, 2016 at 1:44 AM -0400, "Brady Miller" <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually, disregard the whitespacing removal issue above. It is ok to fix trailing whitespace when doing other work (easy to have github not show these).

-

**Comment by bradymiller** [comment]
Hi Robert,
This will be worth it. Note can have github ignore whitespacing changes when reviewing the code, so not an issue.
-brady

**Comment by Wakie87** [comment]
@bradymiller from what I can see the only file that is changed to enable openemr is the config.inc.php. Eventually using composer we can extend it to run a script either after install or after autoload-dump to create the config.inc.php file in the vendor directory.

[https://getcomposer.org/doc/articles/scripts.md](https://getcomposer.org/doc/articles/scripts.md)

**Comment by bradymiller** [comment]
I'm new to composer, but I assumed that this vendor directory would hold unmodified packages/libraries. Is this an incorrect assumption?

**Comment by Wakie87** [comment]
No you are right, What we should actually be doing, and we can do it with phpgacl as well is create a new repository on github/sourceforge that pulls in the latest PHPmyadmin and merge our added file as well. Then in our composer.php file we call it from our own project.

[https://getcomposer.org/doc/05-repositories.md#vcs](https://getcomposer.org/doc/05-repositories.md#vcs)

**Comment by robertdown** [comment]
Couple of things we can do here. Normally with composer, you don't actually commit anything inside of `vendor` to git. The developer would have to run `composer install` to grab the vendor files. This is good practice as it keeps the overhead of the repo down and keeps 3rd party packages out of the project until needed. For a release, you could run `composer install` prior to doing your release work (zipping, etc.)

However, I have a feeling that idea won't fly and since we are already embedding libraries, we go ahead an put the actual files inside of `vendor`. This means we could get away with minor changes like this (though I don't think we should get in the habit of it).

The alternative would be to fork phpMyAdmin and add that 1 file and then tell composer to use our fork instead of upstream. This is trivial and easy and could be done very quickly.

Either way is fine by me--so long as phpmyadmin ends up under `vendor/` :)
(Also, this commit already adds config.inc.php)

**Comment by bradymiller** [comment]
Hi,

Recommend keeping it simple and placing the package in the openemr repo (then gets ongoing testing without needing to do a "build").

For phpmyadmin, agree with using composer and placing it in vendor (this will also make it easier t) upgrade phpmyadmin the future).

To make it clear, should break this down into following commits:
1. Pieces for composer. For this 1 create a global such as 'vendor_path_absolute' in globals below the assets_path global, thus will use this in code for paths of stuff in vendor (this will allow us to move/rename the vendor directory in the future if needed)
2. Bring in phpmyadmin (and remove the old one) and change path to link in left_nav (using the global from step 1). 
3. Place the phpmyadmin config.inc.php file

(if you do step 1, I would be glad to do steps 2-3)

-brady

**Comment by Wakie87** [comment]
Hi @bradymiller 

I think the best way is to create a fork of phpmyadmin under the openemr organisation and add the config.inc.php file into the openemr/phpmyadmin repository. Then from there we can create the composer file to pull in "our" version of phpmyadmin. 

Composer best practices say you shouldn't commit the dependencies in the vendor folder.
[https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md](https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md )

**Comment by robertdown** [comment]
I think forking the phpmyadmin is also the better way to go, it's cleaner. I don't have access to publish to the openemr account on Github so @bradymiller will either have to give me enough access to create the repo (but not touch the openemr repo) or just create it himself. I don't mind doing it, just need access

I know Composer best practices say not to commit vendor, but I have a feeling older devs will balk at this (even though it's a widely adopted principle in dev workflows. My preference is to *not* put the contents of `vendor` under VCS. For developers, it's just `git clone ...` and then just `php composer.phar install` and boom, it gets everything. As the developer actually implementing this, I'd like to think my opinion carries a bit of weight.

**Comment by Wakie87** [comment]
Yes +1 to @robertdown comment. 
Maybe when we release a new version we provide an additional zip that has all the vendor components installed?

**Comment by robertdown** [comment]
I assume Brady does the relasing. You only have to run 'composer install' once (or if we upgrade vendor packages. If Brady has a working copy, he can just zip everything up. The only thing that changes is the composer install, which would have happened way before a release, since we'd be testing already. I really think the pros outweigh the cons on this one

**Comment by olegsv** [comment]
@bradymiller  if we can publish OpenEMR  installation files in zip and tgz format including vendors directory contents, then we can avoid storing contents of vendor/ in our github. We just bring them while building a version zip archive.

**Comment by bradymiller** [comment]
As with bower and the front-end assets, propose baby steps. This will at least be much simpler since there will only be 1 version of each package...

Recommend starting with placing plan on the wiki page:
http://www.open-emr.org/wiki/index.php/Composer

For an example, see the bower page:
http://www.open-emr.org/wiki/index.php/Bower

I see no reason to rock OpenEMR's world with separate repos and forced developer composer education at this early in the game. When implementing something, should also think of the downstream effect. For example, resources to:
1. convert githib openemr project to an organization
2. convert demo farm to build package
3. convert package builder script to build package
4. testing of packages will likelyl entirely fall on the person making the release
5. requires all developers(newbie, experienced, young, old) to use composer to have a working package. Thus need documentation for developers.
6. testers with minimal development experience whom test the master codebase frequently (ie. for example Arnab) will need to use composer to have a working package. Thus need documentation for non-developers.

Why not first just get composer in and start migrating packages to it (while tracking this on the wiki page). Then could always decide to go the build route in the future with very small amount of work, which would just involve deleting files and adding a phpmyadmin repo (ie why are we making this decision now?).

If still wish to push for this so early in the game, then recommend discussing it on the forums.

-brady

**Comment by bradymiller** [comment]
btw,
Don't mean to come off as being cranky :)
(and the conversion of the openemr github account to an organization is at the top of my normal priority queue, which may be several months :) )
-brady

**Comment by bradymiller** [comment]
@Wakie87 
@robertdown 

Now that we have an organization, does it make sense to proceed with:

> I think the best way is to create a fork of phpmyadmin under the openemr organisation and add the config.inc.php file into the openemr/phpmyadmin repository. Then from there we can create the composer file to pull in "our" version of phpmyadmin.

**Comment by robertdown** [comment]
Oh please yes!

**Comment by robertdown** [comment]
Pulling this PR as it's stale and hopefully we'll be removing phpmyadmin all together in the near future

**Comment by MatthewVita** [comment]
@robertdown what's the rationale for removing PMA? Just curious.

**Comment by robertdown** [comment]
It's 3rd party software that doesn't solve a specific business function inside OpenEMR. Having it embedded is a security risk and just bad practice (think separation of function)

**Pull request closed without merging**
