### PR TITLE
Various Billing Fixes

### PR DESCRIPTION
**Pull request by sjpadgett**
First in a series of billing fixes.

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @sjpadgett ,
You want me to leave this PR open for more fixes or bring in this fix now?
-brady

**Comment by sjpadgett** [comment]
Yep leave open, I have one more tonight then couple more tomorrow plus Stephen and I are going to fix 837P here.

**Comment by stephenwaite** [comment]
[2017-08-31-1327-batch.txt](https://github.com/openemr/openemr/files/1281712/2017-08-31-1327-batch.txt)

here's the error from this file:

**Comment by stephenwaite** [comment]
hi @sjpadgett so there's only 48 segments in the file but the SE segment says 49, hoping there's a `++edicount;` missing before the `    $out .= "ST" .`

**Comment by sjpadgett** [comment]
The missing is in the patched in loop 1000 ie PER is new seqment.

**Comment by sjpadgett** [comment]
@stephenwaite  Want me to fix and put on server?

**Comment by stephenwaite** [comment]
that would be great, thanks

**Comment by sjpadgett** [comment]
Here is new claim and and also put fixed file on server:
[2017-09-07-1016-batch.txt](https://github.com/openemr/openemr/files/1285043/2017-09-07-1016-batch.txt)
I verified in edi viewer the correct seg count... tadah

**Comment by stephenwaite** [comment]
very nice, uploaded to clearinghouse will report back, thanks @sjpadgett

**Comment by sjpadgett** [comment]
I have an 837I ready to go. Can we also give that a shot at same time?
[2017-09-07-1047-837i-batch.txt](https://github.com/openemr/openemr/files/1285362/2017-09-07-1047-837i-batch.txt)

**Comment by stephenwaite** [comment]
sure, 837**P** accepted :)

**Comment by stephenwaite** [comment]
file was accepted! i'm amazed


[Z2626624.txt](https://github.com/openemr/openemr/files/1286018/Z2626624.txt)

**Comment by bradymiller** [comment]
whoa!
A sample institutional x12 from OpenEMR got accepted? that is awesome. congrats @sjpadgett !

**Comment by sjpadgett** [comment]
Thanks @stephenwaite @bradymiller , Great teamwork. Also, my test server will be down for a few hours while I move my stuff to more secure location.

**Comment by sjpadgett** [comment]
@robertdown or @MatthewVita I need to find a smooth exit for various UI cancel/save and go returns in billing.  Some stuff use to close a window but with newer UI window.close simply leave user with white screen. What is a method to close the current tab. I've tried several approaches, no joy. Thanks

**Comment by stephenwaite** [comment]
here's the batch report showing acceptance [Z2799126.txt](https://github.com/openemr/openemr/files/1288298/Z2799126.txt) :)
here's the claim report showing a reject 
[Z2760879.txt](https://github.com/openemr/openemr/files/1288300/Z2760879.txt) :(
got an email into the project manager for more details

**Comment by sjpadgett** [comment]
Claims billed amount prob doesn't make sense and claim may need a value code assigned. Different payers require different boxes.

**Comment by bradymiller** [comment]
@sjpadgett ,
Too close a tab, would call this via parent.
https://github.com/openemr/openemr/blob/master/interface/main/tabs/js/tabs_view_model.js#L96
(would use the tab gui global to decide whether to do that or what is done in frames)

**Comment by bradymiller** [comment]
@sjpadgett ,
Actually, bad advice above. Instead use the top.tabCloseByName() function call to close the tab.
https://github.com/openemr/openemr/blob/master/interface/main/tabs/js/tabs_view_model.js#L106

**Comment by bradymiller** [comment]
these code changes look good to me. will tag @sunsetsystems to see if has any input.

**Comment by stephenwaite** [comment]
guess we can't use all 9s for clinic tax id, will update clinc and send out another test once you're set up at your new location, hope you survived Irma!

**Comment by sjpadgett** [comment]
@stephenwaite I now have waterfront property to park that yacht.:) I changed test server for better formatted fake npi and taxid's. Here is new claim based on previous 837P submitted or my server is up now.
[2017-09-11-1407-837P-batch.txt](https://github.com/openemr/openemr/files/1293589/2017-09-11-1407-837P-batch.txt)

@bradymiller  I found at least one ub04 update we missed in last PR so I am going to included in this PR once I finish going through.

**Comment by sjpadgett** [comment]
@bradymiller Done with this for awhile. @juggernautsei is testing the v5.0.0(3) version of these issues live now but I think it's safe to bring this in but no hurry for me. I'm off to the portal.

**Comment by juggernautsei** [comment]
Thanks, Jerry!

Sherwin
757-328-2736
Juggernaut Systems Express

       www.openmedpractice.com

OpenEMR Simplicity at its best in cloud-based EMR's
“For those who believe, no proof is necessary. For those who don't believe,
no proof is possible <http://beingsaved.org/innercoc.va>.”

**Comment by bradymiller** [comment]
thanks @sjpadgett !!
Just brought your code into the codebase.
-brady

**Pull request merged**
