### PR TITLE
left nav globals

### PR DESCRIPTION
**Pull request by shachar058**
Hi,
Here we added more globals to add more control on what the payments tab in left nav shows.

### CODE REVIEW

**Comment by mdsupport** [comment]
@shachar058, assuming you want to suppress menu links for users not authorized to enter billing wouldn't it be better to use existing ACL values rather than yet another GLOBAL?

On a related aesthetics note, if this a good idea left_nav users, someone would want to extend it to tabs where GLOBALS like `*left_nav*` are going to look a bit misleading.

**Comment by shachar058** [comment]
@mdsupport 
Regarding the `left_menu`, I was just using what was already in `enable_edihistory_in_left_menu`for consistence. Maybe this should be changed too.
Regarding your first comment - I don't quite understand your  suggestion. We would like to make it possible for these tabs not to show. Can you elaborate?

**Comment by bradymiller** [comment]
I think it's ok to use globals to turn off menu items, since this would be a practice wide thing (akin to completely turning off a module/feature).

Even though those other items say left menu, these globals/behavior have also been incorporated into the tabs menu. Going forward and for this code, recommend dropping the left from the global and the label/description text. For the prior items, we should not change the global token name, but should drop the left from the label/description text.

(once this goes into the codebase, I'd be happy to incorporate these new globals into the tabs menu)

**Comment by shachar058** [comment]
Ok removed left from new globals and from the labels in the old ones

**Comment by bradymiller** [comment]
Looks good and will bring this into the codebase. I'll follow it with a commit to bring into the tabs menu and to also make the global descriptions same as labels (to save a tiny bit of effort for the translators :) )

**Pull request merged**
