### PR TITLE
net sftp bug fix

### PR DESCRIPTION
**Pull request by bradymiller**
Proposed fix for the following issue:
https://github.com/openemr/openemr/issues/371
(it needs to be tested)

### CODE REVIEW

**Comment by bradymiller** [comment]
Note to self:
if bring this in, need to change author to MDSupport

**Comment by mdsupport** [comment]
@bradymiller, tested the receive part.  Since it is just the class name change, at least PHP fatal error should be eliminated now.
In case you need to test SFTP->get for yourself, [sftp.net](http://www.sftp.net/public-online-sftp-servers) has list of read only servers that will send you a dummy file.  Their Rebex installation free server is also cool option for more controlled testing from your windows workstation.

**Comment by mdsupport** [comment]
Will include updated cli script with other workflow updates in a PR for labs interface.

**Comment by bradymiller** [comment]
@mdsupport , thanks!

And look forward to the workflow updates PR.

**Comment by bradymiller** [comment]
I just brought this fix into the codebase.

**Pull request closed without merging**
