### PR TITLE
calendar facilities list bug

### PR DESCRIPTION
**Pull request by sjpadgett**
#### Short description of what this resolves:
- calendar facility table not responsive if more than six facilities
- modify dump command option escaping

### CODE REVIEW

**Comment by sjpadgett** [comment]
Tested well. @bradymiller Waiting to see if escaping is more palpable to you.

**Comment by bradymiller** [comment]
hi @sjpadgett , looks great!

**Comment by sjpadgett** [comment]
Yep but I forgot all the other exports like lists etc. Have to go through all windows escing...

**Comment by bradymiller** [comment]
no pressure or anything, but hopefully gonna get 6.0.0 out late tonight (ok, i guess that is pressure :) )

**Comment by bradymiller** [comment]
btw @sjpadgett , @stephenwaite , and anybody else. Here's the planned summary for release statement. Just let me know if any input (I use this for announcements):
```
The OpenEMR community has released version 6.0.0. OpenEMR 6.0.0 has numerous new features including an upgraded API supporting OAuth2, FHIR, and SMART on FHIR in addition to user interface improvements, security improvements, support for 34 language translations, and new support for Kubernetes. OpenEMR 6.0.0 can be downloaded from the OpenEMR Project website at https://www.open-emr.org . Thanks goes to the OpenEMR community for producing this release.
```

The specific Release Features list is here:
https://www.open-emr.org/wiki/index.php/Release_Features#Version_6.0.0

**Comment by stephenwaite** [comment]
sounds wonderful, congratulations @bradymiller ! 
88220254-ba0afc00-cc30-11ea-9dd4-503ca1172e0e

**Comment by sjpadgett** [comment]
Thanks @bradymiller I'll have this finished in a couple hours. Also, don't to forget OICD so it's `OAuth2, OIDC, FHIR, and SMART on FHIR`

**Comment by bradymiller** [comment]
OICD or OIDC?

**Comment by bradymiller** [comment]
figured it out via google. is OIDC. will add it

**Comment by bradymiller** [comment]
tenor99

**Comment by stephenwaite** [comment]
https://user-images.githubusercontent.com/5618372/103705952-f2ea2380-4f79-11eb-862e-858294abe297.mp4

**Comment by sjpadgett** [comment]
bringing in after actions then cherry pick

**Comment by sjpadgett** [comment]
good to go @bradymiller

**Pull request merged**
