### PR TITLE
QRDA I exports from CCM

### LINKED ISSUE #4641: ONC CQM Phase two
This phase will concentrate on import and export development of the necessary QRDA Cat I and III documents.
The QRDA I is a document that contains three main section with the last section(Patient Data based on QDM data types) being important for importing the data necessary to calculate against measures ONC requires at test time.
The resulting calculations are then used in reporting via the QRDA III document.

Once the import is mature enough to populate openemr database with ONC's supplied QRDA I patient data documents based on measures to be tested, we'll continue the development of the patient models for internal CQM calculations that supply's the results for the QRDA III report.

### PR DESCRIPTION
**Pull request by sjpadgett**
Two new classes for QRDA reports
Add new catI html version view button.
Add download zip of selected patients QRDAI reports

Fixes #4641 

#### Short description of what this resolves:
Adds to CCM export Cat I export/download requirement for ONC 2015. These reports are used for import into ONC Cypress testing jig.
Based on imports, Cypress run calculations to compare with the EMR results.

### CODE REVIEW

**Comment by sjpadgett** [comment]
image

Also new qrda html view companion to ccda html.

image

CCDA is not looking too bad!
image

**Comment by bradymiller** [comment]
2DV

**Comment by sjpadgett** [comment]
@kchapple Do you need this PR in master for your testing? I plan to add a measure(s) selection for building export downloads later today.

**Comment by sjpadgett** [comment]
During:

image

After:

image

A small triumph yeah!

**Comment by sjpadgett** [comment]
Add doc type to import:
image

**Comment by sjpadgett** [comment]
@bradymiller 
I decided to add a list as @adunsulag is doing in AMC mainly because I need measure titles etc for UX. The plan is whenever a new reporting period we want to support then a new list would follow e.g. for release we'd have a list of the 47 measures titled:
`eCQM 2021 Reporting Period` then `eCQM 2024 Reporting Period` and so forth.
The measures that user wants to report would then be selected by making measure active in list.

**Comment by sjpadgett** [comment]
I knew dates were going to bite us:
```
{"qrda_catI_export_1647184570\\QRDAI_Bates Jr._Jeremy.xml"=>["22:0: ERROR: Element '{urn:hl7-org:v3}effectiveTime', attribute 'value': [facet 'pattern'] The value '2022-03-13 11:16' is not accepted by the pattern '[0-9]{1,8}|([0-9]{9,14}|[0-9]{14,14}\\.[0-9]+)([+\\-][0-9]{1,4})?'.", "41:0: ERROR: Element '{urn:hl7-org:v3}birthTime', attribute 'value': [facet 'pattern'] The value '1980-08-01T04:00:00Z' is not accepted by the pattern '[0-9]{1,8}|([0-9]{9,14}|[0-9]{14,14}\\.[0-9]+)([+\\-][0-9]{1,4})?'.", "42:0: ERROR: Element '{urn:hl7-org:v3}raceCode', attribute 'code': [facet 'pattern'] The value '' is not accepted by the pattern '[^\\s]+'.", "43:0: ERROR: Element '{urn:hl7-org:v3}ethnicGroupCode', attribute 'code': [facet 'pattern'] The value '' is not accepted by the pattern '[^\\s]+'.", "53:0: ERROR: Element '{urn:hl7-org:v3}time', attribute 'value': [facet 'pattern'] The value '2022-03-13 11:16' is not accepted by the pattern '[0-9]{1,8}|([0-9]{9,14}|[0-9]{14,14}\\.[0-9]+)([+\\-][0-9]{1,4})?'
```

**Comment by sjpadgett** [comment]
@kchapple 
Dates need to be in the form 201512311230-0800 if a time and time zone. Dates like dob don't have time 20151231. Most all dates won't have time zone.

**Comment by sjpadgett** [comment]
@bradymiller I added clear CCDA document types to send. The other type selects will go away as they never really worked w/o a bunch of user interaction.
I'll get around to ensuring all these work soon.

image

**Comment by sjpadgett** [comment]
I'm doing one more commit for creating download zip on per measure with all patients for measure. This is best for test jig. Then I'll bring this PR in. 
@kchapple You might want to review the conversations here to get an idea how the reporting works.
I also attached a screenshot of a cypress validation failed report.

image

**Comment by stephenwaite** [comment]
excited_elephant

**Pull request merged**
