### PR TITLE
find_code_dynamic wildcard addon fix

### PR DESCRIPTION
**Pull request by matrix-drorgo**
Hi ,
I have created an automatic  "like" search for the find_code_dynamic_wildcard screen.
what it suppose to do is when value entered in the search criteria it wraps it with the '%' char.

thanks
Dror G.

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @matrix-drorgo ,
Are you getting any difference in testing when check and uncheck Like? It looks like the search already does wildcard on outsides. For example:
`biovar` and `%biovar%` yield the same entries

**Comment by matrix-drorgo** [comment]
Hi,
I as you can see the search with like gives different results .


image

image

thnaks
Dror G.

**Comment by bradymiller** [comment]
Hi @matrix-drorgo ,
How about the description element? I am pretty sure that already does a LIKE %.% search under the hood, and as above, I saw no difference in the `biovar` and `%biovar` above.
I think the code element does do a LIKE .% under the hood since in this case searching for a digit code makes sense (for example, is that 00 vs %.00.% result meaningful from a practical standpoint?)
-brady

**Comment by matrix-drorgo** [comment]
Hi,
the result of searching 00 and %00% are very meaningful for us since we search more by code and not by description.

**Comment by bradymiller** [comment]
@matrix-amiel ,
From a physician/billing coder perspective, when I search for codes, there are 2 things I may do.
1. If I know the actual code, I would start left to right and use the autocomplete function of what is currently there (ie. code.%). I just have never had a situation where middle numerals (ie. a 0 inside the code of what is essentially a unreadable phrase) are where I would start searching. Can your group can ensure that this behavior is being requested. If this is the case, then I think a global would make more sense on this and have it do this behind the scenes without the Like toggle (of which users won't understand why % signs are being added to the code).
2. If I am searching for text, then makes sense to do a %term% like since this is a readable phrase.

**Comment by sjpadgett** [comment]
How about add a second search field to the dialog? This will save a global and let the user decide how to search.

**Comment by bradymiller** [comment]
Sounds reasonable; let me do some quick research to refresh how the underlying search works.

**Comment by bradymiller** [comment]
That research brought back some nice memories when we converted OpenEMR to flexible code types...
Here's the flow:
1. main_code_set_search() call at https://github.com/openemr/openemr/blob/master/interface/patient_file/encounter/find_code_dynamic_ajax.php#L264-L265
2. main_code_set_search()  (note there is a $mode parameter here) is at https://github.com/openemr/openemr/blob/master/custom/code_types.inc.php#L413
3. main_code_set_search() then uses sequential_code_set_search() which is at https://github.com/openemr/openemr/blob/master/custom/code_types.inc.php#L413
4. Interestingly, in sequential_code_set_search(), which does a couple pertinent things regading $mode and searching described here:
https://github.com/openemr/openemr/blob/master/custom/code_types.inc.php#L762-L766
4. sequential_code_set_search() then uses code_set_search() which is where the magic happens :)
https://github.com/openemr/openemr/blob/master/custom/code_types.inc.php#L458
Here's the pertinent algorithm:
https://github.com/openemr/openemr/blob/master/custom/code_types.inc.php#L586-L606
(This is where code gets a .% search and description gets a %.% search when done separately; note that I see a bug there where if mode is not set and does default search, it will search both at same time and do %.% for both; ie. not consistent; I should probably fix this)

So, there are a couple places to attack this, and we should be able to support separate Code and Description search boxes separately, which I think would be ideal. We are still left, though with how to offer option of a Code search being either .% or %.%.

**Pull request closed without merging**
