### PR TITLE
fix: possible fix of logic in jquery-datetimepicker-2-5-4-translated.js

### PR DESCRIPTION
**Pull request by bradymiller**
possible fix of logic in jquery-datetimepicker-2-5-4-translated.js

hi @adunsulag , noted that the logic in this script may be incorrect (unless i am missing something; perhaps this setting is already set somewhere by default). This is a blind fix since not sure how to test it.

### CODE REVIEW

**Comment by adunsulag** [comment]
@bradymiller Good catch, not sure how that got missed but I can see in the original file that it didn't get copied across.  Currently this is only used in the insurance edit screen.  We'd have to change the settings there to test this.  The default format is 'Y/m/d H:i' which we don't want https://xdsoft.net/jqplugins/datetimepicker/#format.

**Review by adunsulag — APPROVED** [review]

**Review by stephenwaite — APPROVED** [review]

**Comment by stephenwaite** [comment]
nice @bradymiller , couldn't find this file because it snuck by my branch into master :)

**Comment by bradymiller** [comment]
will bring this fix into rel-702 branch

**Comment by bradymiller** [comment]
oops, not bringing into rel-702 since that script does not exist there :)

**Pull request merged**
