### PR TITLE
Add portal flag and supervisor to users

### PR DESCRIPTION
**Pull request by sjpadgett**
Fixes #

#### Short description of what this resolves:

- need to select what users may appear for portal
- add a supervisor for user.
- feesheet add supervisor default to rendering providers supervisor

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @sjpadgett , Code looks good to me. I am guessing you are planning on using the portal_user for something exciting :)

**Comment by sjpadgett** [comment]
@bradymiller 
The portal flag is to support @tywrenn PR for allowing patients and providers to reply to each other without having to be an auth provider.
Also, I can't remember. When we do a patch in 502 with database changes, do we update upgrade, database and patch or just patch?

**Comment by bradymiller** [comment]
In 5.0.2, update patch.sql and database.sql. The upgrade script will run patch.sql if it exists (so thus don't need to add to the upgrade sql file).

**Comment by sjpadgett** [comment]
That's right now only if my brain could get right!
Bringing in. thanks for keeping an eye out...

**Pull request merged**
