### PR TITLE
minor php syntax fix

### PR DESCRIPTION
**Pull request by stephenwaite**
not sure how travis missed this?

### CODE REVIEW

**Comment by sunsetsystems** [comment]
Not sure that's an error. Looks like it's passing a negative number which may be the intent. Does it appear to be a bug in testing?

**Comment by stephenwaite** [comment]
ok, good catch, it's for the previous page, guess it's just missing the closing semicolon?

**Comment by stephenwaite** [comment]
ok, the paging is testing well, kudos to @bradymiller , like to add this functionality to the find_code_popup so it doesn't load the whole icd10 table when nothing is entered in the search box

**Comment by sunsetsystems** [comment]
I fixed a bug like that in find_code_dynamic_ajax.php on 10/02. Make sure you have current code.

**Comment by stephenwaite** [comment]
freshly made this am :), it's called when you click on coding from add issue

**Comment by sunsetsystems** [comment]
It would also need a UI change to support paging. Best solution is to substitute find_code_dynamic.php which already does that and more. It might just plug right in, not sure offhand, but it's on my list of things to deal with.

**Comment by sunsetsystems** [comment]
Just checked, it doesn't quite plug right in but it is something I can do in the near future.

**Comment by stephenwaite** [comment]
very nice, thanks Rod

**Comment by sunsetsystems** [comment]
OK here it is:
https://github.com/openemr/openemr/pull/1123

**Comment by bradymiller** [comment]
gonna bring this into codebase
thanks! -brady

**Pull request merged**
