### PR TITLE
Handle route ids with string values.

### LINKED ISSUE #5743: String-based route types do not save
### Describe the bug

*(As a quick note to start, this work is being driven by my employer, [Altispeed Technologies](https://altispeed.com/). I'm actively working on this issue. Any screenshots shown use test data, and are not associated with any real patient.)*

When setting any of the following options to an existing prescription, they do not save:
 - Intradermal
 - Other/Miscellaneous
 - Transdermal
 - Intramuscular
 - Inhale
 - By Mouth

### Client configuration

- **Browser**: Firefox Nightly
- **OpenEMR version:** 7.0.0.1, tip of master
- **Operating system:** Ubuntu 22.04 LTS, Kinetic (development release)

### PR DESCRIPTION
**Pull request by sjpadgett**
Fixes #5743

#### Short description of what this resolves:
Allow string option_id from drug_route list

#### Changes proposed in this pull request:
Modify Prescription class and change table column from int to varchar

### CODE REVIEW

**Comment by sjpadgett** [comment]
I think this will suffice. 
What is strange is that my databases for ONC QRDA and CCDA both have the drug_route option_ids using all numeric values as if they have been already converted like I did in Simons PR.

Those were the databases we used for testing! In fact all my v7 backups were this way so I'm greatly bewildered and was the reason I embarked on the path I did take in Simons PR.

**Comment by sjpadgett** [comment]
Take a look @bradymiller and merge unless you see an issue. I'm going to bed and the culmination of this PR was not the way my day was supposed to go! thanks.

**Comment by stephenwaite** [comment]
excited_elephant

**Comment by tsimonq2** [comment]
Thank you very much!! :partying_face:

**Comment by bradymiller** [comment]
2DV

(will bring this into rel-700)

**Pull request merged**
