### PR TITLE
SyntaxUpdating

### PR DESCRIPTION
**Pull request by joshuaaguilar20**

### CODE REVIEW

**Comment by danehrlich1** [comment]
Brady can all of Joshua’s pull requests be merged. I think they are just syntax changes? No rush though but I wanted to note.

**Comment by bradymiller** [comment]
hi @danehrlich1 ,
There seems to be overlap in those PR's. Would it make sense to migrate them to 1 PR/commit, which would make it all more clear and make it easier to test. If you don't have time to do, just let me know if you want me to do this (I could likely get it done over the weekend).

**Comment by danehrlich1** [comment]
1. Yes there are a lot of PR’s lol

2. I am actually reading a book on Git right now... they are super strict on my current project about usage of Git, so will be fun to try to do that and see if I can merge them. Give me a week.

**Comment by joshuaaguilar20** [comment]
Dan,

I can look into fixing that as well. Sorry about that guys.

**Pull request closed without merging**
