### PR TITLE
Adding attr to css_header to prevent XSS

### PR DESCRIPTION
**Pull request by sharonco-matrix**
Here is the first PR to add attr to all the places where we are using the css_header global variable in order to avoid an XSS vulnerability.
@bradymiller (please consider cleaning the variables before entering theDB)
We need help to push this into the codebase as soon as possible, we are in the final tests and this came up as a critical XSS vulnerability

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @sharonco-matrix ,
css_header is a special variable that is process in globals.php, so do not need to fix in all these scripts. Can fix this everywhere with just 2 line changes in the globals.php script:
line 352, wrap $gl_value with attr()
line 432, wrap $new_theme with attr()
(also place a comment above each of these lines that added attr() for security)

**Comment by bradymiller** [comment]
btw,
1. Even though your large code change won't be needed, it is still awesome to see this kind of stuff(ie. changes that touch lots of files).
2. Seeing "we are in the final tests" sounds like great news too, which I am guessing means your group will be going into production mode soon :)

**Comment by matrix-amiel** [comment]
Solution in the globals.php in PR #1387.

**Comment by bradymiller** [comment]
Brought in your new PR (which also tested well for me), so will close this PR.

**Comment by sharonco-matrix** [comment]
Exactly! we are getting into production mode very soon...  we are excited

**Pull request closed without merging**
