### PR TITLE
LBF custom template (nation notes) fancybox replace.

### PR DESCRIPTION
**Pull request by sjpadgett**
Updated ckeditor to assets version 4.7.0.
Also add form refreshes for after edits.

(below added by bradymiller)
demo is here:
http://www.open-emr.org/wiki/index.php/Development_Demo#Eta_-_Up_For_Grabs_Demo

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller Probably best we do docker and maybe some friends familiar with nation notes can help test. I think there is an ongoing bug(or lack of function) with templates and context presentation. It's always been there but I'm not sure of the design intent thus, need someone who knows to let me know if I need to fix anything while I'm here..

**Comment by bradymiller** [comment]
@sjpadgett ,
Just set it up for the following Up For Grabs demo:
http://www.open-emr.org/wiki/index.php/Development_Demo#Eta_-_Up_For_Grabs_Demo

@arnabnaha , Do you use Nation Notes? If so, was hoping to get help with testing these changes (this is a huge deal because it gets us away from fancybox that will allow OpenEMR to standardized all it's js libraries and really dive into code modernization).

**Comment by bradymiller** [comment]
@sjpadgett ,
Will this allow us to completely drop the old ckeditor package?

**Comment by bradymiller** [comment]
btw, the code looks really nice. Sadly, I could find no code issues to comment on :)

**Comment by sjpadgett** [comment]
Concerning ckeditor, I believe so and I'm looking into. As for code issues, I'll work on that :)

**Comment by sjpadgett** [comment]
@bradymiller I'm not seeing the ckeditor in custom template dir being used anywhere else and I removed from my dev and tested so, if you take a look and can't spot it used elsewhere, i'll remove with this PR.

**Comment by bradymiller** [comment]
@sjpadgett , your good to go on removing it.
(for git commit strategy, rec keeping the remove as a separate commit in this same PR and then merge pull request when bring this PR into the codebase to have the remove commit separate; makes debugging easier in the future to avoid the real work being lumped together with a bunch of deleted files in the same commit)

**Comment by bradymiller** [comment]
Just updated the up for grabs demo to bring in most recent commit :)

**Comment by bradymiller** [comment]
I plan to test this out via the following wiki page:
http://www.open-emr.org/wiki/index.php/Nation_Notes

**Comment by sjpadgett** [comment]
Be aware the Add Category button is in the Personalize popup, not main dialog...Not sure what that is about

**Comment by arnabnaha** [comment]
Hi..Brady
I do use nation notes till now..i have couple of forms build with nation notes. I will test this out now
Thanks
Arnab

**Comment by arnabnaha** [comment]
I am testing this using the  up for grab demo you have created. I created a new nation note form called blood invetigation. I added categories, added context and everything. I am able to use it nicely. everything is working fine. The form is saving well and displaying well. All functions are good.

**Comment by bradymiller** [comment]
Thank you @arnabnaha !
Looks like you have a green light to bring this into the codebase @sjpadgett :)

**Comment by sjpadgett** [comment]
@arnabnaha Yep the retouched themes really are looking great in frames, even green:) Thanks for looking over, I was concerned with this one. I've noticed the updated ckeditor has some new features that may prove useful in NN. Thanks.
@bradymiller As soon as I catch up with ya,  I'll try another this morning. Seems you've gotten the hang of losing fancybox. :) Bringing this one into codebase.

**Pull request merged**
