### PR TITLE
New oeFaxSMS Module with RingCentral

### PR DESCRIPTION
**Pull request by sjpadgett**
- see #2635
Doing this in this way makes for a pain to take back to v5.0.2. I may even still make this a module install when I add Twilio api.  I may add a function to utilities.js to send fax from a rest call so folks can send faxes and messages from their scripts etc.

This is just a basic REST interface from abstract class oeActionDispatch extended by oeFaxSMSClient class. Redirect .htaccess is not necessary as dispatch class could have simple mod to rid it. Not sure why I use it except for some versatility.

This is as simple as I could keep it w/o using frameworks etc. I was half tempted to make the html a template but need to get this done so....
The credential template is temporary. To log on for testing see #2635 for howto.

Let's do an up for grab demo and see how it goes. Then while adding Twilio I can make adjustments if requested. 

Thanks in advance @bradymiller for helping me clean this up.

### CODE REVIEW

**Comment by matrix-amiel** [comment]
Hi @sjpadgett 
1. We want that all the working with notifications will be in the openemr screens, therefore, we prefer to use Twillio api that not required login into another service unlike RingCentral.
2. I took al look on your screens, we don't plan to use Fax but the screen of sending sms before an appointment could be useful for us, we have thought to create a more generic mechanism for sending notifications according to rules, would you think it can be merged with your development?
3. I think it's not hard to write guide for creating a new account in Twilio for users who want to use with sms.         
4. Just my thoughts, why we do not use know framework (like ZF) for all the new screens?  it's can save a lot of working if we will use an existing functionality...

**Comment by bradymiller** [comment]
This is weird. I am seeing no modified files on this PR:
image

**Comment by bradymiller** [comment]
looks like you reverted your work in your branch:
image

**Comment by sjpadgett** [comment]
Yep, moving lots of stuff around and more tightly integrating. Might put up ringcentral tomorrow. Close to being done with twilio so may wait. or I may just go fishing....

**Pull request closed without merging**
