### PR TITLE
JS packages update

### PR DESCRIPTION
**Pull request by bradymiller**
Still in early testing phase. Just seeing what it will take to update all the npm packages (except for bootstrap).
Don't worry @sjpadgett , this won't even get close to the main codebase until the bootstrap PR is in :)

When ready, planning to bring this work into the bootstrap PR rather than master.

Notes below (ie. scratchpad):
* **LATER** had to keep the literallycanvas/react duo since literallycanvas is basically a dead project and using the most recent working distribution. Goal will be to migrate to another tool (and could then drop react).
* **LATER** look into jscolor further
* **LATER** knockout 3.5 not working, so dropped back to 3.4.* branch; try debug later
* **LATER** also see if can deal with the manually added and modified assets
* **LATER** Completed updating build pipeline(updated packages and migrated gulpfile.js to use gulp4) (need to do more testing, especially the watch thing) (also need to try to remove the warnings, issues; ensure do with and without the package lock)
* **LATER** Remove outdated CSS and JS files from /interface/modules/zend_modules/public and instead link the files to the respective /public/assets folder
* **LATER** chart.js works, but there are deprecation notices
* **LATER** scan assets and vendor stuff and filter out unneeded dir/files in build.xml.
* **LATER** with dwv dicom viewer and related updates. Working on testing. Note needed to use dwv 0.25.2 rather than 0.26.0 since 0.26.0 was throwing error (can work on this in future after this code is in main codebase).
* **LATER** confirmed that jquery-ui and jquery-ui-theme npm packages are not usable, so keep using the napa collection

### CODE REVIEW

**Comment by sjpadgett** [comment]
Also if anyone with more experience than I will look at compiling BS4 sass using current npm-sass, I am having issue with that workflow. We may need to bring in DART.

**Comment by sjpadgett** [comment]
@bradymiller 
Testing jquery-ui drag resize replacement. Looking at https://github.com/taye/interact.js but in the end I may write our own library. The above opens up many other useful features though.
Also, select2 bootstrap css may need to be styled away but I don't think most folks used in many palaces.

**Comment by bradymiller** [comment]
@sjpadgett , I'm getting close to bringing this PR code into @tywrenn 's bootstrap PR. Just a little more road testing (and after @tywrenn 's pending commit).

**Comment by bradymiller** [comment]
@sjpadgett and @tywrenn , I just brought this code into the bootstrap PR.

**Pull request closed without merging**
