### PR TITLE
Several minor bug fixes

### PR DESCRIPTION
**Pull request by ophthal**
Spectacle Rx fix.
JS,Help.php and styling.

### CODE REVIEW

**Comment by bradymiller** [comment]
nicely done PR. I'll bring this into the codebase this evening (I will squash it all into 1 commit, since will also bring these fixes into the next 5.0.0 patch).

**Comment by ophthal** [comment]
Old dogs can learn new tricks…

**Comment by ophthal** [comment]
Ok so there is one more commit needed to fix the specs bug...

**Comment by bradymiller** [comment]
@ophthal , ok, will delay pushing this PR then. Just let us know when it's ready :)

**Comment by ophthal** [comment]
It’s up there now.

**Comment by bradymiller** [comment]
ok, going to bring this in as 1 commit. thanks for the fixes! -brady

**Pull request merged**
