### PR TITLE
PHP7 fixes for openflashchart

### PR DESCRIPTION
**Pull request by juggernautsei**
I had time to update the library to the PHP7 standards.
Deprecated class calls have been corrected.

### CODE REVIEW

**Comment by bradymiller** [comment]
Nice. Code looks good. Just let me know that the graphing is testing well for the vitals, and then I'll bring this into the codebase.

For the future, recommend avoiding adding trailing whitespacing (we are in process of removing this from the codebase). What code editor do you use(then I can provide guidance how to atuomatically remove trailiing whitespacing for the future)?

**Comment by juggernautsei** [comment]
I am using Notepad++ as my editor. 
Yes, I tested the code as I did the changes. Looking at the error log every time to make sure the error had been eliminated.

**Comment by bradymiller** [comment]
Just brought your code into the codebase. Thanks for the fixes!

In Notepad++, try Macro -> Trim Trailing and save (this should then remove all the trailing whitespaced)

**Comment by bradymiller** [comment]
as an aside, a simply awesome editor is sublime:
https://www.sublimetext.com/
(I left vim for it a couple months ago and have never looked back)

**Comment by juggernautsei** [comment]
I will try the sublime.

**Comment by bradymiller** [comment]
I placed some instruction on your Slack to help get some very useful sublime packages.

**Comment by MatthewVita** [comment]
> I left vim for it [Sublime] a couple months ago and have never looked back)

I could not recommend [Vintageous](https://github.com/guillermooo/Vintageous) for Sublime more. It's an incredible Vim emulation layer for Sublime. You'll have the beauty and productivity of Vim, but in a very modern code editor.

**Pull request merged**
