### PR TITLE
More BS4 Fixes

### LINKED ISSUE #3637: Portal Drop-down Showing when it shouldn't
### Describe the bug

The portal notifications drop-down is now showing all the time when it should be hidden.

image

### LINKED ISSUE #3644: Audio files should be shown in an audio player instead of downloaded
### Describe the problem
At the clinic that I work for, we record audio with patient encounters using a custom module that I built that records the audio and then sends it over to the document tree of the patient. A big problem with the documents area is that it tries to download the audio file instead of displaying it.

### Describe the solution you'd like
I'd like for the documents area to be able to view audio files instead of downloading them. The ones that my clinic uses are ogg files yet with a simple line of code in HTML I could in theory support almost all audio file types.

### LINKED ISSUE #3651: Occasional Glitching with FontAwesome
### Describe the bug
After converting to using SASS for Font Awesome, a glitch is happening where occasionally there are random letters after a Font Awesome icon.

### Solution
Modifying the SCSS a little bit might fix this issue. We use an escape character after every icon which probably is causing the issue so solving that will fix this.

### LINKED ISSUE #3683: UI Issue: Search or Add Patient odd input field
### Describe the bug

I am not sure, when I click the input field, it will show the orange background.
Also, the layout of the form looks like it needs to adjust. Please assign this issue to me.

### To Reproduce

1. Go to Patient Finder
2. Click Add new Patient  button
3. See the odd field 

image

### Client configuration

- Browser: Firefox 75
- OpenEMR version: OpenEMR 6.0.0-dev
- Operating system: Windows 10

### LINKED ISSUE #3694: list editor missing header
Screenshot from 2020-06-29 10-09-35

@tywrenn , would `py-1` be ok here?
https://github.com/openemr/openemr/blob/master/interface/super/edit_list.php#L1030

### PR DESCRIPTION
**Pull request by tywrenn**
Fixes #3637
Fixes #3651
Fixes #3644 
Fixes #3683
Fixes #3694

#### Short description of what this resolves:
This fixes numerous issues related to BS4 and also fixes an issue where portal messages are always showing up. This also fixes a glitch where Font Awesome was showing random letters on occasion.

### CODE REVIEW

**Comment by tywrenn** [comment]
#### Changelog so far
- Fixes superbill area
- Fixes portal admin view
- Hides portal dropdown
- Add EMR version to bottom of portal footer in some areas
- Other fixes


This is still ongoing

**Comment by tywrenn** [comment]
Changelog:
- Updated file browser area to BS4
- Changed demographics area to use BS4 grid instead of tables (this took forever)
- Other random fixes

@bradymiller How do I test the therapy groups area?

**Comment by bradymiller** [comment]
@tywrenn , Turn on this global and then logout/login. Then will see the group menu at top. Note these groups act like patients in a way. You will see what I mean when you test it out:
https://www.open-emr.org/wiki/index.php/Administration_Globals#Enable_Group_Therapy

**Comment by tywrenn** [comment]
Changelog:
- Removed orange background and changed over to BS4 for the add new patient area
- Updated options inc to use more bootstrap (Note: I don't know how much this will break)
- Add audio support for documents area
- Other fixes

**Comment by tywrenn** [comment]
Changelog:
- Redesigns group therapy area with BS4 in mind
- Fix script issue on add new patient area where we tried hiding fields when on mobile but failed
- Attempted to make the new patient area more mobile-friendly
- Other fixes

**Comment by tywrenn** [comment]
@bradymiller This is now ready for testing/merging

**Comment by bradymiller** [comment]
hi @tywrenn , Really nice work! Looks good and testing well. Gonna bring this in (I'll do quick PSR12 fixes after bring it in). thanks!

**Pull request merged**
