### PR TITLE
Add AutoLoader functionality

### PR DESCRIPTION
**Pull request by robertdown**
Setup an AutoLoader to begin to ease the use of require statements. For instance, the patient module I'm working on will be located in library/Patient/src/ but instead of managing the path depending on where I'm at in the code, you can now just use

````
<?php 
use OpenEMR\Patient\<ClassNameHere>;
$patient = new OpenEMR\Patient\ClassNameHere(); // or
$patient = new ClassNameHere();
````

and it'll just work

This should be utilized as it:
1. promotes modularized development
2. reduces the risk of error by lessening the burden of require_once statements and
3. falls in line with modern PHP development practice. This is common practice.

There is also a ViewHelper module, where I began transposing various helper function into. For instance, you can now call

````
<?php 
$formatted = ViewHelper->money($amount, $symbol)
````

and be given back a proper currency string. This is essentially moving various functions found in .inc files into a central class that makes a bit more sense in terms of nomenclature.

This should be implemented as again it promotes modularization of code, keeping functions out of the global namespace and improving re usability.

I am working on a Patient module that will be the central interaction point for a patient, but I choose to leave it off from this code review as I want this first step to be clear and concise.

### CODE REVIEW

**Comment by kchapple** [comment]
While I agree with the importance of autoloading, I'm not sure about checking in a hard-coded configuration to the project. Why not just use composer?

**Comment by robertdown** [comment]
I have no problem with composer, I use it in nearly every project I write. Is the consensus to implement that? If so, I'll go back and work that in.

**Comment by tmccormi** [comment]
We are starting to use composer for a lot of our customization installs

Tony

**Comment by robertdown** [comment]
That's good news. I'll work on that later tonight, perhaps Wednesday depending on how work goes.

For the inclined: https://getcomposer.org/doc/01-basic-usage.md#autoloading

**Comment by kchapple** [comment]
No, not saying that your way is bad, or that you should re-implement. Just a quesiton :) Autoloading is very nice and this is good work. Thanks!

**Comment by robertdown** [comment]
Autoloading is now handled by composer. Add a module by adding it to the list of psr-4 autoloaders in composer.json and then run `composer dump-autoload` to get the updated autoload files into vendor.

**Comment by robertdown** [comment]
Any movement on this @bradymiller?

**Comment by bradymiller** [comment]
in my queue :)

**Comment by robertdown** [comment]
My goal is to move over core code into a modular system. For example, all interaction with a Patient would happen at the class-level. Since Patient is a core module, it'd stay under the library folder. I'm looking at adding a top level "public" folder, where front-end assets would eventually migrate. So public/assets/js/some-cool-jquery-plugin.js.

We should mitigate jquery version conflicts using some PHP logic, but I think it'd be better to implement a tighter standard on what jquery versions we allow in the code.

Vendor packages generally kept under the top level "vendor" folder, which currently doesn't exist. I'm all for keeping vendor-specific code in the vendor/<vendor-name> folder format. 

I don't know much about how 3rd party modules are handled now, so I have no input on the registry table.

There is no easy way to extend this architecture to current code - current code would need to be refactored into a better structure.

**Comment by mdsupport** [comment]
[This commit](https://github.com/mdsupport/openemr/commit/0c295b3ab8bbd16d30743adad352f36c33d09294) has insert_features code which centralizes several code components into a single function call.  It also implemented include_once for scripts and stylesheets.  Although we use it in all our code, few months ago, based on [this discussion](http://sourceforge.net/p/openemr/discussion/202506/thread/c1a0eab7/) there was little interest in any central control.  Reason for bringing this was for stuff like patient search which your core class will need to address.  When you do that, it would be good if that is a general purpose utility class rather than a point solution.  
Great work.

**Comment by robertdown** [comment]
@bradymiller Any feedback on this PR?

**Comment by bradymiller** [comment]
Hi Robert,
It's still in the queue :(
I was prioritizing your ui stuff. Any progress on that?
The MU2 deadline is 2 months away and things will likely be hectic until the deadline passes.
-brady

**Comment by bradymiller** [comment]
On a somewhat related note, would the stuff that will likely be brought in by the Zend code be helpful on your endeavor:
https://github.com/zhhealthcare/openemr/commits/CareCoordinationV3

My code review of the Zend code is on sourceforge (which has been down for several days). Let me know if your interested in my review and I can paste it here (it's rather long).

**Comment by robertdown** [comment]
I know Zend has an autoloader - I just wasn't sure if we can reliably use the Zend stuff outside of what ZH brought it in for.

The reason I keep pestering is because this provides a lot f the base for my UI stuff. But if I can use the Zend autoloader stuff, I will look into that also.

**Comment by bradymiller** [comment]
The UI is looking nice, though. Just seems like this will further delay the UI. Zend is in the project now, so could leverage this, if think it will be helpful. As an aside, a very nice thing to leverage would be Zend's database engine (to solve the issue when php no longer supports mysql connector); basically wrap functions in library/sql.inc around Zend rather than adodb.

**Comment by mdsupport** [comment]
If Zend is to become core requirement, please consider moving it to vendor directory and using composer.  Putting entire framework deep within any of the project's 'standard' directories is unusual.

**Comment by tmccormi** [comment]
Unusual and bad.  I strongly agree with mdsupport on this issue.

Tony McCormick
www.mi-squared.com
On Jul 25, 2015 9:37 AM, "mdsupport" <notifications@github.com> wrote:

> If Zend is to become core requirement, please consider moving it to vendor
> directory and using composer. Putting entire framework deep within any of
> the project's 'standard' directories is unusual.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openemr/openemr/pull/56#issuecomment-124860199>.
>

-- 
Please be aware that e-mail communication can be intercepted in 
transmission or misdirected. Please consider communicating any sensitive 
information by telephone.  The information contained in this message may be 
privileged and confidential. If you are NOT the intended recipient, please 
notify the sender immediately with a copy to hipaa-security@mrsb-ltd.com and 
destroy this message.

**Comment by robertdown** [comment]
I agree that Zend should be in the vendor folder - I've thought this from the beginning.

**Comment by bradymiller** [comment]
Looks like there is now a vendor folder in their more recent code undergoing review:
interface/modules/zend_modules/vendor

Should this be moved and if so, can this be done while supporting the non-Zend code? I am basically asking what needs to be done to fix this issue.

Here's the code and review:
https://sourceforge.net/p/openemr/code-review/243/

**Comment by mdsupport** [comment]
interface/modules/zend_modules/vendor is Zend's vendor directory.  Zend will be our vendor as 
<<openemr>>/vendor/zf2/...

**Comment by robertdown** [comment]
If we wanted to use standard practice, ALL non-openemr code would be under /vendor. This would include ZF2, as well as any modules ZF2 may rely on. 

Have we considered using composer to manage things like this? getcomposer.org

**Comment by tmccormi** [comment]
We (MI2) have begun using composer for all our customized modules ...  much
easier to keep the code clean.

Tony McCormick, CTO
www.mi-squared.com
Support: 866-735-0897, Direct: 713-574-6709
My Calendar:  http://bit.ly/XznvDo
 ... we have to slow down a bit to be able to speed up a lot... (me)



On Mon, Jul 27, 2015 at 1:57 PM, Robert Down <notifications@github.com>
wrote:

> If we wanted to use standard practice, ALL non-openemr code would be under
> /vendor. This would include ZF2, as well as any modules ZF2 may rely on.
>
> Have we considered using composer to manage things like this?
> getcomposer.org
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openemr/openemr/pull/56#issuecomment-125340529>.
>

-- 
Please be aware that e-mail communication can be intercepted in 
transmission or misdirected. Please consider communicating any sensitive 
information by telephone.  The information contained in this message may be 
privileged and confidential. If you are NOT the intended recipient, please 
notify the sender immediately with a copy to hipaa-security@mrsb-ltd.com and 
destroy this message.

**Comment by robertdown** [comment]
Going to close this. Composer is coming in #150 and that will handle autoloading

**Pull request closed without merging**
