### PR TITLE
EOB fixes

### LINKED ISSUE #3863: EOB Post new payment
### Describe the bug
EOB Post new payment amount doesn't decrease during distribution v5.0.2(1-4)

EOB is not the place to do a manual payment posting imo. Too many ways to get into trouble and that workflow is more conducive to Batch Payments. ERA only!
@stephenwaite is this why you had me hide Posting in v6.0?

### PR DESCRIPTION
**Pull request by sjpadgett**
- js opener form update syntax error
- php save payer id invalid array
- open form to invoice search

Fixes #3863

### CODE REVIEW

**Comment by sjpadgett** [comment]
I'm so over billing!

**Comment by juggernautsei** [comment]
I understand completely

**Comment by sjpadgett** [comment]
I'm pulling the Save Current button as it is confusing people. It'll be just Save.
I found a maria/php 7.4 query bug in batch payment search so once fixed, i'll do a patch.

**Comment by bradymiller** [comment]
@sjpadgett versus billing

tenor (35)

**Comment by sjpadgett** [comment]
You and cats Brady. Is this a thing we should worry about?

**Comment by bradymiller** [comment]
nope, nothing to worry about :)

tenor (29)

**Comment by sjpadgett** [comment]
@bradymiller Check out my last commit. What's up with the DateToYYYYMMDD()? I haven't looked but should I be worried about if this function is broken?

**Comment by juggernautsei** [comment]
@sjpadgett 
image

**Comment by sjpadgett** [comment]
lol, today a hero, tomorrow, a villain!
I'm think this gets us there until......
@juggernautsei There were definitely bugs in EOB posting. thanks for bringing up however, umm take a break on the billing stuff.:)

bringing in and will post a patch somewhere here shortly.

**Comment by sjpadgett** [comment]
@juggernautsei Here is patch. I may post it on billing forum thread tomorrow when I build in patch 4. This can only be installed on top of patch 4. Important!
This also includes a left nav fix and new 2020 ICD10 zips.

[issue_eob_patch_.zip](https://github.com/openemr/openemr/files/5093767/issue_eob_patch_.zip)

**Comment by juggernautsei** [comment]
Understood, I will post it today and get her to step through it.

**Comment by juggernautsei** [comment]
Jenzen has not tested the changes. I have stepped through them alongside the video and the changes are active. 
I uploaded the zip files but the system does not recognize the updated files. Was I suppose to remove the older files?

image

**Comment by juggernautsei** [comment]
Yes, that was it. Once I removed the old files the system prompted me to install the new codes.

**Comment by juggernautsei** [comment]
The patient balances are not correctly calculating. I know you are over this billing thing. But people need you...

image

**Comment by sjpadgett** [comment]
@juggernautsei 
This is because of posting against patient instead of insurance. Encounter last level closed is off and needs to be reset. Possibly from previous attempts to post. Need to double check that the correct posting level is indicated when posting if not set!
This is my guess. This is why I allow level to be reset in edit.

**Comment by sjpadgett** [comment]
@juggernautsei I know you don't have control over this but, what user is doing is what batch payments is for. I know the whole dos argument but, in batch, charges are sorted by dos/encounter/patient. Plus it takes half the time to do a payment. Where in EOB you have to hold your tongue just so to ensure insurance done with and posting to are set and even then, you can't edit an ar activity. Plus you have to save current encounter then open another and so forth.

It really, imo, is worth the effort to learn the workflow. okay, last i'll say about this. besides, I have to push my work product somehow to feel it was worthwhile!:)

**Comment by juggernautsei** [comment]
I'll see what I can do with her. She is resistant because the batch payment does not show the instant balance change in her mind.

**Comment by sjpadgett** [comment]
That's okay I guess. Maybe afterwards I can improve either...

**Pull request merged**
