### PR TITLE
Medex9.28.22

### PR DESCRIPTION
**Pull request by ophthal**
Remove a MedEx Preference.
Reset background_services on Preference change.

### CODE REVIEW

**Comment by stephenwaite** [comment]
hi @ophthal , is this ready to bring in? thanks

**Comment by ophthal** [comment]
Only Ralf is using the latest openemr version and I haven’t heard from him in a while, so the answer must be yes for MedEx.

However, a cursory look at the demo and I see lots of formatting errors associated with the Recall Board due to MedEx for non MedEx users.  Haven’t looked at the Flow Board.  Eye Form is loaded with new errors too.  

I think it may be time for me to submit PRs to remove MedEx from parts of OpenEMR like the Recall Board - very few MedEx people use the Recall Board…

**Comment by stephenwaite** [comment]
Ok, thanks @ophthal. We'll bring this in and get into the next patch too.

We've been fixing up php8 errors along the way and hopefully that's all there is to address in those places.

**Comment by ophthal** [comment]
Maybe.  The advanced features can only really be appreciated when used in production over time - it continually adapts for each provider as data is entered and also for individual patient charts as new visits are added, so I understand how they can be missed.  It is not a simple form to debug since it wasn’t written by a programmer ;)

**Pull request merged**
