### PR TITLE
OpenEMR Cloud: v1 Beta AWS Guide

### PR DESCRIPTION
**Pull request by MatthewVita**
This solution is provided by https://github.com/GoTeamEpsilon under an MIT license.

### CODE REVIEW

**Comment by MatthewVita** [comment]
@bradymiller or @robertdown,

Phew. Okay. Ready to check in the beta guide.

Please note the following:

1) The tar file in the guide has a custom version of OpenEMR v5.0.0-2 checked in... however, it's ~80MB. Hopefully this isn't a big deal?

2) I've adjusted raw absolute download links to point at master so these links will be broken in this PR.

Thanks,
Matthew

**Comment by bradymiller** [comment]
Hi @MatthewVita ,

Probably makes more sense to place the 80MB file on sourceforge download. I can quickly do this(in matter of 30 minutes before would be able to download it). I would make a 'OpenEMR Cloud' category with a 5.0.0 folder and put it there:
https://sourceforge.net/projects/openemr/files/?source=navbar

And a download link would then be:
https://sourceforge.net/projects/openemr/files/OpenEMR%20Cloud/5.0.0/openemr-v5-0-0-2-cloud.tar.gz/download

And can place a README there with quick description and link to the manual on github openemr repo docs. And could even place this in the Downloads section of OpenEMR website with of course warnings that this is Beta and not yet Hipaa compliant that again links to the github openemr repo docs.

thoughts?
-brady

**Comment by MatthewVita** [comment]
@bradymiller that sounds great. Once this gets merged and we have verified the links are working, I will update the downloads section!

**Comment by MatthewVita** [comment]
Please let me know when the tarball is uploaded to SF. Thanks!

**Comment by bradymiller** [comment]
It's up an here's the download link:
https://sourceforge.net/projects/openemr/files/OpenEMR%20Cloud/5.0.0/openemr-v5-0-0-2-cloud.tar.gz/download

**Comment by bradymiller** [comment]
After you drop the tar file and modify the download link, then feel free to commit this PR into the codebase. Use 'Squash and merge' here so then won't bring the tar in and out (which would then cause rather long time for developers to update git repo).

Let me know when you do this and then I'll add this to the OpenEMR download page.

(in future, I'll show you how to do all this stuff)

-brady

**Comment by bradymiller** [comment]
If you want to get your feet wet with the file release on sourceforge, then feel free to delete and add a new README file here:
https://sourceforge.net/projects/openemr/files/OpenEMR%20Cloud/5.0.0/

**Comment by MatthewVita** [comment]
Okay @bradymiller thank you so much.

I amended the branch to not include the tar file.

HOWEVER, it looks like the tar file is screwed up:

image


image


See the weird `.` `_` files? Maybe the tar got messed up?

**Comment by MatthewVita** [comment]
Oops, looks when something went wrong when Daniel zipped it up originally. Just re tarred and fixed up the sourceforge file and README

**Comment by MatthewVita** [comment]
Appears to be good now... here goes nothing!

**Comment by MatthewVita** [comment]
@bradymiller I will update the download page and create a new ticket for the v1 stable solution shortly...

**Comment by bradymiller** [comment]
@MatthewVita ,
I noted the md5sum on the README doesn't match the md5sum on sourceforge (click the i bubble thing to the left of the garbage can). Either is because README not updated or the full file didn't get uploaded to sourceforge (ie. make sure the md5sum of the file you uploaded matches the md5sum reported on soureforge to avoid this).

**Comment by MatthewVita** [comment]
Hi @bradymiller,  think this is a caching issue on SF because I see them matching.

**Pull request merged**
