### PR TITLE
bug fix for null skipArray in History

### PR DESCRIPTION
**Pull request by sjpadgett**
Been bugging me so here it is.
@bradymiller if you need I can put this in v502 and/or bring clear logs by Sherwin or other you need done.

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @sjpadgett ,
I just brought this into rel-502. Let me take a quick look at the clear logs to see if that will go into rel-502 easily.

**Comment by bradymiller** [comment]
just brought in the clear log stuff into rel-502 also :)
(fyi @juggernautsei )

**Comment by juggernautsei** [comment]
=)

**Comment by bradymiller** [comment]
fyi @sjpadgett and @stephenwaite , Patch is gonna be released soon (zip patch and branch is testing well; just need to test the new packages/docker before release them). Thanks for the recent fixes.

**Comment by stephenwaite** [comment]
ok, nice going @bradymiller , Ray might have found another bug in billing :|, still time for one more fix?

**Comment by bradymiller** [comment]
@sjpadgett and @stephenwaite , Gonna hold off on the patch (just a day or so) to bring in your recent 2 fixes in addition to the security fix just posted. Hopefully that will be all :)

**Pull request merged**
