### PR TITLE
Patient Finder to show deceased patients at end

### PR DESCRIPTION
**Pull request by mdsupport**
Deceased patients to appear at end of find results

### CODE REVIEW

**Comment by bradymiller** [comment]
From a workflow perspective, there are times when i need to go into a deceased patient's chart (death certificate info etc or unfinished paperwork). And if no longer alphabetically sorted for that use case, could that confuse users?

**Comment by mdsupport** [comment]
If Doe, Jane is deceased and Doe, John is not, both will still show up during search - except Jane will be towards end. More of UX choice where choices likely to be more relevant in general are presented first. 

Unfortunately no experience or interest in datatables - otherwise a visual indicator like muted row will make it obvious for the users.

**Comment by sjpadgett** [comment]
I had two goals for release 6.1.
- Split Billing
- Archiving Patients

unfortunately I haven't been able to get to them. However for archiving patients I plan to modify patient Finder to search by archived patients so user can view or bring back to active. Would not a deceased patient be archived? or could add as search param while i'm in the datatables. I too find datatables tedious.:)

**Comment by mdsupport** [comment]
Archiving is a big long term solution. But from experience with other systems, it opens a can of worms because project does not implement referential integrity at data level. In any case, most practices would keep these records around until billing is completed. That could be for several months. Malpractice guys will like it there for several more years. During that time, what would be percent of searches where inactive patient would have equal relevance as active patients? In any case, when search returns more than 10-20 results user will find it expedient to keep refining rather than scroll.

Had this mod for years and no complaints.  Did look at putting an asterisk in the name but have no time in addressing any issues other parts could create.

Ideally the project should support concept of 'inactive' patient. We currently use translation as a workaround and treat deceased_date as date when inactivity started. As an example, if patient requested transfer of medical records, doesn't that record have same retention requirement as a deceased patient?

**Comment by sjpadgett** [comment]
I guess archive is a misnomer on my part. Inactive would be a better way to put it. The way I plan to do it is not really a big lift!
It's a matter of removing the inactive patient from views and reports. Is that not the goal of marking patient inactive. Or I may be wrong not having much clinical experience.
All I know is that this has been asked for in the community for years and the only reason we haven't done it up to this point is we have to touch a lot of core.

**Comment by robertdown** [comment]
I agree with Brady re: the workflow and usability concern. We know deceased and inactive patients are causing performance issues and @sjpadgett seems to have a plan. This PR would be negated by those improvements and could cause confusion to the end user in the intermediate.

**Comment by sjpadgett** [comment]
I am going to take this on now. Hopefully in next day or two I'll put up a working PR so you guys can give input and guidance.
I really would like to get this feature into next release.

**Comment by mdsupport** [comment]
@sjpadgett , In your design please consider adding and using the active flag to patient_data as specified in [FHIR model](https://build.fhir.org/patient-definitions.html). Also specifies link between patient.active and patient.deceased.

**Pull request closed without merging**
