### PR TITLE
Some last minute changes

### LINKED ISSUE #7027: Default themes font size to small
### Describe the bug
For BS3 the default font size was 14px however for BS4 the size was increased to 16px. My guess is was due to newer and better resolution displays. 
So when we refactored to BS4 it was decided by Tyler to keep near 14px by scaling defaults to 0.875 rem getting close to 14px.
However this is not appropriate anymore IMO!
### Expected behavior
Follow BS4 defaults

### Client configuration

- Browser: all
- OpenEMR version: 6.10 up
- Operating system:

### PR DESCRIPTION
**Pull request by sjpadgett**
- Change themes default font size to BS defaults 1rem.
- add card class to center cards class list
- fix Medications card list font weight to normal from bold.

Fixes #7027

### CODE REVIEW

**Comment by sjpadgett** [comment]
I think it is an improvement but others may not. Pull my branch and look if you want to keep me honest!:)

image

image

**Comment by sjpadgett** [comment]
image

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
didn't test, but have faith :)

2DV

**Comment by sjpadgett** [comment]
I let you bring back @bradymiller

**Comment by bradymiller** [comment]
done :)

**Pull request merged**
