### PR TITLE
AD

### PR DESCRIPTION
**Pull request by shachar058**
Hi Brady,

This is a cool addition to enable auth against active directory.

The general idea:
The authentication of the users will be against AD. Still though, the acl of users (and all user info) will be against the DB. This means that though 'user_security' table will not be used (as we are not storing passwords in the DB), every user MUST exist in the 'users' table. Therefore in the system initialization (setup), if the user wants for auth to be against AD, he will need to provide his username (not password) so system can create his user in the DB.  

There is still much work to be done - I've only developed the login procedure. 
We still need to:
- Authenticate the E-sign with active directory
- Disable 'change password' screen incase active directory auth is enabled
- When adding a user the password (of whoever is adding the user) is checked against the AD and no password is needed for the new user
- Update setup process so that if we want to use AD auth then user will be able to enter connection details and his user in the active directory (password will not be needed because when he logs in it is checked with AD

So this feature is still under heavy development, but wanted to hear your thoughts on what was done so far and suggestions for the future.

P.S. 
I have no idea why git made a whole scramble of the login_operations file - I tried reverting and commiting again but didn't help, tell me if you know how to beautify this.

Regards,
Shachar

### CODE REVIEW

**Comment by bradymiller** [comment]
Looks very promising and the strategy sounds good. -brady

**Comment by bradymiller** [comment]
Would is make sense to not touch setup.php? Meaning the first user always gets a password assigned in OpenEMR. And then that user would then setup active directory to work; then that user(and all other users if exist) would be using active directory for credentials after this (and would have a backup login mechanism in case turns off active directory). This also makes it more simple since don't need to have a mechanism to turn on active directory during installation. And note many OpenEMR packages start with OpenEMR already installed (ie. bypasses setup.php).

**Comment by bradymiller** [comment]
Just checking if this is still an active project?

**Comment by sharonco-matrix** [comment]
Yes, we will send you more updates soon 
Thanks

**Comment by oshriromatrix** [comment]
Brady hi,

As you suggested we didn't change the setup process.
There is now AD support for login, user creation, and e-sign.
If AD is on, in user creation the password checks against AD and no new password is needed for the new user. Also, the link for updating password will be hidden, and screen blocked.

Hope to hear from you soon to get this cool feature up and running.

Thanks!

**Comment by bradymiller** [comment]
The code is really nice and clean. Gonna test it now (I can't test the AD stuff, but will make sure everything still works when AD is off).

**Comment by bradymiller** [comment]
nice work! testing very well (with AD off; note I am not able to test the AD on feature). Going to bring this into the codebase and thanks for the awesome feature! -brady

**Comment by bradymiller** [comment]
Note I added the following commit after it (placed these setting in the globals Security tab and made the labels so it's clear all the setting are related to Active Directory; I also placed it at the bottom to avoid a bunch of forum posts in the future "I turned on the Active Directory to see what it did and can no longer log in" :) ):
https://github.com/openemr/openemr/commit/b9f9954e937a60cb9f22e2de89afefa5d67ffe40

**Pull request merged**
