### PR TITLE
Update document class to check for relocated documents folder

### PR DESCRIPTION
**Pull request by mdsupport**
(Adding my tasks to the top of the PR so they don't get lost -matthew)

#### MATTHEW'S TASKS
- [x] Overview http://open-emr.org/wiki/index.php/Templates_for_Patient_Documents
- [x] Test changes with http://open-emr.org/wiki/index.php/Encryption_and_Decryption_of_Documents (this feature appears to be broken... logged a bug here https://github.com/openemr/openemr/issues/482 - your branch doesn't change anything so we're okay)
- [x] Test the changing of `documents.url`
- [x] Test the changing of the install location
- [x] Make sure patient portal isn't affected
- [x] Make sure CouchDB usage isn't affected
- [x] Make sure `This upload tool is only for uploading documents on patients that are not yet entered into the system.` isn't affected via the `Misc` tab
- [x] Make sure this works on Windows
- [x] Make sure this works with multi site

### CODE REVIEW

**Comment by MatthewVita** [comment]
Hi @mdsupport,

I will be reviewing this. Code looks good so far, however, you'll have to be patient with me as I ramp up my knowledge on the documents feature.

I'll want to QA this heavily.

Thanks,

Matthew Vita

**Comment by MatthewVita** [comment]
Hi @mdsupport,

Would setting `$GLOBALS['oer_config']['documents']` to something like `/openemr-data` (which could be another filesystem mount) be a good test?

Thanks
Matthew

**Comment by mdsupport** [comment]
This issue was encountered when we migrated from var/www/emr in old apache to var/www/html/emr.  Document display continued to work as it is 'site' aware but rename functions are not.  For testing, I guess one can play with the documents.url field to simulate the change or have two installations pointing to same database.

Rest of the renaming code is cosmetics.

**Comment by MatthewVita** [comment]
Hi @mdsupport,

Some updates:

- Wanted to let you know that I logged a separate bug with this feature (decryption/encryption) https://github.com/openemr/openemr/issues/482 but it has nothing to do with your PR.
- I installed OpenEMR in `/var/www/openemr` and moved the install to `/var/www/new_openemr/openemr`. It works. Should the `url` entry be updated, however? I noticed it is still saying `file:///var/www/openemr/sites/default/documents/1/test_image`

Thanks,
Matthew

**Comment by mdsupport** [comment]
@MatthewVita, this PR just fixes single issue we encountered. While fixing that issue, developer tried to bring clarity to document renaming scheme as well.  However roi isn't there to fix several conceptual and functional design deficiencies of the documents feature.

To your specific point about Couchdb, we did not test that scenario.  Since couch access uses different fields, we assume it should not be affected.  If you find otherwise, we can add conditional return to that function.

**Comment by MatthewVita** [comment]
@mdsupport sounds good. Also, Couch does use some of the same fields, but it is working just fine per my tests. Good news is all I have to do now is test on my OpenEMR Windows VM before signing off (I'm just going to test with disk-based documents because Couch isn't really meant for Windows).

@bradymiller I've decided to remove these testing tasks from my list as I wasn't getting anywhere with them:
- Make sure `emr_scan_load.plx` isn't affected **
- Make sure Fax dispatch isn't affected ***

** It seems as though `emr_scan_load.plx` is a legacy perl script that I doubt anyone is making use of.

*** I remember grepping the codebase to see where files touched the documents/categories stuff and remember seeing reference to "fax dispatch". However, it doesn't seem like this is a mainline feature (e.g.: not well documented in the wiki) and I doubt that this PR would affect it anyways.

**Comment by MatthewVita** [comment]
@mdsupport Testing complete!

@bradymiller Ready for rebase/merge.

**Comment by bradymiller** [comment]
Nice! Thank you @mdsupport and @MatthewVita . Will bring this into the codebase.

**Pull request merged**
