### PR TITLE
more clean up

### PR DESCRIPTION
**Pull request by stephenwaite**
cleaning up html and a few saved globals

### CODE REVIEW

**Comment by bradymiller** [comment]
Going to bring this into the codebase since the mechanism in the upgrade script is time sensitive(I agree with doing it this way though). I'm going to follow this with some commits (mostly to remove the use of the short php echo tags. we have decided in the past not to do this, but now since we no longer support php 5.4, there is an option to support this now; we should discuss this either on github or on forums first, though).

**Comment by bradymiller** [comment]
nice quick blurb on php short echo tags that can reference this when discuss it:
https://leehblue.com/summary-php-echo-shortcut-tag/

**Comment by bradymiller** [comment]
Here the commits I placed after this:
https://github.com/openemr/openemr/commit/9aab3805508fe95b3898a42b8b51eba77a15a627
https://github.com/openemr/openemr/commit/2e784085026ad2e2fa949c493ef83558063f4b25

thanks for the contribution!
This is looking ready to bring on the bootstrap :)

**Comment by stephenwaite** [comment]
glad to help, thanks for the explanation and tidying up

**Pull request merged**
