### PR TITLE
Obstetrics Form with LMP/EDC calculator

### PR DESCRIPTION
**Pull request by mazdoc**
This is a basic form for use by obstetricians. The difference between this form and the previously submitted forms is that the Last Menstrual Period, Estimated Date of Confinement, and the current gestational age (weeks and days) is automatically calculated once one of the data items is available.

The form was generated with formscript.pl and later edited to remove the table elements from New.php (it was a javascript mess trying to get the field IDs with tables)

Comments, ideas, changes are all welcome

[Obstetrics_Form.zip](https://github.com/openemr/openemr/files/1285890/Obstetrics_Form.zip)

### CODE REVIEW

**Comment by robertdown** [comment]
Hi @mazdoc,

Thanks for the contribution! Just a couple of housekeeping things to get done prior to merging this in.

First, it looks like this branch is pretty far behind the current master; let's get it caught up. I'm gonna ask @bradymiller to comment on how best to get you caught up (He's the go to rebase guru around here). Once we do that, I'll review the new form and bring it in.

Side note for Brady - go ahead and leave the update instructions and then I'll add a public gist for reference so I don't have to bug you next time

**Comment by mazdoc** [comment]
Hello Robert;

Thank you so much for all the help.
I'm still new to GitHub, but I look forward to further collaboration.

Mazen

Mazen Fakih MD








-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v.1.20130820
Comment: http://openpgpjs.org

xsFNBFJoOL8BD/9MGAe6X8TIPMc9lGg7I9uvvCY29qfvm1spaLxRP2LIhK+p
AjevcVaF1VqNcjonqkAuzRQrX/E8aeDvy7GZSInzTy2YMctyeWIhO5HyzjoY
OuJN6f52qxwQ2bNW0uwWZHXFuegifNGYQL4SWxXK7Yx4lEHzNcewzyKozJv+
bRgoHDGcHM4gU916oadRpXKowDVG1KdWPK/971I0+VakgqLx9rQlqnsIxg1H
noRIDFd06f//WJrsHz3/DdjC3+inAaDXfnTA7pBdLX4Z+Ss9KAaFDuh7tOl4
RQhBD6Ixii9UDW3w4/uR6M5LRxlsHab8ZhShksdcsN8nQ3xwFb9szi26t7zo
IBfcC01yKNnJ63pL2oY6p8+WPj5C76wP8EvBeOgr74Enx79N1n/VLIXSBDSW
Kw3f6X0gOMdztBn/xnCfioB1F6RrwsDPN/dxRqZkSjRRt1fsxTY5hKF3udVG
hR/qtgPh2d/teBb/S7iowCKQ2ayjqSer5ymUqrUI7mPumOYI5wxPBC5c2YKt
51ChmgXUyVC4foil9rpuCknTiJxMpGYdYRq0jvejJfEF41uy4Ip/nZtTouqW
iLiRhp6yXbt6wPDwynWe3elvWQA+mzJyqkX4H88w16t6ZTOkq45oktM1kScU
0ZZxEL1KE6NRJW6I2HRTochxnry45bJ+LbCzjQARAQABzSNNYXplbiBGYWtp
aCA8ZmFraWgubWF6ZW5AZ21haWwuY29tPsLBXAQQAQgAEAUCUmg4+gkQOehF
Vy9F56kAADfqD/9AS/zw9xRmrbGsI/aqauOPN82vveq0+fCB5DRZFb0RZb44
tUjAf/D3b+5NPl+jsacaUZMezIAn0WXR7fVfUM6XylGnk0VxcO6D+rJf+D3x
IXJ+/SEIYFlcwIEKEOZT6W2u96e0tQvyQRUkzXVaJbC2i2XQ8o2opj9OaeiI
29OP+tZfeRC0eP4kbZYwOIojdJIt3PZgeEfDC0slmrv8lylAl1IcP5mXDbQX
cyiRcLlDBfrNUYu+9/yw8qghARJeVQ3Hb0rKrdbQkqmX7SCHmTBbNIWbHDOw
22pmq2djJlANfxmL+EfzE45N+HkXudOM2tVHq6cnLDrIWeNaa8mBpaiCJYxE
S4SK7S83YDl9uGH+cNfTWmPkkMlK2VP3h2dZN4JoH5rxgYXBugHsWFwGO9DP
21Pc5hSdf5/H5euSXzHSUTEVLFNC7c4dTbpyYz/SxyltAXG3msyD1pUzrxeq
jU+bNPHwPDJZUSkgGtDfcdNC7pw+4F/S3y9qqtF8hvae+kTELChZPGMC0huu
raDdKc4pHDFphdmQ7Fld9/Oz3KkrkubOU6WH+O2hZL5hP32ZCeAT2gQJSpB1
7k6mx00irrDlX67ryRbbtkFu5NLB+FKY/2jUe88OoNYlGcUCeSktpX8i/7Jf
MUVMrPNXg5zH3akbf+qb5A3R/hiYug4owv7CPw==
=Kx9Y
-----END PGP PUBLIC KEY BLOCK-----

**Comment by bradymiller** [comment]
hi @mazdoc ,

Thanks for the code submission!
Recommend going through the following tutorial (skip the video part) to create your own git/github openemr repo, which is a good first step for learning git/github for OpenEMR:
http://www.open-emr.org/wiki/index.php/Git_for_dummies

To expedite things for your form code, I'll create a branch/PR with your form on it, so folks can review/test it.(then when you have your own openemr github repo, I'll show you how to bring your code into your repo)

-brady

**Comment by bradymiller** [comment]
hi @mazdoc ,

New PR with your code is here:
https://github.com/openemr/openemr/pull/1074

-brady

**Pull request closed without merging**
