### PR TITLE
fix php warnings for Rules

### PR DESCRIPTION
**Pull request by stephenwaite**
#1175

### CODE REVIEW

**Comment by stephenwaite** [comment]
sunday school :)

**Comment by sjpadgett** [comment]
Funny, the only school I haven't been kicked out. :) This looks okay too me. Thanks.

**Comment by bradymiller** [comment]
I think I may of given you bad advice on the need for child __construct. from the php docs:
``````
Note: Parent constructors are not called implicitly if the child class defines a constructor. In order to run a parent constructor, a call to parent::__construct() within the child constructor is required. If the child does not define a constructor then it may be inherited from the parent class just like a normal class method (if it was not declared as private).
``````

**Comment by bradymiller** [comment]
So, I don't think the child class __construct's are needed. sorry :)
(since it's my mistake, I'd be happy to remove them and test them before bringing into codebase; just let me know)

**Comment by sjpadgett** [comment]
@bradymiller Though not necessary, they should not hurt anything and is a reminder for any future work that there is a parent construct in case new development needs a constructor in extended class. If it tests well I would just leave.

**Comment by bradymiller** [comment]
@sjpadgett ,
Sounds good to me. @stephenwaite , can you let us know if it's testing well(if so, then we'll merge this in).
-brady

**Comment by stephenwaite** [comment]
hi @bradymiller, it's testing fine

**Comment by bradymiller** [comment]
@stephenwaite ,
Thanks for the fix! will bring it in now.
-brady

**Pull request merged**
