### PR TITLE
Product Registration doctrine impl

### PR DESCRIPTION
**Pull request by MatthewVita**

### CODE REVIEW

**Comment by MatthewVita** [comment]
@juggernautsei this should be the complete implementation to compare your branch against for the product registration doctrine implementation. I went ahead and put it all together so you can compare your work to it along the way.

Disregard the calendar template stuff that got checked in... oops!

**Comment by bradymiller** [comment]
Just checking if this is a WIP or if it's ready for review :)

**Comment by MatthewVita** [comment]
@bradymiller this _is_ a work-in-progress but it is for @juggernautsei to test out and study. We had a Google Hangout to overview where he is at with his Doctrine learning (he is a fast learner). I simply put this PR together with the complete solution for him to study/verify.

Sherwin, let me know when you are comfortable with this solution.

**Comment by juggernautsei** [comment]
Matthew,
Thanks for your attention and help in this learning curve. I will be able to work on this today and get back to you this afternoon.

**Comment by MatthewVita** [comment]
@juggernautsei Are things "clicking"? Let me know if another Google Hangouts session would be helpful for you.

**Comment by juggernautsei** [comment]
Matthew,

The session was helpful and I am getting finished with a couple of projects
I was working on.
I have some time now to get back to this.

Sherwin

**Comment by MatthewVita** [comment]
Awesome

**Comment by juggernautsei** [comment]
Where do you want me to jump back in? I see you went ahead with the
registration build. Which I would have done the same thing.

I wanted to share with you that in my last project, I am breaking away from
the procedural coding and introducing OOP into my coding practice.
I created and object and retrieved it in my lasting coding project. This
helping you is helping to get me in the mind to build objects and not just
code.

In my last project. I separated sql from frontend display and service so
that I am getting in the habit of this process moving forward.

This is great for my growth as a developer.

What do you want me to model now?

Sherwin

**Comment by MatthewVita** [comment]
> Where do you want me to jump back in? I see you went ahead with the registration build.

This PR is the complete registration solution so that you can compare it with your own. Once you're comfortable with the code, please:

1. Rebase the branch against master
2. Remove accidentally checked in files in `interface/main/calendar/modules/PostCalendar/pntemplates/compiled/...`
3. `git commit --amend --author="Sherwin Gaddis <sherwingaddis@gmail.com>"`
4. Remove "WIP" from this PR, test, and then ask Brady to review

> In my last project. I separated sql from frontend display and service ...

Makes life a lot easier! Awesome!

> What do you want me to model now?

I'm currently working on facilities (will take a long time... LOTs of areas that are affected/need to be tested). @BradyMiller, what do you think would be a good database table/set of related tables for Sherwin to model next?

**Comment by bradymiller** [comment]
@MatthewVita @juggernautsei ,
Two options that should be straightforward to work on for Sherwin are:
1. chart_tracker table
2. amendments/amendments_history tables

**Comment by juggernautsei** [comment]
> This PR is the complete registration solution so that you can compare it with your own. Once you're comfortable with the code, please:

Could you send me a link to this so I can pull down a copy of the code?
$matthew

**Comment by juggernautsei** [comment]
@MatthewVita 

I got through all of the code change you have posted.  The only question I have is that in the post there are changes to the composer files. Do I need to copy those?

**Comment by MatthewVita** [comment]
Hi @bradymiller and @juggernautsei,

Sorry for my lack of responsiveness this week! Been a bit busy.

Sherwin, you'll want to include the changes to the composer files. However, you may want to rebase your branch with master and run the following steps http://www.open-emr.org/wiki/index.php/Composer#Migrating just to be safe.

Thanks,
Matthew

**Comment by juggernautsei** [comment]
No problem. I have been a busy bee as well working on this eRx thing a few other issues with clients. The link you gave me answers a few questions that I had about how to up date  the auto loader. I will attempt to figure out how to rebase my project. That is going to be fun.

**Comment by MatthewVita** [comment]
@bradymiller I caught this branch up with master and I believe it's ready for merging. Please give it a quick smoke test first.

Thanks,
Matthew

**Comment by bradymiller** [comment]
looks good. will bring this into the codebase. we will probably keep flip-flopping on those composer changes depending on who does the update :)

**Comment by bradymiller** [comment]
@MatthewVita ,
On the login screen and the about screen the registration popup is not showing up and getting the following error in the php error log:
``````
[23-Mar-2017 00:13:42 America/Los_Angeles] PHP Fatal error:  Uncaught Error: Call to a member function getRegistrationId() on null in /var/www/openemr/services/product_registration_service.php:55
Stack trace:
#0 /var/www/openemr/interface/product_registration/product_registration_controller.php(47): services\ProductRegistrationService->getProductStatus()
#1 /var/www/openemr/interface/product_registration/product_registration_controller.php(41): ProductRegistrationController->get()
#2 /var/www/openemr/interface/product_registration/product_registration_controller.php(75): ProductRegistrationController->__construct()
#3 {main}
  thrown in /var/www/openemr/services/product_registration_service.php on line 55
``````
OpenEMR is otherwise working fine.

**Comment by MatthewVita** [comment]
Being worked on here: https://github.com/openemr/openemr/issues/584

**Pull request merged**
