### PR TITLE
PHP8 and CCDA

### LINKED ISSUE #4483: Site Id missing from Session Data
### Describe the bug
Either one of our timers is preventing going to log in landing page on a time out or time out is broken.

Instead, the next time after timeout the user tries to go to a page, globals throws the warning.

### PR DESCRIPTION
**Pull request by sjpadgett**
- procedure order php8
- care plan add LOINC code type

Fixes #4483

### CODE REVIEW

**Comment by bradymiller** [comment]
2DV

**Comment by sjpadgett** [comment]
reverted last commit so I can add to my other PR to cherry pick!

**Comment by sjpadgett** [comment]
@bradymiller Do you recall(I know it's been awhile) if CCD were kicked off from CCM or from encounter(Sent to HIE) for referrals and ToC?
Toc are usually based on one encounter where CCD is all. Also, MU2 required on transition of care both CCD and CDA are generated and then recorded in the encounter. Does this sound right?

**Comment by sjpadgett** [comment]
btw: For now on I think we need to implement an incentive policy that if receive 5 ata boys you get a new toaster! 
giphy-downsized

**Comment by stephenwaite** [comment]
toaster

**Comment by sjpadgett** [comment]
Shucks! ya didn't have to!:)

**Comment by sjpadgett** [comment]
Due to fixes to clinical notes form I'm going to merge this. Care plan now has all the required templates for plan types.
Health Concerns is last section I want to further button down to be sure.

Next I'm working on how to send referral and ToC documents. Not seeing that workflow in CCM so may have to write it in!
@adunsulag thought you may want to note this and does vitals cover everything you need now?

**Comment by adunsulag** [comment]
@sjpadgett I'll need to look at my care plan resource, but vitals was already passing all the test cases.  Looking through your code I didn't see anything that would break things on my end.

**Comment by bradymiller** [comment]
signal-2020-11-19-220815

**Pull request merged**
