### PR TITLE
procedure order fix

### PR DESCRIPTION
**Pull request by sjpadgett**
- invalid directory and filename

#### Short description of what this resolves:
initial log file create was invalid and to soon.

#### Changes proposed in this pull request:
conditional to check for valid data before creating initial log file.

### CODE REVIEW

**Comment by sjpadgett** [comment]
I didn't bother testing new order after escaping was done.
I wonder where I got my lazy genes.

**Comment by stephenwaite** [comment]
at the rate you're crafting code how can you find the time to test :)

**Comment by sjpadgett** [comment]
lol well bet @bradymiller gets to grin as escaping caught me with my pants down! guess i'll quit giving grief about escaping...

**Comment by stephenwaite** [comment]
project escaping :) that would be deter many a gsoc hopeful

**Comment by sjpadgett** [comment]
at least Brady's polite about it! I just ignore it!:)

**Comment by sjpadgett** [comment]
bringing in so I can show off my goof!:)

**Pull request merged**
