### PR TITLE
PHP8 fixes

### PR DESCRIPTION
**Pull request by bradymiller**
work in progress

### CODE REVIEW

**Comment by bradymiller** [comment]
goodness, billing engine changes for php8 is nearing torture :)

**Comment by stephenwaite** [comment]
ugh, thanks for tackling, should have helped with this

**Comment by bradymiller** [comment]
testing well and bringing in. @stephenwaite , if you can, test out billing some (should be fine, but my billing testing was pretty basic).

**Comment by stephenwaite** [comment]
almost forgot, thank you @bradymiller for the contrib!
88220254-ba0afc00-cc30-11ea-9dd4-503ca1172e0e

**Pull request merged**
