### PR TITLE
Portal Secure Messaging Audits

### PR DESCRIPTION
**Pull request by sjpadgett**
- log message soft delete to audit logs
- fix eob search for All alerts
- cleanup dependencies.

### CODE REVIEW

**Comment by sjpadgett** [comment]
git has been weird last day or so. travis isn't running on this PR.

**Comment by bradymiller** [comment]
yep, looks like things are almost fixed on github: https://status.github.com/messages

**Comment by bradymiller** [comment]
(it appears there is a lag in stuff happening/registering with the PR's, so in time it should appear on list and get checked by travis)

**Comment by bradymiller** [comment]
hi Jerry,
This code looks good to me.
-brady

**Pull request merged**
