### PR TITLE
502 portal

### PR DESCRIPTION
**Pull request by sjpadgett**
Fixes #
Don't want to say!
#### Short description of what this resolves:
Stuff

#### Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller Why the heck is those 8 prior commits following me around. My locals are clean. Last time I did 502 PR had same thing.
Also, need to get rid of the enlarged titles in PR template!

**Comment by bradymiller** [comment]
try following on git:
git checkout upstream/rel-502
git checkout -b 502-portal-good
git cherry-pick a238b18a8ce129239e62b32e631f607868b68014

Now you should have a good branch on 502-portal-good with your commit to make a PR from.

For PR template, feel free to just delete it especially for this kind of stuff.

**Comment by sjpadgett** [comment]
All those commits are already in 502 branch. I put them there couple months ago.

**Comment by bradymiller** [comment]
Agreed. The only commit that is new here is the a238b18a8ce129239e62b32e631f607868b68014 , so above is basically going to pluck it out and place it on top of the official rel-502 branch. The reason this is likely happening is either a github artifact bug or that the commit sha1 are not the same.

**Comment by sjpadgett** [comment]
hmm, okay. I'll redo my 502 branch. thanks.
bringing this to 503 now

**Comment by bradymiller** [comment]
I'll do the github rain dance to ensure it works for you:

rain-dance

**Comment by sjpadgett** [comment]
I'd say you've too much time on your hands but, I know better:)

**Pull request merged**
