### PR TITLE
Updated stylesheets plus new style help

### PR DESCRIPTION
**Pull request by zbig01**
Stylesheets using new styleguide
fixed minor styling issues in style_manila.css and style_light.css
added new style help files

### CODE REVIEW

**Comment by zbig01** [comment]
@bradymiller 
I created this PR to let you checkout how the new stylesheets and the new help files work

**Comment by zbig01** [comment]
This PR also contains the correct themes directory

**Comment by zbig01** [comment]
@bradymiller 
When you bring this PR in please bring the themes in from this PR otherwise the cflatstylesheets will be missing the styling needed for the help files, flowboard etc. 
Thanks

**Comment by bradymiller** [comment]
hi @zbig01 ,
But there is nothing new in the scss scripts here compared to what I just brought into the codebase???
(or is there?)
-brady

**Comment by zbig01** [comment]
@bradymiller

This is getting more confusing. Let me submit a new PR that has only the themes directory changes. You can then see the changes. They should reflect the addition of oe-common to the color_base.scss and to oe-help.scss

**Comment by bradymiller** [comment]
@zbig01 ,
When there are conflicts and lots of merges, github review/diff basically breaks and shows changes that are not really changes. Making another PR based on most recent codebase would be ideal (if needed, I can also "sort" it out, but its getting more complicated as you add more commits).
-brady

**Comment by zbig01** [comment]
@bradymiller 
I do not want to complicate this situation. If you give the go ahead I will sumbit a new PR bades on the latest master.

**Comment by bradymiller** [comment]
hi @zbig01 ,

Things got really messy, but got it sorted out here:
https://github.com/openemr/openemr/pull/1690

We shouldn't be in this position again, so figured you shouldn't go through the pain of sorting this out (in case you are curious, I basically started on master, copied in your changes to the scss scripts, ran npm run build twice (need to run twice to process the rtl scripts for some reason), then copied in the files with your help work. fun, fun, fun :)

-brady

**Comment by bradymiller** [comment]
This code was brought in via the above PR, so closing this PR.

**Pull request closed without merging**
