### PR TITLE
CCDA Testing fixes and prior commit conflicts

### PR DESCRIPTION
**Pull request by sjpadgett**
Fixes #

#### Short description of what this resolves:
Not too sure but looks like a prior commit change got by me.

### CODE REVIEW

**Comment by sjpadgett** [comment]
This is working for me on windows but I fear issues with linux. will merge so can test on demo

**Comment by sjpadgett** [comment]
@bradymiller if you can test it'd be great.

**Comment by bradymiller** [comment]
hi @sjpadgett ,
Still unable to import ccda's with these changes. see here for more details on issue:
https://github.com/openemr/openemr/issues/5903

**Comment by bradymiller** [comment]
fyi, regarding ccda creation, though, that is working (and it also included the unstructured document when requested that)

**Comment by sjpadgett** [comment]
Can you import the create zip from export?
I'm only concerned with import from gui right now.

**Comment by bradymiller** [comment]
also not working, but that gives following errors in the php error log:
```
[Thu Nov 03 00:45:23.298939 2022] [php:notice] [pid 898] [client 172.21.0.1:38136] [2022-11-03T00:45:23.298197+00:00] OpenEMR.ERROR: File in zip is CCDA_Patient_Documents_1667435844/ [] [], referer: http://localhost:8300/interface/modules/zend_modules/public/carecoordination/upload?id=1
[Thu Nov 03 00:45:23.299000 2022] [php:notice] [pid 898] [client 172.21.0.1:38136] [2022-11-03T00:45:23.298969+00:00] OpenEMR.ERROR: File in zip is CCDA_Patient_Documents_1667435844/CDA.xsl [] [], referer: http://localhost:8300/interface/modules/zend_modules/public/carecoordination/upload?id=1
[Thu Nov 03 00:45:23.299044 2022] [php:notice] [pid 898] [client 172.21.0.1:38136] [2022-11-03T00:45:23.299017+00:00] OpenEMR.ERROR: File in zip is CCDA_Patient_Documents_1667435844/CCDA_Sdf_Sdf_ccd_2022_11_03_003724.xml [] [], referer: http://localhost:8300/interface/modules/zend_modules/public/carecoordination/upload?id=1
[Thu Nov 03 00:45:23.299086 2022] [php:notice] [pid 898] [client 172.21.0.1:38136] [2022-11-03T00:45:23.299059+00:00] OpenEMR.ERROR: File in zip is CCDA_Patient_Documents_1667435844/CCDA_Sdf_Sdf_ccd_2022_11_03_003724.html [] [], referer: http://localhost:8300/interface/modules/zend_modules/public/carecoordination/upload?id=1
[Thu Nov 03 00:45:23.299125 2022] [php:notice] [pid 898] [client 172.21.0.1:38136] [2022-11-03T00:45:23.299099+00:00] OpenEMR.ERROR: File in zip is CCDA_Patient_Documents_1667435844/CCDA_Sdf_Sdf_unstructured_2022_11_03_003724.xml [] [], referer: http://localhost:8300/interface/modules/zend_modules/public/carecoordination/upload?id=1
```

**Comment by bradymiller** [comment]
to clarify, the 'Virginia Klein" ccda (in xml form) is also not working on the gui import, however it is not creating any error in the php error log.

**Comment by sjpadgett** [comment]
That really info for what files to be imported.
We must be getting import errors that are not bubbling up. Exceptions do that in CCM and is quite frustrating.
You have to set breakpoints and step to trap them.
All works on windows so must be a path issue or missing a dependency

**Comment by sjpadgett** [comment]
Can you set break at L-187 interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php 
and step through?

**Comment by bradymiller** [comment]
did some quick breakpoint galore (appears to be dying at line 197 and not getting to the catch, so seem like something else is going on that is catching it and dying):
image

gotta go for a bit but will get back at it later tonight

**Comment by sjpadgett** [comment]
Okay. Try stepping into $xmltoarray->fromString($xml_content_new) see if that's the issue where linux may act differently to the flags for node size.
If that's the case then I may be screwed!

**Comment by sjpadgett** [comment]
@bradymiller try to set my.ini setting `max_allowed_packet` to higher value maybe 100MB

**Pull request merged**
