### PR TITLE
migrate dev environments and primary testing environments to php8

### PR DESCRIPTION
**Pull request by bradymiller**
migrate dev environments and primary testing environments to php8

### CODE REVIEW

**Comment by bradymiller** [comment]
to help with https://github.com/openemr/openemr/issues/4482

**Comment by bradymiller** [comment]
fingers crossed that testing does not explode :)

**Comment by sjpadgett** [comment]
don't have a fingers crossed gif..

**Comment by bradymiller** [comment]
@sjpadgett , was going old school text :)

**Comment by bradymiller** [comment]
bringing in. on to the glorious world of php 8 :)

**Comment by stephenwaite** [comment]
compete

**Pull request merged**
