### PR TITLE
Extend the JS validation to support dd/mm/YYYY format 

### PR DESCRIPTION
**Pull request by eyalvo-matrix**
This commit add the option to validate dates in format dd/mm/YYYY format  with the pastDate function 
by editing the  LBF_Validations and changing it to 
{"pastDate":{"message":"must be past date","format":"2"}}

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @eyalvo-matrix ,
Rather than force manual setting of the format, can't this automated depending on the user's global choice as is done here: https://github.com/openemr/openemr/blob/master/library/formatting.inc.php#L169
(use case: 1 openemr instance will be used by different users with different date format settings)
-brady

**Comment by eyalvo-matrix** [comment]
hi @bradymiller  , I really prefer what you have suggested , I thought about the exact thing too :) 
but how can I have access to the global variable in a pure JS file ?

**Comment by bradymiller** [comment]
hi @eyalvo-matrix , Can't you set a variable in php before you include this JS script?

**Comment by eyalvo-matrix** [comment]
hi @bradymiller  thank you for your replay 
I don't see a simple way to do that since the validation function is called from the database
{"pastDate":{"message":"must be past date","format":"2"}}

**Comment by eyalvo-matrix** [comment]
The only way I can currently think of to get the php date format 
 is to do an ajax call to the server inside the validation 
but since the users are configuring the validation manually anyhow 
is it necessary ?

**Comment by bradymiller** [comment]
hi @eyalvo-matrix ,
Which php scripts are bringing in this js library, though?
Before bringing in this js library in the php script, could set a js variable.
(and ajax from js is not an option since can't ensure it will be returned before running the following js code since the asynchronous thing is in process of being deprecated and not supported by browsers in the future)
-brady

**Comment by sjpadgett** [comment]
Think you mean synchronous, however, you could use a defer/promise to run the needed js code after the var is fetched or like you say set the global js var from php.

**Comment by eyalvo-matrix** [comment]
@sjpadgett  and @bradymiller , How about some thing like this ? 
I changed the code a little bit, now you do not need to change the sql

**Comment by bradymiller** [comment]
hi @eyalvo-matrix , This looks good and I assume you've tested it. Will bring it into the codebase. -brady

**Pull request merged**
