### PR TITLE
add os x support for tmp folder

### PR DESCRIPTION
**Pull request by stephenwaite**
tested with xampp for os x

### CODE REVIEW

**Comment by robertdown** [comment]
Does this affect XAMPP only, or all OS X installs? This wouldn't work if you're installing on OS X but using their built-in Apache/PHP or if using homebrew

**Comment by stephenwaite** [comment]
good pt, didn't know they had built in and forgot about homebrew;  they probably use the same temp folder though so could pare it down to that and the bin path, thanks Robert

**Comment by bradymiller** [comment]
Hi,
For windows, we just took strategy of just supporting the paths for xampp by default since this was the most popular way to install on windows (and other users could just modify it as needed). Recommend taking the same strategy for OSX and bringing in stephen's changes as is.
-brady

**Comment by bradymiller** [comment]
ok to bring this in?

**Comment by robertdown** [comment]
OS X has PHP and Apache installed by default - forcing defaults to XAMPP is not something I'd recommend. Should have some kind of config file that allows users to update easily (Not even just on OS X, but on all platforms...)

**Comment by stephenwaite** [comment]
if that's the case should we recommend the linux type install and then update the Darwin section appropriately?

**Comment by robertdown** [comment]
Probably? I'd need to investigate the actual code a bit more

**Comment by bobinson** [comment]
/usr/local/bin/mysql ---> this is the binary location for homebrew based install. FYI.

**Comment by bobinson** [comment]
I cooked up a installation script (copied and modified to be precise) & its [here](https://github.com/bobinson/OpenEMR-on-macOS) with instructions.  Note that its not tested extensively.

- The script assumes its running on macOS (TODO)
- the script assumes that home brew is used to install apache and PHP (TODO)

**Comment by bradymiller** [comment]
Nice @bobinson , this would be a nice thing to link to from the wiki (maybe development version install section). If your interested, can submit request for account here which I'll gladly verify:
http://www.open-emr.org/wiki/index.php/Special:RequestAccount

**Comment by bobinson** [comment]
@bradymiller thanks :) and I have requested for access in the wiki.

PS: I would recommend that someone is helping with alpha testing the script.

**Comment by stephenwaite** [comment]
hi, i'd be glad to test it out @bobinson :)

**Comment by bobinson** [comment]
@stephenwaite fingers crossed!

**Comment by stephenwaite** [comment]
thanks for the easy to follow setup, should the command be `git init` after you `cd into hack/code`?

**Comment by stephenwaite** [comment]
do you install mysqladmin with brew too?

**Comment by bobinson** [comment]
@stephenwaite no, its part of the mariadb package

see below:

```
brew ls mariadb | grep admin
/usr/local/Cellar/mariadb/10.1.22/bin/mysqladmin
```

**Comment by stephenwaite** [comment]
thanks @bobinson , then probably need to add the mariadb to the brew setup section of the instructions

**Comment by bobinson** [comment]
@stephenwaite thank you! Since it was already installed on my system I missed it.

**Comment by stephenwaite** [comment]
hi @bobinson, refresh_OpenEMR.sh is a nice little script, just have to change the user name maybe could use a hardcoded env variable?

also need to show how to add directory block in the httpd.conf or mkdir sites-available and include to set up openemr directory which are obvious to os x developers who use homebrew, can understand why @bradymiller suggested this as a dev install wiki 

probably should add install instructions for the already integrated apache on the download page for basic users as @robertdown recommended

**Comment by bobinson** [comment]
@stephenwaite -

> 1.  just have to change the user name maybe could use a hardcoded env variable?


If you meant the users for apache, its handled with the following variables. I will add necessary comments to make it clear.

APACHE_USER=b5413b
APACHE_GROUP=admin

2. 
> also need to show how to add directory block in the httpd.conf or mkdir sites-available and include to set up openemr directory which are obvious to os x developers who use homebrew, can understand why @bradymiller suggested this as a dev install wiki

I found a sample under the following path

[openemr/contrib/util/ubuntu_package_scripts/production/openemr.conf](https://github.com/bobinson/openemr/tree/master/contrib/util/ubuntu_package_scripts)
I will try to incorporate this.

3. >  already integrated apache

Will handle this along with item 2.

Just need to fight my procrastination now !

**Comment by stephenwaite** [comment]
cool, thanks @bobinson, you've got momentum now :)
for the APACHE_USER i was thinking $USER if i catch the drift

**Comment by bobinson** [comment]
@stephenwaite I added some comments + some of your suggestions in the revision.

The reasoning behind mentioning APACHE_USER and APACHE_GROUP is that since we will be using this for development mostly, its better to give the logged in Mac user to have permission to edit files on the fly if needed. Also Home brew uses the same permissions - so any change under /usr/local becomes possible without other permissions issues.

What you think about the above ?

**Comment by bobinson** [comment]
@stephenwaite  added some more changes just now and they are here : https://github.com/bobinson/OpenEMR-on-macOS

CHANGELOG:

- removed requirement to hard code user name
- now user name is picked from $LOGNAME environment variable
- tweaked README

**Comment by stephenwaite** [comment]
thanks i'll check it out this weekend

**Comment by stephenwaite** [comment]
Hi @bobinson, having an issue getting php to run in Apache , even though it states that the mod is loaded and it's running on restart with httpd it won't load a simple php info script under localhost.  Is there an additional setting in httpd.conf?

**Comment by stephenwaite** [comment]
found a nice article to assist, [https://getgrav.org/blogmacos-sierra-apache-multiple-php-versions](url)
found the needed`<IfModule dir_module>
    DirectoryIndex index.php index.html
</IfModule>

<FilesMatch \.php$>
    SetHandler application/x-httpd-php
</FilesMatch>
`

**Comment by stephenwaite** [comment]
hi @bobinson, reinstalled and have a working openemr now :)

**Comment by bradymiller** [comment]
@stephenwaite ,
Been doing a sweep through PR's and noted this one. thoughts on this one?
thanks, -brady

**Comment by stephenwaite** [comment]
sorry this turned into a 3 headed monster since could install on mac via xampp, apache or homebrew.  maybe could make a wiki page with @bobinson 's above advice and scripting ?

**Comment by stephenwaite** [comment]
installed on mac recently and it wasn't tres difficile, one of the only differences is default webroot of `/Library/Documents/Webserver`

**Pull request closed without merging**
