### PR TITLE
Change JS functions for browsers compatibility (edit_list.php)

### PR DESCRIPTION
**Pull request by matrix-amiel**
Hi.

Here I replace some new js functions with old functions  for an IE compatibility  )-:

Thanks

Amiel

### CODE REVIEW

**Comment by sjpadgett** [comment]
Hi @matrix-amiel ,
I know you guys like to use I.E. Do you have a set min version ie 11?

**Comment by matrix-amiel** [comment]
We hate.. our customers like.. )-:

Yes IE11 doesn't support `new URL`

**Comment by bradymiller** [comment]
hi @matrix-amiel , I assumed we broke IE11 in other places, which sounds like is not yet the case. Is this only place where IE11 breaks?

**Comment by matrix-amiel** [comment]
Hi @bradymiller 

We didn't find more bugs with IE11.
Our customers working with IE well..

**Comment by bradymiller** [comment]
hi @matrix-amiel ,
Code looks good. Just let me know that it's testing well for you and then I'll bring it into codebase. -brady

**Comment by matrix-amiel** [comment]
Yes. It's working well

Thank you

**Comment by bradymiller** [comment]
hi @matrix-amiel , bringing in now then. thanks for the fix! -brady

**Pull request merged**
