### PR TITLE
Newcrop diagnois only active

### PR DESCRIPTION
**Pull request by kchapple**
#### Short description of what this resolves:

We should only be sending active diagnosis to newcrop, not all

### CODE REVIEW

**Comment by sjpadgett** [comment]
Oh my goodness, It's our old friend Ken!
I thought for sure we lost you to those evil proprietary developers or your band had gone full time....

**Comment by sjpadgett** [comment]
BTW: Harly does a great job on the forum

**Comment by kchapple** [comment]
Not rid of me yet!

Might be a "problem" with this PR because I changed a couple .inc.php back to .inc to backport to openemr 7.0. The files are still there in this code base, but you guys are obviously trying to git rid of those .inc files.

**Comment by bradymiller** [comment]
hi @kchapple , yep, just need to add back the .php extensions and then this looks good to me.

**Pull request merged**
