### PR TITLE
Refactor: remove unnecessary oe classes.

### PR DESCRIPTION
**Pull request by stu01509**
Remove unnecessary `oe` classes.

#### Short description of what this resolves:
In this PR,  remove the 
- oe-opt-btn-separate-left
- oe-opt-btn-group-pinch
- btn-group-pinch
- btn-separate-left

And convert the `oe-text-to-right`, `oe-text-to-left` to Bootstrap classes
- text-left
- text-right

### CODE REVIEW

**Comment by tywrenn** [comment]
@stu01509 Do btn-group-pinch and btn-separate-left actually do anything? xD

**Comment by stu01509** [comment]
Hey @tywrenn 

The `btn-separate-left ` do `margin-left: 20px`, and the `btn-group-pinch ` to be honest, I still not know its effect lol.
I guess it is an outdated style, has been removed, just not remove fully.

**Comment by tywrenn** [comment]
@stu01509 You can go a step further and remove the references found in `/interface/themes/core/text.scss` any other references you can find.

**Comment by stu01509** [comment]
Hi @tywrenn 

Finally, I removed the
 `oe-text-to-right` and `oe-text-to-left` in `/interface/themes/core/text.scss`,

`oe-opt-btn-separate-left`, `oe-opt-btn-group-pinch`, `btn-group-pinch` and `btn-separate-left` in `interface/themes/colors/utilities/bootstrap.scss`

Also,  `oe-text-to-right` and `oe-text-to-left`  are still in `rtl_style_pdf.css ` file, not sure should I remove it?

**Comment by tywrenn** [comment]
@stu01509 if it's removed out of existence you can remove it there as well lol

**Comment by stu01509** [comment]
@tywrenn  Updated the commit. Please review it again.

**Comment by tywrenn** [comment]
In `interface/README.md`, remove line 25, 26, 27 and 28.

In `interface/billing/billing_report.php` at line 119 you'll need to find a way to remove that.

**Comment by stu01509** [comment]
Update the commit.

**Comment by bradymiller** [comment]
hi @stu01509 , Bringing in. Thanks for the improvements! -brady

**Pull request merged**
