### PR TITLE
fix: remove dynamic properties from the crypto class

### PR DESCRIPTION
**Pull request by bradymiller**
fix: remove dynamic properties from the crypto class

### CODE REVIEW

**Comment by stephenwaite** [comment]
seal-dunk

**Comment by sjpadgett** [comment]
@bradymiller 
I added this fix in my PR and removed my now unnecessary comments.
I'm also testing as Brads modules are unrulily with some flooding of this exception but haven't found how I get in trouble yet!

So if you're okay with me just merging fix in my PR and close this one we can do that or if not no biggie!

**Comment by bradymiller** [comment]
hi @sjpadgett , Definitely feel free to bring this commit into your PR (when it's there I'll close this PR).  thanks!

**Comment by bradymiller** [comment]
oops, already closed it :)

**Comment by sjpadgett** [comment]
Will commit in a few minutes.

**Pull request closed without merging**
