### PR TITLE
see what happens (trying google cloud build ci)

### PR DESCRIPTION
**Pull request by bradymiller**
just testing something out

### CODE REVIEW

**Comment by danehrlich1** [comment]
See a cool part about this is by using the runners for NPM and Composer you can leave them out of the final build. A smaller leaner more secured image.

**Comment by danehrlich1** [comment]
Yeah and look @bradymiller your thing works when you put CloudBuild.yaml at the very top of the repo

**Comment by bradymiller** [comment]
Note this is why the PR's are not getting tested on github:
https://github.com/GoogleCloudPlatform/cloud-builders/issues/380

**Comment by bradymiller** [comment]
According to this, placing the file CloudBuild.yaml at top means should get triggered (in theory) on github PR and new commit into repo; however the PR is basically not working per above link (a bummer) without needing to set up triggers in GCP: https://developer.github.com/v3/checks/

**Comment by bradymiller** [comment]
interesting, now the Google Build check is showing on this PR also. I am so confused :)
Will play around with this more tomorrow.

**Comment by bradymiller** [comment]
Going to bring this into the codebase as more of a placemarker so we don't get that ugly red x on the commits. Working on bringing up a flex docker that will use the actual codebase in the PR/commit. This is some really cool stuff.

**Pull request merged**
