### PR TITLE
zip needs flags on php 7.1?

### PR DESCRIPTION
**Pull request by stephenwaite**
at least it did on aws express package running 7.1.17

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @stephenwaite ,
Does this throw a warning or break entirely? Also may be other places in codebase that need fixing.

**Comment by sjpadgett** [comment]
I know it seems like(or maybe I do) nitpicking but while it appears these flags may not be case sensitive, they are class constants.  I'd error on safe side and use as documented eg ZipArchive::OVERWRITE etc.
I'm not sure if an issue but, I couldn't help myself from mentioning.

**Comment by stephenwaite** [comment]
Hi @bradymiller , it breaks entirely. Hi @sjpadgett, be glad to follow your advice :)

**Comment by bradymiller** [comment]
hi @stephenwaite , Code looks good and bringing into codebase. Thanks for he fixes! -brady

**Comment by stephenwaite** [comment]
looks like i had a bad zip file which led to this but upon testing this change works fine, will think about @sjpadgett 's  [comment](https://community.open-emr.org/t/icd-10-2019-unsupported-database-load-file/11554/21) some more

**Pull request merged**
