### PR TITLE
Ev/cdr wildcard

### PR DESCRIPTION
**Pull request by eyalvo-matrix**
Happy new year to all !! 

This small change to the CDR 
allows entering a wild card in the value field of the demographics filter criteria
The wild card is #CURDATE# and it is replaced with the value of date("Y-m-d")
By doing so we can create a dynamic date filter criteria
I added this because we need it  
and I can not reproduce the same functunality with the current CDR  
I think it will be useful to others too

Eyal

### CODE REVIEW

**Comment by mdsupport** [comment]
@eyalvo-matrix, if you are creating your own rules, you will see lot more flexibility and better performance by using database views.

@bradymiller, gentle reminder about [ticket#263](https://sourceforge.net/p/openemr/code-review/263/).

**Comment by bradymiller** [comment]
@mdsupport , thanks for the reminder on that code. I lost track of that one and will place it at top of queue. I keep a list here (to maintain my sanity); just let me know if anything else is missing from the list:
http://www.bradymd.com/todo/#openemr-code-reviews

**Comment by eyalvo-matrix** [comment]
Thanks for the replay ,
Does ticket#263 has a wild card for daily date ?

**Comment by mdsupport** [comment]
# @eyalvo-matrix, 263 is unrelated to your change.  Your PR triggered a reminder of that dormant ticket.  
Sorry to hijack your thread.

**Comment by bradymiller** [comment]
@eyalvo-matrix ,
Just brought your code into the codebase and thanks for the contribution!
(I followed your commit with a small commit to add this feature to the functions comments)

@mdsupport ,
While I was integrating your code into the more recent codebase, I realized there was an issue, which I reported on github/sourceforge.

**Comment by eyalvo-matrix** [comment]
Thanks @mdsupport I will try that :)

**Pull request merged**
