### PR TITLE
Google Sign-on allows user to select email address from within GSuite…

### PR DESCRIPTION
**Pull request by growlingflea**
… organization and use that to

sign in as long as email address is recorded in Administration->users Google sign-in field. User must
configure Google credentials and put Google ID in Administration->Globals connectors.

Fixes #

### CODE REVIEW

**Comment by sunsetsystems** [comment]
I see a couple of references to apis.google.com ... some installations might not have access to the outside world, so all code should be local.

Also please make sure U2F and TOTP still work with this.

**Comment by sjpadgett** [comment]
I'm sorry, not sure I like this! Are we next going to embed Facebook or Git or Amazon etc.
This needs to be more universal and a plug in rather than embedded in our login(embed a hook maybe).

If a third party identity is used, then hook to an adapter or plugin. Build an interface object that will then accept different identity providers with google an example.

**Comment by kchapple** [comment]
@growlingflea this is also the wrong branch you created the pull request from. This needs to be closed and re-submitted.

@sunsetsystems 
> so all code should be local.
If the system can't access the google API, there is a message shown. This was tested with no internet, and with google being blocked by a firewall. 

@sjpadgett 
> I'm sorry, not sure I like this! Are we next going to embed Facebook or Git or Amazon etc.
> This needs to be more universal and a plug in rather than embedded in our login(embed a hook maybe).
I'm not sure those other 3rd party providers offer a BAA as google does with their business workspace accounts. We were only tasked to implement Google, and I ran this by @bradymiller before we started the work. Perhaps if folks ask for other 3rd party auth-providers down the road, we could refactor it, but right now we don't have the time to research and test integrations with multiple platforms and make sure a generic interface will work with all of them.

Ken

**Comment by kchapple** [comment]
@sjpadgett If it has to be a module, we can put in hooks instead. We thought this would make many users' lives easier and it would be easier to access if it was in the core.

**Comment by kchapple** [comment]
@bradymiller you don't need to start a review on this. It's the wrong branch, and sounds like we're getting some pushback on the implementation anyways.

**Comment by bradymiller** [comment]
@kchapple , @growlingflea , @sjpadgett ,

Definitely repost this PR from the correct branch so I can review/test this feature. This doesn't look like a generic single sign on, but instead looks like something comparable to ldap (ie. organization of certain google workspace (aka G suite) users are allowed automatic sign in access), which would be a powerful (and easier/safer to manage than ldap) single sign in mechanism for larger organization/enterprise support that they can incorporate into all their software tools including OpenEMR especially if offers BAA.

**Comment by bradymiller** [comment]
on a completely unrelated note, @sunsetsystems , I wonder what it would take to support an option for mfa (totp and u2f) to have checkbox option to identify the computer and not need to relogin to mfa every time (looks like it is standard to give option of 30 days)

**Comment by sjpadgett** [comment]
This is what oauth and openid connect is all about! Why we worked so hard to have our own identity server.
Though configured for API currently, our identity workflow could still be configured for third party identities.
Since we already establish trusted users for API, it'd just be a matter of provisioning other providers.

We'd have a signin client for openemr login the same as for apis. This client would/could handle single sign in or two/three legged authentication including identity.

We do this already with MFA, which I really like, and proved to be a pretty easy integration.

This has been part of my plan all along. That is, to provide oauth login for openemr but, using our identity server.
Afterall, just because someone specify google, what they really want is the convenience of an oauth/openid connect login. 

I'm truly not trying to upset the apple cart but instead, I think there is a better way of doing this. More conducive to expanding the feature in the future.

**Comment by sunsetsystems** [comment]
> on a completely unrelated note, @sunsetsystems , I wonder what it would take to support an option for mfa (totp and u2f) to have checkbox option to identify the computer and not need to relogin to mfa every time (looks like it is standard to give option of 30 days)

Definitely sounds like a useful improvement!

**Comment by sjpadgett** [comment]
agin that's what an oauth login provides!

**Pull request closed without merging**
