### PR TITLE
Users in reports (optional)

### PR DESCRIPTION
**Pull request by sharonco-matrix**
We need a flag in order to know if the user needs to be part of the reports or not.
For example if there is a report  on how many patients a provider saw. Then the staff (secretary) wont be a part of reports

### CODE REVIEW

**Comment by bradymiller** [comment]
Doesn't the Provider selector work for this?

**Comment by sharonco-matrix** [comment]
@bradymiller the problem is that removing the provider also removes the calendar.
Its important for us to be a user that has almost all the privileges but he doesn't appear in the reports.
If you have another idea we will be happy to hear

**Comment by bradymiller** [comment]
@sharonco-matrix ,
In user, there are currently the following checkbox flags:
Provider
Calendar

So you should be able to remove the calendar and still have set as a provider.(do not that you can't do opposite, though, where set calendar and not provider)

Perhaps another checkbox flag of Reporting(which follows same logic as calendar where it is autoselected when click provider and requires provider to be selected). However, need to have a good idea what you mean regarding reporting? There are just so many different types of reporting, need to have a good idea what you are shooting for to figure out ideal solution.

**Comment by bradymiller** [comment]
To illustrate, the Patient Flow Board is basically a customized report. So, if not reportable, does it also mean not reportable here?

**Comment by bradymiller** [comment]
I realized there may of been confusion in the Provider Selector I brought up above. I was referencing in the reports where you can choose which Providers to include via the selector.

**Pull request closed without merging**
