### PR TITLE
couchdb updates

### PR DESCRIPTION
**Pull request by bradymiller**
next on the agenda after this is to:
1. fix up the thumbnails module to work with encryption (pretty sure it is broken by just reading the code)
2. finish up https://github.com/openemr/openemr/issues/2181

TODO:
update composer lock

### CODE REVIEW

**Comment by bradymiller** [comment]
Note adding this is a bit of a false sense of security, since the value can be easily picked up in the value attribute. The main security for these items that already exists is they are encrypted on the database end.

**Comment by bradymiller** [comment]
oops, above comment is in wrong PR, gonna remove it.

**Comment by tywrenn** [comment]
Breaking flex docker again? xD

**Comment by tywrenn** [comment]
@bradymiller Unfortunately u broke all the flex dockers by just adding this one feature

**Comment by bradymiller** [comment]
hi @tywrenn , this PR is not yet in codebase.

Do you mean this update:
https://community.open-emr.org/t/openemr-flex-docker-updated/12051/66

If so, did you update the docker (`docker pull openemr/openemr:flex`) and are you using most recent codebase?

**Comment by tywrenn** [comment]
@bradymiller Yep I pulled the most recent update and it kept spitting out a couchdb error -- let me get that error for you real quick

**Comment by tywrenn** [comment]
@bradymiller 
`couchdb_1     | [notice] 2020-08-10T02:46:23.422143Z nonode@nohost <0.342.0> -------- chttpd_auth_cache changes listener died because the _users database does not exist. Create the database to silence this notice.
couchdb_1     | [error] 2020-08-10T02:46:23.422920Z nonode@nohost emulator -------- Error in process <0.481.0> with exit value:
couchdb_1     | {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,374}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,403}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,96}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,145}]}]}
couchdb_1     | 
couchdb_1     | [notice] 2020-08-10T02:46:23.428335Z nonode@nohost <0.364.0> -------- couch_replicator_clustering : cluster stable
couchdb_1     | [notice] 2020-08-10T02:46:23.435750Z nonode@nohost <0.374.0> -------- Started replicator db changes listener <0.482.0>
couchdb_1     | [info] 2020-08-10T02:46:23.446645Z nonode@nohost <0.484.0> -------- open_result error {not_found,no_db_file} for _replicator
`

**Comment by bradymiller** [comment]
hi @tywrenn , Assuming that OpenEMR is working ok, can ignore that (just couchdb docker log stuff). Can avoid seeing that stuff by using `-d` parameter (`docker-compose up -d`)

**Comment by bradymiller** [comment]
testing well and bringing in after passing travis. regarding the couchdb docker error logging, that is a separate issue and will look into why that is happening.

**Pull request merged**
