### PR TITLE
fontawesome fixes

### PR DESCRIPTION
**Pull request by bradymiller**
I noted the spinner pulse fontawesome icon was not working in setup.php since need to update the new fontawesome 5 path. Also updated this on the other places where it is needed.

### CODE REVIEW

**Comment by tywrenn** [comment]
We shouldn't have these references...or should at least create a way to use core headers here for consistency sake.

**Comment by bradymiller** [comment]
@tywrenn , Are you suggesting I fix the disease rather than just the symptom? :)

tenor (14)

**Comment by tywrenn** [comment]
@bradymiller It's a very cancerous disease that breaks all code in it's path if not taken cared for 😂

**Comment by stu01509** [comment]
Is possible integration to the `FontAwesome.scss`?

**Comment by tywrenn** [comment]
@bradymiller Way to fix this:

Add this before html declaration in ALL help files:
`use OpenEMR\Core\Header;

// Don't use auth in help files
$ignoreAuth = true;

require_once("../../interface/globals.php");`

Add core header declaration after head tag:
`<?php Header::setupHeader(); ?>`


I just realized all the help files aren't ignoring the auth -- this can be an issue as some people don't login to view the help files.

**Comment by bradymiller** [comment]
These aren't as straightforward as they appear, since unable to get globals.php context in the ones that are running when:
1. no database yet
2. sites/* agnostic (like the admin.php script)

**Comment by tywrenn** [comment]
@bradymiller We can probably just not include globals...?

**Comment by bradymiller** [comment]
@tywrenn , It is kind of all or nothing with globals.php. To encapsulate these, we'd likely need to set up a wonky type Header function that we could import the needed globals into and just bring in autoloaded classes. But this wouldn't be ideal since you can never really predict which globals it will need. We may need to live with this cancer :)

**Comment by bradymiller** [comment]
@tywrenn , Gonna bring this in to fix the bugs (not seeing fontawesome icons in these scripts). Gonna have to attack the underlying cancer in the future when have more time :)

**Pull request merged**
