### PR TITLE
Implement C-CDA Care Team Section

### LINKED ISSUE #5513: Implement C-CDA Care Team Section
### Describe the problem
HL7 Rel2.1 Cures moved care team members from under the documentionOf template into it's own sectional template using an organizer to hold team members and stats.

Although the current testing passes as we are currently implementing and the care team section is a MAY include, seems to me this is important to be correctly implemented and used since our CDA is becoming pretty nice.
Bottom line, it just bugs me to not be current and correct. Well worth the $1.99 I'm charging!
### Describe the solution you'd like
Add the section. This can be tricky sometimes when new templates are involved.

### PR DESCRIPTION
**Pull request by sjpadgett**
- various JS template modification
- new careTeamEntryLevel

Fixes #5513 

image

### CODE REVIEW

**Comment by sjpadgett** [comment]
```
<section>
          <templateId root="2.16.840.1.113883.10.20.22.2.500" extension="2019-07-01"/>
          <code code="85847-2" displayName="Patient Care Teams" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"/>
          <title>Patient Care Teams</title>
          <text>
            <table width="100%" border="1">
              <thead>
                <tr>
                  <th>Performer Name</th>
                  <th>Performer Role</th>
                  <th>Performer Since Date</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td ID="careTeam1">Albert Davis</td>
                  <td>Family Medicine</td>
                  <td>2020-06-01</td>
                </tr>
                <tr>
                  <td ID="careTeam2">Tracy Davis</td>
                  <td>Registered Nurse</td>
                  <td>2022-06-20</td>
                </tr>
              </tbody>
            </table>
          </text>
          <entry>
            <organizer classCode="CLUSTER" moodCode="EVN">
              <templateId root="2.16.840.1.113883.10.20.22.4.500" extension="2019-07-01"/>
              <id root="0b745840-3f8e-4a72-9afd-50dcc76c1675"/>
              <code code="85847-2" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Care Team Information"/>
              <statusCode code="active"/>
              <effectiveTime>
                <low value="20220620"/>
              </effectiveTime>
              <component>
                <act classCode="ACT" moodCode="EVN">
                  <templateId root="2.16.840.1.113883.10.20.22.4.500.1" extension="2019-07-01"/>
                  <id root="4b78dba7-2967-4f8b-aab9-9c1ab5fb9be7"/>
                  <code code="85847-2" displayName="Care Team Information" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"/>
                  <statusCode code="active"/>
                  <effectiveTime xsi:type="IVL_TS">
                    <low value="20200601"/>
                  </effectiveTime>
                  <performer typeCode="PRF">
                    <functionCode xmlns="urn:hl7-org:sdtc" code="207Q00000X" displayName="Family Medicine" codeSystem="2.16.840.1.113883.6.101" codeSystemName="NUCC Health Care Provider Taxonomy">
                      <originalText xmlns="urn:hl7-org:v3">
                        <reference value="#teamMember1"/>
                      </originalText>
                    </functionCode>
                    <assignedEntity>
                      <id root="2.16.840.1.113883.4.6" extension="123456789"/>
                      <addr>
                        <streetAddressLine>2472 Rocky place</streetAddressLine>
                        <city>Beaverton</city>
                        <state>OR</state>
                        <postalCode>97006</postalCode>
                        <country>US</country>
                      </addr>
                      <assignedPerson>
                        <name>
                          <family>Davis</family>
                          <given>Albert</given>
                        </name>
                      </assignedPerson>
                    </assignedEntity>
                  </performer>
                </act>
                <act classCode="ACT" moodCode="EVN">
                  <templateId root="2.16.840.1.113883.10.20.22.4.500.1" extension="2019-07-01"/>
                  <id root="c84a43d8-9ca1-4218-b24e-cae64a4ed038"/>
                  <code code="85847-2" displayName="Care Team Information" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"/>
                  <statusCode code="active"/>
                  <effectiveTime xsi:type="IVL_TS">
                    <low value="20220620"/>
                  </effectiveTime>
                  <performer typeCode="PRF">
                    <functionCode xmlns="urn:hl7-org:sdtc" code="163W00000X" displayName="Registered Nurse" codeSystem="2.16.840.1.113883.6.101" codeSystemName="NUCC Health Care Provider Taxonomy">
                      <originalText xmlns="urn:hl7-org:v3">
                        <reference value="#teamMember2"/>
                      </originalText>
                    </functionCode>
                    <assignedEntity>
                      <id root="2.16.840.1.113883.4.6" extension="998877661"/>
                      <addr>
                        <streetAddressLine>2472 Rocky Place</streetAddressLine>
                        <city>Brandon</city>
                        <state>Fl</state>
                        <postalCode>33221</postalCode>
                        <country>US</country>
                      </addr>
                      <assignedPerson>
                        <name>
                          <family>Davis</family>
                          <given>Tracy</given>
                        </name>
                      </assignedPerson>
                    </assignedEntity>
                  </performer>
                </act>
              </component>
            </organizer>
          </entry>
        </section>
```

**Comment by sjpadgett** [comment]
I use the user/providers facility. So care team facility is not needed for ccda.

**Review by adunsulag — COMMENTED** [review]
I didn't see any problems with your code here @sjpadgett.  I will pull down your PR later today and test it out, if that all works then it should be fine to bring in.

**Comment by sjpadgett** [comment]
```> </performer>
>                 </act>
>                 <act classCode="ACT" moodCode="EVN">
```
Need to wait until I figure out why engine won't close the component between act.

**Comment by adunsulag** [comment]
@sjpadgett I'm just working on the date filtering for G9.  Once that's done its just running through all the SLI test scripts.  Once you have this in, and my date filtering for G9 PR goes in, we should branch the code and run all our testing off of that and make sure we haven't missed anything.

**Comment by sjpadgett** [comment]
Works okay for me on windows so go figure!:) Still your solution is appropriate.
I'm now having issue with Alice getting Failed to connect to ccdaservice. Verify your environment is setup correctly by following the instructions in the ccdaservice`s Readme file. Weird for sure.
Let me figure out what's up with Alice and I'll do PR or you can add to yours. Up to you...

**Comment by sjpadgett** [comment]
umm Have you done a sql upgrade because looks like provider_since is not sent by dispatch?

**Comment by adunsulag** [comment]
Let me push out a PR, had to fix a bug in the stylesheet and I have some typos up above.  Though, I'm also failing validation on Alice but its complaining about the careteam section so perhaps I need to fix some more things.

**Pull request merged**
