### PR TITLE
Fix patient portal login and php errors

### PR DESCRIPTION
**Pull request by Wakie87**
`require_once("../library/translation.inc.php");` was being called before globals, which threw an error. Also fixed up php errors.

### CODE REVIEW

**Comment by bradymiller** [comment]
The code changes in patients/get_patient_info.php break RTL (to see this, choose Hebrew and you will note it is no longer RTL); as I recall, Matrix needed to set this before globals.php to get it to work. Here is a commit that will fix this and bring in your php fixes also:
https://github.com/bradymiller/openemr/tree/revised-sql-library-fix-and-portal-php-fixes_2
(note ideal since need to remove the vendor path variable, but guessing will be complicated if try to get RTL working with your changes)
Just let me know if ok with this commit or if want to find another solution.

**Comment by bradymiller** [comment]
Hi Scott,
I committed my revised fix above to get this working in the codebase. Just let me know if you aren't ok with the solution and I'll re-open this PR.
thanks,
-brady

**Comment by mdsupport** [comment]
This thing uses [gritter](https://github.com/jboesch/Gritter) - a 3rd party plugin for jquery.  Any plans to move it public assets to give it visibility?  It or something like it will be a good replacement for reminders, alerts etc...

**Comment by bradymiller** [comment]
Ask and you shall receive :)
https://github.com/openemr/openemr/pull/225
(note it still needs testing)

**Comment by bradymiller** [comment]
@mdsupport,
I just committed the above PR into the codebase (gritter is now at the public assets and the portal uses it). Note it does look like that gritter is no longer an active project though.

**Comment by mdsupport** [comment]
Thx Brady. Gritter is outdated and limited in functionality. But without the public directory there is no way for developer/moderator to realistically avoid incorporating multiple components with same abilities.  We will check for errors in testing.

**Comment by bradymiller** [comment]
Yep, the first goal is to have the public directory function as an aircraft control to store, organize, standardize, and gain some control over the assets.
(btw, the gritter migration(and version upgrade) tested well and I brought it into the codebase yesterday)

**Pull request closed without merging**
