### PR TITLE
fix calender problems when provider name is smaller then the name of  the patient

### PR DESCRIPTION
**Pull request by matrix-drorgo**
…the patient. this css fix it to show the partial patient name with  post string of '...'.

image

please review it thanks.....
Dror G.

### CODE REVIEW

**Comment by bradymiller** [comment]
looks good. I brought this into the codebase. In future, avoid all the white space changes, since confused things. Note it's ok to fix whitespacing, but suggest doing that in a separate commit and then making the code changes in another commit. thanks for the contribution!

**Comment by bradymiller** [comment]
Hi,

See the following forum post for a bug related to this code (the time columns are too wide):
https://sourceforge.net/p/openemr/discussion/202506/thread/123862ba/#d99f

This line is the culprit:
https://github.com/openemr/openemr/blob/master/interface/themes/ajax_calendar.css#L221

Looks like this line was added to make each provider calendar the same width. Was hoping you could figure out a way to do this while avoiding making the time column too wide.

thanks,
-brady

**Comment by eyalvo-matrix** [comment]
Ok I just tried to fix it in another way you can see my changes at 
https://github.com/openemr/openemr/pull/213

**Comment by bradymiller** [comment]
Looks good and just brought in your fix at PR 213.
Still need a fix for the calendar date width :) :
https://github.com/openemr/openemr/issues/235

**Pull request closed without merging**
