### PR TITLE
Add support for apostrophe direction in xl function

### PR DESCRIPTION
**Pull request by oshriromatrix**
Hi, i add support for apostrophe direction.
The RTL languages ​​there is a difference between apostrophe direction.
LTR: `
RTL: '

### CODE REVIEW

**Comment by bradymiller** [comment]
Hi @oshriromatrix ,

Note that the correct apostrophe for LTR is also ' .

We converted all ' and " to the ` character since the ` characters does not break things. The problem with ' and " is that they have the potential to break code in a systemic fashion (if they are not escaped correctly downstream). It was a tough solution to solve, so we decided to just convert them to ` and not worry about it. If your group really needs this, then will be best to have it as a global setting (that is off by default); and if do this, I would recommend ensuring all xl calls in the database are properly escaped.

-brady

**Comment by oshriromatrix** [comment]
Hi, i adding a new global to the system.

**Comment by bradymiller** [comment]
@oshriromatrix ,
I submitted the following PR with an optimized solution for this issue. Let me know if that will work for you:
https://github.com/openemr/openemr/pull/515

**Comment by oshriromatrix** [comment]
Hi is a same code. choose one of the codes, it does not matter

**Comment by bradymiller** [comment]
thanks, I'll bring that 1 in then and close this PR.

**Pull request closed without merging**
