### PR TITLE
add tooltip for care plan form code field and php8 fixes

### LINKED ISSUE #5322: full OID code not displaying
### Describe the bug

some codes are really long so need a tooltip

### To Reproduce
Screenshot from 2022-05-12 22-06-56

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #5322

### CODE REVIEW

**Comment by sjpadgett** [comment]
@stephenwaite This is holding me up. I have development using the CCM and CDA stuff.
Need to bring in sooner than later.

**Comment by stephenwaite** [comment]
if looks okay to you feel free to bring in

**Comment by sjpadgett** [comment]
I still can't figure out why windows doesn't show the undefined warnings. Must be in difference between php compiling between linux and windows.

**Comment by bradymiller** [comment]
2DV-2

**Pull request merged**
