### PR TITLE
Portal Login UI improvements

### PR DESCRIPTION
**Pull request by juggernautsei**
Fixes 7584

#### Short description of what this resolves:
making the UI more appealing 

#### Changes proposed in this pull request:
reduce the size of the logo and reduce the size of the form display

### CODE REVIEW

**Comment by adunsulag** [comment]
@juggernautsei can you post a screenshot of the before and after with this change?  Will col-8 still look good on a mobile phone?

**Comment by juggernautsei** [comment]
Current desktop view before from the demo site.
image

After changes applied.
image

**Comment by sjpadgett** [comment]
I told you I'm refactoring the portal so why are you wasting your time! The way I do it is the way it's going to stay. I'm tired of 100 different opinions on styling so going forward if people don't like the portal styling then don't use!

**Comment by sjpadgett** [comment]
This is the way I had logo originally till everyone started refactoring. logo is fluid and 60% original
image

iphone
image

**Pull request closed without merging**
