### PR TITLE
bug fixes

### PR DESCRIPTION
**Pull request by bradymiller**
several bug fixes

### CODE REVIEW

**Comment by stephenwaite** [comment]
wow, thank you for securing us from the portal fka as portal_two

**Review by sjpadgett — APPROVED** [review]
Looks okay to me Brady. Although i'm not so sure we need all the additional csrf in some places but, who can argue against better security.
Thanks. 
I can't decide if I should change your nickname from eagle eye to the machine!

**Comment by bradymiller** [comment]
sounds good. please bring in if you can (I am not going to have access to
github until late evening).
(eagle eye or machine; tough decision, will need to think about it :) )

**Comment by sjpadgett** [comment]
done, thanks for the hard work.

**Pull request merged**
